<?php $title = 'C.2. PHP File Formatting'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">C.2. PHP File Formatting</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="coding-standard.phtml">Prev</a> </td>
<th width="60%" align="center">Appendix C. Zend Framework Coding Standard for PHP</th>
<td width="20%" align="right"> <a accesskey="n" href="coding-standard.naming-conventions.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="coding-standard.php-file-formatting"></a>C.2. PHP File Formatting</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="coding-standard.php-file-formatting.general"></a>C.2.1. General</h3></div></div></div>
<p>
                For files that contain only <acronym class="acronym">PHP</acronym> code, the closing tag ("?&gt;") is
                never permitted. It is not required by <acronym class="acronym">PHP</acronym>, and omitting it´
                prevents the accidental injection of trailing white space into the response.
            </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Note</th>
</tr>
<tr><td align="left" valign="top"><p>
                    <span class="emphasis"><em>Important</em></span>: Inclusion of arbitrary binary data as permitted
                    by <code class="methodname">__HALT_COMPILER()</code> is prohibited from
                    <acronym class="acronym">PHP</acronym> files in the Zend Framework project or files derived
                    from them. Use of this feature is only permitted for some installation scripts.
                </p></td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="coding-standard.php-file-formatting.indentation"></a>C.2.2. Indentation</h3></div></div></div>
<p>Indentation should consist of 4 spaces. Tabs are not allowed.</p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="coding-standard.php-file-formatting.max-line-length"></a>C.2.3. Maximum Line Length</h3></div></div></div>
<p>
                The target line length is 80 characters. That is to say, Zend Framework developers
                should strive keep each line of their code under 80 characters where possible and
                practical. However, longer lines are acceptable in some circumstances. The maximum
                length of any line of <acronym class="acronym">PHP</acronym> code is 120 characters.
            </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="coding-standard.php-file-formatting.line-termination"></a>C.2.4. Line Termination</h3></div></div></div>
<p>
                Line termination follows the Unix text file convention. Lines must end with a
                single linefeed (LF) character. Linefeed characters are represented as ordinal 10,
                or hexadecimal 0x0A.
            </p>
<p>
                Note: Do not use carriage returns (CR) as is the convention in Apple OS's (0x0D) or
                the carriage return - linefeed combination (<acronym class="acronym">CRLF</acronym>) as is standard
                for the Windows OS (0x0D, 0x0A).
            </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="coding-standard.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="coding-standard.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="coding-standard.naming-conventions.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Appendix C. Zend Framework Coding Standard for PHP </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> C.3. Naming Conventions</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
