<?php $title = 'Appendix C. Zend Framework Coding Standard for PHP'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Appendix C. Zend Framework Coding Standard for PHP</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="migration.06.phtml">Prev</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> <a accesskey="n" href="coding-standard.php-file-formatting.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="appendix">
<div class="titlepage"><div><div><h1 class="title">
<a name="coding-standard"></a>Appendix C. Zend Framework Coding Standard for PHP</h1></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="coding-standard.phtml#coding-standard.overview">C.1. Overview</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="coding-standard.phtml#coding-standard.overview.scope">C.1.1. Scope</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.phtml#coding-standard.overview.goals">C.1.2. Goals</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="coding-standard.php-file-formatting.phtml">C.2. PHP File Formatting</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.general">C.2.1. General</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.indentation">C.2.2. Indentation</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.max-line-length">C.2.3. Maximum Line Length</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.line-termination">C.2.4. Line Termination</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="coding-standard.naming-conventions.phtml">C.3. Naming Conventions</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.classes">C.3.1. Classes</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.abstracts">C.3.2. Abstract Classes</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.interfaces">C.3.3. Interfaces</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.filenames">C.3.4. Filenames</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.functions-and-methods">C.3.5. Functions and Methods</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.variables">C.3.6. Variables</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.constants">C.3.7. Constants</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="coding-standard.coding-style.phtml">C.4. Coding Style</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.php-code-demarcation">C.4.1. PHP Code Demarcation</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings">C.4.2. Strings</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings.literals">C.4.2.1. String Literals</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings.literals-containing-apostrophes">C.4.2.2. String Literals Containing Apostrophes</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings.variable-substitution">C.4.2.3. Variable Substitution</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings.string-concatenation">C.4.2.4. String Concatenation</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.arrays">C.4.3. Arrays</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.arrays.numerically-indexed">C.4.3.1. Numerically Indexed Arrays</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.arrays.associative">C.4.3.2. Associative Arrays</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.classes">C.4.4. Classes</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.classes.declaration">C.4.4.1. Class Declaration</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.classes.member-variables">C.4.4.2. Class Member Variables</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.functions-and-methods">C.4.5. Functions and Methods</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.functions-and-methods.declaration">C.4.5.1. Function and Method Declaration</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.functions-and-methods.usage">C.4.5.2. Function and Method Usage</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.control-statements">C.4.6. Control Statements</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.control-statements.if-else-elseif">C.4.6.1. If/Else/Elseif</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.coding-style.control-statements.switch">C.4.6.2. Switch</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation">C.4.7. Inline Documentation</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation.documentation-format">C.4.7.1. Documentation Format</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation.files">C.4.7.2. Files</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation.classes">C.4.7.3. Classes</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation.functions">C.4.7.4. Functions</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="coding-standard.overview"></a>C.1. Overview</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="coding-standard.overview.scope"></a>C.1.1. Scope</h3></div></div></div>
<p>
                This document provides guidelines for code formatting and documentation to
                individuals and teams contributing to Zend Framework. Many developers using Zend
                Framework have also found these coding standards useful because their code's style
                remains consistent with all Zend Framework code. It is also worth noting that it
                requires significant effort to fully specify coding standards.
            </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Note</th>
</tr>
<tr><td align="left" valign="top"><p>
                    Sometimes developers consider the establishment of a standard more important
                    than what that standard actually suggests at the most detailed level of
                    design. The guidelines in Zend Framework's coding standards capture practices
                    that have worked well on the Zend Framework project. You may modify these
                    standards or use them as is in accordance with the terms of our <a class="ulink" href="http://framework.zend.com/license" target="_top">license</a>.
                </p></td></tr>
</table></div>
<p>
                Topics covered in Zend Framework's coding standards include:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p><acronym class="acronym">PHP</acronym> File Formatting</p></li>
<li class="listitem"><p>Naming Conventions</p></li>
<li class="listitem"><p>Coding Style</p></li>
<li class="listitem"><p>Inline Documentation</p></li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="coding-standard.overview.goals"></a>C.1.2. Goals</h3></div></div></div>
<p>
                Coding standards are important in any development project, but they are particularly
                important when many developers are working on the same project. Coding standards
                help ensure that the code is high quality, has fewer bugs, and can be easily
                maintained.
            </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="migration.06.phtml">Prev</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> <a accesskey="n" href="coding-standard.php-file-formatting.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">B.11. Zend Framework 0.6 </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> C.2. PHP File Formatting</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
