<?php $title = 'D.2. Documentation File Formatting'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">D.2. Documentation File Formatting</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="doc-standard.phtml">Prev</a> </td>
<th width="60%" align="center">Appendix D. Zend Framework Documentation Standard</th>
<td width="20%" align="right"> <a accesskey="n" href="doc-standard.recommendations.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="doc-standard.file-formatting"></a>D.2. Documentation File Formatting</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.xml-tags"></a>D.2.1. XML Tags</h3></div></div></div>
<p>
                Each manual file must include the following <acronym class="acronym">XML</acronym> declarations at
                the top of the file:
            </p>
<pre class="programlisting">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;!-- Reviewed: no --&gt;
</pre>
<p>
                <acronym class="acronym">XML</acronym> files from translated languages must also include a revision
                tag containing the revision of the corresponding English-language file the
                translation was based on.
            </p>
<pre class="programlisting">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;!-- EN-Revision: 14978 --&gt;
&lt;!-- Reviewed: no --&gt;
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.max-line-length"></a>D.2.2. Maximum Line Length</h3></div></div></div>
<p>
                The maximum line length, including tags, attributes, and indentation, is not to
                exceed 100 characters. There is only one exception to this rule: attribute and value
                pairs are allowed to exceed the 100 chars as they are not allowed to be separated.
            </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.indentation"></a>D.2.3. Indentation</h3></div></div></div>
<p>Indentation should consist of 4 spaces. Tabs are not allowed.</p>
<p>Tags which are at the same level must have the same indentation.</p>
<pre class="programlisting">
&lt;sect1&gt;
&lt;/sect1&gt;

&lt;sect1&gt;
&lt;/sect1&gt;
</pre>
<p>
                Tags which are one level under the previous tag must be indented with 4 additional
                spaces.
            </p>
<pre class="programlisting">
&lt;sect1&gt;
    &lt;sect2&gt;
    &lt;/sect2&gt;
&lt;/sect1&gt;
</pre>
<p>
                Multiple block tags within the same line are not allowed; multiple inline tags are
                allowed, however.
            </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED: --&gt;
&lt;sect1&gt;&lt;sect2&gt;
&lt;/sect2&gt;&lt;/sect1&gt;

&lt;!-- ALLOWED --&gt;
&lt;para&gt;
    &lt;classname&gt;Zend_Magic&lt;/classname&gt; does not exist. &lt;classname&gt;Zend_Acl&lt;/classname&gt; does.
&lt;/para&gt;
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.line-termination"></a>D.2.4. Line Termination</h3></div></div></div>
<p>
                Line termination follows the Unix text file convention. Lines must end with a
                single linefeed (LF) character. Linefeed characters are represented as ordinal 10,
                or hexadecimal 0x0A.
            </p>
<p>
                Note: Do not use carriage returns (<acronym class="acronym">CR</acronym>) as is the convention in
                Apple OS's (0x0D) or the carriage return - linefeed combination
                (<acronym class="acronym">CRLF</acronym>) as is standard for the Windows OS (0x0D, 0x0A).
            </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.empty-tags"></a>D.2.5. Empty tags</h3></div></div></div>
<p>
                Empty tags are not allowed; all tags must contain text or child tags.
            </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
&lt;para&gt;
    Some text. &lt;link&gt;&lt;/link&gt;
&lt;/para&gt;

&lt;para&gt;
&lt;/para&gt;
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.whitespace"></a>D.2.6. Usage of whitespace within documents</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.whitespace.trailing"></a>D.2.6.1. Whitespace within tags</h4></div></div></div>
<p>
                    Opening block tags should have no whitespace immediately following them other
                    than line breaks (and indentation on the following line).
                </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
&lt;sect1&gt;WHITESPACE
&lt;/sect1&gt;
</pre>
<p>
                    Opening inline tags should have no whitespace immediately following them.
                </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
This is the class &lt;classname&gt; Zend_Class&lt;/classname&gt;.

&lt;!-- OK --&gt;
This is the class &lt;classname&gt;Zend_Class&lt;/classname&gt;.
</pre>
<p>
                    Closing block tags may be preceded by whitespace equivalent to the current
                    indentation level, but no more than that amount.
                </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
    &lt;sect1&gt;
     &lt;/sect1&gt;

&lt;!-- OK --&gt;
    &lt;sect1&gt;
    &lt;/sect1&gt;
</pre>
<p>
                    Closing inline tags must not be preceded by any whitespace.
                </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
This is the class &lt;classname&gt;Zend_Class &lt;/classname&gt;

&lt;!-- OK --&gt;
This is the class &lt;classname&gt;Zend_Class&lt;/classname&gt;
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.whitespace.multiple-line-breaks"></a>D.2.6.2. Multiple line breaks</h4></div></div></div>
<p>
                    Multiple line breaks within or between tags are not allowed.
                </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
&lt;para&gt;
    Some text...

    ... and more text
&lt;/para&gt;


&lt;para&gt;
    Another paragraph.
&lt;/para&gt;

&lt;!-- OK --&gt;
&lt;para&gt;
    Some text...
    ... and more text
&lt;/para&gt;

&lt;para&gt;
    Another paragraph.
&lt;/para&gt;
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.whitespace.tag-separation"></a>D.2.6.3. Separation between tags</h4></div></div></div>
<p>
                    Tags at the same level must be separated by an empty line to improve
                    readability.
                </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
&lt;para&gt;
    Some text...
&lt;/para&gt;
&lt;para&gt;
    More text...
&lt;/para&gt;

&lt;!-- OK --&gt;
&lt;para&gt;
    Some text...
&lt;/para&gt;

&lt;para&gt;
    More text...
&lt;/para&gt;
</pre>
<p>
                    The first child tag should open directly below its parent, with no empty line
                    between them; the last child tag should close directly before the closing tag of
                    its parent.
                </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
&lt;sect1&gt;

    &lt;sect2&gt;
    &lt;/sect2&gt;

    &lt;sect2&gt;
    &lt;/sect2&gt;

    &lt;sect2&gt;
    &lt;/sect2&gt;

&lt;/sect1&gt;

&lt;!-- OK --&gt;
&lt;sect1&gt;
    &lt;sect2&gt;
    &lt;/sect2&gt;

    &lt;sect2&gt;
    &lt;/sect2&gt;

    &lt;sect2&gt;
    &lt;/sect2&gt;
&lt;/sect1&gt;
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.program-listing"></a>D.2.7. Program Listings</h3></div></div></div>
<p>
                The opening <span class="emphasis"><em>&lt;programlisting&gt;</em></span> tag must indicate the
                appropriate "language" attribute and be indented at the same level as its sibling
                blocks.
            </p>
<pre class="programlisting">
&lt;para&gt;Sibling paragraph.&lt;/para&gt;

&lt;programlisting language="php"&gt;&lt;![CDATA[
</pre>
<p>
                <acronym class="acronym">CDATA</acronym> should be used around all program listings.
            </p>
<p>
                <span class="emphasis"><em>&lt;programlisting&gt;</em></span> sections must not add linebreaks or
                whitespace at the beginning or end of the section, as these are then represented in
                the final output.
            </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
&lt;programlisting language="php"&gt;&lt;![CDATA[

$render = "xxx";

]]&gt;&lt;/programlisting&gt;

&lt;!-- OK --&gt;
&lt;programlisting language="php"&gt;&lt;![CDATA[
$render = "xxx";
]]&gt;&lt;/programlisting&gt;
</pre>
<p>
                Ending <acronym class="acronym">CDATA</acronym> and <span class="emphasis"><em>&lt;programlisting&gt;</em></span>
                tags should be on the same line, without any indentation.
            </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
    &lt;programlisting language="php"&gt;&lt;![CDATA[
$render = "xxx";
]]&gt;
    &lt;/programlisting&gt;

&lt;!-- NOT ALLOWED --&gt;
    &lt;programlisting language="php"&gt;&lt;![CDATA[
$render = "xxx";
    ]]&gt;&lt;/programlisting&gt;

&lt;!-- OK --&gt;
    &lt;programlisting language="php"&gt;&lt;![CDATA[
$render = "xxx";
]]&gt;&lt;/programlisting&gt;
</pre>
<p>
                The <span class="emphasis"><em>&lt;programlisting&gt;</em></span> tag should contain the "language"
                attribute with a value appropriate to the contents of the program listing. Typical
                values include "css", "html", "ini", "javascript", "php", "text", and "xml".
            </p>
<pre class="programlisting">
&lt;!-- PHP --&gt;
&lt;programlisting language="php"&gt;&lt;![CDATA[

&lt;!-- Javascript --&gt;
&lt;programlisting language="javascript"&gt;&lt;![CDATA[

&lt;!-- XML --&gt;
&lt;programlisting language="xml"&gt;&lt;![CDATA[
</pre>
<p>
                For program listings containing only <acronym class="acronym">PHP</acronym> code,
                <acronym class="acronym">PHP</acronym> tags (e.g., "&lt;?php", "?&gt;") are not required, and
                should not be used. They simply clutter the narrative, and are implied by the use
                of the <span class="emphasis"><em>&lt;programlisting&gt;</em></span> tag.
            </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
&lt;programlisting language="php"&lt;![CDATA[&lt;?php
    // ...
?&gt;]]&gt;&lt;/programlisting&gt;

&lt;programlisting language="php"&lt;![CDATA[
&lt;?php
    // ...
?&gt;
]]&gt;&lt;/programlisting&gt;
</pre>
<p>
                Line lengths within program listings should follow the <a class="link" href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.max-line-length" title="C.2.3. Maximum Line Length">coding standards
                recommendations</a>.
            </p>
<p>
                Refrain from using <code class="methodname">require_once()</code>,
                <code class="methodname">require()</code>, <code class="methodname">include_once()</code>, and
                <code class="methodname">include()</code> calls within <acronym class="acronym">PHP</acronym> listings.
                They simply clutter the narrative, and are largely obviated when using an
                autoloader. Use them only when they are essential to the example.
            </p>
<div class="note"><table border="0" summary="Note: Never use short tags">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Never use short tags</th>
</tr>
<tr><td align="left" valign="top"><p>
                    Short tags (e.g., "&lt;?", "&lt;?=") should never be used within
                    <span class="emphasis"><em>programlisting</em></span> or the narrative of a document.
                </p></td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.inline-tags"></a>D.2.8. Notes on specific inline tags</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.inline-tags.classname"></a>D.2.8.1. classname</h4></div></div></div>
<p>
                    The tag <span class="emphasis"><em>&lt;classname&gt;</em></span> must be used each time a class
                    name is represented by itself; it should not be used when combined with a
                    method name, variable name, or constant, and no other content is allowed within
                    the tag.
                </p>
<pre class="programlisting">
&lt;para&gt;
    The class &lt;classname&gt;Zend_Class&lt;/classname&gt;.
&lt;/para&gt;
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.inline-tags.varname"></a>D.2.8.2. varname</h4></div></div></div>
<p>
                    Variables must be wrapped in the <span class="emphasis"><em>&lt;varname&gt;</em></span> tag.
                    Variables must be written using the "$" sigil. No other content is allowed
                    within this tag, unless a class name is used, which indicates a class variable.
                </p>
<pre class="programlisting">
&lt;para&gt;
    The variable &lt;varname&gt;$var&lt;/varname&gt; and the class variable
    &lt;varname&gt;Zend_Class::$var&lt;/varname&gt;.
&lt;/para&gt;
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.inline-tags.methodname"></a>D.2.8.3. methodname</h4></div></div></div>
<p>
                    Methods must be wrapped in the <span class="emphasis"><em>&lt;methodname&gt;</em></span> tag.
                    Methods must either include the full method signature or at the least a pair of
                    closing parentheses (e.g., "()"). No other content is allowed within this tag,
                    unless a class name is used, which indicates a class method.
                </p>
<pre class="programlisting">
&lt;para&gt;
    The method &lt;methodname&gt;foo()&lt;/methodname&gt; and the class method
    &lt;methodname&gt;Zend_Class::foo()&lt;/methodname&gt;. A method with a full signature:
    &lt;methodname&gt;foo($bar, $baz)&lt;/methodname&gt;
&lt;/para&gt;
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.inline-tags.constant"></a>D.2.8.4. constant</h4></div></div></div>
<p>
                    Use the <span class="emphasis"><em>&lt;constant&gt;</em></span> tag when denoting constants.
                    Constants must be written in <acronym class="acronym">UPPERCASE</acronym>. No other content is
                    allowed within this tag, unless a class name is used, which indicates a class
                    constant.
                </p>
<pre class="programlisting">
&lt;para&gt;
    The constant &lt;constant&gt;FOO&lt;/constant&gt; and the class constant
    &lt;constant&gt;Zend_Class::FOO&lt;/constant&gt;.
&lt;/para&gt;
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.inline-tags.filename"></a>D.2.8.5. filename</h4></div></div></div>
<p>
                    Filenames and paths must be wrapped in the
                    <span class="emphasis"><em>&lt;filename&gt;</em></span> tag. No other content is allowed in this
                    tag.
                </p>
<pre class="programlisting">
&lt;para&gt;
    The filename &lt;filename&gt;application/Bootstrap.php&lt;/filename&gt;.
&lt;/para&gt;
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.inline-tags.command"></a>D.2.8.6. command</h4></div></div></div>
<p>
                    Commands, shell scripts, and program calls must be wrapped in the
                    <span class="emphasis"><em>&lt;command&gt;</em></span> tag. If the command includes arguments,
                    these should also be included within the tag.
                </p>
<pre class="programlisting">
&lt;para&gt;
    Execute &lt;command&gt;zf.sh create project&lt;/command&gt;.
&lt;/para&gt;
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.inline-tags.code"></a>D.2.8.7. code</h4></div></div></div>
<p>
                    Usage of the <span class="emphasis"><em>&lt;code&gt;</em></span> tag is discouraged, in favor of
                    the other inline tasks discussed previously.
                </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.file-formatting.block-tags"></a>D.2.9. Notes on specific block tags</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="doc-standard.file-formatting.block-tags.title"></a>D.2.9.1. title</h4></div></div></div>
<p>
                    The <span class="emphasis"><em>&lt;title&gt;</em></span> tag is not allowed to hold other tags.
                </p>
<pre class="programlisting">
&lt;!-- NOT ALLOWED --&gt;
&lt;title&gt;Using &lt;classname&gt;Zend_Class&lt;/classname&gt;&lt;/title&gt;

&lt;!-- OK --&gt;
&lt;title&gt;Using Zend_Class&lt;/title&gt;
</pre>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="doc-standard.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="doc-standard.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="doc-standard.recommendations.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Appendix D. Zend Framework Documentation Standard </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> D.3. Recommendations</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
