<?php $title = 'Chapter 9. Getting Started with Zend_Session, Zend_Auth, and Zend_Acl'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 9. Getting Started with Zend_Session, Zend_Auth, and Zend_Acl</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.form.decorators.conclusion.phtml">Prev</a> </td>
<th width="60%" align="center">Part II. Learning Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.multiuser.sessions.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="learning.multiuser"></a>Chapter 9. Getting Started with Zend_Session, Zend_Auth, and Zend_Acl</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="learning.multiuser.phtml#learning.multiuser.intro">9.1. Building Multi-User Applications With Zend Framework</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="learning.multiuser.phtml#learning.multiuser.intro.zf">9.1.1. Zend Framework</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="learning.multiuser.sessions.phtml">9.2. Managing User Sessions In ZF</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.multiuser.sessions.phtml#learning.multiuser.sessions.intro">9.2.1. Introduction to Sessions</a></span></dt>
<dt><span class="sect2"><a href="learning.multiuser.sessions.phtml#learning.multiuser.sessions.basic-usage">9.2.2. Basic Usage of Zend_Session</a></span></dt>
<dt><span class="sect2"><a href="learning.multiuser.sessions.phtml#learning.multiuser.sessions.advanced-usage">9.2.3. Advanced Usage of Zend_Session</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.multiuser.authentication.phtml">9.3. Authenticating Users in Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.multiuser.authentication.phtml#learning.multiuser.authentication.intro">9.3.1. Introduction to Authentication</a></span></dt>
<dt><span class="sect2"><a href="learning.multiuser.authentication.phtml#learning.multiuser.authentication.basic-usage">9.3.2. Basic Usage of Zend_Auth</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.multiuser.authorization.phtml">9.4. Building an Authorization System in Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.multiuser.authorization.phtml#learning.multiuser.authorization.intro">9.4.1. Introduction to Authorization</a></span></dt>
<dt><span class="sect2"><a href="learning.multiuser.authorization.phtml#learning.multiuser.authorization.basic-usage">9.4.2. Basic Usage of Zend_Acl</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.multiuser.intro"></a>9.1. Building Multi-User Applications With Zend Framework</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="learning.multiuser.intro.zf"></a>9.1.1. Zend Framework</h3></div></div></div>
<p>
            When the original "web" was created, it was designed to be a publishing platform
            for predominantly static content. As demand for content on the web grew, as did
            the number of consumers on the internet for web content, the demand for using the
            web as an application platform also grew. Since the web is inherently good at
            delivering a simultaneous experience to many consumers from a single location,
            it makes it an ideal environment for building dynamically driven, multi-user,
            and more commonly today, social systems.
        </p>
<p>
            <acronym class="acronym">HTTP</acronym> is the protocol of the web: a stateless, typically short
            lived, request and response protocol. This protocol was designed this way because
            the original intent of the web was to serve or publish static content. It is this
            very design that has made the web as immensely successful as it is. It is also
            exactly this design that brings new concerns to developers who wish to use the
            web as an application platform.
        </p>
<p>
            These concerns and responsibilities can effectively be summed up by three questions:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    How do you distinguish one application consumer from another?
                </p></li>
<li class="listitem"><p>
                    How do you identify a consumer as authentic?
                </p></li>
<li class="listitem"><p>
                    How do you control what a consumer has access to?
                </p></li>
</ul></div>
<div class="note"><table border="0" summary="Note: Consumer Vs. User">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Consumer Vs. User</th>
</tr>
<tr><td align="left" valign="top"><p>
                Notice we use the term "consumer" instead of person. Increasingly, web applications
                are becoming service driven. This means that not only are real people ("users") with
                real web browsers consuming and using your application, but also other web
                applications through machine service technologies such as <acronym class="acronym">REST</acronym>,
                <acronym class="acronym">SOAP</acronym>, and <acronym class="acronym">XML-RPC</acronym>. In this respect,
                people, as well as other consuming applications, should all be treated in same with
                regard to the concerns outlined above.
            </p></td></tr>
</table></div>
<p>
            In the following chapters, we'll take a look at these common problems relating to
            authentication and authorization in detail. We will discover how 3 main components:
            <code class="classname">Zend_Session</code>, <code class="classname">Zend_Auth</code>, and
            <code class="classname">Zend_Acl</code>; provide an out-of-the-box solution as well as the
            extension points each have that will cater to a more customized solution.
        </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.form.decorators.conclusion.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.multiuser.sessions.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">8.6. Conclusion </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 9.2. Managing User Sessions In ZF</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
