<?php $title = 'Chapter 8. Understanding and Using Zend Form Decorators'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 8. Understanding and Using Zend Form Decorators</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.view.placeholders.conclusion.phtml">Prev</a> </td>
<th width="60%" align="center">Part II. Learning Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.form.decorators.simplest.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="learning.form.decorators"></a>Chapter 8. Understanding and Using Zend Form Decorators</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="learning.form.decorators.phtml#learning.form.decorators.intro">8.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.simplest.phtml">8.2. Decorator Basics</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.form.decorators.simplest.phtml#learning.form.decorators.simplest.decorator-overview">8.2.1. Overview of the Decorator Pattern</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.simplest.phtml#learning.form.decorators.simplest.first-decorator">8.2.2. Creating Your First Decorator</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.form.decorators.layering.phtml">8.3. Layering Decorators</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.individual.phtml">8.4. Rendering Individual Decorators</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.composite.phtml">8.5. Creating and Rendering Composite Elements</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.element">8.5.1. The Element</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.decorator">8.5.2. The Decorator</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.conclusion">8.5.3. Conclusion</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.form.decorators.conclusion.phtml">8.6. Conclusion</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.form.decorators.intro"></a>8.1. Introduction</h2></div></div></div>
<p>
        <a class="link" href="zend.form.phtml" title="Chapter 36. Zend_Form">Zend_Form</a> utilizes the <span class="emphasis"><em>decorator</em></span>
        pattern in order to render elements and forms. Unlike the classic <a class="ulink" href="http://en.wikipedia.org/wiki/Decorator_pattern" target="_top">decorator pattern</a>, in
        which you pass an object to a wrapping class, decorators in <code class="classname">Zend_Form</code>
        implement a <a class="ulink" href="http://en.wikipedia.org/wiki/Strategy_pattern" target="_top">strategy
            pattern</a>, and utilize the metadata contained in an element or form in order to
        create a representation of it
    </p>
<p>
        Don't let the terminology scare you away, however; at heart, decorators in
        <code class="classname">Zend_Form</code> are not terribly difficult, and the mini-tutorials that
        follow should help you along the way. They will guide you through the basics of decoration,
        all the way to creating decorators for composite elements.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.view.placeholders.conclusion.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.form.decorators.simplest.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">7.4. View Placeholders: Conclusion </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 8.2. Decorator Basics</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
