<?php $title = '10.3. Index Opening and Creation'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">10.3. Index Opening and Creation</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.lucene.index-structure.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 10. Getting Started with Zend_Search_Lucene</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.lucene.indexing.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.lucene.index-opening"></a>10.3. Index Opening and Creation</h2></div></div></div>
<p>
        All index operations (e.g., creating a new index, adding a document to the index, deleting a
        document, searching through the index) need an index object. One can be obtained using one
        of the following two methods.
    </p>
<div class="example">
<a name="learning.lucene.index-opening.creation"></a><p class="title"><b>Example 10.1. Lucene Index Creation</b></p>
<div class="example-contents"><pre class="programlisting">
$index = Zend_Search_Lucene::create($indexPath);
</pre></div>
</div>
<br class="example-break"><div class="example">
<a name="learning.lucene.index-opening.opening"></a><p class="title"><b>Example 10.2. Lucene Index Opening</b></p>
<div class="example-contents"><pre class="programlisting">
$index = Zend_Search_Lucene::open($indexPath);
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.lucene.index-structure.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.lucene.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.lucene.indexing.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">10.2. Lucene Index Structure </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 10.4. Indexing</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
