<?php $title = '11.4. Putting it all Together'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">11.4. Putting it all Together</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.paginator.control.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 11. Getting Started with Zend_Paginator</th>
<td width="20%" align="right"> <a accesskey="n" href="reference.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.paginator.together"></a>11.4. Putting it all Together</h2></div></div></div>
<p>
        You have seen how to create a Paginator object, how to render the items on the current page,
        and how to render a navigation element to browse through your pages. In this section you
        will see how Paginator fits in with the rest of your MVC application.
    </p>
<p>
        In the following examples we will ignore the best practice implementation of using a Service
        Layer to keep the example simple and easier to understand. Once you get familiar with using
        Service Layers, it should be easy to see how Paginator can fit in with the best practice
        approach.
    </p>
<p>
        Lets start with the controller. The sample application is simple, and we'll just put
        everything in the IndexController and the IndexAction. Again, this is for demonstration
        purposes only. A real application should not use controllers in this manner.
    </p>
<pre class="programlisting">
class IndexController extends Zend_Controller_Action
{
    public function indexAction()
    {
        // Setup pagination control view script. See the pagation control tutorial page
        // for more information about this view script.
        Zend_View_Helper_PaginationControl::setDefaultViewPartial('controls.phtml');

        // Fetch an already instantiated database connection from the registry
        $db = Zend_Registry::get('db');

        // Create a select object which fetches blog posts, sorted decending by date of creation
        $select = $db-&gt;select()-&gt;from('posts')-&gt;sort('date_created DESC');

        // Create a Paginator for the blog posts query
        $paginator = Zend_Paginator::factory($select);

        // Read the current page number from the request. Default to 1 if no explicit page number is provided.
        $paginator-&gt;setCurrentPageNumber($this-&gt;_getParam('page', 1));

        // Assign the Paginator object to the view
        $this-&gt;view-&gt;paginator = $paginator;
    }
}
</pre>
<p>
        The following view script is the index.phtml view script for the IndexController's
        indexAction. The view script can be kept simple. We're assuming the use of the default
        ScrollingStyle.
    </p>
<pre class="programlisting">
&lt;ul&gt;
&lt;?php
// Render each the title of each post for the current page in a list-item
foreach ($this-&gt;paginator as $item) {
    echo '&lt;li&gt;' . $item-&gt;title . '&lt;/li&gt;';
}
?&gt;
&lt;/ul&gt;
&lt;?php echo $this-&gt;paginator; ?&gt;
</pre>
<p>
        Now navigate to your project's index and see Paginator in action. What we have discussed
        in this tutorial is just the tip of the iceberg. The reference manual and
        <acronym class="acronym">API</acronym> documentation can tell you more about what you can do with
        <code class="classname">Zend_Paginator</code>.
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.paginator.control.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.paginator.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="reference.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">11.3. Pagination Control and ScrollingStyles </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Part III. Zend Framework Reference</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
