<?php $title = '10.2. Lucene Index Structure'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">10.2. Lucene Index Structure</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.lucene.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 10. Getting Started with Zend_Search_Lucene</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.lucene.index-opening.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.lucene.index-structure"></a>10.2. Lucene Index Structure</h2></div></div></div>
<p>
        In order to fully utilize <code class="classname">Zend_Search_Lucene</code>'s capabilities with
        maximum performance, you need to understand it's internal index structure.
    </p>
<p>
        An <span class="emphasis"><em>index</em></span> is stored as a set of files within a single directory.
    </p>
<p>
        An <span class="emphasis"><em>index</em></span> consists of any number of independent
        <span class="emphasis"><em>segments</em></span> which store information about a subset of indexed documents.
        Each <span class="emphasis"><em>segment</em></span> has its own <span class="emphasis"><em>terms dictionary</em></span>, terms
        dictionary index, and document storage (stored field values) <a href="#ftn.id3318" class="footnote" name="id3318"><sup class="footnote">[3]</sup></a>. All segment data is stored in
        <code class="filename">_xxxxx.cfs</code> files, where <span class="emphasis"><em>xxxxx</em></span> is a segment name.
    </p>
<p>
        Once an index segment file is created, it can't be updated. New documents are added to new
        segments. Deleted documents are only marked as deleted in an optional
        <code class="filename">&lt;segmentname&gt;.del</code> file.
    </p>
<p>
        Document updating is performed as separate delete and add operations, even though it's done
        using an <code class="methodname">update()</code> <acronym class="acronym">API</acronym> call
        <a href="#ftn.id3328" class="footnote" name="id3328"><sup class="footnote">[4]</sup></a>.
        This simplifies adding new documents, and allows updating concurrently with search
        operations.
    </p>
<p>
        On the other hand, using several segments (one document per segment as a borderline case)
        increases search time:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                retrieving a term from a dictionary is performed for each segment;
            </p></li>
<li class="listitem"><p>
                the terms dictionary index is pre-loaded for each segment (this process takes the
                most search time for simple queries, and it also requires additional memory).
            </p></li>
</ul></div>
<p>
        If the terms dictionary reaches a saturation point, then search through one segment is
        <span class="emphasis"><em>N</em></span> times faster than search through <span class="emphasis"><em>N</em></span> segments
        in most cases.
    </p>
<p>
        <span class="emphasis"><em>Index optimization</em></span> merges two or more segments into a single new one. A
        new segment is added to the index segments list, and old segments are excluded.
    </p>
<p>
        Segment list updates are performed as an atomic operation. This gives the ability of
        concurrently adding new documents, performing index optimization, and searching through the
        index.
    </p>
<p>
        Index auto-optimization is performed after each new segment generation. It merges sets of
        the smallest segments into larger segments, and larger segments into even larger segments,
        if we have enough segments to merge.
    </p>
<p>
        Index auto-optimization is controlled by three options:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <span class="emphasis"><em>MaxBufferedDocs</em></span> (the minimal number of documents required
                before the buffered in-memory documents are written into a new segment);
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>MaxMergeDocs</em></span> (the largest number of documents ever merged by
                an optimization operation); and
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>MergeFactor</em></span> (which determines how often segment indices are
                merged by auto-optimization operations).
            </p></li>
</ul></div>
<p>
        If we add one document per script execution, then <span class="emphasis"><em>MaxBufferedDocs</em></span> is
        actually not used (only one new segment with only one document is created at the end of
        script execution, at which time the auto-optimization process starts).
    </p>
<div class="footnotes">
<br><hr style="width:100; text-align:left;margin-left: 0">
<div id="ftn.id3318" class="footnote"><p><a href="#id3318" class="para"><sup class="para">[3] </sup></a>Starting with
                Lucene 2.3, document storage files can be shared between segments; however,
                <code class="classname">Zend_Search_Lucene</code> doesn't use this
                capability</p></div>
<div id="ftn.id3328" class="footnote"><p><a href="#id3328" class="para"><sup class="para">[4] </sup></a>This call is provided only by Java Lucene now, but it's planned to extend
            the <code class="classname">Zend_Search_Lucene</code> <acronym class="acronym">API</acronym> with similar
            functionality</p></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.lucene.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.lucene.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.lucene.index-opening.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Chapter 10. Getting Started with Zend_Search_Lucene </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 10.3. Index Opening and Creation</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
