<?php $title = 'Appendix B. Zend Framework Migration Notes'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Appendix B. Zend Framework Migration Notes</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="requirements.phtml">Prev</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> <a accesskey="n" href="migration.110.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="appendix">
<div class="titlepage"><div><div><h1 class="title">
<a name="migration"></a>Appendix B. Zend Framework Migration Notes</h1></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="migration.phtml#migration.112">B.1. Zend Framework 1.12</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.phtml#migration.12.zend.view.helper.navigation">B.1.1. Zend_View_Helper_Navigation</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="migration.110.phtml">B.2. Zend Framework 1.10</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.controller.front">B.2.1. Zend_Controller_Front</a></span></dt>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.feed.reader">B.2.2. Zend_Feed_Reader</a></span></dt>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.file.transfer">B.2.3. Zend_File_Transfer</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.file.transfer.files">B.2.3.1. Security change</a></span></dt>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.file.transfer.count">B.2.3.2. Count validation</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.filter.html-entities">B.2.4. Zend_Filter_HtmlEntities</a></span></dt>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.filter.strip-tags">B.2.5. Zend_Filter_StripTags</a></span></dt>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.translate">B.2.6. Zend_Translate</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.translate.xliff">B.2.6.1. Xliff adapter</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.validate">B.2.7. Zend_Validate</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.validate.selfwritten">B.2.7.1. Self written validators</a></span></dt>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.validate.datevalidator">B.2.7.2. Simplification in date validator</a></span></dt>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.validate.barcodevalidator">B.2.7.3. Fixes in Alpha, Alnum and Barcode validator</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.19.phtml">B.3. Zend Framework 1.9</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.file.transfer">B.3.1. Zend_File_Transfer</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.19.phtml#migration.19.zend.file.transfer.mimetype">B.3.1.1. MimeType validation</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.filter">B.3.2. Zend_Filter</a></span></dt>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.http.client">B.3.3. Zend_Http_Client</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.zend.http.client.fileuploadsarray">B.3.3.1. Changes to internal uploaded file information storage</a></span></dt>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.zend.http.client.getparamsrecursize">B.3.3.2. Deprecation of Zend_Http_Client::_getParametersRecursive()</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.locale">B.3.4. Zend_Locale</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.19.phtml#migration.19.zend.locale.deprecated">B.3.4.1. Deprecated methods</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.view.helper.navigation">B.3.5. Zend_View_Helper_Navigation</a></span></dt>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.security">B.3.6. Security fixes as with 1.9.7</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.security.zend.dojo.editor">B.3.6.1. Zend_Dojo_View_Helper_Editor</a></span></dt>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.security.zend.filter.html-entities">B.3.6.2. Zend_Filter_HtmlEntities</a></span></dt>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.security.zend.filter.strip-tags">B.3.6.3. Zend_Filter_StripTags</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.18.phtml">B.4. Zend Framework 1.8</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.18.phtml#migration.18.zend.controller">B.4.1. Zend_Controller</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.18.phtml#migration.18.zend.controller.router">B.4.1.1. Standard Route Changes</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.18.phtml#migration.18.zend.locale">B.4.2. Zend_Locale</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.18.phtml#migration.18.zend.locale.defaultcaching">B.4.2.1. Default caching</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.17.phtml">B.5. Zend Framework 1.7</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.controller">B.5.1. Zend_Controller</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.controller.dispatcher">B.5.1.1. Dispatcher Interface Changes</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.file.transfer">B.5.2. Zend_File_Transfer</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators">B.5.2.1. Changes when using filters and validators</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.rename">B.5.2.1.1. Filter: Rename</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.count">B.5.2.1.2. Validator: Count</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.extension">B.5.2.1.3. Validator:Extension</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.filessize">B.5.2.1.4. Validator: FilesSize</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.hash">B.5.2.1.5. Validator: Hash</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.imagesize">B.5.2.1.6. Validator: ImageSize</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.size">B.5.2.1.7. Validator: Size</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.locale">B.5.3. Zend_Locale</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.locale.islocale">B.5.3.1. Changes when using isLocale()</a></span></dt>
<dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.locale.islocale.getdefault">B.5.3.2. Changes when using getDefault()</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.translate">B.5.4. Zend_Translate</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.translate.languages">B.5.4.1. Setting languages</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.view">B.5.5. Zend_View</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.view.disabling">B.5.5.1. Disabling LFI protection for the render() method</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.16.phtml">B.6. Zend Framework 1.6</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.16.phtml#migration.16.zend.controller">B.6.1. Zend_Controller</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.16.phtml#migration.16.zend.controller.dispatcher">B.6.1.1. Dispatcher Interface Changes</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.16.phtml#migration.16.zend.file.transfer">B.6.2. Zend_File_Transfer</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.16.phtml#migration.16.zend.file.transfer.validators">B.6.2.1. Changes when using validators</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.15.phtml">B.7. Zend Framework 1.5</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.15.phtml#migration.15.zend.controller">B.7.1. Zend_Controller</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="migration.10.phtml">B.8. Zend Framework 1.0</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.10.phtml#migration.10.zend.controller">B.8.1. Zend_Controller</a></span></dt>
<dt><span class="sect2"><a href="migration.10.phtml#migration.10.zend.currency">B.8.2. Zend_Currency</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="migration.09.phtml">B.9. Zend Framework 0.9</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.09.phtml#migration.09.zend.controller">B.9.1. Zend_Controller</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="migration.08.phtml">B.10. Zend Framework 0.8</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.08.phtml#migration.08.zend.controller">B.10.1. Zend_Controller</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="migration.06.phtml">B.11. Zend Framework 0.6</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.06.phtml#migration.06.zend.controller">B.11.1. Zend_Controller</a></span></dt></dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="migration.112"></a>B.1. Zend Framework 1.12</h2></div></div></div>
<p>
        When upgrading from a previous release to Zend Framework 1.12 or higher you
        should note the following migration notes.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.12.zend.view.helper.navigation"></a>B.1.1. Zend_View_Helper_Navigation</h3></div></div></div>
<p>
            Prior to the 1.12 release, a helper with the name
            "My_View_Helper_Navigation_Menu" can not be used, because the proxy
            helper returns always the standard view helper
            "Zend_View_Helper_Navigation_Menu".
        </p>
<p>
            Starting from version 1.12, you can use our own navigation helpers
            with the name "menu", "breadcrumbs", ...
        </p>
<p>
            Create your own helper with name "Menu":
        </p>
<pre class="programlisting">
class My_View_Helper_Navigation_Menu
    extends Zend_View_Helper_Navigation_HelperAbstract
{
    public function menu(Zend_Navigation_Container $container = null)
    {
        if (null !== $container) {
            $this-&gt;setContainer($container);
        }

        return $this;
    }

    public function render(Zend_Navigation_Container $container = null)
    {
        return '&lt;nav&gt;Example&lt;/nav&gt;';
    }
}
</pre>
<p>
            Add the helper path to <code class="classname">Zend_View</code> in your
            Bootstrap class:
        </p>
<pre class="programlisting">
    protected function _initView()
    {
        $this-&gt;bootstrap('view');
        $this-&gt;view-&gt;addHelperPath(
            'path/to/helper',
            'My_View_Helper_Navigation'
        );
    }
</pre>
<p>
            Or add the helper path in your "application.ini" file:
        </p>
<pre class="programlisting">
resources.view.helperPath.My_View_Helper_Navigation = "path/to/helper"
</pre>
<p>
            The following code is used in a view script:
        </p>
<pre class="programlisting">
&lt;?php echo $this-&gt;navigation()-&gt;menu(); ?&gt;
</pre>
<p>
            Output:
        </p>
<pre class="programlisting">
&lt;nav&gt;Example&lt;/nav&gt;
</pre>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="requirements.phtml">Prev</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> <a accesskey="n" href="migration.110.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Appendix A. Zend Framework Requirements </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> B.2. Zend Framework 1.10</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
