<?php $title = 'B.4. Zend Framework 1.8'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">B.4. Zend Framework 1.8</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="migration.19.phtml">Prev</a> </td>
<th width="60%" align="center">Appendix B. Zend Framework Migration Notes</th>
<td width="20%" align="right"> <a accesskey="n" href="migration.17.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="migration.18"></a>B.4. Zend Framework 1.8</h2></div></div></div>
<p>
        When upgrading from a previous release to Zend Framework 1.8 or higher you
        should note the following migration notes.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.18.zend.controller"></a>B.4.1. Zend_Controller</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="migration.18.zend.controller.router"></a>B.4.1.1. Standard Route Changes</h4></div></div></div>
<p>
                As translated segments were introduced into the new standard
                route, the '<span class="emphasis"><em>@</em></span>' character is now a special character
                in the beginning of a route segment. To be able to use it in a
                static segment, you must escape it by prefixing it with second
                '<span class="emphasis"><em>@</em></span>' character. The same rule now applies for the
                '<span class="emphasis"><em>:</em></span>' character.
            </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.18.zend.locale"></a>B.4.2. Zend_Locale</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="migration.18.zend.locale.defaultcaching"></a>B.4.2.1. Default caching</h4></div></div></div>
<p>
                As with Zend Framework 1.8 a default caching was added. The reason behind this
                change was, that most users had performance problems but did not add caching at
                all. As the I18n core is a bottleneck when no caching is used we decided to add
                a default caching when no cache has been set to <code class="classname">Zend_Locale</code>.
            </p>
<p>
                Sometimes it is still wanted to prevent caching at all even if this decreases
                performance. To do so you can simply disable caching by using the
                <code class="methodname">disableCache()</code> method.
            </p>
<div class="example">
<a name="migration.18.zend.locale.defaultcaching.example"></a><p class="title"><b>Example B.3. Disabling default caching</b></p>
<div class="example-contents"><pre class="programlisting">
Zend_Locale::disableCache(true);
</pre></div>
</div>
<br class="example-break">
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="migration.19.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="migration.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="migration.17.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">B.3. Zend Framework 1.9 </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> B.5. Zend Framework 1.7</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
