<?php $title = 'E.3. Module Structure'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">E.3. Module Structure</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="project-structure.project.phtml">Prev</a> </td>
<th width="60%" align="center">Appendix E. Recommended Project Structure for Zend Framework MVC Applications</th>
<td width="20%" align="right"> <a accesskey="n" href="project-structure.rewrite.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="project-structure.filesystem"></a>E.3. Module Structure</h2></div></div></div>
<p>
            The directory structure for modules should mimic that of the
            <code class="filename">application/</code> directory in the recommended project structure:
        </p>
<pre class="programlisting">
&lt;modulename&gt;
    configs/
        application.ini
    controllers/
        helpers/
    forms/
    layouts/
        filters/
        helpers/
        scripts/
    models/
    services/
    views/
        filters/
        helpers/
        scripts/
    Bootstrap.php
</pre>
<p>
            The purpose of these directories remains exactly the same as for the recommended
            project directory structure.
        </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="project-structure.project.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="project-structure.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="project-structure.rewrite.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">E.2. Recommended Project Directory Structure </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> E.4. Rewrite Configuration Guide</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
