<?php $title = 'Appendix E. Recommended Project Structure for Zend Framework MVC Applications'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Appendix E. Recommended Project Structure for Zend Framework MVC Applications</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="doc-standard.recommendations.phtml">Prev</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> <a accesskey="n" href="project-structure.project.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="appendix">
<div class="titlepage"><div><div><h1 class="title">
<a name="project-structure"></a>Appendix E. Recommended Project Structure for Zend Framework MVC Applications</h1></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="project-structure.phtml#project-structure.overview">E.1. Overview</a></span></dt>
<dt><span class="sect1"><a href="project-structure.project.phtml">E.2. Recommended Project Directory Structure</a></span></dt>
<dt><span class="sect1"><a href="project-structure.filesystem.phtml">E.3. Module Structure</a></span></dt>
<dt><span class="sect1"><a href="project-structure.rewrite.phtml">E.4. Rewrite Configuration Guide</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="project-structure.rewrite.phtml#project-structure.rewrite.apache">E.4.1. Apache HTTP Server</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="project-structure.rewrite.phtml#project-structure.rewrite.apache.vhost">E.4.1.1. Rewriting inside a VirtualHost</a></span></dt>
<dt><span class="sect3"><a href="project-structure.rewrite.phtml#project-structure.rewrite.apache.htaccess">E.4.1.2. Rewriting within a .htaccess file</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="project-structure.rewrite.phtml#project-structure.rewrite.iis">E.4.2. Microsoft Internet Information Server</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="project-structure.overview"></a>E.1. Overview</h2></div></div></div>
<p>
            Many developers seek guidance on the best project structure for a Zend Framework project
            in a relatively flexible environment. A "flexible" environment is one in which the
            developer can manipulate their file systems and web server configurations as needed to
            achieve the most ideal project structure to run and secure their application. The
            default project structure will assume that the developer has such flexibility at their
            disposal.
        </p>
<p>
            The following directory structure is designed to be maximally extensible for complex
            projects, while providing a simple subset of folder and files for project with simpler
            requirements. This structure also works without alteration for both modular and
            non-modular Zend Framework applications. The <code class="filename">.htaccess</code> files
            require <acronym class="acronym">URL</acronym> rewrite functionality in the web server as described in
            the <a class="link" href="project-structure.rewrite.phtml" title="E.4. Rewrite Configuration Guide">Rewrite Configuration Guide</a>, also
            included in this appendix.
        </p>
<p>
            It is not the intention that this project structure will support all possible Zend
            Framework project requirements. The default project profile used by
            <code class="classname">Zend_Tool</code> reflect this project structure, but applications with
            requirements not supported by this structure should use a custom project profile.
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="doc-standard.recommendations.phtml">Prev</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> <a accesskey="n" href="project-structure.project.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">D.3. Recommendations </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> E.2. Recommended Project Directory Structure</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
