<?php $title = 'Index'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Index</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="copyrights.phtml">Prev</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> </td>
</tr>
</table></div>
<div class="index">
<div class="titlepage"><div><div><h1 class="title">
<a name="the.index"></a>Index</h1></div></div></div>
<div xmlns:xlink="http://www.w3.org/1999/xlink" class="index"></div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="copyrights.phtml">Prev</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> </td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Appendix G. Copyright Information </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> </td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
