<?php $title = 'Chapter 35. Zend_Filter'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 35. Zend_Filter</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.file.transfer.filters.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.filter.set.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.filter"></a>Chapter 35. Zend_Filter</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.filter.phtml#zend.filter.introduction">35.1. Introduction</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.filter.phtml#zend.filter.introduction.definition">35.1.1. What is a filter?</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.phtml#zend.filter.introduction.using">35.1.2. Basic usage of filters</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.phtml#zend.filter.introduction.static">35.1.3. Using the static staticFilter() method</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.filter.phtml#zend.filter.introduction.static.namespaces">35.1.3.1. Namespaces</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.filter.phtml#zend.filter.introduction.caveats">35.1.4. Double filtering</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.filter.set.phtml">35.2. Standard Filter Classes</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.alnum">35.2.1. Alnum</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alnum.options">35.2.1.1. Supported options for Zend_Filter_Alnum</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alnum.basic">35.2.1.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alnum.whitespace">35.2.1.3. Allow whitespaces</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.alpha">35.2.2. Alpha</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alpha.options">35.2.2.1. Supported options for Zend_Filter_Alpha</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alpha.basic">35.2.2.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alpha.whitespace">35.2.2.3. Allow whitespace characters</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.basename">35.2.3. BaseName</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.basename.options">35.2.3.1. Supported options for Zend_Filter_BaseName</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.basename.basic">35.2.3.2. Basic usage</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.boolean">35.2.4. Boolean</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.options">35.2.4.1. Supported options for Zend_Filter_Boolean</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.default">35.2.4.2. Default behaviour for Zend_Filter_Boolean</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.types">35.2.4.3. Changing behaviour for Zend_Filter_Boolean</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.localized">35.2.4.4. Localized booleans</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.casting">35.2.4.5. Disable casting</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.callback">35.2.5. Callback</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.callback.options">35.2.5.1. Supported options for Zend_Filter_Callback</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.callback.basic">35.2.5.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.callback.parameters">35.2.5.3. Default parameters within a callback</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.compress">35.2.6. Compress and Decompress</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.options">35.2.6.1. Supported options for Zend_Filter_Compress and Zend_Filter_Decompress</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.basic">35.2.6.2. Supported compression adapters</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.generic">35.2.6.3. Generic handling</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.archive">35.2.6.4. Creating an archive</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.decompress">35.2.6.5. Decompressing an archive</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.bz2">35.2.6.6. Bz2 Adapter</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.gz">35.2.6.7. Gz Adapter</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.lzf">35.2.6.8. Lzf Adapter</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.rar">35.2.6.9. Rar Adapter</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.tar">35.2.6.10. Tar Adapter</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.zip">35.2.6.11. Zip Adapter</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.digits">35.2.7. Digits</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.digits.options">35.2.7.1. Supported options for Zend_Filter_Digits</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.digits.basic">35.2.7.2. Basic usage</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.dir">35.2.8. Dir</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.dir.options">35.2.8.1. Supported options for Zend_Filter_Dir</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.dir.basic">35.2.8.2. Basic usage</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.encrypt">35.2.9. Encrypt and Decrypt</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.options">35.2.9.1. Supported options for Zend_Filter_Encrypt and Zend_Filter_Decrypt</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.adapterusage">35.2.9.2. Adapter usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.mcrypt">35.2.9.3. Encryption with Mcrypt</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.mcryptdecrypt">35.2.9.4. Decryption with Mcrypt</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.openssl">35.2.9.5. Encryption with OpenSSL</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.openssl.simplified">35.2.9.5.1. Simplified usage with Openssl</a></span></dt>
<dt><span class="sect4"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.openssl.compressed">35.2.9.5.2. Compressing the content</a></span></dt>
</dl></dd>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.openssldecrypt">35.2.9.6. Decryption with OpenSSL</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities">35.2.10. HtmlEntities</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities.options">35.2.10.1. Supported options for Zend_Filter_HtmlEntities</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities.basic">35.2.10.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities.quotestyle">35.2.10.3. Quote Style</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities.">35.2.10.4. Helper Methods</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.int">35.2.11. Int</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.int.options">35.2.11.1. Supported options for Zend_Filter_Int</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.int.basic">35.2.11.2. Basic usage</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized">35.2.12. LocalizedToNormalized and NormalizedToLocalized</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.options">35.2.12.1. 
            Supported options for Zend_Filter_LocalizedToNormalized and
            Zend_Filter_NormalizedToLocalized
        </a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.workflow">35.2.12.2. Workflow</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.numbersnormal">35.2.12.3. Normalization for numbers</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.dates">35.2.12.4. Normalization for date and time</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.numberslocal">35.2.12.5. Localization for numbers</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.normalizedtolocalized.dates">35.2.12.6. Localization for date and time</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.null">35.2.13. Null</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.null.options">35.2.13.1. Supported options for Zend_Filter_Null</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.null.default">35.2.13.2. Default behaviour for Zend_Filter_Null</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.null.types">35.2.13.3. Changing behaviour for Zend_Filter_Null</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.pregreplace">35.2.14. PregReplace</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.pregreplace.options">35.2.14.1. Supported options for Zend_Filter_PregReplace</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.pregreplace.basic">35.2.14.2. Basic usage</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.realpath">35.2.15. RealPath</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.realpath.options">35.2.15.1. Supported options for Zend_Filter_RealPath</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.realpath.basic">35.2.15.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.realpath.exists">35.2.15.3. Non existing paths</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.stringtolower">35.2.16. StringToLower</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtolower.options">35.2.16.1. Supported options for Zend_Filter_StringToLower</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtolower.basic">35.2.16.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtolower.encoding">35.2.16.3. Different encoded strings</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.stringtoupper">35.2.17. StringToUpper</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtoupper.options">35.2.17.1. Supported options for Zend_Filter_StringToUpper</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtoupper.basic">35.2.17.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtoupper.encoding">35.2.17.3. Different encoded strings</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.stringtrim">35.2.18. StringTrim</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtrim.options">35.2.18.1. Supported options for Zend_Filter_StringTrim</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtrim.basic">35.2.18.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtrim.types">35.2.18.3. Default behaviour for Zend_Filter_StringTrim</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.stripnewlines">35.2.19. StripNewLines</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.strinpnewlines.options">35.2.19.1. Supported options for Zend_Filter_StripNewLines</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stripnewlines.basic">35.2.19.2. Basic usage</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.striptags">35.2.20. StripTags</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.striptags.options">35.2.20.1. Supported options for Zend_Filter_StripTags</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.striptags.basic">35.2.20.2. Basic usage</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.striptags.allowtags">35.2.20.3. Allowing defined tags</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.striptags.allowattribs">35.2.20.4. Allowing defined attributes</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.filter.filter_chains.phtml">35.3. Filter Chains</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="zend.filter.filter_chains.phtml#zend.filter.filter_chains.order">35.3.1. Changing filter chain order</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="zend.filter.writing_filters.phtml">35.4. Writing Filters</a></span></dt>
<dt><span class="sect1"><a href="zend.filter.input.phtml">35.5. Zend_Filter_Input</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.declaring">35.5.1. Declaring Filter and Validator Rules</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.running">35.5.2. Creating the Filter and Validator Processor</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.results">35.5.3. Retrieving Validated Fields and other Reports</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.results.isvalid">35.5.3.1. Querying if the input is valid</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.results.reports">35.5.3.2. Getting Invalid, Missing, or Unknown Fields</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.results.escaping">35.5.3.3. Getting Valid Fields</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.metacommands">35.5.4. Using Metacommands to Control Filter or Validator Rules</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.fields">35.5.4.1. The FIELDS metacommand</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.presence">35.5.4.2. The PRESENCE metacommand</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.default">35.5.4.3. The DEFAULT_VALUE metacommand</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.allow-empty">35.5.4.4. The ALLOW_EMPTY metacommand</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.break-chain">35.5.4.5. The BREAK_CHAIN metacommand</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.messages">35.5.4.6. The MESSAGES metacommand</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.global">35.5.4.7. Using options to set metacommands for all rules</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.namespaces">35.5.5. Adding Filter Class Namespaces</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.filter.inflector.phtml">35.6. Zend_Filter_Inflector</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.operation">35.6.1. Operation</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.paths">35.6.2. Setting Paths To Alternate Filters</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.targets">35.6.3. Setting the Inflector Target</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.rules">35.6.4. Inflection Rules</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.inflector.phtml#zend.filter.inflector.rules.static">35.6.4.1. Static Rules</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.inflector.phtml#zend.filter.inflector.rules.filters">35.6.4.2. Filter Inflector Rules</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.inflector.phtml#zend.filter.inflector.rules.multiple">35.6.4.3. Setting Many Rules At Once</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.utility">35.6.5. Utility Methods</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.config">35.6.6. Using Zend_Config with Zend_Filter_Inflector</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.filter.introduction"></a>35.1. Introduction</h2></div></div></div>
<p>
        The <code class="classname">Zend_Filter</code> component provides a set of commonly needed data
        filters. It also provides a simple filter chaining mechanism by which
        multiple filters may be applied to a single datum in a user-defined
        order.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.introduction.definition"></a>35.1.1. What is a filter?</h3></div></div></div>
<p>
            In the physical world, a filter is typically used for removing
            unwanted portions of input, and the desired portion of the input
            passes through as filter output (e.g., coffee). In such scenarios,
            a filter is an operator that produces a subset of the input. This
            type of filtering is useful for web applications - removing illegal
            input, trimming unnecessary white space, etc.
        </p>
<p>
            This basic definition of a filter may be extended to include
            generalized transformations upon input. A common transformation
            applied in web applications is the escaping of <acronym class="acronym">HTML</acronym> entities. For
            example, if a form field is automatically populated with untrusted
            input (e.g., from a web browser), this value should either be free
            of <acronym class="acronym">HTML</acronym> entities or contain only escaped <acronym class="acronym">HTML</acronym>
            entities, in order to prevent undesired behavior and security vulnerabilities. To meet
            this requirement, <acronym class="acronym">HTML</acronym> entities that appear in the input must
            either be removed or escaped. Of course, which approach is more
            appropriate depends on the situation. A filter that removes the
            <acronym class="acronym">HTML</acronym> entities operates within the scope of the first definition of
            filter - an operator that produces a subset of the input. A filter
            that escapes the <acronym class="acronym">HTML</acronym> entities, however, transforms the input
            (e.g., "&amp;" is transformed to
            "&amp;amp;"). Supporting such use cases for web
            developers is important, and "to filter," in the context of using
            <code class="classname">Zend_Filter</code>, means to perform some transformations upon input
            data.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.introduction.using"></a>35.1.2. Basic usage of filters</h3></div></div></div>
<p>
            Having this filter definition established provides the foundation
            for <code class="classname">Zend_Filter_Interface</code>, which requires a single
            method named <code class="methodname">filter()</code> to be implemented by a filter
            class.
        </p>
<p>
            Following is a basic example of using a filter upon two input data,
            the ampersand (<span class="emphasis"><em>&amp;</em></span>) and double quote
            (<span class="emphasis"><em>"</em></span>) characters:
        </p>
<pre class="programlisting">
$htmlEntities = new Zend_Filter_HtmlEntities();

echo $htmlEntities-&gt;filter('&amp;'); // &amp;amp;
echo $htmlEntities-&gt;filter('"'); // &amp;quot;
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.introduction.static"></a>35.1.3. Using the static staticFilter() method</h3></div></div></div>
<p>
            If it is inconvenient to load a given filter class and create an
            instance of the filter, you can use the static method
            <code class="methodname">Zend_Filter::filterStatic()</code> as an alternative invocation style.
            The first argument of this method is a data input value, that you
            would pass to the <code class="methodname">filter()</code> method. The second
            argument is a string, which corresponds to the basename of the
            filter class, relative to the <code class="classname">Zend_Filter</code> namespace. The
            <code class="methodname">staticFilter()</code> method automatically loads the class, creates
            an instance, and applies the <code class="methodname">filter()</code> method to the data
            input.
        </p>
<pre class="programlisting">
echo Zend_Filter::filterStatic('&amp;', 'HtmlEntities');
</pre>
<p>
            You can also pass an array of constructor arguments, if they
            are needed for the filter class.
        </p>
<pre class="programlisting">
echo Zend_Filter::filterStatic('"',
                               'HtmlEntities',
                               array('quotestyle' =&gt; ENT_QUOTES));
</pre>
<p>
            The static usage can be convenient for invoking a filter ad hoc,
            but if you have the need to run a filter for multiple inputs,
            it's more efficient to follow the first example above,
            creating an instance of the filter object and calling its
            <code class="methodname">filter()</code> method.
        </p>
<p>
            Also, the <code class="classname">Zend_Filter_Input</code> class allows you to instantiate and
            run multiple filter and validator classes on demand to process
            sets of input data. See <a class="link" href="zend.filter.input.phtml" title="35.5. Zend_Filter_Input">Zend_Filter_Input</a>.
        </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.introduction.static.namespaces"></a>35.1.3.1. Namespaces</h4></div></div></div>
<p>
                When working with self defined filters you can give a fourth parameter
                to <code class="methodname">Zend_Filter::filterStatic()</code> which is the namespace
                where your filter can be found.
            </p>
<pre class="programlisting">
echo Zend_Filter::filterStatic(
    '"',
    'MyFilter',
    array($parameters),
    array('FirstNamespace', 'SecondNamespace')
);
</pre>
<p>
                <code class="classname">Zend_Filter</code> allows also to set namespaces as default.
                This means that you can set them once in your bootstrap and have not to give
                them again for each call of <code class="methodname">Zend_Filter::filterStatic()</code>.
                The following code snippet is identical to the above one.
            </p>
<pre class="programlisting">
Zend_Filter::setDefaultNamespaces(array('FirstNamespace', 'SecondNamespace'));
echo Zend_Filter::filterStatic('"', 'MyFilter', array($parameters));
echo Zend_Filter::filterStatic('"', 'OtherFilter', array($parameters));
</pre>
<p>
                For your convenience there are following methods which allow the handling of
                namespaces:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <span class="emphasis"><em><code class="methodname">Zend_Filter::getDefaultNamespaces()</code></em></span>:
                        Returns all set default namespaces as array.
                    </p></li>
<li class="listitem"><p>
                        <span class="emphasis"><em><code class="methodname">Zend_Filter::setDefaultNamespaces()</code></em></span>:
                        Sets new default namespaces and overrides any previous set. It accepts
                        either a string for a single namespace of an array for multiple namespaces.
                    </p></li>
<li class="listitem"><p>
                        <span class="emphasis"><em><code class="methodname">Zend_Filter::addDefaultNamespaces()</code></em></span>:
                        Adds additional namespaces to already set ones. It accepts either a string
                        for a single namespace of an array for multiple namespaces.
                    </p></li>
<li class="listitem"><p>
                        <span class="emphasis"><em><code class="methodname">Zend_Filter::hasDefaultNamespaces()</code></em></span>:
                        Returns <code class="constant">TRUE</code> when one or more default namespaces are
                        set, and <code class="constant">FALSE</code> when no default namespaces are set.
                    </p></li>
</ul></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.introduction.caveats"></a>35.1.4. Double filtering</h3></div></div></div>
<p>
            When using two filters after each other you have to keep in mind that it is often not
            possible to get the original output by using the opposite filter. Take the following
            example:
        </p>
<pre class="programlisting">
$original = "my_original_content";

// Attach a filter
$filter   = new Zend_Filter_Word_UnderscoreToCamelCase();
$filtered = $filter-&gt;filter($original);

// Use it's opposite
$filter2  = new Zend_Filter_Word_CamelCaseToUnderscore();
$filtered = $filter2-&gt;filter($filtered)
</pre>
<p>
            The above code example could lead to the impression that you will get the original
            output after the second filter has been applied. But thinking logically this is not the
            case. After applying the first filter <span class="emphasis"><em>my_original_content</em></span> will be
            changed to <span class="emphasis"><em>MyOriginalContent</em></span>. But after applying the second filter
            the result is <span class="emphasis"><em>My_Original_Content</em></span>.
        </p>
<p>
            As you can see it is not always possible to get the original output by using a filter
            which seems to be the opposite. It depends on the filter and also on the given input.
        </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.file.transfer.filters.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.filter.set.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">34.3. Filters for Zend_File_Transfer </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 35.2. Standard Filter Classes</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
