<?php $title = '45.9. Additional Headers'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">45.9. Additional Headers</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.boundary.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 45. Zend_Mail</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.character-sets.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.additional-headers"></a>45.9. Additional Headers</h2></div></div></div>
<p>
        <code class="classname">Zend_Mail</code> provides several methods to set additional Mail Headers:

        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="methodname">setReplyTo($email, $name=null)</code>: sets the Reply-To:
                    header.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setDate($date = null)</code>: sets the Date: header.
                    This method uses current time stamp by default. Or You can pass time stamp,
                    date string or <code class="classname">Zend_Date</code> instance to this method.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setMessageId($id = true)</code>: sets the Message-Id: header.
                    This method can generate message ID automatically by default. Or You can pass
                    your message ID string to this method.
                    This method call <code class="methodname">createMessageId()</code> internally.
                </p></li>
</ul></div>
<p>
    </p>
<div class="note"><table border="0" summary="Note: Return-Path">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Return-Path</th>
</tr>
<tr><td align="left" valign="top"><p>
            If you set Return-Path on your mail, see <a class="link" href="zend.mail.phtml#zend.mail.introduction.sendmail" title="45.1.2. Configuring the default sendmail transport">Configuring sendmail transport</a>.
            Unfortunately, <code class="methodname">setReturnPath($email)</code> method does not perform
            this purpose.
        </p></td></tr>
</table></div>
<p>
        Furthermore, arbitrary mail headers can be set by using the
        <code class="methodname">addHeader()</code> method. It requires two parameters containing the name
        and the value of the header field. A third optional parameter determines if the header
        should have only one or multiple values:
    </p>
<div class="example">
<a name="zend.mail.additional-headers.example-1"></a><p class="title"><b>Example 45.10. Adding E-Mail Message Headers</b></p>
<div class="example-contents"><pre class="programlisting">
$mail = new Zend_Mail();
$mail-&gt;addHeader('X-MailGenerator', 'MyCoolApplication');
$mail-&gt;addHeader('X-greetingsTo', 'Mom', true); // multiple values
$mail-&gt;addHeader('X-greetingsTo', 'Dad', true);
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.boundary.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mail.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.character-sets.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">45.8. Controlling the MIME Boundary </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 45.10. Character Sets</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
