<?php $title = 'Chapter 30. Zend_Dom'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 30. Zend_Dom</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.dojo.build-layers.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.dom.query.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.dom"></a>Chapter 30. Zend_Dom</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.dom.phtml#zend.dom.introduction">30.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.dom.query.phtml">30.2. Zend_Dom_Query</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.dom.query.phtml#zend.dom.query.operation">30.2.1. Theory of Operation</a></span></dt>
<dt><span class="sect2"><a href="zend.dom.query.phtml#zend.dom.query.methods">30.2.2. Methods Available</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.dom.query.phtml#zend.dom.query.methods.zenddomquery">30.2.2.1. Zend_Dom_Query</a></span></dt>
<dt><span class="sect3"><a href="zend.dom.query.phtml#zend.dom.query.methods.zenddomqueryresult">30.2.2.2. Zend_Dom_Query_Result</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.dom.introduction"></a>30.1. Introduction</h2></div></div></div>
<p>
        <code class="classname">Zend_Dom</code> provides tools for working with <acronym class="acronym">DOM</acronym>
        documents and structures. Currently, we offer <code class="classname">Zend_Dom_Query</code>, which
        provides a unified interface for querying <acronym class="acronym">DOM</acronym> documents utilizing both
        XPath and <acronym class="acronym">CSS</acronym> selectors.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.dojo.build-layers.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.dom.query.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">29.5. Zend_Dojo build layer support </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 30.2. Zend_Dom_Query</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
