<?php $title = '16.2. Barcode creation using Zend_Barcode class'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">16.2. Barcode creation using Zend_Barcode class</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.barcode.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 16. Zend_Barcode</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.barcode.objects.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.barcode.creation"></a>16.2. Barcode creation using Zend_Barcode class</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.barcode.creation.configuration"></a>16.2.1. Using Zend_Barcode::factory</h3></div></div></div>
<p>
            <code class="classname">Zend_Barcode</code> uses a factory method to create an instance of a
            renderer that extends <code class="classname">Zend_Barcode_Renderer_RendererAbstract</code>. The
            factory method accepts five arguments.
        </p>
<div class="orderedlist"><ol class="orderedlist" type="1">
<li class="listitem"><p>The name of the barcode format (e.g., "code39") (required)</p></li>
<li class="listitem"><p>The name of the renderer (e.g., "image") (required)</p></li>
<li class="listitem"><p>
                    Options to pass to the barcode object (an array or
                    <code class="classname">Zend_Config</code> object) (optional)
                </p></li>
<li class="listitem"><p>
                    Options to pass to the renderer object (an array or
                    <code class="classname">Zend_Config</code> object) (optional)
                </p></li>
<li class="listitem"><p>
                    Boolean to indicate whether or not to automatically render errors. If an
                    exception occurs, the provided barcode object will be replaced with an Error
                    representation (optional default <code class="constant">TRUE</code>)
                </p></li>
</ol></div>
<div class="example">
<a name="zend.barcode.creation.configuration.example-1"></a><p class="title"><b>Example 16.1. Getting a Renderer with Zend_Barcode::factory()</b></p>
<div class="example-contents">
<p>
                <code class="methodname">Zend_Barcode::factory()</code> instantiates barcode objects and
                renderers and ties them together. In this first example, we will use the
                <span class="emphasis"><em>Code39</em></span> barcode type together with the
                <span class="emphasis"><em>Image</em></span> renderer.
            </p>
<pre class="programlisting">
// Only the text to draw is required
$barcodeOptions = array('text' =&gt; 'ZEND-FRAMEWORK');

// No required options
$rendererOptions = array();
$renderer = Zend_Barcode::factory(
    'code39', 'image', $barcodeOptions, $rendererOptions
);
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.barcode.creation.configuration.example-2"></a><p class="title"><b>Example 16.2. Using Zend_Barcode::factory() with Zend_Config objects</b></p>
<div class="example-contents">
<p>
                You may pass a <code class="classname">Zend_Config</code> object to the factory in order to
                create the necessary objects. The following example is functionally equivalent to
                the previous.
            </p>
<pre class="programlisting">
// Using only one Zend_Config object
$config = new Zend_Config(array(
    'barcode'        =&gt; 'code39',
    'barcodeParams'  =&gt; array('text' =&gt; 'ZEND-FRAMEWORK'),
    'renderer'       =&gt; 'image',
    'rendererParams' =&gt; array('imageType' =&gt; 'gif'),
));

$renderer = Zend_Barcode::factory($config);
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.barcode.creation.drawing"></a>16.2.2. Drawing a barcode</h3></div></div></div>
<p>
            When you <span class="emphasis"><em>draw</em></span> the barcode, you retrieve the resource in which the
            barcode is drawn. To draw a barcode, you can call the <code class="methodname">draw()</code> of
            the renderer, or simply use the proxy method provided by
            <code class="classname">Zend_Barcode</code>.
        </p>
<div class="example">
<a name="zend.barcode.creation.drawing.example-1"></a><p class="title"><b>Example 16.3. Drawing a barcode with the renderer object</b></p>
<div class="example-contents"><pre class="programlisting">
// Only the text to draw is required
$barcodeOptions = array('text' =&gt; 'ZEND-FRAMEWORK');

// No required options
$rendererOptions = array();

// Draw the barcode in a new image,
$imageResource = Zend_Barcode::factory(
    'code39', 'image', $barcodeOptions, $rendererOptions
)-&gt;draw();
</pre></div>
</div>
<br class="example-break"><div class="example">
<a name="zend.barcode.creation.drawing.example-2"></a><p class="title"><b>Example 16.4. Drawing a barcode with Zend_Barcode::draw()</b></p>
<div class="example-contents"><pre class="programlisting">
// Only the text to draw is required
$barcodeOptions = array('text' =&gt; 'ZEND-FRAMEWORK');

// No required options
$rendererOptions = array();

// Draw the barcode in a new image,
$imageResource = Zend_Barcode::draw(
    'code39', 'image', $barcodeOptions, $rendererOptions
);
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.barcode.creation.renderering"></a>16.2.3. Renderering a barcode</h3></div></div></div>
<p>
            When you render a barcode, you draw the barcode, you send the headers and you send the
            resource (e.g. to a browser). To render a barcode, you can call the
            <code class="methodname">render()</code> method of the renderer or simply use the proxy method
            provided by <code class="classname">Zend_Barcode</code>.
        </p>
<div class="example">
<a name="zend.barcode.creation.renderering.example-1"></a><p class="title"><b>Example 16.5. Renderering a barcode with the renderer object</b></p>
<div class="example-contents">
<pre class="programlisting">
// Only the text to draw is required
$barcodeOptions = array('text' =&gt; 'ZEND-FRAMEWORK');

// No required options
$rendererOptions = array();

// Draw the barcode in a new image,
// send the headers and the image
Zend_Barcode::factory(
    'code39', 'image', $barcodeOptions, $rendererOptions
)-&gt;render();
</pre>
<p>
                This will generate this barcode:
            </p>
<p>
                <img src="figures/zend.barcode.introduction.example-1.png" align="middle" width="275">
            </p>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.barcode.creation.renderering.example-2"></a><p class="title"><b>Example 16.6. Renderering a barcode with Zend_Barcode::render()</b></p>
<div class="example-contents">
<pre class="programlisting">
// Only the text to draw is required
$barcodeOptions = array('text' =&gt; 'ZEND-FRAMEWORK');

// No required options
$rendererOptions = array();

// Draw the barcode in a new image,
// send the headers and the image
Zend_Barcode::render(
    'code39', 'image', $barcodeOptions, $rendererOptions
);
</pre>
<p>
                This will generate the same barcode as the previous example.
            </p>
</div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.barcode.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.barcode.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.barcode.objects.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Chapter 16. Zend_Barcode </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 16.3. Zend_Barcode Objects</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
