<?php $title = '57.5. Customizing Zend_Queue'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">57.5. Customizing Zend_Queue</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.queue.adapters.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 57. Zend_Queue</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.queue.stomp.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.queue.custom"></a>57.5. Customizing Zend_Queue</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.queue.custom.adapter"></a>57.5.1. Creating your own adapter</h3></div></div></div>
<p>
            <code class="classname">Zend_Queue</code> will accept any adapter that
            implements
            <code class="classname">Zend_Queue_Adapter_AdapterAbstract</code>. You can
            create your own adapter by extending one of the existing adapters,
            or the abstract class
            <code class="classname">Zend_Queue_Adapter_AdapterAbstract</code>. I
            suggest reviewing <code class="classname">Zend_Queue_Adapter_Array</code> as
            this adapter is the easiest to conceptualize.
        </p>
<pre class="programlisting">
class Custom_DbForUpdate extends Zend_Queue_Adapter_Db
{
    /**
     * @see code in tests/Zend/Queue/Custom/DbForUpdate.php
     *
     * Custom_DbForUpdate uses the SELECT ... FOR UPDATE to find it's rows.
     * this is more likely to produce the wanted rows than the existing code.
     *
     * However, not all databases have SELECT ... FOR UPDATE as a feature.
     *
     * Note: this was later converted to be an option for Zend_Queue_Adapter_Db
     *
     * This code still serves as a good example.
     */
}

$options = array(
    'name'          =&gt; 'queue1',
    'driverOptions' =&gt; array(
        'host'      =&gt; '127.0.0.1',
        'port'      =&gt; '3306',
        'username'  =&gt; 'queue',
        'password'  =&gt; 'queue',
        'dbname'    =&gt; 'queue',
        'type'      =&gt; 'pdo_mysql'
    )
);

$adapter = new Custom_DbForUpdate($options);
$queue = new Zend_Queue($adapter, $options);
</pre>
<p>
            You can also change the adapter on the fly as well.
        </p>
<pre class="programlisting">
$adapter = new MyCustom_Adapter($options);
$queue   = new Zend_Queue($options);
$queue-&gt;setAdapter($adapter);
echo "Adapter: ", get_class($queue-&gt;getAdapter()), "\n";
</pre>
<p>or</p>
<pre class="programlisting">
$options = array(
    'name'           =&gt; 'queue1',
    'namespace'      =&gt; 'Custom',
    'driverOptions'  =&gt; array(
        'host'       =&gt; '127.0.0.1',
        'port'       =&gt; '3306',
        'username'   =&gt; 'queue',
        'password'   =&gt; 'queue',
        'dbname'     =&gt; 'queue',
        'type'       =&gt; 'pdo_mysql'
    )
);
$queue = new Zend_Queue('DbForUpdate', $config); // loads Custom_DbForUpdate
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.queue.custom.message"></a>57.5.2. Creating your own message class</h3></div></div></div>
<p>
            <code class="classname">Zend_Queue</code> will also accept your own message class.
            Our variables start with an underscore. For example:
        </p>
<pre class="programlisting">
class Zend_Queue_Message
{
    protected $_data = array();
}
</pre>
<p>
            You can extend the existing messaging class. See the example code in
            <code class="filename">tests/Zend/Queue/Custom/Message.php</code>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.queue.custom-iterator"></a>57.5.3. Creating your own message iterator class</h3></div></div></div>
<p>
            <code class="classname">Zend_Queue</code> will also accept your own message
            iterator class. The message iterator class is used to return
            messages from
            <code class="methodname">Zend_Queue_Adapter_Abstract::recieve()</code>.
            <code class="methodname">Zend_Queue_Abstract::receive()</code> should always
            return a container class like
            <code class="classname">Zend_Queue_Message_Iterator</code>, even if there is
            only one message.
        </p>
<p>
            See the example filename in
            <code class="filename">tests/Zend/Queue/Custom/Messages.php</code>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.queue.custom.queue"></a>57.5.4. Creating your own queue class </h3></div></div></div>
<p>
            <code class="classname">Zend_Queue</code> can also be overloaded easily.
        </p>
<p>
            See the example filename in <code class="filename">tests/Zend/Queue/Custom/Queue.php</code>.
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.queue.adapters.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.queue.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.queue.stomp.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">57.4. Adapters </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 57.6. Stomp</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
