<?php $title = 'Chapter 72. Zend_Tool_Framework'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 72. Zend_Tool_Framework</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.tool.extending.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.tool.framework.clitool.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.tool.framework"></a>Chapter 72. Zend_Tool_Framework</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.tool.framework.phtml#zend.tool.framework.introduction">72.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.tool.framework.clitool.phtml">72.2. Using the CLI Tool</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.setup-general">72.2.1. Setting up the CLI tool</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.setup-starnix">72.2.2. Setting up the CLI tool on Unix-like Systems</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.setup-windows">72.2.3. Setting up the CLI tool on Windows</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.setup-othernotes">72.2.4. Other Setup Considerations</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.continuing">72.2.5. Where To Go Next?</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.framework.architecture.phtml">72.3. Architecture</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.registry">72.3.1. Registry</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.providers">72.3.2. Providers</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.loaders">72.3.3. Loaders</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.manifests">72.3.4. Manifests</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.clients">72.3.5. Clients</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.framework.writing-providers.phtml">72.4. Creating Providers to use with Zend_Tool_Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.loading">72.4.1. How Zend_Tool finds your Providers</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.basic">72.4.2. Basic Instructions for Creating Providers</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.response">72.4.3. The response object</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced">72.4.4. Advanced Development Information</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.variables">72.4.4.1. Passing Variables to a Provider</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.prompt">72.4.4.2. Prompt the User for Input</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.pretendable">72.4.4.3. Pretending to execute a Provider Action</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.verbosedebug">72.4.4.4. Verbose and Debug modes</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.configstorage">72.4.4.5. Accessing User Config and Storage</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.framework.system-providers.phtml">72.5. Shipped System Providers</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.system-providers.phtml#zend.tool.framework.system-providers.version">72.5.1. The Version Provider</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.system-providers.phtml#zend.tool.framework.system-providers.manifest">72.5.2. The Manifest Provider</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.framework.extending.phtml">72.6. Extending and Configuring Zend_Tool_Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client">72.6.1. Customizing Zend_Tool Console Client</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client.home-directory">72.6.1.1. The Home Directory</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client.local-storage">72.6.1.2. Local Storage</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client.configuration-file">72.6.1.3. User Configuration</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client.configuration-content">72.6.1.4. User Configuration File Content</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.tool.framework.introduction"></a>72.1. Introduction</h2></div></div></div>
<p>
        <code class="classname">Zend_Tool_Framework</code> is a framework for exposing common
        functionalities such as the creation of project scaffolds, code
        generation, search index generation, and much more. Functionality may be
        written and exposed via <acronym class="acronym">PHP</acronym> classes dropped into the
        <acronym class="acronym">PHP</acronym> <span class="property">include_path</span>, providing incredible
        flexibility of implementation. The functionality may then be consumed by writing
        implementation and/or protocol-specific clients -- such as console
        clients, <acronym class="acronym">XML-RPC</acronym>, <acronym class="acronym">SOAP</acronym>, and much more.
    </p>
<p>
        <code class="classname">Zend_Tool_Framework</code> provides the following:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <span class="emphasis"><em>Common interfaces and abstracts</em></span> that allow
                developers to create functionality and capabilities that are
                dispatchable by tooling clients.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Base client functionality</em></span> and a concrete
                console implementation that connect external tools and
                interfaces to the <code class="classname">Zend_Tool_Framework</code>. The Console
                client may be used in <acronym class="acronym">CLI</acronym> environments such as unix shells and
                the Windows console.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>"Provider" and "Manifest" interfaces</em></span> that
                can be utilized by the tooling system. "Providers" represent the
                functional aspect of the framework, and define the actions that
                tooling clients may call. "Manifests" act as metadata registries
                that provide additional context for the various defined
                providers.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>An introspective loading system</em></span> that will
                scan the environment for providers and determine what is
                required to dispatch them.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>A standard set of system providers</em></span> that
                allow the system to report what the full capabilities of the
                system are as well as provide useful feedback. This also
                includes a comprehensive "Help System".
            </p></li>
</ul></div>
<p>
        Definitions that you should be aware of through this manual with respect
        to <code class="classname">Zend_Tool_Framework</code> include:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <code class="classname">Zend_Tool_Framework</code> - The framework which exposes
                tooling capabilities.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Tooling Client</em></span> - A developer tool that connects
                to and consumes <code class="classname">Zend_Tool_Framework</code>.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Client</em></span> - The subsystem of
                <code class="classname">Zend_Tool_Framework</code> that exposes an interface such that
                tooling clients can connect, query and execute commands.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Console Client / Command Line Interface /
                <code class="filename">zf.php</code></em></span> - The tooling client for the command line.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Provider</em></span> - A subsystem and a collection of
                built-in functionality that the framework exports.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Manifest</em></span> - A subsystem for defining,
                organizing, and disseminating provider requirement data.
            </p></li>
<li class="listitem"><p>
                <code class="classname">Zend_Tool_Project</code> Provider - A set of providers
                specifically for creating and maintaining Zend Framework-based projects.
            </p></li>
</ul></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.tool.extending.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.tool.framework.clitool.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">71.2. Extending Zend_Tool </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 72.2. Using the CLI Tool</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
