<?php $title = '41.5. Object oriented access to the LDAP tree using Zend_Ldap_Node'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">41.5. Object oriented access to the LDAP tree using Zend_Ldap_Node</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.ldap.tools.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 41. Zend_Ldap</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.ldap.server.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.ldap.node"></a>41.5. Object oriented access to the LDAP tree using Zend_Ldap_Node</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.ldap.node.basic"></a>41.5.1. Basic CRUD operations</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.ldap.node.basic.retrieve"></a>41.5.1.1. Retrieving data from the LDAP</h4></div></div></div>
<div class="sect4">
<div class="titlepage"><div><div><h5 class="title">
<a name="zend.ldap.node.basic.retrieve.dn"></a>41.5.1.1.1. Getting a node by its DN</h5></div></div></div>
<p></p>
</div>
<div class="sect4">
<div class="titlepage"><div><div><h5 class="title">
<a name="zend.ldap.node.basic.retrieve.search"></a>41.5.1.1.2. Searching a node's subtree</h5></div></div></div>
<p></p>
</div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.ldap.node.basic.add"></a>41.5.1.2. Adding a new node to the LDAP</h4></div></div></div>
<p></p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.ldap.node.basic.delete"></a>41.5.1.3. Deleting a node from the LDAP</h4></div></div></div>
<p></p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.ldap.node.basic.update"></a>41.5.1.4. Updating a node on the LDAP</h4></div></div></div>
<p></p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.ldap.node.extended"></a>41.5.2. Extended operations</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.ldap.node.extended.copy-and-move"></a>41.5.2.1. Copy and move nodes in the LDAP</h4></div></div></div>
<p></p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.ldap.node.traversal"></a>41.5.3. Tree traversal</h3></div></div></div>
<div class="example">
<a name="id1808"></a><p class="title"><b>Example 41.12. Traverse LDAP tree recursively</b></p>
<div class="example-contents"><pre class="programlisting">
$options = array(/* ... */);
$ldap = new Zend_Ldap($options);
$ldap-&gt;bind();
$ri = new RecursiveIteratorIterator($ldap-&gt;getBaseNode(),
                                    RecursiveIteratorIterator::SELF_FIRST);
foreach ($ri as $rdn =&gt; $n) {
    var_dump($n);
}
</pre></div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.ldap.tools.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.ldap.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.ldap.server.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">41.4. Tools </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 41.6. Getting information from the LDAP server</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
