<?php $title = '60.3. Zend_Rest_Server'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">60.3. Zend_Rest_Server</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.rest.client.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 60. Zend_Rest</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.search.lucene.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.rest.server"></a>60.3. Zend_Rest_Server</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.rest.server.introduction"></a>60.3.1. Introduction</h3></div></div></div>
<p>
            <code class="classname">Zend_Rest_Server</code> is intended as a fully-featured REST server.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.rest.server.usage"></a>60.3.2. REST Server Usage</h3></div></div></div>
<div class="example">
<a name="zend.rest.server.usage.example-1"></a><p class="title"><b>Example 60.6. Basic Zend_Rest_Server Usage - Classes</b></p>
<div class="example-contents"><pre class="programlisting">
$server = new Zend_Rest_Server();
$server-&gt;setClass('My_Service_Class');
$server-&gt;handle();
</pre></div>
</div>
<br class="example-break"><div class="example">
<a name="zend.rest.server.usage.example-2"></a><p class="title"><b>Example 60.7. Basic Zend_Rest_Server Usage - Functions</b></p>
<div class="example-contents"><pre class="programlisting">
/**
 * Say Hello
 *
 * @param string $who
 * @param string $when
 * @return string
 */
function sayHello($who, $when)
{
    return "Hello $who, Good $when";
}

$server = new Zend_Rest_Server();
$server-&gt;addFunction('sayHello');
$server-&gt;handle();
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.rest.server.args"></a>60.3.3. Calling a Zend_Rest_Server Service</h3></div></div></div>
<p>
            To call a <code class="classname">Zend_Rest_Server</code> service, you must supply a
            <code class="constant">GET</code>/POST <code class="code">method</code> argument with a value that is the
            method you wish to call. You can then follow that up with any number
            of arguments using either the name of the argument (i.e. "who") or
            using <code class="code">arg</code> following by the numeric position of the
            argument (i.e. "arg1").
        </p>
<div class="note"><table border="0" summary="Note: Numeric index">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Numeric index</th>
</tr>
<tr><td align="left" valign="top"><p>
                Numeric arguments use a 1-based index.
            </p></td></tr>
</table></div>
<p>
            To call <code class="code">sayHello</code> from the example above, you can use either:
        </p>
<p>
            <code class="code">?method=sayHello&amp;who=Davey&amp;when=Day</code>
        </p>
<p>
            or:
        </p>
<p>
            <code class="code">?method=sayHello&amp;arg1=Davey&amp;arg2=Day</code>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.rest.server.customstatus"></a>60.3.4. Sending A Custom Status</h3></div></div></div>
<p>
            When returning values, to return a custom status, you may return an
            array with a <code class="code">status</code> key.
        </p>
<div class="example">
<a name="zend.rest.server.customstatus.example-1"></a><p class="title"><b>Example 60.8. Returning Custom Status</b></p>
<div class="example-contents"><pre class="programlisting">
/**
 * Say Hello
 *
 * @param string $who
 * @param string $when
 * @return array
 */
function sayHello($who, $when)
{
    return array('msg' =&gt; "An Error Occurred", 'status' =&gt; false);
}

$server = new Zend_Rest_Server();
$server-&gt;addFunction('sayHello');
$server-&gt;handle();
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.rest.server.customxml"></a>60.3.5. Returning Custom XML Responses</h3></div></div></div>
<p>
            If you wish to return custom <acronym class="acronym">XML</acronym>, simply return a
            <code class="code">DOMDocument</code>, <code class="code">DOMElement</code> or
            <code class="code">SimpleXMLElement</code> object.
        </p>
<div class="example">
<a name="zend.rest.server.customxml.example-1"></a><p class="title"><b>Example 60.9. Return Custom XML</b></p>
<div class="example-contents"><pre class="programlisting">
/**
 * Say Hello
 *
 * @param string $who
 * @param string $when
 * @return SimpleXMLElement
 */
function sayHello($who, $when)
{
    $xml ='&lt;?xml version="1.0" encoding="ISO-8859-1"?&gt;
&lt;mysite&gt;
    &lt;value&gt;Hey $who! Hope you\'re having a good $when&lt;/value&gt;
    &lt;code&gt;200&lt;/code&gt;
&lt;/mysite&gt;';

    $xml = simplexml_load_string($xml);
    return $xml;
}

$server = new Zend_Rest_Server();
$server-&gt;addFunction('sayHello');

$server-&gt;handle();
</pre></div>
</div>
<br class="example-break"><p>
            The response from the service will be returned without modification
            to the client.
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.rest.client.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.rest.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.search.lucene.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">60.2. Zend_Rest_Client </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Chapter 61. Zend_Search_Lucene</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
