<?php $title = 'setOptions'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">setOptions</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.constructor.phtml">Prev</a> </td>
<th width="60%" align="center">42.7.4. Available Methods</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.set-fallback-autoloader.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.standard-autoloader.methods.set-options"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Name</h2>
<p>setOptions — Set object state based on provided options.</p>
</div>
<div class="refsynopsisdiv">
<h2>Synopsis</h2>
<code class="methodsynopsis"><span class="methodname">setOptions</span>(<span class="methodparam">$options</span>);</code>
</div>
<div class="refsection">
<a name="id37060"></a><h2>setOptions()</h2>
<p>
                    Takes an argument of either an associative array or
                    <code class="interfacename">Traversable</code> object. Recognized keys are detailed
                    under <a class="xref" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.options" title="42.7.3. Configuration Options">Section 42.7.3, “Configuration Options”</a>, with the
                    following behaviors:
                </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                            The <code class="varname">namespaces</code> value will be passed to <a class="link" href="zend.loader.standard-autoloader.methods.register-namespaces.phtml" title="registerNamespaces">registerNamespaces()</a>.
                        </p></li>
<li class="listitem"><p>
                            The <code class="varname">prefixes</code> value will be passed to <a class="link" href="zend.loader.standard-autoloader.methods.register-prefixes.phtml" title="registerPrefixes">registerPrefixes()</a>.
                        </p></li>
<li class="listitem"><p>
                            The <code class="varname">fallback_autoloader</code> value will be passed to <a class="link" href="zend.loader.standard-autoloader.methods.set-fallback-autoloader.phtml" title="setFallbackAutoloader">setFallbackAutoloader()</a>.
                        </p></li>
</ul></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.constructor.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.methods">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.set-fallback-autoloader.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">__construct </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> setFallbackAutoloader</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
