<?php $title = '38.11. The TeraWurfl UserAgent Features Adapter'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">38.11. The TeraWurfl UserAgent Features Adapter</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.http.user-agent-features-device-atlas.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 38. Zend_Http</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.http.user-agent-storage.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.http.user-agent-features-tera-wurfl"></a>38.11. The TeraWurfl UserAgent Features Adapter</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features-tera-wurfl.intro"></a>38.11.1. Overview</h3></div></div></div>
<p>
            <a class="ulink" href="" target="_top">TeraWurfl</a> parses the WURFL database into a MySQL
            database, and provides an API for querying that database for mobile device capabilies.
            The API also performs rigorous caching, leading to excellent performance.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features-tera-wurfl.quick-start"></a>38.11.2. Quick Start</h3></div></div></div>
<p>
            You will need to <a class="ulink" href="http://www.tera-wurfl.com/wiki/index.php/Downloads" target="_top">download</a> and <a class="ulink" href="http://www.tera-wurfl.com/wiki/index.php/Installation" target="_top">install</a>
            TeraWurfl. Make a note of where you install the library
            (<code class="filename">TeraWurfl.php</code>); we recommend installing it in your application's
            <code class="filename">library</code> directory.
        </p>
<p>
            Once installed, the easiest way to use TeraWurfl is to configure it via the application
            resource.
        </p>
<pre class="programlisting">
resources.useragent.terawurfl.terawurfl_lib_dir = APPLICATION_PATH "/../library/"
</pre>
<p>
            If the file is autoloadable, you can also specify an empty configuration in order to
            utilize the adapter.
        </p>
<pre class="programlisting">
resources.useragent.terawurfl[] =
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features-tera-wurfl.options"></a>38.11.3. Configuration Options</h3></div></div></div>
<div class="variablelist">
<p class="title"><b>TeraWurfl API Options</b></p>
<dl class="variablelist">
<dt><span class="term">terawurfl.terawurfl_lib_dir</span></dt>
<dd><p>
                        If using the TeraWurfl API, use this key to specify in which
                        directory the <code class="filename">TeraWurfl.php</code> file exists.
                    </p></dd>
</dl>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features-tera-wurfl.methods"></a>38.11.4. Available Methods</h3></div></div></div>
<div class="variablelist"><dl class="variablelist">
<dt>
<a name="zend.http.user-agent-features-tera-wurfl.methods.get-from-request"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getFromRequest</span>(<span class="methodparam">array $request, array $config</span>);</code>
                </span>
</dt>
<dd><p>
                        Decompose the request in order to return an array of device capabilities.
                    </p></dd>
</dl></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.http.user-agent-features-device-atlas.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.http.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.http.user-agent-storage.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">38.10. The DeviceAtlas UserAgent Features Adapter </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 38.12. The UserAgent Storage Interface</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
