<?php $title = '25.7. How much is my currency?'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">25.7. How much is my currency?</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.currency.number.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 25. Zend_Currency</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.currency.calculation.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.currency.value"></a>25.7. How much is my currency?</h2></div></div></div>
<p>
        When you are working with currencies then you normally want to display an amount of
        money. And when you work with different currencies then you have to do this with three
        different things. The amount you want to display, the precision you want to use, and
        probably the exchange rate.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.currency.value.money"></a>25.7.1. Working with currency values</h3></div></div></div>
<p>
            The currency value, a.k.a. the money, you want to use can easily be set by using the
            <span class="property">value</span> option.
        </p>
<pre class="programlisting">
$currency = new Zend_Currency(
    array(
        'value'    =&gt; 1000,
        'currency' =&gt; 'USD',
    )
);

print $currency; // Could return '$ 1.000'
</pre>
<p>
            Using the <code class="methodname">setFormat()</code> method with this array option, and
            also by using the <code class="methodname">setValue()</code> method you can set the value
            afterwards.
        </p>
<pre class="programlisting">
$currency = new Zend_Currency(
    array(
        'value'    =&gt; 1000,
        'currency' =&gt; 'USD',
    )
);

print $currency-&gt;setValue(2000); // Could return '$ 2.000'
</pre>
<p>
            With the <code class="methodname">getValue()</code> method you will get the actual set
            value.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.currency.value.precision"></a>25.7.2. Using precision on currencies</h3></div></div></div>
<p>
            When working with currencies they you probably also have to handle precision.
            Most currencies use a precision of 2. This means that when you have 100 US dollars
            you could also have 50 cents. The related value is simply a floating value.
        </p>
<pre class="programlisting">
$currency = new Zend_Currency(
    array(
        'value'    =&gt; 1000.50,
        'currency' =&gt; 'USD',
    )
);

print $currency; // Could return '$ 1.000,50'
</pre>
<p>
            Of course, as the default precision is 2, you will get '00' for the decimal value
            when there is no precision to display.
        </p>
<pre class="programlisting">
$currency = new Zend_Currency(
    array(
        'value'    =&gt; 1000,
        'currency' =&gt; 'USD',
    )
);

print $currency; // Could return '$ 1.000,00'
</pre>
<p>
            To get rid of this default precision you could simply use the
            <span class="property">precision</span> option and set it to '0'. And you can set any other
            precision you want to use between 0 and 9. All values will be rounded or streched
            when they don't fit the set precision.
        </p>
<pre class="programlisting">
$currency = new Zend_Currency(
    array(
        'value'     =&gt; 1000,30,
        'currency'  =&gt; 'USD',
        'precision' =&gt; 0
    )
);

print $currency; // Could return '$ 1.000'
</pre>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.currency.number.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.currency.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.currency.calculation.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">25.6. How does the currency look like? </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 25.8. Calculating with currencies</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
