<?php $title = '45.2. Sending via SMTP'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">45.2. Sending via SMTP</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 45. Zend_Mail</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.multiple-emails.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.sending"></a>45.2. Sending via SMTP</h2></div></div></div>
<p>
        To send mail via SMTP, <code class="classname">Zend_Mail_Transport_Smtp</code> needs to be created
        and registered with <code class="classname">Zend_Mail</code> before the
        <code class="methodname">send()</code> method is called. For all remaining
        <code class="methodname">Zend_Mail::send()</code> calls in the current script, the SMTP transport
        will then be used:
    </p>
<div class="example">
<a name="zend.mail.sending.example-1"></a><p class="title"><b>Example 45.3. Sending E-Mail via SMTP</b></p>
<div class="example-contents"><pre class="programlisting">
$tr = new Zend_Mail_Transport_Smtp('mail.example.com');
Zend_Mail::setDefaultTransport($tr);
</pre></div>
</div>
<br class="example-break"><p>
        The <code class="methodname">setDefaultTransport()</code> method and the constructor of
        <code class="classname">Zend_Mail_Transport_Smtp</code> are not expensive. These two lines can be
        processed at script setup time (e.g., config.inc or similar) to configure the behavior of
        the <code class="classname">Zend_Mail</code> class for the rest of the script. This keeps
        configuration information out of the application logic - whether mail is sent via SMTP or
        <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a>, what mail server
        is used, etc.
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mail.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.multiple-emails.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Chapter 45. Zend_Mail </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 45.3. Sending Multiple Mails per SMTP Connection</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
