<?php $title = '61.8. Interoperating with Java Lucene'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">61.8. Interoperating with Java Lucene</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.search.lucene.extending.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 61. Zend_Search_Lucene</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.search.lucene.advanced.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.search.lucene.java-lucene"></a>61.8. Interoperating with Java Lucene</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.file-formats"></a>61.8.1. File Formats</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> index file formats are binary compatible with
            Java Lucene version 1.4 and greater.
        </p>
<p>
            A detailed description of this format is available here:
            <a class="ulink" href="http://lucene.apache.org/java/2_3_0/fileformats.html" target="_top">http://lucene.apache.org/java/2_3_0/fileformats.html</a>
            <a href="#ftn.id47150" class="footnote" name="id47150"><sup class="footnote">[17]</sup></a>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.index-directory"></a>61.8.2. Index Directory</h3></div></div></div>
<p>
            After index creation, the index directory will contain several files:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    The <code class="filename">segments</code> file is a list of index segments.
                </p></li>
<li class="listitem"><p>
                    The <code class="filename">*.cfs</code> files contain index segments.
                    Note! An optimized index always has only one segment.
                </p></li>
<li class="listitem"><p>
                    The <code class="filename">deletable</code> file is a list of files that are no longer
                    used by the index, but which could not be deleted.
                </p></li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.java-lucene.source-code"></a>61.8.3. Java Source Code</h3></div></div></div>
<p>
            The Java program listing below provides an example of how to index a file
            using Java Lucene:
        </p>
<pre class="programlisting">
/**
* Index creation:
*/
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.document.*;

import java.io.*

...

IndexWriter indexWriter = new IndexWriter("/data/my_index",
                                          new SimpleAnalyzer(), true);

...

String filename = "/path/to/file-to-index.txt"
File f = new File(filename);

Document doc = new Document();
doc.add(Field.Text("path", filename));
doc.add(Field.Keyword("modified",DateField.timeToString(f.lastModified())));
doc.add(Field.Text("author", "unknown"));
FileInputStream is = new FileInputStream(f);
Reader reader = new BufferedReader(new InputStreamReader(is));
doc.add(Field.Text("contents", reader));

indexWriter.addDocument(doc);
</pre>
</div>
<div class="footnotes">
<br><hr style="width:100; text-align:left;margin-left: 0">
<div id="ftn.id47150" class="footnote"><p><a href="#id47150" class="para"><sup class="para">[17] </sup></a>
                    The currently supported Lucene index file format version is 2.3 (starting from
                    Zend Framework 1.6).
                </p></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.search.lucene.extending.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.search.lucene.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.search.lucene.advanced.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">61.7. Extensibility </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 61.9. Advanced</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
