<?php $title = '45.6. Attachments'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">45.6. Attachments</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.html-mails.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 45. Zend_Mail</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.adding-recipients.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.attachments"></a>45.6. Attachments</h2></div></div></div>
<p>
        Files can be attached to an e-mail using the <code class="methodname">createAttachment()</code>
        method. The default behavior of <code class="classname">Zend_Mail</code> is to assume the
        attachment is a binary object (<span class="property">application/octet-stream</span>), that it
        should be transferred with base64 encoding, and that it is handled as an attachment. These
        assumptions can be overridden by passing more parameters to
        <code class="methodname">createAttachment()</code>:
    </p>
<div class="example">
<a name="zend.mail.attachments.example-1"></a><p class="title"><b>Example 45.8. E-Mail Messages with Attachments</b></p>
<div class="example-contents"><pre class="programlisting">
$mail = new Zend_Mail();
// build message...
$mail-&gt;createAttachment($someBinaryString);
$mail-&gt;createAttachment($myImage,
                        'image/gif',
                        Zend_Mime::DISPOSITION_INLINE,
                        Zend_Mime::ENCODING_BASE64);
</pre></div>
</div>
<br class="example-break"><p>
        If you want more control over the <acronym class="acronym">MIME</acronym> part generated for this
        attachment you can use the return value of <code class="methodname">createAttachment()</code> to
        modify its attributes. The <code class="methodname">createAttachment()</code> method returns a
        <code class="classname">Zend_Mime_Part</code> object:
    </p>
<pre class="programlisting">
$mail = new Zend_Mail();

$at = $mail-&gt;createAttachment($myImage);
$at-&gt;type        = 'image/gif';
$at-&gt;disposition = Zend_Mime::DISPOSITION_INLINE;
$at-&gt;encoding    = Zend_Mime::ENCODING_BASE64;
$at-&gt;filename    = 'test.gif';

$mail-&gt;send();
</pre>
<p>
        An alternative is to create an instance of <code class="classname">Zend_Mime_Part</code> and add it
        with <code class="methodname">addAttachment()</code>:
    </p>
<pre class="programlisting">
$mail = new Zend_Mail();

$at = new Zend_Mime_Part($myImage);
$at-&gt;type        = 'image/gif';
$at-&gt;disposition = Zend_Mime::DISPOSITION_INLINE;
$at-&gt;encoding    = Zend_Mime::ENCODING_BASE64;
$at-&gt;filename    = 'test.gif';

$mail-&gt;addAttachment($at);

$mail-&gt;send();
</pre>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.html-mails.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mail.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.adding-recipients.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">45.5. HTML E-Mail </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 45.7. Adding Recipients</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
