<?php $title = '73.3. Zend_Tool Project Providers'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">73.3. Zend_Tool Project Providers</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.tool.project.create-a-project.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 73. Zend_Tool_Project</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.tool.project.internals.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.tool.project.providers"></a>73.3. Zend_Tool Project Providers</h2></div></div></div>
<p>
        Below is a table of all of the providers shipped with
        <code class="classname">Zend_Tool_Project</code>.
    </p>
<div class="table">
<a name="zend.tool.project.project-provider"></a><p class="title"><b>Table 73.2. Project Provider Options</b></p>
<div class="table-contents"><table class="table" summary="Project Provider Options" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Provider Name</th>
<th>Available Actions</th>
<th>Parameters</th>
<th>
<acronym class="acronym">CLI</acronym> Usage</th>
</tr></thead>
<tbody>
<tr>
<td>Controller</td>
<td>Create</td>
<td>create - [name, indexActionIncluded=true]</td>
<td><span class="command"><strong>zf create controller foo</strong></span></td>
</tr>
<tr>
<td>Action</td>
<td>Create</td>
<td>create - [name, controllerName=index, viewIncluded=true]</td>
<td>
                        <span class="command"><strong>zf create action bar foo</strong></span>
                        (or <span class="command"><strong>zf create action --name bar --controlller-name=foo</strong></span>)
                    </td>
</tr>
<tr>
<td>Controller</td>
<td>Create</td>
<td>create - [name, indexActionIncluded=true]</td>
<td><span class="command"><strong>zf create controller foo</strong></span></td>
</tr>
<tr>
<td>Profile</td>
<td>Show</td>
<td>show - []</td>
<td><span class="command"><strong>zf show profile</strong></span></td>
</tr>
<tr>
<td>View</td>
<td>Create</td>
<td>create - [controllerName,actionNameOrSimpleName]</td>
<td>
                        <span class="command"><strong>zf create view foo bar</strong></span>
                        (or <span class="command"><strong>zf create view -c foo -a bar</strong></span>)
                    </td>
</tr>
<tr>
<td>Test</td>
<td>Create / Enable / Disable</td>
<td>create - [libraryClassName]</td>
<td>
                        <span class="command"><strong>zf create test My_Foo_Baz</strong></span> /
                        <span class="command"><strong>zf disable test</strong></span> /
                        <span class="command"><strong>zf enable test</strong></span>
                    </td>
</tr>
<tr>
<td>DbTable</td>
<td>Create</td>
<td>create - [libraryClassName, tableName, ModuleName=null, forceOverwrite=false]</td>
<td>
                        <span class="command"><strong>zf create db-table FooClass FooTableName BarModule force-overwrite</strong></span> /
                        <span class="command"><strong>zf create db-table FooClass FooTableName BarModule</strong></span> /
                        <span class="command"><strong>zf create db-table FooClass FooTableName</strong></span> /
                        <span class="command"><strong>zf create db-table FooClass FooTableName --force-overwrite=true</strong></span> /
                        <span class="command"><strong>zf create db-table.from-database BarModule force-overwrite </strong></span> /
                        <span class="command"><strong>zf create db-table.from-database BarModule </strong></span> /
                        <span class="command"><strong>zf create db-table.from-database --force-overwrite=true </strong></span>
                    </td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.tool.project.create-a-project.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.tool.project.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.tool.project.internals.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">73.2. Create A Project </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 73.4. Zend_Tool_Project Internals</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
