<?php $title = 'registerAutoloadMaps'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">registerAutoloadMaps</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.register-autoload-map.phtml">Prev</a> </td>
<th width="60%" align="center">42.8.4. Available Methods</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.class-map-autoloader.methods.get-autoload-map.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.class-map-autoloader.methods.register-autoload-maps"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Name</h2>
<p>registerAutoloadMaps — Register multiple class maps at once</p>
</div>
<div class="refsynopsisdiv">
<h2>Synopsis</h2>
<code class="methodsynopsis"><span class="methodname">registerAutoloadMaps</span>(<span class="methodparam">$maps</span>);</code>
</div>
<div class="refsection">
<a name="id37254"></a><h2>registerAutoloadMaps()</h2>
<p>
                    Register multiple class maps with the autoloader. Expects either an array or
                    <code class="interfacename">Traversable</code> object; it then iterates over the
                    argument and passes each value to <a class="link" href="zend.loader.class-map-autoloader.methods.register-autoload-map.phtml" title="registerAutoloadMap">registerAutoloadMap()</a>.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.register-autoload-map.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.class-map-autoloader.phtml#zend.loader.class-map-autoloader.methods">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.class-map-autoloader.methods.get-autoload-map.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">registerAutoloadMap </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> getAutoloadMap</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
