<?php $title = 'registerPrefix'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">registerPrefix</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.register-namespaces.phtml">Prev</a> </td>
<th width="60%" align="center">42.7.4. Available Methods</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.register-prefixes.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.standard-autoloader.methods.register-prefix"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Name</h2>
<p>registerPrefix — Register a vendor prefix with the autoloader.</p>
</div>
<div class="refsynopsisdiv">
<h2>Synopsis</h2>
<code class="methodsynopsis"><span class="methodname">registerPrefix</span>(<span class="methodparam">$prefix, $directory</span>);</code>
</div>
<div class="refsection">
<a name="id37130"></a><h2>registerPrefix()</h2>
<p>
                    Register a vendor prefix with the autoloader, pointing it to a specific
                    directory on the filesystem for class resolution. For classes matching that
                    initial vendor prefix, the autoloader will then perform lookups within that
                    directory.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.register-namespaces.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.methods">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.register-prefixes.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">registerNamespaces </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> registerPrefixes</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
