<?php $title = 'Chapter 29. Zend_Dojo'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 29. Zend_Dojo</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.debug.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.dojo.data.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.dojo"></a>Chapter 29. Zend_Dojo</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.dojo.phtml#zend.dojo.introduction">29.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.dojo.data.phtml">29.2. Zend_Dojo_Data: dojo.data Envelopes</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.dojo.data.phtml#zend.dojo.data.usage">29.2.1. Zend_Dojo_Data Usage</a></span></dt>
<dt><span class="sect2"><a href="zend.dojo.data.phtml#zend.dojo.data.metadata">29.2.2. Adding metadata to your containers</a></span></dt>
<dt><span class="sect2"><a href="zend.dojo.data.phtml#zend.dojo.data.advanced">29.2.3. Advanced Use Cases</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.dojo.data.phtml#zend.dojo.data.advanced.methods">29.2.3.1. Available Methods</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.dojo.view.phtml">29.3. Dojo View Helpers</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.dojo.view.phtml#zend.dojo.view.dojo">29.3.1. dojo() View Helper</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.dojo.view.phtml#zend.dojo.view.dojo.declarative">29.3.1.1. Programmatic and Declarative Usage of Dojo</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.view.phtml#zend.dojo.view.dojo.themes">29.3.1.2. Themes</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.view.phtml#zend.dojo.view.dojo.layers">29.3.1.3. Using Layers (Custom Builds)</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.view.phtml#zend.dojo.view.dojo.methods">29.3.1.4. Methods Available</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.dojo.view.phtml#zend.dojo.view.dijit">29.3.2. Dijit-Specific View Helpers</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.dojo.view.phtml#zend.dojo.view.dijit.layout">29.3.2.1. Dijit Layout Elements</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.view.phtml#zend.dojo.view.dijit.form">29.3.2.2. Dijit Form Elements</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.view.phtml#zend.dojo.view.dijit.custom">29.3.2.3. Custom Dijits</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.dojo.form.phtml">29.4. Dojo Form Elements and Decorators</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.dojo.form.phtml#zend.dojo.form.decorators">29.4.1. Dijit-Specific Form Decorators</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.decorators.dijitElement">29.4.1.1. DijitElement Decorator</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.decorators.dijitForm">29.4.1.2. DijitForm Decorator</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.decorators.dijitContainer">29.4.1.3. DijitContainer-based Decorators</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.dojo.form.phtml#zend.dojo.form.elements">29.4.2. Dijit-Specific Form Elements</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.button">29.4.2.1. Button</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.checkBox">29.4.2.2. CheckBox</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.comboBox">29.4.2.3. ComboBox and FilteringSelect</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.currencyTextBox">29.4.2.4. CurrencyTextBox</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.dateTextBox">29.4.2.5. DateTextBox</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.editor">29.4.2.6. Editor</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.horizontalSlider">29.4.2.7. HorizontalSlider</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.numberSpinner">29.4.2.8. NumberSpinner</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.numberTextBox">29.4.2.9. NumberTextBox</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.passwordTextBox">29.4.2.10. PasswordTextBox</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.radioButton">29.4.2.11. RadioButton</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.simpletextarea">29.4.2.12. SimpleTextarea</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.slider">29.4.2.13. Slider abstract element</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.submitButton">29.4.2.14. SubmitButton</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.textBox">29.4.2.15. TextBox</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.textarea">29.4.2.16. Textarea</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.timeTextBox">29.4.2.17. TimeTextBox</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.validationTextBox">29.4.2.18. ValidationTextBox</a></span></dt>
<dt><span class="sect3"><a href="zend.dojo.form.phtml#zend.dojo.form.elements.verticalSlider">29.4.2.19. VerticalSlider</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.dojo.form.phtml#zend.dojo.form.examples">29.4.3. Dojo Form Examples</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.dojo.build-layers.phtml">29.5. Zend_Dojo build layer support</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.introduction">29.5.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.usage">29.5.2. Generating Custom Module Layers with Zend_Dojo_BuildLayer</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.usage.options">29.5.2.1. BuildLayer options</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.usage.options.view">29.5.2.1.1. Setting the view object</a></span></dt>
<dt><span class="sect4"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.usage.options.layername">29.5.2.1.2. Setting the layer name</a></span></dt>
<dt><span class="sect4"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.usage.options.onload">29.5.2.1.3. Including onLoad events in the generated layer</a></span></dt>
<dt><span class="sect4"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.usage.options.javascript">29.5.2.1.4. Including captured JavaScript in the generated layer</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect2"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.profiles">29.5.3. Generating Build Profiles with Zend_Dojo_BuildLayer</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.dojo.build-layers.phtml#zend.dojo.build-layers.profiles.options">29.5.3.1. Build Profile options</a></span></dt></dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.dojo.introduction"></a>29.1. Introduction</h2></div></div></div>
<p>
        Zend Framework ships <a class="ulink" href="http://dojotoolkit.org" target="_top">Dojo Toolkit</a> to support
        out-of-the-box rich internet application development. Integration
        points with Dojo include:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p><acronym class="acronym">JSON-RPC</acronym> support</p></li>
<li class="listitem"><p><span class="command"><strong>dojo.data</strong></span> compatibility</p></li>
<li class="listitem"><p>View helper to help setup the Dojo environment</p></li>
<li class="listitem"><p>Dijit-specific <code class="classname">Zend_View</code> helpers</p></li>
<li class="listitem"><p>Dijit-specific <code class="classname">Zend_Form</code> elements and decorators</p></li>
</ul></div>
<p>
        The Dojo distribution itself may be found in the
        <code class="filename">externals/dojo/</code> directory of Zend Framework's
        distribution. This is a source distribution, which includes Dojo's full
        javascript source, unit tests, and build tools. You can symlink this
        into your javascript directory, copy it, or use the build tool to create
        your own custom build to include in your project. Alternatively, you can
        use one of the Content Delivery Networks that offer Dojo (Zend Framework supports
        both the official <acronym class="acronym">AOL</acronym> <acronym class="acronym">CDN</acronym> as well as the Google
        <acronym class="acronym">CDN</acronym>).
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.debug.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.dojo.data.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Chapter 28. Zend_Debug </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 29.2. Zend_Dojo_Data: dojo.data Envelopes</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
