<?php $title = 'Chapter 28. Zend_Debug'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 28. Zend_Debug</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.db.table.definition.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.dojo.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.debug"></a>Chapter 28. Zend_Debug</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc"><dt><span class="sect1"><a href="zend.debug.phtml#zend.debug.dumping">28.1. Dumping Variables</a></span></dt></dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.debug.dumping"></a>28.1. Dumping Variables</h2></div></div></div>
<p>
        The static method <code class="methodname">Zend_Debug::dump()</code> prints or returns
        information about an expression. This simple technique of debugging is
        common because it is easy to use in an ad hoc fashion and requires no
        initialization, special tools, or debugging environment.
    </p>
<div class="example">
<a name="zend.debug.dumping.example"></a><p class="title"><b>Example 28.1. Example of dump() method</b></p>
<div class="example-contents"><pre class="programlisting">
Zend_Debug::dump($var, $label = null, $echo = true);
</pre></div>
</div>
<br class="example-break"><p>
        The <code class="varname">$var</code> argument specifies the expression or variable
        about which the <code class="methodname">Zend_Debug::dump()</code> method outputs
        information.
    </p>
<p>
        The <code class="varname">$label</code> argument is a string to be prepended to the
        output of <code class="methodname">Zend_Debug::dump()</code>. It may be useful, for
        example, to use labels if you are dumping information about multiple
        variables on a given screen.
    </p>
<p>
        The boolean <code class="varname">$echo</code> argument specifies whether the output
        of <code class="methodname">Zend_Debug::dump()</code> is echoed or not.
        If <code class="constant">TRUE</code>, the output is echoed.
        Regardless of the value of the <code class="varname">$echo</code> argument, the
        return value of this method contains the output.
    </p>
<p>
        It may be helpful to understand that
        <code class="methodname">Zend_Debug::dump()</code> method wraps the <acronym class="acronym">PHP</acronym> function
        <a class="ulink" href="http://php.net/var_dump" target="_top"><code class="methodname">var_dump()</code></a>.
        If the output stream is detected as a web presentation,
        the output of <code class="methodname">var_dump()</code> is escaped using <a class="ulink" href="http://php.net/htmlspecialchars" target="_top"><code class="methodname">htmlspecialchars()</code></a>
        and wrapped with (X)HTML <span class="command"><strong>&lt;pre&gt;</strong></span> tags.
    </p>
<div class="tip"><table border="0" summary="Tip: Debugging with Zend_Log">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Tip]" src="images/tip.png"></td>
<th align="left">Debugging with Zend_Log</th>
</tr>
<tr><td align="left" valign="top">
<p>
            Using <code class="methodname">Zend_Debug::dump()</code> is best for ad hoc
            debugging during software development. You can add code to dump
            a variable and then remove the code very quickly.
        </p>
<p>
            Also consider the <a class="link" href="zend.log.phtml#zend.log.overview" title="44.1. Overview">Zend_Log</a>
            component when writing more permanent debugging code. For example,
            you can use the <code class="constant">DEBUG</code> log level and the
            <a class="link" href="zend.log.writers.phtml#zend.log.writers.stream" title="44.2.1. Writing to Streams">stream log writer</a> to
            output the string returned by <code class="methodname">Zend_Debug::dump()</code>.
        </p>
</td></tr>
</table></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.db.table.definition.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.dojo.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">27.9. Zend_Db_Table_Definition </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Chapter 29. Zend_Dojo</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
