<?php $title = 'Chapter 80. Zend_XmlRpc'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 80. Zend_XmlRpc</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.wildfire.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.xmlrpc.client.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.xmlrpc"></a>Chapter 80. Zend_XmlRpc</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.xmlrpc.phtml#zend.xmlrpc.introduction">80.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.xmlrpc.client.phtml">80.2. Zend_XmlRpc_Client</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.introduction">80.2.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.method-calls">80.2.2. Method Calls</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.value.parameters">80.2.3. Types and Conversions</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.value.parameters.php-native">80.2.3.1. PHP Native Types as Parameters</a></span></dt>
<dt><span class="sect3"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.value.parameters.xmlrpc-value">80.2.3.2. Zend_XmlRpc_Value Objects as Parameters</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.requests-and-responses">80.2.4. Server Proxy Object</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.error-handling">80.2.5. Error Handling</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.error-handling.http">80.2.5.1. HTTP Errors</a></span></dt>
<dt><span class="sect3"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.error-handling.faults">80.2.5.2. XML-RPC Faults</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.introspection">80.2.6. Server Introspection</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.request-to-response">80.2.7. From Request to Response</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.http-client">80.2.8. HTTP Client and Testing</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.xmlrpc.server.phtml">80.3. Zend_XmlRpc_Server</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.introduction">80.3.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.usage">80.3.2. Basic Usage</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.structure">80.3.3. Server Structure</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.anatomy">80.3.4. Anatomy of a webservice</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.anatomy.general">80.3.4.1. General considerations</a></span></dt>
<dt><span class="sect3"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.anatomy.expose">80.3.4.2. What to expose?</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.conventions">80.3.5. Conventions</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.namespaces">80.3.6. Utilizing Namespaces</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.request">80.3.7. Custom Request Objects</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.response">80.3.8. Custom Responses</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.fault">80.3.9. Handling Exceptions via Faults</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.caching">80.3.10. Caching Server Definitions Between Requests</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.use">80.3.11. Usage Examples</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.performance">80.3.12. Performance optimization</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.xmlrpc.introduction"></a>80.1. Introduction</h2></div></div></div>
<p>
        From its <a class="ulink" href="http://www.xmlrpc.com/" target="_top">home page</a>,
        <acronym class="acronym">XML-RPC</acronym> is described as a "...remote procedure calling using
        <acronym class="acronym">HTTP</acronym> as the transport and <acronym class="acronym">XML</acronym> as the encoding.
        <acronym class="acronym">XML-RPC</acronym> is designed to be as simple as possible, while allowing complex
        data structures to be transmitted, processed and returned."
    </p>
<p>
        Zend Framework provides support for both consuming remote <acronym class="acronym">XML-RPC</acronym>
        services and building new <acronym class="acronym">XML-RPC</acronym> servers.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.wildfire.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.xmlrpc.client.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Chapter 79. Zend_Wildfire </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 80.2. Zend_XmlRpc_Client</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
