<?php $title = 'Chapter 49. Zend_Mime'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 49. Zend_Mime</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.memory.memory-objects.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mime.message.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.mime"></a>Chapter 49. Zend_Mime</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.mime.phtml#zend.mime.mime">49.1. Zend_Mime</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.mime.phtml#zend.mime.mime.introduction">49.1.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.mime.phtml#zend.mime.mime.static">49.1.2. Static Methods and Constants</a></span></dt>
<dt><span class="sect2"><a href="zend.mime.phtml#zend.mime.mime.instantiation">49.1.3. Instantiating Zend_Mime</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.mime.message.phtml">49.2. Zend_Mime_Message</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.mime.message.phtml#zend.mime.message.introduction">49.2.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.mime.message.phtml#zend.mime.message.instantiation">49.2.2. Instantiation</a></span></dt>
<dt><span class="sect2"><a href="zend.mime.message.phtml#zend.mime.message.addparts">49.2.3. Adding MIME Parts</a></span></dt>
<dt><span class="sect2"><a href="zend.mime.message.phtml#zend.mime.message.bondary">49.2.4. Boundary handling</a></span></dt>
<dt><span class="sect2"><a href="zend.mime.message.phtml#zend.mime.message.parse">49.2.5. parsing a string to create a Zend_Mime_Message object (experimental)</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.mime.part.phtml">49.3. Zend_Mime_Part</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.mime.part.phtml#zend.mime.part.introduction">49.3.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.mime.part.phtml#zend.mime.part.instantiation">49.3.2. Instantiation</a></span></dt>
<dt><span class="sect2"><a href="zend.mime.part.phtml#zend.mime.part.methods">49.3.3. Methods for rendering the message part to a string</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mime.mime"></a>49.1. Zend_Mime</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mime.mime.introduction"></a>49.1.1. Introduction</h3></div></div></div>
<p>
            <code class="classname">Zend_Mime</code> is a support class for handling multipart
            <acronym class="acronym">MIME</acronym> messages. It is used by <a class="link" href="zend.mail.phtml" title="Chapter 45. Zend_Mail"><code class="classname">Zend_Mail</code></a> and <a class="link" href="zend.mime.message.phtml" title="49.2. Zend_Mime_Message"><code class="classname">Zend_Mime_Message</code></a> and may
            be used by applications requiring <acronym class="acronym">MIME</acronym> support.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mime.mime.static"></a>49.1.2. Static Methods and Constants</h3></div></div></div>
<p>
            <code class="classname">Zend_Mime</code> provides a simple set of static helper methods to work
            with <acronym class="acronym">MIME</acronym>:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">Zend_Mime::isPrintable()</code>: Returns
                        <code class="constant">TRUE</code> if the given string contains no unprintable
                        characters, <code class="constant">FALSE</code> otherwise.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Mime::encode()</code>: Encodes a string with
                        specified encoding.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Mime::encodeBase64()</code>: Encodes a string into
                        base64 encoding.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Mime::encodeQuotedPrintable()</code>: Encodes a
                        string with the quoted-printable mechanism.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Mime::encodeBase64Header()</code>: Encodes a string
                        into base64 encoding for Mail Headers.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Mime::encodeQuotedPrintableHeader()</code>: Encodes
                        a string with the quoted-printable mechanism for Mail Headers.
                    </p></li>
</ul></div>
<p>
        </p>
<p>
            <code class="classname">Zend_Mime</code> defines a set of constants commonly used with
            <acronym class="acronym">MIME</acronym> Messages:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::TYPE_OCTETSTREAM</code>: 'application/octet-stream'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::TYPE_TEXT</code>: 'text/plain'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::TYPE_HTML</code>: 'text/html'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::ENCODING_7BIT</code>: '7bit'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::ENCODING_8BIT</code>: '8bit'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::ENCODING_QUOTEDPRINTABLE</code>: 'quoted-printable'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::ENCODING_BASE64</code>: 'base64'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::DISPOSITION_ATTACHMENT</code>: 'attachment'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::DISPOSITION_INLINE</code>: 'inline'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::MULTIPART_ALTERNATIVE</code>:
                        'multipart/alternative'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::MULTIPART_MIXED</code>: 'multipart/mixed'
                    </p></li>
<li class="listitem"><p>
                        <code class="constant">Zend_Mime::MULTIPART_RELATED</code>: 'multipart/related'
                    </p></li>
</ul></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mime.mime.instantiation"></a>49.1.3. Instantiating Zend_Mime</h3></div></div></div>
<p>
            When Instantiating a <code class="classname">Zend_Mime</code> Object, a <acronym class="acronym">MIME</acronym>
            boundary is stored that is used for all subsequent non-static method calls on that
            object. If the constructor is called with a string parameter, this value
            is used as a <acronym class="acronym">MIME</acronym> boundary. If not, a random <acronym class="acronym">MIME</acronym>
            boundary is generated during construction time.
        </p>
<p>
            A <code class="classname">Zend_Mime</code> object has the following Methods:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">boundary()</code>: Returns the <acronym class="acronym">MIME</acronym>
                        boundary string.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">boundaryLine()</code>: Returns the complete
                        <acronym class="acronym">MIME</acronym> boundary line.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">mimeEnd()</code>: Returns the complete
                        <acronym class="acronym">MIME</acronym> end boundary line.
                    </p></li>
</ul></div>
<p>
        </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.memory.memory-objects.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mime.message.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">48.3. Memory Objects </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 49.2. Zend_Mime_Message</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
