<?php $title = '50.4. Zend_Mobile_Push_Mpns'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">50.4. Zend_Mobile_Push_Mpns</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mobile.push.gcm.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 50. Zend_Mobile_Push</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.navigation.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mobile.push.mpns"></a>50.4. Zend_Mobile_Push_Mpns</h2></div></div></div>
<p>
        <code class="classname">Zend_Mobile_Push_Mpns</code> provides the ability to
        send push notifications to Windows Phone.  MPNS allows the sending of
        3 different types of notifications; which common behavior is in the
        <code class="classname">Zend_Mobile_Push_Message_Mpns</code> base.  Followed by
        specific classes for Raw, Toast and Tile notifications.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mobile.push.mpns.server"></a>50.4.1. Pushing Messages</h3></div></div></div>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Note</th>
</tr>
<tr><td align="left" valign="top"><p>Prior to pushing messages; you must implement the practices
                outlined on <a class="ulink" href="http://msdn.microsoft.com/en-us/library/hh202940(v=VS.92).aspx" target="_top">Receiving
                Push Notifications for Windows Phone</a>. 
            </p></td></tr>
</table></div>
<p>
            When implementing MPNS; you have several components that
            you will utilize.  <code class="classname">Zend_Mobile_Push_Mpns</code>
            which contains the server components and
            <code class="classname">Zend_Mobile_Push_Message_Mpns_Raw</code> which
            allows you to send <a class="ulink" href="http://msdn.microsoft.com/en-us/library/hh202977(v=VS.92).aspx" target="_top">raw
            notifications</a>,
            <code class="classname">Zend_Mobile_Push_Message_Mpns_Toast</code> which
            allows you to send <a class="ulink" href="http://msdn.microsoft.com/en-us/library/hh202967(v=VS.92).aspx" target="_top">toast
            notifications</a>, and
            <code class="classname">Zend_Mobile_Push_Message_Mpns_Tile</code> which
            allows you to send <a class="ulink" href="http://msdn.microsoft.com/en-us/library/hh202970(v=VS.92).aspx" target="_top">tile
            notifications</a>.  Each message sent must do an HTTP request;
            so remember this when sending in large batches.
        </p>
<p>
            The actual implementation of the code is fairly minimal; however,
            considerations to error handling must be taken.
        </p>
<pre class="programlisting">
$mpns = new Zend_Mobile_Push_Mpns();
$messages = array();

// raw notification
$message = new Zend_Mobile_Push_Message_Mpns_Raw();
$message-&gt;setToken('http://sn1.notify.live.net/throttledthirdparty/01.00/THETOKEN');
$message-&gt;setMessage('&lt;notification&gt;&lt;foo id="bar" /&gt;&lt;/notification&gt;');
$messages[] = $message;

// toast message
$message = new Zend_Mobile_Push_Message_Mpns_Toast();
$message-&gt;setToken('http://sn1.notify.live.net/throttledthirdparty/01.00/THETOKEN');
$message-&gt;setTitle('Foo');
$message-&gt;setMessage('Bar');
$messages[] = $message;

// tile message
$message = new Zend_Mobile_Push_Mpns_Tile();
$message-&gt;setToken('http://sn1.notify.live.net/throttledthirdparty/01.00/THETOKEN');
$message-&gt;setBackgroundImage('foo.bar');
$message-&gt;setCount(1);
$message-&gt;setTitle('Bar Foo');
$messages[] = $message;

foreach ($messages as $m) {
    try {
        $mpns-&gt;send($m);
    } catch (Zend_Mobile_Push_Exception_InvalidToken $e) {
        echo 'Remove token: ' . $m-&gt;getToken() . PHP_EOL;
    } catch (Zend_Mobile_Push_Exception $e) {
        echo 'Error occurred, token: ' . $m-&gt;getToken() . ' - ' . $e-&gt;getMessage() . PHP_EOL;
    }
}
</pre>
<div class="table">
<a name="zend.mobile.push.mpns.server.exceptions"></a><p class="title"><b>Table 50.5. Exceptions and Remediation Techniques</b></p>
<div class="table-contents"><table class="table" summary="Exceptions and Remediation Techniques" border="1">
<colgroup>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th align="left">Exception</th>
<th align="left">Meaning</th>
<th align="left">Handling</th>
</tr></thead>
<tbody>
<tr>
<td align="left">Zend_Mobile_Push_Exception</td>
<td align="left">These types of exceptions are more generic in nature
                        and are thrown either from MPNS or internally on input
                        validation</td>
<td align="left">Read the message and determine remediation steps.</td>
</tr>
<tr>
<td align="left">Zend_Mobile_Push_Exception_DeviceQuotaExceeded</td>
<td align="left">You have sent too many messages to this device;
                            you may retry again later.</td>
<td align="left">Try again later or implement <a class="ulink" href="http://en.wikipedia.org/wiki/Exponential_backoff" target="_top">
                            Exponential Backoff
                        </a>.</td>
</tr>
<tr>
<td align="left">Zend_Mobile_Push_Exception_InvalidPayload</td>
<td align="left">Generally the payload will not throw an exception
                        unless the size of the payload is too large or it is missing
                        required content.</td>
<td align="left">Check the size of the payload is within the
                        requirements of MPNS</td>
</tr>
<tr>
<td align="left">Zend_Mobile_Push_Exception_InvalidToken</td>
<td align="left">Any form of an invalid token will be if the
                            device is no longer subscribed, inactive or not
                            valid.</td>
<td align="left">In some cases you may attempt to resend in an
                            hour; this will be stated in the exception.
                            Otherwise you will want to remove the token from
                            being sent to again.</td>
</tr>
<tr>
<td align="left">Zend_Mobile_Push_Exception_QuotaExceeded</td>
<td align="left">You have reached the per-day throttling.</td>
<td align="left">Per-day throttling is only on unauthenticated web
                        services; you will need to <a class="ulink" href="http://msdn.microsoft.com/en-us/library/ff941099(v=vs.92).aspx" target="_top">register
                        your application for notifications</a>.</td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mobile.push.mpns.message"></a>50.4.2. Advanced Messages</h3></div></div></div>
<p>
            MPNS provides the ability for sending more advanced messages; for
            instance the examples above show the most basic implementation of a
            message.  Zend_Mobile_Push_Message_Mpns_* allows you to do far more
            advanced messaging outlined below.
        </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.mobile.push.mpns.message.tile"></a>50.4.2.1. Tile Messages</h4></div></div></div>
<p>
                Tile messages have additional optional attributes for Windows
                Phone 7.1+; you must ensure that you are sending to a device
                with the proper version otherwise your notification will fail.
            </p>
<pre class="programlisting">
$message = new Zend_Mobile_Push_Message_Mpns_Tile();
$message-&gt;setToken('http://sn1.notify.live.net/throttledthirdparty/01.00/THETOKEN'); // REPLACE WITH NOTIFICATION URI FROM MPNS
$message-&gt;setBackgroundImage('foo.jpg');
$message-&gt;setCount(1);
$message-&gt;setTitle('Bar');

// other optional attributes for wp7.1+
$message-&gt;setTileId('/Foo.xaml');
$message-&gt;setBackBackgroundImage('blue.jpg');
$message-&gt;setBackTitle('Bar');
$message-&gt;setBackContent('Foo Bar');
    </pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.mobile.push.mpns.message.toast"></a>50.4.2.2. Toast Messages</h4></div></div></div>
<p>
                Toast messages have additional optional attributes for Windows
                Phone 7.1+; you must ensure that you are sending to a device
                with the proper version otherwise your notification will fail.
            </p>
<pre class="programlisting">
$message = new Zend_Mobile_Push_Message_Mpns_Toast();
$message-&gt;setToken('http://sn1.notify.live.net/throttledthirdparty/01.00/THETOKEN'); // REPLACE WITH NOTIFICATION URI FROM MPNS
$message-&gt;setTitle('Foo');
$message-&gt;setMessage('Bar');

// optional attributes for wp7.1+
$message-&gt;setParams('?bar=foo'); //optional parameters
</pre>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mobile.push.gcm.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mobile.push.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.navigation.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">50.3. Zend_Mobile_Push_Gcm </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Chapter 51. Zend_Navigation</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
