<?php $title = '__construct'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">__construct</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.phtml">Prev</a> </td>
<th width="60%" align="center">42.7.4. Available Methods</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.set-options.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.standard-autoloader.methods.constructor"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Name</h2>
<p>__construct — Initialize a new instance of the object</p>
</div>
<div class="refsynopsisdiv">
<h2>Synopsis</h2>
<code class="methodsynopsis"><span class="methodname">__construct</span>(<span class="methodparam">$options = null</span>);</code>
</div>
<div class="refsection">
<a name="id37045"></a><h2>Constructor</h2>
<p>
                    Takes an optional <code class="varname">$options</code> argument. This argument may be an
                    associative array or <code class="interfacename">Traversable</code> object. If not
                    null, the argument is passed to <a class="link" href="zend.loader.standard-autoloader.methods.set-options.phtml" title="setOptions"><code class="methodname">setOptions()</code></a>.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.methods">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.set-options.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">42.7. The StandardAutoloader </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> setOptions</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
