<?php $title = '57.6. Stomp'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">57.6. Stomp</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.queue.custom.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 57. Zend_Queue</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.reflection.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.queue.stomp"></a>57.6. Stomp</h2></div></div></div>
<p>
        <code class="classname">Zend_Queue_Stomp</code> provides a basic client to
        communicate with <a class="ulink" href="http://stomp.codehaus.org/" target="_top">Stomp</a>
        compatible servers. Some servers, such as Apache ActiveMQ and RabbitMQ, will
        allow you to communicate by other methods, such as <acronym class="acronym">HTTP</acronym>,
        and <acronym class="acronym">XMPP</acronym>.
    </p>
<p>
        The Stomp protocol provides <a class="ulink" href="http://stomp.codehaus.org/StompConnect" target="_top">StompConnect</a>
        which supports any <a class="ulink" href="http://java.sun.com/products/jms/" target="_top"> Java
            Message Service (JMS)</a> provider.
        Stomp is supported by
        <a class="ulink" href="http://activemq.apache.org/" target="_top">Apache ActiveMQ</a>,
        <a class="ulink" href="http://www.rabbitmq.com/" target="_top">RabbitMQ</a>,
        <a class="ulink" href="http://stompserver.rubyforge.org/" target="_top">stompserver</a>, and
        <a class="ulink" href="http://www.germane-software.com/software/Java/Gozirra/" target="_top">Gozirra</a>.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.queue.adapters-configuration.stomp"></a>57.6.1. Stomp - Supporting classes</h3></div></div></div>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="classname">Zend_Queue_Stomp_Frame</code>. This class
                    provides the basic functions for manipulating a Stomp Frame.
                </p></li>
<li class="listitem"><p>
                    <code class="classname">Zend_Queue_Stomp_Client</code>. This class
                    provides the basic functions to
                    <code class="methodname">send()</code> and
                    <code class="methodname">receive()</code>
                    <code class="classname">Zend_Queue_Stomp_Frame</code>s to and from a
                    Stomp compatible server.
                </p></li>
</ul></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.queue.custom.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.queue.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.reflection.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">57.5. Customizing Zend_Queue </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Chapter 58. Zend_Reflection</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
