<?php $title = '26.5. Creation of Dates'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">26.5. Creation of Dates</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.date.overview.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 26. Zend_Date</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.date.constants.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.date.creation"></a>26.5. Creation of Dates</h2></div></div></div>
<p>
        <code class="classname">Zend_Date</code> provides several different ways to create a new instance of
        itself. As there are different needs the most convenient ways will be shown in this chapter.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.date.creation.actual"></a>26.5.1. Create the Actual Date</h3></div></div></div>
<p>
            The simplest way of creating a date object is to create the actual date. You can either
            create a new instance with <span class="command"><strong>new Zend_Date()</strong></span> or use the convenient
            static method <code class="methodname">Zend_Date::now()</code> which both will return the
            actual date as new instance of <code class="classname">Zend_Date</code>. The actual date always
            include the actual date and time for the actual set timezone.
        </p>
<div class="example">
<a name="zend.date.creation.actual.example-1"></a><p class="title"><b>Example 26.10. Date Creation by Instance</b></p>
<div class="example-contents">
<p>
                Date creation by creating a new instance means that you do not need to give an
                parameter. Of course there are several parameters which will be described later but
                normally this is the simplest and most used way to get the actual date as
                <code class="classname">Zend_Date</code> instance.
            </p>
<pre class="programlisting">
$date = new Zend_Date();
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.date.creation.actual.example-2"></a><p class="title"><b>Example 26.11. Static Date Creation</b></p>
<div class="example-contents">
<p>
                Sometimes it is easier to use a static method for date creation. Therefor you can
                use the <span class="emphasis"><em><code class="methodname">now()</code></em></span> method. It returns a
                new instance of <code class="classname">Zend_Date</code> the same way as if you would use
                <span class="command"><strong>new Zend_Date()</strong></span>. But it will always return the actual date and
                can not be changed by giving optional parameters.
            </p>
<pre class="programlisting">
$date = Zend_Date::now();
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.date.creation.database"></a>26.5.2. Create a Date from Database</h3></div></div></div>
<p>
            Databases are often used to store date values. But the problem is, that every database
            outputs its date values in a different way. <span class="emphasis"><em>MsSQL</em></span> databases use a
            quite different standard date output than <span class="emphasis"><em>MySQL</em></span> databases. But for
            simplification <code class="classname">Zend_Date</code> makes it very easy to create a date
            from database date values.
        </p>
<p>
            Of course each database can be said to convert the output of a defined column to a
            special value. For example you could convert a <span class="emphasis"><em>datetime</em></span> value to
            output a minute value. But this is time expensive and often you are in need of handling
            dates in an other way than expected when creating the database query.
        </p>
<p>
            So we have one quick and one convenient way of creating dates from database values.
        </p>
<div class="example">
<a name="zend.date.creation.database.example-1"></a><p class="title"><b>Example 26.12. Quick Creation of Dates from Database Date Values</b></p>
<div class="example-contents">
<p>
                All databases are known to handle queries as fast as possible. They are built to act
                and respond quick. The quickest way for handling dates is to get unix timestamps
                from the database. All databases store date values internal as timestamp (not unix
                timestamp). This means that the time for creating a timestamp through a query is
                much smaller than converting it to a specified format.
            </p>
<pre class="programlisting">
// SELECT UNIX_TIMESTAMP(my_datetime_column) FROM my_table
$date = new Zend_Date($unixtimestamp, Zend_Date::TIMESTAMP);
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.date.creation.database.example-2"></a><p class="title"><b>Example 26.13. Convenient Creation of Dates from Database Date Values</b></p>
<div class="example-contents">
<p>
                The standard output of all databases is quite different even if it looks the same on
                the first eyecatch. But all are part of the <acronym class="acronym">ISO</acronym> Standard and
                explained through it. So the easiest way of date creation is the usage of
                <code class="constant">Zend_Date::ISO_8601</code>. Databases which are known to be
                recognised by <code class="constant">Zend_Date::ISO_8601</code> are
                <span class="emphasis"><em>MySQL</em></span>, <span class="emphasis"><em>MsSQL</em></span> for example. But all
                databases are also able to return a <acronym class="acronym">ISO-8601</acronym> representation of a
                date column. <acronym class="acronym">ISO-8601</acronym> has the big advantage that it is human
                readable. The disadvantage is that <acronym class="acronym">ISO-8601</acronym> needs more time for
                computation than a simple unix timestamp. But it should also be mentioned that unix
                timestamps are only supported for dates after 1 January 1970.
            </p>
<pre class="programlisting">
// SELECT datecolumn FROM my_table
$date = new Zend_Date($datecolumn, Zend_Date::ISO_8601);
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.date.creation.array"></a>26.5.3. Create Dates from an Array</h3></div></div></div>
<p>
            Dates can also be created by the usage of an array. This is a simple and easy way. The
            used array keys are:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: opencircle; ">
<li class="listitem" style="list-style-type: circle"><p><span class="emphasis"><em>day</em></span>: day of the date as number</p></li>
<li class="listitem" style="list-style-type: circle"><p><span class="emphasis"><em>month</em></span>: month of the date as number</p></li>
<li class="listitem" style="list-style-type: circle"><p><span class="emphasis"><em>year</em></span>: full year of the date</p></li>
<li class="listitem" style="list-style-type: circle"><p><span class="emphasis"><em>hour</em></span>: hour of the date</p></li>
<li class="listitem" style="list-style-type: circle"><p><span class="emphasis"><em>minute</em></span>: minute of the date</p></li>
<li class="listitem" style="list-style-type: circle"><p><span class="emphasis"><em>second</em></span>: second of the date</p></li>
</ul></div>
<div class="example">
<a name="zend.date.creation.array.example"></a><p class="title"><b>Example 26.14. Date Creation by Array</b></p>
<div class="example-contents">
<p>
                Normally you will give a complete date array for creation of a new date instance.
                But when you do not give all values, the not given array values are zeroed. This
                means that if f.e. no hour is given the hour <span class="emphasis"><em>0</em></span> is used.
            </p>
<pre class="programlisting">
$datearray = array('year' =&gt; 2006,
                   'month' =&gt; 4,
                   'day' =&gt; 18,
                   'hour' =&gt; 12,
                   'minute' =&gt; 3,
                   'second' =&gt; 10);
$date = new Zend_Date($datearray);
</pre>
<pre class="programlisting">
$datearray = array('year' =&gt; 2006, 'month' =&gt; 4, 'day' =&gt; 18);
$date = new Zend_Date($datearray);
</pre>
</div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.date.overview.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.date.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.date.constants.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">26.4. Zend_Date API Overview </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 26.6. Constants for General Date Functions</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
