<?php $title = 'Chapter 62. Zend_Serializer'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 62. Zend_Serializer</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.search.lucene.best-practice.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.serializer.adapter.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.serializer"></a>Chapter 62. Zend_Serializer</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.serializer.phtml#zend.serializer.introduction">62.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.serializer.adapter.phtml">62.2. Zend_Serializer_Adapter</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.phpserialize">62.2.1. Zend_Serializer_Adapter_PhpSerialize</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.igbinary">62.2.2. Zend_Serializer_Adapter_Igbinary</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.wddx">62.2.3. Zend_Serializer_Adapter_Wddx</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.json">62.2.4. Zend_Serializer_Adapter_Json</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.amf03">62.2.5. Zend_Serializer_Adapter_Amf 0 and 3</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.pythonpickle">62.2.6. Zend_Serializer_Adapter_PythonPickle</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.phpcode">62.2.7. Zend_Serializer_Adapter_PhpCode</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.serializer.introduction"></a>62.1. Introduction</h2></div></div></div>
<p>
        <code class="classname">Zend_Serializer</code> provides an adapter based interface to simply
        generate storable representation of <acronym class="acronym">PHP</acronym> types by different facilities,
        and recover.
    </p>
<div class="example">
<a name="zend.serializer.introduction.example.dynamic"></a><p class="title"><b>Example 62.1. Using Zend_Serializer dynamic interface</b></p>
<div class="example-contents">
<p>
            To instantiate a serializer you should use the factory method with the name of the
            adapter:
        </p>
<pre class="programlisting">
$serializer = Zend_Serializer::factory('PhpSerialize');
// Now $serializer is an instance of Zend_Serializer_Adapter_AdapterInterface,
// specifically Zend_Serializer_Adapter_PhpSerialize

try {
    $serialized = $serializer-&gt;serialize($data);
    // now $serialized is a string

    $unserialized = $serializer-&gt;unserialize($serialized);
    // now $data == $unserialized
} catch (Zend_Serializer_Exception $e) {
    echo $e;
}
</pre>
</div>
</div>
<br class="example-break"><p>
        The method <code class="methodname">serialize()</code> generates a storable string. To regenerate
        this serialized data you can simply call the method <code class="methodname">unserialize()</code>.
    </p>
<p>
        Any time an error is encountered serializing or unserializing,
        <code class="classname">Zend_Serializer</code> will throw a
        <code class="classname">Zend_Serializer_Exception</code>.
    </p>
<p>
        To configure a given serializer adapter, you can optionally add an array or an instance of
        <code class="classname">Zend_Config</code> to the <code class="methodname">factory()</code> or to the
        <code class="methodname">serialize()</code> and <code class="methodname">unserialize()</code> methods:
    </p>
<pre class="programlisting">
$serializer = Zend_Serializer::factory('Wddx', array(
    'comment' =&gt; 'serialized by Zend_Serializer',
));

try {
    $serialized = $serializer-&gt;serialize(
        $data,
        array('comment' =&gt; 'change comment')
    );

    $unserialized = $serializer-&gt;unserialize(
        $serialized,
        array(/* options for unserialize */)
    );
} catch (Zend_Serializer_Exception $e) {
    echo $e;
}
</pre>
<p>
        Options passed to the <code class="methodname">factory()</code> are valid for the instantiated
        object. You can change these options using the <code class="methodname">setOption(s)</code> method.
        To change one or more options only for a single call, pass them as the second argument to
        either the <code class="methodname">serialize()</code> or <code class="methodname">unserialize()</code>
        method.
    </p>
<div class="example">
<a name="zend.serializer.introduction.example.static.php"></a><p class="title"><b>Example 62.2. Using the Zend_Serializer static interface</b></p>
<div class="example-contents">
<p>
            You can register a specific serializer adapter as a default serialization adapter for
            use with <code class="classname">Zend_Serializer</code>. By default, the
            <code class="classname">PhpSerialize</code> adapter will be registered, but you can change this
            option using the <code class="methodname">setDefaultAdapter()</code> static method.
        </p>
<pre class="programlisting">
Zend_Serializer::setDefaultAdapter('PhpSerialize', $options);
// or
$serializer = Zend_Serializer::factory('PhpSerialize', $options);
Zend_Serializer::setDefaultAdapter($serializer);

try {
    $serialized   = Zend_Serializer::serialize($data, $options);
    $unserialized = Zend_Serializer::unserialize($serialized, $options);
} catch (Zend_Serializer_Exception $e) {
    echo $e;
}
</pre>
</div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.search.lucene.best-practice.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.serializer.adapter.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">61.10. Best Practices </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 62.2. Zend_Serializer_Adapter</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
