<?php $title = 'Chapter 18. Zend_Captcha'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 18. Zend_Captcha</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.cache.cache.manager.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.captcha.operation.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.captcha"></a>Chapter 18. Zend_Captcha</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.captcha.phtml#zend.captcha.introduction">18.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.captcha.operation.phtml">18.2. Captcha Operation</a></span></dt>
<dt><span class="sect1"><a href="zend.captcha.adapters.phtml">18.3. CAPTCHA Adapters</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.captcha.adapters.phtml#zend.captcha.adapters.word">18.3.1. Zend_Captcha_Word</a></span></dt>
<dt><span class="sect2"><a href="zend.captcha.adapters.phtml#zend.captcha.adapters.dumb">18.3.2. Zend_Captcha_Dumb</a></span></dt>
<dt><span class="sect2"><a href="zend.captcha.adapters.phtml#zend.captcha.adapters.figlet">18.3.3. Zend_Captcha_Figlet</a></span></dt>
<dt><span class="sect2"><a href="zend.captcha.adapters.phtml#zend.captcha.adapters.image">18.3.4. Zend_Captcha_Image</a></span></dt>
<dt><span class="sect2"><a href="zend.captcha.adapters.phtml#zend.captcha.adapters.recaptcha">18.3.5. Zend_Captcha_ReCaptcha</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.captcha.introduction"></a>18.1. Introduction</h2></div></div></div>
<p>
        <a class="ulink" href="http://en.wikipedia.org/wiki/Captcha" target="_top">CAPTCHA</a>
        stands for "Completely Automated Public Turing test to tell Computers and Humans
        Apart"; it is used as a challenge-response to ensure that the individual
        submitting information is a human and not an automated process. Typically, a
        captcha is used with form submissions where authenticated users are not
        necessary, but you want to prevent spam submissions.
    </p>
<p>
        Captchas can take a variety of forms, including asking logic questions, presenting skewed
        fonts, and presenting multiple images and asking how they relate.
        <code class="classname">Zend_Captcha</code> aims to provide a variety of back ends that may be
        utilized either standalone or in conjunction with <code class="classname">Zend_Form</code>.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.cache.cache.manager.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.captcha.operation.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">17.5. The Cache Manager </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 18.2. Captcha Operation</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
