<?php $title = 'Chapter 73. Zend_Tool_Project'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 73. Zend_Tool_Project</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.tool.framework.extending.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.tool.project.create-a-project.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.tool.project"></a>Chapter 73. Zend_Tool_Project</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.tool.project.phtml#zend.tool.project.introduction">73.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.tool.project.create-a-project.phtml">73.2. Create A Project</a></span></dt>
<dt><span class="sect1"><a href="zend.tool.project.providers.phtml">73.3. Zend_Tool Project Providers</a></span></dt>
<dt><span class="sect1"><a href="zend.tool.project.internals.phtml">73.4. Zend_Tool_Project Internals</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.project.internals.phtml#zend.tool.project.internals.xml-structure">73.4.1. Zend_Tool_Project Internal Xml Structure</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.project.internals.phtml#zend.tool.project.internals.extending">73.4.2. Zend_Tool_Project Internal Extending</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.tool.project.introduction"></a>73.1. Introduction</h2></div></div></div>
<p>
        <code class="classname">Zend_Tool_Project</code> builds on and extends the capabilities of
        <code class="classname">Zend_Tool_Framework</code> to that of managing a "project". In general, a
        "project" is a planned endeavor or an initiative. In the computer world, projects generally
        are a collection of resources. These resources can be files, directories, databases,
        schemas, images, styles, and more.
    </p>
<p>
        This same concept applies to Zend Framework projects. In Zend Framework projects, you have
        controllers, actions, views, models, databases and so on and so forth. In terms of
        <code class="classname">Zend_Tool</code>, we need a way to track these types of resources - thus
        <code class="classname">Zend_Tool_Project</code>.
    </p>
<p>
        <code class="classname">Zend_Tool_Project</code> is capable of tracking project resources throughout
        the development of a project. So, for example, if in one command you created a controller,
        and in the next command you wish to create an action within that controller,
        <code class="classname">Zend_Tool_Project</code> is gonna have to <span class="emphasis"><em>know</em></span> about
        the controller file you created so that you can (in the next action), be able to append that
        action to it. This is what keeps our projects up to date and <span class="emphasis"><em>stateful</em></span>.
    </p>
<p>
        Another important point to understand about projects is that typically, resources are
        organized in a hierarchical fashion. With that in mind,
        <code class="classname">Zend_Tool_Project</code> is capable of serializing the current project into
        a internal representation that allows it to keep track of not only <span class="emphasis"><em>what</em></span>
        resources are part of a project at any given time, but also <span class="emphasis"><em>where</em></span> they
        are in relation to one another.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.tool.framework.extending.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.tool.project.create-a-project.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">72.6. Extending and Configuring Zend_Tool_Framework </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 73.2. Create A Project</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
