<?php $title = 'Chapter 54. Zend_Paginator'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 54. Zend_Paginator</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.openid.provider.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.paginator.usage.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.paginator"></a>Chapter 54. Zend_Paginator</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.paginator.phtml#zend.paginator.introduction">54.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.paginator.usage.phtml">54.2. Usage</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.paginator.usage.phtml#zend.paginator.usage.paginating">54.2.1. Paginating data collections</a></span></dt>
<dt><span class="sect2"><a href="zend.paginator.usage.phtml#zend.paginator.usage.dbselect">54.2.2. The DbSelect and DbTableSelect adapter</a></span></dt>
<dt><span class="sect2"><a href="zend.paginator.usage.phtml#zend.paginator.rendering">54.2.3. Rendering pages with view scripts</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.paginator.usage.phtml#zend.paginator.usage.rendering.example-controls">54.2.3.1. Example pagination controls</a></span></dt>
<dt><span class="sect3"><a href="zend.paginator.usage.phtml#zend.paginator.usage.rendering.properties">54.2.3.2. Listing of properties</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.paginator.configuration.phtml">54.3. Configuration</a></span></dt>
<dt><span class="sect1"><a href="zend.paginator.advanced.phtml">54.4. Advanced usage</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.paginator.advanced.phtml#zend.paginator.advanced.adapters">54.4.1. Custom data source adapters</a></span></dt>
<dt><span class="sect2"><a href="zend.paginator.advanced.phtml#zend.paginator.advanced.scrolling-styles">54.4.2. Custom scrolling styles</a></span></dt>
<dt><span class="sect2"><a href="zend.paginator.advanced.phtml#zend.paginator.advanced.caching">54.4.3. Caching features</a></span></dt>
<dt><span class="sect2"><a href="zend.paginator.advanced.phtml#zend.paginator.advanced.aggregator">54.4.4. Zend_Paginator_AdapterAggregate Interface</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.paginator.introduction"></a>54.1. Introduction</h2></div></div></div>
<p>
        <code class="classname">Zend_Paginator</code> is a flexible component for paginating
        collections of data and presenting that data to users.
    </p>
<p>
        The primary design goals of <code class="classname">Zend_Paginator</code> are as follows:

        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    Paginate arbitrary data, not just relational databases
                </p></li>
<li class="listitem"><p>
                    Fetch only the results that need to be displayed
                </p></li>
<li class="listitem"><p>
                    Do not force users to adhere to only one way of displaying
                    data or rendering pagination controls
                </p></li>
<li class="listitem"><p>
                    Loosely couple <code class="classname">Zend_Paginator</code> to other Zend
                    Framework components so that users who wish to use it
                    independently of <code class="classname">Zend_View</code>,
                    <code class="classname">Zend_Db</code>, etc. can do so
                </p></li>
</ul></div>
<p>
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.openid.provider.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.paginator.usage.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">53.3. Zend_OpenId_Provider </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 54.2. Usage</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
