<?php $title = 'Chapter 79. Zend_Wildfire'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 79. Zend_Wildfire</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.view.abstract.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.xmlrpc.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.wildfire"></a>Chapter 79. Zend_Wildfire</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc"><dt><span class="sect1"><a href="zend.wildfire.phtml#zend.wildfire.chapter">79.1. Zend_Wildfire</a></span></dt></dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.wildfire.chapter"></a>79.1. Zend_Wildfire</h2></div></div></div>
<p>
        <code class="classname">Zend_Wildfire</code> is a component that facilitates communication
        between <acronym class="acronym">PHP</acronym> code and
        <a class="ulink" href="http://www.wildfirehq.org/" target="_top">Wildfire</a> client components.
    </p>
<p>
        The purpose of the Wildfire Project is to develop standardized communication channels
        between a large variety of components and a dynamic and scriptable plugin architecture. At
        this time, the primary focus is to provide a system that allows server-side
        <acronym class="acronym">PHP</acronym> code to inject logging messages into the
        <a class="ulink" href="http://www.getfirebug.com/" target="_top">Firebug Console</a>.
    </p>
<p>
        The <a class="link" href="zend.log.writers.phtml#zend.log.writers.firebug" title="44.2.3. Writing to Firebug"><code class="classname">Zend_Log_Writer_Firebug</code></a>
        component is provided for the purpose of logging to Firebug, and a communication protocol
        has been developed that uses <acronym class="acronym">HTTP</acronym> request and response headers to send
        data between the server and client components. It is great for logging intelligence data to
        the browser that is generated during script execution, without interfering with the page
        content. With this approach, it is possible to debug <acronym class="acronym">AJAX</acronym> requests that
        require clean <acronym class="acronym">JSON</acronym> and <acronym class="acronym">XML</acronym> responses.
    </p>
<p>
        There is also a <a class="link" href="zend.db.profiler.phtml#zend.db.profiler.profilers.firebug" title="27.3.4.1. Profiling with Firebug"><code class="classname">Zend_Db_Profiler_Firebug</code></a>
        component to log database profiling information to Firebug.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.view.abstract.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.xmlrpc.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">78.5. Zend_View_Abstract </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Chapter 80. Zend_XmlRpc</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
