<?php $title = '32.3. Previous Exceptions'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">32.3. Previous Exceptions</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.exception.basic.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 32. Zend_Exception</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.feed.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.exception.previous"></a>32.3. Previous Exceptions</h2></div></div></div>
<p>
        Since Zend Framework 1.10, <code class="classname">Zend_Exception</code> implements the
        <acronym class="acronym">PHP</acronym> 5.3 support for previous exceptions. Simply put, when in a
        <code class="methodname">catch()</code> block, you can throw a new exception that references the
        original exception, which helps provide additional context when debugging. By providing this
        support in Zend Framework, your code may now be forwards compatible with
        <acronym class="acronym">PHP</acronym> 5.3.
    </p>
<p>
        Previous exceptions are indicated as the third argument to an exception constructor.
    </p>
<div class="example">
<a name="zend.exception.previous.example"></a><p class="title"><b>Example 32.4. Previous exceptions</b></p>
<div class="example-contents"><pre class="programlisting">
try {
    $db-&gt;query($sql);
} catch (Zend_Db_Statement_Exception $e) {
    if ($e-&gt;getPrevious()) {
        echo '[' . get_class($e)
            . '] has the previous exception of ['
            . get_class($e-&gt;getPrevious())
            . ']' . PHP_EOL;
    } else {
        echo '[' . get_class($e)
            . '] does not have a previous exception'
            . PHP_EOL;
    }

    echo $e;
    // displays all exceptions starting by the first thrown
    // exception if available.
}
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.exception.basic.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.exception.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.feed.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">32.2. Basic usage </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Chapter 33. Zend_Feed</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
