<?php $title = 'registerNamespace'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">registerNamespace</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.is-fallback-autoloader.phtml">Prev</a> </td>
<th width="60%" align="center">42.7.4. Available Methods</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.register-namespaces.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.standard-autoloader.methods.register-namespace"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Name</h2>
<p>registerNamespace — Register a namespace with the autoloader</p>
</div>
<div class="refsynopsisdiv">
<h2>Synopsis</h2>
<code class="methodsynopsis"><span class="methodname">registerNamespace</span>(<span class="methodparam">$namespace, $directory</span>);</code>
</div>
<div class="refsection">
<a name="id37106"></a><h2>registerNamespace()</h2>
<p>
                    Register a namespace with the autoloader, pointing it to a specific directory on
                    the filesystem for class resolution. For classes matching that initial
                    namespace, the autoloader will then perform lookups within that directory.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.is-fallback-autoloader.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.methods">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.register-namespaces.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">isFallbackAutoloader </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> registerNamespaces</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
