<?php $title = '45.3. Sending Multiple Mails per SMTP Connection'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">45.3. Sending Multiple Mails per SMTP Connection</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.sending.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 45. Zend_Mail</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.different-transports.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.multiple-emails"></a>45.3. Sending Multiple Mails per SMTP Connection</h2></div></div></div>
<p>
        By default, a single SMTP transport creates a single connection and
        re-uses it for the lifetime of the script execution. You may send multiple
        e-mails through this SMTP connection. A RSET command is issued before each
        delivery to ensure the correct SMTP handshake is followed.
    </p>
<p>
        Optionally, you can also define a default From email address and name,
        as well as a default reply-to header. This can be done through the static
        methods <code class="methodname">setDefaultFrom()</code> and
        <code class="methodname">setDefaultReplyTo()</code>. These defaults will be used when you
        don't specify a From/Reply-to Address or -Name until the defaults are reset (cleared).
        Resetting the defaults can be done through the use of the
        <code class="methodname">clearDefaultFrom()</code> and
        <code class="methodname">clearDefaultReplyTo</code>.
    </p>
<div class="example">
<a name="zend.mail.multiple-emails.example-1"></a><p class="title"><b>Example 45.4. Sending Multiple Mails per SMTP Connection</b></p>
<div class="example-contents"><pre class="programlisting">
// Create transport
$config = array('name' =&gt; 'sender.example.com');
$transport = new Zend_Mail_Transport_Smtp('mail.example.com', $config);

// Set From &amp; Reply-To address and name for all emails to send.
Zend_Mail::setDefaultFrom('sender@example.com', 'John Doe');
Zend_Mail::setDefaultReplyTo('replyto@example.com','Jane Doe');

// Loop through messages
for ($i = 0; $i &lt; 5; $i++) {
    $mail = new Zend_Mail();
    $mail-&gt;addTo('studio@example.com', 'Test');

    $mail-&gt;setSubject(
        'Demonstration - Sending Multiple Mails per SMTP Connection'
    );
    $mail-&gt;setBodyText('...Your message here...');
    $mail-&gt;send($transport);
}

// Reset defaults
Zend_Mail::clearDefaultFrom();
Zend_Mail::clearDefaultReplyTo();
</pre></div>
</div>
<br class="example-break"><p>
        If you wish to have a separate connection for each mail
        delivery, you will need to create and destroy your transport before and
        after each <code class="methodname">send()</code> method is called. Or alternatively,
        you can manipulate the connection between each delivery by accessing the
        transport's protocol object.
    </p>
<div class="example">
<a name="zend.mail.multiple-emails.example-2"></a><p class="title"><b>Example 45.5. Manually controlling the transport connection</b></p>
<div class="example-contents"><pre class="programlisting">
// Create transport
$transport = new Zend_Mail_Transport_Smtp();

$protocol = new Zend_Mail_Protocol_Smtp('mail.example.com');
$protocol-&gt;connect();
$protocol-&gt;helo('sender.example.com');

$transport-&gt;setConnection($protocol);

// Loop through messages
for ($i = 0; $i &lt; 5; $i++) {
    $mail = new Zend_Mail();
    $mail-&gt;addTo('studio@example.com', 'Test');
    $mail-&gt;setFrom('studio@example.com', 'Test');
    $mail-&gt;setSubject(
        'Demonstration - Sending Multiple Mails per SMTP Connection'
    );
    $mail-&gt;setBodyText('...Your message here...');

    // Manually control the connection
    $protocol-&gt;rset();
    $mail-&gt;send($transport);
}

$protocol-&gt;quit();
$protocol-&gt;disconnect();
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.sending.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mail.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.different-transports.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">45.2. Sending via SMTP </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 45.4. Using Different Transports</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
