<?php $title = '45.8. Controlling the MIME Boundary'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">45.8. Controlling the MIME Boundary</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.adding-recipients.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 45. Zend_Mail</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.additional-headers.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.boundary"></a>45.8. Controlling the MIME Boundary</h2></div></div></div>
<p>
        In a multipart message, a <acronym class="acronym">MIME</acronym> boundary for separating the different
        parts of the message is normally generated at random. In some cases, however, you might
        want to specify the <acronym class="acronym">MIME</acronym> boundary that is used. This can be done using
        the <code class="methodname">setMimeBoundary()</code> method, as in the following example:
    </p>
<div class="example">
<a name="zend.mail.boundary.example-1"></a><p class="title"><b>Example 45.9. Changing the MIME Boundary</b></p>
<div class="example-contents"><pre class="programlisting">
$mail = new Zend_Mail();
$mail-&gt;setMimeBoundary('=_' . md5(microtime(1) . $someId++));
// build message...
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.adding-recipients.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mail.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.additional-headers.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">45.7. Adding Recipients </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 45.9. Additional Headers</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
