<?php $title = 'Chapter 46. Zend_Markup'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 46. Zend_Markup</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.read.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.markup.getting-started.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.markup"></a>Chapter 46. Zend_Markup</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.markup.phtml#zend.markup.introduction">46.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.markup.getting-started.phtml">46.2. Getting Started With Zend_Markup</a></span></dt>
<dt><span class="sect1"><a href="zend.markup.parsers.phtml">46.3. Zend_Markup Parsers</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.markup.parsers.phtml#zend.markup.parsers.theory">46.3.1. Theory of Parsing</a></span></dt>
<dt><span class="sect2"><a href="zend.markup.parsers.phtml#zend.markup.parsers.bbcode">46.3.2. The BBCode parser</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.markup.renderers.phtml">46.4. Zend_Markup Renderers</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.markup.renderers.phtml#zend.markup.renderers.add">46.4.1. Adding your own markups</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.markup.renderers.phtml#zend.markup.renderers.add.callback">46.4.1.1. Add a callback markup</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.markup.renderers.phtml#zend.markup.renderers.list">46.4.2. List of markups</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.markup.introduction"></a>46.1. Introduction</h2></div></div></div>
<p>
        The <code class="classname">Zend_Markup</code> component provides an extensible
        way for parsing text and rendering lightweight markup languages like
        BBcode. It is available as of Zend Framework version 1.10.
    </p>
<p>
        <code class="classname">Zend_Markup</code> uses a factory method to instantiate
        an instance of a renderer that extends
        <code class="classname">Zend_Markup_Renderer_Abstract</code>. The factory
        method accepts three arguments. The first one is the parser used to
        tokenize the text (e.g. BbCode). The second (optional) parameter is
        the renderer to use, <acronym class="acronym">HTML</acronym> by default. Thirdly an array with options
        to use for the renderer can be specified.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.read.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.markup.getting-started.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">45.14. Reading Mail Messages </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 46.2. Getting Started With Zend_Markup</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
