<?php $title = 'Chapter 71. Zend_Tool'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 71. Zend_Tool</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.timesync.working.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.tool.extending.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.tool"></a>Chapter 71. Zend_Tool</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.tool.phtml#zend.tool.usage.cli">71.1. Using Zend_Tool On The Command Line</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.phtml#zend.tool.usage.cli.installation">71.1.1. Installation</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.installation.download-and-go">71.1.1.1. Download And Go</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.installation.pear">71.1.1.2. Installing Via Pear</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.installation.install-by-hand">71.1.1.3. Installing by Hand</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.tool.phtml#zend.tool.usage.cli.general-purpose-commands">71.1.2. General Purpose Commands</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.general-purpose-commands.version">71.1.2.1. Version</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.general-purpose-commands.built-in-help">71.1.2.2. Built-in Help</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.general-purpose-commands.manifest">71.1.2.3. Manifest</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands">71.1.3. Project Specific Commands</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.project">71.1.3.1. Project</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.module">71.1.3.2. Module</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.controller">71.1.3.3. Controller</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.action">71.1.3.4. Action</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.view">71.1.3.5. View</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.model">71.1.3.6. Model</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.form">71.1.3.7. Form</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.database-adapter">71.1.3.8. DbAdapter</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.db-table">71.1.3.9. DbTable</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.layout">71.1.3.10. Layout</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.tool.phtml#zend.tool.usage.cli.environment-customization">71.1.4. Environment Customization</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.environment-customization.storage-directory">71.1.4.1. The Storage Directory</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.environment-customization.configuration-file">71.1.4.2. The Configuration File</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.environment-customization.environment-locations">71.1.4.3. Environment Locations</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.extending.phtml">71.2. Extending Zend_Tool</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.extending.phtml#zend.tool.extending.overview">71.2.1. Overview of Zend_Tool</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework">71.2.2. Zend_Tool_Framework Extensions</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.architecture">71.2.2.1. Overall Architecture</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client">71.2.2.2. Understanding the CLI Client</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client.setup-general">71.2.2.2.1. Setting up the CLI tool</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client.setup-starnix">71.2.2.2.2. Setting up the CLI tool on Unix-like Systems</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client.setup-windows">71.2.2.2.3. Setting up the CLI tool on Windows</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client.setup-othernotes">71.2.2.2.4. Other Setup Considerations</a></span></dt>
</dl></dd>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests">71.2.2.3. Creating Providers</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests.loading">71.2.2.3.1. How Zend_Tool finds your Providers</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests.basic">71.2.2.3.2. Basic Instructions for Creating Providers</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests.response">71.2.2.3.3. The response object</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests.advanced">71.2.2.3.4. Advanced Development Information</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect2"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-project">71.2.3. Zend_Tool_Project Extensions</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-project.architecture">71.2.3.1. Overall Architecture</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-project.providers">71.2.3.2. Creating Providers</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.tool.usage.cli"></a>71.1. Using Zend_Tool On The Command Line</h2></div></div></div>
<p>
        The <acronym class="acronym">CLI</acronym>, or command line tool (internally known as the console tool),
        is currently the primary interface for dispatching <code class="classname">Zend_Tool</code>
        requests. With the <acronym class="acronym">CLI</acronym> tool, developers can issue tooling requests
        inside the "command line window", also commonly known as a "terminal" window. This
        environment is predominant in the *nix environment, but also has a common implementation
        in windows with the <code class="filename">cmd.exe</code>, console2 and also with the Cygwin project.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.tool.usage.cli.installation"></a>71.1.1. Installation</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.installation.download-and-go"></a>71.1.1.1. Download And Go</h4></div></div></div>
<p>
                First download Zend Framework. This can be done by going to framework.zend.com
                and downloading the latest release. After you've downloaded the package and placed
                it on your system. The next step is to make the zf command available to your
                system. The easiest way to do this, is to copy the proper files from the bin/
                directory of the download, and place these files within the
                <span class="emphasis"><em>same</em></span> directory as the location of the <acronym class="acronym">PHP</acronym>
                cli binary.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.installation.pear"></a>71.1.1.2. Installing Via Pear</h4></div></div></div>
<p>
                To install via PEAR, you must use the 3rd party zfcampus.org site to retrieve the
                latest Zend Framework PEAR package. These packages are typically built within a day
                of an official Zend Framework release. The benefit of installing via the PEAR
                package manager is that during the install process, the ZF library will end up on
                the include_path, and the zf.php and zf scripts will end up in a place on your
                system that will allow you to run them without any additional setup.
            </p>
<pre class="programlisting">
pear channel-discover pear.zfcampus.org
pear install zfcampus/zf
</pre>
<p>
                That is it. After the initial install, you should be able to continue on by
                running the zf command. Go good way to check to see if it't there is to run
                zf --help
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.installation.install-by-hand"></a>71.1.1.3. Installing by Hand</h4></div></div></div>
<p>
                Installing by hand refers to the process of forcing the zf.php and Zend Framework
                library to work together when they are placed in non-convential places, or at least,
                in a place that your system cannot dispatch from easily (typical of programs in your
                system PATH).
            </p>
<p>
                If you are on a *nix or mac system, you can also create a link from somewhere in
                your path to the zf.sh file. If you do this, you do not need to worry about having
                Zend Framework's library on your include_path, as the zf.php and zf.sh files will
                be able to access the library relative to where they are (meaning the ./bin/ files
                are ../library/ relative to the Zend Framework library).
            </p>
<p>
                There are a number of other options available for setting up the zf.php and library
                on your system. These options revolve around setting specific environment
                variables. These are described in the later section on "customizing the CLI
                environement". The environment variables for setting the zf.php include_path,
                ZEND_TOOL_INCLUDE_PATH and ZF_TOOL_INCLUDE_PATH_PREPEND, are the ones of most interest.
            </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.tool.usage.cli.general-purpose-commands"></a>71.1.2. General Purpose Commands</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.general-purpose-commands.version"></a>71.1.2.1. Version</h4></div></div></div>
<p>
                This will show the current version number of the copy of Zend Framework the zf.php
                tool is using.
            </p>
<pre class="programlisting">
zf show version
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.general-purpose-commands.built-in-help"></a>71.1.2.2. Built-in Help</h4></div></div></div>
<p>
                The built-in help system is the primary place where you can get up-to-date
                information on what your system is capable of doing. The help system is dynamic in
                that as providers are added to your system, they are automatically dispatchable, and
                as such, the parameters required to run them will be in the help screen. The
                easiest way to retrieve the help screen is the following:
            </p>
<pre class="programlisting">
zf --help
</pre>
<p>
                This will give you an overview of the various capabilities of the system.
                Sometimes, there are more finite commands than can be run, and to gain more
                information about these, you might have to run a more specialized help command.
                For specialized help, simply replace any of the elements of the command with a "?".
                This will tell the help system that you want more information about what commands
                can go in place of the question mark. For example:
            </p>
<pre class="programlisting">
zf ? controller
</pre>
<p>
                The above means "show me all 'actions' for the provider 'controller'"; while the
                following:
            </p>
<pre class="programlisting">
zf show ?
</pre>
<p>
                means "show me all providers that support the 'show' action". This works for
                drilling down into options as well as you can see in the following examples:
            </p>
<pre class="programlisting">
zf show version.? (show any specialties)
zf show version ? (show any options)
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.general-purpose-commands.manifest"></a>71.1.2.3. Manifest</h4></div></div></div>
<p>
                This will show what information is in the tooling systems manifest. This is more
                important for provider developers than casual users of the tooling system.
            </p>
<pre class="programlisting">
zf show manifest
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.tool.usage.cli.project-specific-commands"></a>71.1.3. Project Specific Commands</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.project"></a>71.1.3.1. Project</h4></div></div></div>
<p>
                The project provider is the first command you might want to run. This will setup the
                basic structure of your application. This is required before any of the other
                providers can be executed.
            </p>
<pre class="programlisting">
zf create project MyProjectName
</pre>
<p>
                This will create a project in a directory called ./MyProjectName. From this point
                on, it is important to note that any subsequent commands on the command line must be
                issued from within the project directory you had just created. So, after creation,
                changing into that directory is required.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.module"></a>71.1.3.2. Module</h4></div></div></div>
<p>
                The module provider allows for the easy creation of a Zend Framework module. A
                module follows the hMVC pattern loosely. When creating modules, it will take the
                same structure used at the application/ level, and duplicate it inside of the chosen
                name for your module, inside of the "modules" directory of the application/
                directory without duplicating the modules directory itself. For example:
            </p>
<pre class="programlisting">
zf create module Blog
</pre>
<p>
                This will create a module named Blog at application/modules/Blog, and all of the
                artifacts that a module will need.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.controller"></a>71.1.3.3. Controller</h4></div></div></div>
<p>
                The controller provider is responsible for creating (mostly) empty controllers as
                well as their corresponding view script directories and files. To utilize it to
                create an 'Auth' controlller, for example, execute:
            </p>
<pre class="programlisting">
zf create controller Auth
</pre>
<p>
                This will create a controller named Auth, specifically it will create a file at
                application/controllers/AuthController.php with the AuthController inside.
                If you wish to create a controller for a module, use any of the following:
            </p>
<pre class="programlisting">
zf create controller Post 1 Blog
zf create controller Post -m Blog
zf create controller Post --module=Blog
</pre>
<p>
                Note: In the first command, 1 is the value for the "includeIndexAction" flag.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.action"></a>71.1.3.4. Action</h4></div></div></div>
<p>
                To create an action within an existing controller:
            </p>
<pre class="programlisting">
zf create action login Auth
zf create action login -c Auth
zf create action login --controller-name=Auth
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.view"></a>71.1.3.5. View</h4></div></div></div>
<p>
                To create a view outside of the normal controller/action creation, you would use
                one of the following:
            </p>
<pre class="programlisting">
zf create view Auth my-script-name
zf create view -c Auth -a my-script-name
            </pre>
<p>
                This will create a view script in the controller folder of Auth.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.model"></a>71.1.3.6. Model</h4></div></div></div>
<p>
                The model provider is only responsible for creating the proper model files,
                with the proper name inside the application folder. For example
            </p>
<pre class="programlisting">
zf create model User
</pre>
<p>
                If you wish to create a model within a specific module:
            </p>
<pre class="programlisting">
zf create model Post -m Blog
</pre>
<p>
                The above will create a 'Post' model inside of the 'Blog' module.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.form"></a>71.1.3.7. Form</h4></div></div></div>
<p>
                The form provider is only responsible for creating the proper form file and
                init() method, with the proper name inside the application folder. For example:
            </p>
<pre class="programlisting">
zf create form Auth
</pre>
<p>
                If you wish to create a model within a specific module:
            </p>
<pre class="programlisting">
zf create form Comment -m Blog
</pre>
<p>
                The above will create a 'Comment' form inside of the 'Blog' module.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.database-adapter"></a>71.1.3.8. DbAdapter</h4></div></div></div>
<p>
                To configure a DbAdapter, you will need to provide the information as a url
                encoded string. This string needs to be in quotes on the command line.
            </p>
<p>
                For example, to enter the following information:

                </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>adapter: Pdo_Mysql</p></li>
<li class="listitem"><p>username: test</p></li>
<li class="listitem"><p>password: test</p></li>
<li class="listitem"><p>dbname: test </p></li>
</ul></div>
<p>

                The following will have to be run on the command line:
            </p>
<pre class="programlisting">
zf configure dbadapter "adapter=Pdo_Mysql&amp;username=test&amp;password=test&amp;dbname=test"
</pre>
<p>
                This assumes you wish to store this information inside of the
                'production' space of the application configuration file. The following will
                demonstrate an sqlite configuration, in the 'development' section of the
                application config file.
            </p>
<pre class="programlisting">
zf configure dbadapter "adapter=Pdo_Sqlite&amp;dbname=../data/test.db" development
zf configure dbadapter "adapter=Pdo_Sqlite&amp;dbname=../data/test.db" -s development
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.db-table"></a>71.1.3.9. DbTable</h4></div></div></div>
<p>
                The DbTable provider is responsible for creating
                <code class="classname">Zend_Db_Table</code> model/data access files for your application to
                consume, with the proper class name, and in the proper location in the application.
                The two important pieces of information are the <span class="emphasis"><em>DbTable name</em></span>,
                and the <span class="emphasis"><em>actual database table name</em></span>. For example:
            </p>
<pre class="programlisting">
zf create dbtable User user
zf create dbtable User -a user

// also accepts a force option to overwrite existing files
zf create dbtable User user -f
zf create dbtable User user --force-overwrite
</pre>
<p>
                The DbTable provider is also capable of creating the proper files by
                scanning the database configured with the above DbAdapter provider.
            </p>
<pre class="programlisting">
zf create dbtable.from-database
</pre>
<p>
                When executing the above, it might make sense to use the pretend / "-p"
                flag first so that you can see what would be done, and what tables can
                be found in the database.
            </p>
<pre class="programlisting">
zf -p create dbtable.from-database
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.layout"></a>71.1.3.10. Layout</h4></div></div></div>
<p>
                Currently, the only supported action for layouts is simply to enable them
                will setup the proper keys in the application.ini file for the application
                resource to work, and create the proper directories and layout.phtml file.
            </p>
<pre class="programlisting">
zf enable layout
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.tool.usage.cli.environment-customization"></a>71.1.4. Environment Customization</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.environment-customization.storage-directory"></a>71.1.4.1. The Storage Directory</h4></div></div></div>
<p>
                The storage directory is important so that providers may have a place to find
                custom user generated logic that might change the way they behave. One example
                can be found below is the placement of a custom project profile file.
            </p>
<pre class="programlisting">
zf --setup storage-directory
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.environment-customization.configuration-file"></a>71.1.4.2. The Configuration File</h4></div></div></div>
<p>
                This will create the proper zf.ini file. This <span class="emphasis"><em>should</em></span>
                be run after <span class="command"><strong>zf --setup storage-directory</strong></span>. If it is not, it will
                be located inside the users home directory. If it is, it will be located inside
                the users storage directory.
            </p>
<pre class="programlisting">
zf --setup config-file
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.environment-customization.environment-locations"></a>71.1.4.3. Environment Locations</h4></div></div></div>
<p>
                These should be set if you wish to override the default places where zf will
                attempt to read their values.
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>ZF_HOME</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>the directory this tool will look for a home directory</p></li>
<li class="listitem"><p>directory must exist</p></li>
<li class="listitem">
<p>search order:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: square; ">
<li class="listitem"><p>ZF_HOME environment variable</p></li>
<li class="listitem"><p>HOME environment variable</p></li>
<li class="listitem"><p>then HOMEPATH environment variable</p></li>
</ul></div>
</li>
</ul></div>
</li>
<li class="listitem">
<p>ZF_STORAGE_DIRECTORY</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>where this tool will look for a storage directory</p></li>
<li class="listitem"><p>directory must exist</p></li>
<li class="listitem">
<p>search order:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: square; ">
<li class="listitem"><p>ZF_STORAGE_DIRECTORY environment variable</p></li>
<li class="listitem"><p>$homeDirectory/.zf/ directory</p></li>
</ul></div>
</li>
</ul></div>
</li>
<li class="listitem">
<p>ZF_CONFIG_FILE</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>where this tool will look for a configuration file</p></li>
<li class="listitem">
<p>search order:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: square; ">
<li class="listitem"><p>ZF_CONFIG_FILE environment variable</p></li>
<li class="listitem"><p>$homeDirectory/.zf.ini file if it exists</p></li>
<li class="listitem"><p>$storageDirectory/zf.ini file if it exists</p></li>
</ul></div>
</li>
</ul></div>
</li>
<li class="listitem">
<p>ZEND_TOOL_INCLUDE_PATH</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>set the include_path for this tool to use this value</p></li>
<li class="listitem">
<p>original behavior:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: square; ">
<li class="listitem"><p>
                                        use <acronym class="acronym">PHP</acronym>'s include_path to find ZF
                                    </p></li>
<li class="listitem"><p>use the ZEND_TOOL_INCLUDE_PATH environment variable</p></li>
<li class="listitem"><p>
                                        use the path ../library (relative to zf.php) to find ZF
                                    </p></li>
</ul></div>
</li>
</ul></div>
</li>
<li class="listitem">
<p>ZF_TOOL_INCLUDE_PATH_PREPEND</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; "><li class="listitem"><p>prepend the current php.ini include_path with this value</p></li></ul></div>
</li>
</ul></div>
</div>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.timesync.working.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.tool.extending.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">70.2. Working with Zend_TimeSync </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 71.2. Extending Zend_Tool</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
