<?php $title = '35.4. Writing Filters'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">35.4. Writing Filters</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.filter.filter_chains.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 35. Zend_Filter</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.filter.input.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.filter.writing_filters"></a>35.4. Writing Filters</h2></div></div></div>
<p>
        <code class="classname">Zend_Filter</code> supplies a set of commonly needed filters, but developers
        will often need to write custom filters for their particular use cases. The task of writing
        a custom filter is facilitated by implementing <code class="classname">Zend_Filter_Interface</code>.
    </p>
<p>
        <code class="classname">Zend_Filter_Interface</code> defines a single method,
        <code class="methodname">filter()</code>, that may be implemented by user classes. An object that
        implements this interface may be added to a filter chain with
        <code class="methodname">Zend_Filter::addFilter()</code>.
    </p>
<p>
        The following example demonstrates how to write a custom filter:
    </p>
<pre class="programlisting">
class MyFilter implements Zend_Filter_Interface
{
    public function filter($value)
    {
        // perform some transformation upon $value to arrive on $valueFiltered

        return $valueFiltered;
    }
}
</pre>
<p>
        To add an instance of the filter defined above to a filter chain:
    </p>
<pre class="programlisting">
$filterChain = new Zend_Filter();
$filterChain-&gt;addFilter(new MyFilter());
</pre>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.filter.filter_chains.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.filter.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.filter.input.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">35.3. Filter Chains </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 35.5. Zend_Filter_Input</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
