<?php $title = '32.2. Basic usage'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">32.2. Basic usage</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.exception.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 32. Zend_Exception</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.exception.previous.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.exception.basic"></a>32.2. Basic usage</h2></div></div></div>
<p>
        <code class="classname">Zend_Exception</code> is the base class for all exceptions thrown by Zend
        Framework. This class extends the base <code class="classname">Exception</code> class of
        <acronym class="acronym">PHP</acronym>.
    </p>
<div class="example">
<a name="zend.exception.catchall.example"></a><p class="title"><b>Example 32.2. Catch all Zend Framework exceptions</b></p>
<div class="example-contents"><pre class="programlisting">
try {
    // your code
} catch (Zend_Exception $e) {
    // do something
}
</pre></div>
</div>
<br class="example-break"><div class="example">
<a name="zend.exception.catchcomponent.example"></a><p class="title"><b>Example 32.3. Catch exceptions thrown by a specific component of Zend Framework</b></p>
<div class="example-contents"><pre class="programlisting">
try {
    // your code
} catch (Zend_Db_Exception $e) {
    // do something
}
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.exception.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.exception.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.exception.previous.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Chapter 32. Zend_Exception </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 32.3. Previous Exceptions</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
