<?php $title = 'Chapter 61. Zend_Search_Lucene'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 61. Zend_Search_Lucene</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.rest.server.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.search.lucene.index-creation.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.search.lucene"></a>Chapter 61. Zend_Search_Lucene</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.search.lucene.phtml#zend.search.lucene.overview">61.1. Overview</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.introduction">61.1.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.documents-and-fields">61.1.2. Document and Field Objects</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.understanding-field-types">61.1.3. Understanding Field Types</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.html-documents">61.1.4. HTML documents</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.docx-documents">61.1.5. Word 2007 documents</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.pptx-documents">61.1.6. Powerpoint 2007 documents</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.xlsx-documents">61.1.7. Excel 2007 documents</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.index-creation.phtml">61.2. Building Indexes</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.creating">61.2.1. Creating a New Index</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.updating">61.2.2. Updating Index</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.document-updating">61.2.3. Updating Documents</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.counting">61.2.4. Retrieving Index Size</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.optimization">61.2.5. Index optimization</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.optimization.maxbuffereddocs">61.2.5.1. MaxBufferedDocs auto-optimization option</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.optimization.maxmergedocs">61.2.5.2. MaxMergeDocs auto-optimization option</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.optimization.mergefactor">61.2.5.3. MergeFactor auto-optimization option</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.permissions">61.2.6. Permissions</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.limitations">61.2.7. Limitations</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.limitations.index-size">61.2.7.1. Index size</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.limitations.filesystems">61.2.7.2. Supported Filesystems</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.searching.phtml">61.3. Searching an Index</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.query_building">61.3.1. Building Queries</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.query_building.parsing">61.3.1.1. Query Parsing</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.results">61.3.2. Search Results</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.results-limiting">61.3.3. Limiting the Result Set</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.results-scoring">61.3.4. Results Scoring</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.sorting">61.3.5. Search Result Sorting</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.highlighting">61.3.6. Search Results Highlighting</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.query-language.phtml">61.4. Query Language</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.terms">61.4.1. Terms</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.fields">61.4.2. Fields</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.wildcard">61.4.3. Wildcards</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.modifiers">61.4.4. Term Modifiers</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.range">61.4.5. Range Searches</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.fuzzy">61.4.6. Fuzzy Searches</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.matched-terms-limitations">61.4.7. Matched terms limitation</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.proximity-search">61.4.8. Proximity Searches</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boosting">61.4.9. Boosting a Term</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean">61.4.10. Boolean Operators</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.and">61.4.10.1. AND</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.or">61.4.10.2. OR</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.not">61.4.10.3. NOT</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.other-form">61.4.10.4. &amp;&amp;, ||, and ! operators</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.plus">61.4.10.5. +</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.minus">61.4.10.6. -</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.no-operator">61.4.10.7. No Operator</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.grouping">61.4.11. Grouping</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.field-grouping">61.4.12. Field Grouping</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.escaping">61.4.13. Escaping Special Characters</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.query-api.phtml">61.5. Query Construction API</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.exceptions">61.5.1. Query Parser Exceptions</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.term-query">61.5.2. Term Query</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.multiterm-query">61.5.3. Multi-Term Query</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.boolean-query">61.5.4. Boolean Query</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.wildcard">61.5.5. Wildcard Query</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.fuzzy">61.5.6. Fuzzy Query</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.phrase-query">61.5.7. Phrase Query</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.range">61.5.8. Range Query</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.charset.phtml">61.6. Character Set</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.charset.phtml#zend.search.lucene.charset.description">61.6.1. UTF-8 and single-byte character set support</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.charset.phtml#zend.search.lucene.charset.default_analyzer">61.6.2. Default text analyzer</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.charset.phtml#zend.search.lucene.charset.utf_analyzer">61.6.3. UTF-8 compatible text analyzers</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.extending.phtml">61.7. Extensibility</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.analysis">61.7.1. Text Analysis</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.filters">61.7.2. Tokens Filtering</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.scoring">61.7.3. Scoring Algorithms</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.storage">61.7.4. Storage Containers</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.java-lucene.phtml">61.8. Interoperating with Java Lucene</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.java-lucene.phtml#zend.search.lucene.index-creation.file-formats">61.8.1. File Formats</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.java-lucene.phtml#zend.search.lucene.index-creation.index-directory">61.8.2. Index Directory</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.java-lucene.phtml#zend.search.lucene.java-lucene.source-code">61.8.3. Java Source Code</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.advanced.phtml">61.9. Advanced</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.advanced.phtml#zend.search.lucene.advanced.format_migration">61.9.1. Starting from 1.6, handling index format transformations</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.advanced.phtml#zend.search.lucene.advanced.static">61.9.2. Using the index as static property</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.best-practice.phtml">61.10. Best Practices</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.field-names">61.10.1. Field names</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.indexing-performance">61.10.2. Indexing performance</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.shutting-down">61.10.3. Index during Shut Down</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.unique-id">61.10.4. Retrieving documents by unique id</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.memory-usage">61.10.5. Memory Usage</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.encoding">61.10.6. Encoding</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.maintenance">61.10.7. Index maintenance</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.search.lucene.overview"></a>61.1. Overview</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.introduction"></a>61.1.1. Introduction</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> is a general purpose text search engine
            written entirely in <acronym class="acronym">PHP</acronym> 5. Since it stores its index on the
            filesystem and does not require a database server, it can add search capabilities to
            almost any <acronym class="acronym">PHP</acronym>-driven website.
            <code class="classname">Zend_Search_Lucene</code> supports the following features:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Ranked searching - best results returned first</p></li>
<li class="listitem"><p>
                       Many powerful query types: phrase queries, boolean queries, wildcard queries,
                       proximity queries, range queries and many others.
                    </p></li>
<li class="listitem"><p>Search by specific field (e.g., title, author, contents)</p></li>
</ul></div>
<p>

            <code class="classname">Zend_Search_Lucene</code> was derived from the Apache Lucene project.
            The currently (starting from ZF 1.6) supported Lucene index format versions are 1.4 -
            2.3. For more information on Lucene, visit <a class="ulink" href="http://lucene.apache.org/java/docs/" target="_top">http://lucene.apache.org/java/docs/</a>.
        </p>
<div class="note"><table border="0" summary="Note: ">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left"></th>
</tr>
<tr><td align="left" valign="top">
<p>
                Previous <code class="classname">Zend_Search_Lucene</code> implementations support the
                Lucene 1.4 (1.9) - 2.1 index formats.
            </p>
<p>
                Starting from Zend Framework 1.5 any index created using pre-2.1 index format is
                automatically upgraded to Lucene 2.1 format after the
                <code class="classname">Zend_Search_Lucene</code> update and will not be compatible with
                <code class="classname">Zend_Search_Lucene</code> implementations included into Zend
                Framework 1.0.x.
            </p>
</td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.documents-and-fields"></a>61.1.2. Document and Field Objects</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> operates with documents as atomic objects for
            indexing. A document is divided into named fields, and fields have content that can be
            searched.
        </p>
<p>
            A document is represented by the <code class="classname">Zend_Search_Lucene_Document</code>
            class, and this objects of this class contain instances of
            <code class="classname">Zend_Search_Lucene_Field</code> that represent the fields on the
            document.
        </p>
<p>
            It is important to note that any information can be added to the index.
            Application-specific information or metadata can be stored in the document
            fields, and later retrieved with the document during search.
        </p>
<p>
            It is the responsibility of your application to control the indexer.
            This means that data can be indexed from any source
            that is accessible by your application. For example, this could be the
            filesystem, a database, an <acronym class="acronym">HTML</acronym> form, etc.
        </p>
<p>
            <code class="classname">Zend_Search_Lucene_Field</code> class provides several static methods to
            create fields with different characteristics:
        </p>
<pre class="programlisting">
$doc = new Zend_Search_Lucene_Document();

// Field is not tokenized, but is indexed and stored within the index.
// Stored fields can be retrived from the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::Keyword('doctype',
                                                 'autogenerated'));

// Field is not tokenized nor indexed, but is stored in the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed('created',
                                                   time()));

// Binary String valued Field that is not tokenized nor indexed,
// but is stored in the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::Binary('icon',
                                                $iconData));

// Field is tokenized and indexed, and is stored in the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::Text('annotation',
                                              'Document annotation text'));

// Field is tokenized and indexed, but is not stored in the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('contents',
                                                  'My document content'));
</pre>
<p>
            Each of these methods (excluding the
            <code class="methodname">Zend_Search_Lucene_Field::Binary()</code> method) has an optional
            <code class="varname">$encoding</code> parameter for specifying input data encoding.
        </p>
<p>
            Encoding may differ for different documents as well as for different fields within one
            document:
        </p>
<pre class="programlisting">
$doc = new Zend_Search_Lucene_Document();
$doc-&gt;addField(Zend_Search_Lucene_Field::Text('title',
                                              $title,
                                              'iso-8859-1'));
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('contents',
                                                  $contents,
                                                  'utf-8'));
</pre>
<p>
            If encoding parameter is omitted, then the current locale is used at processing time.
            For example:
        </p>
<pre class="programlisting">
setlocale(LC_ALL, 'de_DE.iso-8859-1');
...
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('contents', $contents));
</pre>
<p>
            Fields are always stored and returned from the index in UTF-8 encoding. Any required
            conversion to UTF-8 happens automatically.
        </p>
<p>
            Text analyzers (<a class="link" href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.analysis" title="61.7.1. Text Analysis">see below</a>)
            may also convert text to some other encodings. Actually, the default analyzer converts
            text to 'ASCII//TRANSLIT' encoding. Be careful, however; this translation may depend on
            current locale.
        </p>
<p>
            Fields' names are defined at your discretion in the <code class="methodname">addField()</code>
            method.
        </p>
<p>
            Java Lucene uses the 'contents' field as a default field to search.
            <code class="classname">Zend_Search_Lucene</code> searches through all fields by default, but
            the behavior is configurable. See the <a class="link" href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.fields" title="61.4.2. Fields">"Default search field"</a>
            chapter for details.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.understanding-field-types"></a>61.1.3. Understanding Field Types</h3></div></div></div>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="code">Keyword</code> fields are stored and indexed, meaning that they can be
                    searched as well as displayed in search results. They are not split up into
                    separate words by tokenization. Enumerated database fields usually translate
                    well to Keyword fields in <code class="classname">Zend_Search_Lucene</code>.
                </p></li>
<li class="listitem"><p>
                    <code class="code">UnIndexed</code> fields are not searchable, but they are returned with
                    search hits. Database timestamps, primary keys, file system paths, and other
                    external identifiers are good candidates for UnIndexed fields.
                </p></li>
<li class="listitem"><p>
                    <code class="code">Binary</code> fields are not tokenized or indexed, but are stored for
                    retrieval with search hits. They can be used to store any data encoded as a
                    binary string, such as an image icon.
                </p></li>
<li class="listitem"><p>
                    <code class="code">Text</code> fields are stored, indexed, and tokenized. Text fields are
                    appropriate for storing information like subjects and titles that need to be
                    searchable as well as returned with search results.
                </p></li>
<li class="listitem">
<p>
                    <code class="code">UnStored</code> fields are tokenized and indexed, but not stored in the
                    index. Large amounts of text are best indexed using this type of field. Storing
                    data creates a larger index on disk, so if you need to search but not redisplay
                    the data, use an UnStored field. UnStored fields are practical when using a
                    <code class="classname">Zend_Search_Lucene</code> index in combination with a relational
                    database. You can index large data fields with UnStored fields for searching,
                    and retrieve them from your relational database by using a separate field as an
                    identifier.
               </p>
<div class="table">
<a name="zend.search.lucene.index-creation.understanding-field-types.table"></a><p class="title"><b>Table 61.1. Zend_Search_Lucene_Field Types</b></p>
<div class="table-contents"><table class="table" summary="Zend_Search_Lucene_Field Types" border="1">
<colgroup>
<col>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Field Type</th>
<th>Stored</th>
<th>Indexed</th>
<th>Tokenized</th>
<th>Binary</th>
</tr></thead>
<tbody>
<tr>
<td>Keyword</td>
<td>Yes</td>
<td>Yes</td>
<td>No</td>
<td>No</td>
</tr>
<tr>
<td>UnIndexed</td>
<td>Yes</td>
<td>No</td>
<td>No</td>
<td>No</td>
</tr>
<tr>
<td>Binary</td>
<td>Yes</td>
<td>No</td>
<td>No</td>
<td>Yes</td>
</tr>
<tr>
<td>Text</td>
<td>Yes</td>
<td>Yes</td>
<td>Yes</td>
<td>No</td>
</tr>
<tr>
<td>UnStored</td>
<td>No</td>
<td>Yes</td>
<td>Yes</td>
<td>No</td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.html-documents"></a>61.1.4. HTML documents</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> offers a <acronym class="acronym">HTML</acronym> parsing
            feature. Documents can be created directly from a <acronym class="acronym">HTML</acronym> file or
            string:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Html::loadHTMLFile($filename);
$index-&gt;addDocument($doc);
...
$doc = Zend_Search_Lucene_Document_Html::loadHTML($htmlString);
$index-&gt;addDocument($doc);
</pre>
<p>
            <code class="classname">Zend_Search_Lucene_Document_Html</code> class uses the
            <code class="methodname">DOMDocument::loadHTML()</code> and
            <code class="methodname">DOMDocument::loadHTMLFile()</code> methods to parse the source
            <acronym class="acronym">HTML</acronym>, so it doesn't need <acronym class="acronym">HTML</acronym> to be well formed or
            to be <acronym class="acronym">XHTML</acronym>. On the other hand, it's sensitive to the encoding
            specified by the "meta http-equiv" header tag.
        </p>
<p>
            <code class="classname">Zend_Search_Lucene_Document_Html</code> class recognizes document title,
            body and document header meta tags.
        </p>
<p>
            The 'title' field is actually the /html/head/title value. It's stored within the index,
            tokenized and available for search.
        </p>
<p>
            The 'body' field is the actual body content of the <acronym class="acronym">HTML</acronym> file or
            string. It doesn't include scripts, comments or attributes.
        </p>
<p>
            The <code class="methodname">loadHTML()</code> and <code class="methodname">loadHTMLFile()</code>
            methods of <code class="classname">Zend_Search_Lucene_Document_Html</code> class also have
            second optional argument. If it's set to <code class="constant">TRUE</code>, then body content is
            also stored within index and can be retrieved from the index. By default, the body is
            tokenized and indexed, but not stored.
        </p>
<p>
            The third parameter of <code class="methodname">loadHTML()</code> and
            <code class="methodname">loadHTMLFile()</code> methods optionally specifies source
            <acronym class="acronym">HTML</acronym> document encoding. It's used if encoding is not specified using
            Content-type HTTP-EQUIV meta tag.
        </p>
<p>
            Other document header meta tags produce additional document fields. The field 'name' is
            taken from 'name' attribute, and the 'content' attribute populates the field 'value'.
            Both are tokenized, indexed and stored, so documents may be searched by their meta tags
            (for example, by keywords).
        </p>
<p>
            Parsed documents may be augmented by the programmer with any other field:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Html::loadHTML($htmlString);
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed('created',
                                                   time()));
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed('updated',
                                                   time()));
$doc-&gt;addField(Zend_Search_Lucene_Field::Text('annotation',
                                              'Document annotation text'));
$index-&gt;addDocument($doc);
</pre>
<p>
            Document links are not included in the generated document, but may be retrieved with
            the <code class="methodname">Zend_Search_Lucene_Document_Html::getLinks()</code> and
            <code class="methodname">Zend_Search_Lucene_Document_Html::getHeaderLinks()</code> methods:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Html::loadHTML($htmlString);
$linksArray = $doc-&gt;getLinks();
$headerLinksArray = $doc-&gt;getHeaderLinks();
</pre>
<p>
            Starting from Zend Framework 1.6 it's also possible to exclude links with
            <code class="code">rel</code> attribute set to <code class="code">'nofollow'</code>. Use
            <code class="methodname">Zend_Search_Lucene_Document_Html::setExcludeNoFollowLinks($true)</code>
            to turn on this option.
        </p>
<p>
            <code class="methodname">Zend_Search_Lucene_Document_Html::getExcludeNoFollowLinks()</code>
            method returns current state of "Exclude nofollow links" flag.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.docx-documents"></a>61.1.5. Word 2007 documents</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> offers a Word 2007 parsing feature. Documents
            can be created directly from a Word 2007 file:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Docx::loadDocxFile($filename);
$index-&gt;addDocument($doc);
</pre>
<p>
            <code class="classname">Zend_Search_Lucene_Document_Docx</code> class uses the
            <code class="code">ZipArchive</code> class and <code class="code">simplexml</code> methods to parse the source
            document. If the <code class="code">ZipArchive</code> class (from module php_zip) is not available,
            the <code class="classname">Zend_Search_Lucene_Document_Docx</code> will also not be available
            for use with Zend Framework.
        </p>
<p>
            <code class="classname">Zend_Search_Lucene_Document_Docx</code> class recognizes document meta
            data and document text. Meta data consists, depending on document contents, of filename,
            title, subject, creator, keywords, description, lastModifiedBy, revision, modified,
            created.
        </p>
<p>
            The 'filename' field is the actual Word 2007 file name.
        </p>
<p>
            The 'title' field is the actual document title.
        </p>
<p>
            The 'subject' field is the actual document subject.
        </p>
<p>
            The 'creator' field is the actual document creator.
        </p>
<p>
            The 'keywords' field contains the actual document keywords.
        </p>
<p>
            The 'description' field is the actual document description.
        </p>
<p>
            The 'lastModifiedBy' field is the username who has last modified the actual document.
        </p>
<p>
            The 'revision' field is the actual document revision number.
        </p>
<p>
            The 'modified' field is the actual document last modified date / time.
        </p>
<p>
            The 'created' field is the actual document creation date / time.
        </p>
<p>
            The 'body' field is the actual body content of the Word 2007 document. It only includes
            normal text, comments and revisions are not included.
        </p>
<p>
            The <code class="methodname">loadDocxFile()</code> methods of
            <code class="classname">Zend_Search_Lucene_Document_Docx</code> class also have second optional
            argument. If it's set to <code class="constant">TRUE</code>, then body content is also stored
            within index and can be retrieved from the index. By default, the body is tokenized and
            indexed, but not stored.
        </p>
<p>
            Parsed documents may be augmented by the programmer with any other field:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Docx::loadDocxFile($filename);
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed(
    'indexTime',
    time())
);
$doc-&gt;addField(Zend_Search_Lucene_Field::Text(
    'annotation',
    'Document annotation text')
);
$index-&gt;addDocument($doc);
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.pptx-documents"></a>61.1.6. Powerpoint 2007 documents</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> offers a Powerpoint 2007 parsing feature.
            Documents can be created directly from a Powerpoint 2007 file:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Pptx::loadPptxFile($filename);
$index-&gt;addDocument($doc);
</pre>
<p>
            <code class="classname">Zend_Search_Lucene_Document_Pptx</code> class uses the
            <code class="code">ZipArchive</code> class and <code class="code">simplexml</code> methods to parse the source
            document. If the <code class="code">ZipArchive</code> class (from module php_zip) is not available,
            the <code class="classname">Zend_Search_Lucene_Document_Pptx</code> will also not be available
            for use with Zend Framework.
        </p>
<p>
            <code class="classname">Zend_Search_Lucene_Document_Pptx</code> class recognizes document meta
            data and document text. Meta data consists, depending on document contents, of filename,
            title, subject, creator, keywords, description, lastModifiedBy, revision, modified,
            created.
        </p>
<p>
            The 'filename' field is the actual Powerpoint 2007 file name.
        </p>
<p>
            The 'title' field is the actual document title.
        </p>
<p>
            The 'subject' field is the actual document subject.
        </p>
<p>
            The 'creator' field is the actual document creator.
        </p>
<p>
            The 'keywords' field contains the actual document keywords.
        </p>
<p>
            The 'description' field is the actual document description.
        </p>
<p>
            The 'lastModifiedBy' field is the username who has last modified the actual document.
        </p>
<p>
            The 'revision' field is the actual document revision number.
        </p>
<p>
            The 'modified' field is the actual document last modified date / time.
        </p>
<p>
            The 'created' field is the actual document creation date / time.
        </p>
<p>
            The 'body' field is the actual content of all slides and slide notes in the Powerpoint
            2007 document.
        </p>
<p>
            The <code class="methodname">loadPptxFile()</code> methods of
            <code class="classname">Zend_Search_Lucene_Document_Pptx</code> class also have second optional
            argument. If it's set to <code class="constant">TRUE</code>, then body content is also stored
            within index and can be retrieved from the index. By default, the body is tokenized and
            indexed, but not stored.
        </p>
<p>
            Parsed documents may be augmented by the programmer with any other field:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Pptx::loadPptxFile($filename);
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed(
    'indexTime',
    time()));
$doc-&gt;addField(Zend_Search_Lucene_Field::Text(
    'annotation',
    'Document annotation text'));
$index-&gt;addDocument($doc);
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.xlsx-documents"></a>61.1.7. Excel 2007 documents</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> offers a Excel 2007 parsing feature. Documents
            can be created directly from a Excel 2007 file:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Xlsx::loadXlsxFile($filename);
$index-&gt;addDocument($doc);
</pre>
<p>
            <code class="classname">Zend_Search_Lucene_Document_Xlsx</code> class uses the
            <code class="code">ZipArchive</code> class and <code class="code">simplexml</code> methods to parse the source
            document. If the <code class="code">ZipArchive</code> class (from module php_zip) is not available,
            the <code class="classname">Zend_Search_Lucene_Document_Xlsx</code> will also not be available
            for use with Zend Framework.
        </p>
<p>
            <code class="classname">Zend_Search_Lucene_Document_Xlsx</code> class recognizes document meta
            data and document text. Meta data consists, depending on document contents, of filename,
            title, subject, creator, keywords, description, lastModifiedBy, revision, modified,
            created.
        </p>
<p>
            The 'filename' field is the actual Excel 2007 file name.
        </p>
<p>
            The 'title' field is the actual document title.
        </p>
<p>
            The 'subject' field is the actual document subject.
        </p>
<p>
            The 'creator' field is the actual document creator.
        </p>
<p>
            The 'keywords' field contains the actual document keywords.
        </p>
<p>
            The 'description' field is the actual document description.
        </p>
<p>
            The 'lastModifiedBy' field is the username who has last modified the actual document.
        </p>
<p>
            The 'revision' field is the actual document revision number.
        </p>
<p>
            The 'modified' field is the actual document last modified date / time.
        </p>
<p>
            The 'created' field is the actual document creation date / time.
        </p>
<p>
            The 'body' field is the actual content of all cells in all worksheets of the Excel 2007
            document.
        </p>
<p>
            The <code class="methodname">loadXlsxFile()</code> methods of
            <code class="classname">Zend_Search_Lucene_Document_Xlsx</code> class also have second optional
            argument. If it's set to <code class="constant">TRUE</code>, then body content is also stored
            within index and can be retrieved from the index. By default, the body is tokenized and
            indexed, but not stored.
        </p>
<p>
            Parsed documents may be augmented by the programmer with any other field:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Xlsx::loadXlsxFile($filename);
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed(
    'indexTime',
    time()));
$doc-&gt;addField(Zend_Search_Lucene_Field::Text(
    'annotation',
    'Document annotation text'));
$index-&gt;addDocument($doc);
</pre>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.rest.server.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.search.lucene.index-creation.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">60.3. Zend_Rest_Server </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 61.2. Building Indexes</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
