<?php $title = 'Chapter 68. Zend_Test'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 68. Zend_Test</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.tag.cloud.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.test.phpunit.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.test"></a>Chapter 68. Zend_Test</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.test.phtml#zend.test.introduction">68.1. Introduction</a></span></dt>
<dt><span class="sect1"><a href="zend.test.phpunit.phtml">68.2. Zend_Test_PHPUnit</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.test.phpunit.phtml#zend.test.phpunit.bootstrapping">68.2.1. Bootstrapping your TestCase</a></span></dt>
<dt><span class="sect2"><a href="zend.test.phpunit.phtml#zend.test.phpunit.testing">68.2.2. Testing your Controllers and MVC Applications</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.testing.redirector">68.2.2.1. Controller Tests and the Redirector Action Helper</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions">68.2.3. Assertions</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.query">68.2.3.1. CSS Selector Assertions</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.xpath">68.2.3.2. XPath Assertions</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.redirect">68.2.3.3. Redirect Assertions</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.header">68.2.3.4. Response Header Assertions</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.request">68.2.3.5. Request Assertions</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.test.phpunit.phtml#zend.test.phpunit.examples">68.2.4. Examples</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.test.phpunit.db.phtml">68.3. Zend_Test_PHPUnit_Db</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.quickstart">68.3.1. Quickstart</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.quickstart.testcase">68.3.1.1. Setup a Database TestCase</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.quickstart.dataset">68.3.1.2. Specify a seed dataset</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.quickstart.initial-tests">68.3.1.3. A few initial database tests</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.testing">68.3.2. Usage, API and Extensions Points</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.testing.testcase">68.3.2.1. The Zend_Test_PHPUnit_DatabaseTestCase class</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.testing.controllerintegration">68.3.2.2. Integrating Database Testing with the ControllerTestCase</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.adapter">68.3.3. Using the Database Testing Adapter</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.test.introduction"></a>68.1. Introduction</h2></div></div></div>
<p>
        <code class="classname">Zend_Test</code> provides tools to facilitate unit testing of your
        Zend Framework applications. At this time, we offer facilities to enable
        testing of your Zend Framework <acronym class="acronym">MVC</acronym> applications
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.tag.cloud.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.test.phpunit.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">67.2. Zend_Tag_Cloud </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 68.2. Zend_Test_PHPUnit</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
