<?php $title = '25.9. Exchanging currencies'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">25.9. Exchanging currencies</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.currency.calculation.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 25. Zend_Currency</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.currency.additional.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.currency.exchange"></a>25.9. Exchanging currencies</h2></div></div></div>
<p>
        Within the previous section we discussed currency calculations. But as you can imaging
        calculating currencies does often mean to calculate different currencies from different
        countries.
    </p>
<p>
        In this case the currencies have to be exchanged so that both use the same currency.
        Within real live this information is available by banks or by daily papers. But as we
        are in web, we should use available exchange services.
        <code class="classname">Zend_Currency</code> allows their usage with a simple callback.
    </p>
<p>
        First let's write a simple exchange service.
    </p>
<pre class="programlisting">
class SimpleExchange implements Zend_Currency_CurrencyInterface
{
    public function getRate($from, $to)
    {
        if ($from !== "USD") {
            throw new Exception('We can only exchange USD');
        }

        switch ($to) {
            case 'EUR':
                return 2;
            case 'JPE':
                return 0.7;
       }

       throw new Exception('Unable to exchange $to');
    }
}
</pre>
<p>
        We have now created a manual exchange service. It will not fit the real live, but it
        shows you how currency exchange works.
    </p>
<p>
        Your exchange class must implement the
        <code class="classname">Zend_Currency_CurrencyInterface</code> interface. This interface
        requires the single method <code class="methodname">getRate()</code> to be implemented. This
        method has two parameters it will receive. Both are the short names for the given
        currencies. <code class="classname">Zend_Currency</code> on the other side needs the exchange
        rate to be returned.
    </p>
<p>
        In a living exchange class you would probably ask the service provider for the correct
        exchange rates. For our example the manual rate will be ok.
    </p>
<p>
        Now we will simply attach our exchange class with <code class="classname">Zend_Currency</code>.
        There are two ways to do this. Eigher by attaching a instance of the Exchange class, or
        by simply giving a string with the classname.
    </p>
<pre class="programlisting">
$currency = new Zend_Currency(
    array(
        'value'    =&gt; 1000,
        'currency' =&gt; 'EUR',
    )
);

$service  = new SimpleExchange();

// attach the exchange service
$currency-&gt;setService($service);

$currency2 = new Zend_Currency(
    array(
        'value'    =&gt; 1000,
        'currency' =&gt; 'USD',
    )
);

print $currency-&gt;add($currency2);
</pre>
<p>
        The above example will return '$ 3.000' because the 1.000 <acronym class="acronym">USD</acronym> will be
        converted by a rate of 2 to 2.000 <acronym class="acronym">EUR</acronym>.
    </p>
<div class="note"><table border="0" summary="Note: Calculation without exchange service">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Calculation without exchange service</th>
</tr>
<tr><td align="left" valign="top"><p>
            When you try to calculate two currency objects which do not use the same currency
            and have no exchange service attached, you will get an exception. The reason is
            that <code class="classname">Zend_Currency</code> is then not able to switch between the
            different currencies.
        </p></td></tr>
</table></div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.currency.calculation.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.currency.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.currency.additional.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">25.8. Calculating with currencies </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 25.10. Additional informations on Zend_Currency</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
