<?php $title = 'Chapter 70. Zend_TimeSync'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 70. Zend_TimeSync</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.text.table.introduction.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.timesync.working.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.timesync"></a>Chapter 70. Zend_TimeSync</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.timesync.phtml#zend.timesync.introduction">70.1. Introduction</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.timesync.phtml#zend.timesync.introduction.why">70.1.1. Why Zend_TimeSync ?</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.phtml#zend.timesync.introduction.ntp">70.1.2. What is NTP ?</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.phtml#zend.timesync.introduction.sntp">70.1.3. What is SNTP?</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.phtml#zend.timesync.introduction.problematic">70.1.4. Problematic usage</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.phtml#zend.timesync.introduction.decision">70.1.5. Decide which server to use</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.timesync.working.phtml">70.2. Working with Zend_TimeSync</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.timesync.working.phtml#zend.timesync.working.generic">70.2.1. Generic Time Server Request</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.working.phtml#zend.timesync.working.multiple">70.2.2. Multiple Time Servers</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.working.phtml#zend.timesync.working.protocol">70.2.3. Protocols of Time Servers</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.working.phtml#zend.timesync.working.ports">70.2.4. Using Ports for Time Servers</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.working.phtml#zend.timesync.working.options">70.2.5. Time Servers Options</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.working.phtml#zend.timesync.working.different">70.2.6. Using Different Time Servers</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.working.phtml#zend.timesync.working.informations">70.2.7. Information from Time Servers</a></span></dt>
<dt><span class="sect2"><a href="zend.timesync.working.phtml#zend.timesync.working.exceptions">70.2.8. Handling Exceptions</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.timesync.introduction"></a>70.1. Introduction</h2></div></div></div>
<p>
        <code class="classname">Zend_TimeSync</code> is able to receive internet or network time from a time
        server using the <span class="emphasis"><em>NTP</em></span> or <span class="emphasis"><em>SNTP</em></span> protocol.
        With <code class="classname">Zend_TimeSync</code>, Zend Framework is able to act independently from
        the time settings of the server where it is running.
    </p>
<p>
        To be independent from the actual time of the server, <code class="classname">Zend_TimeSync</code>
        works with the difference of the real time which is sent through NTP or SNTP and the
        internal server's time.
    </p>
<div class="note"><table border="0" summary="Note: Background">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Background</th>
</tr>
<tr><td align="left" valign="top"><p>
            <code class="classname">Zend_TimeSync</code> is not able to change the server's time, but it
            will return a <a class="link" href="zend.date.phtml#zend.date.introduction" title="26.1. Introduction">Zend_Date</a> instance from
            which the difference from the server's time can be worked with.
        </p></td></tr>
</table></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.timesync.introduction.why"></a>70.1.1. Why Zend_TimeSync ?</h3></div></div></div>
<p>
            So why would someone use <code class="classname">Zend_TimeSync</code> ?
        </p>
<p>
            Normally every server within a multi-server farm will have a service running which
            synchronizes its own time with a time server. So within a standard environment it should
            not be necessary to use <code class="classname">Zend_TimeSync</code>. But it can become handy if
            there is no service available and if you don't have the right to install such a service.
        </p>
<p>
            Here are some example use cases, for which <code class="classname">Zend_TimeSync</code> is
            perfect suited:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: opencircle; ">
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Server without time service</em></span>
                </p>
<p>
                    If your application is running on a server and this server does not have any
                    time service running, it may make sense to use
                    <code class="classname">Zend_TimeSync</code> in your application.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Separate database server</em></span>
                </p>
<p>
                    If your database is running on a different server and this server is not
                    connected with <span class="emphasis"><em>NTP</em></span> or <span class="emphasis"><em>SNTP</em></span>
                    to the application server, you might have problems using storing and using time
                    stamp data.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Multiple servers</em></span>
                </p>
<p>
                    If your application is running on more than one server and these servers' time
                    bases are not syncronized, you can expect problems within your application when
                    part of the application is coming from one server and another part from another
                    server.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Batch processing</em></span>
                </p>
<p>
                    If you want to work with a time service within a batch file or within a
                    command line application, <code class="classname">Zend_TimeSync</code> may be of use.
                </p>
</li>
</ul></div>
<p>
            <code class="classname">Zend_TimeSync</code> may provide a good solution in all of these cases
            and can be used if you are unable to run any services on your server.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.timesync.introduction.ntp"></a>70.1.2. What is NTP ?</h3></div></div></div>
<p>
            The Network Time Protocol (<span class="emphasis"><em>NTP</em></span>) is a protocol
            for synchronizing multiple systems' clocks over packet-switched, variable-latency data
            networks. NTP uses UDP port 123 as its transport layer. See the <a class="ulink" href="http://en.wikipedia.org/wiki/Network_Time_Protocol" target="_top">wikipedia article</a>
            for details about this protocol.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.timesync.introduction.sntp"></a>70.1.3. What is SNTP?</h3></div></div></div>
<p>
            The Simple Network Time Protocol (<span class="emphasis"><em>SNTP</em></span>) is a
            protocol synchronizing multiple systems' clocks over packet-switched, variable-latency
            data networks. SNTP uses UDP port 37 as its transport layer. It is closely related to
            the Network Time Protocol, but simpler.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.timesync.introduction.problematic"></a>70.1.4. Problematic usage</h3></div></div></div>
<p>
            Be warned that when you are using <code class="classname">Zend_TimeSync</code> you will have to
            think about some details related to the structure of time sync and the internet itself.
            Correct usage and best practices will be described here. Read carefully before you begin
            using <code class="classname">Zend_TimeSync</code>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.timesync.introduction.decision"></a>70.1.5. Decide which server to use</h3></div></div></div>
<p>
            You should select the time server that you want to use very carefully according to the
            following criteria:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: opencircle; ">
<li class="listitem" style="list-style-type: circle">
<p>
                    Distance
                </p>
<p>
                    The distance from your application server to the time server. If your server is
                    in Europe, it would make little sense to select a time server in Tahiti. Always
                    select a server which is not far away. This reduces the request time and overall
                    network load.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    Speed
                </p>
<p>
                    How long it takes to receive the request is also relevant. Try different servers
                    to get the best result. If you are requesting a server which is never
                    accessible, you will always have an unnecessary delay.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    Splitting
                </p>
<p>
                    Do not always use the same server. All time servers will lock out requests from
                    servers that are flooding the server. If your application requires heavy use of
                    time servers, you should consider one of the pools described later.
                </p>
</li>
</ul></div>
<p>
            So where can you find a time server? Generally you can use any timeserver you can
            connect to. This can be a time server within your LAN or any public time server you have
            access to. If you decide to use a public time server, you should consider using a server
            pool. Server pools are public addresses from which you will get a random, pooled time
            server by requesting the time. This way you will not have to split your requests. There
            are public server pools available for many regions which you may use to avoid problems
            mentioned above.
        </p>
<p>
            See <a class="ulink" href="http://www.pool.ntp.org" target="_top">pool.ntp.org</a> to find your nearest
            server pool. For example, if your server is located within Germany you can connect to
            <span class="emphasis"><em>0.europe.pool.ntp.org</em></span>.
        </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.text.table.introduction.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.timesync.working.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">69.2. Zend_Text_Table </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 70.2. Working with Zend_TimeSync</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
