<?php $title = 'Chapter 45. Zend_Mail'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 45. Zend_Mail</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.log.factory.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.sending.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.mail"></a>Chapter 45. Zend_Mail</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.mail.phtml#zend.mail.introduction">45.1. Introduction</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.mail.phtml#zend.mail.introduction.getting-started">45.1.1. Getting started</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.phtml#zend.mail.introduction.sendmail">45.1.2. Configuring the default sendmail transport</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.mail.sending.phtml">45.2. Sending via SMTP</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.multiple-emails.phtml">45.3. Sending Multiple Mails per SMTP Connection</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.different-transports.phtml">45.4. Using Different Transports</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="zend.mail.different-transports.phtml#zend.mail.file-transport">45.4.1. Using File Transport</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="zend.mail.html-mails.phtml">45.5. HTML E-Mail</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.attachments.phtml">45.6. Attachments</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.adding-recipients.phtml">45.7. Adding Recipients</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.boundary.phtml">45.8. Controlling the MIME Boundary</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.additional-headers.phtml">45.9. Additional Headers</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.character-sets.phtml">45.10. Character Sets</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.encoding.phtml">45.11. Encoding</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.smtp-authentication.phtml">45.12. SMTP Authentication</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.smtp-secure.phtml">45.13. Securing SMTP Transport</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.read.phtml">45.14. Reading Mail Messages</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-example">45.14.1. Simple example using Pop3</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-open-local">45.14.2. Opening a local storage</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-open-remote">45.14.3. Opening a remote storage</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-fetching">45.14.4. Fetching messages and simple methods</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-message">45.14.5. Working with messages</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-flags">45.14.6. Checking for flags</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-folders">45.14.7. Using folders</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-advanced">45.14.8. Advanced Use</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.mail.read.phtml#zend.mail.read-advanced.noop">45.14.8.1. Using NOOP</a></span></dt>
<dt><span class="sect3"><a href="zend.mail.read.phtml#zend.mail.read-advanced.caching">45.14.8.2. Caching instances</a></span></dt>
<dt><span class="sect3"><a href="zend.mail.read.phtml#zend.mail.read-advanced.extending">45.14.8.3. Extending Protocol Classes</a></span></dt>
<dt><span class="sect3"><a href="zend.mail.read.phtml#zend.mail.read-advanced.quota">45.14.8.4. Using Quota (since 1.5)</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.introduction"></a>45.1. Introduction</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mail.introduction.getting-started"></a>45.1.1. Getting started</h3></div></div></div>
<p>
            <code class="classname">Zend_Mail</code> provides generalized functionality to compose and send
            both text and <acronym class="acronym">MIME</acronym>-compliant multipart e-mail messages. Mail can be
            sent with <code class="classname">Zend_Mail</code> via the default
            <code class="classname">Zend_Mail_Transport_Sendmail</code> transport or via
            <code class="classname">Zend_Mail_Transport_Smtp</code>.
        </p>
<div class="example">
<a name="zend.mail.introduction.example-1"></a><p class="title"><b>Example 45.1. Simple E-Mail with Zend_Mail</b></p>
<div class="example-contents">
<p>
                A simple e-mail consists of some recipients, a subject, a body and a sender. To send
                such a mail using <code class="classname">Zend_Mail_Transport_Sendmail</code>, do the
                following:
            </p>
<pre class="programlisting">
$mail = new Zend_Mail();
$mail-&gt;setBodyText('This is the text of the mail.');
$mail-&gt;setFrom('somebody@example.com', 'Some Sender');
$mail-&gt;addTo('somebody_else@example.com', 'Some Recipient');
$mail-&gt;setSubject('TestSubject');
$mail-&gt;send();
</pre>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: Minimum definitions">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Minimum definitions</th>
</tr>
<tr><td align="left" valign="top"><p>
                In order to send an e-mail with <code class="classname">Zend_Mail</code> you have to specify
                at least one recipient, a sender (e.g., with <code class="methodname">setFrom()</code>),
                and a message body (text and/or <acronym class="acronym">HTML</acronym>).
            </p></td></tr>
</table></div>
<p>
            For most mail attributes there are "get" methods to read the information stored in the
            mail object. for further details, please refer to the <acronym class="acronym">API</acronym>
            documentation. A special one is <code class="methodname">getRecipients()</code>. It returns an
            array with all recipient e-mail addresses that were added prior to the method call.
        </p>
<p>
            For security reasons, <code class="classname">Zend_Mail</code> filters all header fields to
            prevent header injection with newline (<span class="emphasis"><em>\n</em></span>) characters.
            Double quotation is changed to single quotation and angle brackets to square brackets in
            the name of sender and recipients. If the marks are in email address, the marks will be
            removed.
        </p>
<p>
            You also can use most methods of the <code class="classname">Zend_Mail</code> object with a
            convenient fluent interface.
        </p>
<pre class="programlisting">
$mail = new Zend_Mail();
$mail-&gt;setBodyText('This is the text of the mail.')
    -&gt;setFrom('somebody@example.com', 'Some Sender')
    -&gt;addTo('somebody_else@example.com', 'Some Recipient')
    -&gt;setSubject('TestSubject')
    -&gt;send();
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mail.introduction.sendmail"></a>45.1.2. Configuring the default sendmail transport</h3></div></div></div>
<p>
            The default transport for a <code class="classname">Zend_Mail</code> instance is
            <code class="classname">Zend_Mail_Transport_Sendmail</code>. It is essentially a wrapper to the
            <acronym class="acronym">PHP</acronym> <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a> function. If you
            wish to pass additional parameters to the <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a> function, simply
            create a new transport instance and pass your parameters to the constructor. The new
            transport instance can then act as the default <code class="classname">Zend_Mail</code>
            transport, or it can be passed to the <code class="methodname">send()</code> method of
            <code class="classname">Zend_Mail</code>.
        </p>
<div class="example">
<a name="zend.mail.introduction.sendmail.example-1"></a><p class="title"><b>Example 45.2. 
                Passing additional parameters to the Zend_Mail_Transport_Sendmail transport
            </b></p>
<div class="example-contents">
<p>
                This example shows how to change the Return-Path of the <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a> function.
            </p>
<pre class="programlisting">
$tr = new Zend_Mail_Transport_Sendmail('-freturn_to_me@example.com');
Zend_Mail::setDefaultTransport($tr);

$mail = new Zend_Mail();
$mail-&gt;setBodyText('This is the text of the mail.');
$mail-&gt;setFrom('somebody@example.com', 'Some Sender');
$mail-&gt;addTo('somebody_else@example.com', 'Some Recipient');
$mail-&gt;setSubject('TestSubject');
$mail-&gt;send();
</pre>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: Safe mode restrictions">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Safe mode restrictions</th>
</tr>
<tr><td align="left" valign="top"><p>
                The optional additional parameters will be cause the <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a> function to
                fail if <acronym class="acronym">PHP</acronym> is running in safe mode.
            </p></td></tr>
</table></div>
<div class="warning"><table border="0" summary="Warning: Sendmail Transport and Windows">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Warning]" src="images/warning.png"></td>
<th align="left">Sendmail Transport and Windows</th>
</tr>
<tr><td align="left" valign="top">
<p>
                As the <acronym class="acronym">PHP</acronym> manual states the <code class="methodname">mail()</code>
                function has different behaviour on Windows and on *nix based systems. Using the
                Sendmail Transport on Windows will not work in combination with
                <code class="methodname">addBcc()</code>. The <code class="methodname">mail()</code> function will
                sent to the BCC recipient such that all the other recipients can see him as
                recipient!
            </p>
<p>
                Therefore if you want to use BCC on a windows server, use the SMTP
                transport for sending!
            </p>
</td></tr>
</table></div>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.log.factory.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.sending.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">44.5. Using the Factory to Create a Log </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 45.2. Sending via SMTP</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
