<?php $title = 'Chapter 25. Zend_Currency'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 25. Zend_Currency</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.controller.exceptions.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.currency.usage.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.currency"></a>Chapter 25. Zend_Currency</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.currency.phtml#zend.currency.introduction">25.1. Introduction to Zend_Currency</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="zend.currency.phtml#zend.currency.introduction.list">25.1.1. Why should you use Zend_Currency?</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="zend.currency.usage.phtml">25.2. Using Zend_Currency</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.currency.usage.phtml#zend.currency.usage.generic">25.2.1. Generic usage</a></span></dt>
<dt><span class="sect2"><a href="zend.currency.usage.phtml#zend.currency.usage.locale">25.2.2. Currency creation based on a locale</a></span></dt>
<dt><span class="sect2"><a href="zend.currency.usage.phtml#zend.currency.usage.territory">25.2.3. Currency creation based on a country</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.currency.options.phtml">25.3. Options for currencies</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.description.phtml">25.4. What makes a currency?</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.position.phtml">25.5. Where is the currency?</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.number.phtml">25.6. How does the currency look like?</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.value.phtml">25.7. How much is my currency?</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.currency.value.phtml#zend.currency.value.money">25.7.1. Working with currency values</a></span></dt>
<dt><span class="sect2"><a href="zend.currency.value.phtml#zend.currency.value.precision">25.7.2. Using precision on currencies</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.currency.calculation.phtml">25.8. Calculating with currencies</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.exchange.phtml">25.9. Exchanging currencies</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.additional.phtml">25.10. Additional informations on Zend_Currency</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.currency.additional.phtml#zend.currency.additional.informations">25.10.1. Currency informations</a></span></dt>
<dt><span class="sect2"><a href="zend.currency.additional.phtml#zend.currency.additional.cache">25.10.2. Currency Performance Optimization</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.currency.introduction"></a>25.1. Introduction to Zend_Currency</h2></div></div></div>
<p>
        <code class="classname">Zend_Currency</code> is part of the strong support for I18n in Zend
        Framework. It handles all issues related to currency, money representation, formatting,
        exchange services and calculation.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.currency.introduction.list"></a>25.1.1. Why should you use Zend_Currency?</h3></div></div></div>
<p>
            <code class="classname">Zend_Currency</code> offers you the following benefit:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: opencircle; ">
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Complete Locale support</em></span>
                </p>
<p>
                    This component works with all available locales and therefore knows about more
                    than 100 different localized currencies. This includes informations like
                    currency names, abbreviations, money signs and much more.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Reusable Currency Definitions</em></span>
                </p>
<p>
                    <code class="classname">Zend_Currency</code> has the advantage that already defined
                    currency representations can be reused. You could also have 2 different
                    representations for the same currency.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Currency calculation</em></span>
                </p>
<p>
                    <code class="classname">Zend_Currency</code> allows you also to calculate with currency
                    values. Therefore, it provides you an interface to exchange services.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Additional Methods</em></span>
                </p>
<p>
                    <code class="classname">Zend_Currency</code> includes several additional methods that
                    offer detailed informations about currencies like which currency is used
                    within a defined region and what are the known abbreviations of a currency.
                </p>
</li>
</ul></div>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.controller.exceptions.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.currency.usage.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">24.12. MVC Exceptions </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 25.2. Using Zend_Currency</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
