<?php $title = '42.9. The Class Map Generator utility: bin/classmap_generator.php'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">42.9. The Class Map Generator utility: bin/classmap_generator.php</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.register.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 42. Zend_Loader</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.locale.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.loader.classmap-generator"></a>42.9. The Class Map Generator utility: bin/classmap_generator.php</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.loader.classmap-generator.intro"></a>42.9.1. Overview</h3></div></div></div>
<p>
            The script <code class="filename">bin/classmap_generator.php</code> can be used to generate class
            map files for use with <a class="link" href="zend.loader.class-map-autoloader.phtml" title="42.8. The ClassMapAutoloader">the
                ClassMapAutoloader</a>.
        </p>
<p>
            Internally, it consumes both <a class="link" href="zend.console.getopt.phtml" title="Chapter 23. Zend_Console_Getopt">Zend_Console_Getopt</a> (for parsing command-line
            options) and Zend_File_ClassFileLocator for
            recursively finding all PHP class files in a given tree.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.loader.classmap-generator.quick-start"></a>42.9.2. Quick Start</h3></div></div></div>
<p>
            You may run the script over any directory containing source code. By default, it will
            look in the current directory, and will write the script to
            <code class="filename">autoload_classmap.php</code> in the directory you specify.
        </p>
<pre class="programlisting">
php classmap_generator.php Some/Directory/
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.loader.classmap-generator.options"></a>42.9.3. Configuration Options</h3></div></div></div>
<div class="variablelist">
<p class="title"><b>Class Map Generator Options</b></p>
<dl class="variablelist">
<dt><span class="term">--help or -h</span></dt>
<dd><p>
                        Returns the usage message. If any other options are provided, they will be
                        ignored.
                    </p></dd>
<dt><span class="term">--library or -l</span></dt>
<dd><p>
                        Expects a single argument, a string specifying the library directory to
                        parse. If this option is not specified, it will assume the current working
                        directory.
                    </p></dd>
<dt><span class="term">--output or -o</span></dt>
<dd><p>
                        Where to write the autoload class map file. If not provided, assumes
                        "autoload_classmap.php" in the library directory.
                    </p></dd>
<dt><span class="term">--overwrite or -w</span></dt>
<dd><p>
                        If an autoload class map file already exists with the name as specified via
                        the <code class="varname">--output</code> option, you can overwrite it by specifying
                        this flag. Otherwise, the script will not write the class map and return a
                        warning.
                    </p></dd>
</dl>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.register.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.locale.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">register </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Chapter 43. Zend_Locale</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
