<?php $title = '38.8. The UserAgent Features Adapter'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">38.8. The UserAgent Features Adapter</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.http.user-agent-device.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 38. Zend_Http</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.http.user-agent-features-browscap.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.http.user-agent-features"></a>38.8. The UserAgent Features Adapter</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features.intro"></a>38.8.1. Overview</h3></div></div></div>
<p>
            A variety of databases exist that define browser device features and capabilities.
            <code class="classname">Zend_Http_UserAgent</code> provides the ability to utilize the database
            of your choice via a features adapter interface.
        </p>
<p>
            The features adapter is passed a request array that contains the User-Agent string and
            any other relevant HTTP headers and environment pertinent to detecting the device in
            use. Additionally, if any adapter-specific configuration might be needed, an additional
            configuration array will be provided. The adapter must then return an array of device
            capabilities.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features.quick-start"></a>38.8.2. Quick Start</h3></div></div></div>
<p>
            The adapter interface is quite simple, defining but the single static method
            <code class="methodname">getFromRequest()</code>.
        </p>
<pre class="programlisting">
interface Zend_Http_UserAgent_Features_Adapter
{
    /**
     * Retrieve the browser's features from a given request object ($_SERVER)
     *
     * @return array
     */
    public static function getFromRequest($request, array $config);
}
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features.options"></a>38.8.3. Configuration Options</h3></div></div></div>
<p>
            Options are defined on a per-adapter basis.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features.methods"></a>38.8.4. Available Methods</h3></div></div></div>
<div class="variablelist"><dl class="variablelist">
<dt>
<a name="zend.http.user-agent-features.methods.get-from-request"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getFromRequest</span>(<span class="methodparam">array $request, array $config</span>);</code>
                </span>
</dt>
<dd><p>
                        Decompose the request in order to return an array of device capabilities.
                    </p></dd>
</dl></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.http.user-agent-device.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.http.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.http.user-agent-features-browscap.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">38.7. The UserAgent Device Interface </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 38.9. The Browscap UserAgent Features Adapter</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
