<?php $title = 'Chapter 38. Zend_Http'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 38. Zend_Http</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.gdata.exception.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.http.client.advanced.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.http"></a>Chapter 38. Zend_Http</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.http.phtml#zend.http.client">38.1. Introduction</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.usage">38.1.1. Using Zend_Http_Client</a></span></dt>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.configuration">38.1.2. Configuration Parameters</a></span></dt>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.basic-requests">38.1.3. Performing Basic HTTP Requests</a></span></dt>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.parameters">38.1.4. Adding GET and POST parameters </a></span></dt>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.accessing_last">38.1.5. Accessing Last Request and Response</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.client.advanced.phtml">38.2. Zend_Http_Client - Advanced Usage</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.redirections">38.2.1. HTTP Redirections</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.cookies">38.2.2. Adding Cookies and Using Cookie Persistence</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.custom_headers">38.2.3. Setting Custom Request Headers</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.file_uploads">38.2.4. File Uploads</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.raw_post_data">38.2.5. Sending Raw POST Data</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.http_authentication">38.2.6. HTTP Authentication</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.multiple_requests">38.2.7. Sending Multiple Requests With the Same Client</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.streaming">38.2.8. Data Streaming</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.client.adapters.phtml">38.3. Zend_Http_Client - Connection Adapters</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.overview">38.3.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.socket">38.3.2. The Socket Adapter</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.socket.streamcontext">38.3.2.1. Customizing and accessing the Socket adapter stream context</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.proxy">38.3.3. The Proxy Adapter</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.curl">38.3.4. The cURL Adapter</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.test">38.3.5. The Test Adapter</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.extending">38.3.6. Creating your own connection adapters</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.cookies.phtml">38.4. Zend_Http_Cookie and Zend_Http_CookieJar</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.introduction">38.4.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookie.instantiating">38.4.2. Instantiating Zend_Http_Cookie Objects</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookie.accessors">38.4.3. Zend_Http_Cookie getter methods</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookie.matching">38.4.4. Zend_Http_Cookie: Matching against a scenario</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookiejar">38.4.5. The Zend_Http_CookieJar Class: Instantiation</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookiejar.adding_cookies">38.4.6. Adding Cookies to a Zend_Http_CookieJar object</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookiejar.getting_cookies">38.4.7. Retrieving Cookies From a Zend_Http_CookieJar object</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.response.phtml">38.5. Zend_Http_Response</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.response.phtml#zend.http.response.introduction">38.5.1. Introduction</a></span></dt>
<dt><span class="sect2"><a href="zend.http.response.phtml#zend.http.response.testers">38.5.2. Boolean Tester Methods</a></span></dt>
<dt><span class="sect2"><a href="zend.http.response.phtml#zend.http.response.acessors">38.5.3. Accessor Methods</a></span></dt>
<dt><span class="sect2"><a href="zend.http.response.phtml#zend.http.response.static_parsers">38.5.4. Static HTTP Response Parsers</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent.phtml">38.6. Zend_Http_UserAgent</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.intro">38.6.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.quick-start">38.6.2. Quick Start</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.options">38.6.3. Configuration Options</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.methods">38.6.4. Available Methods</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.examples">38.6.5. Examples</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-device.phtml">38.7. The UserAgent Device Interface</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.intro">38.7.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.quick-start">38.7.2. Quick Start</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.options">38.7.3. Configuration Options</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.methods">38.7.4. Available Methods</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.examples">38.7.5. Examples</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-features.phtml">38.8. The UserAgent Features Adapter</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-features.phtml#zend.http.user-agent-features.intro">38.8.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features.phtml#zend.http.user-agent-features.quick-start">38.8.2. Quick Start</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features.phtml#zend.http.user-agent-features.options">38.8.3. Configuration Options</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features.phtml#zend.http.user-agent-features.methods">38.8.4. Available Methods</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-features-browscap.phtml">38.9. The Browscap UserAgent Features Adapter</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-features-browscap.phtml#zend.http.user-agent-features-browscap.intro">38.9.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-browscap.phtml#zend.http.user-agent-features-browscap.quick-start">38.9.2. Quick Start</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-browscap.phtml#zend.http.user-agent-features-browscap.options">38.9.3. Configuration Options</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-browscap.phtml#zend.http.user-agent-features-browscap.methods">38.9.4. Available Methods</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-features-device-atlas.phtml">38.10. The DeviceAtlas UserAgent Features Adapter</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-features-device-atlas.phtml#zend.http.user-agent-features-device-atlas.intro">38.10.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-device-atlas.phtml#zend.http.user-agent-features-device-atlas.quick-start">38.10.2. Quick Start</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-device-atlas.phtml#zend.http.user-agent-features-device-atlas.options">38.10.3. Configuration Options</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-device-atlas.phtml#zend.http.user-agent-features-device-atlas.methods">38.10.4. Available Methods</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-features-tera-wurfl.phtml">38.11. The TeraWurfl UserAgent Features Adapter</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-features-tera-wurfl.phtml#zend.http.user-agent-features-tera-wurfl.intro">38.11.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-tera-wurfl.phtml#zend.http.user-agent-features-tera-wurfl.quick-start">38.11.2. Quick Start</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-tera-wurfl.phtml#zend.http.user-agent-features-tera-wurfl.options">38.11.3. Configuration Options</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-tera-wurfl.phtml#zend.http.user-agent-features-tera-wurfl.methods">38.11.4. Available Methods</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-storage.phtml">38.12. The UserAgent Storage Interface</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-storage.phtml#zend.http.user-agent-storage.intro">38.12.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage.phtml#zend.http.user-agent-storage.quick-start">38.12.2. Quick Start</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage.phtml#zend.http.user-agent-storage.options">38.12.3. Configuration Options</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage.phtml#zend.http.user-agent-storage.methods">38.12.4. Available Methods</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-storage-session.phtml">38.13. The Session UserAgent Storage Adapter</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-storage-session.phtml#zend.http.user-agent-storage-session.intro">38.13.1. Overview</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage-session.phtml#zend.http.user-agent-storage-session.quick-start">38.13.2. Quick Start</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage-session.phtml#zend.http.user-agent-storage-session.options">38.13.3. Configuration Options</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage-session.phtml#zend.http.user-agent-storage-session.methods">38.13.4. Available Methods</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.http.client"></a>38.1. Introduction</h2></div></div></div>
<p>
        <code class="classname">Zend_Http_Client</code> provides an easy interface for preforming Hyper-Text
        Transfer Protocol (HTTP) requests. <code class="classname">Zend_Http_Client</code> supports most
        simple features expected from an <acronym class="acronym">HTTP</acronym> client, as well as some more
        complex features such as <acronym class="acronym">HTTP</acronym> authentication and file uploads. Successful
        requests (and most unsuccessful ones too) return a <code class="classname">Zend_Http_Response</code>
        object, which provides access to the response's headers and body (see
        <a class="link" href="zend.http.response.phtml" title="38.5. Zend_Http_Response">this section</a>).
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.usage"></a>38.1.1. Using Zend_Http_Client</h3></div></div></div>
<p>
            The class constructor optionally accepts a URL as its first parameter
            (can be either a string or a <code class="classname">Zend_Uri_Http</code> object), and an array
            or <code class="classname">Zend_Config</code> object containing configuration options. Both can
            be left out, and set later using the setUri() and setConfig() methods.

            </p>
<div class="example">
<a name="zend.http.client.introduction.example-1"></a><p class="title"><b>Example 38.1. Instantiating a Zend_Http_Client Object</b></p>
<div class="example-contents"><pre class="programlisting">
$client = new Zend_Http_Client('http://example.org', array(
    'maxredirects' =&gt; 0,
    'timeout'      =&gt; 30));

// This is actually exactly the same:
$client = new Zend_Http_Client();
$client-&gt;setUri('http://example.org');
$client-&gt;setConfig(array(
    'maxredirects' =&gt; 0,
    'timeout'      =&gt; 30));

// You can also use a Zend_Config object to set the client's configuration
$config = new Zend_Config_Ini('httpclient.ini', 'secure');
$client-&gt;setConfig($config);
</pre></div>
</div>
<p><br class="example-break">

            </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Note</th>
</tr>
<tr><td align="left" valign="top"><p>
                    <code class="classname">Zend_Http_Client</code> uses
                    <code class="classname">Zend_Uri_Http</code> to validate URLs. This means
                    that some special characters like the pipe symbol ('|') or the
                    caret symbol ('^') will not be accepted in the URL by default.
                    This can be modified by setting the 'allow_unwise' option of
                    <code class="classname">Zend_Uri</code> to '<code class="constant">TRUE</code>'. See <a class="link" href="zend.uri.phtml#zend.uri.validation.allowunwise" title='75.1.4.1. Allowing "Unwise" characters in URIs'>this section</a> for more
                    information.
                </p></td></tr>
</table></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.configuration"></a>38.1.2. Configuration Parameters</h3></div></div></div>
<p>
            The constructor and setConfig() method accept an associative array
            of configuration parameters, or a <code class="classname">Zend_Config</code> object. Setting
            these parameters is optional, as they all have default values.

            </p>
<div class="table">
<a name="zend.http.client.configuration.table"></a><p class="title"><b>Table 38.1. Zend_Http_Client configuration parameters</b></p>
<div class="table-contents"><table class="table" summary="Zend_Http_Client configuration parameters" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Parameter</th>
<th>Description</th>
<th>Expected Values</th>
<th>Default Value</th>
</tr></thead>
<tbody>
<tr>
<td>maxredirects</td>
<td>Maximum number of redirections to follow (0 = none)</td>
<td>integer</td>
<td>5</td>
</tr>
<tr>
<td>strict</td>
<td>
                                Whether perform validation on header names. When set to
                                <code class="constant">FALSE</code>, validation functions will be skipped.
                                Usually this should not be changed
                            </td>
<td>boolean</td>
<td><code class="constant">TRUE</code></td>
</tr>
<tr>
<td>strictredirects</td>
<td>
                                Whether to strictly follow the <acronym class="acronym">RFC</acronym> when
                                redirecting (see <a class="link" href="zend.http.client.advanced.phtml#zend.http.client.redirections" title="38.2.1. HTTP Redirections">this section</a>)
                            </td>
<td>boolean</td>
<td><code class="constant">FALSE</code></td>
</tr>
<tr>
<td>useragent</td>
<td>User agent identifier string (sent in request headers)</td>
<td>string</td>
<td>'Zend_Http_Client'</td>
</tr>
<tr>
<td>timeout</td>
<td>Connection timeout (seconds)</td>
<td>integer</td>
<td>10</td>
</tr>
<tr>
<td>httpversion</td>
<td>HTTP protocol version (usually '1.1' or '1.0')</td>
<td>string</td>
<td>'1.1'</td>
</tr>
<tr>
<td>adapter</td>
<td>
                                Connection adapter class to use (see <a class="link" href="zend.http.client.adapters.phtml" title="38.3. Zend_Http_Client - Connection Adapters">this section</a>)
                            </td>
<td>mixed</td>
<td>'Zend_Http_Client_Adapter_Socket'</td>
</tr>
<tr>
<td>keepalive</td>
<td>
                                Whether to enable keep-alive connections with the server. Useful and
                                might improve performance if several consecutive requests to the
                                same server are performed.
                            </td>
<td>boolean</td>
<td><code class="constant">FALSE</code></td>
</tr>
<tr>
<td>storeresponse</td>
<td>
                                Whether to store last response for later retrieval with
                                <code class="methodname">getLastResponse()</code>. If set to
                                <code class="constant">FALSE</code>
                                <code class="methodname">getLastResponse()</code> will return
                                <code class="constant">NULL</code>.
                            </td>
<td>boolean</td>
<td><code class="constant">TRUE</code></td>
</tr>
<tr>
<td>encodecookies</td>
<td>
                                Whether to pass the cookie value through urlencode/urldecode.
                                Enabling this breaks support with some web servers.
                                Disabling this limits the range of values the cookies can contain.
                            </td>
<td>boolean</td>
<td><code class="constant">TRUE</code></td>
</tr>
</tbody>
</table></div>
</div>
<p><br class="table-break">
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.basic-requests"></a>38.1.3. Performing Basic HTTP Requests</h3></div></div></div>
<p>
            Performing simple <acronym class="acronym">HTTP</acronym> requests is very easily done using the
            request() method, and rarely needs more than three lines of code:

            </p>
<div class="example">
<a name="zend.http.client.basic-requests.example-1"></a><p class="title"><b>Example 38.2. Performing a Simple GET Request</b></p>
<div class="example-contents"><pre class="programlisting">
$client = new Zend_Http_Client('http://example.org');
$response = $client-&gt;request();
</pre></div>
</div>
<p><br class="example-break">

            The request() method takes one optional parameter - the request method.
            This can be either <span class="property">GET</span>, <span class="property">POST</span>,
            <span class="property">PUT</span>, <span class="property">HEAD</span>, <span class="property">DELETE</span>,
            <span class="property">TRACE</span>, <span class="property">OPTIONS</span> or <span class="property">CONNECT</span>
            as defined by the <acronym class="acronym">HTTP</acronym> protocol

            <a href="#ftn.id31191" class="footnote" name="id31191"><sup class="footnote">[6]</sup></a>.

            For convenience, these are all defined as class constants:
            Zend_Http_Client::GET, Zend_Http_Client::POST and so on.
        </p>
<p>
            If no method is specified, the method set by the last
            <code class="methodname">setMethod()</code> call is used. If
            <code class="methodname">setMethod()</code> was never called, the default request
            method is <code class="constant">GET</code> (see the above example).

            </p>
<div class="example">
<a name="zend.http.client.basic-requests.example-2"></a><p class="title"><b>Example 38.3. Using Request Methods Other Than GET</b></p>
<div class="example-contents"><pre class="programlisting">
// Preforming a POST request
$response = $client-&gt;request('POST');

// Yet another way of preforming a POST request
$client-&gt;setMethod(Zend_Http_Client::POST);
$response = $client-&gt;request();
</pre></div>
</div>
<p><br class="example-break">
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.parameters"></a>38.1.4. Adding GET and POST parameters </h3></div></div></div>
<p>
            Adding <code class="constant">GET</code> parameters to an <acronym class="acronym">HTTP</acronym> request is
            quite simple, and can be done either by specifying them as part of the URL, or by using
            the setParameterGet() method.
            This method takes the <code class="constant">GET</code> parameter's name as its first parameter,
            and the <code class="constant">GET</code> parameter's value as its second parameter.
            For convenience, the setParameterGet() method can also accept a
            single associative array of name =&gt; value <code class="constant">GET</code> variables - which may
            be more comfortable when several <code class="constant">GET</code> parameters need to be set.

            </p>
<div class="example">
<a name="zend.http.client.parameters.example-1"></a><p class="title"><b>Example 38.4. Setting GET Parameters</b></p>
<div class="example-contents"><pre class="programlisting">
// Setting a get parameter using the setParameterGet method
$client-&gt;setParameterGet('knight', 'lancelot');

// This is equivalent to setting such URL:
$client-&gt;setUri('http://example.com/index.php?knight=lancelot');

// Adding several parameters with one call
$client-&gt;setParameterGet(array(
    'first_name'  =&gt; 'Bender',
    'middle_name' =&gt; 'Bending'
    'made_in'     =&gt; 'Mexico',
));
</pre></div>
</div>
<p><br class="example-break">
        </p>
<p>
            While <code class="constant">GET</code> parameters can be sent with every request method, POST
            parameters are only sent in the body of POST requests. Adding POST
            parameters to a request is very similar to adding <code class="constant">GET</code> parameters,
            and can be done with the setParameterPost() method, which is
            similar to the setParameterGet() method in structure.

            </p>
<div class="example">
<a name="zend.http.client.parameters.example-2"></a><p class="title"><b>Example 38.5. Setting POST Parameters</b></p>
<div class="example-contents"><pre class="programlisting">
// Setting a POST parameter
$client-&gt;setParameterPost('language', 'fr');

// Setting several POST parameters, one of them with several values
$client-&gt;setParameterPost(array(
    'language'  =&gt; 'es',
    'country'   =&gt; 'ar',
    'selection' =&gt; array(45, 32, 80)
));
</pre></div>
</div>
<p><br class="example-break">

            Note that when sending POST requests, you can set both <code class="constant">GET</code> and
            POST parameters. On the other hand, while setting POST parameters
            for a non-POST request will not trigger and error, it is useless.
            Unless the request is a POST request, POST parameters are simply
            ignored.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.accessing_last"></a>38.1.5. Accessing Last Request and Response</h3></div></div></div>
<p>
            <code class="classname">Zend_Http_Client</code> provides methods of accessing the last request
            sent and last response received by the client object.
            <code class="classname">Zend_Http_Client-&gt;getLastRequest()</code> takes no parameters
            and returns the last <acronym class="acronym">HTTP</acronym> request sent by the client as a string.
            Similarly, <code class="classname">Zend_Http_Client-&gt;getLastResponse()</code> returns
            the last <acronym class="acronym">HTTP</acronym> response received by the client as a
            <a class="link" href="zend.http.response.phtml" title="38.5. Zend_Http_Response">Zend_Http_Response</a> object.
        </p>
</div>
</div>
<div class="footnotes">
<br><hr style="width:100; text-align:left;margin-left: 0">
<div id="ftn.id31191" class="footnote"><p><a href="#id31191" class="para"><sup class="para">[6] </sup></a>
                See RFC 2616 - <a class="ulink" href="http://www.w3.org/Protocols/rfc2616/rfc2616.html" target="_top">http://www.w3.org/Protocols/rfc2616/rfc2616.html</a>.
              </p></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.gdata.exception.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.http.client.advanced.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">37.11. Catching Gdata Exceptions </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 38.2. Zend_Http_Client - Advanced Usage</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
