<?php $title = '38.10. The DeviceAtlas UserAgent Features Adapter'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">38.10. The DeviceAtlas UserAgent Features Adapter</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.http.user-agent-features-browscap.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 38. Zend_Http</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.http.user-agent-features-tera-wurfl.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.http.user-agent-features-device-atlas"></a>38.10. The DeviceAtlas UserAgent Features Adapter</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features-device-atlas.intro"></a>38.10.1. Overview</h3></div></div></div>
<p>
            <a class="ulink" href="http://deviceatlas.com/" target="_top">DeviceAtlas</a> provides a comprehensive mobile
            device database, in editions ranging from free to enterprise level. The databases
            provided with all editions utilize the same API, which is shipped as part of the
            DeviceAtlas offering. This particular features adapter interacts with the DeviceAtlas
            API in order to return device capabilities.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features-device-atlas.quick-start"></a>38.10.2. Quick Start</h3></div></div></div>
<p>
            You will first need to download the DeviceAtlas PHP API, available via their <a class="ulink" href="http://deviceatlas.com/downloads" target="_top">downloads</a> page. Unpack this into your
            library, and make note of the directory in which it resides.
        </p>
<p>
            From there, you may optionally desire to download one of the DeviceAtlas databases; see
            their site for details. When you do, make sure you make note of where the data file
            resides.
        </p>
<p>
            Once you have this information, you may configure
            <code class="classname">Zend_Http_UserAgent</code> to utilize it. The easiest way is through
            your application configuration.
        </p>
<pre class="programlisting">
resources.useragent.deviceatlas.deviceatlas_lib_dir = APPLICATION_PATH "/../library/DeviceAtlas"
resources.useragent.deviceatlas.deviceatlas_data = APPLICATION_PATH "/../data/DeviceAtlas/json/DeviceAtlas.json
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features-device-atlas.options"></a>38.10.3. Configuration Options</h3></div></div></div>
<div class="variablelist">
<p class="title"><b>DeviceAtlas API Options</b></p>
<dl class="variablelist">
<dt><span class="term">deviceatlas.deviceatlas_lib_dir</span></dt>
<dd><p>
                        If using the DeviceAtlas API, use this key to specify in which directory the
                        library exists. If the <code class="classname">Mobi_Mtld_DA_Api</code> class is
                        autoloadable, you may omit this setting.
                    </p></dd>
<dt><span class="term">deviceatlas.deviceatlas_data</span></dt>
<dd><p>
                        If using the DeviceAtlas API, use this key to specify the location of the
                        data file you will use.
                    </p></dd>
</dl>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features-device-atlas.methods"></a>38.10.4. Available Methods</h3></div></div></div>
<div class="variablelist"><dl class="variablelist">
<dt>
<a name="zend.http.user-agent-features-device-atlas.methods.get-from-request"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getFromRequest</span>(<span class="methodparam">array $request, array $config</span>);</code>
                </span>
</dt>
<dd><p>
                        Decompose the request in order to return an array of device capabilities.
                    </p></dd>
</dl></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.http.user-agent-features-browscap.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.http.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.http.user-agent-features-tera-wurfl.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">38.9. The Browscap UserAgent Features Adapter </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 38.11. The TeraWurfl UserAgent Features Adapter</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
