<?php $title = 'Chapter 32. Zend_Exception'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 32. Zend_Exception</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.event-manager.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.exception.basic.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.exception"></a>Chapter 32. Zend_Exception</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.exception.phtml#zend.exception.using">32.1. Using Exceptions</a></span></dt>
<dt><span class="sect1"><a href="zend.exception.basic.phtml">32.2. Basic usage</a></span></dt>
<dt><span class="sect1"><a href="zend.exception.previous.phtml">32.3. Previous Exceptions</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.exception.using"></a>32.1. Using Exceptions</h2></div></div></div>
<p>
        <code class="classname">Zend_Exception</code> is simply the base class for all exceptions thrown
        within Zend Framework.
    </p>
<div class="example">
<a name="zend.exception.using.example"></a><p class="title"><b>Example 32.1. Catching an Exception</b></p>
<div class="example-contents">
<p>
            The following code listing demonstrates how to catch an exception thrown in a Zend
            Framework class:
        </p>
<pre class="programlisting">
try {
    // Calling Zend_Loader::loadClass() with a non-existant class will cause
    // an exception to be thrown in Zend_Loader:
    Zend_Loader::loadClass('nonexistantclass');
} catch (Zend_Exception $e) {
    echo "Caught exception: " . get_class($e) . "\n";
    echo "Message: " . $e-&gt;getMessage() . "\n";
    // Other code to recover from the error
}
</pre>
</div>
</div>
<br class="example-break"><p>
        <code class="classname">Zend_Exception</code> can be used as a catch-all exception class in a
        catch block to trap all exceptions thrown by Zend Framework classes. This can
        be useful when the program can not recover by catching a specific exception type.
    </p>
<p>
        The documentation for each Zend Framework
        component and class will contain specific information on which methods
        throw exceptions, the circumstances that cause an exception to be thrown,
        and the various exception types that may be thrown.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.event-manager.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.exception.basic.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Chapter 31. Zend_EventManager </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 32.2. Basic usage</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
