<?php $title = '61.2. Building Indexes'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">61.2. Building Indexes</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.search.lucene.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 61. Zend_Search_Lucene</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.search.lucene.searching.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.search.lucene.index-creation"></a>61.2. Building Indexes</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.creating"></a>61.2.1. Creating a New Index</h3></div></div></div>
<p>
            Index creation and updating capabilities are implemented within the
            <code class="classname">Zend_Search_Lucene</code> component, as well as the Java Lucene project.
            You can use either of these options to create indexes that
            <code class="classname">Zend_Search_Lucene</code> can search.
        </p>
<p>
            The <acronym class="acronym">PHP</acronym> code listing below provides an example of how to index a file
            using <code class="classname">Zend_Search_Lucene</code> indexing <acronym class="acronym">API</acronym>:
        </p>
<pre class="programlisting">
// Create index
$index = Zend_Search_Lucene::create('/data/my-index');

$doc = new Zend_Search_Lucene_Document();

// Store document URL to identify it in the search results
$doc-&gt;addField(Zend_Search_Lucene_Field::Text('url', $docUrl));

// Index document contents
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('contents', $docContent));

// Add document to the index
$index-&gt;addDocument($doc);
</pre>
<p>
            Newly added documents are immediately searchable in the index.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.updating"></a>61.2.2. Updating Index</h3></div></div></div>
<p>
            The same procedure is used to update an existing index. The only difference
            is that the open() method is called instead of the create() method:
        </p>
<pre class="programlisting">
// Open existing index
$index = Zend_Search_Lucene::open('/data/my-index');

$doc = new Zend_Search_Lucene_Document();
// Store document URL to identify it in search result.
$doc-&gt;addField(Zend_Search_Lucene_Field::Text('url', $docUrl));
// Index document content
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('contents',
                                                  $docContent));

// Add document to the index.
$index-&gt;addDocument($doc);
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.document-updating"></a>61.2.3. Updating Documents</h3></div></div></div>
<p>
            The Lucene index file format doesn't support document updating.
            Documents should be removed and re-added to the index to effectively update them.
        </p>
<p>
            <code class="methodname">Zend_Search_Lucene::delete()</code> method operates with an internal
            index document id. It can be retrieved from a query hit by 'id' property:
        </p>
<pre class="programlisting">
$removePath = ...;
$hits = $index-&gt;find('path:' . $removePath);
foreach ($hits as $hit) {
    $index-&gt;delete($hit-&gt;id);
}
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.counting"></a>61.2.4. Retrieving Index Size</h3></div></div></div>
<p>
            There are two methods to retrieve the size of an index in
            <code class="classname">Zend_Search_Lucene</code>.
        </p>
<p>
             <code class="methodname">Zend_Search_Lucene::maxDoc()</code> returns one greater than the
             largest possible document number. It's actually the overall number of the documents in
             the index including deleted documents, so it has a synonym:
             <code class="methodname">Zend_Search_Lucene::count()</code>.
        </p>
<p>
             <code class="methodname">Zend_Search_Lucene::numDocs()</code> returns the total number of
             non-deleted documents.
        </p>
<pre class="programlisting">
$indexSize = $index-&gt;count();
$documents = $index-&gt;numDocs();
</pre>
<p>
            <code class="methodname">Zend_Search_Lucene::isDeleted($id)</code> method may be used to check
            if a document is deleted.
        </p>
<pre class="programlisting">
for ($count = 0; $count &lt; $index-&gt;maxDoc(); $count++) {
    if ($index-&gt;isDeleted($count)) {
        echo "Document #$id is deleted.\n";
    }
}
</pre>
<p>
            Index optimization removes deleted documents and squeezes documents' IDs in to a smaller
            range. A document's internal id may therefore change during index optimization.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.optimization"></a>61.2.5. Index optimization</h3></div></div></div>
<p>
            A Lucene index consists of many segments. Each segment is a completely independent set
            of data.
        </p>
<p>
            Lucene index segment files can't be updated by design. A segment update needs full
            segment reorganization. See Lucene index file formats for details (<a class="ulink" href="http://lucene.apache.org/java/2_3_0/fileformats.html" target="_top">http://lucene.apache.org/java/2_3_0/fileformats.html</a>)

            <a href="#ftn.id46348" class="footnote" name="id46348"><sup class="footnote">[10]</sup></a>.

            New documents are added to the index by creating new segment.
        </p>
<p>
            Increasing number of segments reduces quality of the index, but index optimization
            restores it. Optimization essentially merges several segments into a new one. This
            process also doesn't update segments. It generates one new large segment and updates
            segment list ('segments' file).
        </p>
<p>
            Full index optimization can be trigger by calling the
            <code class="methodname">Zend_Search_Lucene::optimize()</code> method. It merges all index
            segments into one new segment:
        </p>
<pre class="programlisting">
// Open existing index
$index = Zend_Search_Lucene::open('/data/my-index');

// Optimize index.
$index-&gt;optimize();
</pre>
<p>
            Automatic index optimization is performed to keep indexes in a consistent state.
        </p>
<p>
            Automatic optimization is an iterative process managed by several index options. It
            merges very small segments into larger ones, then merges these larger segments into even
            larger segments and so on.
        </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.search.lucene.index-creation.optimization.maxbuffereddocs"></a>61.2.5.1. MaxBufferedDocs auto-optimization option</h4></div></div></div>
<p>
                <span class="emphasis"><em>MaxBufferedDocs</em></span> is a minimal number of documents required
                before the buffered in-memory documents are written into a new segment.
            </p>
<p>
                <span class="emphasis"><em>MaxBufferedDocs</em></span> can be retrieved or set by
                <code class="code">$index-&gt;getMaxBufferedDocs()</code> or
                <code class="code">$index-&gt;setMaxBufferedDocs($maxBufferedDocs)</code> calls.
            </p>
<p>
                Default value is 10.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.search.lucene.index-creation.optimization.maxmergedocs"></a>61.2.5.2. MaxMergeDocs auto-optimization option</h4></div></div></div>
<p>
                <span class="emphasis"><em>MaxMergeDocs</em></span> is a largest number of documents ever merged by
                addDocument(). Small values (e.g., less than 10.000) are best for interactive
                indexing, as this limits the length of pauses while indexing to a few seconds.
                Larger values are best for batched indexing and speedier searches.
            </p>
<p>
                <span class="emphasis"><em>MaxMergeDocs</em></span> can be retrieved or set by
                <code class="code">$index-&gt;getMaxMergeDocs()</code> or
                <code class="code">$index-&gt;setMaxMergeDocs($maxMergeDocs)</code> calls.
            </p>
<p>
                Default value is PHP_INT_MAX.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.search.lucene.index-creation.optimization.mergefactor"></a>61.2.5.3. MergeFactor auto-optimization option</h4></div></div></div>
<p>
                <span class="emphasis"><em>MergeFactor</em></span> determines how often segment indices are merged by
                addDocument(). With smaller values, less <acronym class="acronym">RAM</acronym> is used while
                indexing, and searches on unoptimized indices are faster, but indexing speed is
                slower. With larger values, more <acronym class="acronym">RAM</acronym> is used during indexing, and
                while searches on unoptimized indices are slower, indexing is faster. Thus larger
                values (&gt; 10) are best for batch index creation, and smaller values (&lt; 10) for
                indices that are interactively maintained.
            </p>
<p>
                <span class="emphasis"><em>MergeFactor</em></span> is a good estimation for average number of segments
                merged by one auto-optimization pass. Too large values produce large number of
                segments while they are not merged into new one. It may be a cause of "failed to
                open stream: Too many open files" error message. This limitation is system
                dependent.
            </p>
<p>
                <span class="emphasis"><em>MergeFactor</em></span> can be retrieved or set by
                <code class="code">$index-&gt;getMergeFactor()</code> or
                <code class="code">$index-&gt;setMergeFactor($mergeFactor)</code> calls.
            </p>
<p>
                Default value is 10.
            </p>
<p>
                Lucene Java and Luke (Lucene Index Toolbox - <a class="ulink" href="http://www.getopt.org/luke/" target="_top">http://www.getopt.org/luke/</a>) can also
                be used to optimize an index. Latest Luke release (v0.8) is based on Lucene v2.3 and
                compatible with current implementation of <code class="classname">Zend_Search_Lucene</code>
                component (Zend Framework 1.6). Earlier versions of
                <code class="classname">Zend_Search_Lucene</code> implementations need another versions of
                Java Lucene tools to be compatible:

                </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                            Zend Framework 1.5 - Java Lucene 2.1 (Luke tool v0.7.1 - <a class="ulink" href="http://www.getopt.org/luke/luke-0.7.1/" target="_top">http://www.getopt.org/luke/luke-0.7.1/</a>)
                        </p></li>
<li class="listitem"><p>
                            Zend Framework 1.0 - Java Lucene 1.4 - 2.1 (Luke tool v0.6 - <a class="ulink" href="http://www.getopt.org/luke/luke-0.6/" target="_top">http://www.getopt.org/luke/luke-0.6/</a>)
                        </p></li>
</ul></div>
<p>
            </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.permissions"></a>61.2.6. Permissions</h3></div></div></div>
<p>
            By default, index files are available for reading and writing by everyone.
        </p>
<p>
            It's possible to override this with the
            <code class="methodname">Zend_Search_Lucene_Storage_Directory_Filesystem::setDefaultFilePermissions()</code>
            method:
        </p>
<pre class="programlisting">
// Get current default file permissions
$currentPermissions =
    Zend_Search_Lucene_Storage_Directory_Filesystem::getDefaultFilePermissions();

// Give read-writing permissions only for current user and group
Zend_Search_Lucene_Storage_Directory_Filesystem::setDefaultFilePermissions(0660);
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.limitations"></a>61.2.7. Limitations</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.search.lucene.index-creation.limitations.index-size"></a>61.2.7.1. Index size</h4></div></div></div>
<p>
                Index size is limited by 2GB for 32-bit platforms.
            </p>
<p>
                Use 64-bit platforms for larger indices.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.search.lucene.index-creation.limitations.filesystems"></a>61.2.7.2. Supported Filesystems</h4></div></div></div>
<p>
                <code class="classname">Zend_Search_Lucene</code> uses <code class="methodname">flock()</code> to
                provide concurrent searching, index updating and optimization.
            </p>
<p>
                According to the <acronym class="acronym">PHP</acronym> <a class="ulink" href="http://www.php.net/manual/en/function.flock.php" target="_top">documentation</a>,
                "<code class="methodname">flock()</code> will not work on NFS and many other networked file
                systems".
            </p>
<p>
                Do not use networked file systems with <code class="classname">Zend_Search_Lucene</code>.
            </p>
</div>
</div>
<div class="footnotes">
<br><hr style="width:100; text-align:left;margin-left: 0">
<div id="ftn.id46348" class="footnote"><p><a href="#id46348" class="para"><sup class="para">[10] </sup></a>
                    The currently supported Lucene index file format is version 2.3 (starting from
                    Zend Framework 1.6).
                </p></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.search.lucene.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.search.lucene.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.search.lucene.searching.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Chapter 61. Zend_Search_Lucene </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 61.3. Searching an Index</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
