<?php $title = 'Chapter 77. Zend_Version'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Chapter 77. Zend_Version</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.validate.messages.phtml">Prev</a> </td>
<th width="60%" align="center">Part III. Zend Framework Reference</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.view.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.version"></a>Chapter 77. Zend_Version</h2></div></div></div>
<div class="toc">
<p><b>Table of Contents</b></p>
<dl class="toc"><dt><span class="sect1"><a href="zend.version.phtml#zend.version.reading">77.1. Getting the Zend Framework Version</a></span></dt></dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.version.reading"></a>77.1. Getting the Zend Framework Version</h2></div></div></div>
<p>
        <code class="classname">Zend_Version</code> provides a class constant
        <code class="constant">Zend_Version::VERSION</code> that contains a string
        identifying the version number of your Zend Framework installation.
        <code class="constant">Zend_Version::VERSION</code> might contain "1.7.4", for example.
    </p>
<p>
        The static method <code class="methodname">Zend_Version::compareVersion($version)</code>
        is based on the <acronym class="acronym">PHP</acronym> function <a class="ulink" href="http://php.net/version_compare" target="_top"><code class="methodname">version_compare()</code></a>.
        This method returns -1 if the specified version
        is older than the installed Zend Framework version, 0 if they are the same
        and +1 if the specified version is newer than the
        version of the Zend Framework installation.
    </p>
<div class="example">
<a name="zend.version.reading.example"></a><p class="title"><b>Example 77.1. Example of the compareVersion() Method</b></p>
<div class="example-contents"><pre class="programlisting">
// returns -1, 0 or 1
$cmp = Zend_Version::compareVersion('2.0.0');
</pre></div>
</div>
<br class="example-break"><p>
        The static method <code class="methodname">Zend_Version::getLatest()</code> provides the version
        number of the last stable release available for download on the site
        <a class="ulink" href="http://framework.zend.com/download/latest" target="_top">Zend Framework</a>.
    </p>
<div class="example">
<a name="zend.version.latest.example"></a><p class="title"><b>Example 77.2. Example of the getLatest() Method</b></p>
<div class="example-contents"><pre class="programlisting">
// returns 1.11.0 (or a later version)
echo Zend_Version::getLatest();
</pre></div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.validate.messages.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.view.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">76.5. Validation Messages </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> Chapter 78. Zend_View</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
