<?php $title = '64.35. Zend_Service_WindowsAzure_Diagnostics_Manager'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.35. Zend_Service_WindowsAzure_Diagnostics_Manager</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.windowsazure.storage.blob.phtml">Prev</a> </td>
<th width="60%" align="center">Chapter 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.windowsazure.storage.queue.phtml">Next</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.windowsazure.diagnostics.manager"></a>64.35. Zend_Service_WindowsAzure_Diagnostics_Manager</h2></div></div></div>
<p>
        Blob Storage stores sets of binary data. Blob storage offers the following three
        Windows Azure Diagnostics enables you to collect diagnostic data from a service
        running in Windows Azure. It can be used for tasks like debugging and
        troubleshooting, measuring performance, monitoring resource usage, traffic
        analysis, capacity planning, and auditing. Once collected, diagnostic data can be
        transferred to a Windows Azure storage account for persistence. Transfers can
        either be scheduled or on-demand.
    </p>
<p>
        You can configure Windows Azure Diagnostics from code running within a role. You
        can also configure it remotely from an application running outside of the Windows
        Azure; for example, you can manage Windows Azure Diagnostics from a custom
        dashboard application running locally. By managing Windows Azure Diagnostics
        remotely, you can start your service with an initial diagnostic configuration,
        and then tweak that configuration from code running outside of your service,
        without having to upgrade your service.
    </p>
<p>
        More information on which logs, performance counters, crash dumps, ...
        can be monitored can be found on the <a class="ulink" href="http://msdn.microsoft.com/en-us/library/ee758705(v=MSDN.10).aspx" target="_top">
        corresponding MSDN web page</a>.
    </p>
<p>
        Note: Diagnostics are configured on a per-role basis. This means that each
        role should be configured separately. Specifying diagnostics instructions
        for one role instance does not imply this configuration is loaded on other
        role instances.
    </p>
<p>
        Note: Diagnostics are configured on a per-role basis. This means that each
        The Diagnostics API in the Windows Azure SDK for PHP can only be used when
        the DiagnosticsMonitor has been started during role startup. Currently,
        this is only supported when an application is packaged with the Windows
        Azure Command-line Tools for PHP Developers.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.windowsazure.diagnostics.manager.api"></a>64.35.1. API Examples</h3></div></div></div>
<p>
            This topic lists some examples of using the
            <code class="classname">Zend_Service_WindowsAzure_Diagnostics_Manager</code> class.  Other features are
            available in the download package, as well as a detailed API documentation of those
            features.
        </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-exists"></a>64.35.1.1. Checking if a diagnostics configuration for the current role instance exists</h4></div></div></div>
<p>
                Using the following code, you can check if a diagnostics configuration for the
                current role instance exists.
            </p>
<div class="example">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-exists.example"></a><p class="title"><b>Example 64.162. Checking if a diagnostics configuration for the current role instance exists</b></p>
<div class="example-contents"><pre class="programlisting">
/** Zend_Service_WindowsAzure_Storage_Blob */
require_once 'Zend/Service/WindowsAzure/Storage/Blob.php';

/** Zend_Service_WindowsAzure_Diagnostics_Manager */
require_once 'Zend/Service/WindowsAzure/Diagnostics/Manager.php';

$storageClient = new Zend_Service_WindowsAzure_Storage_Blob();
$manager = new Zend_Service_WindowsAzure_Diagnostics_Manager($storageClient);

$configurationExists = $manager-&gt;configurationForCurrentRoleInstanceExists();

echo 'The configuration ' . ($configurationExists ? 'exists' : 'does not exist';
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-load"></a>64.35.1.2. Loading the current role instance diagnostics configuration</h4></div></div></div>
<p>
                Using the following code, you can load the current role instance diagnostics
                configuration.
            </p>
<div class="example">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-load.example"></a><p class="title"><b>Example 64.163. Loading the current role instance diagnostics configuration</b></p>
<div class="example-contents"><pre class="programlisting">
/** Zend_Service_WindowsAzure_Storage_Blob */
require_once 'Zend/Service/WindowsAzure/Storage/Blob.php';

/** Zend_Service_WindowsAzure_Diagnostics_Manager */
require_once 'Zend/Service/WindowsAzure/Diagnostics/Manager.php';

$storageClient = new Zend_Service_WindowsAzure_Storage_Blob();
$manager = new Zend_Service_WindowsAzure_Diagnostics_Manager($storageClient);

$configuration = $manager-&gt;getConfigurationForCurrentRoleInstance();
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-store"></a>64.35.1.3. Storing the current role instance diagnostics configuration</h4></div></div></div>
<p>
                Using the following code, you can store the current role instance diagnostics
                configuration.
            </p>
<div class="example">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-store.example"></a><p class="title"><b>Example 64.164. Storing the current role instance diagnostics configuration</b></p>
<div class="example-contents"><pre class="programlisting">
/** Zend_Service_WindowsAzure_Storage_Blob */
require_once 'Zend/Service/WindowsAzure/Storage/Blob.php';

/** Zend_Service_WindowsAzure_Diagnostics_Manager */
require_once 'Zend/Service/WindowsAzure/Diagnostics/Manager.php';

$storageClient = new Zend_Service_WindowsAzure_Storage_Blob();
$manager = new Zend_Service_WindowsAzure_Diagnostics_Manager($storageClient);

$configuration = // ...;
$manager-&gt;setConfigurationForCurrentRoleInstance($configuration);
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-perf"></a>64.35.1.4. Subscribing to a performance counter</h4></div></div></div>
<p>
                Using the following code, you can subscribe to a performance counter.
            </p>
<div class="example">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-perf.example"></a><p class="title"><b>Example 64.165. Subscribing to a performance counter</b></p>
<div class="example-contents"><pre class="programlisting">
/** Zend_Service_WindowsAzure_Storage_Blob */
require_once 'Zend/Service/WindowsAzure/Storage/Blob.php';

/** Zend_Service_WindowsAzure_Diagnostics_Manager */
require_once 'Zend/Service/WindowsAzure/Diagnostics/Manager.php';

$storageClient = new Zend_Service_WindowsAzure_Storage_Blob();
$manager = new Zend_Service_WindowsAzure_Diagnostics_Manager($storageClient);

$configuration = $manager-&gt;getConfigurationForCurrentRoleInstance();

// Subscribe to \Processor(*)\% Processor Time
$configuration-&gt;DataSources-&gt;PerformanceCounters-&gt;addSubscription('\Processor(*)\% Processor Time', 1);

$manager-&gt;setConfigurationForCurrentRoleInstance($configuration);
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-roleid"></a>64.35.1.5. Getting the current role instance id</h4></div></div></div>
<p>
                The current role instance id is defined in the server variable
                RdRoleId. It will only be available when the application is run in
                Development Fabric or Windows Azure Fabric.
            </p>
<div class="example">
<a name="zend.service.windowsazure.diagnostics.manager.api.config-roleid.example"></a><p class="title"><b>Example 64.166. Getting the current role instance id</b></p>
<div class="example-contents"><pre class="programlisting">
echo 'The role instance id is ' . $_SERVER['RdRoleId'];
</pre></div>
</div>
<br class="example-break">
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.windowsazure.storage.blob.phtml">Prev</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Up</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.windowsazure.storage.queue.phtml">Next</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.34. Zend_Service_WindowsAzure_Storage_Blob </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Home</a></td>
<td width="40%" align="right" valign="top"> 64.36. Zend_Service_WindowsAzure_Storage_Queue</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
