<?php $title = 'Apéndice C. Estándar de codificación de Zend Framework para PHP'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Apéndice C. Estándar de codificación de Zend Framework para PHP</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="migration.06.phtml">Anterior</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> <a accesskey="n" href="coding-standard.php-file-formatting.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="appendix">
<div class="titlepage"><div><div><h1 class="title">
<a name="coding-standard"></a>Apéndice C. Estándar de codificación de Zend Framework para PHP</h1></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="coding-standard.phtml#coding-standard.overview">C.1. Resumen</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="coding-standard.phtml#coding-standard.overview.scope">C.1.1. Ámbito</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.phtml#coding-standard.overview.goals">C.1.2. Objetivos</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="coding-standard.php-file-formatting.phtml">C.2. Formato de archivos PHP</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.general">C.2.1. General</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.indentation">C.2.2. Sangría</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.max-line-length">C.2.3. Longitud máxima de línea</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.php-file-formatting.phtml#coding-standard.php-file-formatting.line-termination">C.2.4. Terminación de línea</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="coding-standard.naming-conventions.phtml">C.3. Convenciones de nomenclatura</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.classes">C.3.1. Clases</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.abstracts">C.3.2. Clases abstractas</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.interfaces">C.3.3. Interfaces</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.filenames">C.3.4. Nombres de archivo</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.functions-and-methods">C.3.5. Funciones y métodos</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.variables">C.3.6. Variables</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.naming-conventions.phtml#coding-standard.naming-conventions.constants">C.3.7. Constantes</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="coding-standard.coding-style.phtml">C.4. Estilo de codificación</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.php-code-demarcation">C.4.1. Delimitación de código PHP</a></span></dt>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings">C.4.2. Cadenas</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings.literals">C.4.2.1. Cadenas literales</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings.literals-containing-apostrophes">C.4.2.2. Cadenas literales que contienen apóstrofos</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings.variable-substitution">C.4.2.3. Sustitución de variables</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.strings.string-concatenation">C.4.2.4. Concatenación de cadenas</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.arrays">C.4.3. Arreglos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.arrays.numerically-indexed">C.4.3.1. Arreglos indexados numéricamente</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.arrays.associative">C.4.3.2. Arreglos asociativos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.classes">C.4.4. Clases</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.classes.declaration">C.4.4.1. Declaración de clases</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.classes.member-variables">C.4.4.2. Variables miembro de clase</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.functions-and-methods">C.4.5. Funciones y métodos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.functions-and-methods.declaration">C.4.5.1. Declaración de funciones y métodos</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.functions-and-methods.usage">C.4.5.2. Uso de funciones y métodos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.control-statements">C.4.6. Sentencias de control</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standard.coding-style.control-statements.if-else-elseif">C.4.6.1. If/Else/Elseif</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.coding-style.control-statements.switch">C.4.6.2. Switch</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation">C.4.7. Documentación en línea</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation.documentation-format">C.4.7.1. Formato de documentación</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation.files">C.4.7.2. Archivos</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation.classes">C.4.7.3. Clases</a></span></dt>
<dt><span class="sect3"><a href="coding-standard.coding-style.phtml#coding-standards.inline-documentation.functions">C.4.7.4. Funciones</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="coding-standard.overview"></a>C.1. Resumen</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="coding-standard.overview.scope"></a>C.1.1. Ámbito</h3></div></div></div>
<p>
                Este documento ofrece pautas para el formato y la documentación de código a
                las personas y equipos que colaboran con Zend Framework. Muchos desarrolladores que usan Zend
                Framework también han encontrado útiles estos estándares de codificación porque el estilo de su código
                permanece coherente con todo el código de Zend Framework. También cabe destacar que
                requiere un esfuerzo considerable especificar completamente los estándares de codificación.
            </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                    A veces los desarrolladores consideran más importante el establecimiento de un estándar
                    que lo que ese estándar sugiere realmente al nivel de detalle más profundo del
                    diseño. Las pautas de los estándares de codificación de Zend Framework recogen prácticas
                    que han funcionado bien en el proyecto Zend Framework. Puede modificar estos
                    estándares o usarlos tal cual de acuerdo con los términos de nuestra <a class="ulink" href="http://framework.zend.com/license" target="_top">licencia</a>.
                </p></td></tr>
</table></div>
<p>
                Los temas cubiertos en los estándares de codificación de Zend Framework incluyen:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Formato de archivos <acronym class="acronym">PHP</acronym></p></li>
<li class="listitem"><p>Convenciones de nomenclatura</p></li>
<li class="listitem"><p>Estilo de codificación</p></li>
<li class="listitem"><p>Documentación en línea</p></li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="coding-standard.overview.goals"></a>C.1.2. Objetivos</h3></div></div></div>
<p>
                Los estándares de codificación son importantes en cualquier proyecto de desarrollo, pero son particularmente
                importantes cuando muchos desarrolladores trabajan en el mismo proyecto. Los estándares de codificación
                ayudan a garantizar que el código sea de alta calidad, tenga menos errores y pueda mantenerse
                fácilmente.
            </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="migration.06.phtml">Anterior</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> <a accesskey="n" href="coding-standard.php-file-formatting.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">B.11. Zend Framework 0.6 </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> C.2. Formato de archivos PHP</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
