<?php $title = 'Apéndice D. Estándar de documentación de Zend Framework'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Apéndice D. Estándar de documentación de Zend Framework</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="coding-standard.coding-style.phtml">Anterior</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> <a accesskey="n" href="doc-standard.file-formatting.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="appendix">
<div class="titlepage"><div><div><h1 class="title">
<a name="doc-standard"></a>Apéndice D. Estándar de documentación de Zend Framework</h1></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="doc-standard.phtml#doc-standard.overview">D.1. Resumen</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="doc-standard.phtml#doc-standard.overview.scope">D.1.1. Alcance</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="doc-standard.file-formatting.phtml">D.2. Formato de los archivos de documentación</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.xml-tags">D.2.1. Etiquetas XML</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.max-line-length">D.2.2. Longitud máxima de línea</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.indentation">D.2.3. Sangría</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.line-termination">D.2.4. Terminación de línea</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.empty-tags">D.2.5. Etiquetas vacías</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.whitespace">D.2.6. Uso de los espacios en blanco dentro de los documentos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.whitespace.trailing">D.2.6.1. Espacios en blanco dentro de las etiquetas</a></span></dt>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.whitespace.multiple-line-breaks">D.2.6.2. Múltiples saltos de línea</a></span></dt>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.whitespace.tag-separation">D.2.6.3. Separación entre etiquetas</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.program-listing">D.2.7. Listados de programa</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.inline-tags">D.2.8. Notas sobre etiquetas en línea específicas</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.inline-tags.classname">D.2.8.1. classname</a></span></dt>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.inline-tags.varname">D.2.8.2. varname</a></span></dt>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.inline-tags.methodname">D.2.8.3. methodname</a></span></dt>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.inline-tags.constant">D.2.8.4. constant</a></span></dt>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.inline-tags.filename">D.2.8.5. filename</a></span></dt>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.inline-tags.command">D.2.8.6. command</a></span></dt>
<dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.inline-tags.code">D.2.8.7. code</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.block-tags">D.2.9. Notas sobre etiquetas de bloque específicas</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="doc-standard.file-formatting.phtml#doc-standard.file-formatting.block-tags.title">D.2.9.1. title</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="doc-standard.recommendations.phtml">D.3. Recomendaciones</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="doc-standard.recommendations.phtml#doc-standard.recommendations.editors">D.3.1. Utilice editores sin autoformato</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.recommendations.phtml#doc-standard.recommendations.images">D.3.2. Utilice imágenes</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.recommendations.phtml#doc-standard.recommendations.examples">D.3.3. Utilice ejemplos de casos de uso</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.recommendations.phtml#doc-standard.recommendations.phpdoc">D.3.4. Evite replicar el contenido de phpdoc</a></span></dt>
<dt><span class="sect2"><a href="doc-standard.recommendations.phtml#doc-standard.recommendations.links">D.3.5. Utilice enlaces</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="doc-standard.overview"></a>D.1. Resumen</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="doc-standard.overview.scope"></a>D.1.1. Alcance</h3></div></div></div>
<p>
                Este documento proporciona directrices para la creación de la
                documentación de usuario final que se encuentra dentro de Zend
                Framework. Está pensado como una guía para los colaboradores de Zend
                Framework, quienes deben escribir documentación como parte de sus
                contribuciones a los componentes, así como para los traductores de la
                documentación. Los estándares aquí contenidos tienen como objetivo
                facilitar la traducción de la documentación, minimizar las
                diferencias visuales y de estilo entre los distintos archivos de
                documentación, y facilitar la búsqueda de cambios en la documentación
                con herramientas de <span class="command"><strong>diff</strong></span>.
            </p>
<p>
                Puede adoptar y/o modificar estos estándares de acuerdo con los
                términos de nuestra <a class="ulink" href="http://framework.zend.com/license" target="_top">licencia</a>.
            </p>
<p>
                Los temas cubiertos en los estándares de documentación de Zend
                Framework incluyen el formato de los archivos de documentación y
                recomendaciones para la calidad de la documentación.
            </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="coding-standard.coding-style.phtml">Anterior</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> <a accesskey="n" href="doc-standard.file-formatting.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">C.4. Estilo de código </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> D.2. Formato de los archivos de documentación</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
