<?php $title = 'Capítulo 2. Instalación'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 2. Instalación</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="introduction.overview.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte I. Introducción a Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="introduction.installation"></a>Capítulo 2. Instalación</h2></div></div></div>
<p>
        Consulte el <a class="link" href="requirements.phtml" title="Appendix A. Zend Framework Requirements">apéndice de requisitos</a> para obtener una lista detallada de los
        requisitos de Zend Framework.
    </p>
<p>
        Instalar Zend Framework es extremadamente sencillo. Una vez que haya descargado y extraído el
        framework, debe añadir la carpeta <code class="filename">/library</code> de la distribución al
        principio de su include path. Es posible que también desee mover la carpeta library
        a otra ubicación de su sistema de archivos, posiblemente compartida.
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <a class="ulink" href="http://framework.zend.com/download/latest" target="_top">Descargue la última
                versión estable.</a> Esta versión, disponible tanto en formato
                <code class="filename">.zip</code> como <code class="filename">.tar.gz</code>, es una
                buena opción para quienes son nuevos en Zend Framework.
            </p></li>
<li class="listitem"><p>
                <a class="ulink" href="http://framework.zend.com/download/snapshot" target="_top">Descargue la última
                instantánea nocturna.</a> Para quienes se atrevan con lo más reciente, las
                instantáneas nocturnas representan el último avance del desarrollo de Zend Framework.
                Las instantáneas se distribuyen con documentación solo en inglés o en todos los
                idiomas disponibles. Si prevé trabajar con los últimos desarrollos de Zend Framework,
                considere usar un cliente de Subversion (<acronym class="acronym">SVN</acronym>).
            </p></li>
<li class="listitem">
<p>
                Usando un cliente <a class="ulink" href="http://subversion.tigris.org" target="_top">Subversion</a>
                (<acronym class="acronym">SVN</acronym>). Zend Framework es software de código abierto, y el
                repositorio de Subversion usado para su desarrollo está disponible públicamente. Considere
                usar <acronym class="acronym">SVN</acronym> para obtener Zend Framework si ya usa
                <acronym class="acronym">SVN</acronym> para el desarrollo de sus aplicaciones, si desea
                contribuir al framework, o si necesita actualizar su versión del framework
                con más frecuencia de la que ocurren las publicaciones.
            </p>
<p>
                <a class="ulink" href="http://svnbook.red-bean.com/nightly/en/svn.ref.svn.c.export.html" target="_top">
                Exportar</a> es útil si desea obtener una revisión concreta del framework
                sin los directorios <code class="filename">.svn</code> que se crean en una copia de trabajo.
            </p>
<p>
                <a class="ulink" href="http://svnbook.red-bean.com/nightly/en/svn.ref.svn.c.checkout.html" target="_top">
                Obtener una copia de trabajo</a> si desea contribuir a Zend Framework, una
                copia de trabajo puede actualizarse en cualquier momento con
                <a class="ulink" href="http://svnbook.red-bean.com/nightly/en/svn.ref.svn.c.update.html" target="_top">
                svn update</a> y los cambios pueden confirmarse en nuestro repositorio
                <acronym class="acronym">SVN</acronym> con el comando
                <a class="ulink" href="http://svnbook.red-bean.com/nightly/en/svn.ref.svn.c.commit.html" target="_top">
                svn commit</a>.
            </p>
<p>
                Una
                <a class="ulink" href="http://svnbook.red-bean.com/nightly/en/svn.advanced.externals.html" target="_top">
                definición externals</a> resulta bastante conveniente para los desarrolladores que ya usan
                <acronym class="acronym">SVN</acronym> para gestionar las copias de trabajo de sus aplicaciones.
            </p>
<p>
                La <acronym class="acronym">URL</acronym> del tronco (trunk) del repositorio <acronym class="acronym">SVN</acronym>
                de Zend Framework es: <a class="ulink" href="http://framework.zend.com/svn/framework/standard/trunk" target="_top">
                    http://framework.zend.com/svn/framework/standard/trunk</a>
            </p>
</li>
</ul></div>
<p>
        Una vez que disponga de una copia de Zend Framework, su aplicación necesita poder
        acceder a las clases del framework. Aunque hay
        <a class="ulink" href="http://www.php.net/manual/en/configuration.changes.php" target="_top">
        varias formas de lograrlo</a>, su
        <a class="ulink" href="http://www.php.net/manual/en/ini.core.php#ini.include-path" target="_top">include_path</a>
        de <acronym class="acronym">PHP</acronym>
        debe contener la ruta a la biblioteca de Zend Framework.
    </p>
<p>
        Zend ofrece un <a class="ulink" href="http://framework.zend.com/docs/quickstart" target="_top">QuickStart</a>
        para que empiece a funcionar lo antes posible. Es una excelente manera de comenzar a
        aprender sobre el framework con énfasis en ejemplos del mundo real sobre los que puede
        construir.
    </p>
<p>
        Dado que los componentes de Zend Framework están débilmente acoplados, puede usar una combinación
        algo particular de ellos en sus propias aplicaciones. Los siguientes capítulos ofrecen una
        referencia exhaustiva de Zend Framework componente por componente.
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="introduction.overview.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="introduction.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 1. Resumen </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Parte II. Aprendiendo Zend Framework</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
