<?php $title = 'Capítulo 1. Resumen'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Encabezado de navegación">
<tr><th colspan="3" align="center">Capítulo 1. Resumen</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="introduction.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte I. Introducción a Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="introduction.installation.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="introduction.overview"></a>Capítulo 1. Resumen</h2></div></div></div>
<p>
        Zend Framework es un framework de código abierto para desarrollar aplicaciones web y servicios
        con <acronym class="acronym">PHP</acronym> 5. Zend Framework está implementado utilizando código 100%
        orientado a objetos. La estructura de componentes de Zend Framework es un tanto singular; cada
        componente se ha diseñado con pocas dependencias respecto de otros componentes. Esta arquitectura
        débilmente acoplada permite a los desarrolladores utilizar los componentes de forma individual.
        A menudo llamamos a esto un diseño de «uso a voluntad» (<span lang="en"><i>use-at-will</i></span>).
    </p>
<p>
        Aunque pueden utilizarse por separado, los componentes de Zend Framework incluidos en la biblioteca
        estándar conforman, al combinarse, un framework de aplicaciones web potente y extensible. Zend Framework
        ofrece una implementación <acronym class="acronym">MVC</acronym> robusta y de alto rendimiento, una
        abstracción de base de datos sencilla de usar y un componente de formularios que implementa la
        representación, validación y filtrado de formularios <acronym class="acronym">HTML</acronym>, de modo
        que los desarrolladores pueden consolidar todas estas operaciones mediante una única interfaz orientada
        a objetos y fácil de usar. Otros componentes, como
        <code class="classname">Zend_Auth</code> y <code class="classname">Zend_Acl</code>, proporcionan
        autenticación y autorización de usuarios frente a todos los almacenes de credenciales habituales. Otros
        implementan bibliotecas cliente para acceder de forma sencilla a los servicios web más populares
        disponibles. Sean cuales sean las necesidades de su aplicación, es probable que encuentre un componente
        de Zend Framework que pueda utilizarse para reducir drásticamente el tiempo de desarrollo sobre una
        base minuciosamente probada.
    </p>
<p>
        El principal patrocinador del proyecto «Zend Framework» es <a class="ulink" href="http://www.zend.com" target="_top">
        Zend Technologies</a>, pero muchas empresas han contribuido con componentes o funcionalidades
        importantes al framework. Empresas como Google, Microsoft y StrikeIron se han asociado con Zend para
        proporcionar interfaces a servicios web y otras tecnologías que desean poner a disposición de los
        desarrolladores de Zend Framework.
    </p>
<p>
        Zend Framework no podría ofrecer ni dar soporte a todas estas funcionalidades sin la ayuda de la
        vibrante comunidad de Zend Framework. Los miembros de la comunidad, incluidos los colaboradores, se
        ponen a disposición de todos en <a class="ulink" href="http://framework.zend.com/archives" target="_top">listas
            de correo</a>, <a class="ulink" href="http://www.zftalk.com" target="_top">canales de IRC</a> y otros
        foros. Sea cual sea la pregunta que tenga sobre Zend Framework, la comunidad siempre está disponible
        para responderla.
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Pie de navegación">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="introduction.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="introduction.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="introduction.installation.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Parte I. Introducción a Zend Framework </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 2. Instalación</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
