<?php $title = '3.6. ¡Felicidades!'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">3.6. ¡Felicidades!</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.quickstart.create-form.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 3. Inicio rápido de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.autoloading.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.quickstart.conclusion"></a>3.6. ¡Felicidades!</h2></div></div></div>
<p>
        Ahora ha creado una aplicación muy sencilla utilizando algunos de los componentes de Zend
        Framework más utilizados. Zend Framework pone a su disposición numerosos componentes que
        cubren la mayoría de los requisitos habituales en las aplicaciones web, incluyendo servicios
        web, búsqueda, lectura y escritura de <acronym class="acronym">PDF</acronym>, autenticación, autorización y
        mucho más. La <a class="link" href="reference.phtml" title="Part III. Zend Framework Reference">Guía de Referencia</a> es un lugar excelente para
        conocer más sobre los componentes que ha utilizado en este Inicio rápido, así como otros
        componentes. ¡Esperamos que Zend Framework le resulte útil y - lo que es más importante -
        divertido!
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.quickstart.create-form.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.quickstart.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.autoloading.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">3.5. Crear un formulario </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 4. Autocarga en Zend Framework</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
