<?php $title = '4.5. Conclusión'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">4.5. Conclusión</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.autoloading.resources.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 4. Autocarga en Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.plugins.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.autoloading.conclusion"></a>4.5. Conclusión</h2></div></div></div>
<p>
        Zend Framework fomenta el uso de la autocarga, e incluso la inicializa por defecto en
        <code class="classname">Zend_Application</code>. Con suerte, este tutorial le proporciona la
        información necesaria para aprovechar al máximo <code class="classname">Zend_Loader_Autoloader</code>,
        así como para ampliar sus capacidades adjuntando autocargadores personalizados o
        autocargadores de recursos.
    </p>
<p>
        Para más información sobre su uso, lea las páginas del manual de <a class="link" href="zend.loader.autoloader.phtml" title="42.2. The Autoloader">Zend_Loader_Autoloader</a> y <a class="link" href="zend.loader.autoloader-resource.phtml" title="42.3. Resource Autoloaders">Zend_Loader_Autoloader_Resource</a>.
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.autoloading.resources.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.autoloading.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.plugins.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">4.4. Autocarga de recursos </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 5. Plugins en Zend Framework</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
