<?php $title = '5.2. Uso de plugins'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">5.2. Uso de plugins</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.plugins.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 5. Plugins en Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.plugins.conclusion.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.plugins.usage"></a>5.2. Uso de plugins</h2></div></div></div>
<p>
        Los componentes que hacen uso de plugins normalmente usan
        <code class="classname">Zend_Loader_PluginLoader</code> para realizar su trabajo. Esta clase le permite
        registrar plugins especificando una o más "rutas de prefijo". El componente entonces llamará al
        método <code class="methodname">load()</code> del PluginLoader, pasándole el nombre corto del plugin.
        El PluginLoader consultará entonces cada ruta de prefijo para ver si existe una clase que
        coincida con ese nombre corto. Las rutas de prefijo se buscan en orden LIFO (último en entrar,
        primero en salir), de modo que coincidirá primero con las rutas de prefijo registradas en último
        lugar -- lo que le permite sobrescribir plugins existentes.
    </p>
<p>
        Algunos ejemplos aclararán todo esto.
    </p>
<div class="example">
<a name="learning.plugins.usage.basic"></a><p class="title"><b>Ejemplo 5.1. Ejemplo básico de plugin: añadir una única ruta de prefijo</b></p>
<div class="example-contents">
<p>
            En este ejemplo, asumiremos que se han escrito algunos validadores y se han colocado en el
            directorio <code class="filename">foo/plugins/validators/</code>, y que todas estas clases comparten
            el prefijo de clase "Foo_Validate_"; estos dos datos forman nuestra "ruta de prefijo".
            Además, supongamos que tenemos dos validadores, uno llamado "Even" (que asegura que un
            número a validar sea par), y otro llamado "Dozens" (que asegura que el número sea un
            múltiplo de 12). El árbol podría verse así:
        </p>
<pre class="programlisting">
foo/
|-- plugins/
|   |-- validators/
|   |   |-- Even.php
|   |   |-- Dozens.php
</pre>
<p>
            Ahora, informaremos a una instancia de <code class="classname">Zend_Form_Element</code> de esta
            ruta de prefijo. El método <code class="methodname">addPrefixPath()</code> de
            <code class="classname">Zend_Form_Element</code> espera un tercer argumento que indica
            el tipo de plugin para el cual se está registrando la ruta; en este caso, es un
            plugin "validate".
        </p>
<pre class="programlisting">
$element-&gt;addPrefixPath('Foo_Validate', 'foo/plugins/validators/', 'validate');
</pre>
<p>
            Ahora podemos simplemente indicarle al elemento el nombre corto de los validadores que
            queremos usar. En el siguiente ejemplo, usamos una combinación de validadores estándar
            ("NotEmpty", "Int") y validadores personalizados ("Even", "Dozens"):
        </p>
<pre class="programlisting">
$element-&gt;addValidator('NotEmpty')
        -&gt;addValidator('Int')
        -&gt;addValidator('Even')
        -&gt;addValidator('Dozens');
</pre>
<p>
            Cuando el elemento necesite validar, solicitará entonces la clase del plugin al
            PluginLoader. Los dos primeros validadores se resolverán en
            <code class="classname">Zend_Validate_NotEmpty</code> y
            <code class="classname">Zend_Validate_Int</code>, respectivamente; los siguientes dos se resolverán
            en <code class="classname">Foo_Validate_Even</code> y <code class="classname">Foo_Validate_Dozens</code>,
            respectivamente.
        </p>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: What happens if a plugin is not found?">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">¿Qué sucede si no se encuentra un plugin?</th>
</tr>
<tr><td align="left" valign="top">
<p>
            ¿Qué sucede si se solicita un plugin, pero el PluginLoader no puede encontrar una clase
            que coincida con él? Por ejemplo, en el ejemplo anterior, si registráramos el plugin "Bar" con
            el elemento, ¿qué sucedería?
        </p>
<p>
            El cargador de plugins recorrerá cada ruta de prefijo, comprobando si se encuentra un
            archivo que coincida con el nombre del plugin en esa ruta. Si no se encuentra el archivo, pasa
            entonces a la siguiente ruta de prefijo.
        </p>
<p>
            Una vez que se ha agotado la pila de rutas de prefijo, si no se ha encontrado ningún archivo
            coincidente, lanzará una <code class="exceptionname">Zend_Loader_PluginLoader_Exception</code>.
        </p>
</td></tr>
</table></div>
<div class="example">
<a name="learning.plugins.usage.override"></a><p class="title"><b>Ejemplo 5.2. Uso intermedio de plugins: sobrescribir plugins existentes</b></p>
<div class="example-contents">
<p>
            Una fortaleza del PluginLoader es que su uso de una pila LIFO le permite sobrescribir
            plugins existentes creando sus propias versiones localmente con una ruta de prefijo diferente,
            y registrando esa ruta de prefijo más adelante en la pila.
        </p>
<p>
            Por ejemplo, consideremos <code class="classname">Zend_View_Helper_FormButton</code> (los
            helpers de vista son una forma de plugin). Este helper de vista acepta tres argumentos, un
            nombre de elemento (también usado como identificador DOM del elemento), un valor (usado
            como etiqueta del botón), y un array opcional de atributos. El helper entonces genera
            marcado <acronym class="acronym">HTML</acronym> para un elemento de entrada de formulario.
        </p>
<p>
            Supongamos que quiere que el helper genere en su lugar un verdadero elemento
            <code class="constant">button</code> de <acronym class="acronym">HTML</acronym>; no quiere que el helper
            genere un identificador DOM, sino que use el valor para un selector de clase CSS; y que
            no tiene interés en manejar atributos arbitrarios. Podría lograr esto de un par de
            maneras. En ambos casos, crearía su propia clase de helper de vista que implemente el
            comportamiento que desea; la diferencia está en cómo la nombraría e invocaría.
        </p>
<p>
            Nuestro primer ejemplo será nombrar el elemento con un nombre único:
            <code class="classname">Foo_View_Helper_CssButton</code>, lo que implica el nombre de plugin
            "CssButton". Si bien este es ciertamente un enfoque viable, plantea varios problemas: si
            ya ha usado el helper de vista Button en su código, ahora tendría que refactorizar;
            alternativamente, si otro desarrollador comienza a escribir código para su aplicación, podría
            usar inadvertidamente el helper de vista Button en lugar de su nuevo helper de vista.
        </p>
<p>
            Así que el mejor ejemplo es usar el nombre de plugin "Button", lo que nos da el nombre de
            clase <code class="classname">Foo_View_Helper_Button</code>. Entonces registramos la ruta de
            prefijo con la vista:
        </p>
<pre class="programlisting">
// Zend_View::addHelperPath() utilizes the PluginLoader; however, it inverts
// the arguments, as it provides a default value of "Zend_View_Helper" for the
// plugin prefix.
//
// The below assumes your class is in the directory 'foo/view/helpers/'.
$view-&gt;addHelperPath('foo/view/helpers', 'Foo_View_Helper');
</pre>
<p>
            Una vez hecho esto, ¡en cualquier lugar donde ahora use el helper "Button" se delegará a su
            clase personalizada <code class="classname">Foo_View_Helper_Button</code>!
        </p>
</div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.plugins.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.plugins.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.plugins.conclusion.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 5. Plugins en Zend Framework </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 5.3. Conclusión</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
