<?php $title = 'Capítulo 7. Primeros pasos con los marcadores de posición de Zend_View'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 7. Primeros pasos con los marcadores de posición de Zend_View</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.layout.conclusions.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte II. Aprendiendo Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.view.placeholders.basics.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="learning.view.placeholders"></a>Capítulo 7. Primeros pasos con los marcadores de posición de Zend_View</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="learning.view.placeholders.phtml#learning.view.placeholders.intro">7.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.view.placeholders.basics.phtml">7.2. Uso básico de los marcadores de posición</a></span></dt>
<dt><span class="sect1"><a href="learning.view.placeholders.standard.phtml">7.3. Marcadores de posición estándar</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.view.placeholders.standard.phtml#learning.view.placeholders.standard.doctype">7.3.1. Configurando el DocType</a></span></dt>
<dt><span class="sect2"><a href="learning.view.placeholders.standard.phtml#learning.view.placeholders.standard.head-title">7.3.2. Especificando el título de la página</a></span></dt>
<dt><span class="sect2"><a href="learning.view.placeholders.standard.phtml#learning.view.placeholders.standard.head-link">7.3.3. Especificando hojas de estilo con HeadLink</a></span></dt>
<dt><span class="sect2"><a href="learning.view.placeholders.standard.phtml#learning.view.placeholders.standard.head-script">7.3.4. Agregando scripts usando HeadScript</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.view.placeholders.conclusion.phtml">7.4. Marcadores de posición de vista: Conclusión</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.view.placeholders.intro"></a>7.1. Introducción</h2></div></div></div>
<p>
        En <a class="link" href="learning.layout.phtml" title="Chapter 6. Getting Started with Zend_Layout">el capítulo anterior</a>, analizamos principalmente el
        patrón Two Step View, que le permite incrustar vistas individuales de la aplicación dentro de un
        diseño (layout) a nivel de todo el sitio. Sin embargo, al final de ese capítulo, discutimos algunas limitaciones:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                ¿Cómo se modifica el título de la página?
            </p></li>
<li class="listitem"><p>
                ¿Cómo se inyectarían scripts u hojas de estilo condicionales en el diseño de todo el sitio?
            </p></li>
<li class="listitem"><p>
                ¿Cómo se crearía y renderizaría una barra lateral opcional? ¿Qué pasaría si hubiera contenido
                incondicional y otro contenido condicional para la barra lateral?
            </p></li>
</ul></div>
<p>
        Estas preguntas se abordan en el patrón de diseño <a class="ulink" href="http://www.oracle.com/technetwork/java/compositeview-137722.html" target="_top">Composite
        View</a>. Un enfoque de ese patrón es proporcionar "pistas" o contenido
        al diseño de todo el sitio. En Zend Framework, esto se logra mediante ayudantes de vista especializados
        llamados "marcadores de posición" (placeholders). Los marcadores de posición le permiten agregar contenido, y luego renderizar
        ese contenido agregado en otro lugar.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.layout.conclusions.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.view.placeholders.basics.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">6.3. Zend_Layout: Conclusiones </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 7.2. Uso básico de los marcadores de posición</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
