<?php $title = 'Capítulo 8. Entendiendo y usando los decoradores de Zend Form'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 8. Entendiendo y usando los decoradores de Zend Form</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.view.placeholders.conclusion.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte II. Aprendiendo Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.form.decorators.simplest.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="learning.form.decorators"></a>Capítulo 8. Entendiendo y usando los decoradores de Zend Form</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="learning.form.decorators.phtml#learning.form.decorators.intro">8.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.simplest.phtml">8.2. Fundamentos de los decoradores</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.form.decorators.simplest.phtml#learning.form.decorators.simplest.decorator-overview">8.2.1. Resumen del patrón decorador</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.simplest.phtml#learning.form.decorators.simplest.first-decorator">8.2.2. Creando su primer decorador</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.form.decorators.layering.phtml">8.3. Superponiendo decoradores</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.individual.phtml">8.4. Renderizando decoradores individuales</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.composite.phtml">8.5. Creando y renderizando elementos compuestos</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.element">8.5.1. El elemento</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.decorator">8.5.2. El decorador</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.conclusion">8.5.3. Conclusión</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.form.decorators.conclusion.phtml">8.6. Conclusión</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.form.decorators.intro"></a>8.1. Introducción</h2></div></div></div>
<p>
        <a class="link" href="zend.form.phtml" title="Chapter 36. Zend_Form">Zend_Form</a> utiliza el patrón <span class="emphasis"><em>decorador</em></span>
        para renderizar elementos y formularios. A diferencia del clásico <a class="ulink" href="http://en.wikipedia.org/wiki/Decorator_pattern" target="_top">patrón decorador</a>, en
        el que se pasa un objeto a una clase envolvente, los decoradores en <code class="classname">Zend_Form</code>
        implementan un <a class="ulink" href="http://en.wikipedia.org/wiki/Strategy_pattern" target="_top">patrón
            estrategia</a>, y utilizan los metadatos contenidos en un elemento o formulario para
        crear una representación de este
    </p>
<p>
        Sin embargo, no deje que la terminología lo asuste; en esencia, los decoradores en
        <code class="classname">Zend_Form</code> no son terriblemente difíciles, y los mini-tutoriales que
        siguen deberían ayudarle en el camino. Le guiarán a través de los fundamentos de la decoración,
        hasta llegar a la creación de decoradores para elementos compuestos.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.view.placeholders.conclusion.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.form.decorators.simplest.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">7.4. Marcadores de posición de vista: Conclusión </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 8.2. Fundamentos de los decoradores</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
