<?php $title = 'Capítulo 4. Autocarga en Zend Framework'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 4. Autocarga en Zend Framework</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.quickstart.conclusion.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte II. Aprendiendo Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.autoloading.design.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="learning.autoloading"></a>Capítulo 4. Autocarga en Zend Framework</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="learning.autoloading.phtml#learning.autoloading.intro">4.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.autoloading.design.phtml">4.2. Objetivos y diseño</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.autoloading.design.phtml#learning.autoloading.design.naming">4.2.1. Convenciones de nomenclatura de clases</a></span></dt>
<dt><span class="sect2"><a href="learning.autoloading.design.phtml#learning.autoloading.design.autoloader">4.2.2. Convenciones y diseño del autoloader</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.autoloading.usage.phtml">4.3. Uso básico del autoloader</a></span></dt>
<dt><span class="sect1"><a href="learning.autoloading.resources.phtml">4.4. Autocarga de recursos</a></span></dt>
<dt><span class="sect1"><a href="learning.autoloading.conclusion.phtml">4.5. Conclusión</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.autoloading.intro"></a>4.1. Introducción</h2></div></div></div>
<p>
        La autocarga es un mecanismo que elimina la necesidad de incluir manualmente las dependencias en
        su código <acronym class="acronym">PHP</acronym>. Según <a class="ulink" href="http://php.net/autoload" target="_top">el manual de autoload de PHP</a>,
        una vez que se ha definido un autoloader, este "se llama automáticamente
        cuando se intenta usar una clase o interfaz que aún no ha sido definida."
    </p>
<p>
        Al usar la autocarga, no necesita preocuparse por <span class="emphasis"><em>dónde</em></span> existe una clase
        en su proyecto. Con autoloaders bien definidos, no necesita preocuparse por dónde se
        encuentra un archivo de clase en relación con el archivo de clase actual; simplemente usa la clase, y el
        autoloader realizará la búsqueda del archivo.
    </p>
<p>
        Además, la autocarga, dado que difiere la carga hasta el último momento posible y garantiza
        que una coincidencia solo tenga que ocurrir una vez, puede suponer una enorme mejora de rendimiento,
        en particular si se toma el tiempo de eliminar las llamadas a <code class="methodname">require_once()</code> antes de
        pasar a producción.
    </p>
<p>
        Zend Framework fomenta el uso de la autocarga y proporciona varias herramientas para
        la autocarga tanto del código de la biblioteca como del código de la aplicación. Este tutorial cubre estas
        herramientas, así como la forma de usarlas de manera efectiva.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.quickstart.conclusion.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.autoloading.design.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">3.6. ¡Felicidades! </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 4.2. Objetivos y diseño</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
