<?php $title = 'Capítulo 3. Inicio rápido de Zend Framework'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 3. Inicio rápido de Zend Framework</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte II. Aprendiendo Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.quickstart.create-project.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="learning.quickstart"></a>Capítulo 3. Inicio rápido de Zend Framework</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="learning.quickstart.phtml#learning.quickstart.intro">3.1. Introducción a Zend Framework y MVC</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.quickstart.phtml#learning.quickstart.intro.zf">3.1.1. Zend Framework</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.phtml#learning.quickstart.intro.mvc">3.1.2. Modelo-Vista-Controlador</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.quickstart.create-project.phtml">3.2. Cree su proyecto</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.install-zf">3.2.1. Instale Zend Framework</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.create-project">3.2.2. Cree su proyecto</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.bootstrap">3.2.3. El bootstrap</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.configuration">3.2.4. Configuración</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.action-controllers">3.2.5. Controladores de acciones</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.views">3.2.6. Vistas</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.vhost">3.2.7. Cree un host virtual</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.checkpoint">3.2.8. Punto de control</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.quickstart.create-layout.phtml">3.3. Cree un diseño (layout)</a></span></dt>
<dt><span class="sect1"><a href="learning.quickstart.create-model.phtml">3.4. Cree un modelo y una tabla de base de datos</a></span></dt>
<dt><span class="sect1"><a href="learning.quickstart.create-form.phtml">3.5. Cree un formulario</a></span></dt>
<dt><span class="sect1"><a href="learning.quickstart.conclusion.phtml">3.6. ¡Felicidades!</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.quickstart.intro"></a>3.1. Introducción a Zend Framework y MVC</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="learning.quickstart.intro.zf"></a>3.1.1. Zend Framework</h3></div></div></div>
<p>
            Zend Framework es un framework de aplicaciones web orientado a objetos y de código abierto para
            <acronym class="acronym">PHP</acronym> 5. A menudo se denomina a Zend Framework "biblioteca de componentes", porque
            cuenta con muchos componentes débilmente acoplados que puede usar de forma más o menos independiente. Pero
            Zend Framework también proporciona una implementación avanzada de Modelo-Vista-Controlador (<acronym class="acronym">MVC</acronym>)
            que puede usarse para establecer una estructura básica para sus aplicaciones de Zend Framework.
            Este inicio rápido le presentará algunos de los componentes de Zend Framework más utilizados,
            incluyendo <code class="classname">Zend_Controller</code>, <code class="classname">Zend_Layout</code>,
            <code class="classname">Zend_Config</code>, <code class="classname">Zend_Db</code>,
            <code class="classname">Zend_Db_Table</code>, <code class="classname">Zend_Registry</code>, junto
            con algunos helpers de vista.
        </p>
<p>
            Usando estos componentes, construiremos una sencilla aplicación de libro de visitas basada en base de
            datos en cuestión de minutos. El código fuente completo de esta aplicación está disponible en los
            siguientes archivos:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <a class="ulink" href="http://framework.zend.com/demos/ZendFrameworkQuickstart.zip" target="_top">zip</a>
                </p></li>
<li class="listitem"><p>
                    <a class="ulink" href="http://framework.zend.com/demos/ZendFrameworkQuickstart.tar.gz" target="_top">tar.gz</a>
                </p></li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="learning.quickstart.intro.mvc"></a>3.1.2. Modelo-Vista-Controlador</h3></div></div></div>
<p>
            Entonces, ¿qué es exactamente ese patrón <acronym class="acronym">MVC</acronym> del que todo el mundo habla, y
            por qué debería importarle? <acronym class="acronym">MVC</acronym> es mucho más que un simple acrónimo de tres
            letras (<acronym class="acronym">TLA</acronym>, por sus siglas en inglés) que puede sacar a relucir cuando quiera sonar
            inteligente;
            se ha convertido en una especie de estándar en el diseño de las aplicaciones web modernas. Y por
            buenas razones. La mayor parte del código de las aplicaciones web pertenece a una de las siguientes tres
            categorías: presentación, lógica de negocio y acceso a datos. El patrón <acronym class="acronym">MVC</acronym>
            modela bien esta separación de responsabilidades. El resultado final es que el código de
            presentación puede consolidarse en una parte de la aplicación, la lógica de negocio en otra
            y el código de acceso a datos en otra más. Muchos desarrolladores han considerado
            esta separación bien definida indispensable para mantener su código organizado, especialmente
            cuando más de un desarrollador trabaja en la misma aplicación.
        </p>
<div class="note"><table border="0" summary="Note: More Information">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Más información</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Vamos a desglosar el patrón y a examinar cada una de sus partes:
            </p>
<p>
                <img src="figures/learning.quickstart.intro.mvc.png" align="middle">
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <span class="emphasis"><em>Modelo</em></span>: es la parte de su
                        aplicación que define su funcionalidad básica tras un conjunto de
                        abstracciones. Las rutinas de acceso a datos y parte de la lógica de negocio pueden definirse en
                        el modelo.
                    </p></li>
<li class="listitem"><p>
                        <span class="emphasis"><em>Vista</em></span>: las vistas definen exactamente lo que se
                        presenta al usuario. Normalmente los controladores pasan datos a cada vista para que los presente
                        en algún formato. Las vistas también suelen recopilar datos del usuario. Aquí es
                        donde es probable que encuentre marcado <acronym class="acronym">HTML</acronym> en sus
                        aplicaciones <acronym class="acronym">MVC</acronym>.
                    </p></li>
<li class="listitem"><p>
                        <span class="emphasis"><em>Controlador</em></span>: los controladores unen todo el
                        patrón. Manipulan los modelos, deciden qué vista mostrar en función de
                        la solicitud del usuario y otros factores, transmiten los datos que cada vista
                        necesitará, o transfieren el control a otro controlador por completo. La mayoría de los
                        expertos en <acronym class="acronym">MVC</acronym> recomiendan <a class="ulink" href="http://weblog.jamisbuck.org/2006/10/18/skinny-controller-fat-model" target="_top">mantener
                        los controladores lo más ligeros posible</a>.
                    </p></li>
</ul></div>
<p>
                Por supuesto, hay <a class="ulink" href="http://ootips.org/mvc-pattern.html" target="_top">más que
                    decir</a> sobre este patrón fundamental, pero esto debería darle suficientes
            conocimientos previos para entender la aplicación de libro de visitas que construiremos.
            </p>
</td></tr>
</table></div>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.quickstart.create-project.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Parte II. Aprendiendo Zend Framework </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 3.2. Cree su proyecto</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
