<?php $title = 'Parte II. Aprendiendo Zend Framework'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Parte II. Aprendiendo Zend Framework</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="introduction.installation.phtml">Anterior</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> <a accesskey="n" href="learning.quickstart.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="part">
<div class="titlepage"><div><div><h1 class="title">
<a name="learning"></a>Parte II. Aprendiendo Zend Framework</h1></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="chapter"><a href="learning.quickstart.phtml">3. Inicio rápido de Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.quickstart.phtml#learning.quickstart.intro">3.1. Introducción a Zend Framework y MVC</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.quickstart.phtml#learning.quickstart.intro.zf">3.1.1. Zend Framework</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.phtml#learning.quickstart.intro.mvc">3.1.2. Modelo-Vista-Controlador</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.quickstart.create-project.phtml">3.2. Cree su proyecto</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.install-zf">3.2.1. Instalar Zend Framework</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.create-project">3.2.2. Cree su proyecto</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.bootstrap">3.2.3. El Bootstrap</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.configuration">3.2.4. Configuración</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.action-controllers">3.2.5. Controladores de acción</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.views">3.2.6. Vistas</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.vhost">3.2.7. Crear un host virtual</a></span></dt>
<dt><span class="sect2"><a href="learning.quickstart.create-project.phtml#learning.quickstart.create-project.checkpoint">3.2.8. Punto de control</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.quickstart.create-layout.phtml">3.3. Cree un layout</a></span></dt>
<dt><span class="sect1"><a href="learning.quickstart.create-model.phtml">3.4. Cree un modelo y una tabla de base de datos</a></span></dt>
<dt><span class="sect1"><a href="learning.quickstart.create-form.phtml">3.5. Cree un formulario</a></span></dt>
<dt><span class="sect1"><a href="learning.quickstart.conclusion.phtml">3.6. ¡Felicidades!</a></span></dt>
</dl></dd>
<dt><span class="chapter"><a href="learning.autoloading.phtml">4. Autocarga en Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.autoloading.phtml#learning.autoloading.intro">4.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.autoloading.design.phtml">4.2. Objetivos y diseño</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.autoloading.design.phtml#learning.autoloading.design.naming">4.2.1. Convenciones de nomenclatura de clases</a></span></dt>
<dt><span class="sect2"><a href="learning.autoloading.design.phtml#learning.autoloading.design.autoloader">4.2.2. Convenciones y diseño del Autoloader</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.autoloading.usage.phtml">4.3. Uso básico del Autoloader</a></span></dt>
<dt><span class="sect1"><a href="learning.autoloading.resources.phtml">4.4. Autocarga de recursos</a></span></dt>
<dt><span class="sect1"><a href="learning.autoloading.conclusion.phtml">4.5. Conclusión</a></span></dt>
</dl></dd>
<dt><span class="chapter"><a href="learning.plugins.phtml">5. Plugins en Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.plugins.phtml#learning.plugins.intro">5.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.plugins.usage.phtml">5.2. Uso de plugins</a></span></dt>
<dt><span class="sect1"><a href="learning.plugins.conclusion.phtml">5.3. Conclusión</a></span></dt>
</dl></dd>
<dt><span class="chapter"><a href="learning.layout.phtml">6. Primeros pasos con Zend_Layout</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.layout.phtml#learning.layout.intro">6.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.layout.usage.phtml">6.2. Uso de Zend_Layout</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.layout.usage.phtml#learning.layout.usage.configuration">6.2.1. Configuración del layout</a></span></dt>
<dt><span class="sect2"><a href="learning.layout.usage.phtml#learning.layout.usage.layout-script">6.2.2. Crear un script de layout</a></span></dt>
<dt><span class="sect2"><a href="learning.layout.usage.phtml#learning.layout.usage.access">6.2.3. Acceso al objeto layout</a></span></dt>
<dt><span class="sect2"><a href="learning.layout.usage.phtml#learning.layout.usage.other-operations">6.2.4. Otras operaciones</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.layout.conclusions.phtml">6.3. Zend_Layout: conclusiones</a></span></dt>
</dl></dd>
<dt><span class="chapter"><a href="learning.view.placeholders.phtml">7. Primeros pasos con los Placeholders de Zend_View</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.view.placeholders.phtml#learning.view.placeholders.intro">7.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.view.placeholders.basics.phtml">7.2. Uso básico de Placeholder</a></span></dt>
<dt><span class="sect1"><a href="learning.view.placeholders.standard.phtml">7.3. Placeholders estándar</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.view.placeholders.standard.phtml#learning.view.placeholders.standard.doctype">7.3.1. Establecer el DocType</a></span></dt>
<dt><span class="sect2"><a href="learning.view.placeholders.standard.phtml#learning.view.placeholders.standard.head-title">7.3.2. Especificar el título de página</a></span></dt>
<dt><span class="sect2"><a href="learning.view.placeholders.standard.phtml#learning.view.placeholders.standard.head-link">7.3.3. Especificar hojas de estilo con HeadLink</a></span></dt>
<dt><span class="sect2"><a href="learning.view.placeholders.standard.phtml#learning.view.placeholders.standard.head-script">7.3.4. Agregar scripts usando HeadScript</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.view.placeholders.conclusion.phtml">7.4. Placeholders de vista: conclusión</a></span></dt>
</dl></dd>
<dt><span class="chapter"><a href="learning.form.decorators.phtml">8. Comprender y usar los decoradores de Zend Form</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.form.decorators.phtml#learning.form.decorators.intro">8.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.simplest.phtml">8.2. Fundamentos de los decoradores</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.form.decorators.simplest.phtml#learning.form.decorators.simplest.decorator-overview">8.2.1. Resumen del patrón Decorator</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.simplest.phtml#learning.form.decorators.simplest.first-decorator">8.2.2. Creación de su primer decorador</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.form.decorators.layering.phtml">8.3. Superposición de decoradores</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.individual.phtml">8.4. Renderizado de decoradores individuales</a></span></dt>
<dt><span class="sect1"><a href="learning.form.decorators.composite.phtml">8.5. Creación y renderizado de elementos compuestos</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.element">8.5.1. El elemento</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.decorator">8.5.2. El decorador</a></span></dt>
<dt><span class="sect2"><a href="learning.form.decorators.composite.phtml#learning.form.decorators.composite.conclusion">8.5.3. Conclusión</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.form.decorators.conclusion.phtml">8.6. Conclusión</a></span></dt>
</dl></dd>
<dt><span class="chapter"><a href="learning.multiuser.phtml">9. Primeros pasos con Zend_Session, Zend_Auth y Zend_Acl</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.multiuser.phtml#learning.multiuser.intro">9.1. Creación de aplicaciones multiusuario con Zend Framework</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="learning.multiuser.phtml#learning.multiuser.intro.zf">9.1.1. Zend Framework</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="learning.multiuser.sessions.phtml">9.2. Gestión de sesiones de usuario en ZF</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.multiuser.sessions.phtml#learning.multiuser.sessions.intro">9.2.1. Introducción a las sesiones</a></span></dt>
<dt><span class="sect2"><a href="learning.multiuser.sessions.phtml#learning.multiuser.sessions.basic-usage">9.2.2. Uso básico de Zend_Session</a></span></dt>
<dt><span class="sect2"><a href="learning.multiuser.sessions.phtml#learning.multiuser.sessions.advanced-usage">9.2.3. Uso avanzado de Zend_Session</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.multiuser.authentication.phtml">9.3. Autenticación de usuarios en Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.multiuser.authentication.phtml#learning.multiuser.authentication.intro">9.3.1. Introducción a la autenticación</a></span></dt>
<dt><span class="sect2"><a href="learning.multiuser.authentication.phtml#learning.multiuser.authentication.basic-usage">9.3.2. Uso básico de Zend_Auth</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="learning.multiuser.authorization.phtml">9.4. Construcción de un sistema de autorización en Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="learning.multiuser.authorization.phtml#learning.multiuser.authorization.intro">9.4.1. Introducción a la autorización</a></span></dt>
<dt><span class="sect2"><a href="learning.multiuser.authorization.phtml#learning.multiuser.authorization.basic-usage">9.4.2. Uso básico de Zend_Acl</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="chapter"><a href="learning.lucene.phtml">10. Primeros pasos con Zend_Search_Lucene</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.lucene.phtml#learning.lucene.intro">10.1. Introducción a Zend_Search_Lucene</a></span></dt>
<dt><span class="sect1"><a href="learning.lucene.index-structure.phtml">10.2. Estructura del índice Lucene</a></span></dt>
<dt><span class="sect1"><a href="learning.lucene.index-opening.phtml">10.3. Apertura y creación de índices</a></span></dt>
<dt><span class="sect1"><a href="learning.lucene.indexing.phtml">10.4. Indexación</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="learning.lucene.indexing.phtml#learning.lucene.indexing.policy">10.4.1. Política de indexación</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="learning.lucene.searching.phtml">10.5. Búsqueda</a></span></dt>
<dt><span class="sect1"><a href="learning.lucene.queries.phtml">10.6. Consultas admitidas</a></span></dt>
<dt><span class="sect1"><a href="learning.lucene.pagination.phtml">10.7. Paginación de resultados de búsqueda</a></span></dt>
</dl></dd>
<dt><span class="chapter"><a href="learning.paginator.phtml">11. Primeros pasos con Zend_Paginator</a></span></dt>
<dd><dl>
<dt><span class="sect1"><a href="learning.paginator.phtml#learning.paginator.intro">11.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="learning.paginator.simple.phtml">11.2. Ejemplos simples</a></span></dt>
<dt><span class="sect1"><a href="learning.paginator.control.phtml">11.3. Control de paginación y ScrollingStyles</a></span></dt>
<dt><span class="sect1"><a href="learning.paginator.together.phtml">11.4. Poniéndolo todo junto</a></span></dt>
</dl></dd>
</dl>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="introduction.installation.phtml">Anterior</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> <a accesskey="n" href="learning.quickstart.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 2. Instalación </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 3. Inicio rápido de Zend Framework</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
