<?php $title = '7.4. Placeholders de vista: conclusión'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">7.4. Placeholders de vista: conclusión</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="learning.view.placeholders.standard.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 7. Primeros pasos con los placeholders de Zend_View</th>
<td width="20%" align="right"> <a accesskey="n" href="learning.form.decorators.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="learning.view.placeholders.conclusion"></a>7.4. Placeholders de vista: conclusión</h2></div></div></div>
<p>
        Los placeholders de vista son un método simple y potente para crear diseños ricos para su
        aplicación. Puede usar una variedad de placeholders estándar, como los tratados
        (<code class="methodname">doctype()</code>, <code class="methodname">headTitle()</code>,
        <code class="methodname">headLink()</code> y <code class="methodname">headScript()</code>), o usar
        el helper genérico <code class="methodname">placeholder()</code> para agregar contenido y renderizarlo
        de forma personalizada. Experimente con la funcionalidad que exponen, y visite las secciones
        correspondientes de la guía de referencia para descubrir las funcionalidades adicionales que ofrecen -- y
        cómo puede aprovechar esas funcionalidades para crear contenido rico para sus lectores.
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="learning.view.placeholders.standard.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="learning.view.placeholders.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="learning.form.decorators.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">7.3. Placeholders estándar </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 8. Comprender y usar los decoradores de Zend Form</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
