<?php $title = 'Apéndice B. Notas de migración de Zend Framework'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Apéndice B. Notas de migración de Zend Framework</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="requirements.phtml">Anterior</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> <a accesskey="n" href="migration.110.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="appendix">
<div class="titlepage"><div><div><h1 class="title">
<a name="migration"></a>Apéndice B. Notas de migración de Zend Framework</h1></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="migration.phtml#migration.112">B.1. Zend Framework 1.12</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.phtml#migration.12.zend.view.helper.navigation">B.1.1. Zend_View_Helper_Navigation</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="migration.110.phtml">B.2. Zend Framework 1.10</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.controller.front">B.2.1. Zend_Controller_Front</a></span></dt>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.feed.reader">B.2.2. Zend_Feed_Reader</a></span></dt>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.file.transfer">B.2.3. Zend_File_Transfer</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.file.transfer.files">B.2.3.1. Cambio de seguridad</a></span></dt>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.file.transfer.count">B.2.3.2. Validación de conteo</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.filter.html-entities">B.2.4. Zend_Filter_HtmlEntities</a></span></dt>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.filter.strip-tags">B.2.5. Zend_Filter_StripTags</a></span></dt>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.translate">B.2.6. Zend_Translate</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.translate.xliff">B.2.6.1. Adaptador Xliff</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.110.phtml#migration.110.zend.validate">B.2.7. Zend_Validate</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.validate.selfwritten">B.2.7.1. Validadores escritos por el usuario</a></span></dt>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.validate.datevalidator">B.2.7.2. Simplificación en el validador de fecha</a></span></dt>
<dt><span class="sect3"><a href="migration.110.phtml#migration.110.zend.validate.barcodevalidator">B.2.7.3. Correcciones en los validadores Alpha, Alnum y Barcode</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.19.phtml">B.3. Zend Framework 1.9</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.file.transfer">B.3.1. Zend_File_Transfer</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.19.phtml#migration.19.zend.file.transfer.mimetype">B.3.1.1. Validación de MimeType</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.filter">B.3.2. Zend_Filter</a></span></dt>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.http.client">B.3.3. Zend_Http_Client</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.zend.http.client.fileuploadsarray">B.3.3.1. Cambios en el almacenamiento interno de información de archivos subidos</a></span></dt>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.zend.http.client.getparamsrecursize">B.3.3.2. Obsolescencia de Zend_Http_Client::_getParametersRecursive()</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.locale">B.3.4. Zend_Locale</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.19.phtml#migration.19.zend.locale.deprecated">B.3.4.1. Métodos obsoletos</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.zend.view.helper.navigation">B.3.5. Zend_View_Helper_Navigation</a></span></dt>
<dt><span class="sect2"><a href="migration.19.phtml#migration.19.security">B.3.6. Correcciones de seguridad a partir de la 1.9.7</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.security.zend.dojo.editor">B.3.6.1. Zend_Dojo_View_Helper_Editor</a></span></dt>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.security.zend.filter.html-entities">B.3.6.2. Zend_Filter_HtmlEntities</a></span></dt>
<dt><span class="sect3"><a href="migration.19.phtml#migration.19.security.zend.filter.strip-tags">B.3.6.3. Zend_Filter_StripTags</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.18.phtml">B.4. Zend Framework 1.8</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.18.phtml#migration.18.zend.controller">B.4.1. Zend_Controller</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.18.phtml#migration.18.zend.controller.router">B.4.1.1. Cambios en la ruta estándar</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.18.phtml#migration.18.zend.locale">B.4.2. Zend_Locale</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.18.phtml#migration.18.zend.locale.defaultcaching">B.4.2.1. Caché por defecto</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.17.phtml">B.5. Zend Framework 1.7</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.controller">B.5.1. Zend_Controller</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.controller.dispatcher">B.5.1.1. Cambios en la interfaz Dispatcher</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.file.transfer">B.5.2. Zend_File_Transfer</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators">B.5.2.1. Cambios al usar filtros y validadores</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.rename">B.5.2.1.1. Filtro: Rename</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.count">B.5.2.1.2. Validador: Count</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.extension">B.5.2.1.3. Validador: Extension</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.filessize">B.5.2.1.4. Validador: FilesSize</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.hash">B.5.2.1.5. Validador: Hash</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.imagesize">B.5.2.1.6. Validador: ImageSize</a></span></dt>
<dt><span class="sect4"><a href="migration.17.phtml#migration.17.zend.file.transfer.validators.size">B.5.2.1.7. Validador: Size</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.locale">B.5.3. Zend_Locale</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.locale.islocale">B.5.3.1. Cambios al usar isLocale()</a></span></dt>
<dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.locale.islocale.getdefault">B.5.3.2. Cambios al usar getDefault()</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.translate">B.5.4. Zend_Translate</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.translate.languages">B.5.4.1. Establecer idiomas</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.17.phtml#migration.17.zend.view">B.5.5. Zend_View</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.17.phtml#migration.17.zend.view.disabling">B.5.5.1. Deshabilitar la protección LFI para el método render()</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.16.phtml">B.6. Zend Framework 1.6</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.16.phtml#migration.16.zend.controller">B.6.1. Zend_Controller</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.16.phtml#migration.16.zend.controller.dispatcher">B.6.1.1. Cambios en la interfaz Dispatcher</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="migration.16.phtml#migration.16.zend.file.transfer">B.6.2. Zend_File_Transfer</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="migration.16.phtml#migration.16.zend.file.transfer.validators">B.6.2.1. Cambios al usar validadores</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="migration.15.phtml">B.7. Zend Framework 1.5</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.15.phtml#migration.15.zend.controller">B.7.1. Zend_Controller</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="migration.10.phtml">B.8. Zend Framework 1.0</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="migration.10.phtml#migration.10.zend.controller">B.8.1. Zend_Controller</a></span></dt>
<dt><span class="sect2"><a href="migration.10.phtml#migration.10.zend.currency">B.8.2. Zend_Currency</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="migration.09.phtml">B.9. Zend Framework 0.9</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.09.phtml#migration.09.zend.controller">B.9.1. Zend_Controller</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="migration.08.phtml">B.10. Zend Framework 0.8</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.08.phtml#migration.08.zend.controller">B.10.1. Zend_Controller</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="migration.06.phtml">B.11. Zend Framework 0.6</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="migration.06.phtml#migration.06.zend.controller">B.11.1. Zend_Controller</a></span></dt></dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="migration.112"></a>B.1. Zend Framework 1.12</h2></div></div></div>
<p>
        Al actualizar desde una versión anterior a Zend Framework 1.12 o superior,
        debería tener en cuenta las siguientes notas de migración.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.12.zend.view.helper.navigation"></a>B.1.1. Zend_View_Helper_Navigation</h3></div></div></div>
<p>
            Antes de la versión 1.12, no se podía utilizar un helper con el nombre
            "My_View_Helper_Navigation_Menu", porque el helper proxy siempre devolvía
            el helper de vista estándar
            "Zend_View_Helper_Navigation_Menu".
        </p>
<p>
            A partir de la versión 1.12, puede utilizar sus propios helpers de
            navegación con el nombre "menu", "breadcrumbs", ...
        </p>
<p>
            Cree su propio helper con nombre "Menu":
        </p>
<pre class="programlisting">
class My_View_Helper_Navigation_Menu
    extends Zend_View_Helper_Navigation_HelperAbstract
{
    public function menu(Zend_Navigation_Container $container = null)
    {
        if (null !== $container) {
            $this-&gt;setContainer($container);
        }

        return $this;
    }

    public function render(Zend_Navigation_Container $container = null)
    {
        return '&lt;nav&gt;Example&lt;/nav&gt;';
    }
}
</pre>
<p>
            Añada la ruta del helper a <code class="classname">Zend_View</code> en su
            clase Bootstrap:
        </p>
<pre class="programlisting">
    protected function _initView()
    {
        $this-&gt;bootstrap('view');
        $this-&gt;view-&gt;addHelperPath(
            'path/to/helper',
            'My_View_Helper_Navigation'
        );
    }
</pre>
<p>
            O añada la ruta del helper en su archivo "application.ini":
        </p>
<pre class="programlisting">
resources.view.helperPath.My_View_Helper_Navigation = "path/to/helper"
</pre>
<p>
            El siguiente código se utiliza en un script de vista:
        </p>
<pre class="programlisting">
&lt;?php echo $this-&gt;navigation()-&gt;menu(); ?&gt;
</pre>
<p>
            Salida:
        </p>
<pre class="programlisting">
&lt;nav&gt;Example&lt;/nav&gt;
</pre>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="requirements.phtml">Anterior</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> <a accesskey="n" href="migration.110.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Apéndice A. Requisitos de Zend Framework </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> B.2. Zend Framework 1.10</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
