<?php $title = 'B.4. Zend Framework 1.8'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">B.4. Zend Framework 1.8</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="migration.19.phtml">Anterior</a> </td>
<th width="60%" align="center">Apéndice B. Notas de migración de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="migration.17.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="migration.18"></a>B.4. Zend Framework 1.8</h2></div></div></div>
<p>
        Al actualizar desde una versión anterior a Zend Framework 1.8 o superior, debería
        tener en cuenta las siguientes notas de migración.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.18.zend.controller"></a>B.4.1. Zend_Controller</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="migration.18.zend.controller.router"></a>B.4.1.1. Cambios en la ruta estándar</h4></div></div></div>
<p>
                Dado que se introdujeron segmentos traducidos en la nueva ruta
                estándar, el carácter '<span class="emphasis"><em>@</em></span>' ahora es un carácter especial
                al comienzo de un segmento de ruta. Para poder usarlo en un
                segmento estático, debe escaparlo anteponiéndole un segundo
                carácter '<span class="emphasis"><em>@</em></span>'. La misma regla se aplica ahora al
                carácter '<span class="emphasis"><em>:</em></span>'.
            </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.18.zend.locale"></a>B.4.2. Zend_Locale</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="migration.18.zend.locale.defaultcaching"></a>B.4.2.1. Caché por defecto</h4></div></div></div>
<p>
                A partir de Zend Framework 1.8 se añadió una caché por defecto. La razón detrás de este
                cambio fue que la mayoría de los usuarios tenían problemas de rendimiento pero no añadían
                caché en absoluto. Como el núcleo de I18n es un cuello de botella cuando no se usa
                caché, decidimos añadir una caché por defecto cuando no se ha establecido ninguna caché
                en <code class="classname">Zend_Locale</code>.
            </p>
<p>
                A veces todavía se desea evitar la caché por completo aunque esto reduzca
                el rendimiento. Para hacerlo puede simplemente deshabilitar la caché usando el
                método <code class="methodname">disableCache()</code>.
            </p>
<div class="example">
<a name="migration.18.zend.locale.defaultcaching.example"></a><p class="title"><b>Ejemplo B.3. Deshabilitar la caché por defecto</b></p>
<div class="example-contents"><pre class="programlisting">
Zend_Locale::disableCache(true);
</pre></div>
</div>
<br class="example-break">
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="migration.19.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="migration.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="migration.17.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">B.3. Zend Framework 1.9 </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> B.5. Zend Framework 1.7</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
