<?php $title = 'B.9. Zend Framework 0.9'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">B.9. Zend Framework 0.9</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="migration.10.phtml">Anterior</a> </td>
<th width="60%" align="center">Apéndice B. Notas de migración de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="migration.08.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="migration.09"></a>B.9. Zend Framework 0.9</h2></div></div></div>
<p>
        Al actualizar desde una versión anterior a Zend Framework 0.9 o superior debería
        tener en cuenta las siguientes notas de migración.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.09.zend.controller"></a>B.9.1. Zend_Controller</h3></div></div></div>
<p>
            0.9.3 introduce los <a class="link" href="zend.controller.actionhelpers.phtml" title="24.8. Action Helpers">helpers de acción</a>.
            Como parte de este cambio, se han eliminado los siguientes métodos ya
            que ahora están encapsulados en el <a class="link" href="zend.controller.actionhelpers.phtml#zend.controller.actionhelpers.redirector" title="24.8.4.6. Redirector">helper de acción
                redirector</a>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="methodname">setRedirectCode()</code>; use
                    <code class="methodname">Zend_Controller_Action_Helper_Redirector::setCode()</code>.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setRedirectPrependBase()</code>; use
                    <code class="methodname">Zend_Controller_Action_Helper_Redirector::setPrependBase()</code>.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setRedirectExit()</code>; use
                    <code class="methodname">Zend_Controller_Action_Helper_Redirector::setExit()</code>.
                </p></li>
</ul></div>
<p>
            Lea la <a class="link" href="zend.controller.actionhelpers.phtml" title="24.8. Action Helpers">documentación de los
                helpers de acción</a> para más información sobre cómo
            obtener y manipular objetos helper, y la <a class="link" href="zend.controller.actionhelpers.phtml#zend.controller.actionhelpers.redirector" title="24.8.4.6. Redirector">documentación del
                helper redirector</a> para más información sobre cómo configurar
            opciones de redirección (así como métodos alternativos para redirigir).
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="migration.10.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="migration.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="migration.08.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">B.8. Zend Framework 1.0 </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> B.10. Zend Framework 0.8</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
