<?php $title = 'B.6. Zend Framework 1.6'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">B.6. Zend Framework 1.6</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="migration.17.phtml">Anterior</a> </td>
<th width="60%" align="center">Apéndice B. Notas de migración de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="migration.15.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="migration.16"></a>B.6. Zend Framework 1.6</h2></div></div></div>
<p>
        Al actualizar desde una versión anterior a Zend Framework 1.6 o superior
        debe tener en cuenta las siguientes notas de migración.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.16.zend.controller"></a>B.6.1. Zend_Controller</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="migration.16.zend.controller.dispatcher"></a>B.6.1.1. Cambios en la interfaz Dispatcher</h4></div></div></div>
<p>
                Los usuarios nos hicieron notar el hecho de que
                <code class="classname">Zend_Controller_Front</code> y
                <code class="classname">Zend_Controller_Router_Route_Module</code> utilizaban cada uno
                métodos del dispatcher que no estaban en la interfaz del
                dispatcher. Ahora hemos añadido los siguientes tres métodos para
                asegurar que los dispatchers personalizados sigan funcionando con las
                implementaciones proporcionadas:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">getDefaultModule()</code>: debe devolver el nombre del
                        módulo por defecto.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getDefaultControllerName()</code>: debe devolver el
                        nombre del controlador por defecto.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getDefaultAction()</code>: debe devolver el
                        nombre de la acción por defecto.
                    </p></li>
</ul></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="migration.16.zend.file.transfer"></a>B.6.2. Zend_File_Transfer</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="migration.16.zend.file.transfer.validators"></a>B.6.2.1. Cambios al usar validadores</h4></div></div></div>
<p>
                Como han observado los usuarios, los validadores de <code class="classname">Zend_File_Transfer</code>
                no funcionan de la misma manera que los predeterminados de
                <code class="classname">Zend_Form</code>. <code class="classname">Zend_Form</code> permite el uso
                de un parámetro <code class="varname">$breakChainOnFailure</code> que interrumpe la validación
                para todos los validadores posteriores cuando ha ocurrido un error de validación.
            </p>
<p>
                Por ello hemos añadido también este parámetro a todos los validadores existentes de
                <code class="classname">Zend_File_Transfer</code>.
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <acronym class="acronym">API</acronym> del método antiguo: <code class="methodname">addValidator($validator,
                            $options, $files)</code>.
                    </p></li>
<li class="listitem"><p>
                        <acronym class="acronym">API</acronym> del método nuevo: <code class="methodname">addValidator($validator,
                            $breakChainOnFailure, $options, $files)</code>.
                    </p></li>
</ul></div>
<p>
                Para migrar sus scripts a la nueva <acronym class="acronym">API</acronym>, simplemente añada un
                <code class="constant">FALSE</code> después de definir el validador deseado.
            </p>
<div class="example">
<a name="migration.16.zend.file.transfer.example"></a><p class="title"><b>Ejemplo B.14. Cómo cambiar sus validadores de archivo de la versión 1.6.1 a la 1.6.2</b></p>
<div class="example-contents"><pre class="programlisting">
// Example for 1.6.1
$upload = new Zend_File_Transfer_Adapter_Http();
$upload-&gt;addValidator('FilesSize', array('1B', '100kB'));

// Same example for 1.6.2 and newer
// Note the added boolean false
$upload = new Zend_File_Transfer_Adapter_Http();
$upload-&gt;addValidator('FilesSize', false, array('1B', '100kB'));
</pre></div>
</div>
<br class="example-break">
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="migration.17.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="migration.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="migration.15.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">B.5. Zend Framework 1.7 </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> B.7. Zend Framework 1.5</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
