<?php $title = 'Apéndice E. Estructura de proyecto recomendada para aplicaciones MVC de Zend Framework'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Apéndice E. Estructura de proyecto recomendada para aplicaciones MVC de Zend Framework</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="doc-standard.recommendations.phtml">Anterior</a> </td>
<th width="60%" align="center"> </th>
<td width="20%" align="right"> <a accesskey="n" href="project-structure.project.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="appendix">
<div class="titlepage"><div><div><h1 class="title">
<a name="project-structure"></a>Apéndice E. Estructura de proyecto recomendada para aplicaciones MVC de Zend Framework</h1></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="project-structure.phtml#project-structure.overview">E.1. Resumen</a></span></dt>
<dt><span class="sect1"><a href="project-structure.project.phtml">E.2. Estructura de directorios de proyecto recomendada</a></span></dt>
<dt><span class="sect1"><a href="project-structure.filesystem.phtml">E.3. Estructura de módulos</a></span></dt>
<dt><span class="sect1"><a href="project-structure.rewrite.phtml">E.4. Guía de configuración de reescritura</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="project-structure.rewrite.phtml#project-structure.rewrite.apache">E.4.1. Servidor HTTP Apache</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="project-structure.rewrite.phtml#project-structure.rewrite.apache.vhost">E.4.1.1. Reescritura dentro de un VirtualHost</a></span></dt>
<dt><span class="sect3"><a href="project-structure.rewrite.phtml#project-structure.rewrite.apache.htaccess">E.4.1.2. Reescritura dentro de un archivo .htaccess</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="project-structure.rewrite.phtml#project-structure.rewrite.iis">E.4.2. Microsoft Internet Information Server</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="project-structure.overview"></a>E.1. Resumen</h2></div></div></div>
<p>
            Muchos desarrolladores buscan orientación sobre la mejor estructura de proyecto para un proyecto de Zend Framework
            en un entorno relativamente flexible. Un entorno "flexible" es aquel en el que el
            desarrollador puede manipular sus sistemas de archivos y configuraciones de servidor web según sea necesario para
            lograr la estructura de proyecto más ideal para ejecutar y proteger su aplicación. La
            estructura de proyecto predeterminada asumirá que el desarrollador dispone de dicha flexibilidad.
        </p>
<p>
            La siguiente estructura de directorios está diseñada para ser lo más extensible posible en proyectos complejos,
            a la vez que proporciona un subconjunto simple de carpetas y archivos para proyectos con requisitos
            más simples. Esta estructura también funciona sin alteraciones tanto para aplicaciones modulares como
            no modulares de Zend Framework. Los archivos <code class="filename">.htaccess</code>
            requieren la funcionalidad de reescritura de <acronym class="acronym">URL</acronym> en el servidor web, tal como se describe en
            la <a class="link" href="project-structure.rewrite.phtml" title="E.4. Rewrite Configuration Guide">Guía de configuración de reescritura</a>, también
            incluida en este apéndice.
        </p>
<p>
            No es la intención que esta estructura de proyecto soporte todos los posibles requisitos de proyectos
            de Zend Framework. El perfil de proyecto predeterminado usado por
            <code class="classname">Zend_Tool</code> refleja esta estructura de proyecto, pero las aplicaciones con
            requisitos no soportados por esta estructura deberían usar un perfil de proyecto personalizado.
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="doc-standard.recommendations.phtml">Anterior</a> </td>
<td width="20%" align="center"> </td>
<td width="40%" align="right"> <a accesskey="n" href="project-structure.project.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">D.3. Recomendaciones </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> E.2. Estructura de directorios de proyecto recomendada</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
