<?php $title = '64.17. Zend_Service_Audioscrobbler'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.17. Zend_Service_Audioscrobbler</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.amazon.sqs.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.delicious.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.audioscrobbler"></a>64.17. Zend_Service_Audioscrobbler</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.audioscrobbler.introduction"></a>64.17.1. Introducción</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Audioscrobbler</code> es una <acronym class="acronym">API</acronym>
            sencilla para utilizar el servicio web REST de Audioscrobbler. El servicio web
            Audioscrobbler proporciona acceso a su base de datos de Usuarios, Artistas, Álbumes,
            Pistas, Etiquetas, Grupos y Foros. Los métodos de la clase
            <code class="classname">Zend_Service_Audioscrobbler</code> comienzan con uno de estos
            términos. La sintaxis y los espacios de nombres del servicio web Audioscrobbler se
            reflejan en <code class="classname">Zend_Service_Audioscrobbler</code>. Para más
            información acerca del servicio web REST de Audioscrobbler, visite el
            <a class="ulink" href="http://www.audioscrobbler.net/data/webservices/" target="_top">sitio del servicio web
                Audioscrobbler</a>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.audioscrobbler.users"></a>64.17.2. Usuarios</h3></div></div></div>
<p>
            Para recuperar información de un usuario específico, primero se utiliza el método
            <code class="methodname">setUser()</code> para seleccionar el usuario del que se van a
            recuperar los datos. <code class="classname">Zend_Service_Audioscrobbler</code> proporciona
            varios métodos para recuperar datos específicos de un único usuario:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">userGetProfileInformation()</code>: Devuelve un objeto
                        SimpleXML que contiene la información del perfil del usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetTopArtists()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de los artistas más escuchados por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetTopAlbums()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de los álbumes más escuchados por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetTopTracks()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de las pistas más escuchadas por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetTopTags()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de las etiquetas más aplicadas por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetTopTagsForArtist()</code>: Requiere que se
                        establezca un artista mediante <code class="methodname">setArtist()</code>.
                        Devuelve un objeto SimpleXML que contiene las etiquetas más aplicadas al
                        artista actual por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetTopTagsForAlbum()</code>: Requiere que se
                        establezca un álbum mediante <code class="methodname">setAlbum()</code>.
                        Devuelve un objeto SimpleXML que contiene las etiquetas más aplicadas al
                        álbum actual por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetTopTagsForTrack()</code>: Requiere que se
                        establezca una pista mediante <code class="methodname">setTrack()</code>.
                        Devuelve un objeto SimpleXML que contiene las etiquetas más aplicadas a la
                        pista actual por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetFriends()</code>: Devuelve un objeto SimpleXML
                        que contiene los nombres de usuario de los amigos del usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetNeighbours()</code>: Devuelve un objeto SimpleXML
                        que contiene los nombres de usuario de las personas con hábitos de escucha
                        similares al usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetRecentTracks()</code>: Devuelve un objeto SimpleXML
                        que contiene las 10 pistas reproducidas más recientemente por el usuario
                        actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetRecentBannedTracks()</code>: Devuelve un objeto
                        SimpleXML que contiene una lista de las 10 pistas vetadas más recientemente
                        por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetRecentLovedTracks()</code>: Devuelve un objeto
                        SimpleXML que contiene una lista de las 10 pistas marcadas como favoritas más
                        recientemente por el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetRecentJournals()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de las entradas de diario más recientes del usuario
                        actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetWeeklyChartList()</code>: Devuelve un objeto
                        SimpleXML que contiene una lista de semanas para las que existen Listas
                        Semanales para el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetRecentWeeklyArtistChart()</code>: Devuelve un
                        objeto SimpleXML que contiene la Lista Semanal de Artistas más reciente para
                        el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetRecentWeeklyAlbumChart()</code>: Devuelve un
                        objeto SimpleXML que contiene la Lista Semanal de Álbumes más reciente para
                        el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetRecentWeeklyTrackChart()</code>: Devuelve un
                        objeto SimpleXML que contiene la Lista Semanal de Pistas más reciente para
                        el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetPreviousWeeklyArtistChart($fromDate,
                            $toDate)</code>: Devuelve un objeto SimpleXML que contiene la Lista
                        Semanal de Artistas desde <code class="varname">$fromDate</code> hasta <code class="varname">$toDate</code>
                        para el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetPreviousWeeklyAlbumChart($fromDate,
                            $toDate)</code>: Devuelve un objeto SimpleXML que contiene la Lista
                        Semanal de Álbumes desde <code class="varname">$fromDate</code> hasta <code class="varname">$toDate</code>
                        para el usuario actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">userGetPreviousWeeklyTrackChart($fromDate,
                            $toDate)</code>: Devuelve un objeto SimpleXML que contiene la Lista
                        Semanal de Pistas desde <code class="varname">$fromDate</code> hasta <code class="varname">$toDate</code>
                        para el usuario actual.
                    </p></li>
</ul></div>
<p>
        </p>
<div class="example">
<a name="zend.service.audioscrobbler.users.example.profile_information"></a><p class="title"><b>Ejemplo 64.77. Recuperación de la información del perfil de un usuario</b></p>
<div class="example-contents">
<p>
                En este ejemplo, utilizamos los métodos <code class="methodname">setUser()</code> y
                <code class="methodname">userGetProfileInformation()</code> para recuperar la información
                del perfil de un usuario específico:
            </p>
<pre class="programlisting">
$as = new Zend_Service_Audioscrobbler();
// Set the user whose profile information we want to retrieve
$as-&gt;setUser('BigDaddy71');
// Retrieve BigDaddy71's profile information
$profileInfo = $as-&gt;userGetProfileInformation();
// Display some of it
print "Information for $profileInfo-&gt;realname "
    . "can be found at $profileInfo-&gt;url";
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.service.audioscrobbler.users.example.weekly_artist_chart"></a><p class="title"><b>Ejemplo 64.78. Recuperación de la Lista Semanal de Artistas de un usuario</b></p>
<div class="example-contents"><pre class="programlisting">
$as = new Zend_Service_Audioscrobbler();
// Set the user whose profile weekly artist chart we want to retrieve
$as-&gt;setUser('lo_fye');
// Retrieves a list of previous weeks for which there are chart data
$weeks = $as-&gt;userGetWeeklyChartList();
if (count($weeks) &lt; 1) {
    echo 'No data available';
}
sort($weeks); // Order the list of weeks

$as-&gt;setFromDate($weeks[0]); // Set the starting date
$as-&gt;setToDate($weeks[0]); // Set the ending date

$previousWeeklyArtists = $as-&gt;userGetPreviousWeeklyArtistChart();

echo 'Artist Chart For Week Of '
   . date('Y-m-d h:i:s', $as-&gt;from_date)
   . '&lt;br /&gt;';

foreach ($previousWeeklyArtists as $artist) {
    // Display the artists' names with links to their profiles
    print '&lt;a href="' . $artist-&gt;url . '"&gt;' . $artist-&gt;name . '&lt;/a&gt;&lt;br /&gt;';
}
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.audioscrobbler.artists"></a>64.17.3. Artistas</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Audioscrobbler</code> proporciona varios métodos para
            recuperar datos sobre un artista específico, indicado mediante el método
            <code class="methodname">setArtist()</code>:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">artistGetRelatedArtists()</code>: Devuelve un objeto
                        SimpleXML que contiene una lista de Artistas similares al Artista actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">artistGetTopFans()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de Usuarios que más escuchan al Artista actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">artistGetTopTracks()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de las Pistas mejor valoradas del Artista actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">artistGetTopAlbums()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de los Álbumes mejor valorados del Artista actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">artistGetTopTags()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de las Etiquetas más frecuentemente aplicadas al
                        Artista actual.
                    </p></li>
</ul></div>
<p>
        </p>
<div class="example">
<a name="zend.service.audioscrobbler.artists.example.related_artists"></a><p class="title"><b>Ejemplo 64.79. Recuperación de artistas relacionados</b></p>
<div class="example-contents"><pre class="programlisting">
$as = new Zend_Service_Audioscrobbler();
// Set the artist for whom you would like to retrieve related artists
$as-&gt;setArtist('LCD Soundsystem');
// Retrieve the related artists
$relatedArtists = $as-&gt;artistGetRelatedArtists();
foreach ($relatedArtists as $artist) {
    // Display the related artists
    print '&lt;a href="' . $artist-&gt;url . '"&gt;' . $artist-&gt;name . '&lt;/a&gt;&lt;br /&gt;';
}
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.audioscrobbler.tracks"></a>64.17.4. Pistas</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Audioscrobbler</code> proporciona dos métodos para
            recuperar datos específicos de una única pista, indicada mediante el método
            <code class="methodname">setTrack()</code>:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">trackGetTopFans()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de Usuarios que más escuchan la Pista actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">trackGetTopTags()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de las Etiquetas más frecuentemente aplicadas a la
                        Pista actual.
                    </p></li>
</ul></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.audioscrobbler.tags"></a>64.17.5. Etiquetas</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Audioscrobbler</code> proporciona varios métodos para
            recuperar datos específicos de una única etiqueta, indicada mediante el método
            <code class="methodname">setTag()</code>:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">tagGetOverallTopTags()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de las Etiquetas más frecuentemente usadas en
                        Audioscrobbler.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">tagGetTopArtists()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de Artistas a los que se ha aplicado con más
                        frecuencia la Etiqueta actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">tagGetTopAlbums()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de Álbumes a los que se ha aplicado con más
                        frecuencia la Etiqueta actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">tagGetTopTracks()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de Pistas a las que se ha aplicado con más
                        frecuencia la Etiqueta actual.
                    </p></li>
</ul></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.audioscrobbler.groups"></a>64.17.6. Grupos</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Audioscrobbler</code> proporciona varios métodos para
            recuperar datos específicos de un único grupo, indicado mediante el método
            <code class="methodname">setGroup()</code>:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">groupGetRecentJournals()</code>: Devuelve un objeto
                        SimpleXML que contiene una lista de las entradas de diario recientes de los
                        Usuarios del Grupo actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">groupGetWeeklyChart()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de semanas para las que existen Listas Semanales para
                        el Grupo actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">groupGetRecentWeeklyArtistChart()</code>: Devuelve un
                        objeto SimpleXML que contiene la Lista Semanal de Artistas más reciente para
                        el Grupo actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">groupGetRecentWeeklyAlbumChart()</code>: Devuelve un
                        objeto SimpleXML que contiene la Lista Semanal de Álbumes más reciente para
                        el Grupo actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">groupGetRecentWeeklyTrackChart()</code>: Devuelve un
                        objeto SimpleXML que contiene la Lista Semanal de Pistas más reciente para
                        el Grupo actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">groupGetPreviousWeeklyArtistChart($fromDate,
                            $toDate)</code>: Requiere <code class="methodname">setFromDate()</code>
                        y <code class="methodname">setToDate()</code>. Devuelve un objeto SimpleXML
                        que contiene la Lista Semanal de Artistas desde el fromDate actual hasta el
                        toDate actual para el Grupo actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">groupGetPreviousWeeklyAlbumChart($fromDate,
                            $toDate)</code>: Requiere <code class="methodname">setFromDate()</code>
                        y <code class="methodname">setToDate()</code>. Devuelve un objeto SimpleXML
                        que contiene la Lista Semanal de Álbumes desde el fromDate actual hasta el
                        toDate actual para el Grupo actual.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">groupGetPreviousWeeklyTrackChart($fromDate,
                            $toDate)</code>: Devuelve un objeto SimpleXML que contiene la Lista
                        Semanal de Pistas desde el fromDate actual hasta el toDate actual para el
                        Grupo actual.
                    </p></li>
</ul></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.audioscrobbler.forums"></a>64.17.7. Foros</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Audioscrobbler</code> proporciona un método para recuperar
            datos específicos de un único foro, indicado mediante el método
            <code class="methodname">setForum()</code>:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                        <code class="methodname">forumGetRecentPosts()</code>: Devuelve un objeto SimpleXML
                        que contiene una lista de las publicaciones recientes en el foro actual.
                    </p></li></ul></div>
<p>
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.amazon.sqs.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.delicious.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.16. Zend_Service_Amazon_Sqs </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 64.18. Zend_Service_Delicious</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
