<?php $title = '42.9. La utilidad Class Map Generator: bin/classmap_generator.php'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">42.9. La utilidad Class Map Generator: bin/classmap_generator.php</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.register.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 42. Zend_Loader</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.locale.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.loader.classmap-generator"></a>42.9. La utilidad Class Map Generator: bin/classmap_generator.php</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.loader.classmap-generator.intro"></a>42.9.1. Resumen</h3></div></div></div>
<p>
            El script <code class="filename">bin/classmap_generator.php</code> puede usarse para generar archivos de mapa
            de clases para usar con <a class="link" href="zend.loader.class-map-autoloader.phtml" title="42.8. The ClassMapAutoloader">el
                ClassMapAutoloader</a>.
        </p>
<p>
            Internamente, utiliza tanto <a class="link" href="zend.console.getopt.phtml" title="Chapter 23. Zend_Console_Getopt">Zend_Console_Getopt</a> (para analizar las
            opciones de línea de comandos) como Zend_File_ClassFileLocator para
            encontrar de forma recursiva todos los archivos de clases PHP en un árbol de directorios dado.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.loader.classmap-generator.quick-start"></a>42.9.2. Inicio rápido</h3></div></div></div>
<p>
            Puede ejecutar el script sobre cualquier directorio que contenga código fuente. Por defecto,
            buscará en el directorio actual, y escribirá el script en
            <code class="filename">autoload_classmap.php</code> en el directorio que especifique.
        </p>
<pre class="programlisting">
php classmap_generator.php Some/Directory/
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.loader.classmap-generator.options"></a>42.9.3. Opciones de configuración</h3></div></div></div>
<div class="variablelist">
<p class="title"><b>Opciones del Class Map Generator</b></p>
<dl class="variablelist">
<dt><span class="term">--help o -h</span></dt>
<dd><p>
                        Devuelve el mensaje de uso. Si se proporcionan otras opciones, serán
                        ignoradas.
                    </p></dd>
<dt><span class="term">--library o -l</span></dt>
<dd><p>
                        Espera un único argumento, una cadena que especifique el directorio de la biblioteca
                        a analizar. Si esta opción no se especifica, se asumirá el directorio de trabajo
                        actual.
                    </p></dd>
<dt><span class="term">--output o -o</span></dt>
<dd><p>
                        Dónde escribir el archivo de mapa de clases de autoload. Si no se proporciona, se asume
                        "autoload_classmap.php" en el directorio de la biblioteca.
                    </p></dd>
<dt><span class="term">--overwrite o -w</span></dt>
<dd><p>
                        Si ya existe un archivo de mapa de clases de autoload con el nombre especificado mediante
                        la opción <code class="varname">--output</code>, puede sobrescribirlo especificando
                        este indicador. De lo contrario, el script no escribirá el mapa de clases y devolverá una
                        advertencia.
                    </p></dd>
</dl>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.register.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.locale.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">register </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 43. Zend_Locale</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
