<?php $title = '24.2. Fundamentos de Zend_Controller'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">24.2. Fundamentos de Zend_Controller</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.controller.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 24. Zend_Controller</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.controller.front.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.controller.basics"></a>24.2. Fundamentos de Zend_Controller</h2></div></div></div>
<p>
        El sistema <code class="classname">Zend_Controller</code> está diseñado para ser
        ligero, modular y extensible. Es un diseño minimalista que
        permite flexibilidad y cierta libertad a los usuarios, a la vez que proporciona
        suficiente estructura para que los sistemas construidos alrededor de <code class="classname">Zend_Controller</code>
        compartan algunas convenciones comunes y una disposición de código similar.
    </p>
<p>
        El siguiente diagrama muestra el flujo de trabajo, y la narrativa que
        sigue describe en detalle las interacciones:
    </p>
<p>
        <img src="figures/zend.controller.basics.png" align="middle">
    </p>
<p>
        El flujo de trabajo de <code class="classname">Zend_Controller</code> se implementa mediante varios
        componentes. Aunque no es necesario comprender completamente los
        entresijos de todos estos componentes para usar el sistema, tener un
        conocimiento práctico del proceso resulta útil.
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <code class="classname">Zend_Controller_Front</code> orquesta todo el
                flujo de trabajo del sistema <code class="classname">Zend_Controller</code>. Es
                una interpretación del patrón FrontController.
                <code class="classname">Zend_Controller_Front</code> procesa todas las peticiones
                recibidas por el servidor y es, en última instancia, responsable de
                delegar las peticiones a los ActionControllers
                (<code class="classname">Zend_Controller_Action</code>).
            </p></li>
<li class="listitem">
<p>
                <code class="classname">Zend_Controller_Request_Abstract</code> (a menudo
                denominado el <span class="emphasis"><em>objeto de petición</em></span>) representa
                el entorno de la petición y proporciona métodos para establecer y
                recuperar los nombres del controlador y la acción, así como cualquier parámetro
                de la petición. Además, lleva un registro de si la
                acción que contiene ha sido despachada o no por
                <code class="classname">Zend_Controller_Dispatcher</code>. Las extensiones al
                objeto de petición abstracto se pueden usar para encapsular
                todo el entorno de la petición, permitiendo que los enrutadores extraigan
                información del entorno de la petición con el fin de establecer los
                nombres del controlador y la acción.
            </p>
<p>
                Por defecto, se utiliza <code class="classname">Zend_Controller_Request_Http</code>,
                que proporciona acceso a todo el entorno de la petición <acronym class="acronym">HTTP</acronym>.
            </p>
</li>
<li class="listitem">
<p>
                <code class="classname">Zend_Controller_Router_Interface</code> se utiliza para
                definir enrutadores. El enrutamiento es el proceso de examinar el
                entorno de la petición para determinar qué controlador, y
                qué acción de ese controlador, debe recibir la petición. Este
                controlador, acción, y parámetros opcionales se establecen entonces
                en el objeto de petición para ser procesados por
                <code class="classname">Zend_Controller_Dispatcher_Standard</code>. El enrutamiento
                ocurre solo una vez: cuando se recibe la petición inicialmente y
                antes de que se despache el primer controlador.
            </p>
<p>
                El enrutador por defecto,
                <code class="classname">Zend_Controller_Router_Rewrite</code>, toma un
                punto final de <acronym class="acronym">URI</acronym> tal como se especifica en
                <code class="classname">Zend_Controller_Request_Http</code> y lo descompone
                en un controlador, una acción y parámetros basándose en la información de ruta
                de la <acronym class="acronym">URL</acronym>. Por ejemplo, la <acronym class="acronym">URL</acronym>
                <code class="filename">http://localhost/foo/bar/key/value</code> se
                decodificaría para usar el controlador <span class="emphasis"><em>foo</em></span>,
                la acción <span class="emphasis"><em>bar</em></span>, y especificar un parámetro
                <span class="emphasis"><em>key</em></span> con un valor de <span class="emphasis"><em>value</em></span>.
            </p>
<p>
                <code class="classname">Zend_Controller_Router_Rewrite</code> también se puede usar
                para hacer coincidir rutas arbitrarias; consulte <a class="link" href="zend.controller.router.phtml" title="24.5. The Standard Router">la documentación del enrutador</a>
                para más información.
            </p>
</li>
<li class="listitem">
<p>
                <code class="classname">Zend_Controller_Dispatcher_Interface</code> se utiliza para
                definir despachadores. El despacho es el proceso de extraer
                el controlador y la acción del objeto de petición y
                asignarlos a un archivo de controlador (o clase) y un método de acción en
                la clase del controlador. Si el controlador o la acción no
                existen, se encarga de determinar los controladores y
                acciones por defecto a despachar.
            </p>
<p>
                El proceso de despacho en sí consiste en instanciar la
                clase del controlador y llamar al método de acción en esa
                clase. A diferencia del enrutamiento, que ocurre solo una vez, el despacho
                ocurre en un bucle. Si el estado de despachado del objeto de petición
                se restablece en algún momento, el bucle se repetirá, llamando a
                cualquier acción que esté actualmente establecida en el objeto de petición. La
                primera vez que el bucle finaliza con el estado de despachado del objeto de petición
                establecido (<span class="type">booleano</span> <code class="constant">TRUE</code>),
                se dará por terminado el procesamiento.
            </p>
<p>
                El despachador por defecto es
                <code class="classname">Zend_Controller_Dispatcher_Standard</code>. Define los
                controladores como MixedCasedClasses terminadas en la palabra
                Controller, y los métodos de acción como camelCasedMethods terminados
                en la palabra Action:
                <code class="methodname">FooController::barAction()</code>. En este caso, el
                controlador se denominaría <span class="emphasis"><em>foo</em></span> y
                la acción <span class="emphasis"><em>bar</em></span>.
            </p>
<div class="note"><table border="0" summary="Note: Case Naming Conventions">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Convenciones de nomenclatura en el uso de mayúsculas</th>
</tr>
<tr><td align="left" valign="top">
<p>
                    Dado que los seres humanos son notoriamente inconsistentes a la hora de
                    mantener la sensibilidad a mayúsculas y minúsculas al escribir enlaces, Zend
                    Framework en realidad normaliza la información de ruta a
                    minúsculas. Esto, por supuesto, afectará a cómo nombre
                    sus controladores y acciones... o los referencie en
                    los enlaces.
                </p>
<p>
                    Si desea que el nombre de la clase de su controlador o el método de acción
                    tenga varias MixedCasedWords o
                    camelCasedWords, deberá separar esas palabras
                    en la url con un '-' o un '.' (aunque puede
                    configurar el carácter utilizado).
                </p>
<p>
                    Por ejemplo, si fuera a acceder a la acción en
                    <code class="methodname">FooBarController::bazBatAction()</code>, la
                    referenciaría en la url como <code class="filename">/foo-bar/baz-bat</code>
                    o <code class="filename">/foo.bar/baz.bat</code>.
                </p>
</td></tr>
</table></div>
</li>
<li class="listitem"><p>
                <code class="classname">Zend_Controller_Action</code> es el componente base de
                controlador de acción. Cada controlador es una única clase
                que extiende la clase <code class="classname">Zend_Controller_Action</code>
                y debe contener uno o más métodos de acción.
            </p></li>
<li class="listitem">
<p>
                <code class="classname">Zend_Controller_Response_Abstract</code> define una
                clase de respuesta base utilizada para recopilar y devolver respuestas
                de los controladores de acción. Recopila tanto cabeceras como
                contenido del cuerpo.
            </p>
<p>
                La clase de respuesta por defecto es
                <code class="classname">Zend_Controller_Response_Http</code>, que es
                adecuada para su uso en un entorno <acronym class="acronym">HTTP</acronym>.
            </p>
</li>
</ul></div>
<p>
        El flujo de trabajo de <code class="classname">Zend_Controller</code> es relativamente sencillo. Una
        petición es recibida por <code class="classname">Zend_Controller_Front</code>, que a su vez
        llama a <code class="classname">Zend_Controller_Router_Rewrite</code> para determinar qué
        controlador (y qué acción de ese controlador) despachar.
        <code class="classname">Zend_Controller_Router_Rewrite</code> descompone la <acronym class="acronym">URI</acronym>
        con el fin de establecer los nombres del controlador y la acción en la petición.
        <code class="classname">Zend_Controller_Front</code> entra entonces en un bucle de despacho. Llama a
        <code class="classname">Zend_Controller_Dispatcher_Standard</code>, pasándole la
        petición, para despachar al controlador y la acción especificados en la
        petición (o usar los valores por defecto). Una vez que el controlador ha terminado, el control
        vuelve a <code class="classname">Zend_Controller_Front</code>. Si el controlador ha
        indicado que se debe despachar otro controlador restableciendo el
        estado de despachado de la petición, el bucle continúa y se realiza otro
        despacho. En caso contrario, el proceso termina.
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.controller.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.controller.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.controller.front.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 24. Zend_Controller </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 24.3. El controlador frontal</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
