<?php $title = '33.6. Consumo de una única entrada Atom'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">33.6. Consumo de una única entrada Atom</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.feed.consuming-atom.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 33. Zend_Feed</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.feed.modifying-feed.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.feed.consuming-atom-single-entry"></a>33.6. Consumo de una única entrada Atom</h2></div></div></div>
<p>
        Los elementos <span class="command"><strong>&lt;entry&gt;</strong></span> Atom individuales también son válidos por sí mismos. Normalmente
        la <acronym class="acronym">URL</acronym> de una entrada es la <acronym class="acronym">URL</acronym> del feed seguida de
        <span class="command"><strong>/&lt;entryId&gt;</strong></span>, como
        <code class="filename">http://atom.example.com/feed/1</code>, usando la
        <acronym class="acronym">URL</acronym> de ejemplo que usamos anteriormente.
    </p>
<p>
        Si lee una única entrada, seguirá teniendo un objeto <code class="classname">Zend_Feed_Atom</code>,
        pero automáticamente creará un feed "anónimo" para contener la entrada.
    </p>
<div class="example">
<a name="zend.feed.consuming-atom-single-entry.example.atom"></a><p class="title"><b>Ejemplo 33.3. Lectura de un feed Atom de entrada única</b></p>
<div class="example-contents"><pre class="programlisting">
$feed = new Zend_Feed_Atom('http://atom.example.com/feed/1');
echo 'The feed has: ' . $feed-&gt;count() . ' entry.';

$entry = $feed-&gt;current();
</pre></div>
</div>
<br class="example-break"><p>
        Alternativamente, podría instanciar el objeto entrada directamente si sabe que está accediendo
        a un documento solo de <span class="command"><strong>&lt;entry&gt;</strong></span>:
    </p>
<div class="example">
<a name="zend.feed.consuming-atom-single-entry.example.entryatom"></a><p class="title"><b>Ejemplo 33.4. Uso directo del objeto Entry para un feed Atom de entrada única</b></p>
<div class="example-contents"><pre class="programlisting">
$entry = new Zend_Feed_Entry_Atom('http://atom.example.com/feed/1');
echo $entry-&gt;title();
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.feed.consuming-atom.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.feed.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.feed.modifying-feed.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">33.5. Consumo de un feed Atom </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 33.7. Modificación de estructuras Feed y Entry</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
