<?php $title = 'Capítulo 13. Zend_Amf'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 13. Zend_Amf</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.acl.advanced.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.amf.server.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.amf"></a>Capítulo 13. Zend_Amf</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.amf.phtml#zend.amf.introduction">13.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.amf.server.phtml">13.2. Zend_Amf_Server</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.amf.server.phtml#zend.amf.server.flex">13.2.1. Conexión al servidor desde Flex</a></span></dt>
<dt><span class="sect2"><a href="zend.amf.server.phtml#zend.amf.server.errors">13.2.2. Manejo de errores</a></span></dt>
<dt><span class="sect2"><a href="zend.amf.server.phtml#zend.amf.server.response">13.2.3. Respuestas AMF</a></span></dt>
<dt><span class="sect2"><a href="zend.amf.server.phtml#zend.amf.server.typedobjects">13.2.4. Objetos tipados</a></span></dt>
<dt><span class="sect2"><a href="zend.amf.server.phtml#zend.amf.server.resources">13.2.5. Recursos</a></span></dt>
<dt><span class="sect2"><a href="zend.amf.server.phtml#zend.amf.server.flash">13.2.6. Conexión al servidor desde Flash</a></span></dt>
<dt><span class="sect2"><a href="zend.amf.server.phtml#zend.amf.server.auth">13.2.7. Autenticación</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.amf.introduction"></a>13.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Amf</code> proporciona soporte para el <a class="ulink" href="http://en.wikipedia.org/wiki/Action_Message_Format" target="_top">Action
        Message Format</a> (<acronym class="acronym">AMF</acronym>) de Adobe, para permitir la comunicación entre
        <a class="ulink" href="http://en.wikipedia.org/wiki/Adobe_Flash_Player" target="_top">Flash
        Player</a> de Adobe y <acronym class="acronym">PHP</acronym>. En concreto, proporciona una implementación de
        servidor de puerta de enlace para gestionar las peticiones enviadas desde Flash Player al
        servidor y hacer corresponder estas peticiones con métodos de objetos y clases, así como con
        callbacks arbitrarios.
    </p>
<p>
        La <a class="ulink" href="http://download.macromedia.com/pub/labs/amf/amf3_spec_121207.pdf" target="_top">especificación
        AMF3</a> está disponible libremente, y sirve como referencia
        para saber qué tipos de mensajes pueden enviarse entre Flash Player y el
        servidor.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.acl.advanced.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.amf.server.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">12.3. Uso avanzado </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 13.2. Zend_Amf_Server</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
