<?php $title = '38.8. El adaptador UserAgent Features'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">38.8. El adaptador UserAgent Features</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.http.user-agent-device.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 38. Zend_Http</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.http.user-agent-features-browscap.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.http.user-agent-features"></a>38.8. El adaptador UserAgent Features</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features.intro"></a>38.8.1. Resumen</h3></div></div></div>
<p>
            Existe una variedad de bases de datos que definen las características y capacidades de los
            dispositivos de los navegadores. <code class="classname">Zend_Http_UserAgent</code> ofrece la posibilidad de utilizar la
            base de datos de su elección mediante una interfaz de adaptador de características.
        </p>
<p>
            Al adaptador de características se le pasa un array de solicitud que contiene la cadena User-Agent y
            cualquier otra cabecera HTTP y entorno relevante para la detección del dispositivo en
            uso. Además, si se necesita alguna configuración específica del adaptador, se
            proporcionará un array de configuración adicional. El adaptador debe entonces devolver un array de
            capacidades del dispositivo.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features.quick-start"></a>38.8.2. Inicio rápido</h3></div></div></div>
<p>
            La interfaz del adaptador es bastante sencilla, y define únicamente el método
            estático <code class="methodname">getFromRequest()</code>.
        </p>
<pre class="programlisting">
interface Zend_Http_UserAgent_Features_Adapter
{
    /**
     * Retrieve the browser's features from a given request object ($_SERVER)
     *
     * @return array
     */
    public static function getFromRequest($request, array $config);
}
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features.options"></a>38.8.3. Opciones de configuración</h3></div></div></div>
<p>
            Las opciones se definen según cada adaptador.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.user-agent-features.methods"></a>38.8.4. Métodos disponibles</h3></div></div></div>
<div class="variablelist"><dl class="variablelist">
<dt>
<a name="zend.http.user-agent-features.methods.get-from-request"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getFromRequest</span>(<span class="methodparam">array $request, array $config</span>);</code>
                </span>
</dt>
<dd><p>
                        Descompone la solicitud para devolver un array de capacidades del dispositivo.
                    </p></dd>
</dl></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.http.user-agent-device.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.http.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.http.user-agent-features-browscap.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">38.7. La interfaz UserAgent Device </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 38.9. El adaptador UserAgent Features de Browscap</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
