<?php $title = '__construct'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">__construct</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.phtml">Anterior</a> </td>
<th width="60%" align="center">42.7.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.set-options.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.standard-autoloader.methods.constructor"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>__construct — Inicializa una nueva instancia del objeto</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">__construct</span>(<span class="methodparam">$options = null</span>);</code>
</div>
<div class="refsection">
<a name="id37045"></a><h2>Constructor</h2>
<p>
                    Toma un argumento opcional <code class="varname">$options</code>. Este argumento puede ser un
                    array asociativo u objeto <code class="interfacename">Traversable</code>. Si no es
                    null, el argumento se pasa a <a class="link" href="zend.loader.standard-autoloader.methods.set-options.phtml" title="setOptions"><code class="methodname">setOptions()</code></a>.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.set-options.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">42.7. El StandardAutoloader </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> setOptions</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
