<?php $title = '64.4. Zend_Service_Amazon_Ec2'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.4. Zend_Service_Amazon_Ec2</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.amazon.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.amazon.ec2.instance.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.amazon.ec2"></a>64.4. Zend_Service_Amazon_Ec2</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.amazon.ec2.introduction"></a>64.4.1. Introducción</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Amazon_Ec2</code> proporciona una interfaz para Amazon Elastic
            Cloud Computing (EC2).
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.amazon.ec2.whatis"></a>64.4.2. ¿Qué es Amazon Ec2?</h3></div></div></div>
<p>
            Amazon EC2 es un servicio web que le permite lanzar y gestionar instancias de servidor en
            los centros de datos de Amazon usando <acronym class="acronym">API</acronym>s o herramientas y utilidades disponibles.
            Puede usar instancias de servidor de Amazon EC2 en cualquier momento, durante el tiempo que necesite, y para
            cualquier propósito legal.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.amazon.ec2.staticmethods"></a>64.4.3. Métodos estáticos</h3></div></div></div>
<p>
            Para facilitar el uso de la clase Ec2 hay dos métodos estáticos que pueden ser
            invocados desde cualquiera de los elementos de Ec2. El primer método estático es <code class="code">setKeys</code>
            que definirá sus claves de acceso de <acronym class="acronym">AWS</acronym> como claves por defecto. Cuando luego
            cree cualquier objeto nuevo, no necesitará pasar ninguna clave al constructor.
        </p>
<div class="example">
<a name="zend.service.amazon.ec2.staticmethods.setkeys"></a><p class="title"><b>Ejemplo 64.11. Ejemplo de setKeys()</b></p>
<div class="example-contents"><pre class="programlisting">
Zend_Service_Amazon_Ec2_Ebs::setKeys('aws_key','aws_secret_key');
</pre></div>
</div>
<br class="example-break"><p>
            Para establecer la región en la que está trabajando puede llamar a <code class="code">setRegion</code> para establecer
            en qué región de Amazon Ec2 está trabajando. Actualmente solo hay dos regiones disponibles,
            us-east-1 y eu-west-1. Si se pasa un valor inválido, se lanzará una excepción
            indicándolo.
        </p>
<div class="example">
<a name="zend.service.amazon.ec2.staticmethods.setregion"></a><p class="title"><b>Ejemplo 64.12. Ejemplo de setRegion()</b></p>
<div class="example-contents"><pre class="programlisting">
Zend_Service_Amazon_Ec2_Ebs::setRegion('us-east-1');
</pre></div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: Set Amazon Ec2 Region">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">
<a name="zend.service.amazon.ec2.staticmethods.setregion.note"></a>Establecer la región de Amazon Ec2</th>
</tr>
<tr><td align="left" valign="top"><p>
                Alternativamente puede establecer la región cuando cree cada clase como el tercer
                parámetro en el método constructor.
            </p></td></tr>
</table></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.amazon.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.amazon.ec2.instance.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.3. Zend_Service_Amazon </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 64.5. Zend_Service_Amazon_Ec2: Instancias</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
