<?php $title = 'Capítulo 61. Zend_Search_Lucene'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 61. Zend_Search_Lucene</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.rest.server.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.search.lucene.index-creation.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.search.lucene"></a>Capítulo 61. Zend_Search_Lucene</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.search.lucene.phtml#zend.search.lucene.overview">61.1. Resumen</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.introduction">61.1.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.documents-and-fields">61.1.2. Objetos Document y Field</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.understanding-field-types">61.1.3. Entendiendo los tipos de campo</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.html-documents">61.1.4. Documentos HTML</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.docx-documents">61.1.5. Documentos Word 2007</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.pptx-documents">61.1.6. Documentos Powerpoint 2007</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.phtml#zend.search.lucene.index-creation.xlsx-documents">61.1.7. Documentos Excel 2007</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.index-creation.phtml">61.2. Construcción de índices</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.creating">61.2.1. Creación de un índice nuevo</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.updating">61.2.2. Actualización del índice</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.document-updating">61.2.3. Actualización de documentos</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.counting">61.2.4. Obtención del tamaño del índice</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.optimization">61.2.5. Optimización del índice</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.optimization.maxbuffereddocs">61.2.5.1. Opción de auto-optimización MaxBufferedDocs</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.optimization.maxmergedocs">61.2.5.2. Opción de auto-optimización MaxMergeDocs</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.optimization.mergefactor">61.2.5.3. Opción de auto-optimización MergeFactor</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.permissions">61.2.6. Permisos</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.limitations">61.2.7. Limitaciones</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.limitations.index-size">61.2.7.1. Tamaño del índice</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.index-creation.phtml#zend.search.lucene.index-creation.limitations.filesystems">61.2.7.2. Sistemas de archivos soportados</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.searching.phtml">61.3. Búsqueda en un índice</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.query_building">61.3.1. Construcción de consultas</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.query_building.parsing">61.3.1.1. Análisis de consultas</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.results">61.3.2. Resultados de búsqueda</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.results-limiting">61.3.3. Limitación del conjunto de resultados</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.results-scoring">61.3.4. Puntuación de resultados</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.sorting">61.3.5. Ordenación de resultados de búsqueda</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.searching.phtml#zend.search.lucene.searching.highlighting">61.3.6. Resaltado de resultados de búsqueda</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.query-language.phtml">61.4. Lenguaje de consulta</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.terms">61.4.1. Términos</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.fields">61.4.2. Campos</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.wildcard">61.4.3. Comodines</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.modifiers">61.4.4. Modificadores de términos</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.range">61.4.5. Búsquedas por rango</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.fuzzy">61.4.6. Búsquedas difusas</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.matched-terms-limitations">61.4.7. Limitación de términos coincidentes</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.proximity-search">61.4.8. Búsquedas de proximidad</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boosting">61.4.9. Potenciar un término</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean">61.4.10. Operadores booleanos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.and">61.4.10.1. AND</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.or">61.4.10.2. OR</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.not">61.4.10.3. NOT</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.other-form">61.4.10.4. operadores &amp;&amp;, || y !</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.plus">61.4.10.5. +</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.minus">61.4.10.6. -</a></span></dt>
<dt><span class="sect3"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.boolean.no-operator">61.4.10.7. Sin operador</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.grouping">61.4.11. Agrupación</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.field-grouping">61.4.12. Agrupación de campos</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.escaping">61.4.13. Escapado de caracteres especiales</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.query-api.phtml">61.5. API de construcción de consultas</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.exceptions">61.5.1. Excepciones del analizador de consultas</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.term-query">61.5.2. Consulta de término</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.multiterm-query">61.5.3. Consulta multi-término</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.boolean-query">61.5.4. Consulta booleana</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.wildcard">61.5.5. Consulta con comodín</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.fuzzy">61.5.6. Consulta difusa</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.phrase-query">61.5.7. Consulta de frase</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.query-api.phtml#zend.search.lucene.queries.range">61.5.8. Consulta de rango</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.charset.phtml">61.6. Juego de caracteres</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.charset.phtml#zend.search.lucene.charset.description">61.6.1. Soporte de UTF-8 y de juegos de caracteres de un solo byte</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.charset.phtml#zend.search.lucene.charset.default_analyzer">61.6.2. Analizador de texto por defecto</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.charset.phtml#zend.search.lucene.charset.utf_analyzer">61.6.3. Analizadores de texto compatibles con UTF-8</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.extending.phtml">61.7. Extensibilidad</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.analysis">61.7.1. Análisis de texto</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.filters">61.7.2. Filtrado de tokens</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.scoring">61.7.3. Algoritmos de puntuación</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.storage">61.7.4. Contenedores de almacenamiento</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.java-lucene.phtml">61.8. Interoperación con Java Lucene</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.java-lucene.phtml#zend.search.lucene.index-creation.file-formats">61.8.1. Formatos de archivo</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.java-lucene.phtml#zend.search.lucene.index-creation.index-directory">61.8.2. Directorio del índice</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.java-lucene.phtml#zend.search.lucene.java-lucene.source-code">61.8.3. Código fuente Java</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.advanced.phtml">61.9. Avanzado</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.advanced.phtml#zend.search.lucene.advanced.format_migration">61.9.1. A partir de la versión 1.6, gestión de las transformaciones del formato de índice</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.advanced.phtml#zend.search.lucene.advanced.static">61.9.2. Uso del índice como propiedad estática</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.search.lucene.best-practice.phtml">61.10. Buenas prácticas</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.field-names">61.10.1. Nombres de campos</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.indexing-performance">61.10.2. Rendimiento de indexación</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.shutting-down">61.10.3. Indexación durante el apagado</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.unique-id">61.10.4. Recuperación de documentos por identificador único</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.memory-usage">61.10.5. Uso de memoria</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.encoding">61.10.6. Codificación</a></span></dt>
<dt><span class="sect2"><a href="zend.search.lucene.best-practice.phtml#zend.search.lucene.best-practice.maintenance">61.10.7. Mantenimiento del índice</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.search.lucene.overview"></a>61.1. Resumen</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.introduction"></a>61.1.1. Introducción</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> es un motor de búsqueda de texto de propósito general
            escrito enteramente en <acronym class="acronym">PHP</acronym> 5. Dado que almacena su índice en el
            sistema de archivos y no requiere un servidor de base de datos, puede añadir capacidades de búsqueda a
            casi cualquier sitio web basado en <acronym class="acronym">PHP</acronym>.
            <code class="classname">Zend_Search_Lucene</code> soporta las siguientes características:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Búsqueda por relevancia: los mejores resultados se devuelven primero</p></li>
<li class="listitem"><p>
                       Muchos tipos de consulta potentes: consultas de frase, consultas booleanas, consultas con comodín,
                       consultas de proximidad, consultas por rango y muchas otras.
                    </p></li>
<li class="listitem"><p>Búsqueda por campo específico (por ejemplo, título, autor, contenido)</p></li>
</ul></div>
<p>

            <code class="classname">Zend_Search_Lucene</code> se derivó del proyecto Apache Lucene.
            Las versiones del formato de índice de Lucene soportadas actualmente (a partir de ZF 1.6) son 1.4 -
            2.3. Para más información sobre Lucene, visite <a class="ulink" href="http://lucene.apache.org/java/docs/" target="_top">http://lucene.apache.org/java/docs/</a>.
        </p>
<div class="note"><table border="0" summary="Note: ">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left"></th>
</tr>
<tr><td align="left" valign="top">
<p>
                Las implementaciones anteriores de <code class="classname">Zend_Search_Lucene</code> soportan
                los formatos de índice Lucene 1.4 (1.9) - 2.1.
            </p>
<p>
                A partir de Zend Framework 1.5, cualquier índice creado usando un formato de índice anterior a 2.1 se
                actualiza automáticamente al formato Lucene 2.1 después de la
                actualización de <code class="classname">Zend_Search_Lucene</code> y no será compatible con
                las implementaciones de <code class="classname">Zend_Search_Lucene</code> incluidas en Zend
                Framework 1.0.x.
            </p>
</td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.documents-and-fields"></a>61.1.2. Objetos Document y Field</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> opera con documentos como objetos atómicos para
            la indexación. Un documento se divide en campos con nombre, y los campos tienen contenido que puede ser
            buscado.
        </p>
<p>
            Un documento está representado por la clase <code class="classname">Zend_Search_Lucene_Document</code>,
            y los objetos de esta clase contienen instancias de
            <code class="classname">Zend_Search_Lucene_Field</code> que representan los campos del
            documento.
        </p>
<p>
            Es importante señalar que se puede añadir cualquier información al índice.
            La información o los metadatos específicos de la aplicación pueden almacenarse en los campos
            del documento y recuperarse posteriormente junto con el documento durante la búsqueda.
        </p>
<p>
            Es responsabilidad de su aplicación controlar el indexador.
            Esto significa que los datos pueden indexarse desde cualquier fuente
            a la que su aplicación tenga acceso. Por ejemplo, esto podría ser el
            sistema de archivos, una base de datos, un formulario <acronym class="acronym">HTML</acronym>, etc.
        </p>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Field</code> proporciona varios métodos estáticos para
            crear campos con diferentes características:
        </p>
<pre class="programlisting">
$doc = new Zend_Search_Lucene_Document();

// Field is not tokenized, but is indexed and stored within the index.
// Stored fields can be retrived from the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::Keyword('doctype',
                                                 'autogenerated'));

// Field is not tokenized nor indexed, but is stored in the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed('created',
                                                   time()));

// Binary String valued Field that is not tokenized nor indexed,
// but is stored in the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::Binary('icon',
                                                $iconData));

// Field is tokenized and indexed, and is stored in the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::Text('annotation',
                                              'Document annotation text'));

// Field is tokenized and indexed, but is not stored in the index.
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('contents',
                                                  'My document content'));
</pre>
<p>
            Cada uno de estos métodos (excluyendo el método
            <code class="methodname">Zend_Search_Lucene_Field::Binary()</code>) tiene un parámetro opcional
            <code class="varname">$encoding</code> para especificar la codificación de los datos de entrada.
        </p>
<p>
            La codificación puede variar entre distintos documentos, así como entre distintos campos dentro de un
            mismo documento:
        </p>
<pre class="programlisting">
$doc = new Zend_Search_Lucene_Document();
$doc-&gt;addField(Zend_Search_Lucene_Field::Text('title',
                                              $title,
                                              'iso-8859-1'));
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('contents',
                                                  $contents,
                                                  'utf-8'));
</pre>
<p>
            Si se omite el parámetro de codificación, se utiliza la configuración regional (locale) actual en el momento del procesamiento.
            Por ejemplo:
        </p>
<pre class="programlisting">
setlocale(LC_ALL, 'de_DE.iso-8859-1');
...
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('contents', $contents));
</pre>
<p>
            Los campos siempre se almacenan y se devuelven del índice en codificación UTF-8. Cualquier conversión
            necesaria a UTF-8 ocurre automáticamente.
        </p>
<p>
            Los analizadores de texto (<a class="link" href="zend.search.lucene.extending.phtml#zend.search.lucene.extending.analysis" title="61.7.1. Text Analysis">vea más abajo</a>)
            también pueden convertir el texto a otras codificaciones. De hecho, el analizador por defecto convierte
            el texto a la codificación 'ASCII//TRANSLIT'. Tenga cuidado, sin embargo; esta traducción puede depender de
            la configuración regional actual.
        </p>
<p>
            Los nombres de los campos se definen a su criterio en el método
            <code class="methodname">addField()</code>.
        </p>
<p>
            Java Lucene utiliza el campo 'contents' como campo de búsqueda por defecto.
            <code class="classname">Zend_Search_Lucene</code> busca en todos los campos por defecto, pero
            el comportamiento es configurable. Vea el capítulo <a class="link" href="zend.search.lucene.query-language.phtml#zend.search.lucene.query-language.fields" title="61.4.2. Fields">"Campo de búsqueda por defecto"</a>
            para más detalles.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.understanding-field-types"></a>61.1.3. Entendiendo los tipos de campo</h3></div></div></div>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    Los campos <code class="code">Keyword</code> se almacenan e indexan, lo que significa que pueden
                    buscarse y también mostrarse en los resultados de búsqueda. No se dividen en
                    palabras separadas mediante tokenización. Los campos de base de datos enumerados suelen traducirse
                    bien a campos Keyword en <code class="classname">Zend_Search_Lucene</code>.
                </p></li>
<li class="listitem"><p>
                    Los campos <code class="code">UnIndexed</code> no son buscables, pero se devuelven con los
                    resultados de búsqueda. Las marcas de tiempo de bases de datos, claves primarias, rutas del sistema
                    de archivos y otros identificadores externos son buenos candidatos para campos UnIndexed.
                </p></li>
<li class="listitem"><p>
                    Los campos <code class="code">Binary</code> no se tokenizan ni se indexan, pero se almacenan para
                    su recuperación junto con los resultados de búsqueda. Pueden usarse para almacenar cualquier dato
                    codificado como una cadena binaria, como un icono de imagen.
                </p></li>
<li class="listitem"><p>
                    Los campos <code class="code">Text</code> se almacenan, indexan y tokenizan. Los campos Text son
                    apropiados para almacenar información como asuntos y títulos que necesitan ser
                    buscables además de devueltos con los resultados de búsqueda.
                </p></li>
<li class="listitem">
<p>
                    Los campos <code class="code">UnStored</code> se tokenizan e indexan, pero no se almacenan en el
                    índice. Las grandes cantidades de texto se indexan mejor usando este tipo de campo. Almacenar
                    datos crea un índice más grande en disco, así que si necesita buscar pero no volver a mostrar
                    los datos, use un campo UnStored. Los campos UnStored son prácticos cuando se usa un
                    índice de <code class="classname">Zend_Search_Lucene</code> en combinación con una base de datos
                    relacional. Puede indexar campos de datos grandes con campos UnStored para su búsqueda,
                    y recuperarlos de su base de datos relacional usando un campo separado como
                    identificador.
               </p>
<div class="table">
<a name="zend.search.lucene.index-creation.understanding-field-types.table"></a><p class="title"><b>Tabla 61.1. Tipos de Zend_Search_Lucene_Field</b></p>
<div class="table-contents"><table class="table" summary="Zend_Search_Lucene_Field Types" border="1">
<colgroup>
<col>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Tipo de campo</th>
<th>Almacenado</th>
<th>Indexado</th>
<th>Tokenizado</th>
<th>Binario</th>
</tr></thead>
<tbody>
<tr>
<td>Keyword</td>
<td>Sí</td>
<td>Sí</td>
<td>No</td>
<td>No</td>
</tr>
<tr>
<td>UnIndexed</td>
<td>Sí</td>
<td>No</td>
<td>No</td>
<td>No</td>
</tr>
<tr>
<td>Binary</td>
<td>Sí</td>
<td>No</td>
<td>No</td>
<td>Sí</td>
</tr>
<tr>
<td>Text</td>
<td>Sí</td>
<td>Sí</td>
<td>Sí</td>
<td>No</td>
</tr>
<tr>
<td>UnStored</td>
<td>No</td>
<td>Sí</td>
<td>Sí</td>
<td>No</td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.html-documents"></a>61.1.4. Documentos HTML</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> ofrece una funcionalidad de análisis de <acronym class="acronym">HTML</acronym>. Los documentos pueden
            crearse directamente a partir de un archivo o una cadena <acronym class="acronym">HTML</acronym>:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Html::loadHTMLFile($filename);
$index-&gt;addDocument($doc);
...
$doc = Zend_Search_Lucene_Document_Html::loadHTML($htmlString);
$index-&gt;addDocument($doc);
</pre>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Document_Html</code> utiliza los métodos
            <code class="methodname">DOMDocument::loadHTML()</code> y
            <code class="methodname">DOMDocument::loadHTMLFile()</code> para analizar el
            <acronym class="acronym">HTML</acronym> de origen, por lo que no necesita que el <acronym class="acronym">HTML</acronym> esté bien formado ni
            que sea <acronym class="acronym">XHTML</acronym>. Por otro lado, es sensible a la codificación
            especificada por la etiqueta de cabecera "meta http-equiv".
        </p>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Document_Html</code> reconoce el título, el
            cuerpo y las etiquetas meta de cabecera del documento.
        </p>
<p>
            El campo 'title' es en realidad el valor de /html/head/title. Se almacena en el índice,
            se tokeniza y está disponible para la búsqueda.
        </p>
<p>
            El campo 'body' es el contenido real del cuerpo del archivo o cadena <acronym class="acronym">HTML</acronym>. No incluye
            scripts, comentarios ni atributos.
        </p>
<p>
            Los métodos <code class="methodname">loadHTML()</code> y <code class="methodname">loadHTMLFile()</code>
            de la clase <code class="classname">Zend_Search_Lucene_Document_Html</code> también tienen un
            segundo argumento opcional. Si se establece en <code class="constant">TRUE</code>, entonces el contenido del cuerpo también se
            almacena en el índice y puede recuperarse del mismo. Por defecto, el cuerpo se
            tokeniza e indexa, pero no se almacena.
        </p>
<p>
            El tercer parámetro de los métodos <code class="methodname">loadHTML()</code> y
            <code class="methodname">loadHTMLFile()</code> especifica opcionalmente la codificación del
            documento <acronym class="acronym">HTML</acronym> de origen. Se utiliza si la codificación no se especifica mediante
            la etiqueta meta Content-type HTTP-EQUIV.
        </p>
<p>
            Otras etiquetas meta de cabecera del documento producen campos adicionales del documento. El campo 'name' se
            toma del atributo 'name', y el atributo 'content' rellena el campo 'value'.
            Ambos se tokenizan, indexan y almacenan, de modo que los documentos pueden buscarse por sus etiquetas meta
            (por ejemplo, por palabras clave).
        </p>
<p>
            Los documentos analizados pueden ser aumentados por el programador con cualquier otro campo:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Html::loadHTML($htmlString);
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed('created',
                                                   time()));
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed('updated',
                                                   time()));
$doc-&gt;addField(Zend_Search_Lucene_Field::Text('annotation',
                                              'Document annotation text'));
$index-&gt;addDocument($doc);
</pre>
<p>
            Los enlaces del documento no se incluyen en el documento generado, pero pueden recuperarse con
            los métodos <code class="methodname">Zend_Search_Lucene_Document_Html::getLinks()</code> y
            <code class="methodname">Zend_Search_Lucene_Document_Html::getHeaderLinks()</code>:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Html::loadHTML($htmlString);
$linksArray = $doc-&gt;getLinks();
$headerLinksArray = $doc-&gt;getHeaderLinks();
</pre>
<p>
            A partir de Zend Framework 1.6 también es posible excluir enlaces con el
            atributo <code class="code">rel</code> establecido a <code class="code">'nofollow'</code>. Use
            <code class="methodname">Zend_Search_Lucene_Document_Html::setExcludeNoFollowLinks($true)</code>
            para activar esta opción.
        </p>
<p>
            El método <code class="methodname">Zend_Search_Lucene_Document_Html::getExcludeNoFollowLinks()</code>
            devuelve el estado actual del indicador "Excluir enlaces nofollow".
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.docx-documents"></a>61.1.5. Documentos Word 2007</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> ofrece una funcionalidad de análisis de Word 2007. Los documentos
            pueden crearse directamente a partir de un archivo Word 2007:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Docx::loadDocxFile($filename);
$index-&gt;addDocument($doc);
</pre>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Document_Docx</code> utiliza la clase
            <code class="code">ZipArchive</code> y los métodos de <code class="code">simplexml</code> para analizar el documento
            de origen. Si la clase <code class="code">ZipArchive</code> (del módulo php_zip) no está disponible,
            <code class="classname">Zend_Search_Lucene_Document_Docx</code> tampoco estará disponible
            para su uso con Zend Framework.
        </p>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Document_Docx</code> reconoce los metadatos y el
            texto del documento. Los metadatos consisten, dependiendo del contenido del documento, en el nombre de archivo,
            título, asunto, creador, palabras clave, descripción, lastModifiedBy, revisión, fecha de modificación,
            fecha de creación.
        </p>
<p>
            El campo 'filename' es el nombre real del archivo Word 2007.
        </p>
<p>
            El campo 'title' es el título real del documento.
        </p>
<p>
            El campo 'subject' es el asunto real del documento.
        </p>
<p>
            El campo 'creator' es el creador real del documento.
        </p>
<p>
            El campo 'keywords' contiene las palabras clave reales del documento.
        </p>
<p>
            El campo 'description' es la descripción real del documento.
        </p>
<p>
            El campo 'lastModifiedBy' es el nombre de usuario que modificó el documento por última vez.
        </p>
<p>
            El campo 'revision' es el número de revisión real del documento.
        </p>
<p>
            El campo 'modified' es la fecha/hora real de la última modificación del documento.
        </p>
<p>
            El campo 'created' es la fecha/hora real de creación del documento.
        </p>
<p>
            El campo 'body' es el contenido real del cuerpo del documento Word 2007. Solo incluye
            texto normal; los comentarios y las revisiones no se incluyen.
        </p>
<p>
            El método <code class="methodname">loadDocxFile()</code> de la clase
            <code class="classname">Zend_Search_Lucene_Document_Docx</code> también tiene un
            segundo argumento opcional. Si se establece en <code class="constant">TRUE</code>, entonces el contenido del cuerpo también se almacena
            en el índice y puede recuperarse del mismo. Por defecto, el cuerpo se tokeniza e
            indexa, pero no se almacena.
        </p>
<p>
            Los documentos analizados pueden ser aumentados por el programador con cualquier otro campo:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Docx::loadDocxFile($filename);
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed(
    'indexTime',
    time())
);
$doc-&gt;addField(Zend_Search_Lucene_Field::Text(
    'annotation',
    'Document annotation text')
);
$index-&gt;addDocument($doc);
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.pptx-documents"></a>61.1.6. Documentos Powerpoint 2007</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> ofrece una funcionalidad de análisis de Powerpoint 2007.
            Los documentos pueden crearse directamente a partir de un archivo Powerpoint 2007:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Pptx::loadPptxFile($filename);
$index-&gt;addDocument($doc);
</pre>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Document_Pptx</code> utiliza la clase
            <code class="code">ZipArchive</code> y los métodos de <code class="code">simplexml</code> para analizar el documento
            de origen. Si la clase <code class="code">ZipArchive</code> (del módulo php_zip) no está disponible,
            <code class="classname">Zend_Search_Lucene_Document_Pptx</code> tampoco estará disponible
            para su uso con Zend Framework.
        </p>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Document_Pptx</code> reconoce los metadatos y el
            texto del documento. Los metadatos consisten, dependiendo del contenido del documento, en el nombre de archivo,
            título, asunto, creador, palabras clave, descripción, lastModifiedBy, revisión, fecha de modificación,
            fecha de creación.
        </p>
<p>
            El campo 'filename' es el nombre real del archivo Powerpoint 2007.
        </p>
<p>
            El campo 'title' es el título real del documento.
        </p>
<p>
            El campo 'subject' es el asunto real del documento.
        </p>
<p>
            El campo 'creator' es el creador real del documento.
        </p>
<p>
            El campo 'keywords' contiene las palabras clave reales del documento.
        </p>
<p>
            El campo 'description' es la descripción real del documento.
        </p>
<p>
            El campo 'lastModifiedBy' es el nombre de usuario que modificó el documento por última vez.
        </p>
<p>
            El campo 'revision' es el número de revisión real del documento.
        </p>
<p>
            El campo 'modified' es la fecha/hora real de la última modificación del documento.
        </p>
<p>
            El campo 'created' es la fecha/hora real de creación del documento.
        </p>
<p>
            El campo 'body' es el contenido real de todas las diapositivas y las notas de diapositiva del documento
            Powerpoint 2007.
        </p>
<p>
            El método <code class="methodname">loadPptxFile()</code> de la clase
            <code class="classname">Zend_Search_Lucene_Document_Pptx</code> también tiene un
            segundo argumento opcional. Si se establece en <code class="constant">TRUE</code>, entonces el contenido del cuerpo también se almacena
            en el índice y puede recuperarse del mismo. Por defecto, el cuerpo se tokeniza e
            indexa, pero no se almacena.
        </p>
<p>
            Los documentos analizados pueden ser aumentados por el programador con cualquier otro campo:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Pptx::loadPptxFile($filename);
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed(
    'indexTime',
    time()));
$doc-&gt;addField(Zend_Search_Lucene_Field::Text(
    'annotation',
    'Document annotation text'));
$index-&gt;addDocument($doc);
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.search.lucene.index-creation.xlsx-documents"></a>61.1.7. Documentos Excel 2007</h3></div></div></div>
<p>
            <code class="classname">Zend_Search_Lucene</code> ofrece una funcionalidad de análisis de Excel 2007. Los documentos
            pueden crearse directamente a partir de un archivo Excel 2007:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Xlsx::loadXlsxFile($filename);
$index-&gt;addDocument($doc);
</pre>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Document_Xlsx</code> utiliza la clase
            <code class="code">ZipArchive</code> y los métodos de <code class="code">simplexml</code> para analizar el documento
            de origen. Si la clase <code class="code">ZipArchive</code> (del módulo php_zip) no está disponible,
            <code class="classname">Zend_Search_Lucene_Document_Xlsx</code> tampoco estará disponible
            para su uso con Zend Framework.
        </p>
<p>
            La clase <code class="classname">Zend_Search_Lucene_Document_Xlsx</code> reconoce los metadatos y el
            texto del documento. Los metadatos consisten, dependiendo del contenido del documento, en el nombre de archivo,
            título, asunto, creador, palabras clave, descripción, lastModifiedBy, revisión, fecha de modificación,
            fecha de creación.
        </p>
<p>
            El campo 'filename' es el nombre real del archivo Excel 2007.
        </p>
<p>
            El campo 'title' es el título real del documento.
        </p>
<p>
            El campo 'subject' es el asunto real del documento.
        </p>
<p>
            El campo 'creator' es el creador real del documento.
        </p>
<p>
            El campo 'keywords' contiene las palabras clave reales del documento.
        </p>
<p>
            El campo 'description' es la descripción real del documento.
        </p>
<p>
            El campo 'lastModifiedBy' es el nombre de usuario que modificó el documento por última vez.
        </p>
<p>
            El campo 'revision' es el número de revisión real del documento.
        </p>
<p>
            El campo 'modified' es la fecha/hora real de la última modificación del documento.
        </p>
<p>
            El campo 'created' es la fecha/hora real de creación del documento.
        </p>
<p>
            El campo 'body' es el contenido real de todas las celdas de todas las hojas de cálculo del documento Excel 2007.
        </p>
<p>
            El método <code class="methodname">loadXlsxFile()</code> de la clase
            <code class="classname">Zend_Search_Lucene_Document_Xlsx</code> también tiene un
            segundo argumento opcional. Si se establece en <code class="constant">TRUE</code>, entonces el contenido del cuerpo también se almacena
            en el índice y puede recuperarse del mismo. Por defecto, el cuerpo se tokeniza e
            indexa, pero no se almacena.
        </p>
<p>
            Los documentos analizados pueden ser aumentados por el programador con cualquier otro campo:
        </p>
<pre class="programlisting">
$doc = Zend_Search_Lucene_Document_Xlsx::loadXlsxFile($filename);
$doc-&gt;addField(Zend_Search_Lucene_Field::UnIndexed(
    'indexTime',
    time()));
$doc-&gt;addField(Zend_Search_Lucene_Field::Text(
    'annotation',
    'Document annotation text'));
$index-&gt;addDocument($doc);
</pre>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.rest.server.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.search.lucene.index-creation.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">60.3. Zend_Rest_Server </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 61.2. Construcción de índices</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
