<?php $title = '36.3. Creación de elementos de formulario usando Zend_Form_Element'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">36.3. Creación de elementos de formulario usando Zend_Form_Element</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.form.quickstart.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 36. Zend_Form</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.form.forms.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.form.elements"></a>36.3. Creación de elementos de formulario usando Zend_Form_Element</h2></div></div></div>
<p>
        Un formulario está compuesto por elementos que típicamente corresponden a entradas de
        formulario <acronym class="acronym">HTML</acronym>. <code class="classname">Zend_Form_Element</code> encapsula elementos
        de formulario individuales, con las siguientes áreas de responsabilidad:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>
                validación (¿son válidos los datos enviados?)
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; "><li class="listitem"><p>captura de los códigos y mensajes de error de validación</p></li></ul></div>
</li>
<li class="listitem"><p>
                filtrado (¿cómo se escapa o normaliza el elemento antes de
                la validación y/o para la salida?)
            </p></li>
<li class="listitem"><p>renderizado (¿cómo se muestra el elemento?)</p></li>
<li class="listitem"><p>metadatos y atributos (¿qué información califica adicionalmente al elemento?)</p></li>
</ul></div>
<p>
        La clase base, <code class="classname">Zend_Form_Element</code>, tiene valores por defecto
        razonables para muchos casos, pero es mejor extender la clase para elementos
        de propósito especial de uso común. Además, Zend Framework se distribuye con un
        número de elementos <acronym class="acronym">XHTML</acronym> estándar; puede leer sobre ellos <a class="link" href="zend.form.standardElements.phtml" title="36.6. Standard Form Elements Shipped With Zend Framework">en el capítulo de
            Elementos Estándar</a>.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.loaders"></a>36.3.1. Cargadores de plugins</h3></div></div></div>
<p>
            <code class="classname">Zend_Form_Element</code> hace uso de <a class="link" href="zend.loader.pluginloader.phtml" title="42.4. Loading Plugins">Zend_Loader_PluginLoader</a>
            para permitir a los desarrolladores especificar ubicaciones de validadores,
            filtros y decoradores alternativos. Cada uno tiene su propio cargador de plugins
            asociado, y se usan accesores generales para recuperar y modificar
            cada uno.
        </p>
<p>
            Los siguientes tipos de cargadores se usan con los distintos métodos del cargador
            de plugins: 'validate', 'filter' y 'decorator'. Los nombres de tipo distinguen
            entre mayúsculas y minúsculas.
        </p>
<p>
            Los métodos usados para interactuar con los cargadores de plugins son los siguientes:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="methodname">setPluginLoader($loader, $type)</code>:
                    <code class="varname">$loader</code> es el propio objeto del cargador de plugins, mientras
                    <code class="varname">$type</code> es uno de los tipos especificados arriba. Esto
                    establece el cargador de plugins para el tipo dado con el nuevo
                    objeto cargador especificado.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">getPluginLoader($type)</code>: recupera el cargador
                    de plugins asociado con <code class="varname">$type</code>.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addPrefixPath($prefix, $path, $type = null)</code>: añade
                    una asociación prefijo/ruta al cargador especificado por
                    <code class="varname">$type</code>. Si <code class="varname">$type</code> es
                    <code class="constant">NULL</code>, intentará añadir la ruta a todos los cargadores, añadiendo
                    "_Validate", "_Filter" y "_Decorator" al prefijo; y
                    añadiendo "Validate/", "Filter/" y
                    "Decorator/" a la ruta. Si tiene todas sus clases de elementos de formulario
                    adicionales bajo una jerarquía común, este es un método de conveniencia para
                    establecer el prefijo base para ellas.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addPrefixPaths(array $spec)</code>: le permite añadir
                    muchas rutas a la vez a uno o más cargadores de plugins. Espera
                    que cada elemento del array sea un array con las claves 'path', 'prefix',
                    y 'type'.
                </p></li>
</ul></div>
<p>
            Los validadores, filtros y decoradores personalizados son una forma fácil de compartir
            funcionalidad entre formularios y de encapsular funcionalidad personalizada.
        </p>
<div class="example">
<a name="zend.form.elements.loaders.customLabel"></a><p class="title"><b>Ejemplo 36.1. Etiqueta personalizada</b></p>
<div class="example-contents">
<p>
                Un caso de uso común para los plugins es proporcionar reemplazos para
                clases estándar. Por ejemplo, si desea proporcionar una
                implementación diferente del decorador 'Label' -- por
                ejemplo, para añadir siempre dos puntos al final -- puede crear su propio
                decorador 'Label' con su propio prefijo de clase, y luego añadirlo a
                su ruta de prefijo.
            </p>
<p>
                Empecemos con un decorador Label personalizado. Le daremos el
                prefijo de clase "My_Decorator", y la clase en sí estará en el
                archivo "My/Decorator/Label.php".
            </p>
<pre class="programlisting">
class My_Decorator_Label extends Zend_Form_Decorator_Abstract
{
    protected $_placement = 'PREPEND';

    public function render($content)
    {
        if (null === ($element = $this-&gt;getElement())) {
            return $content;
        }
        if (!method_exists($element, 'getLabel')) {
            return $content;
        }

        $label = $element-&gt;getLabel() . ':';

        if (null === ($view = $element-&gt;getView())) {
            return $this-&gt;renderLabel($content, $label);
        }

        $label = $view-&gt;formLabel($element-&gt;getName(), $label);

        return $this-&gt;renderLabel($content, $label);
    }

    public function renderLabel($content, $label)
    {
        $placement = $this-&gt;getPlacement();
        $separator = $this-&gt;getSeparator();

        switch ($placement) {
            case 'APPEND':
                return $content . $separator . $label;
            case 'PREPEND':
            default:
                return $label . $separator . $content;
        }
    }
}
</pre>
<p>
                Ahora podemos indicarle al elemento que use esta ruta de plugin cuando busque
                decoradores:
            </p>
<pre class="programlisting">
$element-&gt;addPrefixPath('My_Decorator', 'My/Decorator/', 'decorator');
</pre>
<p>
                Alternativamente, podemos hacer eso a nivel de formulario para asegurar que todos los
                decoradores usen esta ruta:
            </p>
<pre class="programlisting">
$form-&gt;addElementPrefixPath('My_Decorator', 'My/Decorator/', 'decorator');
</pre>
<p>
                Después de añadirla como en el ejemplo anterior, la ruta 'My/Decorator/' se buscará
                primero para ver si el decorador existe allí cuando añada un decorador. Como resultado,
                'My_Decorator_Label' se usará ahora cuando se solicite el decorador 'Label'.
            </p>
</div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.filters"></a>36.3.2. Filtros</h3></div></div></div>
<p>
            A menudo es útil y/o necesario realizar cierta normalización de la
            entrada antes de la validación. Por ejemplo, puede que desee eliminar todo el
            <acronym class="acronym">HTML</acronym>, pero ejecutar sus validaciones sobre lo que queda para asegurar que el
            envío sea válido. O puede que desee recortar los espacios vacíos que rodean la entrada para que un
            validador StringLength use la longitud correcta de la entrada sin contar los espacios en blanco
            iniciales o finales. Estas operaciones se pueden realizar usando
            <code class="classname">Zend_Filter</code>. <code class="classname">Zend_Form_Element</code> tiene soporte
            para cadenas de filtros, permitiéndole especificar múltiples filtros secuenciales. El filtrado
            ocurre tanto durante la validación como cuando recupera el valor del elemento mediante
            <code class="methodname">getValue()</code>:
        </p>
<pre class="programlisting">
$filtered = $element-&gt;getValue();
</pre>
<p>
            Los filtros pueden añadirse a la cadena de dos maneras:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    pasando una instancia concreta de filtro
                </p></li>
<li class="listitem"><p>
                    proporcionando un nombre corto de filtro
                </p></li>
</ul></div>
<p>
            Veamos algunos ejemplos:
        </p>
<pre class="programlisting">
// Instancia concreta de filtro:
$element-&gt;addFilter(new Zend_Filter_Alnum());

// Nombre corto de filtro:
$element-&gt;addFilter('Alnum');
$element-&gt;addFilter('alnum');
</pre>
<p>
            Los nombres cortos son típicamente el nombre del filtro menos el prefijo. En el
            caso por defecto, esto significará menos el prefijo 'Zend_Filter_'.
            La primera letra puede estar en mayúscula o minúscula.
        </p>
<div class="note"><table border="0" summary="Note: Using Custom Filter Classes">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Uso de clases de filtro personalizadas</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Si tiene su propio conjunto de clases de filtro, puede indicarle a
                <code class="classname">Zend_Form_Element</code> sobre estas usando
                <code class="methodname">addPrefixPath()</code>. Por ejemplo, si tiene
                filtros bajo el prefijo 'My_Filter', puede indicarle a
                <code class="classname">Zend_Form_Element</code> sobre esto de la siguiente manera:
            </p>
<pre class="programlisting">
$element-&gt;addPrefixPath('My_Filter', 'My/Filter/', 'filter');
</pre>
<p>
                (Recuerde que el tercer argumento indica sobre qué cargador de plugins
                se realiza la acción.)
            </p>
</td></tr>
</table></div>
<p>
            Si en algún momento necesita el valor sin filtrar, use el
            método <code class="methodname">getUnfilteredValue()</code>:
        </p>
<pre class="programlisting">
$unfiltered = $element-&gt;getUnfilteredValue();
</pre>
<p>
            Para más información sobre filtros, vea la <a class="link" href="zend.filter.phtml#zend.filter.introduction" title="35.1. Introduction">documentación de
                Zend_Filter</a>.
        </p>
<p>
            Los métodos asociados con los filtros incluyen:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="methodname">addFilter($nameOfFilter, array $options = null)</code>
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addFilters(array $filters)</code>
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setFilters(array $filters)</code> (sobrescribe todos los filtros)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">getFilter($name)</code> (recupera un objeto filtro por nombre)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">getFilters()</code> (recupera todos los filtros)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">removeFilter($name)</code> (elimina el filtro por nombre)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">clearFilters()</code> (elimina todos los filtros)
                </p></li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.validators"></a>36.3.3. Validadores</h3></div></div></div>
<p>
            Si se suscribe al mantra de seguridad de "filtrar la entrada, escapar
            la salida", debería usar un validador para filtrar la entrada enviada con su formulario.
            En <code class="classname">Zend_Form</code>, cada elemento incluye su propia cadena de
            validadores, formada por validadores <code class="classname">Zend_Validate_*</code>.
        </p>
<p>
            Los validadores pueden añadirse a la cadena de dos maneras:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    pasando una instancia concreta de validador
                </p></li>
<li class="listitem"><p>
                    proporcionando un nombre corto de validador
                </p></li>
</ul></div>
<p>
            Veamos algunos ejemplos:
        </p>
<pre class="programlisting">
// Instancia concreta de validador:
$element-&gt;addValidator(new Zend_Validate_Alnum());

// Nombre corto de validador:
$element-&gt;addValidator('Alnum');
$element-&gt;addValidator('alnum');
</pre>
<p>
            Los nombres cortos son típicamente el nombre del validador menos el prefijo. En
            el caso por defecto, esto significará menos el prefijo 'Zend_Validate_'.
            Al igual que con los filtros, la primera letra puede estar en mayúscula o minúscula.
        </p>
<div class="note"><table border="0" summary="Note: Using Custom Validator Classes">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Uso de clases de validador personalizadas</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Si tiene su propio conjunto de clases de validador, puede indicarle a
                <code class="classname">Zend_Form_Element</code> sobre estas usando
                <code class="methodname">addPrefixPath()</code>. Por ejemplo, si tiene
                validadores bajo el prefijo 'My_Validator', puede indicarle a
                <code class="classname">Zend_Form_Element</code> sobre esto de la siguiente manera:
            </p>
<pre class="programlisting">
$element-&gt;addPrefixPath('My_Validator', 'My/Validator/', 'validate');
</pre>
<p>
                (Recuerde que el tercer argumento indica sobre qué cargador de plugins
                se realiza la acción.)
            </p>
</td></tr>
</table></div>
<p>
            Si fallar una validación particular debería impedir que se disparen validadores
            posteriores, pase el booleano <code class="constant">TRUE</code> como segundo parámetro:
        </p>
<pre class="programlisting">
$element-&gt;addValidator('alnum', true);
</pre>
<p>
            Si está usando un nombre de cadena para añadir un validador, y la
            clase del validador acepta argumentos en el constructor, puede pasar
            estos como tercer parámetro de <code class="methodname">addValidator()</code> como un
            array:
        </p>
<pre class="programlisting">
$element-&gt;addValidator('StringLength', false, array(6, 20));
</pre>
<p>
            Los argumentos pasados de esta manera deben estar en el orden en que
            se definen en el constructor. El ejemplo anterior instanciará
            la clase <code class="classname">Zend_Validate_StringLenth</code> con sus
            parámetros <code class="varname">$min</code> y <code class="varname">$max</code>:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_StringLength(6, 20);
</pre>
<div class="note"><table border="0" summary="Note: Providing Custom Validator Error Messages">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Proporcionar mensajes de error de validador personalizados</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Algunos desarrolladores pueden desear proporcionar mensajes de error personalizados para un
                validador. El argumento <code class="varname">$options</code> del método
                <code class="methodname">Zend_Form_Element::addValidator()</code> le permite hacer
                esto proporcionando la clave 'messages' y asociándola a un array de pares clave/valor
                para establecer las plantillas de mensajes. Necesitará conocer los
                códigos de error de los distintos tipos de error de validación para el
                validador en particular.
            </p>
<p>
                Una mejor opción es usar un <code class="classname">Zend_Translate_Adapter</code>
                con su formulario. Los códigos de error se pasan automáticamente al
                adaptador mediante el decorador Errors por defecto; entonces puede especificar
                sus propias cadenas de mensajes de error configurando traducciones para
                los distintos códigos de error de sus validadores.
            </p>
</td></tr>
</table></div>
<p>
            También puede establecer muchos validadores a la vez, usando
            <code class="methodname">addValidators()</code>. El uso básico es pasar un array
            de arrays, con cada array conteniendo de 1 a 3 valores, coincidiendo con
            el constructor de <code class="methodname">addValidator()</code>:
        </p>
<pre class="programlisting">
$element-&gt;addValidators(array(
    array('NotEmpty', true),
    array('alnum'),
    array('stringLength', false, array(6, 20)),
));
</pre>
<p>
            Si desea ser más detallado o explícito, puede usar las claves del array
            'validator', 'breakChainOnFailure' y 'options':
        </p>
<pre class="programlisting">
$element-&gt;addValidators(array(
    array(
        'validator'           =&gt; 'NotEmpty',
        'breakChainOnFailure' =&gt; true),
    array('validator' =&gt; 'alnum'),
    array(
        'validator' =&gt; 'stringLength',
        'options'   =&gt; array(6, 20)),
));
</pre>
<p>
            Este uso es bueno para ilustrar cómo podría entonces configurar
            validadores en un archivo de configuración:
        </p>
<pre class="programlisting">
element.validators.notempty.validator = "NotEmpty"
element.validators.notempty.breakChainOnFailure = true
element.validators.alnum.validator = "Alnum"
element.validators.strlen.validator = "StringLength"
element.validators.strlen.options.min = 6
element.validators.strlen.options.max = 20
</pre>
<p>
            Note que cada elemento tiene una clave, la necesite o no; esto
            es una limitación de usar archivos de configuración -- pero también ayuda a
            hacer explícito cuáles son los argumentos. Solo recuerde que cualquier
            opción de validador debe especificarse en orden.
        </p>
<p>
            Para validar un elemento, pase el valor a
            <code class="methodname">isValid()</code>:
        </p>
<pre class="programlisting">
if ($element-&gt;isValid($value)) {
    // válido
} else {
    // inválido
}
</pre>
<div class="note"><table border="0" summary="Note: Validation Operates On Filtered Values">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">La validación opera sobre valores filtrados</th>
</tr>
<tr><td align="left" valign="top"><p>
                <code class="methodname">Zend_Form_Element::isValid()</code> filtra los valores a través
                de la cadena de filtros provista antes de la validación. Vea <a class="link" href="zend.form.elements.phtml#zend.form.elements.filters" title="36.3.2. Filters">la sección de
                    Filtros</a> para más información.
            </p></td></tr>
</table></div>
<div class="note"><table border="0" summary="Note: Validation Context">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Contexto de validación</th>
</tr>
<tr><td align="left" valign="top">
<p>
                <code class="methodname">Zend_Form_Element::isValid()</code> admite un
                argumento adicional, <code class="varname">$context</code>.
                <code class="methodname">Zend_Form::isValid()</code> pasa el array completo de
                datos que se están procesando a <code class="varname">$context</code> al validar un
                formulario, y <code class="methodname">Zend_Form_Element::isValid()</code>, a su vez,
                lo pasa a cada validador. Esto significa que puede escribir
                validadores que sean conscientes de los datos pasados a otros elementos
                del formulario. Como ejemplo, considere un formulario de registro estándar
                que tiene campos tanto para la contraseña como para la confirmación de contraseña;
                una validación sería que ambos campos coincidan. Un validador de este tipo
                podría verse como el siguiente:
            </p>
<pre class="programlisting">
class My_Validate_PasswordConfirmation extends Zend_Validate_Abstract
{
    const NOT_MATCH = 'notMatch';

    protected $_messageTemplates = array(
        self::NOT_MATCH =&gt; 'Password confirmation does not match'
    );

    public function isValid($value, $context = null)
    {
        $value = (string) $value;
        $this-&gt;_setValue($value);

        if (is_array($context)) {
            if (isset($context['password_confirm'])
                &amp;&amp; ($value == $context['password_confirm']))
            {
                return true;
            }
        } elseif (is_string($context) &amp;&amp; ($value == $context)) {
            return true;
        }

        $this-&gt;_error(self::NOT_MATCH);
        return false;
    }
}
</pre>
</td></tr>
</table></div>
<p>
            Los validadores se procesan en orden. Cada validador se procesa,
            a menos que un validador creado con un valor <code class="constant">TRUE</code>
            de <code class="varname">$breakChainOnFailure</code> falle su validación. Asegúrese
            de especificar sus validadores en un orden razonable.
        </p>
<p>
            Después de una validación fallida, puede recuperar los códigos de error y
            los mensajes de la cadena de validadores:
        </p>
<pre class="programlisting">
$errors   = $element-&gt;getErrors();
$messages = $element-&gt;getMessages();
</pre>
<p>
            (Nota: los mensajes de error devueltos son un array asociativo de pares
            código de error / mensaje de error.)
        </p>
<p>
            Además de los validadores, puede especificar que un elemento sea
            obligatorio, usando <code class="methodname">setRequired($flag)</code>. Por defecto, este
            indicador es <code class="constant">FALSE</code>. En combinación con
            <code class="methodname">setAllowEmpty($flag)</code> (<code class="constant">TRUE</code>
            por defecto) y <code class="methodname">setAutoInsertNotEmptyValidator($flag)</code>
            (<code class="constant">TRUE</code> por defecto), el comportamiento de su cadena de validadores
            puede modificarse de varias maneras:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    Usando los valores por defecto, validar un Elemento sin pasar un valor, o
                    pasando una cadena vacía para él, omite todos los validadores y valida como
                    <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setAllowEmpty(false)</code> dejando intactos los otros dos
                    indicadores mencionados, validará contra la cadena de validadores
                    que definió para este Elemento, sin importar el valor pasado
                    a <code class="methodname">isValid()</code>.
                </p></li>
<li class="listitem">
<p>
                    <code class="methodname">setRequired(true)</code> dejando intactos los otros dos
                    indicadores mencionados, añadirá un validador 'NotEmpty'
                    al principio de la cadena de validadores (si aún no se había establecido ninguno), con el
                    indicador <code class="varname">$breakChainOnFailure</code> activado. Este comportamiento otorga
                    al indicador required un significado semántico: si no se pasa ningún valor,
                    invalidamos inmediatamente el envío y notificamos al
                    usuario, y evitamos que otros validadores se ejecuten sobre lo que ya
                    sabemos que son datos inválidos.
                </p>
<p>
                    Si no desea este comportamiento, puede desactivarlo pasando un valor
                    <code class="constant">FALSE</code> a
                    <code class="methodname">setAutoInsertNotEmptyValidator($flag)</code>; esto
                    evitará que <code class="methodname">isValid()</code> coloque el
                    validador 'NotEmpty' en la cadena de validadores.
                </p>
</li>
</ul></div>
<p>
            Para más información sobre validadores, vea la <a class="link" href="zend.validate.phtml#zend.validate.introduction" title="76.1. Introduction">documentación de
                Zend_Validate</a>.
        </p>
<div class="note"><table border="0" summary="Note: Using Zend_Form_Elements as general-purpose validators">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Uso de Zend_Form_Elements como validadores de propósito general</th>
</tr>
<tr><td align="left" valign="top"><p>
                <code class="classname">Zend_Form_Element</code> implementa
                <code class="classname">Zend_Validate_Interface</code>, lo que significa que un elemento también puede
                usarse como validador en otras cadenas de validación no relacionadas
                con formularios.
            </p></td></tr>
</table></div>
<div class="note"><table border="0" summary="Note: When is an element detected as empty?">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">¿Cuándo se detecta que un elemento está vacío?</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Como se mencionó, el validador 'NotEmpty' se usa para detectar si un elemento está vacío
                o no. Pero <code class="classname">Zend_Validate_NotEmpty</code>, por defecto, no
                funciona como el método <code class="methodname">empty()</code> de <acronym class="acronym">PHP</acronym>.
            </p>
<p>
                Esto significa que cuando un elemento contiene un entero <span class="emphasis"><em>0</em></span> o una cadena
                <span class="emphasis"><em>'0'</em></span>, el elemento se considerará no vacío. Si desea
                tener un comportamiento diferente debe crear su propia instancia de
                <code class="classname">Zend_Validate_NotEmpty</code>. Allí puede definir el comportamiento de
                este validador. Vea <a class="ulink" href="zend.validate.set.notempty" target="_top">Zend_Validate_NotEmpty</a> para más detalles.
            </p>
</td></tr>
</table></div>
<p>
            Los métodos asociados con la validación incluyen:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="methodname">setRequired($flag)</code> y
                    <code class="methodname">isRequired()</code> le permiten establecer y recuperar el
                    estado del indicador 'required'. Cuando se establece como booleano <code class="constant">TRUE</code>,
                    este indicador requiere que el elemento esté en los datos procesados por
                    <code class="classname">Zend_Form</code>.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setAllowEmpty($flag)</code> y
                    <code class="methodname">getAllowEmpty()</code> le permiten modificar el
                    comportamiento de elementos opcionales (es decir, elementos donde el
                    indicador required es <code class="constant">FALSE</code>). Cuando el indicador 'allow empty' es
                    <code class="constant">TRUE</code>, los valores vacíos no se pasarán a la cadena de validadores.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setAutoInsertNotEmptyValidator($flag)</code> le permite
                    especificar si se antepondrá o no un validador 'NotEmpty' a la
                    cadena de validadores cuando el elemento sea
                    obligatorio. Por defecto, este indicador es <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addValidator($nameOrValidator, $breakChainOnFailure = false, array
                        $options = null)</code>
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addValidators(array $validators)</code>
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setValidators(array $validators)</code> (sobrescribe todos los
                    validadores)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">getValidator($name)</code> (recupera un objeto validador por
                    nombre)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">getValidators()</code> (recupera todos los validadores)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">removeValidator($name)</code> (elimina el validador por nombre)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">clearValidators()</code> (elimina todos los validadores)
                </p></li>
</ul></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.elements.validators.errors"></a>36.3.3.1. Mensajes de error personalizados</h4></div></div></div>
<p>
                A veces, puede querer especificar uno o más mensajes de error específicos
                para usar en lugar de los mensajes de error generados por los
                validadores adjuntos a su elemento. Además, a veces puede
                querer marcar el elemento como inválido usted mismo. A partir de la versión 1.6.0, esta
                funcionalidad es posible mediante los siguientes métodos.
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">addErrorMessage($message)</code>: añade un mensaje de error
                        para mostrar en los errores de validación del formulario. Puede llamar a esto más
                        de una vez, y los nuevos mensajes se añaden a la pila.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addErrorMessages(array $messages)</code>: añade múltiples
                        mensajes de error para mostrar en los errores de validación del formulario.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setErrorMessages(array $messages)</code>: añade múltiples
                        mensajes de error para mostrar en los errores de validación del formulario,
                        sobrescribiendo todos los mensajes de error establecidos previamente.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getErrorMessages()</code>: recupera la lista de
                        mensajes de error personalizados que se han definido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">clearErrorMessages()</code>: elimina todos los mensajes de error
                        personalizados que se han definido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">markAsError()</code>: marca el elemento como que ha
                        fallado la validación.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">hasErrors()</code>: determina si el elemento ha
                        fallado la validación o ha sido marcado como inválido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addError($message)</code>: añade un mensaje a la pila de
                        mensajes de error personalizados y marca el elemento como inválido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addErrors(array $messages)</code>: añade varios
                        mensajes a la pila de mensajes de error personalizados y marca el
                        elemento como inválido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setErrors(array $messages)</code>: sobrescribe la
                        pila de mensajes de error personalizados con los mensajes proporcionados y
                        marca el elemento como inválido.
                    </p></li>
</ul></div>
<p>
                Todos los errores establecidos de esta manera pueden traducirse. Además,
                puede insertar el marcador de posición "%value%" para representar el
                valor del elemento; este valor actual del elemento se sustituirá
                cuando se recuperen los mensajes de error.
            </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.decorators"></a>36.3.4. Decoradores</h3></div></div></div>
<p>
            Uno de los puntos más dolorosos para muchos desarrolladores web es la creación
            de los propios formularios <acronym class="acronym">XHTML</acronym>. Para cada elemento, el desarrollador
            necesita crear el marcado para el propio elemento (típicamente una etiqueta)
            y marcado especial para mostrar
            los mensajes de error de validación. Cuantos más elementos haya en la página, menos
            trivial se vuelve esta tarea.
        </p>
<p>
            <code class="classname">Zend_Form_Element</code> intenta resolver este problema mediante
            el uso de "decoradores". Los decoradores son simplemente clases que tienen
            acceso al elemento y un método para renderizar contenido. Para más
            información sobre cómo funcionan los decoradores, por favor vea la sección sobre <a class="link" href="zend.form.decorators.phtml" title="36.5. Creating Custom Form Markup Using Zend_Form_Decorator">Zend_Form_Decorator</a>.
        </p>
<p>
            Los decoradores por defecto usados por <code class="classname">Zend_Form_Element</code> son:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>ViewHelper</em></span>: especifica un helper de vista para usar
                    para renderizar el elemento. El atributo del elemento 'helper' puede
                    usarse para especificar qué helper de vista usar. Por defecto,
                    <code class="classname">Zend_Form_Element</code> especifica el helper de vista 'formText',
                    pero las subclases individuales especifican helpers diferentes.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Errors</em></span>: añade mensajes de error al
                    elemento usando <code class="classname">Zend_View_Helper_FormErrors</code>. Si no hay ninguno
                    presente, no se añade nada.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Description</em></span>: añade la descripción
                    del elemento. Si no hay ninguna presente, no se añade nada. Por
                    defecto, la descripción se renderiza en una etiqueta &lt;p&gt; con una
                    clase 'description'.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>HtmlTag</em></span>: envuelve el elemento y los errores en
                    una etiqueta <acronym class="acronym">HTML</acronym> &lt;dd&gt;.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Label</em></span>: antepone una etiqueta al elemento
                    usando <code class="classname">Zend_View_Helper_FormLabel</code>, y la envuelve en una
                    etiqueta &lt;dt&gt;. Si no se proporciona ninguna etiqueta, solo se renderiza
                    la etiqueta de término de definición.
                </p></li>
</ul></div>
<div class="note"><table border="0" summary="Note: Default Decorators Do Not Need to Be Loaded">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Los decoradores por defecto no necesitan cargarse</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Por defecto, los decoradores por defecto se cargan durante la
                inicialización del objeto. Puede desactivar esto pasando la
                opción 'disableLoadDefaultDecorators' al constructor:
            </p>
<pre class="programlisting">
$element = new Zend_Form_Element('foo',
                                 array('disableLoadDefaultDecorators' =&gt;
                                      true)
                                );
</pre>
<p>
                Esta opción puede combinarse con cualquier otra opción que pase,
                tanto como opciones de array o en un objeto <code class="classname">Zend_Config</code>.
            </p>
</td></tr>
</table></div>
<p>
            Dado que el orden en que se registran los decoradores importa -el primer
            decorador registrado se ejecuta primero-, necesitará asegurarse
            de registrar sus decoradores en un orden apropiado, o
            asegurarse de establecer las opciones de posicionamiento de forma razonable. Para
            dar un ejemplo, aquí está el código que registra los decoradores
            por defecto:
        </p>
<pre class="programlisting">
$this-&gt;addDecorators(array(
    array('ViewHelper'),
    array('Errors'),
    array('Description', array('tag' =&gt; 'p', 'class' =&gt; 'description')),
    array('HtmlTag', array('tag' =&gt; 'dd')),
    array('Label', array('tag' =&gt; 'dt')),
));
</pre>
<p>
            El contenido inicial se crea con el decorador 'ViewHelper', el cual
            crea el propio elemento de formulario. A continuación, el decorador 'Errors'
            recupera los mensajes de error del elemento, y, si hay alguno presente,
            los pasa al helper de vista 'FormErrors' para renderizar. Si hay una
            descripción presente, el decorador 'Description' añadirá un
            párrafo de clase 'description' que contiene el texto descriptivo al
            contenido agregado. El siguiente decorador, 'HtmlTag', envuelve el
            elemento, los errores y la descripción en una etiqueta <acronym class="acronym">HTML</acronym> &lt;dd&gt;.
            Finalmente, el último decorador, 'label', recupera la etiqueta del elemento
            y la pasa al helper de vista 'FormLabel', envolviéndola en una etiqueta <acronym class="acronym">HTML</acronym>
            &lt;dt&gt;; el valor se antepone al contenido por defecto.
            El resultado final se ve básicamente así:
        </p>
<pre class="programlisting">
&lt;dt&gt;&lt;label for="foo" class="optional"&gt;Foo&lt;/label&gt;&lt;/dt&gt;
&lt;dd&gt;
    &lt;input type="text" name="foo" id="foo" value="123" /&gt;
    &lt;ul class="errors"&gt;
        &lt;li&gt;"123" is not an alphanumeric value&lt;/li&gt;
    &lt;/ul&gt;
    &lt;p class="description"&gt;
        This is some descriptive text regarding the element.
    &lt;/p&gt;
&lt;/dd&gt;
</pre>
<p>
            Para más información sobre decoradores, lea la sección <a class="link" href="zend.form.decorators.phtml" title="36.5. Creating Custom Form Markup Using Zend_Form_Decorator">Zend_Form_Decorator</a>.
        </p>
<div class="note"><table border="0" summary="Note: Using Multiple Decorators of the Same Type">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Uso de múltiples decoradores del mismo tipo</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Internamente, <code class="classname">Zend_Form_Element</code> usa la clase de un decorador
                como mecanismo de búsqueda al recuperar decoradores. Como
                resultado, no puede registrar múltiples decoradores del mismo
                tipo; los decoradores subsiguientes simplemente sobrescribirán los que
                existían antes.
            </p>
<p>
                Para solucionar esto, puede usar <span class="emphasis"><em>alias</em></span>.
                En lugar de pasar un decorador o nombre de decorador como primer
                argumento a <code class="methodname">addDecorator()</code>, pase un array con un
                único elemento, donde el alias apunta al objeto o nombre de decorador:
            </p>
<pre class="programlisting">
// Alias a 'FooBar':
$element-&gt;addDecorator(array('FooBar' =&gt; 'HtmlTag'),
                       array('tag' =&gt; 'div'));

// Y recuperarlo después:
$decorator = $element-&gt;getDecorator('FooBar');
</pre>
<p>
                En los métodos <code class="methodname">addDecorators()</code> y
                <code class="methodname">setDecorators()</code>, necesitará pasar
                la opción 'decorator' en el array que representa al decorador:
            </p>
<pre class="programlisting">
// Añadir dos decoradores 'HtmlTag', dando alias a uno como 'FooBar':
$element-&gt;addDecorators(
    array('HtmlTag', array('tag' =&gt; 'div')),
    array(
        'decorator' =&gt; array('FooBar' =&gt; 'HtmlTag'),
        'options' =&gt; array('tag' =&gt; 'dd')
    ),
);

// Y recuperarlo después:
$htmlTag = $element-&gt;getDecorator('HtmlTag');
$fooBar  = $element-&gt;getDecorator('FooBar');
</pre>
</td></tr>
</table></div>
<p>
            Los métodos asociados con decoradores incluyen:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="methodname">addDecorator($nameOrDecorator, array $options = null)</code>
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addDecorators(array $decorators)</code>
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">setDecorators(array $decorators)</code> (sobrescribe todos los
                    decoradores)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">getDecorator($name)</code> (recupera un objeto decorador por
                    nombre)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">getDecorators()</code> (recupera todos los decoradores)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">removeDecorator($name)</code> (elimina el decorador por nombre)
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">clearDecorators()</code> (elimina todos los decoradores)
                </p></li>
</ul></div>
<p>
            <code class="classname">Zend_Form_Element</code> también usa sobrecarga para permitir renderizar
            decoradores específicos. <code class="methodname">__call()</code> interceptará los métodos
            que empiecen con el texto 'render' y usará el resto del nombre del método
            para buscar un decorador; si se encuentra, renderizará entonces ese
            decorador <span class="emphasis"><em>único</em></span>. Cualquier argumento pasado a la
            llamada al método se usará como contenido para pasar al método
            <code class="methodname">render()</code> del decorador. Como ejemplo:
        </p>
<pre class="programlisting">
// Renderizar solo el decorador ViewHelper:
echo $element-&gt;renderViewHelper();

// Renderizar solo el decorador HtmlTag, pasando contenido:
echo $element-&gt;renderHtmlTag("This is the html tag content");
</pre>
<p>
            Si el decorador no existe, se lanza una excepción.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.metadata"></a>36.3.5. Metadatos y atributos</h3></div></div></div>
<p>
            <code class="classname">Zend_Form_Element</code> maneja una variedad de atributos y
            metadatos de elementos. Los atributos básicos incluyen:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>name</em></span>: el nombre del elemento. Usa los
                    accesores <code class="methodname">setName()</code> y <code class="methodname">getName()</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>label</em></span>: la etiqueta del elemento. Usa los
                    accesores <code class="methodname">setLabel()</code> y <code class="methodname">getLabel()</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>order</em></span>: el índice en el que un elemento
                    debe aparecer en el formulario. Usa los accesores <code class="methodname">setOrder()</code> y
                    <code class="methodname">getOrder()</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>value</em></span>: el valor actual del elemento. Usa los
                    accesores <code class="methodname">setValue()</code> y <code class="methodname">getValue()</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>description</em></span>: una descripción del elemento;
                    a menudo se usa para proporcionar información contextual mediante tooltip o javascript
                    describiendo el propósito del elemento. Usa los accesores
                    <code class="methodname">setDescription()</code> y
                    <code class="methodname">getDescription()</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>required</em></span>: indicador que señala si
                    el elemento es obligatorio al realizar la validación del formulario. Usa
                    los accesores <code class="methodname">setRequired()</code> y
                    <code class="methodname">isRequired()</code>. Este indicador es
                    <code class="constant">FALSE</code> por defecto.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>allowEmpty</em></span>: indicador que señala si
                    un elemento no obligatorio (opcional) debe intentar validar
                    valores vacíos. Si se establece en <code class="constant">TRUE</code> y el indicador required es
                    <code class="constant">FALSE</code>, los valores vacíos no se pasan a la cadena de validadores
                    y se presumen <code class="constant">TRUE</code>. Usa los
                    accesores <code class="methodname">setAllowEmpty()</code> y
                    <code class="methodname">getAllowEmpty()</code>. Este indicador es
                    <code class="constant">TRUE</code> por defecto.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>autoInsertNotEmptyValidator</em></span>: indicador
                    que señala si se debe insertar o no un validador 'NotEmpty' cuando
                    el elemento es obligatorio. Por defecto, este indicador es <code class="constant">TRUE</code>. Establezca
                    el indicador con <code class="methodname">setAutoInsertNotEmptyValidator($flag)</code> y
                    determine el valor con
                    <code class="methodname">autoInsertNotEmptyValidator()</code>.
                </p></li>
</ul></div>
<p>
            Los elementos de formulario pueden requerir metadatos adicionales. Para elementos de formulario
            <acronym class="acronym">XHTML</acronym>, por ejemplo, puede que desee especificar atributos como
            la clase o el id. Para facilitar esto hay un conjunto de accesores:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>setAttrib($name, $value)</em></span>: añade un atributo
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>setAttribs(array $attribs)</em></span>: similar a
                    addAttribs(), pero sobrescribe
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>getAttrib($name)</em></span>: recupera un único
                    valor de atributo
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>getAttribs()</em></span>: recupera todos los atributos como
                    pares clave/valor
                </p></li>
</ul></div>
<p>
            Sin embargo, la mayoría de las veces puede simplemente acceder a ellos como propiedades
            del objeto, ya que <code class="classname">Zend_Form_Element</code> utiliza sobrecarga
            para facilitar el acceso a ellos:
        </p>
<pre class="programlisting">
// Equivalente a $element-&gt;setAttrib('class', 'text'):
$element-&gt;class = 'text;
</pre>
<p>
            Por defecto, todos los atributos se pasan al helper de vista usado por
            el elemento durante el renderizado, y se renderizan como atributos <acronym class="acronym">HTML</acronym> de
            la etiqueta del elemento.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.standard"></a>36.3.6. Elementos estándar</h3></div></div></div>
<p>
            <code class="classname">Zend_Form</code> se distribuye con un número de elementos estándar; por favor lea
            el capítulo de <a class="link" href="zend.form.standardElements.phtml" title="36.6. Standard Form Elements Shipped With Zend Framework">Elementos Estándar</a>
            para más detalles.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.methods"></a>36.3.7. Métodos de Zend_Form_Element</h3></div></div></div>
<p>
            <code class="classname">Zend_Form_Element</code> tiene muchísimos métodos. A continuación
            se presenta un resumen rápido de sus firmas, agrupados por tipo:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>Configuración:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p><code class="methodname">setOptions(array $options)</code></p></li>
<li class="listitem"><p><code class="methodname">setConfig(Zend_Config $config)</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>I18n:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">setTranslator(Zend_Translate_Adapter $translator
                                = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">getTranslator()</code></p></li>
<li class="listitem"><p><code class="methodname">setDisableTranslator($flag)</code></p></li>
<li class="listitem"><p><code class="methodname">translatorIsDisabled()</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Propiedades:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p><code class="methodname">setName($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getName()</code></p></li>
<li class="listitem"><p><code class="methodname">setValue($value)</code></p></li>
<li class="listitem"><p><code class="methodname">getValue()</code></p></li>
<li class="listitem"><p><code class="methodname">getUnfilteredValue()</code></p></li>
<li class="listitem"><p><code class="methodname">setLabel($label)</code></p></li>
<li class="listitem"><p><code class="methodname">getLabel()</code></p></li>
<li class="listitem"><p><code class="methodname">setDescription($description)</code></p></li>
<li class="listitem"><p><code class="methodname">getDescription()</code></p></li>
<li class="listitem"><p><code class="methodname">setOrder($order)</code></p></li>
<li class="listitem"><p><code class="methodname">getOrder()</code></p></li>
<li class="listitem"><p><code class="methodname">setRequired($flag)</code></p></li>
<li class="listitem"><p><code class="methodname">isRequired()</code></p></li>
<li class="listitem"><p><code class="methodname">setAllowEmpty($flag)</code></p></li>
<li class="listitem"><p><code class="methodname">getAllowEmpty()</code></p></li>
<li class="listitem"><p><code class="methodname">setAutoInsertNotEmptyValidator($flag)</code></p></li>
<li class="listitem"><p><code class="methodname">autoInsertNotEmptyValidator()</code></p></li>
<li class="listitem"><p><code class="methodname">setIgnore($flag)</code></p></li>
<li class="listitem"><p><code class="methodname">getIgnore()</code></p></li>
<li class="listitem"><p><code class="methodname">getType()</code></p></li>
<li class="listitem"><p><code class="methodname">setAttrib($name, $value)</code></p></li>
<li class="listitem"><p><code class="methodname">setAttribs(array $attribs)</code></p></li>
<li class="listitem"><p><code class="methodname">getAttrib($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getAttribs()</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Cargadores de plugins y rutas:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">setPluginLoader(Zend_Loader_PluginLoader_Interface $loader,
                                $type)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">getPluginLoader($type)</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">addPrefixPath($prefix, $path, $type = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addPrefixPaths(array $spec)</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Validación:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">addValidator($validator, $breakChainOnFailure = false,
                                $options = array())</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addValidators(array $validators)</code></p></li>
<li class="listitem"><p><code class="methodname">setValidators(array $validators)</code></p></li>
<li class="listitem"><p><code class="methodname">getValidator($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getValidators()</code></p></li>
<li class="listitem"><p><code class="methodname">removeValidator($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearValidators()</code></p></li>
<li class="listitem"><p><code class="methodname">isValid($value, $context = null)</code></p></li>
<li class="listitem"><p><code class="methodname">getErrors()</code></p></li>
<li class="listitem"><p><code class="methodname">getMessages()</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Filtros:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p><code class="methodname">addFilter($filter, $options = array())</code></p></li>
<li class="listitem"><p><code class="methodname">addFilters(array $filters)</code></p></li>
<li class="listitem"><p><code class="methodname">setFilters(array $filters)</code></p></li>
<li class="listitem"><p><code class="methodname">getFilter($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getFilters()</code></p></li>
<li class="listitem"><p><code class="methodname">removeFilter($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearFilters()</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Renderizado:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">setView(Zend_View_Interface $view = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">getView()</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">addDecorator($decorator, $options = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addDecorators(array $decorators)</code></p></li>
<li class="listitem"><p><code class="methodname">setDecorators(array $decorators)</code></p></li>
<li class="listitem"><p><code class="methodname">getDecorator($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getDecorators()</code></p></li>
<li class="listitem"><p><code class="methodname">removeDecorator($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearDecorators()</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">render(Zend_View_Interface $view = null)</code>
                        </p></li>
</ul></div>
</li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.config"></a>36.3.8. Configuración</h3></div></div></div>
<p>
            El constructor de <code class="classname">Zend_Form_Element</code> acepta ya sea un
            array de opciones o un objeto <code class="classname">Zend_Config</code> que contiene
            opciones, y también puede configurarse usando
            <code class="methodname">setOptions()</code> o <code class="methodname">setConfig()</code>. En términos
            generales, las claves se nombran de la siguiente manera:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    Si 'set' + clave corresponde a un método de
                    <code class="classname">Zend_Form_Element</code>, entonces el valor proporcionado se pasará a ese método.
                </p></li>
<li class="listitem"><p>
                    De lo contrario, el valor se usará para establecer un atributo.
                </p></li>
</ul></div>
<p>
            Las excepciones a la regla incluyen lo siguiente:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="property">prefixPath</span> se pasará a
                    <code class="methodname">addPrefixPaths()</code>
                </p></li>
<li class="listitem">
<p>
                    Los siguientes setters no pueden establecerse de esta manera:
                </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <span class="property">setAttrib</span> (aunque
                            <span class="property">setAttribs</span> <span class="emphasis"><em>sí</em></span> funciona)
                        </p></li>
<li class="listitem"><p><span class="property">setConfig</span></p></li>
<li class="listitem"><p><span class="property">setOptions</span></p></li>
<li class="listitem"><p><span class="property">setPluginLoader</span></p></li>
<li class="listitem"><p><span class="property">setTranslator</span></p></li>
<li class="listitem"><p><span class="property">setView</span></p></li>
</ul></div>
</li>
</ul></div>
<p>
            Como ejemplo, aquí hay un archivo de configuración que pasa configuración para
            cada tipo de dato configurable:
        </p>
<pre class="programlisting">
[element]
name = "foo"
value = "foobar"
label = "Foo:"
order = 10
required = true
allowEmpty = false
autoInsertNotEmptyValidator = true
description = "Foo elements are for examples"
ignore = false
attribs.id = "foo"
attribs.class = "element"
; For radio button elements
escape = true
listsep = "&lt;br /&gt;\n"
; sets 'onclick' attribute
onclick = "autoComplete(this, '/form/autocomplete/element')"
prefixPaths.decorator.prefix = "My_Decorator"
prefixPaths.decorator.path = "My/Decorator/"
disableTranslator = 0
validators.required.validator = "NotEmpty"
validators.required.breakChainOnFailure = true
validators.alpha.validator = "alpha"
validators.regex.validator = "regex"
validators.regex.options.pattern = "/^[A-F].*/$"
filters.ucase.filter = "StringToUpper"
decorators.element.decorator = "ViewHelper"
decorators.element.options.helper = "FormText"
decorators.label.decorator = "Label"
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.elements.custom"></a>36.3.9. Elementos personalizados</h3></div></div></div>
<p>
            Puede crear sus propios elementos personalizados simplemente extendiendo la
            clase <code class="classname">Zend_Form_Element</code>. Las razones comunes para hacer esto
            incluyen:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    Elementos que comparten validadores y/o filtros comunes
                </p></li>
<li class="listitem"><p>
                    Elementos que tienen funcionalidad de decorador personalizada
                </p></li>
</ul></div>
<p>
            Hay dos métodos que se usan típicamente para extender un elemento:
            <code class="methodname">init()</code>, que puede usarse para añadir lógica de inicialización
            personalizada a su elemento, y <code class="methodname">loadDefaultDecorators()</code>,
            que puede usarse para establecer una lista de decoradores por defecto usados por su
            elemento.
        </p>
<p>
            Como ejemplo, digamos que todos los elementos de texto en un formulario que está
            creando necesitan filtrarse con <code class="classname">StringTrim</code>,
            validarse con una expresión regular común, y que desea
            usar un decorador personalizado que ha creado para mostrarlos,
            'My_Decorator_TextItem'. Además, tiene una serie de atributos
            estándar, incluyendo 'size', 'maxLength' y 'class' que desea
            especificar. Podría definir un elemento para lograr esto de la siguiente manera:
        </p>
<pre class="programlisting">
class My_Element_Text extends Zend_Form_Element
{
    public function init()
    {
        $this-&gt;addPrefixPath('My_Decorator', 'My/Decorator/', 'decorator')
             -&gt;addFilters('StringTrim')
             -&gt;addValidator('Regex', false, array('/^[a-z0-9]{6,}$/i'))
             -&gt;addDecorator('TextItem')
             -&gt;setAttrib('size', 30)
             -&gt;setAttrib('maxLength', 45)
             -&gt;setAttrib('class', 'text');
    }
}
</pre>
<p>
            Luego podría informar a su objeto formulario sobre la ruta de prefijo para
            tales elementos, y empezar a crear elementos:
        </p>
<pre class="programlisting">
$form-&gt;addPrefixPath('My_Element', 'My/Element/', 'element')
     -&gt;addElement('text', 'foo');
</pre>
<p>
            El elemento 'foo' ahora será de tipo <code class="classname">My_Element_Text</code>,
            y exhibirá el comportamiento que ha delineado.
        </p>
<p>
            Otro método que puede querer sobrescribir al extender
            <code class="classname">Zend_Form_Element</code> es el método
            <code class="methodname">loadDefaultDecorators()</code>. Este método
            carga condicionalmente un conjunto de decoradores por defecto para su elemento;
            puede que desee sustituir sus propios decoradores en su clase
            que extiende:
        </p>
<pre class="programlisting">
class My_Element_Text extends Zend_Form_Element
{
    public function loadDefaultDecorators()
    {
        $this-&gt;addDecorator('ViewHelper')
             -&gt;addDecorator('DisplayError')
             -&gt;addDecorator('Label')
             -&gt;addDecorator('HtmlTag',
                            array('tag' =&gt; 'div', 'class' =&gt; 'element'));
    }
}
</pre>
<p>
            Hay muchas formas de personalizar elementos. Lea la documentación de la <acronym class="acronym">API</acronym>
            de <code class="classname">Zend_Form_Element</code> para conocer todos los
            métodos disponibles.
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.form.quickstart.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.form.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.form.forms.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">36.2. Inicio rápido de Zend_Form </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 36.4. Creación de formularios usando Zend_Form</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
