<?php $title = 'registerNamespace'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">registerNamespace</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.is-fallback-autoloader.phtml">Anterior</a> </td>
<th width="60%" align="center">42.7.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.register-namespaces.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.standard-autoloader.methods.register-namespace"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>registerNamespace — Registra un espacio de nombres con el autoloader</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">registerNamespace</span>(<span class="methodparam">$namespace, $directory</span>);</code>
</div>
<div class="refsection">
<a name="id37106"></a><h2>registerNamespace()</h2>
<p>
                    Registra un espacio de nombres con el autoloader, apuntándolo a un directorio específico
                    en el sistema de archivos para la resolución de clases. Para las clases que coincidan con ese
                    espacio de nombres inicial, el autoloader realizará entonces las búsquedas dentro de ese directorio.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.is-fallback-autoloader.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.register-namespaces.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">isFallbackAutoloader </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> registerNamespaces</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
