<?php $title = '43.5. Locales soportados'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">43.5. Locales soportados</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.locale.date.datesandtimes.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 43. Zend_Locale</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.log.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.locale.appendix"></a>43.5. Locales soportados</h2></div></div></div>
<p>
        <code class="classname">Zend_Locale</code> proporciona información sobre varios locales. La siguiente
        tabla muestra todos los idiomas y sus locales relacionados, ordenados por idioma:
    </p>
<div class="table">
<a name="zend.locale.appendix.table"></a><p class="title"><b>Tabla 43.9. Lista de todos los idiomas soportados</b></p>
<div class="table-contents"><table class="table" summary="List of all supported languages" border="1">
<colgroup>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Idioma</th>
<th>Locale</th>
<th>Región</th>
</tr></thead>
<tbody>
<tr>
<td rowspan="4" valign="middle">Afar</td>
<td>aa</td>
<td>---</td>
</tr>
<tr>
<td>aa_DJ</td>
<td>Yibuti</td>
</tr>
<tr>
<td>aa_ER</td>
<td>Eritrea</td>
</tr>
<tr>
<td>aa_ET</td>
<td>Etiopía</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Afrikáans</td>
<td>af</td>
<td>---</td>
</tr>
<tr>
<td>af_NA</td>
<td>Namibia</td>
</tr>
<tr>
<td>af_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Akan</td>
<td>ak</td>
<td>---</td>
</tr>
<tr>
<td>ak_GH</td>
<td>Ghana</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Amárico</td>
<td>am</td>
<td>---</td>
</tr>
<tr>
<td>am_ET</td>
<td>Etiopía</td>
</tr>
<tr>
<td rowspan="18" valign="middle">Árabe</td>
<td>ar</td>
<td>---</td>
</tr>
<tr>
<td>ar_AE</td>
<td>Emiratos Árabes Unidos</td>
</tr>
<tr>
<td>ar_BH</td>
<td>Baréin</td>
</tr>
<tr>
<td>ar_DZ</td>
<td>Argelia</td>
</tr>
<tr>
<td>ar_EG</td>
<td>Egipto</td>
</tr>
<tr>
<td>ar_IQ</td>
<td>Irak</td>
</tr>
<tr>
<td>ar_JO</td>
<td>Jordania</td>
</tr>
<tr>
<td>ar_KW</td>
<td>Kuwait</td>
</tr>
<tr>
<td>ar_LB</td>
<td>Líbano</td>
</tr>
<tr>
<td>ar_LY</td>
<td>Libia</td>
</tr>
<tr>
<td>ar_MA</td>
<td>Marruecos</td>
</tr>
<tr>
<td>ar_OM</td>
<td>Omán</td>
</tr>
<tr>
<td>ar_QA</td>
<td>Catar</td>
</tr>
<tr>
<td>ar_SA</td>
<td>Arabia Saudita</td>
</tr>
<tr>
<td>ar_SD</td>
<td>Sudán</td>
</tr>
<tr>
<td>ar_SY</td>
<td>Siria</td>
</tr>
<tr>
<td>ar_TN</td>
<td>Túnez</td>
</tr>
<tr>
<td>ar_YE</td>
<td>Yemen</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Asamés</td>
<td>as</td>
<td>---</td>
</tr>
<tr>
<td>as_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Azerí</td>
<td>az</td>
<td>---</td>
</tr>
<tr>
<td>az_AZ</td>
<td>Azerbaiyán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Bielorruso</td>
<td>be</td>
<td>---</td>
</tr>
<tr>
<td>be_BY</td>
<td>Bielorrusia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Búlgaro</td>
<td>bg</td>
<td>---</td>
</tr>
<tr>
<td>bg_BG</td>
<td>Bulgaria</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Bengalí</td>
<td>bn</td>
<td>---</td>
</tr>
<tr>
<td>bn_BD</td>
<td>Bangladés</td>
</tr>
<tr>
<td>bn_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Tibetano</td>
<td>bo</td>
<td>---</td>
</tr>
<tr>
<td>bo_CN</td>
<td>China</td>
</tr>
<tr>
<td>bn_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Bosnio</td>
<td>bs</td>
<td>---</td>
</tr>
<tr>
<td>bs_BA</td>
<td>Bosnia y Herzegovina</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Blin</td>
<td>byn</td>
<td>---</td>
</tr>
<tr>
<td>byn_ER</td>
<td>Eritrea</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Catalán</td>
<td>ca</td>
<td>---</td>
</tr>
<tr>
<td>ca_ES</td>
<td>España</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Atsam</td>
<td>cch</td>
<td>---</td>
</tr>
<tr>
<td>cch_NG</td>
<td>Nigeria</td>
</tr>
<tr>
<td>Copto</td>
<td>cop</td>
<td>---</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Checo</td>
<td>cs</td>
<td>---</td>
</tr>
<tr>
<td>cs_CZ</td>
<td>República Checa</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Galés</td>
<td>cy</td>
<td>---</td>
</tr>
<tr>
<td>cy_GB</td>
<td>Reino Unido</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Danés</td>
<td>da</td>
<td>---</td>
</tr>
<tr>
<td>da_DK</td>
<td>Dinamarca</td>
</tr>
<tr>
<td rowspan="7" valign="middle">Alemán</td>
<td>de</td>
<td>---</td>
</tr>
<tr>
<td>de_AT</td>
<td>Austria</td>
</tr>
<tr>
<td>de_BE</td>
<td>Bélgica</td>
</tr>
<tr>
<td>de_CH</td>
<td>Suiza</td>
</tr>
<tr>
<td>de_DE</td>
<td>Alemania</td>
</tr>
<tr>
<td>de_LI</td>
<td>Liechtenstein</td>
</tr>
<tr>
<td>de_LU</td>
<td>Luxemburgo</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Divehi</td>
<td>dv</td>
<td>---</td>
</tr>
<tr>
<td>dv_MV</td>
<td>Maldivas</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Dzongkha</td>
<td>dz</td>
<td>---</td>
</tr>
<tr>
<td>dz_BT</td>
<td>Bután</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Ewe</td>
<td>ee</td>
<td>---</td>
</tr>
<tr>
<td>ee_GH</td>
<td>Ghana</td>
</tr>
<tr>
<td>ee_TG</td>
<td>Togo</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Griego</td>
<td>el</td>
<td>---</td>
</tr>
<tr>
<td>el_CY</td>
<td>Chipre</td>
</tr>
<tr>
<td>el_GR</td>
<td>Grecia</td>
</tr>
<tr>
<td rowspan="27" valign="middle">Inglés</td>
<td>en</td>
<td>---</td>
</tr>
<tr>
<td>en_AS</td>
<td>Samoa Americana</td>
</tr>
<tr>
<td>en_AU</td>
<td>Australia</td>
</tr>
<tr>
<td>en_BE</td>
<td>Bélgica</td>
</tr>
<tr>
<td>en_BW</td>
<td>Botsuana</td>
</tr>
<tr>
<td>en_BZ</td>
<td>Belice</td>
</tr>
<tr>
<td>en_CA</td>
<td>Canadá</td>
</tr>
<tr>
<td>en_GB</td>
<td>Reino Unido</td>
</tr>
<tr>
<td>en_GU</td>
<td>Guam</td>
</tr>
<tr>
<td>en_HK</td>
<td>Hong Kong</td>
</tr>
<tr>
<td>en_IE</td>
<td>Irlanda</td>
</tr>
<tr>
<td>en_IN</td>
<td>India</td>
</tr>
<tr>
<td>en_JM</td>
<td>Jamaica</td>
</tr>
<tr>
<td>en_MH</td>
<td>Islas Marshall</td>
</tr>
<tr>
<td>en_MP</td>
<td>Islas Marianas del Norte</td>
</tr>
<tr>
<td>en_MT</td>
<td>Malta</td>
</tr>
<tr>
<td>en_NA</td>
<td>Namibia</td>
</tr>
<tr>
<td>en_NZ</td>
<td>Nueva Zelanda</td>
</tr>
<tr>
<td>en_PH</td>
<td>Filipinas</td>
</tr>
<tr>
<td>en_PK</td>
<td>Pakistán</td>
</tr>
<tr>
<td>en_SG</td>
<td>Singapur</td>
</tr>
<tr>
<td>en_TT</td>
<td>Trinidad y Tobago</td>
</tr>
<tr>
<td>en_UM</td>
<td>Islas Menores Alejadas de los Estados Unidos</td>
</tr>
<tr>
<td>en_US</td>
<td>Estados Unidos</td>
</tr>
<tr>
<td>en_VI</td>
<td>Islas Vírgenes de los Estados Unidos</td>
</tr>
<tr>
<td>en_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td>en_ZW</td>
<td>Zimbabue</td>
</tr>
<tr>
<td>Esperanto</td>
<td>eo</td>
<td>---</td>
</tr>
<tr>
<td rowspan="21" valign="middle">Español</td>
<td>es</td>
<td>---</td>
</tr>
<tr>
<td>es_AR</td>
<td>Argentina</td>
</tr>
<tr>
<td>es_BO</td>
<td>Bolivia</td>
</tr>
<tr>
<td>es_CL</td>
<td>Chile</td>
</tr>
<tr>
<td>es_CO</td>
<td>Colombia</td>
</tr>
<tr>
<td>es_CR</td>
<td>Costa Rica</td>
</tr>
<tr>
<td>es_DO</td>
<td>República Dominicana</td>
</tr>
<tr>
<td>es_EC</td>
<td>Ecuador</td>
</tr>
<tr>
<td>es_ES</td>
<td>España</td>
</tr>
<tr>
<td>es_GT</td>
<td>Guatemala</td>
</tr>
<tr>
<td>es_HN</td>
<td>Honduras</td>
</tr>
<tr>
<td>es_MX</td>
<td>México</td>
</tr>
<tr>
<td>es_NI</td>
<td>Nicaragua</td>
</tr>
<tr>
<td>es_PA</td>
<td>Panamá</td>
</tr>
<tr>
<td>es_PE</td>
<td>Perú</td>
</tr>
<tr>
<td>es_PR</td>
<td>Puerto Rico</td>
</tr>
<tr>
<td>es_PY</td>
<td>Paraguay</td>
</tr>
<tr>
<td>es_SV</td>
<td>El Salvador</td>
</tr>
<tr>
<td>es_US</td>
<td>Estados Unidos</td>
</tr>
<tr>
<td>es_UY</td>
<td>Uruguay</td>
</tr>
<tr>
<td>es_VE</td>
<td>Venezuela</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Estonio</td>
<td>et</td>
<td>---</td>
</tr>
<tr>
<td>et_EE</td>
<td>Estonia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Vasco</td>
<td>eu</td>
<td>---</td>
</tr>
<tr>
<td>eu_ES</td>
<td>España</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Persa</td>
<td>fa</td>
<td>---</td>
</tr>
<tr>
<td>fa_AF</td>
<td>Afganistán</td>
</tr>
<tr>
<td>fa_IR</td>
<td>Irán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Finlandés</td>
<td>fi</td>
<td>---</td>
</tr>
<tr>
<td>fi_FI</td>
<td>Finlandia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Filipino</td>
<td>fil</td>
<td>---</td>
</tr>
<tr>
<td>fil_PH</td>
<td>Filipinas</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Feroés</td>
<td>fo</td>
<td>---</td>
</tr>
<tr>
<td>fo_FO</td>
<td>Islas Feroe</td>
</tr>
<tr>
<td rowspan="8" valign="middle">Francés</td>
<td>fr</td>
<td>---</td>
</tr>
<tr>
<td>fr_BE</td>
<td>Bélgica</td>
</tr>
<tr>
<td>fr_CA</td>
<td>Canadá</td>
</tr>
<tr>
<td>fr_CH</td>
<td>Suiza</td>
</tr>
<tr>
<td>fr_FR</td>
<td>Francia</td>
</tr>
<tr>
<td>fr_LU</td>
<td>Luxemburgo</td>
</tr>
<tr>
<td>fr_MC</td>
<td>Mónaco</td>
</tr>
<tr>
<td>fr_SN</td>
<td>Senegal</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Friulano</td>
<td>fur</td>
<td>---</td>
</tr>
<tr>
<td>fur_IT</td>
<td>Italia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Irlandés</td>
<td>ga</td>
<td>---</td>
</tr>
<tr>
<td>ga_IE</td>
<td>Irlanda</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Ga</td>
<td>gaa</td>
<td>---</td>
</tr>
<tr>
<td>gaa_GH</td>
<td>Ghana</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Geez</td>
<td>gez</td>
<td>---</td>
</tr>
<tr>
<td>gez_ER</td>
<td>Eritrea</td>
</tr>
<tr>
<td>gez_ET</td>
<td>Etiopía</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Gallego</td>
<td>gl</td>
<td>---</td>
</tr>
<tr>
<td>gl_ES</td>
<td>España</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Alemán suizo</td>
<td>gsw</td>
<td>---</td>
</tr>
<tr>
<td>gsw_CH</td>
<td>Suizo</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Guyaratí</td>
<td>gu</td>
<td>---</td>
</tr>
<tr>
<td>gu_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Manés</td>
<td>gv</td>
<td>---</td>
</tr>
<tr>
<td>gv_GB</td>
<td>Reino Unido</td>
</tr>
<tr>
<td rowspan="5" valign="middle">Hausa</td>
<td>ha</td>
<td>---</td>
</tr>
<tr>
<td>ha_GH</td>
<td>Ghana</td>
</tr>
<tr>
<td>ha_NE</td>
<td>Níger</td>
</tr>
<tr>
<td>ha_NG</td>
<td>Nigeria</td>
</tr>
<tr>
<td>ha_SD</td>
<td>Sudán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Hawaiano</td>
<td>haw</td>
<td>---</td>
</tr>
<tr>
<td>haw_US</td>
<td>Estados Unidos</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Hebreo</td>
<td>he</td>
<td>---</td>
</tr>
<tr>
<td>he_IL</td>
<td>Israel</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Hindi</td>
<td>hi</td>
<td>---</td>
</tr>
<tr>
<td>hi_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Croata</td>
<td>hr</td>
<td>---</td>
</tr>
<tr>
<td>hr_HR</td>
<td>Croacia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Húngaro</td>
<td>hu</td>
<td>---</td>
</tr>
<tr>
<td>hu_HU</td>
<td>Hungría</td>
</tr>
<tr>
<td>Armenio</td>
<td>hy</td>
<td>---</td>
</tr>
<tr>
<td>Interlingua</td>
<td>ia</td>
<td>---</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Indonesio</td>
<td>id</td>
<td>---</td>
</tr>
<tr>
<td>id_ID</td>
<td>Indonesia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Igbo</td>
<td>ig</td>
<td>---</td>
</tr>
<tr>
<td>ig_NG</td>
<td>Nigeria</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Yi de Sichuan</td>
<td>ii</td>
<td>---</td>
</tr>
<tr>
<td>ii_CN</td>
<td>China</td>
</tr>
<tr>
<td>Indonesio</td>
<td>in</td>
<td>---</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Islandés</td>
<td>is</td>
<td>---</td>
</tr>
<tr>
<td>is_IS</td>
<td>Islandia</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Italiano</td>
<td>it</td>
<td>---</td>
</tr>
<tr>
<td>it_CH</td>
<td>Suiza</td>
</tr>
<tr>
<td>it_IT</td>
<td>Italia</td>
</tr>
<tr>
<td>Inuktitut</td>
<td>iu</td>
<td>---</td>
</tr>
<tr>
<td>Hebreo</td>
<td>iw</td>
<td>---</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Japonés</td>
<td>ja</td>
<td>---</td>
</tr>
<tr>
<td>ja_JP</td>
<td>Japón</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Georgiano</td>
<td>ka</td>
<td>---</td>
</tr>
<tr>
<td>ka_GE</td>
<td>Georgia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Jju</td>
<td>kaj</td>
<td>---</td>
</tr>
<tr>
<td>kaj_NG</td>
<td>Nigeria</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Kamba</td>
<td>kam</td>
<td>---</td>
</tr>
<tr>
<td>kam_KE</td>
<td>Kenia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Tyap</td>
<td>kcg</td>
<td>---</td>
</tr>
<tr>
<td>kcg_NG</td>
<td>Nigeria</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Koro</td>
<td>kfo</td>
<td>---</td>
</tr>
<tr>
<td>kfo_CI</td>
<td>Costa de Marfil</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Kazajo</td>
<td>kk</td>
<td>---</td>
</tr>
<tr>
<td>kk_KZ</td>
<td>Kazajistán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Kalaallisut</td>
<td>kl</td>
<td>---</td>
</tr>
<tr>
<td>kl_GL</td>
<td>Groenlandia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Jemer</td>
<td>km</td>
<td>---</td>
</tr>
<tr>
<td>km_KH</td>
<td>Camboya</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Canarés</td>
<td>kn</td>
<td>---</td>
</tr>
<tr>
<td>kn_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Coreano</td>
<td>ko</td>
<td>---</td>
</tr>
<tr>
<td>ko_KR</td>
<td>Corea del Sur</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Konkani</td>
<td>kok</td>
<td>---</td>
</tr>
<tr>
<td>kok_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Kpelle</td>
<td>kpe</td>
<td>---</td>
</tr>
<tr>
<td>kpe_GN</td>
<td>Guinea</td>
</tr>
<tr>
<td>kpe_LR</td>
<td>Liberia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Kurdo</td>
<td>ku</td>
<td>---</td>
</tr>
<tr>
<td>ku_IQ</td>
<td>Irak</td>
</tr>
<tr>
<td>ku_IR</td>
<td>Irán</td>
<td class="auto-generated"> </td>
</tr>
<tr>
<td>ku_SY</td>
<td>Siria</td>
<td class="auto-generated"> </td>
</tr>
<tr>
<td>ku_TR</td>
<td>Turquía</td>
<td class="auto-generated"> </td>
</tr>
<tr>
<td rowspan="2" valign="middle">Córnico</td>
<td>kw</td>
<td>---</td>
</tr>
<tr>
<td>kw_GB</td>
<td>Reino Unido</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Kirguís</td>
<td>ky</td>
<td>---</td>
</tr>
<tr>
<td>ky_KG</td>
<td>Kirguistán</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Lingala</td>
<td>ln</td>
<td>---</td>
</tr>
<tr>
<td>ln_CD</td>
<td>Congo (Kinshasa)</td>
</tr>
<tr>
<td>ln_CG</td>
<td>Congo (Brazzaville)</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Lao</td>
<td>lo</td>
<td>---</td>
</tr>
<tr>
<td>lo_LA</td>
<td>Laos</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Lituano</td>
<td>lt</td>
<td>---</td>
</tr>
<tr>
<td>lt_LT</td>
<td>Lituania</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Letón</td>
<td>lv</td>
<td>---</td>
</tr>
<tr>
<td>lv_LV</td>
<td>Letonia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Macedonio</td>
<td>mk</td>
<td>---</td>
</tr>
<tr>
<td>mk_MK</td>
<td>Macedonia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Malayalam</td>
<td>ml</td>
<td>---</td>
</tr>
<tr>
<td>ml_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Mongol</td>
<td>mn</td>
<td>---</td>
</tr>
<tr>
<td>mn_CN</td>
<td>China</td>
</tr>
<tr>
<td>mn_MN</td>
<td>Mongolia</td>
</tr>
<tr>
<td>Rumano</td>
<td>mo</td>
<td>---</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Maratí</td>
<td>mr</td>
<td>---</td>
</tr>
<tr>
<td>mr_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Malayo</td>
<td>ms</td>
<td>---</td>
</tr>
<tr>
<td>ms_BN</td>
<td>Brunéi</td>
</tr>
<tr>
<td>ms_MY</td>
<td>Malasia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Maltés</td>
<td>mt</td>
<td>---</td>
</tr>
<tr>
<td>mt_MT</td>
<td>Malta</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Birmano</td>
<td>my</td>
<td>---</td>
</tr>
<tr>
<td>my_MM</td>
<td>Myanmar</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Noruego bokmål</td>
<td>nb</td>
<td>---</td>
</tr>
<tr>
<td>nb_NO</td>
<td>Noruega</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Bajo alemán</td>
<td>nds</td>
<td>---</td>
</tr>
<tr>
<td>nds_DE</td>
<td>Alemania</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Nepalí</td>
<td>ne</td>
<td>---</td>
</tr>
<tr>
<td>ne_IN</td>
<td>India</td>
</tr>
<tr>
<td>ne_NP</td>
<td>Nepal</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Neerlandés</td>
<td>nl</td>
<td>---</td>
</tr>
<tr>
<td>nl_BE</td>
<td>Bélgica</td>
</tr>
<tr>
<td>nl_NL</td>
<td>Países Bajos</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Noruego nynorsk</td>
<td>nn</td>
<td>---</td>
</tr>
<tr>
<td>nn_NO</td>
<td>Noruega</td>
</tr>
<tr>
<td>Noruego</td>
<td>no</td>
<td>---</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Ndebele del sur</td>
<td>nr</td>
<td>---</td>
</tr>
<tr>
<td>nr_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Sotho septentrional</td>
<td>nso</td>
<td>---</td>
</tr>
<tr>
<td>nso_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Nyanja</td>
<td>ny</td>
<td>---</td>
</tr>
<tr>
<td>ny_MW</td>
<td>Malaui</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Occitano</td>
<td>oc</td>
<td>---</td>
</tr>
<tr>
<td>oc_FR</td>
<td>Francia</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Oromo</td>
<td>om</td>
<td>---</td>
</tr>
<tr>
<td>om_ET</td>
<td>Etiopía</td>
</tr>
<tr>
<td>om_KE</td>
<td>Kenia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Oriya</td>
<td>or</td>
<td>---</td>
</tr>
<tr>
<td>or_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Panyabí</td>
<td>pa</td>
<td>---</td>
</tr>
<tr>
<td>pa_IN</td>
<td>India</td>
</tr>
<tr>
<td>pa_PK</td>
<td>Pakistán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Polaco</td>
<td>pl</td>
<td>---</td>
</tr>
<tr>
<td>pl_PL</td>
<td>Polonia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Pastún</td>
<td>ps</td>
<td>---</td>
</tr>
<tr>
<td>ps_AF</td>
<td>Afganistán</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Portugués</td>
<td>pt</td>
<td>---</td>
</tr>
<tr>
<td>pt_BR</td>
<td>Brasil</td>
</tr>
<tr>
<td>pt_PT</td>
<td>Portugal</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Rumano</td>
<td>ro</td>
<td>---</td>
</tr>
<tr>
<td>ro_MD</td>
<td>Moldavia</td>
</tr>
<tr>
<td>ro_RO</td>
<td>Rumanía</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Ruso</td>
<td>ru</td>
<td>---</td>
</tr>
<tr>
<td>ru_RU</td>
<td>Rusia</td>
</tr>
<tr>
<td>ru_UA</td>
<td>Ucrania</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Kinyarwanda</td>
<td>rw</td>
<td>---</td>
</tr>
<tr>
<td>rw_RW</td>
<td>Ruanda</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Sánscrito</td>
<td>sa</td>
<td>---</td>
</tr>
<tr>
<td>sa_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Sami septentrional</td>
<td>se</td>
<td>---</td>
</tr>
<tr>
<td>se_FI</td>
<td>Finlandia</td>
</tr>
<tr>
<td>se_NO</td>
<td>Noruega</td>
</tr>
<tr>
<td rowspan="4" valign="middle">Serbocroata</td>
<td>sh</td>
<td>---</td>
</tr>
<tr>
<td>sh_BA</td>
<td>Bosnia y Herzegovina</td>
</tr>
<tr>
<td>sh_CS</td>
<td>Serbia y Montenegro</td>
</tr>
<tr>
<td>sh_YU</td>
<td>Serbia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Cingalés</td>
<td>si</td>
<td>---</td>
</tr>
<tr>
<td>si_LK</td>
<td>Sri Lanka</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Sidamo</td>
<td>sid</td>
<td>---</td>
</tr>
<tr>
<td>sid_ET</td>
<td>Etiopía</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Eslovaco</td>
<td>sk</td>
<td>---</td>
</tr>
<tr>
<td>sk_SK</td>
<td>Eslovaquia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Esloveno</td>
<td>sl</td>
<td>---</td>
</tr>
<tr>
<td>sl_SI</td>
<td>Eslovenia</td>
</tr>
<tr>
<td rowspan="5" valign="middle">Somalí</td>
<td>so</td>
<td>---</td>
</tr>
<tr>
<td>so_DJ</td>
<td>Yibuti</td>
</tr>
<tr>
<td>so_ET</td>
<td>Etiopía</td>
</tr>
<tr>
<td>so_KE</td>
<td>Kenia</td>
</tr>
<tr>
<td>so_SO</td>
<td>Somalia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Albanés</td>
<td>sq</td>
<td>---</td>
</tr>
<tr>
<td>sq_AL</td>
<td>Albania</td>
</tr>
<tr>
<td rowspan="6" valign="middle">Serbio</td>
<td>sr</td>
<td>---</td>
</tr>
<tr>
<td>sr_BA</td>
<td>Bosnia y Herzegovina</td>
</tr>
<tr>
<td>sr_CS</td>
<td>Serbia y Montenegro</td>
</tr>
<tr>
<td>sr_ME</td>
<td>Montenegro</td>
</tr>
<tr>
<td>sr_RS</td>
<td>Serbia</td>
</tr>
<tr>
<td>sr_YU</td>
<td>Serbia</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Suazi</td>
<td>ss</td>
<td>---</td>
</tr>
<tr>
<td>ss_SZ</td>
<td>Suazilandia</td>
</tr>
<tr>
<td>ss_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Sotho meridional</td>
<td>st</td>
<td>---</td>
</tr>
<tr>
<td>st_LS</td>
<td>Lesoto</td>
</tr>
<tr>
<td>st_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Sueco</td>
<td>sv</td>
<td>---</td>
</tr>
<tr>
<td>sv_FI</td>
<td>Finlandia</td>
</tr>
<tr>
<td>sv_SE</td>
<td>Suecia</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Suajili</td>
<td>sw</td>
<td>---</td>
</tr>
<tr>
<td>sw_KE</td>
<td>Kenia</td>
</tr>
<tr>
<td>sw_TZ</td>
<td>Tanzania</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Siríaco</td>
<td>syr</td>
<td>---</td>
</tr>
<tr>
<td>syr_SY</td>
<td>Siria</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Tamil</td>
<td>ta</td>
<td>---</td>
</tr>
<tr>
<td>ta_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Telugu</td>
<td>te</td>
<td>---</td>
</tr>
<tr>
<td>te_IN</td>
<td>India</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Tayiko</td>
<td>tg</td>
<td>---</td>
</tr>
<tr>
<td>tg_TJ</td>
<td>Tayikistán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Tailandés</td>
<td>th</td>
<td>---</td>
</tr>
<tr>
<td>th_TH</td>
<td>Tailandia</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Tigriña</td>
<td>ti</td>
<td>---</td>
</tr>
<tr>
<td>ti_ER</td>
<td>Eritrea</td>
</tr>
<tr>
<td>ti_ET</td>
<td>Etiopía</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Tigré</td>
<td>tig</td>
<td>---</td>
</tr>
<tr>
<td>tig_ER</td>
<td>Eritrea</td>
</tr>
<tr>
<td>Tagalo</td>
<td>tl</td>
<td>---</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Setsuana</td>
<td>tn</td>
<td>---</td>
</tr>
<tr>
<td>tn_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Tonga</td>
<td>to</td>
<td>---</td>
</tr>
<tr>
<td>to_TO</td>
<td>Tonga</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Turco</td>
<td>tr</td>
<td>---</td>
</tr>
<tr>
<td>tr_TR</td>
<td>Turquía</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Taroko</td>
<td>trv</td>
<td>---</td>
</tr>
<tr>
<td>trv_TW</td>
<td>Taiwán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Tsonga</td>
<td>ts</td>
<td>---</td>
</tr>
<tr>
<td>ts_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Tártaro</td>
<td>tt</td>
<td>---</td>
</tr>
<tr>
<td>tt_RU</td>
<td>Rusia</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Uigur</td>
<td>ug</td>
<td>---</td>
</tr>
<tr>
<td>ug_CN</td>
<td>China</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Ucraniano</td>
<td>uk</td>
<td>---</td>
</tr>
<tr>
<td>uk_UA</td>
<td>Ucrania</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Urdu</td>
<td>ur</td>
<td>---</td>
</tr>
<tr>
<td>ur_IN</td>
<td>India</td>
</tr>
<tr>
<td>ur_PK</td>
<td>Pakistán</td>
</tr>
<tr>
<td rowspan="3" valign="middle">Uzbeko</td>
<td>uz</td>
<td>---</td>
</tr>
<tr>
<td>uz_AF</td>
<td>Afganistán</td>
</tr>
<tr>
<td>uz_UZ</td>
<td>Uzbekistán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Venda</td>
<td>ve</td>
<td>---</td>
</tr>
<tr>
<td>ve_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Vietnamita</td>
<td>vi</td>
<td>---</td>
</tr>
<tr>
<td>vi_VN</td>
<td>Vietnam</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Walamo</td>
<td>wal</td>
<td>---</td>
</tr>
<tr>
<td>wal_ET</td>
<td>Etiopía</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Wólof</td>
<td>wo</td>
<td>---</td>
</tr>
<tr>
<td>wo_SN</td>
<td>Senegal</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Xhosa</td>
<td>xh</td>
<td>---</td>
</tr>
<tr>
<td>xh_ZA</td>
<td>Sudáfrica</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Yoruba</td>
<td>yo</td>
<td>---</td>
</tr>
<tr>
<td>yo_NG</td>
<td>Nigeria</td>
</tr>
<tr>
<td rowspan="6" valign="middle">Chino</td>
<td>zh</td>
<td>---</td>
</tr>
<tr>
<td>zh_CN</td>
<td>China</td>
</tr>
<tr>
<td>zh_HK</td>
<td>Hong Kong</td>
</tr>
<tr>
<td>zh_MO</td>
<td>Macao</td>
</tr>
<tr>
<td>zh_SG</td>
<td>Singapur</td>
</tr>
<tr>
<td>zh_TW</td>
<td>Taiwán</td>
</tr>
<tr>
<td rowspan="2" valign="middle">Zulú</td>
<td>zu</td>
<td>---</td>
</tr>
<tr>
<td>zu_ZA</td>
<td>Sudáfrica</td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.locale.date.datesandtimes.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.locale.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.log.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">43.4. Trabajando con fechas y horas </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 44. Zend_Log</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
