<?php $title = '64.13. Zend_Service_Amazon_Ec2: Regiones y zonas de disponibilidad'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.13. Zend_Service_Amazon_Ec2: Regiones y zonas de disponibilidad</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.amazon.ec2.keypairs.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.amazon.ec2.securitygroups.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.amazon.ec2.zones"></a>64.13. Zend_Service_Amazon_Ec2: Regiones y zonas de disponibilidad</h2></div></div></div>
<p>
        Amazon EC2 proporciona la posibilidad de ubicar instancias en distintas
        regiones y zonas de disponibilidad. Las regiones están dispersas en
        áreas geográficas o países independientes. Las zonas de disponibilidad
        se encuentran dentro de las regiones y están diseñadas para estar
        aisladas de fallos en otras zonas de disponibilidad, además de
        proporcionar conectividad de red de baja latencia y económica hacia
        otras zonas de disponibilidad de la misma región. Al lanzar instancias
        en zonas de disponibilidad separadas, puede proteger sus aplicaciones
        de fallos en una única zona de disponibilidad.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.amazon.ec2.zones.regions"></a>64.13.1. Regiones de Amazon EC2</h3></div></div></div>
<p>
            Amazon EC2 proporciona múltiples regiones para que pueda lanzar
            instancias de Amazon EC2 en ubicaciones que cumplan sus requisitos.
            Por ejemplo, podría querer lanzar instancias en Europa para estar
            más cerca de sus clientes europeos o para cumplir requisitos legales.
        </p>
<p>
            Cada región de Amazon EC2 está diseñada para estar completamente
            aislada de las demás regiones de Amazon EC2. Esto logra la mayor
            independencia y estabilidad posible ante fallos, y hace inequívoca
            la localidad de cada recurso de EC2.
        </p>
<div class="example">
<a name="zend.service.amazon.ec2.zones.regions.example"></a><p class="title"><b>Ejemplo 64.54. Visualizando las regiones disponibles</b></p>
<div class="example-contents">
<p>
                <code class="code">describe</code> se utiliza para averiguar a qué regiones tiene acceso su cuenta.
            </p>
<p>
                <code class="code">describe</code> devolverá un array que contiene información sobre qué
                regiones están disponibles. Cada array contendrá regionName y regionUrl.
            </p>
<pre class="programlisting">
$ec2_region = new Zend_Service_Amazon_Ec2_Region('aws_key','aws_secret_key');
$regions = $ec2_region-&gt;describe();

foreach($regions as $region) {
    print $region['regionName'] . ' -- ' . $region['regionUrl'] . '&lt;br /&gt;';
}
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.amazon.ec2.zones.availability"></a>64.13.2. Zonas de disponibilidad de Amazon EC2</h3></div></div></div>
<p>
            Al lanzar una instancia, puede especificar opcionalmente una zona
            de disponibilidad. Si no especifica una zona de disponibilidad,
            Amazon EC2 selecciona una por usted en la región que está utilizando.
            Al lanzar sus instancias iniciales, recomendamos aceptar la zona de
            disponibilidad predeterminada, lo que permite que Amazon EC2
            seleccione la mejor zona de disponibilidad para usted en función
            del estado del sistema y la capacidad disponible. Incluso si tiene
            otras instancias en ejecución, podría considerar no especificar una
            zona de disponibilidad si sus nuevas instancias no necesitan estar
            cerca de, ni separadas de, sus instancias existentes.
        </p>
<div class="example">
<a name="zend.service.amazon.ec2.zones.availability.example"></a><p class="title"><b>Ejemplo 64.55. Visualizando las zonas disponibles</b></p>
<div class="example-contents">
<p>
                <code class="code">describe</code> se utiliza para averiguar cuál es el estado de cada
                zona de disponibilidad.
            </p>
<p>
                <code class="code">describe</code> devolverá un array que contiene información sobre qué zonas
                están disponibles. Cada array contendrá zoneName y zoneState.
            </p>
<pre class="programlisting">
$ec2_zones = new Zend_Service_Amazon_Ec2_Availabilityzones('aws_key',
                                                           'aws_secret_key');
$zones = $ec2_zones-&gt;describe();

foreach($zones as $zone) {
    print $zone['zoneName'] . ' -- ' . $zone['zoneState'] . '&lt;br /&gt;';
}
</pre>
</div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.amazon.ec2.keypairs.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.amazon.ec2.securitygroups.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.12. Zend_Service_Amazon_Ec2: Pares de claves </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 64.14. Zend_Service_Amazon_Ec2: Grupos de seguridad</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
