<?php $title = 'Capítulo 62. Zend_Serializer'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 62. Zend_Serializer</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.search.lucene.best-practice.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.serializer.adapter.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.serializer"></a>Capítulo 62. Zend_Serializer</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.serializer.phtml#zend.serializer.introduction">62.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.serializer.adapter.phtml">62.2. Zend_Serializer_Adapter</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.phpserialize">62.2.1. Zend_Serializer_Adapter_PhpSerialize</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.igbinary">62.2.2. Zend_Serializer_Adapter_Igbinary</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.wddx">62.2.3. Zend_Serializer_Adapter_Wddx</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.json">62.2.4. Zend_Serializer_Adapter_Json</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.amf03">62.2.5. Zend_Serializer_Adapter_Amf 0 and 3</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.pythonpickle">62.2.6. Zend_Serializer_Adapter_PythonPickle</a></span></dt>
<dt><span class="sect2"><a href="zend.serializer.adapter.phtml#zend.serializer.adapter.phpcode">62.2.7. Zend_Serializer_Adapter_PhpCode</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.serializer.introduction"></a>62.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Serializer</code> proporciona una interfaz basada en adaptadores para generar
        de forma sencilla una representación almacenable de tipos de <acronym class="acronym">PHP</acronym> mediante
        distintos mecanismos, y recuperarla.
    </p>
<div class="example">
<a name="zend.serializer.introduction.example.dynamic"></a><p class="title"><b>Ejemplo 62.1. Uso de la interfaz dinámica de Zend_Serializer</b></p>
<div class="example-contents">
<p>
            Para instanciar un serializador debe usar el método de fábrica con el nombre del
            adaptador:
        </p>
<pre class="programlisting">
$serializer = Zend_Serializer::factory('PhpSerialize');
// Now $serializer is an instance of Zend_Serializer_Adapter_AdapterInterface,
// specifically Zend_Serializer_Adapter_PhpSerialize

try {
    $serialized = $serializer-&gt;serialize($data);
    // now $serialized is a string

    $unserialized = $serializer-&gt;unserialize($serialized);
    // now $data == $unserialized
} catch (Zend_Serializer_Exception $e) {
    echo $e;
}
</pre>
</div>
</div>
<br class="example-break"><p>
        El método <code class="methodname">serialize()</code> genera una cadena almacenable. Para regenerar
        estos datos serializados basta con llamar al método <code class="methodname">unserialize()</code>.
    </p>
<p>
        Cada vez que se encuentre un error al serializar o deserializar,
        <code class="classname">Zend_Serializer</code> lanzará una
        <code class="classname">Zend_Serializer_Exception</code>.
    </p>
<p>
        Para configurar un adaptador de serialización dado, opcionalmente puede añadir un array o una
        instancia de <code class="classname">Zend_Config</code> al método <code class="methodname">factory()</code> o a los
        métodos <code class="methodname">serialize()</code> y <code class="methodname">unserialize()</code>:
    </p>
<pre class="programlisting">
$serializer = Zend_Serializer::factory('Wddx', array(
    'comment' =&gt; 'serialized by Zend_Serializer',
));

try {
    $serialized = $serializer-&gt;serialize(
        $data,
        array('comment' =&gt; 'change comment')
    );

    $unserialized = $serializer-&gt;unserialize(
        $serialized,
        array(/* options for unserialize */)
    );
} catch (Zend_Serializer_Exception $e) {
    echo $e;
}
</pre>
<p>
        Las opciones pasadas a <code class="methodname">factory()</code> son válidas para el objeto instanciado.
        Puede cambiar estas opciones usando el método <code class="methodname">setOption(s)</code>.
        Para cambiar una o más opciones solo para una llamada concreta, páselas como segundo argumento
        al método <code class="methodname">serialize()</code> o <code class="methodname">unserialize()</code>.
    </p>
<div class="example">
<a name="zend.serializer.introduction.example.static.php"></a><p class="title"><b>Ejemplo 62.2. Uso de la interfaz estática de Zend_Serializer</b></p>
<div class="example-contents">
<p>
            Puede registrar un adaptador de serialización específico como adaptador de serialización
            predeterminado para usar con <code class="classname">Zend_Serializer</code>. Por defecto se
            registrará el adaptador <code class="classname">PhpSerialize</code>, pero puede cambiar esta
            opción usando el método estático <code class="methodname">setDefaultAdapter()</code>.
        </p>
<pre class="programlisting">
Zend_Serializer::setDefaultAdapter('PhpSerialize', $options);
// or
$serializer = Zend_Serializer::factory('PhpSerialize', $options);
Zend_Serializer::setDefaultAdapter($serializer);

try {
    $serialized   = Zend_Serializer::serialize($data, $options);
    $unserialized = Zend_Serializer::unserialize($serialized, $options);
} catch (Zend_Serializer_Exception $e) {
    echo $e;
}
</pre>
</div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.search.lucene.best-practice.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.serializer.adapter.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">61.10. Buenas prácticas </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 62.2. Zend_Serializer_Adapter</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
