<?php $title = '45.8. Controlar el límite MIME'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">45.8. Controlar el límite MIME</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.adding-recipients.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 45. Zend_Mail</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.additional-headers.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.boundary"></a>45.8. Controlar el límite MIME</h2></div></div></div>
<p>
        En un mensaje multiparte, el límite <acronym class="acronym">MIME</acronym> que separa las
        distintas partes del mensaje normalmente se genera de forma aleatoria. Sin embargo, en
        algunos casos, es posible que desee especificar el límite <acronym class="acronym">MIME</acronym> que
        se utiliza. Esto puede hacerse mediante el método
        <code class="methodname">setMimeBoundary()</code>, como en el siguiente ejemplo:
    </p>
<div class="example">
<a name="zend.mail.boundary.example-1"></a><p class="title"><b>Ejemplo 45.9. Cambiar el límite MIME</b></p>
<div class="example-contents"><pre class="programlisting">
$mail = new Zend_Mail();
$mail-&gt;setMimeBoundary('=_' . md5(microtime(1) . $someId++));
// build message...
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.adding-recipients.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mail.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.additional-headers.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">45.7. Agregar destinatarios </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 45.9. Cabeceras adicionales</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
