<?php $title = '49.3. Zend_Mime_Part'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">49.3. Zend_Mime_Part</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mime.message.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 49. Zend_Mime</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mobile.push.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mime.part"></a>49.3. Zend_Mime_Part</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mime.part.introduction"></a>49.3.1. Introducción</h3></div></div></div>
<p>
            Esta clase representa una única parte de un mensaje <acronym class="acronym">MIME</acronym>. Contiene
            el contenido real de la parte del mensaje, además de información sobre su codificación,
            tipo de contenido y nombre de archivo original. Proporciona un método para generar una
            cadena a partir de los datos almacenados. Los objetos <code class="classname">Zend_Mime_Part</code> pueden
            añadirse a <a class="link" href="zend.mime.message.phtml" title="49.2. Zend_Mime_Message"><code class="classname">Zend_Mime_Message</code></a> para
            ensamblar un mensaje multiparte completo.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mime.part.instantiation"></a>49.3.2. Instanciación</h3></div></div></div>
<p>
            <code class="classname">Zend_Mime_Part</code> se instancia con una cadena que
            representa el contenido de la nueva parte. Se asume que el tipo es
            OCTET-STREAM, y la codificación es 8Bit. Después de instanciar un
            <code class="classname">Zend_Mime_Part</code>, la información de metadatos puede establecerse
            accediendo directamente a sus atributos:
        </p>
<pre class="programlisting">
public $type = Zend_Mime::TYPE_OCTETSTREAM;
public $encoding = Zend_Mime::ENCODING_8BIT;
public $id;
public $disposition;
public $filename;
public $description;
public $charset;
public $boundary;
public $location;
public $language;
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mime.part.methods"></a>49.3.3. Métodos para renderizar la parte del mensaje como una cadena</h3></div></div></div>
<p>
            <code class="methodname">getContent()</code> devuelve el contenido codificado del
            MimePart como una cadena, usando la codificación especificada en el atributo
            $encoding. Los valores válidos son Zend_Mime::ENCODING_*. No se realizan
            conversiones de conjunto de caracteres.
        </p>
<p>
            <code class="methodname">getHeaders()</code> devuelve las cabeceras Mime para el
            MimePart, generadas a partir de la información en los atributos públicamente
            accesibles. Los atributos del objeto deben establecerse correctamente antes
            de invocar este método.

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="varname">$charset</code> debe establecerse con el conjunto de caracteres real del
                        contenido si es de tipo texto (Text o <acronym class="acronym">HTML</acronym>).
                    </p></li>
<li class="listitem"><p>
                        <code class="varname">$id</code> puede establecerse para identificar un content-id para imágenes
                        incrustadas en un correo <acronym class="acronym">HTML</acronym>.
                    </p></li>
<li class="listitem"><p>
                        <code class="varname">$filename</code>
                        contiene el nombre que tendrá el archivo al descargarlo.
                    </p></li>
<li class="listitem"><p>
                        <code class="varname">$disposition</code> define si el archivo debe tratarse como un
                        adjunto o si se usa dentro del correo (HTML) (en línea).
                    </p></li>
<li class="listitem"><p>
                        <code class="varname">$description</code>
                        solo se utiliza con fines informativos.
                    </p></li>
<li class="listitem"><p>
                        <code class="varname">$boundary</code>
                        define la cadena que se usará como límite (boundary).
                    </p></li>
<li class="listitem"><p>
                        <code class="varname">$location</code> puede usarse como <acronym class="acronym">URI</acronym> de recurso
                        que tiene relación con el contenido.
                    </p></li>
<li class="listitem"><p>
                        <code class="varname">$language</code>
                        define los idiomas del contenido.
                    </p></li>
</ul></div>
<p>
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mime.message.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mime.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mobile.push.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">49.2. Zend_Mime_Message </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 50. Zend_Mobile_Push</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
