<?php $title = 'Capítulo 37. Zend_Gdata'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 37. Zend_Gdata</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.form.advanced.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.gdata.analytics.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.gdata"></a>Capítulo 37. Zend_Gdata</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.gdata.phtml#zend.gdata.introduction">37.1. Introducción</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.structure">37.1.1. Estructura de Zend_Gdata</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.services">37.1.2. Interactuando con los servicios de Google</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.magicfactory">37.1.3. Obtener instancias de clases Zend_Gdata</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.authentication">37.1.4. Autenticación del cliente de Google Data</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.dependencies">37.1.5. Dependencias</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.creation">37.1.6. Crear un nuevo cliente Gdata</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.parameters">37.1.7. Parámetros de consulta comunes</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.getfeed">37.1.8. Obtener un feed</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.paging">37.1.9. Trabajar con feeds de múltiples páginas</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.usefeedentry">37.1.10. Trabajar con datos en feeds y entradas</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.updateentry">37.1.11. Actualizar entradas</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.post">37.1.12. Publicar entradas en los servidores de Google</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.phtml#zend.gdata.introduction.delete">37.1.13. Eliminar entradas en los servidores de Google</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.analytics.phtml">37.2. Usar Google Analytics</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.analytics.phtml#zend.gdata.analytics.accounts">37.2.1. Recuperar datos de cuenta</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.analytics.phtml#zend.gdata.analytics.reports">37.2.2. Recuperar datos de informes</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.authsub.phtml">37.3. Autenticación con AuthSub</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.authsub.phtml#zend.gdata.authsub.login">37.3.1. Crear un cliente Http autenticado con AuthSub</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.authsub.phtml#zend.gdata.authsub.logout">37.3.2. Revocar la autenticación de AuthSub</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.books.phtml">37.4. Usar la API de datos de Book Search</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.books.phtml#zend.gdata.books.authentication">37.4.1. Autenticarse en el servicio Book Search</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.books.phtml#zend.gdata.books.searching_for_books">37.4.2. Buscar libros</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.gdata.books.phtml#zend.gdata.books.partner_restrict">37.4.2.1. Búsqueda de socio de marca compartida</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.gdata.books.phtml#zend.gdata.books.community_features">37.4.3. Usar funciones de comunidad</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.books.phtml#zend.gdata.books.adding_ratings">37.4.3.1. Añadir una valoración</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.books.phtml#zend.gdata.books.reviews">37.4.3.2. Reseñas</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.gdata.books.phtml#zend.gdata.books.adding_review">37.4.3.2.1. Añadir una reseña</a></span></dt>
<dt><span class="sect4"><a href="zend.gdata.books.phtml#zend.gdata.books.editing_review">37.4.3.2.2. Editar una reseña</a></span></dt>
</dl></dd>
<dt><span class="sect3"><a href="zend.gdata.books.phtml#zend.gdata.books.labels">37.4.3.3. Etiquetas</a></span></dt>
<dd><dl><dt><span class="sect4"><a href="zend.gdata.books.phtml#zend.gdata.books.submitting_labels">37.4.3.3.1. Enviar un conjunto de etiquetas</a></span></dt></dl></dd>
<dt><span class="sect3"><a href="zend.gdata.books.phtml#zend.gdata.books.retrieving_annotations">37.4.3.4. Recuperar anotaciones: reseñas, valoraciones y etiquetas</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.books.phtml#zend.gdata.books.deleting_annotations">37.4.3.5. Eliminar anotaciones</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.books.phtml#zend.gdata.books.sharing_with_my_library">37.4.4. Colecciones de libros y My Library</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.books.phtml#zend.gdata.books.retrieving_books_in_library">37.4.4.1. Recuperar los libros de la biblioteca de un usuario</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.gdata.books.phtml#zend.gdata.books.retrieving_all_books_in_library">37.4.4.1.1. Recuperar todos los libros de la biblioteca de un usuario</a></span></dt>
<dt><span class="sect4"><a href="zend.gdata.books.phtml#zend.gdata.books.retrieving_books_in_library_with_query">37.4.4.1.2. Buscar libros en la biblioteca de un usuario</a></span></dt>
</dl></dd>
<dt><span class="sect3"><a href="zend.gdata.books.phtml#zend.gdata.books.updating_library">37.4.4.2. Actualizar libros en la biblioteca de un usuario</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.gdata.books.phtml#zend.gdata.books.library_book_add">37.4.4.2.1. Añadir un libro a una biblioteca</a></span></dt>
<dt><span class="sect4"><a href="zend.gdata.books.phtml#zend.gdata.books.library_book_remove">37.4.4.2.2. Eliminar un libro de una biblioteca</a></span></dt>
</dl></dd>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.clientlogin.phtml">37.5. Autenticación con ClientLogin</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.clientlogin.phtml#zend.gdata.clientlogin.login">37.5.1. Crear un cliente Http autenticado con ClientLogin</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.clientlogin.phtml#zend.gdata.clientlogin.terminating">37.5.2. Finalizar un cliente Http autenticado con ClientLogin</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.calendar.phtml">37.6. Usar Google Calendar</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.connecting">37.6.1. Conectar con el servicio Calendar</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.connecting.authentication">37.6.1.1. Autenticación</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.connecting.service">37.6.1.2. Crear una instancia de servicio</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar_retrieval">37.6.2. Recuperar una lista de calendarios</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.calendar.phtml#zend.gdata.event_retrieval">37.6.3. Recuperar eventos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.event_retrieval.queries">37.6.3.1. Consultas</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.event_retrieval.start_time">37.6.3.2. Recuperar eventos por orden de hora de inicio</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.event_retrieval.date_range">37.6.3.3. Recuperar eventos en un rango de fechas especificado</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.event_retrieval.fulltext">37.6.3.4. Recuperar eventos mediante consulta de texto completo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.event_retrieval.individual">37.6.3.5. Recuperar eventos individuales</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.creating_events">37.6.4. Crear eventos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.creating_events.single">37.6.4.1. Crear eventos de ocurrencia única</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.creating_events.schedulers_reminders">37.6.4.2. Horarios y recordatorios de eventos</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.creating_events.recurring">37.6.4.3. Crear eventos recurrentes</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.creating_events.quickadd">37.6.4.4. Usar QuickAdd</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.modifying_events">37.6.5. Modificar eventos</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.deleting_events">37.6.6. Eliminar eventos</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.calendar.phtml#zend.gdata.calendar.comments">37.6.7. Acceder a los comentarios de eventos</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.docs.phtml">37.7. Usar la API de datos de Google Documents List</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.docs.phtml#zend.gdata.docs.listdocuments">37.7.1. Obtener una lista de documentos</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.docs.phtml#zend.gdata.docs.creating">37.7.2. Subir un documento</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.docs.phtml#zend.gdata.docs.queries">37.7.3. Buscar en el feed de documentos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.docs.phtml#zend.gdata.docs.listwpdocuments">37.7.3.1. Obtener una lista de documentos de procesamiento de texto</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.docs.phtml#zend.gdata.docs.listspreadsheets">37.7.3.2. Obtener una lista de hojas de cálculo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.docs.phtml#zend.gdata.docs.textquery">37.7.3.3. Realizar una consulta de texto</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.spreadsheets.phtml">37.8. Usar Google Spreadsheets</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.creating">37.8.1. Crear una hoja de cálculo</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listspreadsheets">37.8.2. Obtener una lista de hojas de cálculo</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listworksheets">37.8.3. Obtener una lista de hojas de trabajo</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listfeeds">37.8.4. Interactuar con feeds basados en listas</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listfeeds.get">37.8.4.1. Obtener un feed basado en lista</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listfeeds.reverse">37.8.4.2. Ordenar filas de forma inversa</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listfeeds.sq">37.8.4.3. Enviar una consulta estructurada</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listfeeds.addrow">37.8.4.4. Añadir una fila</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listfeeds.editrow">37.8.4.5. Editar una fila</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.listfeeds.deleterow">37.8.4.6. Eliminar una fila</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.cellfeeds">37.8.5. Interactuar con feeds basados en celdas</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.cellfeeds.get">37.8.5.1. Obtener un feed basado en celdas</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.cellfeeds.cellrangequery">37.8.5.2. Enviar una consulta de rango de celdas</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.spreadsheets.phtml#zend.gdata.spreadsheets.cellfeeds.updatecell">37.8.5.3. Cambiar el contenido de una celda</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.gapps.phtml">37.9. Usar Google Apps Provisioning</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.domain">37.9.1. Establecer el dominio actual</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.domain.service">37.9.1.1. Establecer el dominio para la clase de servicio</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.domain.query">37.9.1.2. Establecer el dominio para las clases de consulta</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users">37.9.2. Interactuar con usuarios</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.creating">37.9.2.1. Crear una cuenta de usuario</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.retrieving">37.9.2.2. Recuperar una cuenta de usuario</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.retrievingAll">37.9.2.3. Recuperar todos los usuarios de un dominio</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.updating">37.9.2.4. Actualizar una cuenta de usuario</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.updating.resettingPassword">37.9.2.4.1. Restablecer la contraseña de un usuario</a></span></dt>
<dt><span class="sect4"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.updating.forcingPasswordChange">37.9.2.4.2. Forzar a un usuario a cambiar su contraseña</a></span></dt>
<dt><span class="sect4"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.updating.suspendingAccount">37.9.2.4.3. Suspender una cuenta de usuario</a></span></dt>
<dt><span class="sect4"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.updating.grantingAdminRights">37.9.2.4.4. Conceder derechos administrativos</a></span></dt>
</dl></dd>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.users.deleting">37.9.2.5. Eliminar cuentas de usuario</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.nicknames">37.9.3. Interactuar con apodos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.nicknames.creating">37.9.3.1. Crear un apodo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.nicknames.retrieving">37.9.3.2. Recuperar un apodo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.nicknames.retrievingUser">37.9.3.3. Recuperar todos los apodos de un usuario</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.nicknames.retrievingAll">37.9.3.4. Recuperar todos los apodos de un dominio</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.nicknames.deleting">37.9.3.5. Eliminar un apodo</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groups">37.9.4. Interactuar con grupos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groups.creating">37.9.4.1. Crear un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groups.retrieveGroup">37.9.4.2. Recuperar un grupo individual</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groups.retrievingAll">37.9.4.3. Recuperar todos los grupos de un dominio</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groups.deleting">37.9.4.4. Eliminar un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groups.updating">37.9.4.5. Actualizar un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groups.retrieve">37.9.4.6. Recuperar todos los grupos a los que pertenece una persona</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupMembers">37.9.5. Interactuar con miembros de grupo</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupMembers.adding">37.9.5.1. Añadir un miembro a un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupMembers.check">37.9.5.2. Comprobar si un miembro pertenece a un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupMembers.removing">37.9.5.3. Eliminar un miembro de un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupMembers.retrieving">37.9.5.4. Recuperar la lista de miembros de un grupo</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupOwners">37.9.6. Interactuar con propietarios de grupo</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupOwners.adding">37.9.6.1. Añadir un propietario a un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupOwners.retrieving">37.9.6.2. Recuperar la lista de propietarios de un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupOwners.check">37.9.6.3. Comprobar si un correo electrónico es propietario de un grupo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.groupOwners.removing">37.9.6.4. Eliminar un propietario de un grupo</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailLists">37.9.7. Interactuar con listas de correo</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailLists.creating">37.9.7.1. Crear una lista de correo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailList.retrieve">37.9.7.2. Recuperar todas las listas de correo a las que está suscrito un destinatario</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailLists.retrievingAll">37.9.7.3. Recuperar todas las listas de correo de un dominio</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailList.deleting">37.9.7.4. Eliminar una lista de correo</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailListRecipients">37.9.8. Interactuar con destinatarios de listas de correo</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailListRecipients.adding">37.9.8.1. Añadir un destinatario a una lista de correo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailListRecipients.retrieving">37.9.8.2. Recuperar la lista de suscriptores de una lista de correo</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.emailListRecipients.removing">37.9.8.3. Eliminar un destinatario de una lista de correo</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.gapps.phtml#zend.gdata.gapps.exceptions">37.9.9. Gestión de errores</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.photos.phtml">37.10. Usar Picasa Web Albums</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.gdata.photos.phtml#zend.gdata.photos.connecting">37.10.1. Conectar con el servicio</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.connecting.authentication">37.10.1.1. Autenticación</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.connecting.service">37.10.1.2. Crear una instancia de servicio</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.photos.phtml#zend.gdata.photos.queries">37.10.2. Comprender y construir consultas</a></span></dt>
<dt><span class="sect2"><a href="zend.gdata.photos.phtml#zend.gdata.photos.retrieval">37.10.3. Recuperar feeds y entradas</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.user_retrieval">37.10.3.1. Recuperar un usuario</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.album_retrieval">37.10.3.2. Recuperar un álbum</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.photo_retrieval">37.10.3.3. Recuperar una foto</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.comment_retrieval">37.10.3.4. Recuperar un comentario</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.tag_retrieval">37.10.3.5. Recuperar una etiqueta</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.photos.phtml#zend.gdata.photos.creation">37.10.4. Crear entradas</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.album_creation">37.10.4.1. Crear un álbum</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.photo_creation">37.10.4.2. Crear una foto</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.comment_creation">37.10.4.3. Crear un comentario</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.tag_creation">37.10.4.4. Crear una etiqueta</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.gdata.photos.phtml#zend.gdata.photos.deletion">37.10.5. Eliminar entradas</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.album_deletion">37.10.5.1. Eliminar un álbum</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.photo_deletion">37.10.5.2. Eliminar una foto</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.comment_deletion">37.10.5.3. Eliminar un comentario</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.tag_deletion">37.10.5.4. Eliminar una etiqueta</a></span></dt>
<dt><span class="sect3"><a href="zend.gdata.photos.phtml#zend.gdata.photos.optimistic_concurrenty">37.10.5.5. Concurrencia optimista (notas sobre la eliminación)</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.gdata.exception.phtml">37.11. Capturar excepciones de Gdata</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.gdata.introduction"></a>37.1. Introducción</h2></div></div></div>
<p>
        Las <acronym class="acronym">API</acronym>s de Google Data proporcionan una interfaz programática para algunos de los
        servicios en línea de Google. El protocolo Google data se basa en el <a class="ulink" href="http://ietfreport.isoc.org/idref/draft-ietf-atompub-protocol/" target="_top">Atom Publishing
            Protocol</a> y permite a las aplicaciones cliente recuperar datos que coincidan con consultas,
        publicar datos, actualizar datos y eliminar datos usando <acronym class="acronym">HTTP</acronym> estándar y el
        formato de sindicación Atom. El componente <code class="classname">Zend_Gdata</code> es una
        interfaz de <acronym class="acronym">PHP</acronym> 5 para acceder a Google Data desde <acronym class="acronym">PHP</acronym>.
        El componente <code class="classname">Zend_Gdata</code> también admite el acceso a otros servicios
        que implementan el Atom Publishing Protocol.
    </p>
<p>
        Consulte
        <a class="ulink" href="http://code.google.com/apis/gdata/" target="_top">http://code.google.com/apis/gdata/</a>
        para más información sobre las <acronym class="acronym">API</acronym>s de Google Data.
    </p>
<p>
        Los servicios accesibles mediante <code class="classname">Zend_Gdata</code> incluyen los
        siguientes:

        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <a class="link" href="zend.gdata.calendar.phtml" title="37.6. Using Google Calendar">Google Calendar</a>
                    es una popular aplicación de calendario en línea.
                </p></li>
<li class="listitem"><p>
                    <a class="link" href="zend.gdata.spreadsheets.phtml" title="37.8. Using Google Spreadsheets">Google Spreadsheets</a>
                    proporciona una herramienta colaborativa de hojas de cálculo en línea que
                    puede usarse como un simple almacén de datos para sus aplicaciones.
                </p></li>
<li class="listitem"><p>
                    <a class="link" href="zend.gdata.docs.phtml" title="37.7. Using Google Documents List Data API">Google Documents List</a>
                    proporciona una lista en línea de todas las hojas de cálculo, documentos de procesamiento de texto
                    y presentaciones almacenadas en una cuenta de Google.
                </p></li>
<li class="listitem"><p>
                    <a class="link" href="zend.gdata.gapps.phtml" title="37.9. Using Google Apps Provisioning">Google Provisioning</a>
                    proporciona la capacidad de crear, recuperar, actualizar y
                    eliminar cuentas de usuario, apodos, grupos y listas de correo en un
                    dominio alojado por Google Apps.
                </p></li>
<li class="listitem"><p>
                    <a class="link" href="zend.gdata.photos.phtml" title="37.10. Using Picasa Web Albums">Picasa Web Albums</a>
                    proporciona una aplicación de intercambio de fotos en línea.
                </p></li>
<li class="listitem"><p>
                    <a class="link" href="zend.gdata.analytics.phtml" title="37.2. Using Google Analytics">Google Analytics</a>
                    es una aplicación de estadísticas de visitantes.
                </p></li>
<li class="listitem"><p>
                    <a class="ulink" href="http://code.google.com/apis/blogger/developers_guide_php.html" target="_top">Google
                        Blogger</a> es un popular proveedor de Internet de
                    "publicación con un solo clic" y sindicación.
                </p></li>
<li class="listitem"><p>
                    Google CodeSearch
                    le permite buscar código fuente público de muchos proyectos.
                </p></li>
<li class="listitem"><p>
                    Google Notebook
                    le permite ver contenido público de Notebook.
                </p></li>
</ul></div>
<p>
    </p>
<div class="note"><table border="0" summary="Note: Unsupported services">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Servicios no admitidos</th>
</tr>
<tr><td align="left" valign="top"><p>
            <code class="classname">Zend_Gdata</code> no proporciona una interfaz para ningún otro servicio de
            Google, como Search, Gmail, Translation o Maps.
            Solo se admiten los servicios que soportan la Google Data <acronym class="acronym">API</acronym>.
        </p></td></tr>
</table></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.structure"></a>37.1.1. Estructura de Zend_Gdata</h3></div></div></div>
<p>
            <code class="classname">Zend_Gata</code> se compone de varios tipos de clases:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        Clases de servicio - heredan de <code class="classname">Zend_Gdata_App</code>.
                        Estas también incluyen otras clases como <code class="classname">Zend_Gdata</code>,
                        <code class="classname">Zend_Gdata_Spreadsheets</code>, etc. Estas clases permiten
                        interactuar con los servicios APP o GData y proporcionan la
                        capacidad de recuperar feeds, recuperar entradas, publicar
                        entradas, actualizar entradas y eliminar entradas.
                    </p></li>
<li class="listitem"><p>
                        Clases de consulta - heredan de <code class="classname">Zend_Gdata_Query</code>.
                        Estas también incluyen otras clases para servicios específicos,
                        como <code class="classname">Zend_Gdata_Spreadsheets_ListQuery</code> y
                        <code class="classname">Zend_Gdata_Spreadsheets_CellQuery</code>. Las clases de consulta
                        proporcionan métodos usados para construir una consulta de datos
                        a recuperar de los servicios GData. Los métodos incluyen
                        getters y setters como <code class="methodname">setUpdatedMin()</code>,
                        <code class="methodname">setStartIndex()</code>, y
                        <code class="methodname">getPublishedMin()</code>. Las clases de consulta también
                        tienen un método para generar una <acronym class="acronym">URL</acronym> que representa la
                        consulta construida -- <code class="methodname">getQueryUrl()</code>.
                        Alternativamente, el componente de cadena de consulta de la <acronym class="acronym">URL</acronym>
                        puede recuperarse usando el método
                        <code class="methodname">getQueryString()</code>.
                    </p></li>
<li class="listitem"><p>
                        Clases de feed - heredan de <code class="classname">Zend_Gdata_App_Feed</code>.
                        Estas también incluyen otras clases como
                        <code class="classname">Zend_Gdata_Feed</code>,
                        <code class="classname">Zend_Gdata_Spreadsheets_SpreadsheetFeed</code>,
                        y <code class="classname">Zend_Gdata_Spreadsheets_ListFeed</code>.
                        Estas clases representan feeds de entradas recuperadas
                        de los servicios. Se usan principalmente para recuperar
                        datos devueltos por los servicios.
                    </p></li>
<li class="listitem"><p>
                        Clases de entrada - heredan de <code class="classname">Zend_Gdata_App_Entry</code>.
                        Estas también incluyen otras clases como
                        <code class="classname">Zend_Gdata_Entry</code>, y
                        <code class="classname">Zend_Gdata_Spreadsheets_ListEntry</code>.
                        Estas clases representan entradas recuperadas de
                        servicios o usadas para construir datos que se enviarán a
                        los servicios. Además de poder establecer las
                        propiedades de una entrada (como el valor de una celda
                        de hoja de cálculo), puede usar un objeto de entrada para enviar solicitudes de
                        actualización o eliminación a un servicio. Por ejemplo,
                        puede llamar a <span class="command"><strong>$entry-&gt;save()</strong></span> para guardar
                        los cambios realizados en una entrada de vuelta al servicio del cual
                        se originó la entrada, o <span class="command"><strong>$entry-&gt;delete()</strong></span>
                        para eliminar una entrada del servidor.
                    </p></li>
<li class="listitem"><p>
                        Otras clases de modelo de datos - heredan de
                        <code class="classname">Zend_Gdata_App_Extension</code>. Estas incluyen clases
                        como <code class="classname">Zend_Gdata_App_Extension_Title</code> (representando el
                        elemento <acronym class="acronym">XML</acronym> atom:title),
                        <code class="classname">Zend_Gdata_Extension_When</code>
                        (representando el elemento <acronym class="acronym">XML</acronym> gd:when usado por el
                        "Kind" de evento GData), y
                        <code class="classname">Zend_Gdata_Extension_Cell</code> (representando el elemento
                        <acronym class="acronym">XML</acronym> gs:cell usado por Google Spreadsheets). Estas
                        clases se usan puramente para almacenar los datos recuperados
                        de los servicios y para construir los datos que se
                        enviarán a los servicios. Estas incluyen getters y setters
                        como
                        <code class="methodname">setText()</code> para establecer el nodo de texto hijo
                        de un elemento, <code class="methodname">getText()</code> para recuperar
                        el nodo de texto de un elemento, <code class="methodname">getStartTime()</code>
                        para recuperar el atributo de hora de inicio de un elemento When,
                        y otros métodos similares.
                        Las clases de modelo de datos también incluyen métodos como
                        <code class="methodname">getDOM()</code> para recuperar una representación DOM
                        del elemento y todos sus hijos y
                        <code class="methodname">transferFromDOM()</code> para construir una representación
                        de modelo de datos de un árbol DOM.
                    </p></li>
</ul></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.services"></a>37.1.2. Interactuando con los servicios de Google</h3></div></div></div>
<p>
            Los servicios de Google data se basan en el Atom Publishing Protocol
            (APP) y el formato de sindicación Atom. Para interactuar con los servicios APP o
            de Google usando el componente <code class="classname">Zend_Gdata</code>, necesita usar
            las clases de servicio como <code class="classname">Zend_Gdata_App</code>,
            <code class="classname">Zend_Gdata</code>, <code class="classname">Zend_Gdata_Spreadsheets</code>, etc.
            Estas clases de servicio proporcionan métodos para recuperar datos de los servicios como feeds, insertar
            nuevas entradas en feeds, actualizar entradas y eliminar entradas.
        </p>
<p>
            Nota: Un ejemplo completo de trabajo con <code class="classname">Zend_Gdata</code> está disponible en
            el directorio <code class="filename">demos/Zend/Gdata</code>. Este ejemplo puede ejecutarse
            desde la línea de comandos, pero los métodos contenidos en él son fácilmente
            portables a una aplicación web.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.magicfactory"></a>37.1.3. Obtener instancias de clases Zend_Gdata</h3></div></div></div>
<p>
            Los estándares de nomenclatura de Zend Framework requieren que todas las clases se
            nombren según la estructura de directorios en la que están ubicadas.
            Por ejemplo, las extensiones relacionadas con Spreadsheets se almacenan en:
            <code class="filename">Zend/Gdata/Spreadsheets/Extension/...</code> y, como resultado
            de esto, se nombran
            <code class="classname">Zend_Gdata_Spreadsheets_Extension_...</code>.
            ¡Esto provoca mucha escritura si intenta construir una nueva
            instancia de un elemento de celda de hoja de cálculo!
        </p>
<p>
            Hemos implementado un método de fábrica mágico en todas las clases de servicio
            (como <code class="classname">Zend_Gdata_App</code>, <code class="classname">Zend_Gdata</code>,
            <code class="classname">Zend_Gdata_Spreadsheets</code>) que debería facilitar mucho la construcción de nuevas
            instancias de clases de modelo de datos, consulta y otras. Esta fábrica mágica está
            implementada usando el método mágico <code class="methodname">__call()</code> para interceptar todos los
            intentos de llamar a <span class="command"><strong>$service-&gt;newXXX(arg1, arg2, ...)</strong></span>. Según
            el valor de XXX, se realiza una búsqueda en todos los 'paquetes' registrados
            para la clase deseada. Aquí hay algunos ejemplos:
        </p>
<pre class="programlisting">
$ss = new Zend_Gdata_Spreadsheets();

// creates a Zend_Gdata_App_Spreadsheets_CellEntry
$entry = $ss-&gt;newCellEntry();

// creates a Zend_Gdata_App_Spreadsheets_Extension_Cell
$cell = $ss-&gt;newCell();
$cell-&gt;setText('My cell value');
$cell-&gt;setRow('1');
$cell-&gt;setColumn('3');
$entry-&gt;cell = $cell;

// ... $entry can then be used to send an update to a Google Spreadsheet
</pre>
<p>
            Cada clase de servicio en el árbol de herencia es responsable de
            registrar los 'paquetes' (directorios) apropiados que deben
            buscarse al llamar al método de fábrica mágico.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.authentication"></a>37.1.4. Autenticación del cliente de Google Data</h3></div></div></div>
<p>
            La mayoría de los servicios de Google Data requieren que las aplicaciones cliente
            se autentiquen contra el servidor de Google antes de acceder a
            datos privados, o guardar o eliminar datos.
            Hay dos implementaciones de autenticación para Google Data:
            <a class="link" href="zend.gdata.authsub.phtml" title="37.3. Authenticating with AuthSub">AuthSub</a> y
            <a class="link" href="zend.gdata.clientlogin.phtml" title="37.5. Authenticating with ClientLogin">ClientLogin</a>.
            <code class="classname">Zend_Gdata</code> ofrece interfaces de clase para ambos métodos.
        </p>
<p>
            La mayoría de los demás tipos de consultas contra servicios de Google Data no
            requieren autenticación.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.dependencies"></a>37.1.5. Dependencias</h3></div></div></div>
<p>
            <code class="classname">Zend_Gdata</code> hace uso de
            <a class="link" href="zend.http.phtml#zend.http.client" title="38.1. Introduction">Zend_Http_Client</a> para enviar
            solicitudes a google.com y obtener resultados. La respuesta a la mayoría de las
            solicitudes de Google Data se devuelve como una subclase de las
            clases <code class="classname">Zend_Gdata_App_Feed</code> o
            <code class="classname">Zend_Gdata_App_Entry</code>.
        </p>
<p>
            <code class="classname">Zend_Gdata</code> asume que su aplicación <acronym class="acronym">PHP</acronym> se
            ejecuta en un host que tiene una conexión directa a Internet.
            El cliente <code class="classname">Zend_Gdata</code> funciona contactando con los servidores de Google Data.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.creation"></a>37.1.6. Crear un nuevo cliente Gdata</h3></div></div></div>
<p>
            Cree un nuevo objeto de la clase <code class="classname">Zend_Gdata_App</code>,
            <code class="classname">Zend_Gdata</code>, o una de las subclases disponibles que ofrecen métodos auxiliares
            para el comportamiento específico del servicio.
        </p>
<p>
            El único parámetro opcional del constructor de <code class="classname">Zend_Gdata_App</code>
            es una instancia de
            <a class="link" href="zend.http.phtml#zend.http.client" title="38.1. Introduction">Zend_Http_Client</a>.
            Si no pasa este parámetro, <code class="classname">Zend_Gdata</code> crea un objeto
            <code class="classname">Zend_Http_Client</code> por defecto, que no tendrá credenciales
            asociadas para acceder a feeds privados. Especificar el
            objeto <code class="classname">Zend_Http_Client</code> también le permite
            pasar opciones de configuración a ese objeto cliente.
        </p>
<pre class="programlisting">
$client = new Zend_Http_Client();
$client-&gt;setConfig( ...options... );

$gdata = new Zend_Gdata($client);
</pre>
<p>
            A partir de Zend Framework 1.7, se ha añadido soporte para
            el versionado de protocolo. Esto permite que el cliente y el servidor admitan
            nuevas funciones manteniendo la compatibilidad hacia atrás. Aunque la mayoría de los
            servicios gestionarán esto por usted, si crea una instancia de <code class="classname">Zend_Gdata</code>
            directamente (a diferencia de una de sus subclases), es posible que
            necesite especificar la versión de protocolo deseada para acceder a cierta
            funcionalidad del servidor.
        </p>
<pre class="programlisting">
$client = new Zend_Http_Client();
$client-&gt;setConfig( ...options... );

$gdata = new Zend_Gdata($client);
$gdata-&gt;setMajorProtocolVersion(2);
$gdata-&gt;setMinorProtocolVersion(null);
</pre>
<p>
            Vea también las secciones sobre autenticación para métodos que
            crean un objeto <code class="classname">Zend_Http_Client</code> autenticado.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.parameters"></a>37.1.7. Parámetros de consulta comunes</h3></div></div></div>
<p>
            Puede especificar parámetros para personalizar consultas con <code class="classname">Zend_Gdata</code>.
            Los parámetros de consulta se especifican usando subclases de
            <code class="classname">Zend_Gdata_Query</code>. La clase <code class="classname">Zend_Gdata_Query</code>
            incluye métodos para establecer todos los parámetros de consulta usados en los servicios GData.
            Los servicios individuales, como Spreadsheets, también proporcionan clases de consulta para definir
            parámetros personalizados para el servicio y feeds concretos.
            Spreadsheets incluye una clase CellQuery para consultar el feed Cell
            y una clase ListQuery para consultar el feed List, ya que diferentes
            parámetros de consulta son aplicables a cada uno de esos tipos de feed.

            Los parámetros de GData a nivel general se describen a continuación.
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>
                    El parámetro <span class="property">q</span> especifica una
                    consulta de texto completo. El valor del parámetro es una cadena.
                </p>
<p>
                    Establezca este parámetro con la función <code class="methodname">setQuery()</code>.
                </p>
</li>
<li class="listitem">
<p>
                    El parámetro <span class="property">alt</span> especifica el tipo de feed.
                    El valor del parámetro puede ser <span class="property">atom</span>,
                    <span class="property">rss</span>, <span class="property">json</span>,
                    o <span class="property">json-in-script</span>.
                    Si no especifica este parámetro, el tipo de feed predeterminado
                    es <span class="property">atom</span>. NOTA: Solo la salida del
                    formato de feed atom puede procesarse usando
                    <code class="classname">Zend_Gdata</code>.
                    El <code class="classname">Zend_Http_Client</code> podría usarse para recuperar
                    feeds en otros formatos, usando <acronym class="acronym">URL</acronym>s de consulta generadas por la
                    clase <code class="classname">Zend_Gdata_Query</code> y sus subclases.
                </p>
<p>
                    Establezca este parámetro con la función <code class="methodname">setAlt()</code>.
                </p>
</li>
<li class="listitem">
<p>
                    El parámetro <span class="property">maxResults</span> limita el número
                    de entradas en el feed. El valor del parámetro es
                    un entero. El número de entradas devueltas en el feed
                    no superará este valor.
                </p>
<p>
                    Establezca este parámetro con la función <code class="methodname">setMaxResults()</code>.
                </p>
</li>
<li class="listitem">
<p>
                    El parámetro <span class="property">startIndex</span> especifica el
                    número ordinal de la primera entrada devuelta en el feed.
                    Las entradas anteriores a este número se omiten.
                </p>
<p>
                    Establezca este parámetro con la función <code class="methodname">setStartIndex()</code>.
                </p>
</li>
<li class="listitem">
<p>
                    Los parámetros <span class="property">updatedMin</span> y <span class="property">updatedMax</span>
                    especifican límites en la fecha de la entrada.
                    Si especifica un valor para <span class="property">updatedMin</span>,
                    no se incluirán en el feed las entradas actualizadas antes
                    de la fecha que especifique. Del mismo modo,
                    no se incluirán las entradas actualizadas después de la fecha especificada por
                    <span class="property">updatedMax</span>.
                </p>
<p>
                    Puede usar marcas de tiempo numéricas, o una variedad de
                    representaciones de cadena de fecha/hora como valor para
                    estos parámetros.
                </p>
<p>
                    Establezca este parámetro con las funciones <code class="methodname">setUpdatedMin()</code>
                    y <code class="methodname">setUpdatedMax()</code>.
                </p>
</li>
</ul></div>
<p>
            Hay una función <code class="methodname">get*()</code> por cada
            función <code class="methodname">set*()</code>.
        </p>
<pre class="programlisting">
$query = new Zend_Gdata_Query();
$query-&gt;setMaxResults(10);
echo $query-&gt;getMaxResults();   // returns 10
</pre>
<p>
            La clase <code class="classname">Zend_Gdata</code> también implementa métodos "mágicos" de
            getter y setter, por lo que puede usar el nombre del parámetro
            como un miembro virtual de la clase.
        </p>
<pre class="programlisting">
$query = new Zend_Gdata_Query();
$query-&gt;maxResults = 10;
echo $query-&gt;maxResults;        // returns 10
</pre>
<p>
            Puede borrar todos los parámetros con la función <code class="methodname">resetParameters()</code>.
            Esto es útil si reutiliza un objeto <code class="classname">Zend_Gdata</code>
            para varias consultas.
        </p>
<pre class="programlisting">
$query = new Zend_Gdata_Query();
$query-&gt;maxResults = 10;
// ...get feed...

$query-&gt;resetParameters();      // clears all parameters
// ...get a different feed...
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.getfeed"></a>37.1.8. Obtener un feed</h3></div></div></div>
<p>
            Use la función <code class="methodname">getFeed()</code> para recuperar
            un feed desde una <acronym class="acronym">URI</acronym> especificada.
            Esta función devuelve una instancia de la clase especificada
            como segundo argumento de getFeed, que por defecto es
            <code class="classname">Zend_Gdata_Feed</code>.
        </p>
<pre class="programlisting">
$gdata = new Zend_Gdata();
$query = new Zend_Gdata_Query(
        'http://www.blogger.com/feeds/blogID/posts/default');
$query-&gt;setMaxResults(10);
$feed = $gdata-&gt;getFeed($query);
</pre>
<p>
            Vea las secciones posteriores para funciones especiales en cada
            clase auxiliar para los servicios de Google Data. Estas
            funciones le ayudan a obtener feeds desde la <acronym class="acronym">URI</acronym> apropiada
            para el servicio respectivo.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.paging"></a>37.1.9. Trabajar con feeds de múltiples páginas</h3></div></div></div>
<p>
            Al recuperar un feed que contiene un gran número de entradas,
            el feed puede dividirse en varias "páginas" más pequeñas de feeds. Cuando
            esto ocurre, cada página contendrá un enlace a la siguiente página en la
            serie. Se puede acceder a este enlace llamando a
            <code class="methodname">getLink('next')</code>. El siguiente ejemplo muestra cómo
            recuperar la siguiente página de un feed:
        </p>
<pre class="programlisting">
function getNextPage($feed) {
    $nextURL = $feed-&gt;getLink('next');
    if ($nextURL !== null) {
        return $gdata-&gt;getFeed($nextURL);
    } else {
        return null;
    }
}
</pre>
<p>
            Si prefiere no trabajar con páginas en su aplicación,
            pase la primera página del feed a
            <code class="methodname">Zend_Gdata_App::retrieveAllEntriesForFeed()</code>, que
            consolidará todas las entradas de cada página en un único feed.
            Este ejemplo muestra cómo usar esta función:
        </p>
<pre class="programlisting">
$gdata = new Zend_Gdata();
$query = new Zend_Gdata_Query(
        'http://www.blogger.com/feeds/blogID/posts/default');
$feed = $gdata-&gt;retrieveAllEntriesForFeed($gdata-&gt;getFeed($query));
</pre>
<p>
            Tenga en cuenta al llamar a esta función que puede tardar mucho
            tiempo en completarse en feeds grandes. Es posible que necesite aumentar el límite
            de tiempo de ejecución de <acronym class="acronym">PHP</acronym> llamando a <code class="methodname">set_time_limit()</code>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.usefeedentry"></a>37.1.10. Trabajar con datos en feeds y entradas</h3></div></div></div>
<p>
            Después de recuperar un feed, puede leer los datos del feed
            o las entradas contenidas en el feed usando los accesores
            definidos en cada una de las clases de modelo de datos o los accesores
            mágicos. Aquí hay un ejemplo:
        </p>
<pre class="programlisting">
$client = Zend_Gdata_ClientLogin::getHttpClient($user, $pass, $service);
$gdata = new Zend_Gdata($client);
$query = new Zend_Gdata_Query(
        'http://www.blogger.com/feeds/blogID/posts/default');
$query-&gt;setMaxResults(10);
$feed = $gdata-&gt;getFeed($query);
foreach ($feed as $entry) {
    // using the magic accessor
    echo 'Title: ' . $entry-&gt;title-&gt;text;
    // using the defined accessors
    echo 'Content: ' . $entry-&gt;getContent()-&gt;getText();
}
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.updateentry"></a>37.1.11. Actualizar entradas</h3></div></div></div>
<p>
            Después de recuperar una entrada, puede actualizar esa entrada y guardar
            los cambios de vuelta en el servidor. Aquí hay un ejemplo:
        </p>
<pre class="programlisting">
$client = Zend_Gdata_ClientLogin::getHttpClient($user, $pass, $service);
$gdata = new Zend_Gdata($client);
$query = new Zend_Gdata_Query(
        'http://www.blogger.com/feeds/blogID/posts/default');
$query-&gt;setMaxResults(10);
$feed = $gdata-&gt;getFeed($query);
foreach ($feed as $entry) {
    // update the title to append 'NEW'
    echo 'Old Title: ' . $entry-&gt;title-&gt;text;
    $entry-&gt;title-&gt;text = $entry-&gt;title-&gt;text . ' NEW';

    // update the entry on the server
    $newEntry = $entry-&gt;save();
    echo 'New Title: ' . $newEntry-&gt;title-&gt;text;
}
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.post"></a>37.1.12. Publicar entradas en los servidores de Google</h3></div></div></div>
<p>
            El objeto <code class="classname">Zend_Gdata</code> tiene una función
            <code class="methodname">insertEntry()</code> con la que puede subir datos para guardar
            nuevas entradas en los servicios de Google Data.
        </p>
<p>
            Puede usar las clases de modelo de datos de cada servicio para construir
            la entrada apropiada que se publicará en los servicios de Google. La
            función <code class="methodname">insertEntry()</code> aceptará un hijo de
            <code class="classname">Zend_Gdata_App_Entry</code> como datos para publicar en el servicio.
            El método devuelve un hijo de <code class="classname">Zend_Gdata_App_Entry</code>
            que representa el estado de la entrada tal como fue devuelto por
            el servidor.
        </p>
<p>
            Alternativamente, podría construir la estructura <acronym class="acronym">XML</acronym> de una entrada
            como una cadena y pasar la cadena a la función
            <code class="methodname">insertEntry()</code>.
        </p>
<pre class="programlisting">
$gdata = new Zend_Gdata($authenticatedHttpClient);

$entry = $gdata-&gt;newEntry();
$entry-&gt;title = $gdata-&gt;newTitle('Playing football at the park');
$content =
    $gdata-&gt;newContent('We will visit the park and play football');
$content-&gt;setType('text');
$entry-&gt;content = $content;

$entryResult = $gdata-&gt;insertEntry($entry,
        'http://www.blogger.com/feeds/blogID/posts/default');

echo 'The &lt;id&gt; of the resulting entry is: ' . $entryResult-&gt;id-&gt;text;
</pre>
<p>
            Para publicar entradas, debe estar usando un
            <code class="classname">Zend_Http_Client</code> autenticado que haya creado usando las
            clases <code class="classname">Zend_Gdata_AuthSub</code> o
            <code class="classname">Zend_Gdata_ClientLogin</code>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.gdata.introduction.delete"></a>37.1.13. Eliminar entradas en los servidores de Google</h3></div></div></div>
<p>
            Opción 1: El objeto <code class="classname">Zend_Gdata</code> tiene una función
            <code class="methodname">delete()</code> con la que puede eliminar entradas de los servicios de Google Data.
            Pase el valor de la <acronym class="acronym">URL</acronym> de edición de
            una entrada de feed al método <code class="methodname">delete()</code>.
        </p>
<p>
            Opción 2: Alternativamente, puede llamar a <span class="command"><strong>$entry-&gt;delete()</strong></span>
            en una entrada recuperada de un servicio de Google.
        </p>
<pre class="programlisting">
$gdata = new Zend_Gdata($authenticatedHttpClient);
// a Google Data feed
$feedUri = ...;
$feed = $gdata-&gt;getFeed($feedUri);
foreach ($feed as $feedEntry) {
    // Option 1 - delete the entry directly
    $feedEntry-&gt;delete();
    // Option 2 - delete the entry by passing the edit URL to
    // $gdata-&gt;delete()
    // $gdata-&gt;delete($feedEntry-&gt;getEditLink()-&gt;href);
}
</pre>
<p>
            Para eliminar entradas, debe estar usando un
            <code class="classname">Zend_Http_Client</code> autenticado que haya creado usando las
            clases <code class="classname">Zend_Gdata_AuthSub</code> o
            <code class="classname">Zend_Gdata_ClientLogin</code>.
        </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.form.advanced.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.gdata.analytics.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">36.9. Uso avanzado de Zend_Form </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 37.2. Usar Google Analytics</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
