<?php $title = '64.11. Zend_Service_Amazon_Ec2: Direcciones IP elásticas'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.11. Zend_Service_Amazon_Ec2: Direcciones IP elásticas</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.amazon.ec2.ebs.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.amazon.ec2.keypairs.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.amazon.ec2.elasticip"></a>64.11. Zend_Service_Amazon_Ec2: Direcciones IP elásticas</h2></div></div></div>
<p>
        Por defecto, a todas las instancias de Amazon EC2 se les asignan dos direcciones IP al
        lanzarlas: una dirección privada (RFC 1918) y una dirección pública que se asigna
        a la dirección IP privada mediante Network Address Translation (NAT).
    </p>
<p>
        Si usa DNS dinámico para asociar un nombre DNS existente a la dirección IP pública
        de una nueva instancia, podría tardar hasta 24 horas en que la dirección IP se propague
        por Internet. Como resultado, las nuevas instancias podrían no recibir tráfico mientras que
        las instancias terminadas siguen recibiendo peticiones.
    </p>
<p>
        Para resolver este problema, Amazon EC2 proporciona direcciones IP elásticas. Las direcciones IP elásticas
        son direcciones IP estáticas diseñadas para la computación en la nube dinámica. Las direcciones IP elásticas
        están asociadas a su cuenta, no a instancias específicas. Cualquier dirección IP elástica
        que asocie a su cuenta permanece asociada a su cuenta hasta que la
        libere explícitamente. Sin embargo, a diferencia de las direcciones IP estáticas tradicionales, las direcciones IP
        elásticas le permiten enmascarar fallos de instancia o de zona de disponibilidad reasignando rápidamente
        sus direcciones IP públicas a cualquier instancia de su cuenta.
    </p>
<div class="example">
<a name="zend.service.amazon.ec2.elasticip.allocate"></a><p class="title"><b>Ejemplo 64.46. Asignando una nueva IP elástica</b></p>
<div class="example-contents">
<p>
            <code class="code">allocate</code> asignará a su cuenta una nueva dirección IP elástica.
        </p>
<p>
            <code class="code">allocate</code> devuelve la ip recién asignada.
        </p>
<pre class="programlisting">
$ec2_eip = new Zend_Service_Amazon_Ec2_Elasticip('aws_key','aws_secret_key');
$ip = $ec2_eip-&gt;allocate();

// print out your newly allocated elastic ip address;
print $ip;
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.service.amazon.ec2.elasticip.describe"></a><p class="title"><b>Ejemplo 64.47. Describiendo direcciones IP elásticas asignadas</b></p>
<div class="example-contents">
<p>
            <code class="code">describe</code> tiene un parámetro opcional para describir todas
            sus direcciones IP elásticas asignadas o solo algunas de sus
            direcciones asignadas.
        </p>
<p>
            <code class="code">describe</code> devuelve un array que contiene información sobre cada dirección IP
            elástica, incluyendo el publicIp y el instanceId si está asociado.
        </p>
<pre class="programlisting">
$ec2_eip = new Zend_Service_Amazon_Ec2_Elasticip('aws_key','aws_secret_key');
// describe all
$ips = $ec2_eip-&gt;describe();

// describe a subset
$ips = $ec2_eip-&gt;describe(array('ip1', 'ip2', 'ip3'));

// describe a single ip address
$ip = $ec2_eip-&gt;describe('ip1');
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.service.amazon.ec2.elasticip.release"></a><p class="title"><b>Ejemplo 64.48. Liberando una IP elástica</b></p>
<div class="example-contents">
<p>
            <code class="code">release</code> liberará una IP elástica a Amazon.
        </p>
<p>
            Devuelve un booleano <code class="constant">TRUE</code> o <code class="constant">FALSE</code>.
        </p>
<pre class="programlisting">
$ec2_eip = new Zend_Service_Amazon_Ec2_Elasticip('aws_key','aws_secret_key');
$ec2_eip-&gt;release('ipaddress');
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.service.amazon.ec2.elasticip.associate"></a><p class="title"><b>Ejemplo 64.49. Asocia una IP elástica a una instancia</b></p>
<div class="example-contents">
<p>
            <code class="code">associate</code> asignará una IP elástica a una
            instancia que ya esté en ejecución.
        </p>
<p>
            Devuelve un booleano <code class="constant">TRUE</code> o <code class="constant">FALSE</code>.
        </p>
<pre class="programlisting">
$ec2_eip = new Zend_Service_Amazon_Ec2_Elasticip('aws_key','aws_secret_key');
$ec2_eip-&gt;associate('instance_id', 'ipaddress');
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.service.amazon.ec2.elasticip.disassociate"></a><p class="title"><b>Ejemplo 64.50. Desasociar una IP elástica de una instancia</b></p>
<div class="example-contents">
<p>
            <code class="code">disassociate</code> desasociará una IP elástica de una instancia.
            Si termina una instancia, se desasociará automáticamente la dirección IP
            elástica por usted.
        </p>
<p>
            Devuelve un booleano <code class="constant">TRUE</code> o <code class="constant">FALSE</code>.
        </p>
<pre class="programlisting">
$ec2_eip = new Zend_Service_Amazon_Ec2_Elasticip('aws_key','aws_secret_key');
$ec2_eip-&gt;disassociate('ipaddress');
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.amazon.ec2.ebs.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.amazon.ec2.keypairs.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.10. Zend_Service_Amazon_Ec2: Elastic Block Storage (EBS) </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 64.12. Zend_Service_Amazon_Ec2: Keypairs</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
