<?php $title = '45.10. Juegos de caracteres'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">45.10. Juegos de caracteres</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.additional-headers.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 45. Zend_Mail</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.encoding.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.character-sets"></a>45.10. Juegos de caracteres</h2></div></div></div>
<p>
        <code class="classname">Zend_Mail</code> no comprueba que el juego de caracteres de las partes
        del correo sea correcto. Al instanciar <code class="classname">Zend_Mail</code>, se puede
        indicar un juego de caracteres para el propio e-mail. Por defecto es
        <span class="emphasis"><em>iso-8859-1</em></span>. La aplicación debe asegurarse de que todas las
        partes añadidas a ese objeto de correo tengan su contenido codificado en el juego de
        caracteres correcto. Al crear una nueva parte de correo, se puede indicar un juego de
        caracteres diferente para cada parte.
    </p>
<div class="note"><table border="0" summary="Note: Only in text format">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Solo en formato de texto</th>
</tr>
<tr><td align="left" valign="top"><p>
            Los juegos de caracteres solo son aplicables a las partes del mensaje en formato de
            texto.
        </p></td></tr>
</table></div>
<div class="example">
<a name="zend.mail.character-sets.cjk"></a><p class="title"><b>Ejemplo 45.11. Uso en idiomas CJK</b></p>
<div class="example-contents">
<p>
            El siguiente ejemplo muestra cómo utilizar <code class="classname">Zend_Mail</code> en
            japonés. Este es uno de los idiomas <acronym class="acronym">CJK</acronym> (también
            conocidos como <acronym class="acronym">CJKV</acronym>). Si utiliza chino, puede usar
            <acronym class="acronym">HZ-GB-2312</acronym> en lugar de
            <acronym class="acronym">ISO-2022-JP</acronym>.
        </p>
<pre class="programlisting">
//We suppose that character encoding of strings is UTF-8 on PHP script.
function myConvert($string) {
    return mb_convert_encoding($string, 'ISO-2022-JP', 'UTF-8');
}

$mail = new Zend_Mail('ISO-2022-JP');
// In this case, you can use ENCODING_7BIT
// because the ISO-2022-JP does not use MSB.
$mail-&gt;setBodyText(
    myConvert('This is the text of the mail.'),
    null,
    Zend_Mime::ENCODING_7BIT
);
$mail-&gt;setHeaderEncoding(Zend_Mime::ENCODING_BASE64);
$mail-&gt;setFrom('somebody@example.com', myConvert('Some Sender'));
$mail-&gt;addTo('somebody_else@example.com', myConvert('Some Recipient'));
$mail-&gt;setSubject(myConvert('TestSubject'));
$mail-&gt;send();
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.additional-headers.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mail.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.encoding.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">45.9. Cabeceras adicionales </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 45.11. Codificación</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
