<?php $title = '55.4. Trabajando con Páginas'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">55.4. Trabajando con Páginas</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.pdf.save.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 55. Zend_Pdf</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.pdf.drawing.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.pdf.pages"></a>55.4. Trabajando con Páginas</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.pdf.pages.creation"></a>55.4.1. Creación de Páginas</h3></div></div></div>
<p>
            Las páginas de un documento <acronym class="acronym">PDF</acronym> se representan como
            instancias de <code class="classname">Zend_Pdf_Page</code> en <code class="classname">Zend_Pdf</code>.
        </p>
<p>
            Las páginas <acronym class="acronym">PDF</acronym> se cargan a partir de un <acronym class="acronym">PDF</acronym>
            existente o se crean usando la <acronym class="acronym">API</acronym> de <code class="classname">Zend_Pdf</code>.
        </p>
<p>
            Se pueden crear nuevas páginas instanciando directamente nuevos objetos <code class="classname">Zend_Pdf_Page</code>
            o llamando al método <code class="methodname">Zend_Pdf::newPage()</code>,
            que devuelve un objeto <code class="classname">Zend_Pdf_Page</code>.
            <code class="methodname">Zend_Pdf::newPage()</code> crea una página que ya está adjunta a
            un documento. Las páginas adjuntas no pueden usarse con otros documentos <acronym class="acronym">PDF</acronym>
            hasta que no se clonen. Vea la sección <a class="link" href="zend.pdf.pages.phtml#zend.pdf.pages.cloning" title="55.4.2. Page cloning">Clonación
            de páginas</a> para más detalles.
        </p>
<p>
            El método <code class="methodname">Zend_Pdf::newPage()</code> y el constructor de
            <code class="classname">Zend_Pdf_Page</code> reciben los mismos parámetros para especificar
            el tamaño de página. Pueden recibir tanto el tamaño de la página ($x, $y) en puntos (1/72 de pulgada) o una
            constante predefinida que representa un tipo de página:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Zend_Pdf_Page::SIZE_A4</p></li>
<li class="listitem"><p>Zend_Pdf_Page::SIZE_A4_LANDSCAPE</p></li>
<li class="listitem"><p>Zend_Pdf_Page::SIZE_LETTER</p></li>
<li class="listitem"><p>Zend_Pdf_Page::SIZE_LETTER_LANDSCAPE</p></li>
</ul></div>
<p>
        </p>
<p>
            Las páginas del documento se almacenan en el atributo público <code class="varname">$pages</code> de la
            clase <code class="classname">Zend_Pdf</code>. El atributo contiene un arreglo de
            objetos <code class="classname">Zend_Pdf_Page</code> y define completamente las instancias y el
            orden de las páginas. Este arreglo puede manipularse como cualquier otro arreglo
            <acronym class="acronym">PHP</acronym>:
        </p>
<div class="example">
<a name="zend.pdf.pages.example-1"></a><p class="title"><b>Ejemplo 55.4. Gestión de páginas de un documento PDF</b></p>
<div class="example-contents"><pre class="programlisting">
...
// Reverse page order
$pdf-&gt;pages = array_reverse($pdf-&gt;pages);
...
// Add new page
$pdf-&gt;pages[] = new Zend_Pdf_Page(Zend_Pdf_Page::SIZE_A4);
// Add new page
$pdf-&gt;pages[] = $pdf-&gt;newPage(Zend_Pdf_Page::SIZE_A4);

// Remove specified page.
unset($pdf-&gt;pages[$id]);

...
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.pdf.pages.cloning"></a>55.4.2. Clonación de páginas</h3></div></div></div>
<p>
            Una página <acronym class="acronym">PDF</acronym> existente puede duplicarse creando un nuevo
            objeto <code class="classname">Zend_Pdf_Page</code> con la página existente como parámetro:
        </p>
<div class="example">
<a name="zend.pdf.pages.example-2"></a><p class="title"><b>Ejemplo 55.5. Duplicación de una página existente</b></p>
<div class="example-contents"><pre class="programlisting">
...
// Store template page in a separate variable
$template = $pdf-&gt;pages[$templatePageIndex];
...
// Add new page
$page1 = new Zend_Pdf_Page($template);
$page1-&gt;drawText('Some text...', $x, $y);
$pdf-&gt;pages[] = $page1;
...

// Add another page
$page2 = new Zend_Pdf_Page($template);
$page2-&gt;drawText('Another text...', $x, $y);
$pdf-&gt;pages[] = $page2;
...

// Remove source template page from the documents.
unset($pdf-&gt;pages[$templatePageIndex]);

...
</pre></div>
</div>
<br class="example-break"><p>
            Esto es útil si necesita crear varias páginas usando una plantilla.
        </p>
<div class="caution"><table border="0" summary="Caution">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Caution]" src="images/caution.png"></td>
<th align="left">Precaución</th>
</tr>
<tr><td align="left" valign="top"><p>
                ¡Importante! La página duplicada comparte algunos recursos <acronym class="acronym">PDF</acronym> con
                una página de plantilla, por lo que solo puede usarse dentro del mismo documento que la página de plantilla.
                El documento modificado puede guardarse como uno nuevo.
            </p></td></tr>
</table></div>
<p>
            El operador <code class="code">clone</code> puede usarse para crear una página que no esté adjunta a ningún documento.
            Toma más tiempo que duplicar una página ya que necesita copiar todos los objetos dependientes
            (fuentes, imágenes y otros recursos utilizados), pero permite usar páginas de distintos documentos
            de origen para crear uno nuevo:
        </p>
<div class="example">
<a name="zend.pdf.pages.example-3"></a><p class="title"><b>Ejemplo 55.6. Clonación de una página existente</b></p>
<div class="example-contents"><pre class="programlisting">
$page1 = clone $pdf1-&gt;pages[$templatePageIndex1];
$page2 = clone $pdf2-&gt;pages[$templatePageIndex2];
$page1-&gt;drawText('Some text...', $x, $y);
$page2-&gt;drawText('Another text...', $x, $y);
...
$pdf = new Zend_Pdf();
$pdf-&gt;pages[] = $page1;
$pdf-&gt;pages[] = $page2;
</pre></div>
</div>
<br class="example-break"><p>
            Si se planea usar varias páginas de plantilla como plantillas, puede resultar más eficiente
            utilizar la clase <code class="classname">Zend_Pdf_Resource_Extractor</code>, que ofrece la capacidad
            de compartir recursos entre páginas clonadas: fuentes, imágenes, etc. (de lo contrario se creará
            una nueva copia del recurso para cada página clonada):
        </p>
<div class="example">
<a name="zend.pdf.pages.example-4"></a><p class="title"><b>Ejemplo 55.7. Clonación de una página existente usando la clase Zend_Pdf_Resource_Extractor</b></p>
<div class="example-contents"><pre class="programlisting">
$extractor = new Zend_Pdf_Resource_Extractor();
....
$page1 = $extractor-&gt;clonePage($pdf-&gt;pages[$templatePageIndex1]);
$page2 = $extractor-&gt;clonePage($pdf-&gt;pages[$templatePageIndex2]);
$page1-&gt;drawText('Some text...', $x, $y);
$page2-&gt;drawText('Another text...', $x, $y);
...
$pdf = new Zend_Pdf();
$pdf-&gt;pages[] = $page1;
$pdf-&gt;pages[] = $page2;
</pre></div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.pdf.save.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.pdf.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.pdf.drawing.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">55.3. Guardar Cambios en Documentos PDF </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 55.5. Dibujo</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
