<?php $title = 'registerAutoloadMaps'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">registerAutoloadMaps</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.register-autoload-map.phtml">Anterior</a> </td>
<th width="60%" align="center">42.8.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.class-map-autoloader.methods.get-autoload-map.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.class-map-autoloader.methods.register-autoload-maps"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>registerAutoloadMaps — Registra varios mapas de clases a la vez</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">registerAutoloadMaps</span>(<span class="methodparam">$maps</span>);</code>
</div>
<div class="refsection">
<a name="id37254"></a><h2>registerAutoloadMaps()</h2>
<p>
                    Registra varios mapas de clases con el autoloader. Espera un array o un objeto
                    <code class="interfacename">Traversable</code>; a continuación itera sobre el
                    argumento y pasa cada valor a <a class="link" href="zend.loader.class-map-autoloader.methods.register-autoload-map.phtml" title="registerAutoloadMap">registerAutoloadMap()</a>.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.register-autoload-map.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.class-map-autoloader.phtml#zend.loader.class-map-autoloader.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.class-map-autoloader.methods.get-autoload-map.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">registerAutoloadMap </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> getAutoloadMap</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
