<?php $title = 'Capítulo 67. Zend_Tag'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 67. Zend_Tag</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.soap.autodiscovery.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.tag.cloud.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.tag"></a>Capítulo 67. Zend_Tag</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.tag.phtml#zend.tag.introduction">67.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.tag.cloud.phtml">67.2. Zend_Tag_Cloud</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tag.cloud.phtml#zend.tag.cloud.decorators">67.2.1. Decoradores</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tag.cloud.phtml#zend.tag.cloud.decorators.htmltag">67.2.1.1. Decorador HTML Tag</a></span></dt>
<dt><span class="sect3"><a href="zend.tag.cloud.phtml#zend.tag.cloud.decorators.htmlcloud">67.2.1.2. Decorador HTML Cloud</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.tag.introduction"></a>67.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Tag</code> es un conjunto de componentes que proporciona una
        facilidad para trabajar con elementos etiquetables. En su base, proporciona dos clases
        para trabajar con etiquetas, <code class="classname">Zend_Tag_Item</code> y
        <code class="classname">Zend_Tag_ItemList</code>. Además, incluye la
        interfaz <code class="classname">Zend_Tag_Taggable</code>, que le permite usar cualquiera de
        sus modelos como un elemento etiquetable en conjunto con
        <code class="classname">Zend_Tag</code>.
    </p>
<p>
        <code class="classname">Zend_Tag_Item</code> es una implementación básica de elemento etiquetable
        que incluye la funcionalidad esencial necesaria para trabajar con
        el conjunto <code class="classname">Zend_Tag</code>. Un elemento etiquetable siempre consiste en
        un título y un peso relativo (por ejemplo, el número de apariciones). También
        almacena parámetros que son utilizados por los diferentes subcomponentes de
        <code class="classname">Zend_Tag</code>.
    </p>
<p>
        Para agrupar varios elementos, existe <code class="classname">Zend_Tag_ItemList</code>
        como un iterador de array y proporciona funcionalidad adicional para calcular
        valores de peso absolutos basados en los pesos relativos dados de cada
        elemento que contiene.
    </p>
<div class="example">
<a name="zend.tag.example.using"></a><p class="title"><b>Ejemplo 67.1. Uso de Zend_Tag</b></p>
<div class="example-contents">
<p>
            Este ejemplo ilustra cómo crear una lista de etiquetas y distribuir
            valores de peso absolutos en ellas.
        </p>
<pre class="programlisting">
// Create the item list
$list = new Zend_Tag_ItemList();

// Assign tags to it
$list[] = new Zend_Tag_Item(array('title' =&gt; 'Code', 'weight' =&gt; 50));
$list[] = new Zend_Tag_Item(array('title' =&gt; 'Zend Framework', 'weight' =&gt; 1));
$list[] = new Zend_Tag_Item(array('title' =&gt; 'PHP', 'weight' =&gt; 5));

// Spread absolute values on the items
$list-&gt;spreadWeightValues(array(1, 2, 3, 4, 5, 6, 7, 8, 9, 10));

// Output the items with their absolute values
foreach ($list as $item) {
    printf("%s: %d\n", $item-&gt;getTitle(), $item-&gt;getParam('weightValue'));
}
</pre>
<p>
            Esto mostrará los tres elementos Code, Zend Framework y <acronym class="acronym">PHP</acronym> con
            los valores absolutos 10, 1 y 2.
        </p>
</div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.soap.autodiscovery.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.tag.cloud.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">66.4. AutoDiscovery </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 67.2. Zend_Tag_Cloud</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
