<?php $title = 'factory'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">factory</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.autoloader-factory.phtml">Anterior</a> </td>
<th width="60%" align="center">42.6.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.autoloader-factory.methods.get-registered-autoloaders.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.autoloader-factory.methods.factory"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>factory — Instancia y registra autoloaders</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">factory</span>(<span class="methodparam">$options</span>);</code>
</div>
<div class="refsection">
<a name="id36937"></a><h2>factory()</h2>
<p>
                    Este método es <span class="emphasis"><em>estático</em></span>, y se utiliza para instanciar
                    autoloaders y registrarlos con el autoloader de SPL. Espera un
                    array o un objeto <code class="interfacename">Traversable</code>, tal como se indica en la
                    <a class="link" href="zend.loader.autoloader-factory.phtml#zend.loader.autoloader-factory.options" title="42.6.3. Configuration Options">sección de opciones</a>.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.autoloader-factory.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.autoloader-factory.phtml#zend.loader.autoloader-factory.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.autoloader-factory.methods.get-registered-autoloaders.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">42.6. AutoloaderFactory </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> getRegisteredAutoloaders</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
