<?php $title = '21.5. Zend_Config_Xml'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">21.5. Zend_Config_Xml</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.config.adapters.json.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 21. Zend_Config</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.config.adapters.yaml.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.config.adapters.xml"></a>21.5. Zend_Config_Xml</h2></div></div></div>
<p>
        <code class="classname">Zend_Config_Xml</code> permite a los desarrolladores almacenar datos de configuración en un
        formato <acronym class="acronym">XML</acronym> simple y leerlos mediante sintaxis de propiedades de objetos anidados. El
        elemento raíz del archivo o cadena <acronym class="acronym">XML</acronym> es irrelevante y puede nombrarse
        de forma arbitraria. El primer nivel de elementos <acronym class="acronym">XML</acronym> corresponde a las
        secciones de datos de configuración. El formato <acronym class="acronym">XML</acronym> soporta organización
        jerárquica mediante el anidamiento de elementos <acronym class="acronym">XML</acronym> por debajo de los elementos
        de nivel de sección. El contenido de un elemento <acronym class="acronym">XML</acronym> de nivel hoja corresponde al
        valor de un dato de configuración. La herencia de secciones se soporta mediante un atributo
        <acronym class="acronym">XML</acronym> especial llamado <span class="emphasis"><em>extends</em></span>, y el valor de este
        atributo corresponde a la sección de la cual la sección que extiende heredará los datos.
    </p>
<div class="note"><table border="0" summary="Note: Return Type">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Tipo de retorno</th>
</tr>
<tr><td align="left" valign="top"><p>
            Los datos de configuración leídos en <code class="classname">Zend_Config_Xml</code> siempre se devuelven
            como cadenas. La conversión de datos de cadenas a otros tipos se deja a los desarrolladores para que se
            adapte a sus necesidades particulares.
        </p></td></tr>
</table></div>
<div class="example">
<a name="zend.config.adapters.xml.example.using"></a><p class="title"><b>Ejemplo 21.4. Uso de Zend_Config_Xml</b></p>
<div class="example-contents">
<p>
            Este ejemplo ilustra un uso básico de <code class="classname">Zend_Config_Xml</code> para
            cargar datos de configuración desde un archivo <acronym class="acronym">XML</acronym>. En este ejemplo hay
            datos de configuración tanto para un sistema de producción como para un sistema de staging. Debido a que
            los datos de configuración del sistema de staging son muy similares a los de producción, la
            sección de staging hereda de la sección de producción. En este caso, la decisión es
            arbitraria y podría haberse escrito al revés, con la sección de producción
            heredando de la sección de staging, aunque esto puede no ser así para situaciones más complejas.
            Suponga, entonces, que los siguientes datos de configuración están contenidos en
            <code class="filename">/path/to/config.xml</code>:
        </p>
<pre class="programlisting">
&lt;?xml version="1.0"?&gt;
&lt;configdata&gt;
    &lt;production&gt;
        &lt;webhost&gt;www.example.com&lt;/webhost&gt;
        &lt;database&gt;
            &lt;adapter&gt;pdo_mysql&lt;/adapter&gt;
            &lt;params&gt;
                &lt;host&gt;db.example.com&lt;/host&gt;
                &lt;username&gt;dbuser&lt;/username&gt;
                &lt;password&gt;secret&lt;/password&gt;
                &lt;dbname&gt;dbname&lt;/dbname&gt;
            &lt;/params&gt;
        &lt;/database&gt;
    &lt;/production&gt;
    &lt;staging extends="production"&gt;
        &lt;database&gt;
            &lt;params&gt;
                &lt;host&gt;dev.example.com&lt;/host&gt;
                &lt;username&gt;devuser&lt;/username&gt;
                &lt;password&gt;devsecret&lt;/password&gt;
            &lt;/params&gt;
        &lt;/database&gt;
    &lt;/staging&gt;
&lt;/configdata&gt;
</pre>
<p>
            A continuación, suponga que el desarrollador de la aplicación necesita los datos de configuración de staging
            del archivo <acronym class="acronym">XML</acronym>. Es sencillo cargar estos datos especificando
            el archivo <acronym class="acronym">XML</acronym> y la sección de staging:
        </p>
<pre class="programlisting">
$config = new Zend_Config_Xml('/path/to/config.xml', 'staging');

echo $config-&gt;database-&gt;params-&gt;host;   // prints "dev.example.com"
echo $config-&gt;database-&gt;params-&gt;dbname; // prints "dbname"
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.config.adapters.xml.example.attributes"></a><p class="title"><b>Ejemplo 21.5. Uso de atributos de etiqueta en Zend_Config_Xml</b></p>
<div class="example-contents">
<p>
            <code class="classname">Zend_Config_Xml</code> también soporta dos formas adicionales de definir
            nodos en la configuración. Ambas hacen uso de atributos. Dado que los atributos
            <span class="emphasis"><em>extends</em></span> y <span class="emphasis"><em>value</em></span> son palabras clave
            reservadas (la segunda por la segunda forma de usar atributos), no pueden
            usarse. La primera forma de hacer uso de atributos es agregar atributos en un nodo
            padre, que luego se traducirán en hijos de ese nodo:
        </p>
<pre class="programlisting">
&lt;?xml version="1.0"?&gt;
&lt;configdata&gt;
    &lt;production webhost="www.example.com"&gt;
        &lt;database adapter="pdo_mysql"&gt;
            &lt;params host="db.example.com" username="dbuser" password="secret"
                    dbname="dbname"/&gt;
        &lt;/database&gt;
    &lt;/production&gt;
    &lt;staging extends="production"&gt;
        &lt;database&gt;
            &lt;params host="dev.example.com" username="devuser"
                    password="devsecret"/&gt;
        &lt;/database&gt;
    &lt;/staging&gt;
&lt;/configdata&gt;
</pre>
<p>
            La otra forma no acorta realmente la configuración, pero es más fácil de mantener ya que
            no tiene que escribir el nombre de la etiqueta dos veces. Simplemente crea una etiqueta vacía con el
            valor en el atributo <span class="emphasis"><em>value</em></span>:
        </p>
<pre class="programlisting">
&lt;?xml version="1.0"?&gt;
&lt;configdata&gt;
    &lt;production&gt;
        &lt;webhost&gt;www.example.com&lt;/webhost&gt;
        &lt;database&gt;
            &lt;adapter value="pdo_mysql"/&gt;
            &lt;params&gt;
                &lt;host value="db.example.com"/&gt;
                &lt;username value="dbuser"/&gt;
                &lt;password value="secret"/&gt;
                &lt;dbname value="dbname"/&gt;
            &lt;/params&gt;
        &lt;/database&gt;
    &lt;/production&gt;
    &lt;staging extends="production"&gt;
        &lt;database&gt;
            &lt;params&gt;
                &lt;host value="dev.example.com"/&gt;
                &lt;username value="devuser"/&gt;
                &lt;password value="devsecret"/&gt;
            &lt;/params&gt;
        &lt;/database&gt;
    &lt;/staging&gt;
&lt;/configdata&gt;
</pre>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: XML strings">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Cadenas XML</th>
</tr>
<tr><td align="left" valign="top">
<p>
            <code class="classname">Zend_Config_Xml</code> es capaz de cargar directamente una cadena
            <acronym class="acronym">XML</acronym>, como la recuperada de una base de datos. La cadena se pasa
            como primer parámetro al constructor y debe comenzar con los
            caracteres <span class="emphasis"><em>'&lt;?xml'</em></span>:
        </p>
<pre class="programlisting">
$string = &lt;&lt;&lt;EOT
&lt;?xml version="1.0"?&gt;
&lt;config&gt;
    &lt;production&gt;
        &lt;db&gt;
            &lt;adapter value="pdo_mysql"/&gt;
            &lt;params&gt;
                &lt;host value="db.example.com"/&gt;
            &lt;/params&gt;
        &lt;/db&gt;
    &lt;/production&gt;
    &lt;staging extends="production"&gt;
        &lt;db&gt;
            &lt;params&gt;
                &lt;host value="dev.example.com"/&gt;
            &lt;/params&gt;
        &lt;/db&gt;
    &lt;/staging&gt;
&lt;/config&gt;
EOT;

$config = new Zend_Config_Xml($string, 'staging');
</pre>
</td></tr>
</table></div>
<div class="note"><table border="0" summary="Note: Zend_Config XML namespace">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Espacio de nombres XML de Zend_Config</th>
</tr>
<tr><td align="left" valign="top">
<p>
            <code class="classname">Zend_Config</code> viene con su propio espacio de nombres
            <acronym class="acronym">XML</acronym>, que agrega funcionalidad adicional al proceso de análisis. Para aprovecharlo,
            debe definir un espacio de nombres con el <acronym class="acronym">URI</acronym> de espacio de nombres
            <code class="filename">http://framework.zend.com/xml/zend-config-xml/1.0/</code> en
            el nodo raíz de su configuración.
        </p>
<p>
            Con el espacio de nombres habilitado, ahora puede usar constantes de <acronym class="acronym">PHP</acronym> dentro
            de sus archivos de configuración. Además, el atributo <span class="emphasis"><em>extends</em></span>
            se trasladó al nuevo espacio de nombres y está obsoleto en el
            espacio de nombres <code class="constant">NULL</code>. Se eliminará por completo allí en
            Zend Framework 2.0.
        </p>
<pre class="programlisting">
$string = &lt;&lt;&lt;EOT
&lt;?xml version="1.0"?&gt;
&lt;config xmlns:zf="http://framework.zend.com/xml/zend-config-xml/1.0/"&gt;
    &lt;production&gt;
        &lt;includePath&gt;
            &lt;zf:const zf:name="APPLICATION_PATH"/&gt;/library&lt;/includePath&gt;
        &lt;db&gt;
            &lt;adapter value="pdo_mysql"/&gt;
            &lt;params&gt;
                &lt;host value="db.example.com"/&gt;
            &lt;/params&gt;
        &lt;/db&gt;
    &lt;/production&gt;
    &lt;staging zf:extends="production"&gt;
        &lt;db&gt;
            &lt;params&gt;
                &lt;host value="dev.example.com"/&gt;
            &lt;/params&gt;
        &lt;/db&gt;
    &lt;/staging&gt;
&lt;/config&gt;
EOT;

define('APPLICATION_PATH', dirname(__FILE__));
$config = new Zend_Config_Xml($string, 'staging');

echo $config-&gt;includePath; // Prints "/var/www/something/library"
</pre>
</td></tr>
</table></div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.config.adapters.json.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.config.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.config.adapters.yaml.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">21.4. Zend_Config_Json </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 21.6. Zend_Config_Yaml</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
