<?php $title = 'getRegisteredAutoloaders'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">getRegisteredAutoloaders</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.autoloader-factory.methods.factory.phtml">Anterior</a> </td>
<th width="60%" align="center">42.6.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.autoloader-factory.methods.get-registered-autoloaders"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>getRegisteredAutoloaders — Recupera una lista de todos los autoloaders registrados mediante la factoría</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">getRegisteredAutoloaders</span>();</code>
</div>
<div class="refsection">
<a name="id36949"></a><h2>getRegisteredAutoloaders()</h2>
<p>
                    Este método es <span class="emphasis"><em>estático</em></span>, y puede usarse para recuperar una lista
                    de todos los autoloaders registrados mediante el método <code class="methodname">factory()</code>.
                    Simplemente devuelve un array de instancias de autoloader.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.autoloader-factory.methods.factory.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.autoloader-factory.phtml#zend.loader.autoloader-factory.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">factory </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 42.7. The StandardAutoloader</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
