<?php $title = '36.8. Internacionalización de Zend_Form'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">36.8. Internacionalización de Zend_Form</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.form.standardDecorators.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 36. Zend_Form</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.form.advanced.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.form.i18n"></a>36.8. Internacionalización de Zend_Form</h2></div></div></div>
<p>
        Cada vez más, los desarrolladores necesitan adaptar su contenido para múltiples
        idiomas y regiones. <code class="classname">Zend_Form</code> tiene como objetivo hacer que dicha tarea sea trivial,
        y aprovecha la funcionalidad tanto de <a class="link" href="zend.translate.phtml" title="Chapter 74. Zend_Translate">Zend_Translate</a> como de <a class="link" href="zend.validate.phtml" title="Chapter 76. Zend_Validate">Zend_Validate</a> para hacerlo.
    </p>
<p>
        Por defecto, no se realiza ninguna internacionalización (I18n). Para activar las
        funciones de I18n en <code class="classname">Zend_Form</code>, necesitará instanciar un objeto
        <code class="classname">Zend_Translate</code> con un adaptador apropiado, y
        adjuntarlo a <code class="classname">Zend_Form</code> y/o <code class="classname">Zend_Validate</code>.
        Consulte la <a class="link" href="zend.translate.phtml" title="Chapter 74. Zend_Translate">documentación de
            Zend_Translate</a> para más información sobre la creación del objeto de traducción
        y los archivos de traducción
    </p>
<div class="note"><table border="0" summary="Note: Translation Can Be Turned Off Per Item">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">La traducción se puede desactivar por elemento</th>
</tr>
<tr><td align="left" valign="top"><p>
            Puede deshabilitar la traducción para cualquier formulario, elemento, grupo de visualización o
            subformulario llamando a su método <code class="methodname">setDisableTranslator($flag)</code>
            o pasando una opción <span class="property">disableTranslator</span> al
            objeto. Esto puede ser útil cuando desea deshabilitar selectivamente la
            traducción para elementos individuales o conjuntos de elementos.
        </p></td></tr>
</table></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.i18n.initialization"></a>36.8.1. Inicializando I18n en formularios</h3></div></div></div>
<p>
            Para inicializar I18n en los formularios, necesitará ya sea un
            objeto <code class="classname">Zend_Translate</code> o un objeto
            <code class="classname">Zend_Translate_Adapter</code>, como se detalla en la
            documentación de <code class="classname">Zend_Translate</code>. Una vez que tenga un
            objeto de traducción, tiene varias opciones:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>
                    <span class="emphasis"><em>Más fácil:</em></span> agréguelo al registro. Todos los componentes
                    de Zend Framework compatibles con I18n descubrirán automáticamente un objeto de
                    traducción que esté en el registro bajo la clave 'Zend_Translate'
                    y lo usarán para realizar la traducción y/o localización:
                </p>
<pre class="programlisting">
// use the 'Zend_Translate' key; $translate is a Zend_Translate object:
Zend_Registry::set('Zend_Translate', $translate);
</pre>
<p>
                    Esto será detectado por <code class="classname">Zend_Form</code>,
                    <code class="classname">Zend_Validate</code>, y
                    <code class="classname">Zend_View_Helper_Translate</code>.
                </p>
</li>
<li class="listitem">
<p>
                    Si lo único que le preocupa es traducir los mensajes de error de
                    validación, puede registrar el objeto de traducción con
                    <code class="classname">Zend_Validate_Abstract</code>:
                </p>
<pre class="programlisting">
// Tell all validation classes to use a specific translate adapter:
Zend_Validate_Abstract::setDefaultTranslator($translate);
</pre>
</li>
<li class="listitem">
<p>
                    Alternativamente, puede adjuntarlo al objeto
                    <code class="classname">Zend_Form</code> como un traductor global. Esto tiene el efecto
                    secundario de traducir también los mensajes de error de validación:
                </p>
<pre class="programlisting">
// Tell all form classes to use a specific translate adapter, as well
// as use this adapter to translate validation error messages:
Zend_Form::setDefaultTranslator($translate);
</pre>
</li>
<li class="listitem">
<p>
                    Finalmente, puede adjuntar un traductor a una instancia de formulario específica
                    o a elementos específicos usando sus métodos <code class="methodname">setTranslator()</code>:
                </p>
<pre class="programlisting">
// Tell *this* form instance to use a specific translate adapter; it
// will also be used to translate validation error messages for all
// elements:
$form-&gt;setTranslator($translate);

// Tell *this* element to use a specific translate adapter; it will
// also be used to translate validation error messages for this
// particular element:
$element-&gt;setTranslator($translate);
</pre>
</li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.i18n.standard"></a>36.8.2. Objetivos estándar de I18n</h3></div></div></div>
<p>
            Ahora que ha adjuntado un objeto de traducción, ¿qué es exactamente lo que
            puede traducir por defecto?
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>
                    <span class="emphasis"><em>Mensajes de error de validación.</em></span> Los mensajes
                    de error de validación se pueden traducir. Para ello, use las diversas
                    constantes de código de error de las clases de validación de
                    <code class="classname">Zend_Validate</code> como los ID de mensaje. Para más información
                    sobre estos códigos, consulte la documentación de <a class="link" href="zend.validate.phtml" title="Chapter 76. Zend_Validate">Zend_Validate</a>.
                </p>
<p>
                    Alternativamente, a partir de la versión 1.6.0, puede proporcionar cadenas
                    de traducción usando los mensajes de error reales como identificadores
                    de mensaje. Este es el caso de uso preferido para la versión 1.6.0 y
                    posteriores, ya que se está deprecando la traducción de claves de mensaje en
                    futuras versiones.
                </p>
</li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Etiquetas.</em></span> Las etiquetas de los elementos serán
                    traducidas, si existe una traducción.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Leyendas de Fieldset.</em></span> Los grupos de visualización y
                    subformularios se renderizan en fieldsets por defecto. El decorador
                    Fieldset intenta traducir la leyenda antes de renderizar
                    el fieldset.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Descripciones de formularios y elementos.</em></span> Todos los tipos
                    de formulario (elemento, formulario, grupo de visualización, subformulario) permiten
                    especificar una descripción de elemento opcional. El decorador Description
                    puede usarse para renderizarla, y por defecto tomará
                    el valor e intentará traducirlo.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Valores de opciones múltiples.</em></span> para los diversos
                    elementos que heredan de <code class="classname">Zend_Form_Element_Multi</code>
                    (incluyendo los elementos MultiCheckbox, Multiselect y Radio),
                    los valores de las opciones (no las claves) se traducirán
                    si hay una traducción disponible; esto significa que las etiquetas de opción
                    presentadas al usuario serán traducidas.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Etiquetas de Submit y Button.</em></span> Los diversos
                    elementos Submit y Button (Button, Submit y Reset) traducirán
                    la etiqueta mostrada al usuario.
                </p></li>
</ul></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.form.standardDecorators.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.form.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.form.advanced.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">36.7. Decoradores de formulario estándar incluidos con Zend Framework </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 36.9. Uso avanzado de Zend_Form</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
