<?php $title = '64.20. Zend_Service_Ebay_Finding'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.20. Zend_Service_Ebay_Finding</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.ebay.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.flickr.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.ebay.finding"></a>64.20. Zend_Service_Ebay_Finding</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.ebay.finding.introduction"></a>64.20.1. Introducción</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Ebay_Finding</code> proporciona un cliente
            para el <a class="ulink" href="http://developer.ebay.com/DevZone/finding/CallRef/index.html" target="_top">eBay Finding</a>.
            Según el sitio web de eBay, "The Finding API provides programmatic access to
            the next generation search capabilities on the eBay platform. It
            lets you search and browse for items listed on eBay, and provides
            useful metadata to refine searches and enhance the search experience."
        </p>
<p>
            Para poder usar <code class="classname">Zend_Service_Ebay_Finding</code>,
            ya debería tener un eBay Application ID. Para obtener una clave y para
            más información, visite el sitio web del
            <a class="ulink" href="https://developer.ebay.com/Join/default.aspx" target="_top">eBay Developers Program</a>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.ebay.finding.factoring"></a>64.20.2. Crear un objeto cliente</h3></div></div></div>
<p>
            Instancie un objeto <code class="classname">Zend_Service_Ebay_Finding</code>,
            pasándole sus claves privadas:
        </p>
<div class="example">
<a name="zend.service.ebay.finding.factoring.sample-1"></a><p class="title"><b>Ejemplo 64.93. Creando una instancia del servicio eBay Finding</b></p>
<div class="example-contents"><pre class="programlisting">
$finding = new Zend_Service_Ebay_Finding('my-app-id');
</pre></div>
</div>
<br class="example-break"><p>
            Instancie un objeto <code class="classname">Zend_Service_Ebay_Finding</code>,
            pasándole sus claves privadas y configurando opciones:
        </p>
<div class="example">
<a name="zend.service.ebay.finding.factoring.sample-2"></a><p class="title"><b>Ejemplo 64.94. Creando una instancia del servicio eBay Finding</b></p>
<div class="example-contents"><pre class="programlisting">
$options = array(Zend_Service_Ebay_Abstract::OPTION_APP_ID    =&gt; 'my-app-id',
                 Zend_Service_Ebay_Abstract::OPTION_GLOBAL_ID =&gt; 'EBAY-GB');
$finding = new Zend_Service_Ebay_Finding($options);
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.ebay.finding.items"></a>64.20.3. Búsqueda de elementos</h3></div></div></div>
<p>
            Hay cinco métodos disponibles para buscar elementos:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>findItemsByKeywords($keywords)</p></li>
<li class="listitem"><p>findItemsByProduct($productId)</p></li>
<li class="listitem"><p>findItemsByCategory($categoryId)</p></li>
<li class="listitem"><p>findItemsAdvanced($keywords)</p></li>
<li class="listitem"><p>findItemsInEbayStores($storeName)</p></li>
</ul></div>
<p>
        </p>
<div class="example">
<a name="zend.service.ebay.finding.items.sample"></a><p class="title"><b>Ejemplo 64.95. Muchas formas de buscar elementos</b></p>
<div class="example-contents"><pre class="programlisting">
$finding  = new Zend_Service_Ebay_Finding('my-app-id');
$response = $finding-&gt;findItemsByKeywords('zend framework book');
foreach ($response-&gt;searchResult-&gt;item as $item) {
    $item-&gt;title;
    $item-&gt;listingInfo-&gt;buyItNowPrice;
    $item-&gt;listingInfo-&gt;viewItemURL;

    // inner call, find for items of same current product
    // like $finding-&gt;findItemsByProduct($item-&gt;productId, $item-&gt;attributes('productId', 'type'))
    $response2 = $item-&gt;findItemsByProduct($finding);

    // inner call, find for items of same store
    // like $finding-&gt;findItemsInEbayStores($item-&gt;storeInfo-&gt;storeName)
    $response3 = $item-&gt;storeInfo-&gt;findItems($finding);
}
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.ebay.finding.keywords-recomendation"></a>64.20.4. Recomendación de palabras clave</h3></div></div></div>
<p>
            Esta operación comprueba las palabras clave especificadas y devuelve
            palabras clave correctamente escritas para obtener los mejores resultados de búsqueda.
        </p>
<div class="example">
<a name="zend.service.ebay.finding.keywords.sample"></a><p class="title"><b>Ejemplo 64.96. Buscando recomendación de palabras clave</b></p>
<div class="example-contents"><pre class="programlisting">
// searching keywords
$finding = new Zend_Service_Ebay_Finding('my-app-id');
$result  = $finding-&gt;getSearchKeywordsRecommendation('zend');
echo 'Did you mean ' . $result-&gt;keyword . '?';

// inner call
// like $finding-&gt;findItemsByKeywords($result-&gt;keyword)
$result2 = $result-&gt;findItems($finding);
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.ebay.finding.histogram"></a>64.20.5. Histogramas</h3></div></div></div>
<p>
            Según el sitio web de eBay, esta operación "category and/or aspect histogram
            information for the eBay category ID you specify. Histograms are
            item counts for the associated category or aspect value. Input
            category ID numbers in the request using the categoryId field".
        </p>
<div class="example">
<a name="zend.service.ebay.finding.histogram.sample"></a><p class="title"><b>Ejemplo 64.97. Obteniendo un histograma</b></p>
<div class="example-contents"><pre class="programlisting">
$finding = new Zend_Service_Ebay_Finding('my-app-id');
$result  = $finding-&gt;getHistograms($categoryId);

foreach ($result-&gt;categoryHistogramContainer-&gt;categoryHistogram as $category) {
    $category-&gt;categoryId;
    $category-&gt;categoryName;

    // inner call
    // like $finding-&gt;findItemsByCategory($category-&gt;categoryId);
    $result2 = $category-&gt;findItems($finding);
}
</pre></div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.ebay.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.flickr.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.19. Zend_Service_Ebay </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 64.21. Zend_Service_Flickr</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
