<?php $title = 'Capítulo 32. Zend_Exception'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 32. Zend_Exception</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.event-manager.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.exception.basic.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.exception"></a>Capítulo 32. Zend_Exception</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.exception.phtml#zend.exception.using">32.1. Uso de excepciones</a></span></dt>
<dt><span class="sect1"><a href="zend.exception.basic.phtml">32.2. Uso básico</a></span></dt>
<dt><span class="sect1"><a href="zend.exception.previous.phtml">32.3. Excepciones previas</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.exception.using"></a>32.1. Uso de excepciones</h2></div></div></div>
<p>
        <code class="classname">Zend_Exception</code> es simplemente la clase base para todas las excepciones lanzadas
        dentro de Zend Framework.
    </p>
<div class="example">
<a name="zend.exception.using.example"></a><p class="title"><b>Ejemplo 32.1. Capturando una excepción</b></p>
<div class="example-contents">
<p>
            El siguiente listado de código muestra cómo capturar una excepción lanzada en una clase de Zend
            Framework:
        </p>
<pre class="programlisting">
try {
    // Calling Zend_Loader::loadClass() with a non-existant class will cause
    // an exception to be thrown in Zend_Loader:
    Zend_Loader::loadClass('nonexistantclass');
} catch (Zend_Exception $e) {
    echo "Caught exception: " . get_class($e) . "\n";
    echo "Message: " . $e-&gt;getMessage() . "\n";
    // Other code to recover from the error
}
</pre>
</div>
</div>
<br class="example-break"><p>
        <code class="classname">Zend_Exception</code> puede usarse como una clase de excepción "atrápalo todo" en un
        bloque catch para capturar todas las excepciones lanzadas por las clases de Zend Framework. Esto puede
        ser útil cuando el programa no puede recuperarse capturando un tipo de excepción específico.
    </p>
<p>
        La documentación de cada componente y clase
        de Zend Framework contendrá información específica sobre qué métodos
        lanzan excepciones, las circunstancias que hacen que se lance una excepción,
        y los distintos tipos de excepción que pueden lanzarse.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.event-manager.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.exception.basic.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 31. Zend_EventManager </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 32.2. Uso básico</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
