<?php $title = 'Capítulo 45. Zend_Mail'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 45. Zend_Mail</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.log.factory.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.sending.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.mail"></a>Capítulo 45. Zend_Mail</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.mail.phtml#zend.mail.introduction">45.1. Introducción</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.mail.phtml#zend.mail.introduction.getting-started">45.1.1. Primeros pasos</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.phtml#zend.mail.introduction.sendmail">45.1.2. Configuración del transporte sendmail por defecto</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.mail.sending.phtml">45.2. Envío vía SMTP</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.multiple-emails.phtml">45.3. Envío de múltiples correos por conexión SMTP</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.different-transports.phtml">45.4. Uso de diferentes transportes</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="zend.mail.different-transports.phtml#zend.mail.file-transport">45.4.1. Uso del transporte de archivo</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="zend.mail.html-mails.phtml">45.5. Correo electrónico en HTML</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.attachments.phtml">45.6. Adjuntos</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.adding-recipients.phtml">45.7. Añadir destinatarios</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.boundary.phtml">45.8. Control del límite MIME</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.additional-headers.phtml">45.9. Cabeceras adicionales</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.character-sets.phtml">45.10. Juegos de caracteres</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.encoding.phtml">45.11. Codificación</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.smtp-authentication.phtml">45.12. Autenticación SMTP</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.smtp-secure.phtml">45.13. Aseguramiento del transporte SMTP</a></span></dt>
<dt><span class="sect1"><a href="zend.mail.read.phtml">45.14. Lectura de mensajes de correo</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-example">45.14.1. Ejemplo simple usando Pop3</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-open-local">45.14.2. Apertura de un almacenamiento local</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-open-remote">45.14.3. Apertura de un almacenamiento remoto</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-fetching">45.14.4. Obtención de mensajes y métodos simples</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-message">45.14.5. Trabajar con mensajes</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-flags">45.14.6. Comprobación de indicadores (flags)</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-folders">45.14.7. Uso de carpetas</a></span></dt>
<dt><span class="sect2"><a href="zend.mail.read.phtml#zend.mail.read-advanced">45.14.8. Uso avanzado</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.mail.read.phtml#zend.mail.read-advanced.noop">45.14.8.1. Uso de NOOP</a></span></dt>
<dt><span class="sect3"><a href="zend.mail.read.phtml#zend.mail.read-advanced.caching">45.14.8.2. Almacenamiento en caché de instancias</a></span></dt>
<dt><span class="sect3"><a href="zend.mail.read.phtml#zend.mail.read-advanced.extending">45.14.8.3. Extensión de las clases de protocolo</a></span></dt>
<dt><span class="sect3"><a href="zend.mail.read.phtml#zend.mail.read-advanced.quota">45.14.8.4. Uso de la cuota (desde 1.5)</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.introduction"></a>45.1. Introducción</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mail.introduction.getting-started"></a>45.1.1. Primeros pasos</h3></div></div></div>
<p>
            <code class="classname">Zend_Mail</code> proporciona funcionalidad generalizada para componer y enviar
            mensajes de correo electrónico tanto de texto como multiparte compatibles con <acronym class="acronym">MIME</acronym>. El correo se puede
            enviar con <code class="classname">Zend_Mail</code> mediante el transporte por defecto
            <code class="classname">Zend_Mail_Transport_Sendmail</code> o mediante
            <code class="classname">Zend_Mail_Transport_Smtp</code>.
        </p>
<div class="example">
<a name="zend.mail.introduction.example-1"></a><p class="title"><b>Ejemplo 45.1. Correo electrónico simple con Zend_Mail</b></p>
<div class="example-contents">
<p>
                Un correo electrónico simple consiste en algunos destinatarios, un asunto, un cuerpo y un remitente. Para enviar
                dicho correo usando <code class="classname">Zend_Mail_Transport_Sendmail</code>, haga
                lo siguiente:
            </p>
<pre class="programlisting">
$mail = new Zend_Mail();
$mail-&gt;setBodyText('This is the text of the mail.');
$mail-&gt;setFrom('somebody@example.com', 'Some Sender');
$mail-&gt;addTo('somebody_else@example.com', 'Some Recipient');
$mail-&gt;setSubject('TestSubject');
$mail-&gt;send();
</pre>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: Minimum definitions">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Definiciones mínimas</th>
</tr>
<tr><td align="left" valign="top"><p>
                Para enviar un correo electrónico con <code class="classname">Zend_Mail</code> debe especificar
                al menos un destinatario, un remitente (por ejemplo, con <code class="methodname">setFrom()</code>),
                y un cuerpo de mensaje (texto y/o <acronym class="acronym">HTML</acronym>).
            </p></td></tr>
</table></div>
<p>
            Para la mayoría de los atributos de correo existen métodos "get" para leer la información almacenada en el
            objeto mail. Para más detalles, consulte la documentación de la <acronym class="acronym">API</acronym>.
            Uno especial es <code class="methodname">getRecipients()</code>. Devuelve un
            array con todas las direcciones de correo electrónico de los destinatarios que se añadieron antes de la llamada al método.
        </p>
<p>
            Por motivos de seguridad, <code class="classname">Zend_Mail</code> filtra todos los campos de cabecera para
            evitar la inyección de cabeceras con caracteres de nueva línea (<span class="emphasis"><em>\n</em></span>).
            Las comillas dobles se cambian a comillas simples y los corchetes angulares a corchetes cuadrados en
            el nombre del remitente y los destinatarios. Si las marcas están en la dirección de correo electrónico, las marcas se
            eliminarán.
        </p>
<p>
            También puede usar la mayoría de los métodos del objeto <code class="classname">Zend_Mail</code> con una
            cómoda interfaz fluida.
        </p>
<pre class="programlisting">
$mail = new Zend_Mail();
$mail-&gt;setBodyText('This is the text of the mail.')
    -&gt;setFrom('somebody@example.com', 'Some Sender')
    -&gt;addTo('somebody_else@example.com', 'Some Recipient')
    -&gt;setSubject('TestSubject')
    -&gt;send();
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mail.introduction.sendmail"></a>45.1.2. Configuración del transporte sendmail por defecto</h3></div></div></div>
<p>
            El transporte por defecto para una instancia de <code class="classname">Zend_Mail</code> es
            <code class="classname">Zend_Mail_Transport_Sendmail</code>. Es esencialmente un envoltorio de la
            función <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a> de <acronym class="acronym">PHP</acronym>. Si
            desea pasar parámetros adicionales a la función <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a>, simplemente
            cree una nueva instancia de transporte y pase sus parámetros al constructor. La nueva
            instancia de transporte puede entonces actuar como el transporte por defecto de
            <code class="classname">Zend_Mail</code>, o se puede pasar al método <code class="methodname">send()</code> de
            <code class="classname">Zend_Mail</code>.
        </p>
<div class="example">
<a name="zend.mail.introduction.sendmail.example-1"></a><p class="title"><b>Ejemplo 45.2.
                Paso de parámetros adicionales al transporte Zend_Mail_Transport_Sendmail
            </b></p>
<div class="example-contents">
<p>
                Este ejemplo muestra cómo cambiar el Return-Path de la función <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a>.
            </p>
<pre class="programlisting">
$tr = new Zend_Mail_Transport_Sendmail('-freturn_to_me@example.com');
Zend_Mail::setDefaultTransport($tr);

$mail = new Zend_Mail();
$mail-&gt;setBodyText('This is the text of the mail.');
$mail-&gt;setFrom('somebody@example.com', 'Some Sender');
$mail-&gt;addTo('somebody_else@example.com', 'Some Recipient');
$mail-&gt;setSubject('TestSubject');
$mail-&gt;send();
</pre>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: Safe mode restrictions">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Restricciones del modo seguro</th>
</tr>
<tr><td align="left" valign="top"><p>
                Los parámetros adicionales opcionales harán que la función <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a>
                falle si <acronym class="acronym">PHP</acronym> se está ejecutando en modo seguro.
            </p></td></tr>
</table></div>
<div class="warning"><table border="0" summary="Warning: Sendmail Transport and Windows">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Warning]" src="images/warning.png"></td>
<th align="left">Transporte Sendmail y Windows</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Como indica el manual de <acronym class="acronym">PHP</acronym>, la función <code class="methodname">mail()</code>
                tiene un comportamiento diferente en Windows y en sistemas basados en *nix. Usar el
                Transporte Sendmail en Windows no funcionará en combinación con
                <code class="methodname">addBcc()</code>. La función <code class="methodname">mail()</code>
                enviará al destinatario en BCC de tal forma que todos los demás destinatarios podrán verlo como
                destinatario.
            </p>
<p>
                Por lo tanto, si desea usar BCC en un servidor Windows, ¡use el transporte
                SMTP para el envío!
            </p>
</td></tr>
</table></div>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.log.factory.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.sending.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">44.5. Uso de la fábrica para crear un log </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 45.2. Envío vía SMTP</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
