<?php $title = '33.4. Consumir un feed RSS'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">33.4. Consumir un feed RSS</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.feed.findFeeds.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 33. Zend_Feed</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.feed.consuming-atom.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.feed.consuming-rss"></a>33.4. Consumir un feed RSS</h2></div></div></div>
<p>
        Leer un feed <acronym class="acronym">RSS</acronym> es tan sencillo como instanciar un
        objeto <code class="classname">Zend_Feed_Rss</code> con la <acronym class="acronym">URL</acronym> del feed:
    </p>
<pre class="programlisting">
$channel = new Zend_Feed_Rss('http://rss.example.com/channelName');
</pre>
<p>
        Si ocurre algún error al obtener el feed, se lanzará una <code class="classname">Zend_Feed_Exception</code>.
    </p>
<p>
        Una vez que tiene un objeto feed, puede acceder a cualquiera de las propiedades
        estándar del "channel" (canal) <acronym class="acronym">RSS</acronym> directamente en el objeto:
    </p>
<pre class="programlisting">
echo $channel-&gt;title();
</pre>
<p>
        Observe la sintaxis de función. <code class="classname">Zend_Feed</code> usa una convención
        de tratar las propiedades como objeto <acronym class="acronym">XML</acronym> si se solicitan con
        sintaxis "getter" de variable (<span class="command"><strong>$obj-&gt;property</strong></span>) y como cadenas
        si se accede a ellas con sintaxis de método (<span class="command"><strong>$obj-&gt;property()</strong></span>).
        Esto permite el acceso al texto completo de cualquier nodo individual, a la vez
        que sigue permitiendo el acceso completo a todos los hijos.
    </p>
<p>
        Si las propiedades del canal tienen atributos, son accesibles usando la
        sintaxis de array de <acronym class="acronym">PHP</acronym>:
    </p>
<pre class="programlisting">
echo $channel-&gt;category['domain'];
</pre>
<p>
        Dado que los atributos <acronym class="acronym">XML</acronym> no pueden tener hijos, no es necesaria
        la sintaxis de método para acceder a los valores de los atributos.
    </p>
<p>
        Lo más habitual será que quiera recorrer el feed y hacer algo con sus entradas.
        <code class="classname">Zend_Feed_Abstract</code> implementa la interfaz
        <code class="classname">Iterator</code> de <acronym class="acronym">PHP</acronym>, por lo que imprimir
        todos los títulos de los artículos en un canal es simplemente cuestión de:
    </p>
<pre class="programlisting">
foreach ($channel as $item) {
    echo $item-&gt;title() . "\n";
}
</pre>
<p>
        Si no está familiarizado con <acronym class="acronym">RSS</acronym>, estos son los elementos
        estándar que puede esperar encontrar disponibles en un canal <acronym class="acronym">RSS</acronym>
        y en elementos <acronym class="acronym">RSS</acronym> individuales (entradas).
    </p>
<p>
        Elementos de canal obligatorios:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p><span class="property">title</span> - El nombre del canal</p></li>
<li class="listitem"><p>
                <span class="property">link</span> - La <acronym class="acronym">URL</acronym> del sitio web
                correspondiente al canal
            </p></li>
<li class="listitem"><p>
                <span class="property">description</span> - Una o varias frases describiendo el canal
            </p></li>
</ul></div>
<p>
        Elementos de canal opcionales comunes:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <span class="property">pubDate</span> - La fecha de publicación de este conjunto de
                contenido, en formato de fecha <acronym class="acronym">RFC</acronym> 822
            </p></li>
<li class="listitem"><p><span class="property">language</span> - El idioma en que está escrito el canal</p></li>
<li class="listitem"><p>
                <span class="property">category</span> - Una o más (especificadas mediante múltiples
                etiquetas) categorías a las que pertenece el canal
            </p></li>
</ul></div>
<p>
        Los elementos <span class="emphasis"><em>&lt;item&gt;</em></span> de <acronym class="acronym">RSS</acronym> no tienen
        ningún elemento estrictamente obligatorio. Sin embargo, debe estar presente
        <span class="property">title</span> o <span class="property">description</span>.
    </p>
<p>
        Elementos de item comunes:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p><span class="property">title</span> - El título del item</p></li>
<li class="listitem"><p><span class="property">link</span> - La <acronym class="acronym">URL</acronym> del item</p></li>
<li class="listitem"><p><span class="property">description</span> - Una sinopsis del item</p></li>
<li class="listitem"><p><span class="property">author</span> - La dirección de correo electrónico del autor</p></li>
<li class="listitem"><p>
                <span class="property">category</span> - Una o más categorías a las que pertenece el item
            </p></li>
<li class="listitem"><p>
                <span class="property">comments</span> - <acronym class="acronym">URL</acronym> de los comentarios
                relacionados con este item
            </p></li>
<li class="listitem"><p>
                <span class="property">pubDate</span> - La fecha en que se publicó el item, en
                formato de fecha <acronym class="acronym">RFC</acronym> 822
            </p></li>
</ul></div>
<p>
        En su código siempre puede comprobar si un elemento no está vacío con:
    </p>
<pre class="programlisting">
if ($item-&gt;propname()) {
    // ... proceed.
}
</pre>
<p>
        Si usa <span class="command"><strong>$item-&gt;propname</strong></span> en su lugar, siempre obtendrá un
        objeto vacío que se evaluará como <code class="constant">TRUE</code>, por lo que su
        comprobación fallará.
    </p>
<p>
        Para más información, la especificación oficial de <acronym class="acronym">RSS</acronym> 2.0
        está disponible en:
        <a class="ulink" href="http://blogs.law.harvard.edu/tech/rss" target="_top">http://blogs.law.harvard.edu/tech/rss</a>
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.feed.findFeeds.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.feed.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.feed.consuming-atom.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">33.3. Obtención de feeds desde páginas web </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 33.5. Consumir un feed Atom</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
