<?php $title = '64.23. Zend_Service_Rackspace'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.23. Zend_Service_Rackspace</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.livedocx.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.rackspace.files.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.rackspace"></a>64.23. Zend_Service_Rackspace</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.rackspace.introduction"></a>64.23.1. Introducción</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Rackspace</code> es una clase que
            proporciona una <acronym class="acronym">API</acronym> sencilla para gestionar los servicios de Rackspace
            Cloud Files y Cloud Servers.
        </p>
<div class="note"><table border="0" summary="Note: Load balancers service">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Servicio de balanceadores de carga</th>
</tr>
<tr><td align="left" valign="top"><p>
                El servicio de balanceadores de carga de Rackspace todavía no está implementado.
                Estamos planeando publicarlo en un futuro próximo.
            </p></td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.rackspace.registering"></a>64.23.2. Registro en Rackspace</h3></div></div></div>
<p>
            Antes de poder comenzar a usar <code class="classname">Zend_Service_Rackspace</code>, primero debe
            registrarse para obtener una cuenta. Consulte la página de
            <a class="ulink" href="http://www.rackspace.com/cloud/" target="_top">Cloud services</a>
            en el sitio web de Rackspace para más información.
        </p>
<p>
            Después de registrarse, puede obtener el nombre de usuario y la clave de la API desde la consola
            de administración de Rackspace en el menú "Your Account" &gt; "API Access".
            Esta información es necesaria para usar las clases de
            <code class="classname">Zend_Service_Rackspace</code>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.rackspace.feature.files"></a>64.23.3. Cloud Files</h3></div></div></div>
<p>
            Cloud Files es un servicio para almacenar cualquier tipo de archivo en un entorno en la nube.
            Un usuario puede almacenar una cantidad ilimitada de archivos y cada archivo puede tener
            hasta 5 gigabytes de tamaño. Los archivos pueden ser privados o públicos. Los archivos
            privados pueden ser accedidos usando la API de Rackspace. Los archivos públicos se acceden
            usando una <acronym class="acronym">CDN</acronym> (Content Delivery Network).
            Rackspace expone una API <acronym class="acronym">REST</acronym> para gestionar Cloud Files.
        </p>
<p>
            <code class="classname">Zend_Service_Rackspace_Files</code> proporciona la siguiente funcionalidad:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        Subir archivos de forma programática para una integración estrecha con su aplicación
                    </p></li>
<li class="listitem"><p>
                        Habilitar la integración de Cloud Files CDN en cualquier contenedor para distribución pública
                    </p></li>
<li class="listitem"><p>
                        Crear contenedores de forma programática
                    </p></li>
<li class="listitem"><p>
                        Recuperar listas de contenedores y archivos
                    </p></li>
</ul></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.rackspace.feature.servers"></a>64.23.4. Cloud Servers</h3></div></div></div>
<p>
            Rackspace Cloud Servers es un servicio de cómputo que proporciona capacidad de servidor en la nube.
            Cloud Servers viene en distintas variantes de memoria, espacio en disco y CPU.
        </p>
<p>
            <code class="classname">Zend_Service_Rackspace_Servers</code> proporciona la siguiente funcionalidad:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        Crear/eliminar nuevos servidores
                    </p></li>
<li class="listitem"><p>
                        Listar y obtener información sobre cada servidor
                    </p></li>
<li class="listitem"><p>
                        Gestionar las direcciones IP públicas/privadas de un servidor
                    </p></li>
<li class="listitem"><p>
                        Redimensionar la capacidad del servidor
                    </p></li>
<li class="listitem"><p>
                        Reiniciar un servidor
                    </p></li>
<li class="listitem"><p>
                        Crear nuevas imágenes de un servidor
                    </p></li>
<li class="listitem"><p>
                        Gestionar la copia de seguridad de un servidor
                    </p></li>
<li class="listitem"><p>
                        Crear un grupo de servidores para compartir las direcciones IP para una arquitectura de alta disponibilidad
                    </p></li>
</ul></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.rackspace.methods"></a>64.23.5. Métodos disponibles</h3></div></div></div>
<p>
            Cada clase de servicio (Files, Servers) de Rackspace extiende la clase abstracta <code class="classname">Zend_Service_Rackspace</code>.
            Esta clase contiene un conjunto de métodos públicos compartidos con todos los servicios.
            Estos métodos públicos se describen a continuación:
        </p>
<div class="variablelist"><dl class="variablelist">
<dt>
<a name="zend.service.rackspace.files.methods.authenticate"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">authenticate</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Autentica la API de Rackspace usando el usuario y la clave especificados en la clase concreta
                        que extiende <code class="classname">Zend_Service_Rackspace</code>.
                        Devuelve <span class="emphasis"><em>true</em></span> en caso de éxito y <span class="emphasis"><em>false</em></span> en caso de error.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.set-service-net"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">setServiceNet</span>(<span class="methodparam">boolean $useServiceNet = true</span>);</code>
                </span>
</dt>
<dd><p>
                        Usa la red interna 'ServiceNet' de Rackspace.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-service-net"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getServiceNet</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        ¿Estamos usando la red interna 'ServiceNet' de Rackspace?
                        Devuelve un booleano.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-auth-url"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getAuthUrl</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene la URL de autenticación de Rackspace.
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-cdn-url"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getCdnUrl</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene la URL de la CDN.
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-error-code"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getErrorCode</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene el último código de error HTTP.
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-error-msg"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getErrorMsg</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene el último mensaje de error.
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-http-client"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getHttpClient</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene el cliente HTTP usado para llamar a la API de Rackspace.
                        Devuelve una instancia de <code class="classname">Zend_Http_Client</code>.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-key"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getKey</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene la clave de autenticación.
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-management-url"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getManagementUrl</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene la URL de los servicios de administración.
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-storage-url"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getStorageUrl</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene la URL del servicio de almacenamiento (archivos).
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-token"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getToken</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene el token devuelto tras una autenticación exitosa.
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.get-user"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">getUser</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Obtiene el usuario autenticado con el servicio de Rackspace.
                        Devuelve una cadena.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.is-successful"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">isSuccessful</span>(<span class="methodparam"></span>);</code>
                </span>
</dt>
<dd><p>
                        Devuelve <span class="emphasis"><em>true</em></span> si la última llamada al servicio fue exitosa, false en caso contrario.
                    </p></dd>
<dt>
<a name="zend.service.rackspace.files.methods.set-auth-url"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">setAuthUrl</span>(<span class="methodparam">string $url</span>);</code>
                </span>
</dt>
<dd>
<p>
                        Establece la URL de autenticación que se usará.
                    </p>
<p>
                        <span class="emphasis"><em>$url</em></span> es la URL para la autenticación
                    </p>
</dd>
<dt>
<a name="zend.service.rackspace.files.methods.set-key"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">setKey</span>(<span class="methodparam">string $key</span>);</code>
                </span>
</dt>
<dd>
<p>
                        Establece la clave para la autenticación de la API.
                    </p>
<p>
                        <span class="emphasis"><em>$key</em></span> es la cadena de la clave para la autenticación
                    </p>
</dd>
<dt>
<a name="zend.service.rackspace.files.methods.set-user"></a><span class="term">
                    <code class="methodsynopsis"><span class="methodname">setUser</span>(<span class="methodparam">string $user</span>);</code>
                </span>
</dt>
<dd>
<p>
                        Establece el usuario para la autenticación de la API.
                    </p>
<p>
                        <span class="emphasis"><em>$user</em></span> es la cadena de usuario para la autenticación
                    </p>
</dd>
</dl></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.livedocx.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.rackspace.files.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.22. Zend_Service_LiveDocx </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 64.24. Zend_Service_Rackspace_Files</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
