<?php $title = '26.6. Constantes para funciones generales de fecha'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">26.6. Constantes para funciones generales de fecha</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.date.creation.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 26. Zend_Date</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.date.additional.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.date.constants"></a>26.6. Constantes para funciones generales de fecha</h2></div></div></div>
<p>
        Siempre que un método de <code class="classname">Zend_Date</code> tenga un parámetro
        <code class="varname">$parts</code>, se puede usar una de las constantes siguientes como argumento
        para ese parámetro, con el fin de seleccionar una parte específica de una fecha o indicar el
        formato de fecha usado o deseado (por ejemplo, <acronym class="acronym">RFC</acronym> 822).
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.date.constants.using"></a>26.6.1. Uso de constantes</h3></div></div></div>
<p>
            Por ejemplo, la constante <code class="constant">Zend_Date::HOUR</code> puede usarse de las
            formas que se muestran a continuación. Cuando se trabaja con días de la semana, fechas
            de calendario, horas, minutos, segundos y cualquier otra parte de fecha que se exprese
            de forma diferente en distintas partes del mundo, la zona horaria del objeto se usará
            automáticamente para calcular el valor correcto, aunque la marca de tiempo interna sea
            la misma para el mismo instante, independientemente de la ubicación física del usuario
            en el mundo. Independientemente de las unidades involucradas, la salida debe expresarse
            como <acronym class="acronym">GMT</acronym> o <acronym class="acronym">UTC</acronym>, o bien
            localizada a un locale. El ejemplo de salida siguiente refleja la localización a
            Europe/GMT+1 hora (por ejemplo, Alemania, Austria, Francia).
        </p>
<div class="table">
<a name="zend.date.constants.using.table"></a><p class="title"><b>Tabla 26.7. Operaciones que involucran Zend_Date::HOUR</b></p>
<div class="table-contents"><table class="table" summary="Operations Involving Zend_Date::HOUR" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Método</th>
<th>Descripción</th>
<th>Fecha original</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td><code class="methodname">get(Zend_Date::HOUR)</code></td>
<td>Salida de la hora</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>14</td>
</tr>
<tr>
<td><code class="methodname">set(12, Zend_Date::HOUR)</code></td>
<td>Establecer nueva hora</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>2009-02-13T12:53:27+01:00</td>
</tr>
<tr>
<td><code class="methodname">add(12, Zend_Date::HOUR)</code></td>
<td>Sumar horas</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>2009-02-14T02:53:27+01:00</td>
</tr>
<tr>
<td><code class="methodname">sub(12, Zend_Date::HOUR)</code></td>
<td>Restar horas</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>2009-02-13T02:53:27+01:00</td>
</tr>
<tr>
<td><code class="methodname">compare(12, Zend_Date::HOUR)</code></td>
<td>Compara la hora, devuelve 0, 1 o -1</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>1 (si objeto &gt; argumento)</td>
</tr>
<tr>
<td><code class="methodname">copy(Zend_Date::HOUR)</code></td>
<td>Copia solo la parte de la hora</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>1970-01-01T14:00:00+01:00</td>
</tr>
<tr>
<td><code class="methodname">equals(14, Zend_Date::HOUR)</code></td>
<td>Compara la hora, devuelve <code class="constant">TRUE</code> o
                        <code class="constant">FALSE</code>
</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><code class="constant">TRUE</code></td>
</tr>
<tr>
<td><code class="methodname">isEarlier(12, Zend_Date::HOUR)</code></td>
<td>Compara la hora, devuelve <code class="constant">TRUE</code> o
                        <code class="constant">FALSE</code>
</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><code class="constant">TRUE</code></td>
</tr>
<tr>
<td><code class="methodname">isLater(12, Zend_Date::HOUR)</code></td>
<td>Compara la hora, devuelve <code class="constant">TRUE</code> o
                        <code class="constant">FALSE</code>
</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><code class="constant">FALSE</code></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.date.constants.list"></a>26.6.2. Lista de todas las constantes</h3></div></div></div>
<p>
            Cada parte de una fecha u hora tiene una constante única en
            <code class="classname">Zend_Date</code>. A continuación se listan todas las constantes
            admitidas por <code class="classname">Zend_Date</code>.
        </p>
<div class="table">
<a name="zend.date.constants.list.table-1"></a><p class="title"><b>Tabla 26.8. Constantes de día</b></p>
<div class="table-contents"><table class="table" summary="Day Constants" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Fecha</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td><code class="constant">Zend_Date::DAY</code></td>
<td>Día (como número, dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>13</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DAY_SHORT</code></td>
<td>Día (como número, uno o dos dígitos)</td>
<td>2009-02-06T14:53:27+01:00</td>
<td><span class="emphasis"><em>6</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::WEEKDAY</code></td>
<td>Día de la semana (nombre del día, localizado, completo)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>Friday</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::WEEKDAY_SHORT</code></td>
<td>
                            Día de la semana (nombre del día, localizado, abreviado, de dos a cuatro caracteres)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>Fri</em></span> para Friday</td>
</tr>
<tr>
<td><code class="constant">Zend_Date::WEEKDAY_NAME</code></td>
<td>
                            Día de la semana (nombre del día, localizado, abreviado, uno o dos caracteres)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>Fr</em></span> para Friday</td>
</tr>
<tr>
<td><code class="constant">Zend_Date::WEEKDAY_NARROW</code></td>
<td>
                            Día de la semana (nombre del día, localizado, abreviado, un carácter)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>F</em></span> para Friday</td>
</tr>
<tr>
<td><code class="constant">Zend_Date::WEEKDAY_DIGIT</code></td>
<td>Día de la semana (0 = domingo, 6 = sábado)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>5</em></span> para Friday</td>
</tr>
<tr>
<td><code class="constant">Zend_Date::WEEKDAY_8601</code></td>
<td>
                            Día de la semana según <acronym class="acronym">ISO</acronym> 8601 (1 = lunes, 7 =
                            domingo)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>5</em></span> para Friday</td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DAY_OF_YEAR</code></td>
<td>Día (como número, uno o dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>43</em></span>
                        </td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DAY_SUFFIX</code></td>
<td>Sufijo en inglés para el día (st, nd, rd, th)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>th</em></span></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><div class="table">
<a name="zend.date.constants.list.table-2"></a><p class="title"><b>Tabla 26.9. Constantes de semana</b></p>
<div class="table-contents"><table class="table" summary="Week Constants" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Fecha</th>
<th>Resultado</th>
</tr></thead>
<tbody><tr>
<td><code class="constant">Zend_Date::WEEK</code></td>
<td>Semana (como número, 1-53)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>8</em></span></td>
</tr></tbody>
</table></div>
</div>
<br class="table-break"><div class="table">
<a name="zend.date.constants.list.table-3"></a><p class="title"><b>Tabla 26.10. Constantes de mes</b></p>
<div class="table-contents"><table class="table" summary="Month Constants" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Fecha</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td><code class="constant">Zend_Date::MONTH_NAME</code></td>
<td>Mes (nombre del mes, localizado, completo)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>February</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MONTH_NAME_SHORT</code></td>
<td>
                            Mes (nombre del mes, localizado, abreviado, de dos a cuatro caracteres)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>Feb</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MONTH_NAME_NARROW</code></td>
<td>
                            Mes (nombre del mes, localizado, abreviado, uno o dos caracteres)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>F</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MONTH</code></td>
<td>Mes (número del mes, dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MONTH_SHORT</code></td>
<td>Mes (número del mes, uno o dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MONTH_DAYS</code></td>
<td>Número de días de ese mes (número)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>28</em></span></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><div class="table">
<a name="zend.date.constants.list.table-4"></a><p class="title"><b>Tabla 26.11. Constantes de año</b></p>
<div class="table-contents"><table class="table" summary="Year Constants" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Fecha</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td><code class="constant">Zend_Date::YEAR</code></td>
<td>Año (número)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>2009</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::YEAR_8601</code></td>
<td>Año según <acronym class="acronym">ISO</acronym> 8601 (número)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>2009</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::YEAR_SHORT</code></td>
<td>Año (número, dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>09</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::YEAR_SHORT_8601</code></td>
<td>
                            Año según <acronym class="acronym">ISO</acronym> 8601 (número, dos dígitos)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>09</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::LEAPYEAR</code></td>
<td>
                            ¿Es el año bisiesto? (<code class="constant">TRUE</code> o
                            <code class="constant">FALSE</code>)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><code class="constant">FALSE</code></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><div class="table">
<a name="zend.date.constants.list.table-5"></a><p class="title"><b>Tabla 26.12. Constantes de hora</b></p>
<div class="table-contents"><table class="table" summary="Time Constants" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Fecha</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td><code class="constant">Zend_Date::HOUR</code></td>
<td>Hora (00-23, dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>14</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::HOUR_SHORT</code></td>
<td>Hora (0-23, uno o dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>14</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::HOUR_SHORT_AM</code></td>
<td>Hora (1-12, uno o dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::HOUR_AM</code></td>
<td>Hora (01-12, dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MINUTE</code></td>
<td>Minuto (00-59, dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>53</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MINUTE_SHORT</code></td>
<td>Minuto (0-59, uno o dos dígitos)</td>
<td>2009-02-13T14:03:27+01:00</td>
<td><span class="emphasis"><em>3</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::SECOND</code></td>
<td>Segundo (00-59, dos dígitos)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>27</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::SECOND_SHORT</code></td>
<td>Segundo (0-59, uno o dos dígitos)</td>
<td>2009-02-13T14:53:07+01:00</td>
<td><span class="emphasis"><em>7</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MILLISECOND</code></td>
<td>Milisegundo (teóricamente infinito)</td>
<td><span class="command"><strong>2009-02-06T14:53:27.20546</strong></span></td>
<td><span class="emphasis"><em>20546</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::MERIDIEM</code></td>
<td>Hora del día (mañana o tarde)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>afternoon</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::SWATCH</code></td>
<td>Swatch Internet Time</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>620</em></span></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><div class="table">
<a name="zend.date.constants.list.table-6"></a><p class="title"><b>Tabla 26.13. Constantes de zona horaria</b></p>
<div class="table-contents"><table class="table" summary="Timezone Constants" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Fecha</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td><code class="constant">Zend_Date::TIMEZONE</code></td>
<td>Nombre de la zona horaria (cadena, abreviada)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em><acronym class="acronym">CET</acronym></em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::TIMEZONE_NAME</code></td>
<td>Nombre de la zona horaria (cadena, completa)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em><span class="command"><strong>Europe/Paris</strong></span></em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::TIMEZONE_SECS</code></td>
<td>
                            Diferencia de la zona horaria respecto a <acronym class="acronym">GMT</acronym> en segundos
                            (entero)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>3600</em></span> (segundos respecto a <acronym class="acronym">GMT</acronym>)</td>
</tr>
<tr>
<td><code class="constant">Zend_Date::GMT_DIFF</code></td>
<td>Diferencia respecto a <acronym class="acronym">GMT</acronym> en segundos (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>+0100</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::GMT_DIFF_SEP</code></td>
<td>
                            Diferencia respecto a <acronym class="acronym">GMT</acronym> en segundos (cadena, separada)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>+01:00</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DAYLIGHT</code></td>
<td>
                            ¿Horario de verano o de invierno? (<code class="constant">TRUE</code> o
                            <code class="constant">FALSE</code>)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><code class="constant">FALSE</code></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><div class="table">
<a name="zend.date.constants.list.table-7"></a><p class="title"><b>Tabla 26.14. Constantes de formato de fecha (los formatos incluyen la zona horaria)</b></p>
<div class="table-contents"><table class="table" summary="Date Format Constants (formats include timezone)" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Fecha</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td><code class="constant">Zend_Date::ISO_8601</code></td>
<td>
                            Fecha según <acronym class="acronym">ISO</acronym> 8601 (cadena, completa)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>2009-02-13T14:53:27+01:00</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::RFC_2822</code></td>
<td>Fecha según <acronym class="acronym">RFC</acronym> 2822 (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>Fri, 13 Feb 2009 14:53:27 +0100</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::TIMESTAMP</code></td>
<td>
                            <a class="ulink" href="http://en.wikipedia.org/wiki/Unix_Time" target="_top">Tiempo Unix</a>
                            (segundos desde el 1.1.1970, mixto)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>1234533207</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::ATOM</code></td>
<td>Fecha según <acronym class="acronym">ATOM</acronym> (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>2009-02-13T14:53:27+01:00</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::COOKIE</code></td>
<td>Fecha para Cookies (cadena, para Cookies)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
                            <span class="emphasis"><em><span class="command"><strong>Friday, 13-Feb-09 14:53:27
                                Europe/Paris</strong></span></em></span>
                        </td>
</tr>
<tr>
<td><code class="constant">Zend_Date::RFC_822</code></td>
<td>Fecha según <acronym class="acronym">RFC</acronym> 822 (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>Fri, 13 Feb 09 14:53:27 +0100</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::RFC_850</code></td>
<td>Fecha según <acronym class="acronym">RFC</acronym> 850 (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
                            <span class="emphasis"><em><span class="command"><strong>Friday, 13-Feb-09 14:53:27
                                Europe/Paris</strong></span></em></span>
                        </td>
</tr>
<tr>
<td><code class="constant">Zend_Date::RFC_1036</code></td>
<td>Fecha según <acronym class="acronym">RFC</acronym> 1036 (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>Fri, 13 Feb 09 14:53:27 +0100</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::RFC_1123</code></td>
<td>Fecha según <acronym class="acronym">RFC</acronym> 1123 (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>Fri, 13 Feb 2009 14:53:27 +0100</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::RFC_3339</code></td>
<td>Fecha según <acronym class="acronym">RFC</acronym> 3339 (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>2009-02-13T14:53:27+01:00</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::RSS</code></td>
<td>Fecha para canales <acronym class="acronym">RSS</acronym> (cadena)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>Fri, 13 Feb 2009 14:53:27 +0100</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::W3C</code></td>
<td>
                            Fecha para <acronym class="acronym">HTML</acronym> o <acronym class="acronym">HTTP</acronym> según
                            <acronym class="acronym">W3C</acronym> (cadena)
                        </td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>2009-02-13T14:53:27+01:00</em></span></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><p>
            Preste especial atención a <code class="constant">Zend_Date::DATES</code>, ya que este
            especificador de formato tiene una propiedad única dentro de
            <code class="classname">Zend_Date</code> como especificador de formato de
            <span class="emphasis"><em>entrada</em></span>. Cuando se usa como formato de entrada para
            <code class="varname">$part</code>, esta constante ofrece la aceptación más flexible de una
            variedad de formatos de fecha similares. Se usan heurísticas para extraer automáticamente
            fechas de una cadena de entrada y luego "corregir" errores simples en las fechas (si los
            hay), como el intercambio de años, meses y días, cuando sea posible.
        </p>
<div class="table">
<a name="zend.date.constants.list.table-8"></a><p class="title"><b>Tabla 26.15. Formatos de fecha y hora (el formato varía según el locale)</b></p>
<div class="table-contents"><table class="table" summary="Date and Time Formats (format varies by locale)" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Fecha</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td><code class="constant">Zend_Date::ERA</code></td>
<td>Era (cadena, localizada, abreviada)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>AD</em></span> (anno Domini)</td>
</tr>
<tr>
<td><code class="constant">Zend_Date::ERA_NAME</code></td>
<td>Era (cadena, localizada, completa)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
<span class="emphasis"><em>anno domini</em></span> (anno Domini)</td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATES</code></td>
<td>Fecha estándar (cadena, localizada, valor predeterminado).</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>13.02.2009</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATE_FULL</code></td>
<td>Fecha completa (cadena, localizada, completa)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>Friday, 13. February 2009</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATE_LONG</code></td>
<td>Fecha larga (cadena, localizada, larga)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>13. February 2009</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATE_MEDIUM</code></td>
<td>Fecha normal (cadena, localizada, normal)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>13.02.2009</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATE_SHORT</code></td>
<td>Fecha abreviada (cadena, localizada, abreviada)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>13.02.09</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::TIMES</code></td>
<td>Hora estándar (cadena, localizada, valor predeterminado)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>14:53:27</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::TIME_FULL</code></td>
<td>Hora completa (cadena, localizada, completa)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em><span class="command"><strong>14:53 Uhr CET</strong></span></em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::TIME_LONG</code></td>
<td>Hora larga (cadena, localizada, larga)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em><span class="command"><strong>14:53:27 CET</strong></span></em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::TIME_MEDIUM</code></td>
<td>Hora normal (cadena, localizada, normal)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>14:53:27</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::TIME_SHORT</code></td>
<td>Hora abreviada (cadena, localizada, abreviada)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>14:53</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATETIME</code></td>
<td>Fecha estándar con hora (cadena, localizada, valor predeterminado).</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>13.02.2009 14:53:27</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATETIME_FULL</code></td>
<td>Fecha completa con hora (cadena, localizada, completa)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
                            <span class="emphasis"><em><span class="command"><strong>Friday, 13. February 2009 14:53 Uhr
                                CET</strong></span></em></span>
                        </td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATETIME_LONG</code></td>
<td>Fecha larga con hora (cadena, localizada, larga)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td>
                            <span class="emphasis"><em><span class="command"><strong>13. February 2009 14:53:27 CET</strong></span></em></span>
                        </td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATETIME_MEDIUM</code></td>
<td>Fecha normal con hora (cadena, localizada, normal)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>13.02.2009 14:53:27</em></span></td>
</tr>
<tr>
<td><code class="constant">Zend_Date::DATETIME_SHORT</code></td>
<td>Fecha abreviada con hora (cadena, localizada, abreviada)</td>
<td>2009-02-13T14:53:27+01:00</td>
<td><span class="emphasis"><em>13.02.09 14:53</em></span></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.date.constants.selfdefinedformats"></a>26.6.3. Formatos de SALIDA autodefinidos con ISO</h3></div></div></div>
<p>
            Si necesita un formato de fecha no mostrado anteriormente, use un formato autodefinido
            compuesto por los especificadores de token de formato <acronym class="acronym">ISO</acronym>
            indicados a continuación. Los siguientes ejemplos ilustran el uso de constantes de la
            tabla siguiente para crear formatos <acronym class="acronym">ISO</acronym> autodefinidos. La
            longitud del formato es ilimitada. Además, se permite el uso múltiple de constantes de
            formato.
        </p>
<p>
            Los especificadores de formato aceptados pueden cambiarse del formato
            <acronym class="acronym">ISO</acronym> al formato de fecha de <acronym class="acronym">PHP</acronym> si
            se siente más cómodo con este. Sin embargo, no todos los formatos definidos en la norma
            <acronym class="acronym">ISO</acronym> son admitidos por los especificadores de formato de fecha de
            <acronym class="acronym">PHP</acronym>. Use el método
            <code class="methodname">Zend_Date::setOptions(array('format_type' =&gt; 'php'))</code> para
            cambiar los métodos de <code class="classname">Zend_Date</code> de admitir especificadores de
            formato <acronym class="acronym">ISO</acronym> a especificadores de tipo
            <code class="methodname">date()</code> de <acronym class="acronym">PHP</acronym> (vea <a class="link" href="zend.date.constants.phtml#zend.date.constants.phpformats" title="26.6.4. Self-Defined OUTPUT Formats Using PHP's date() Format Specifiers">Formatos de
                SALIDA autodefinidos usando los especificadores de formato date() de PHP</a>
            más adelante).
        </p>
<div class="example">
<a name="zend.date.constants.selfdefinedformats.example-1"></a><p class="title"><b>Ejemplo 26.15. Formatos ISO autodefinidos</b></p>
<div class="example-contents"><pre class="programlisting">
$locale = new Zend_Locale('de_AT');
$date = new Zend_Date(1234567890, false, $locale);
print $date-&gt;toString("'Era:GGGG='GGGG, ' Date:yy.MMMM.dd'yy.MMMM.dd");
</pre></div>
</div>
<br class="example-break"><div class="table">
<a name="zend.date.constants.selfdefinedformats.table"></a><p class="title"><b>Tabla 26.16. Constantes para la salida de fecha ISO 8601</b></p>
<div class="table-contents"><table class="table" summary="Constants for ISO 8601 Date Output" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Corresponde mejor a</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td>G</td>
<td>Era, localizada, abreviada</td>
<td><code class="constant">Zend_Date::ERA</code></td>
<td><span class="emphasis"><em>AD</em></span></td>
</tr>
<tr>
<td>GG</td>
<td>Era, localizada, abreviada</td>
<td><code class="constant">Zend_Date::ERA</code></td>
<td><span class="emphasis"><em>AD</em></span></td>
</tr>
<tr>
<td><code class="constant">GGG</code></td>
<td>Era, localizada, abreviada</td>
<td><code class="constant">Zend_Date::ERA</code></td>
<td><span class="emphasis"><em>AD</em></span></td>
</tr>
<tr>
<td><code class="constant">GGGG</code></td>
<td>Era, localizada, completa</td>
<td><code class="constant">Zend_Date::ERA_NAME</code></td>
<td><span class="emphasis"><em>anno domini</em></span></td>
</tr>
<tr>
<td><code class="constant">GGGGG</code></td>
<td>Era, localizada, abreviada</td>
<td><code class="constant">Zend_Date::ERA</code></td>
<td><span class="emphasis"><em>a</em></span></td>
</tr>
<tr>
<td>y</td>
<td>Año, al menos un dígito</td>
<td><code class="constant">Zend_Date::YEAR</code></td>
<td><span class="emphasis"><em>9</em></span></td>
</tr>
<tr>
<td>yy</td>
<td>Año, al menos dos dígitos</td>
<td><code class="constant">Zend_Date::YEAR_SHORT</code></td>
<td><span class="emphasis"><em>09</em></span></td>
</tr>
<tr>
<td>yyy</td>
<td>Año, al menos tres dígitos</td>
<td><code class="constant">Zend_Date::YEAR</code></td>
<td><span class="emphasis"><em>2009</em></span></td>
</tr>
<tr>
<td>yyyy</td>
<td>Año, al menos cuatro dígitos</td>
<td><code class="constant">Zend_Date::YEAR</code></td>
<td><span class="emphasis"><em>2009</em></span></td>
</tr>
<tr>
<td>yyyyy</td>
<td>Año, al menos cinco dígitos</td>
<td><code class="constant">Zend_Date::YEAR</code></td>
<td><span class="emphasis"><em>02009</em></span></td>
</tr>
<tr>
<td>Y</td>
<td>
                            Año según <acronym class="acronym">ISO</acronym> 8601, al menos un dígito
                        </td>
<td><code class="constant">Zend_Date::YEAR_8601</code></td>
<td><span class="emphasis"><em>9</em></span></td>
</tr>
<tr>
<td>YY</td>
<td>
                            Año según <acronym class="acronym">ISO</acronym> 8601, al menos dos dígitos
                        </td>
<td><code class="constant">Zend_Date::YEAR_SHORT_8601</code></td>
<td><span class="emphasis"><em>09</em></span></td>
</tr>
<tr>
<td><code class="constant">YYY</code></td>
<td>
                            Año según <acronym class="acronym">ISO</acronym> 8601, al menos tres dígitos
                        </td>
<td><code class="constant">Zend_Date::YEAR_8601</code></td>
<td><span class="emphasis"><em>2009</em></span></td>
</tr>
<tr>
<td><code class="constant">YYYY</code></td>
<td>
                            Año según <acronym class="acronym">ISO</acronym> 8601, al menos cuatro dígitos
                        </td>
<td><code class="constant">Zend_Date::YEAR_8601</code></td>
<td><span class="emphasis"><em>2009</em></span></td>
</tr>
<tr>
<td><code class="constant">YYYYY</code></td>
<td>
                            Año según <acronym class="acronym">ISO</acronym> 8601, al menos cinco dígitos
                        </td>
<td><code class="constant">Zend_Date::YEAR_8601</code></td>
<td><span class="emphasis"><em>02009</em></span></td>
</tr>
<tr>
<td>M</td>
<td>Mes, uno o dos dígitos</td>
<td><code class="constant">Zend_Date::MONTH_SHORT</code></td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td>MM</td>
<td>Mes, dos dígitos</td>
<td><code class="constant">Zend_Date::MONTH</code></td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td><code class="constant">MMM</code></td>
<td>Mes, localizado, abreviado</td>
<td><code class="constant">Zend_Date::MONTH_NAME_SHORT</code></td>
<td><span class="emphasis"><em>Feb</em></span></td>
</tr>
<tr>
<td><code class="constant">MMMM</code></td>
<td>Mes, localizado, completo</td>
<td><code class="constant">Zend_Date::MONTH_NAME</code></td>
<td><span class="emphasis"><em>February</em></span></td>
</tr>
<tr>
<td><code class="constant">MMMMM</code></td>
<td>Mes, localizado, abreviado, un dígito</td>
<td><code class="constant">Zend_Date::MONTH_NAME_NARROW</code></td>
<td><span class="emphasis"><em>F</em></span></td>
</tr>
<tr>
<td>w</td>
<td>Semana, uno o dos dígitos</td>
<td><code class="constant">Zend_Date::WEEK</code></td>
<td><span class="emphasis"><em>5</em></span></td>
</tr>
<tr>
<td>ww</td>
<td>Semana, dos dígitos</td>
<td><code class="constant">Zend_Date::WEEK</code></td>
<td><span class="emphasis"><em>05</em></span></td>
</tr>
<tr>
<td>d</td>
<td>Día del mes, uno o dos dígitos</td>
<td><code class="constant">Zend_Date::DAY_SHORT</code></td>
<td><span class="emphasis"><em>9</em></span></td>
</tr>
<tr>
<td>dd</td>
<td>Día del mes, dos dígitos</td>
<td><code class="constant">Zend_Date::DAY</code></td>
<td><span class="emphasis"><em>09</em></span></td>
</tr>
<tr>
<td>D</td>
<td>Día del año, uno, dos o tres dígitos</td>
<td><code class="constant">Zend_Date::DAY_OF_YEAR</code></td>
<td><span class="emphasis"><em>7</em></span></td>
</tr>
<tr>
<td>DD</td>
<td>Día del año, dos o tres dígitos</td>
<td><code class="constant">Zend_Date::DAY_OF_YEAR</code></td>
<td><span class="emphasis"><em>07</em></span></td>
</tr>
<tr>
<td><code class="constant">DDD</code></td>
<td>Día del año, tres dígitos</td>
<td><code class="constant">Zend_Date::DAY_OF_YEAR</code></td>
<td><span class="emphasis"><em>007</em></span></td>
</tr>
<tr>
<td>E</td>
<td>Día de la semana, localizado, abreviado, un carácter</td>
<td><code class="constant">Zend_Date::WEEKDAY_NARROW</code></td>
<td><span class="emphasis"><em>M</em></span></td>
</tr>
<tr>
<td>EE</td>
<td>Día de la semana, localizado, abreviado, dos o más caracteres</td>
<td><code class="constant">Zend_Date::WEEKDAY_NAME</code></td>
<td><span class="emphasis"><em>Mo</em></span></td>
</tr>
<tr>
<td><code class="constant">EEE</code></td>
<td>Día de la semana, localizado, abreviado, tres caracteres</td>
<td><code class="constant">Zend_Date::WEEKDAY_SHORT</code></td>
<td><span class="emphasis"><em>Mon</em></span></td>
</tr>
<tr>
<td><code class="constant">EEEE</code></td>
<td>Día de la semana, localizado, completo</td>
<td><code class="constant">Zend_Date::WEEKDAY</code></td>
<td><span class="emphasis"><em>Monday</em></span></td>
</tr>
<tr>
<td><code class="constant">EEEEE</code></td>
<td>Día de la semana, localizado, abreviado, un dígito</td>
<td><code class="constant">Zend_Date::WEEKDAY_NARROW</code></td>
<td><span class="emphasis"><em>M</em></span></td>
</tr>
<tr>
<td>e</td>
<td>Número del día, un dígito</td>
<td><code class="constant">Zend_Date::WEEKDAY_DIGIT</code></td>
<td><span class="emphasis"><em>4</em></span></td>
</tr>
<tr>
<td>ee</td>
<td>Número del día, dos dígitos</td>
<td><code class="constant">Zend_Date::WEEKDAY_NARROW</code></td>
<td><span class="emphasis"><em>04</em></span></td>
</tr>
<tr>
<td>a</td>
<td>Hora del día, localizada</td>
<td><code class="constant">Zend_Date::MERIDIEM</code></td>
<td><span class="emphasis"><em>vorm.</em></span></td>
</tr>
<tr>
<td>h</td>
<td>Hora, (1-12), uno o dos dígitos</td>
<td><code class="constant">Zend_Date::HOUR_SHORT_AM</code></td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td>hh</td>
<td>Hora, (01-12), dos dígitos</td>
<td><code class="constant">Zend_Date::HOUR_AM</code></td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>H</td>
<td>Hora, (0-23), uno o dos dígitos</td>
<td><code class="constant">Zend_Date::HOUR_SHORT</code></td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td>HH</td>
<td>Hora, (00-23), dos dígitos</td>
<td><code class="constant">Zend_Date::HOUR</code></td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>m</td>
<td>Minuto, (0-59), uno o dos dígitos</td>
<td><code class="constant">Zend_Date::MINUTE_SHORT</code></td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td>mm</td>
<td>Minuto, (00-59), dos dígitos</td>
<td><code class="constant">Zend_Date::MINUTE</code></td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>s</td>
<td>Segundo, (0-59), uno o dos dígitos</td>
<td><code class="constant">Zend_Date::SECOND_SHORT</code></td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td>ss</td>
<td>Segundo, (00-59), dos dígitos</td>
<td><code class="constant">Zend_Date::SECOND</code></td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>S</td>
<td>Milisegundo</td>
<td><code class="constant">Zend_Date::MILLISECOND</code></td>
<td><span class="emphasis"><em>20536</em></span></td>
</tr>
<tr>
<td>z</td>
<td>Zona horaria, localizada, abreviada</td>
<td><code class="constant">Zend_Date::TIMEZONE</code></td>
<td><span class="emphasis"><em><code class="constant">CET</code></em></span></td>
</tr>
<tr>
<td>zz</td>
<td>Zona horaria, localizada, abreviada</td>
<td><code class="constant">Zend_Date::TIMEZONE</code></td>
<td><span class="emphasis"><em><code class="constant">CET</code></em></span></td>
</tr>
<tr>
<td>zzz</td>
<td>Zona horaria, localizada, abreviada</td>
<td><code class="constant">Zend_Date::TIMEZONE</code></td>
<td><span class="emphasis"><em><code class="constant">CET</code></em></span></td>
</tr>
<tr>
<td>zzzz</td>
<td>Zona horaria, localizada, completa</td>
<td><code class="constant">Zend_Date::TIMEZONE_NAME</code></td>
<td><span class="emphasis"><em><span class="command"><strong>Europe/Paris</strong></span></em></span></td>
</tr>
<tr>
<td>Z</td>
<td>Diferencia de zona horaria</td>
<td><code class="constant">Zend_Date::GMT_DIFF</code></td>
<td><span class="emphasis"><em>+0100</em></span></td>
</tr>
<tr>
<td>ZZ</td>
<td>Diferencia de zona horaria</td>
<td><code class="constant">Zend_Date::GMT_DIFF</code></td>
<td><span class="emphasis"><em>+0100</em></span></td>
</tr>
<tr>
<td><code class="constant">ZZZ</code></td>
<td>Diferencia de zona horaria</td>
<td><code class="constant">Zend_Date::GMT_DIFF</code></td>
<td><span class="emphasis"><em>+0100</em></span></td>
</tr>
<tr>
<td><code class="constant">ZZZZ</code></td>
<td>Diferencia de zona horaria, separada</td>
<td><code class="constant">Zend_Date::GMT_DIFF_SEP</code></td>
<td><span class="emphasis"><em>+01:00</em></span></td>
</tr>
<tr>
<td>A</td>
<td>Milisegundos del día actual</td>
<td><code class="constant">Zend_Date::MILLISECOND</code></td>
<td><span class="emphasis"><em>20563</em></span></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Tenga en cuenta que el formato <acronym class="acronym">ISO</acronym> predeterminado difiere
                del formato de <acronym class="acronym">PHP</acronym>, lo cual puede resultar molesto si no lo
                ha usado antes. En particular, los especificadores de formato para
                <span class="emphasis"><em>año y minuto</em></span> a menudo no se usan de la forma prevista.
            </p>
<p>
                Para el <span class="emphasis"><em>año</em></span> hay dos especificadores disponibles que a
                menudo se confunden. El especificador <span class="emphasis"><em>Y</em></span> para el año
                <acronym class="acronym">ISO</acronym> y el especificador <span class="emphasis"><em>y</em></span>
                para el año real. La diferencia es pequeña pero significativa.
                <span class="emphasis"><em>Y</em></span> calcula el año <acronym class="acronym">ISO</acronym>, que
                se usa a menudo para formatos de calendario. Vea por ejemplo el 31 de diciembre de
                2007. El año real es 2007, pero es el primer día de la primera semana de la semana
                1 del año 2008. Así, si usa '<span class="command"><strong>dd.MM.yyyy</strong></span>' obtendrá
                '<span class="command"><strong>31.December.2007</strong></span>', pero si usa
                '<span class="command"><strong>dd.MM.YYYY</strong></span>' obtendrá
                '<span class="command"><strong>31.December.2008</strong></span>'. Como puede ver, esto no es
                un error sino un comportamiento esperado según los especificadores usados.
            </p>
<p>
                Para el <span class="emphasis"><em>minuto</em></span> la diferencia no es tan grande.
                <acronym class="acronym">ISO</acronym> usa el especificador <span class="emphasis"><em>m</em></span>
                para el minuto, a diferencia de <acronym class="acronym">PHP</acronym>, que usa
                <span class="emphasis"><em>i</em></span>. Así que si no obtiene el minuto en su formato,
                compruebe si ha usado el especificador correcto.
            </p>
</td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.date.constants.phpformats"></a>26.6.4. Formatos de SALIDA autodefinidos usando los especificadores de formato date() de PHP</h3></div></div></div>
<p>
            Si se siente más cómodo con el especificador de formato de fecha de
            <acronym class="acronym">PHP</acronym> que con los especificadores de formato
            <acronym class="acronym">ISO</acronym>, puede usar el método
            <code class="methodname">Zend_Date::setOptions(array('format_type' =&gt; 'php'))</code> para
            cambiar los métodos de <code class="classname">Zend_Date</code> de admitir especificadores de
            formato <acronym class="acronym">ISO</acronym> a especificadores de tipo
            <code class="methodname">date()</code> de <acronym class="acronym">PHP</acronym>. Después de esto,
            todos los parámetros de formato deben especificarse con los
            <a class="ulink" href="http://php.net/date" target="_top">especificadores de formato de
                <code class="methodname">date()</code> de PHP</a>. El formato de fecha de
            <acronym class="acronym">PHP</acronym> carece de algunos formatos admitidos por el formato
            <acronym class="acronym">ISO</acronym>, y viceversa. Si aún no se siente cómodo con él, use en su
            lugar el formato <acronym class="acronym">ISO</acronym> estándar. Además, si tiene código heredado
            que usa el formato de fecha de <acronym class="acronym">PHP</acronym>, entonces conviértalo
            manualmente al formato <acronym class="acronym">ISO</acronym> usando
            <a class="link" href="zend.locale.date.datesandtimes.phtml#zend.locale.date.normalize" title="43.4.1. Normalizing Dates and Times">Zend_Locale_Format::convertPhpToIsoFormat()</a>,
            o use <code class="methodname">setOptions()</code>. Los siguientes ejemplos ilustran el uso de
            constantes de la tabla siguiente para crear formatos autodefinidos.
        </p>
<div class="example">
<a name="zend.date.constants.phpformats.example-1"></a><p class="title"><b>Ejemplo 26.16. Formatos autodefinidos con especificador de PHP</b></p>
<div class="example-contents"><pre class="programlisting">
$locale = new Zend_Locale('de_AT');
Zend_Date::setOptions(array('format_type' =&gt; 'php'));
$date = new Zend_Date(1234567890, false, $locale);

// outputs something like 'February 16, 2007, 3:36 am'
print $date-&gt;toString('F j, Y, g:i a');

print $date-&gt;toString("'Format:D M j G:i:s T Y='D M j G:i:s T Y");
</pre></div>
</div>
<br class="example-break"><div class="important"><table border="0" summary="Important: PHP Date format and using constants">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Important]" src="images/important.png"></td>
<th align="left">Formato de fecha de PHP y uso de constantes</th>
</tr>
<tr><td align="left" valign="top"><p>
                Es importante notar que las constantes de <code class="classname">Zend_Date</code> usan la
                notación <acronym class="acronym">ISO</acronym>. Esto significa que, cuando configure
                <code class="classname">Zend_Date</code> para usar la notación <acronym class="acronym">PHP</acronym>,
                no debe usar las constantes de <code class="classname">Zend_Date</code>, sino definir
                manualmente el formato deseado. Si no sigue esta recomendación, puede obtener
                resultados inesperados.
            </p></td></tr>
</table></div>
<p>
            La siguiente tabla muestra la lista de especificadores de formato de fecha de
            <acronym class="acronym">PHP</acronym> con sus constantes equivalentes de
            <code class="classname">Zend_Date</code> y los especificadores de formato equivalentes de
            <acronym class="acronym">CLDR</acronym> e <acronym class="acronym">ISO</acronym>. En la mayoría de los
            casos, cuando el formato <acronym class="acronym">CLDR</acronym> e <acronym class="acronym">ISO</acronym>
            no tiene un especificador de formato equivalente, el especificador de formato de
            <acronym class="acronym">PHP</acronym> no es alterado por
            <code class="methodname">Zend_Locale_Format::convertPhpToIsoFormat()</code>, y los métodos de
            <code class="classname">Zend_Date</code> reconocen entonces estos especificadores de formato
            <acronym class="acronym">PHP</acronym> "peculiares", incluso en el modo de formato
            "<acronym class="acronym">ISO</acronym>" predeterminado.
        </p>
<div class="table">
<a name="zend.date.constants.phpformats.table"></a><p class="title"><b>Tabla 26.17. Constantes para la salida de fecha de PHP</b></p>
<div class="table-contents"><table class="table" summary="Constants for PHP Date Output" border="1">
<colgroup>
<col>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Constante</th>
<th>Descripción</th>
<th>Corresponde mejor a</th>
<th>equivalente <acronym class="acronym">CLDR</acronym> más cercano</th>
<th>Resultado</th>
</tr></thead>
<tbody>
<tr>
<td>d</td>
<td>Día del mes, dos dígitos</td>
<td><code class="constant">Zend_Date::DAY</code></td>
<td>dd</td>
<td><span class="emphasis"><em>09</em></span></td>
</tr>
<tr>
<td>D</td>
<td>Día de la semana, localizado, abreviado, tres dígitos</td>
<td><code class="constant">Zend_Date::WEEKDAY_SHORT</code></td>
<td><code class="constant">EEE</code></td>
<td><span class="emphasis"><em>Mon</em></span></td>
</tr>
<tr>
<td>j</td>
<td>Día del mes, uno o dos dígitos</td>
<td><code class="constant">Zend_Date::DAY_SHORT</code></td>
<td>d</td>
<td><span class="emphasis"><em>9</em></span></td>
</tr>
<tr>
<td>l (l minúscula)</td>
<td>Día de la semana, localizado, completo</td>
<td><code class="constant">Zend_Date::WEEKDAY</code></td>
<td><code class="constant">EEEE</code></td>
<td><span class="emphasis"><em>Monday</em></span></td>
</tr>
<tr>
<td>N</td>
<td>Número del día de la semana, un dígito</td>
<td><code class="constant">Zend_Date::WEEKDAY_8601</code></td>
<td>e</td>
<td><span class="emphasis"><em>4</em></span></td>
</tr>
<tr>
<td>S</td>
<td>Sufijos en inglés para el día del mes, dos caracteres</td>
<td>sin equivalente</td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>st</em></span></td>
</tr>
<tr>
<td>w</td>
<td>Número del día de la semana, 0=domingo, 6=sábado</td>
<td><code class="constant">Zend_Date::WEEKDAY_DIGIT</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>4</em></span></td>
</tr>
<tr>
<td>z</td>
<td>Día del año, uno, dos o tres dígitos</td>
<td><code class="constant">Zend_Date::DAY_OF_YEAR</code></td>
<td>D</td>
<td><span class="emphasis"><em>7</em></span></td>
</tr>
<tr>
<td>W</td>
<td>Semana, uno o dos dígitos</td>
<td><code class="constant">Zend_Date::WEEK</code></td>
<td>w</td>
<td><span class="emphasis"><em>5</em></span></td>
</tr>
<tr>
<td>F</td>
<td>Mes, localizado, completo</td>
<td><code class="constant">Zend_Date::MONTH_NAME</code></td>
<td><code class="constant">MMMM</code></td>
<td><span class="emphasis"><em>February</em></span></td>
</tr>
<tr>
<td>m</td>
<td>Mes, dos dígitos</td>
<td><code class="constant">Zend_Date::MONTH</code></td>
<td>MM</td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>M</td>
<td>Mes, localizado, abreviado</td>
<td><code class="constant">Zend_Date::MONTH_NAME_SHORT</code></td>
<td><code class="constant">MMM</code></td>
<td><span class="emphasis"><em>Feb</em></span></td>
</tr>
<tr>
<td>n</td>
<td>Mes, uno o dos dígitos</td>
<td><code class="constant">Zend_Date::MONTH_SHORT</code></td>
<td>M</td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td>t</td>
<td>Número de días por mes, uno o dos dígitos</td>
<td><code class="constant">Zend_Date::MONTH_DAYS</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>30</em></span></td>
</tr>
<tr>
<td>L</td>
<td>Año bisiesto, booleano</td>
<td><code class="constant">Zend_Date::LEAPYEAR</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em><code class="constant">TRUE</code></em></span></td>
</tr>
<tr>
<td>o</td>
<td>
                            Año según <acronym class="acronym">ISO</acronym> 8601, al menos cuatro dígitos
                        </td>
<td><code class="constant">Zend_Date::YEAR_8601</code></td>
<td><code class="constant">YYYY</code></td>
<td><span class="emphasis"><em>2009</em></span></td>
</tr>
<tr>
<td>Y</td>
<td>Año, al menos cuatro dígitos</td>
<td><code class="constant">Zend_Date::YEAR</code></td>
<td>yyyy</td>
<td><span class="emphasis"><em>2009</em></span></td>
</tr>
<tr>
<td>y</td>
<td>Año, al menos dos dígitos</td>
<td><code class="constant">Zend_Date::YEAR_SHORT</code></td>
<td>yy</td>
<td><span class="emphasis"><em>09</em></span></td>
</tr>
<tr>
<td>a</td>
<td>Hora del día, localizada</td>
<td><code class="constant">Zend_Date::MERIDIEM</code></td>
<td>a (más o menos, pero probablemente en mayúsculas)</td>
<td><span class="emphasis"><em>vorm.</em></span></td>
</tr>
<tr>
<td>A</td>
<td>Hora del día, localizada</td>
<td><code class="constant">Zend_Date::MERIDIEM</code></td>
<td>a (más o menos, pero sin garantía de que el formato esté en mayúsculas)</td>
<td><span class="emphasis"><em><span class="command"><strong>VORM.</strong></span></em></span></td>
</tr>
<tr>
<td>B</td>
<td>Swatch internet time</td>
<td><code class="constant">Zend_Date::SWATCH</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>1463</em></span></td>
</tr>
<tr>
<td>g</td>
<td>Hora, (1-12), uno o dos dígitos</td>
<td><code class="constant">Zend_Date::HOUR_SHORT_AM</code></td>
<td>h</td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td>G</td>
<td>Hora, (0-23), uno o dos dígitos</td>
<td><code class="constant">Zend_Date::HOUR_SHORT</code></td>
<td>H</td>
<td><span class="emphasis"><em>2</em></span></td>
</tr>
<tr>
<td>h</td>
<td>Hora, (01-12), dos dígitos</td>
<td><code class="constant">Zend_Date::HOUR_AM</code></td>
<td>hh</td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>H</td>
<td>Hora, (00-23), dos dígitos</td>
<td><code class="constant">Zend_Date::HOUR</code></td>
<td>HH</td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>i</td>
<td>Minuto, (00-59), dos dígitos</td>
<td><code class="constant">Zend_Date::MINUTE</code></td>
<td>mm</td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>s</td>
<td>Segundo, (00-59), dos dígitos</td>
<td><code class="constant">Zend_Date::SECOND</code></td>
<td>ss</td>
<td><span class="emphasis"><em>02</em></span></td>
</tr>
<tr>
<td>e</td>
<td>Zona horaria, localizada, completa</td>
<td><code class="constant">Zend_Date::TIMEZONE_NAME</code></td>
<td>zzzz</td>
<td><span class="emphasis"><em><span class="command"><strong>Europe/Paris</strong></span></em></span></td>
</tr>
<tr>
<td>I</td>
<td>Horario de verano</td>
<td><code class="constant">Zend_Date::DAYLIGHT</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>1</em></span></td>
</tr>
<tr>
<td>O</td>
<td>Diferencia de zona horaria</td>
<td><code class="constant">Zend_Date::GMT_DIFF</code></td>
<td>Z, ZZ o <code class="constant">ZZZ</code>
</td>
<td><span class="emphasis"><em>+0100</em></span></td>
</tr>
<tr>
<td>P</td>
<td>Diferencia de zona horaria, separada</td>
<td><code class="constant">Zend_Date::GMT_DIFF_SEP</code></td>
<td><code class="constant">ZZZZ</code></td>
<td><span class="emphasis"><em>+01:00</em></span></td>
</tr>
<tr>
<td>T</td>
<td>Zona horaria, localizada, abreviada</td>
<td><code class="constant">Zend_Date::TIMEZONE</code></td>
<td>z, zz o zzz</td>
<td><span class="emphasis"><em><code class="constant">CET</code></em></span></td>
</tr>
<tr>
<td>Z</td>
<td>Desplazamiento de zona horaria en segundos</td>
<td><code class="constant">Zend_Date::TIMEZONE_SECS</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>3600</em></span></td>
</tr>
<tr>
<td>c</td>
<td>Salida en formato Iso estándar</td>
<td><code class="constant">Zend_Date::ISO_8601</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>2004-02-13T15:19:21+00:00</em></span></td>
</tr>
<tr>
<td>r</td>
<td>Salida en formato Rfc 2822 estándar</td>
<td><code class="constant">Zend_Date::RFC_2822</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>Thu, 21 Dec 2000 16:01:07 +0200</em></span></td>
</tr>
<tr>
<td>U</td>
<td>Marca de tiempo Unix</td>
<td><code class="constant">Zend_Date::TIMESTAMP</code></td>
<td>sin equivalente</td>
<td><span class="emphasis"><em>15275422364</em></span></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.date.creation.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.date.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.date.additional.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">26.5. Creación de fechas </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 26.7. Ejemplos prácticos</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
