<?php $title = '64.18. Zend_Service_Delicious'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.18. Zend_Service_Delicious</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.audioscrobbler.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.ebay.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.delicious"></a>64.18. Zend_Service_Delicious</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.introduction"></a>64.18.1. Introducción</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Delicious</code> es una <acronym class="acronym">API</acronym> sencilla para utilizar
            los servicios web <acronym class="acronym">XML</acronym> y <acronym class="acronym">JSON</acronym> de
            <a class="ulink" href="http://del.icio.us" target="_top">del.icio.us</a>. Este componente le proporciona acceso de lectura y escritura a
            las entradas de del.icio.us si proporciona credenciales. También permite el acceso de solo lectura a
            los datos públicos de todos los usuarios.
        </p>
<div class="example">
<a name="zend.service.delicious.introduction.getAllPosts"></a><p class="title"><b>Ejemplo 64.80. Obtener todas las entradas</b></p>
<div class="example-contents"><pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');
$posts = $delicious-&gt;getAllPosts();

foreach ($posts as $post) {
    echo "--\n";
    echo "Title: {$post-&gt;getTitle()}\n";
    echo "Url: {$post-&gt;getUrl()}\n";
}
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.retrieving_posts"></a>64.18.2. Obtener entradas</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Delicious</code> proporciona tres métodos para obtener
            entradas: <code class="methodname">getPosts()</code>, <code class="methodname">getRecentPosts()</code>
            y <code class="methodname">getAllPosts()</code>. Todos estos métodos devuelven una instancia de
            <code class="classname">Zend_Service_Delicious_PostList</code>, que contiene todas las entradas obtenidas.
        </p>
<pre class="programlisting">
/**
 * Get posts matching the arguments. If no date or url is given,
 * most recent date will be used.
 *
 * @param string $tag Optional filtering by tag
 * @param Zend_Date $dt Optional filtering by date
 * @param string $url Optional filtering by url
 * @return Zend_Service_Delicious_PostList
 */
public function getPosts($tag = null, $dt = null, $url = null);

/**
 * Get recent posts
 *
 * @param string $tag   Optional filtering by tag
 * @param string $count Maximal number of posts to be returned
 *                      (default 15)
 * @return Zend_Service_Delicious_PostList
 */
public function getRecentPosts($tag = null, $count = 15);

/**
 * Get all posts
 *
 * @param string $tag Optional filtering by tag
 * @return Zend_Service_Delicious_PostList
 */
public function getAllPosts($tag = null);
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.postlist"></a>64.18.3. Zend_Service_Delicious_PostList</h3></div></div></div>
<p>
            Los métodos <code class="methodname">getPosts()</code>,
            <code class="methodname">getAllPosts()</code>, <code class="methodname">getRecentPosts()</code> y
            <code class="methodname">getUserPosts()</code> de
            <code class="classname">Zend_Service_Delicious</code> devuelven instancias de esta clase.
        </p>
<p>
            Para facilitar el acceso a los datos, esta clase implementa las interfaces <code class="code">Countable</code>,
            <code class="code">Iterator</code> y <code class="code">ArrayAccess</code>.
        </p>
<div class="example">
<a name="zend.service.delicious.postlist.accessing_post_lists"></a><p class="title"><b>Ejemplo 64.81. Acceder a listas de entradas</b></p>
<div class="example-contents"><pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');
$posts = $delicious-&gt;getAllPosts();

// count posts
echo count($posts);

// iterate over posts
foreach ($posts as $post) {
    echo "--\n";
    echo "Title: {$post-&gt;getTitle()}\n";
    echo "Url: {$post-&gt;getUrl()}\n";
}

// get post using array access
echo $posts[0]-&gt;getTitle();
</pre></div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Los métodos <code class="methodname">ArrayAccess::offsetSet()</code> y
                <code class="methodname">ArrayAccess::offsetUnset()</code> lanzan excepciones en esta
                implementación. Por lo tanto, un código como <code class="code">unset($posts[0]);</code> y
                <code class="code">$posts[0] = 'A';</code> lanzará excepciones porque estas propiedades son
                de solo lectura.
            </p></td></tr>
</table></div>
<p>
            Los objetos de lista de entradas tienen dos capacidades de filtrado integradas. Las listas de entradas pueden filtrarse
            por etiquetas y por <acronym class="acronym">URL</acronym>.
        </p>
<div class="example">
<a name="zend.service.delicious.postlist.example.withTags"></a><p class="title"><b>Ejemplo 64.82. Filtrar una lista de entradas con etiquetas específicas</b></p>
<div class="example-contents">
<p>
                Las entradas pueden filtrarse por etiquetas específicas usando <code class="methodname">withTags()</code>. Como
                comodidad, también se proporciona <code class="methodname">withTag()</code> para cuando solo se necesite especificar
                una única etiqueta.
            </p>
<pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');
$posts = $delicious-&gt;getAllPosts();

// Print posts having "php" and "zend" tags
foreach ($posts-&gt;withTags(array('php', 'zend')) as $post) {
    echo "Title: {$post-&gt;getTitle()}\n";
    echo "Url: {$post-&gt;getUrl()}\n";
}
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.service.delicious.postlist.example.byUrl"></a><p class="title"><b>Ejemplo 64.83. Filtrar una lista de entradas por URL</b></p>
<div class="example-contents">
<p>
                Las entradas pueden filtrarse por <acronym class="acronym">URL</acronym> haciendo coincidir una expresión
                regular especificada mediante el método <code class="methodname">withUrl()</code>:
            </p>
<pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');
$posts = $delicious-&gt;getAllPosts();

// Print posts having "help" in the URL
foreach ($posts-&gt;withUrl('/help/') as $post) {
    echo "Title: {$post-&gt;getTitle()}\n";
    echo "Url: {$post-&gt;getUrl()}\n";
}
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.editing_posts"></a>64.18.4. Editar entradas</h3></div></div></div>
<div class="example">
<a name="zend.service.delicious.editing_posts.post_editing"></a><p class="title"><b>Ejemplo 64.84. Edición de una entrada</b></p>
<div class="example-contents"><pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');
$posts = $delicious-&gt;getPosts();

// set title
$posts[0]-&gt;setTitle('New title');
// save changes
$posts[0]-&gt;save();
</pre></div>
</div>
<br class="example-break"><div class="example">
<a name="zend.service.delicious.editing_posts.method_call_chaining"></a><p class="title"><b>Ejemplo 64.85. Encadenamiento de llamadas a métodos</b></p>
<div class="example-contents">
<p>
               Cada método setter devuelve el objeto de la entrada, de modo que puede encadenar llamadas a métodos usando
               una interfaz fluida.
            </p>
<pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');
$posts = $delicious-&gt;getPosts();

$posts[0]-&gt;setTitle('New title')
         -&gt;setNotes('New notes')
         -&gt;save();
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.deleting_posts"></a>64.18.5. Eliminar entradas</h3></div></div></div>
<p>
            Hay dos formas de eliminar una entrada: especificando la <acronym class="acronym">URL</acronym> de la entrada o
            llamando al método <code class="methodname">delete()</code> sobre un objeto de entrada.
        </p>
<div class="example">
<a name="zend.service.delicious.deleting_posts.deleting_posts"></a><p class="title"><b>Ejemplo 64.86. Eliminar entradas</b></p>
<div class="example-contents"><pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');

// by specifying URL
$delicious-&gt;deletePost('http://framework.zend.com');

// or by calling the method upon a post object
$posts = $delicious-&gt;getPosts();
$posts[0]-&gt;delete();

// another way of using deletePost()
$delicious-&gt;deletePost($posts[0]-&gt;getUrl());
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.adding_posts"></a>64.18.6. Agregar nuevas entradas</h3></div></div></div>
<p>
            Para agregar una entrada, primero debe llamar al método <code class="methodname">createNewPost()</code>,
            que devuelve un objeto <code class="classname">Zend_Service_Delicious_Post</code>. Cuando
            edite la entrada, deberá guardarla en la base de datos de del.icio.us llamando al método
            <code class="methodname">save()</code>.
        </p>
<div class="example">
<a name="zend.service.delicious.adding_posts.adding_a_post"></a><p class="title"><b>Ejemplo 64.87. Agregar una entrada</b></p>
<div class="example-contents"><pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');

// create a new post and save it (with method call chaining)
$delicious-&gt;createNewPost('Zend Framework', 'http://framework.zend.com')
          -&gt;setNotes('Zend Framework Homepage')
          -&gt;save();

// create a new post and save it  (without method call chaining)
$newPost = $delicious-&gt;createNewPost('Zend Framework',
                                     'http://framework.zend.com');
$newPost-&gt;setNotes('Zend Framework Homepage');
$newPost-&gt;save();
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.tags"></a>64.18.7. Etiquetas</h3></div></div></div>
<div class="example">
<a name="zend.service.delicious.tags.tags"></a><p class="title"><b>Ejemplo 64.88. Etiquetas</b></p>
<div class="example-contents"><pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');

// get all tags
print_r($delicious-&gt;getTags());

// rename tag ZF to zendFramework
$delicious-&gt;renameTag('ZF', 'zendFramework');
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.bundles"></a>64.18.8. Paquetes</h3></div></div></div>
<div class="example">
<a name="zend.service.delicious.bundles.example"></a><p class="title"><b>Ejemplo 64.89. Paquetes</b></p>
<div class="example-contents"><pre class="programlisting">
$delicious = new Zend_Service_Delicious('username', 'password');

// get all bundles
print_r($delicious-&gt;getBundles());

// delete bundle someBundle
$delicious-&gt;deleteBundle('someBundle');

// add bundle
$delicious-&gt;addBundle('newBundle', array('tag1', 'tag2'));
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.public_data"></a>64.18.9. Datos públicos</h3></div></div></div>
<p>
            La <acronym class="acronym">API</acronym> web de del.icio.us permite acceder a los datos públicos de todos los
            usuarios.
        </p>
<div class="table">
<a name="zend.service.delicious.public_data.functions_for_retrieving_public_data"></a><p class="title"><b>Tabla 64.14. Métodos para obtener datos públicos</b></p>
<div class="table-contents"><table class="table" summary="Methods for retrieving public data" border="1">
<colgroup>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Nombre</th>
<th>Descripción</th>
<th>Tipo de retorno</th>
</tr></thead>
<tbody>
<tr>
<td><code class="methodname">getUserFans()</code></td>
<td>Obtiene los seguidores de un usuario</td>
<td>Array</td>
</tr>
<tr>
<td><code class="methodname">getUserNetwork()</code></td>
<td>Obtiene la red de un usuario</td>
<td>Array</td>
</tr>
<tr>
<td><code class="methodname">getUserPosts()</code></td>
<td>Obtiene las entradas de un usuario</td>
<td>Zend_Service_Delicious_PostList</td>
</tr>
<tr>
<td><code class="methodname">getUserTags()</code></td>
<td>Obtiene las etiquetas de un usuario</td>
<td>Array</td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando solo se utilizan estos métodos, no se requiere una combinación de nombre de usuario y contraseña
                al construir un nuevo objeto <code class="classname">Zend_Service_Delicious</code>.
            </p></td></tr>
</table></div>
<div class="example">
<a name="zend.service.delicious.public_data.retrieving_public_data"></a><p class="title"><b>Ejemplo 64.90. Obtener datos públicos</b></p>
<div class="example-contents"><pre class="programlisting">
// username and password are not required
$delicious = new Zend_Service_Delicious();

// get fans of user someUser
print_r($delicious-&gt;getUserFans('someUser'));

// get network of user someUser
print_r($delicious-&gt;getUserNetwork('someUser'));

// get tags of user someUser
print_r($delicious-&gt;getUserTags('someUser'));
</pre></div>
</div>
<br class="example-break"><div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.delicious.public_data.posts"></a>64.18.9.1. Entradas públicas</h4></div></div></div>
<p>
                Al obtener entradas públicas con el método <code class="methodname">getUserPosts()</code>,
                se devuelve un objeto <code class="classname">Zend_Service_Delicious_PostList</code>,
                que contiene objetos <code class="classname">Zend_Service_Delicious_SimplePost</code>,
                los cuales contienen información básica sobre las entradas, incluyendo <acronym class="acronym">URL</acronym>,
                título, notas y etiquetas.
            </p>
<div class="table">
<a name="zend.service.delicious.public_data.posts.SimplePost_methods"></a><p class="title"><b>Tabla 64.15. Métodos de la clase Zend_Service_Delicious_SimplePost</b></p>
<div class="table-contents"><table class="table" summary="Methods of the Zend_Service_Delicious_SimplePost class" border="1">
<colgroup>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Nombre</th>
<th>Descripción</th>
<th>Tipo de retorno</th>
</tr></thead>
<tbody>
<tr>
<td><code class="methodname">getNotes()</code></td>
<td>Devuelve las notas de una entrada</td>
<td>String</td>
</tr>
<tr>
<td><code class="methodname">getTags()</code></td>
<td>Devuelve las etiquetas de una entrada</td>
<td>Array</td>
</tr>
<tr>
<td><code class="methodname">getTitle()</code></td>
<td>Devuelve el título de una entrada</td>
<td>String</td>
</tr>
<tr>
<td><code class="methodname">getUrl()</code></td>
<td>Devuelve la <acronym class="acronym">URL</acronym> de una entrada</td>
<td>String</td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break">
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.delicious.httpclient"></a>64.18.10. Cliente HTTP</h3></div></div></div>
<p>
            <code class="classname">Zend_Service_Delicious</code> utiliza
            <code class="classname">Zend_Rest_Client</code> para realizar solicitudes <acronym class="acronym">HTTP</acronym> al
            servicio web de del.icio.us. Para cambiar qué cliente <acronym class="acronym">HTTP</acronym> utiliza
            <code class="classname">Zend_Service_Delicious</code>, necesita cambiar el cliente
            <acronym class="acronym">HTTP</acronym> de <code class="classname">Zend_Rest_Client</code>.
        </p>
<div class="example">
<a name="zend.service.delicious.httpclient.changing"></a><p class="title"><b>Ejemplo 64.91. Cambiar el cliente HTTP de Zend_Rest_Client</b></p>
<div class="example-contents"><pre class="programlisting">
$myHttpClient = new My_Http_Client();
Zend_Rest_Client::setHttpClient($myHttpClient);
</pre></div>
</div>
<br class="example-break"><p>
            Cuando realiza más de una solicitud con
            <code class="classname">Zend_Service_Delicious</code> para acelerar sus solicitudes, es mejor
            configurar su cliente <acronym class="acronym">HTTP</acronym> para mantener las conexiones activas.
        </p>
<div class="example">
<a name="zend.service.delicious.httpclient.keepalive"></a><p class="title"><b>Ejemplo 64.92. Configurar el cliente HTTP para mantener las conexiones activas</b></p>
<div class="example-contents"><pre class="programlisting">
Zend_Rest_Client::getHttpClient()-&gt;setConfig(array(
        'keepalive' =&gt; true
));
</pre></div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando se construye un objeto <code class="classname">Zend_Service_Delicious</code>, el
                transporte <acronym class="acronym">SSL</acronym> de <code class="classname">Zend_Rest_Client</code> se establece
                en <code class="code">'ssl'</code> en lugar del valor predeterminado <code class="code">'ssl2'</code>. Esto se debe
                a que del.icio.us tiene algunos problemas con <code class="code">'ssl2'</code>, como que las solicitudes
                tarden mucho tiempo en completarse (alrededor de 2 segundos).
            </p></td></tr>
</table></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.audioscrobbler.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.ebay.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.17. Zend_Service_Audioscrobbler </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 64.19. Zend_Service_Ebay</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
