<?php $title = '58.2. Ejemplos de Zend_Reflection'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">58.2. Ejemplos de Zend_Reflection</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.reflection.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 58. Zend_Reflection</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.reflection.reference.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.reflection.examples"></a>58.2. Ejemplos de Zend_Reflection</h2></div></div></div>
<div class="example">
<a name="zend.reflection.examples.file"></a><p class="title"><b>Ejemplo 58.1. Realizar reflection sobre un archivo</b></p>
<div class="example-contents"><pre class="programlisting">
$r = new Zend_Reflection_File($filename);
printf(
    "===&gt; The %s file\n".
    "     has %d lines\n",
    $r-&gt;getFileName(),
    $r-&gt;getEndLine()
);

$classes = $r-&gt;getClasses();
echo "     It has " . count($classes) . ":\n";
foreach ($classes as $class) {
    echo "         " . $class-&gt;getName() . "\n";
}

$functions = $r-&gt;getFunctions();
echo "     It has " . count($functions) . ":\n";
foreach ($functions as $function) {
    echo "         " . $function-&gt;getName() . "\n";
}
</pre></div>
</div>
<br class="example-break"><div class="example">
<a name="zend.reflection.examples.class"></a><p class="title"><b>Ejemplo 58.2. Realizar reflection sobre una clase</b></p>
<div class="example-contents"><pre class="programlisting">
$r = new Zend_Reflection_Class($class);

printf(
    "The class level docblock has the short description: %s\n".
    "The class level docblock has the long description:\n%s\n",
    $r-&gt;getDocblock()-&gt;getShortDescription(),
    $r-&gt;getDocblock()-&gt;getLongDescription(),
);

// Get the declaring file reflection
$file = $r-&gt;getDeclaringFile();
</pre></div>
</div>
<br class="example-break"><div class="example">
<a name="zend.reflection.examples.method"></a><p class="title"><b>Ejemplo 58.3. Realizar reflection sobre un método</b></p>
<div class="example-contents"><pre class="programlisting">
$r = new Zend_Reflection_Method($class, $name);

printf( "Method '%s':\n", $r-&gt;getName());

foreach ($r-&gt;getParameters() as $key =&gt; $param) {
    printf(
        "Param at position '%d' is of type '%s'\n",
        $key,
        $param-&gt;getType()
    );
}
</pre></div>
</div>
<br class="example-break"><div class="example">
<a name="zend.reflection.examples.docblock"></a><p class="title"><b>Ejemplo 58.4. Realizar reflection sobre un docblock</b></p>
<div class="example-contents"><pre class="programlisting">
$r = new Zend_Reflection_Method($class, $name);
$docblock = $r-&gt;getDocblock();

printf(
    "The short description: %s\n".
    "The long description:\n%s\n",
    $r-&gt;getDocblock()-&gt;getShortDescription(),
    $r-&gt;getDocblock()-&gt;getLongDescription(),
);

foreach ($docblock-&gt;getTags() as $tag) {
    printf(
        "Annotation tag '%s' has the description '%s'\n",
        $tag-&gt;getName(),
        $tag-&gt;getDescription()
    );
}
</pre></div>
</div>
<br class="example-break">
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.reflection.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.reflection.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.reflection.reference.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 58. Zend_Reflection </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 58.3. Referencia de Zend_Reflection</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
