<?php $title = '14.4. Ejemplos'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">14.4. Ejemplos</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.application.theory-of-operation.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 14. Zend_Application</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.application.core-functionality.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.application.examples"></a>14.4. Ejemplos</h2></div></div></div>
<p>
        La clase Bootstrap en sí misma será típicamente bastante mínima; a menudo,
        será simplemente un stub vacío que extiende la clase base de bootstrap:
    </p>
<pre class="programlisting">
class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
}
</pre>
<p>
        Con un archivo de configuración correspondiente:
    </p>
<pre class="programlisting">
; APPLICATION_PATH/configs/application.ini
[production]
autoloaderNamespaces[] = "My_"
bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"
pluginpaths.My_Bootstrap_Resource = "My/Bootstrap/Resource"
resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"

[testing : production]
[development : production]
</pre>
<div class="note"><table border="0" summary="Note: Autoloader namespaces">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Espacios de nombres del autoloader</th>
</tr>
<tr><td align="left" valign="top">
<p>
            Debido a que estos ejemplos usan código personalizado, necesitamos registrar los prefijos de espacio de nombres para
            ese código en nuestra configuración; esto se hace con la
            clave de configuración <span class="property">autoloaderNamespaces</span>, que es un array.
        </p>
<p>
            Además, para asegurar que los recursos de plugin personalizados se descubran, necesitamos registrar
            una ruta de prefijo de plugin en el bootstrap. Esto se hace con la
            clave de configuración <span class="property">pluginpaths</span>, que es un array asociativo, con
            claves que denotan el prefijo a usar, y valores que denotan la ruta relacionada con ese prefijo.
        </p>
</td></tr>
</table></div>
<p>
        Sin embargo, si fuera necesaria una inicialización personalizada, tiene dos
        opciones. Primero, puede escribir métodos con el prefijo <span class="emphasis"><em>_init</em></span>
        para especificar código discreto a arrancar. Estos métodos serán llamados por
        <code class="methodname">bootstrap()</code>, y también se pueden llamar como si fueran métodos públicos:
        <span class="emphasis"><em>bootstrap&lt;resource&gt;()</em></span>. Deben aceptar un
        array opcional de opciones.
    </p>
<p>
        Si su método de recurso devuelve un valor, se almacenará en un
        contenedor en el bootstrap. Esto puede ser útil cuando diferentes recursos
        necesitan interactuar (como cuando un recurso se inyecta a sí mismo en otro).
        El método <code class="methodname">getResource()</code> se puede usar entonces para recuperar esos
        valores.
    </p>
<p>
        El ejemplo a continuación muestra un método de recurso para inicializar el objeto
        request. Hace uso del seguimiento de dependencias (depende del recurso del
        front controller), obteniendo un recurso del bootstrap, y
        devolviendo un valor para almacenar en el bootstrap.
    </p>
<pre class="programlisting">
class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
    protected function _initRequest()
    {
        // Ensure front controller instance is present, and fetch it
        $this-&gt;bootstrap('FrontController');
        $front = $this-&gt;getResource('FrontController');

        // Initialize the request object
        $request = new Zend_Controller_Request_Http();
        $request-&gt;setBaseUrl('/foo');

        // Add it to the front controller
        $front-&gt;setRequest($request);

        // Bootstrap will store this value in the 'request' key of its container
        return $request;
    }
}
</pre>
<p>
        Observe en este ejemplo la llamada a <code class="methodname">bootstrap()</code>;
        esto asegura que el front controller se haya inicializado antes de
        llamar a este método. Esa llamada puede activar un recurso u otro
        método en la clase.
    </p>
<p>
        La otra opción es usar plugins de recursos. Los plugins de recursos son
        objetos que realizan inicializaciones específicas, y pueden especificarse:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                Al instanciar el objeto <code class="classname">Zend_Application</code>
            </p></li>
<li class="listitem"><p>
                Durante la inicialización del objeto bootstrap
            </p></li>
<li class="listitem"><p>
                Habilitándolos explícitamente mediante llamadas a métodos del objeto
                bootstrap
            </p></li>
</ul></div>
<p>
        Los plugins de recursos implementan
        <code class="classname">Zend_Application_Resource_ResourceAbstract</code>,
        que simplemente define que permiten la inyección del invocador y
        opciones, y que tienen un método <code class="methodname">init()</code>. Como
        ejemplo, un recurso de bootstrap "View" personalizado podría verse como el
        siguiente:
    </p>
<pre class="programlisting">
class My_Bootstrap_Resource_View
    extends Zend_Application_Resource_ResourceAbstract
{
    public function init()
    {
        $view = new Zend_View($this-&gt;getOptions());
        Zend_Dojo::enableView($view);

        $view-&gt;doctype('XHTML1_STRICT');
        $view-&gt;headTitle()-&gt;setSeparator(' - ')-&gt;append('My Site');
        $view-&gt;headMeta()-&gt;appendHttpEquiv('Content-Type',
                                           'text/html; charset=utf-8');

        $view-&gt;dojo()-&gt;setDjConfigOption('parseOnLoad', true)
                     -&gt;setLocalPath('/js/dojo/dojo.js')
                     -&gt;registerModulePath('../spindle', 'spindle')
                     -&gt;addStylesheetModule('spindle.themes.spindle')
                     -&gt;requireModule('spindle.main')
                     -&gt;disable();

        $viewRenderer = Zend_Controller_Action_HelperBroker::getStaticHelper(
            'ViewRenderer'
        );
        $viewRenderer-&gt;setView($view);

        return $view;
    }
}
</pre>
<p>
        Para indicarle al bootstrap que use esto, necesitaría proporcionar ya sea el
        nombre de clase del plugin de recurso, o una combinación de una ruta de prefijo del cargador de plugins
        y el nombre corto del plugin de recurso (por ejemplo, "view"):
    </p>
<pre class="programlisting">
$application = new Zend_Application(
    APPLICATION_ENV,
    array(
        'resources' =&gt; array(
            'My_Bootstrap_Resource_View' =&gt; array(), // full class name; OR
            'view' =&gt; array(),                       // short name

            'FrontController' =&gt; array(
                'controllerDirectory' =&gt; APPLICATION_PATH . '/controllers',
            ),
        ),

        // For short names, define plugin paths:
        'pluginPaths = array(
            'My_Bootstrap_Resource' =&gt; 'My/Bootstrap/Resource',
        )
    )
);
</pre>
<p>
        Los plugins de recursos pueden invocar otros recursos e inicializadores accediendo al
        bootstrap padre:
    </p>
<pre class="programlisting">
class My_Bootstrap_Resource_Layout
    extends Zend_Application_Resource_ResourceAbstract
{
    public function init()
    {
        // ensure view is initialized...
        $this-&gt;getBootstrap()-&gt;bootstrap('view');

        // Get view object:
        $view = $this-&gt;getBootstrap()-&gt;getResource('view');

        // ...
    }
}
</pre>
<p>
        En el uso normal, instanciaría la aplicación, la arrancaría,
        y la ejecutaría:
    </p>
<pre class="programlisting">
$application = new Zend_Application(...);
$application-&gt;bootstrap()
            -&gt;run();
</pre>
<p>
        Para un script personalizado, podría necesitar simplemente inicializar recursos
        específicos:
    </p>
<pre class="programlisting">
$application = new Zend_Application(...);
$application-&gt;getBootstrap()-&gt;bootstrap('db');

$service = new Zend_XmlRpc_Server();
$service-&gt;setClass('Foo');  // uses database...
echo $service-&gt;handle();
</pre>
<p>
        En lugar de usar el método <code class="methodname">bootstrap()</code> para llamar a los
        métodos internos o recursos, también puede usar sobrecarga:
    </p>
<pre class="programlisting">
$application = new Zend_Application(...);
$application-&gt;getBootstrap()-&gt;bootstrapDb();
</pre>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.application.theory-of-operation.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.application.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.application.core-functionality.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">14.3. Teoría de funcionamiento </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 14.5. Funcionalidad principal</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
