<?php $title = 'Capítulo 33. Zend_Feed'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 33. Zend_Feed</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.exception.previous.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.feed.importing.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.feed"></a>Capítulo 33. Zend_Feed</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.feed.phtml#zend.feed.introduction">33.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.feed.importing.phtml">33.2. Importando Feeds</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.feed.importing.phtml#zend.feed.importing.custom">33.2.1. Feeds personalizados</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.feed.importing.phtml#zend.feed.importing.custom.importarray">33.2.1.1. Importando un array personalizado</a></span></dt>
<dt><span class="sect3"><a href="zend.feed.importing.phtml#zend.feed.importing.custom.importbuilder">33.2.1.2. Importando una fuente de datos personalizada</a></span></dt>
<dt><span class="sect3"><a href="zend.feed.importing.phtml#zend.feed.importing.custom.dump">33.2.1.3. Volcando el contenido de un feed</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.feed.findFeeds.phtml">33.3. Obteniendo Feeds desde páginas web</a></span></dt>
<dt><span class="sect1"><a href="zend.feed.consuming-rss.phtml">33.4. Consumiendo un Feed RSS</a></span></dt>
<dt><span class="sect1"><a href="zend.feed.consuming-atom.phtml">33.5. Consumiendo un Feed Atom</a></span></dt>
<dt><span class="sect1"><a href="zend.feed.consuming-atom-single-entry.phtml">33.6. Consumiendo una única entrada Atom</a></span></dt>
<dt><span class="sect1"><a href="zend.feed.modifying-feed.phtml">33.7. Modificando estructuras de Feed y Entry</a></span></dt>
<dt><span class="sect1"><a href="zend.feed.custom-feed.phtml">33.8. Clases personalizadas de Feed y Entry</a></span></dt>
<dt><span class="sect1"><a href="zend.feed.reader.phtml">33.9. Zend_Feed_Reader</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.introduction">33.9.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.import">33.9.2. Importando Feeds</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.sources">33.9.3. Obteniendo las fuentes subyacentes de Feed y Entry</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.cache-request">33.9.4. Soporte de caché y peticiones inteligentes</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.feed.reader.phtml#zend.feed.reader.cache-request.cache">33.9.4.1. Añadiendo soporte de caché a Zend_Feed_Reader</a></span></dt>
<dt><span class="sect3"><a href="zend.feed.reader.phtml#zend.feed.reader.cache-request.http-conditional-get">33.9.4.2. Soporte de HTTP Conditional GET</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.locate">33.9.5. Localizando URIs de feeds desde sitios web</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.attribute-collections">33.9.6. Colecciones de atributos</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.retrieve-info">33.9.7. Obteniendo información del feed</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.entry">33.9.8. Obteniendo información de Entry/Item</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.reader.phtml#zend.feed.reader.extending">33.9.9. Extendiendo las APIs de Feed y Entry</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.feed.reader.phtml#zend.feed.reader.extending.feed">33.9.9.1. Escribiendo extensiones de Zend_Feed_Reader</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.feed.writer.phtml">33.10. Zend_Feed_Writer</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.feed.writer.phtml#zend.feed.writer.introduction">33.10.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.writer.phtml#zend.feed.writer.architecture">33.10.2. Arquitectura</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.writer.phtml#zend.feed.writer.getting.started">33.10.3. Primeros pasos</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.writer.phtml#zend.feed.writer.setting.feed.data.points">33.10.4. Estableciendo puntos de datos del Feed</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.writer.phtml#zend.feed.writer.setting.entry.data.points">33.10.5. Estableciendo puntos de datos de la Entry</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.feed.pubsubhubbub.introduction.phtml">33.11. Zend_Feed_Pubsubhubbub</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.feed.pubsubhubbub.introduction.phtml#zend.feed.pubsubhubbub.what.is.pubsubhubbub">33.11.1. ¿Qué es Pubsubhubbub?</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.pubsubhubbub.introduction.phtml#zend.feed.pubsubhubbub.architecture">33.11.2. Arquitectura</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.pubsubhubbub.introduction.phtml#zend.feed.pubsubhubbub.zend.feed.pubsubhubbub.publisher">33.11.3. Zend_Feed_Pubsubhubbub_Publisher</a></span></dt>
<dt><span class="sect2"><a href="zend.feed.pubsubhubbub.introduction.phtml#zend.feed.pubsubhubbub.zend.feed.pubsubhubbub.subscriber">33.11.4. Zend_Feed_Pubsubhubbub_Subscriber</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.feed.pubsubhubbub.introduction.phtml#zend.feed.pubsubhubbub.zend.feed.pubsubhubbub.subscriber.subscribing.and.unsubscribing">33.11.4.1. Suscribirse y darse de baja</a></span></dt>
<dt><span class="sect3"><a href="zend.feed.pubsubhubbub.introduction.phtml#zend.feed.pubsubhubbub.zend.feed.pubsubhubbub.subscriber.handling.hub.callbacks">33.11.4.2. Manejo de callbacks del suscriptor</a></span></dt>
<dt><span class="sect3"><a href="zend.feed.pubsubhubbub.introduction.phtml#zend.feed.pubsubhubbub.zend.feed.pubsubhubbub.subscriber.setting.up.and.using.a.callback.url.route">33.11.4.3. Configurando y usando una ruta de URL de callback</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.feed.introduction"></a>33.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Feed</code> proporciona funcionalidad para consumir feeds <acronym class="acronym">RSS</acronym>
        y Atom. Proporciona una sintaxis natural para acceder a los elementos de los feeds, atributos
        de feed, y atributos de entry. <code class="classname">Zend_Feed</code> también cuenta con un amplio
        soporte para modificar la estructura de feed y entry con la misma sintaxis natural, y convertir el
        resultado de nuevo a <acronym class="acronym">XML</acronym>. En el futuro, este soporte de modificación podría
        ofrecer soporte para el Atom Publishing Protocol.
    </p>
<p>
        Desde el punto de vista de la programación, <code class="classname">Zend_Feed</code> consiste en una clase base
        <code class="classname">Zend_Feed</code>, las clases base abstractas <code class="classname">Zend_Feed_Abstract</code>
        y <code class="classname">Zend_Feed_Entry_Abstract</code> para representar Feeds y
        Entries, implementaciones específicas de feeds y entries para <acronym class="acronym">RSS</acronym> y Atom,
        y un ayudante interno que hace posible la magia de la sintaxis natural.
    </p>
<p>
        En el ejemplo de abajo, mostramos un caso de uso sencillo para obtener un
        feed <acronym class="acronym">RSS</acronym> y guardar las partes relevantes de los datos del feed en un simple
        array de <acronym class="acronym">PHP</acronym>, que después podría usarse para imprimir los datos, almacenarlos en una
        base de datos, etc.
    </p>
<div class="note"><table border="0" summary="Note: Be aware">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Tenga en cuenta</th>
</tr>
<tr><td align="left" valign="top"><p>
            Muchos feeds <acronym class="acronym">RSS</acronym> tienen diferentes propiedades de canal e item disponibles.
            La especificación <acronym class="acronym">RSS</acronym> permite muchas propiedades opcionales, así que tenga
            esto en cuenta al escribir código que trabaje con datos <acronym class="acronym">RSS</acronym>.
        </p></td></tr>
</table></div>
<div class="example">
<a name="zend.feed.introduction.example.rss"></a><p class="title"><b>Ejemplo 33.1. Poniendo Zend_Feed a trabajar con datos de un feed RSS</b></p>
<div class="example-contents"><pre class="programlisting">
// Fetch the latest Slashdot headlines
try {
    $slashdotRss =
        Zend_Feed::import('http://rss.slashdot.org/Slashdot/slashdot');
} catch (Zend_Feed_Exception $e) {
    // feed import failed
    echo "Exception caught importing feed: {$e-&gt;getMessage()}\n";
    exit;
}

// Initialize the channel data array
$channel = array(
    'title'       =&gt; $slashdotRss-&gt;title(),
    'link'        =&gt; $slashdotRss-&gt;link(),
    'description' =&gt; $slashdotRss-&gt;description(),
    'items'       =&gt; array()
    );

// Loop over each channel item and store relevant data
foreach ($slashdotRss as $item) {
    $channel['items'][] = array(
        'title'       =&gt; $item-&gt;title(),
        'link'        =&gt; $item-&gt;link(),
        'description' =&gt; $item-&gt;description()
        );
}
</pre></div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.exception.previous.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.feed.importing.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">32.3. Excepciones previas </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 33.2. Importando Feeds</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
