<?php $title = 'registerAutoloadMap'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">registerAutoloadMap</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.set-options.phtml">Anterior</a> </td>
<th width="60%" align="center">42.8.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.class-map-autoloader.methods.register-autoload-maps.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.class-map-autoloader.methods.register-autoload-map"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>registerAutoloadMap — Registra un mapa de clases</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">registerAutoloadMap</span>(<span class="methodparam">$map</span>);</code>
</div>
<div class="refsection">
<a name="id37241"></a><h2>registerAutoloadMap()</h2>
<p>
                    Registra un mapa de clases con el autoloader. <code class="varname">$map</code> puede ser
                    una cadena que hace referencia a un script PHP que devuelve un mapa de clases, o un array que define
                    un mapa de clases.
                </p>
<p>
                    Se puede registrar más de un mapa de clases; cada uno se fusionará con el
                    anterior, lo que significa que es posible que un mapa de clases registrado más tarde sobrescriba entradas de
                    un mapa registrado previamente.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.set-options.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.class-map-autoloader.phtml#zend.loader.class-map-autoloader.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.class-map-autoloader.methods.register-autoload-maps.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">setOptions </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> registerAutoloadMaps</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
