<?php $title = 'Capítulo 60. Zend_Rest'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 60. Zend_Rest</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.registry.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.rest.client.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.rest"></a>Capítulo 60. Zend_Rest</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.rest.phtml#zend.rest.introduction">60.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.rest.client.phtml">60.2. Zend_Rest_Client</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.rest.client.phtml#zend.rest.client.introduction">60.2.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.rest.client.phtml#zend.rest.client.return">60.2.2. Respuestas</a></span></dt>
<dt><span class="sect2"><a href="zend.rest.client.phtml#zend.rest.client.args">60.2.3. Argumentos de solicitud</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.rest.server.phtml">60.3. Zend_Rest_Server</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.rest.server.phtml#zend.rest.server.introduction">60.3.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.rest.server.phtml#zend.rest.server.usage">60.3.2. Uso del servidor REST</a></span></dt>
<dt><span class="sect2"><a href="zend.rest.server.phtml#zend.rest.server.args">60.3.3. Invocar un servicio de Zend_Rest_Server</a></span></dt>
<dt><span class="sect2"><a href="zend.rest.server.phtml#zend.rest.server.customstatus">60.3.4. Enviar un estado personalizado</a></span></dt>
<dt><span class="sect2"><a href="zend.rest.server.phtml#zend.rest.server.customxml">60.3.5. Devolver respuestas XML personalizadas</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.rest.introduction"></a>60.1. Introducción</h2></div></div></div>
<p>
        Los servicios web REST usan formatos <acronym class="acronym">XML</acronym> específicos de cada servicio. Estos estándares
        ad-hoc significan que la forma de acceder a un servicio web REST es
        diferente para cada servicio. Los servicios web REST normalmente usan
        parámetros de <acronym class="acronym">URL</acronym> (datos <code class="constant">GET</code>) o información de ruta para solicitar datos y datos POST
        para enviar datos.
    </p>
<p>
        Zend Framework proporciona capacidades tanto de cliente como de servidor, que,
        cuando se usan juntas, permiten una experiencia de interfaz mucho más "local"
        mediante el acceso a propiedades de objetos virtuales. El componente Server ofrece
        exposición automática de funciones y clases usando un formato
        <acronym class="acronym">XML</acronym> simple y significativo. Al acceder a estos servicios usando el Client, es
        posible recuperar fácilmente los datos de retorno de la llamada remota. Si desea
        usar el cliente con un servicio no basado en Zend_Rest_Server, este
        seguirá proporcionando un acceso más fácil a los datos.
    </p>
<p>
        Además de los componentes <code class="classname">Zend_Rest_Server</code> y
        <code class="classname">Zend_Rest_Client</code>, se proporcionan las clases <a class="link" href="zend.controller.router.phtml#zend.controller.router.routes.rest" title="24.5.7.6. Zend_Rest_Route"><code class="classname">Zend_Rest_Route</code> y
            <code class="classname">Zend_Rest_Controller</code></a> para ayudar a enrutar
        las solicitudes REST hacia los controladores.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.registry.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.rest.client.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 59. Zend_Registry </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 60.2. Zend_Rest_Client</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
