<?php $title = 'Capítulo 72. Zend_Tool_Framework'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 72. Zend_Tool_Framework</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.tool.extending.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.tool.framework.clitool.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.tool.framework"></a>Capítulo 72. Zend_Tool_Framework</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.tool.framework.phtml#zend.tool.framework.introduction">72.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.tool.framework.clitool.phtml">72.2. Uso de la herramienta CLI</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.setup-general">72.2.1. Configuración de la herramienta CLI</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.setup-starnix">72.2.2. Configuración de la herramienta CLI en sistemas tipo Unix</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.setup-windows">72.2.3. Configuración de la herramienta CLI en Windows</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.setup-othernotes">72.2.4. Otras consideraciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.clitool.phtml#zend.tool.framework.clitool.continuing">72.2.5. ¿A dónde ir ahora?</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.framework.architecture.phtml">72.3. Arquitectura</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.registry">72.3.1. Registro</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.providers">72.3.2. Proveedores</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.loaders">72.3.3. Cargadores</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.manifests">72.3.4. Manifiestos</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.architecture.phtml#zend.tool.framework.architecture.clients">72.3.5. Clientes</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.framework.writing-providers.phtml">72.4. Creación de proveedores para usar con Zend_Tool_Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.loading">72.4.1. Cómo encuentra Zend_Tool sus proveedores</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.basic">72.4.2. Instrucciones básicas para crear proveedores</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.response">72.4.3. El objeto de respuesta</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced">72.4.4. Información avanzada de desarrollo</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.variables">72.4.4.1. Pasar variables a un proveedor</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.prompt">72.4.4.2. Solicitar información al usuario</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.pretendable">72.4.4.3. Simular la ejecución de una acción de proveedor</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.verbosedebug">72.4.4.4. Modos detallado y depuración</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.writing-providers.phtml#zend.tool.framework.writing-providers.advanced.configstorage">72.4.4.5. Acceso a la configuración y almacenamiento del usuario</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.framework.system-providers.phtml">72.5. Proveedores del sistema incluidos</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.system-providers.phtml#zend.tool.framework.system-providers.version">72.5.1. El proveedor Version</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.framework.system-providers.phtml#zend.tool.framework.system-providers.manifest">72.5.2. El proveedor Manifest</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.framework.extending.phtml">72.6. Extender y configurar Zend_Tool_Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client">72.6.1. Personalizar el cliente de consola de Zend_Tool</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client.home-directory">72.6.1.1. El directorio de inicio</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client.local-storage">72.6.1.2. Almacenamiento local</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client.configuration-file">72.6.1.3. Configuración de usuario</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.framework.extending.phtml#zend.tool.framework.console-client.configuration-content">72.6.1.4. Contenido del archivo de configuración de usuario</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.tool.framework.introduction"></a>72.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Tool_Framework</code> es un framework para exponer funcionalidades
        comunes tales como la creación de esqueletos de proyecto, generación de
        código, generación de índices de búsqueda, y mucho más. La funcionalidad puede
        escribirse y exponerse mediante clases <acronym class="acronym">PHP</acronym> colocadas en la
        <span class="property">include_path</span> de <acronym class="acronym">PHP</acronym>, lo que proporciona una increíble
        flexibilidad de implementación. Esta funcionalidad puede consumirse después escribiendo
        clientes de implementación y/o específicos de protocolo -- tales como clientes de
        consola, <acronym class="acronym">XML-RPC</acronym>, <acronym class="acronym">SOAP</acronym>, y mucho más.
    </p>
<p>
        <code class="classname">Zend_Tool_Framework</code> proporciona lo siguiente:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <span class="emphasis"><em>Interfaces y abstracciones comunes</em></span> que permiten
                a los desarrolladores crear funcionalidad y capacidades que son
                despachables por clientes de herramientas.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Funcionalidad base de cliente</em></span> y una implementación
                concreta de consola que conectan herramientas e
                interfaces externas con <code class="classname">Zend_Tool_Framework</code>. El cliente
                de consola puede usarse en entornos <acronym class="acronym">CLI</acronym> tales como shells unix y
                la consola de Windows.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Interfaces "Provider" y "Manifest"</em></span> que
                puede utilizar el sistema de herramientas. Los "Providers" representan el
                aspecto funcional del framework, y definen las acciones que
                los clientes de herramientas pueden invocar. Los "Manifests" actúan como registros
                de metadatos que proporcionan contexto adicional para los distintos
                proveedores definidos.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Un sistema de carga introspectivo</em></span> que
                examinará el entorno en busca de proveedores y determinará lo que
                se necesita para despacharlos.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Un conjunto estándar de proveedores del sistema</em></span> que
                permiten al sistema informar de cuáles son sus capacidades completas
                así como proporcionar información útil. Esto también
                incluye un "Sistema de ayuda" completo.
            </p></li>
</ul></div>
<p>
        Las definiciones que debe conocer a lo largo de este manual con respecto
        a <code class="classname">Zend_Tool_Framework</code> incluyen:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <code class="classname">Zend_Tool_Framework</code> - El framework que expone las
                capacidades de herramientas.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Tooling Client</em></span> - Una herramienta de desarrollo que se conecta
                a <code class="classname">Zend_Tool_Framework</code> y la consume.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Client</em></span> - El subsistema de
                <code class="classname">Zend_Tool_Framework</code> que expone una interfaz de modo que
                los clientes de herramientas puedan conectarse, consultar y ejecutar comandos.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Console Client / Command Line Interface /
                <code class="filename">zf.php</code></em></span> - El cliente de herramientas para la línea de comandos.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Provider</em></span> - Un subsistema y una colección de
                funcionalidad incorporada que exporta el framework.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>Manifest</em></span> - Un subsistema para definir,
                organizar y difundir los datos de requisitos de los proveedores.
            </p></li>
<li class="listitem"><p>
                Proveedor <code class="classname">Zend_Tool_Project</code> - Un conjunto de proveedores
                específicamente para crear y mantener proyectos basados en Zend Framework.
            </p></li>
</ul></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.tool.extending.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.tool.framework.clitool.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">71.2. Extender Zend_Tool </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 72.2. Uso de la herramienta CLI</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
