<?php $title = 'Capítulo 35. Zend_Filter'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 35. Zend_Filter</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.file.transfer.filters.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.filter.set.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.filter"></a>Capítulo 35. Zend_Filter</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.filter.phtml#zend.filter.introduction">35.1. Introducción</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.filter.phtml#zend.filter.introduction.definition">35.1.1. ¿Qué es un filtro?</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.phtml#zend.filter.introduction.using">35.1.2. Uso básico de filtros</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.phtml#zend.filter.introduction.static">35.1.3. Uso del método estático staticFilter()</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.filter.phtml#zend.filter.introduction.static.namespaces">35.1.3.1. Espacios de nombres</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.filter.phtml#zend.filter.introduction.caveats">35.1.4. Doble filtrado</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.filter.set.phtml">35.2. Clases de filtro estándar</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.alnum">35.2.1. Alnum</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alnum.options">35.2.1.1. Opciones soportadas para Zend_Filter_Alnum</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alnum.basic">35.2.1.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alnum.whitespace">35.2.1.3. Permitir espacios en blanco</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.alpha">35.2.2. Alpha</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alpha.options">35.2.2.1. Opciones soportadas para Zend_Filter_Alpha</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alpha.basic">35.2.2.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.alpha.whitespace">35.2.2.3. Permitir caracteres de espacio en blanco</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.basename">35.2.3. BaseName</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.basename.options">35.2.3.1. Opciones soportadas para Zend_Filter_BaseName</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.basename.basic">35.2.3.2. Uso básico</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.boolean">35.2.4. Boolean</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.options">35.2.4.1. Opciones soportadas para Zend_Filter_Boolean</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.default">35.2.4.2. Comportamiento por defecto de Zend_Filter_Boolean</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.types">35.2.4.3. Cambiar el comportamiento de Zend_Filter_Boolean</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.localized">35.2.4.4. Booleanos localizados</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.boolean.casting">35.2.4.5. Deshabilitar el casting</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.callback">35.2.5. Callback</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.callback.options">35.2.5.1. Opciones soportadas para Zend_Filter_Callback</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.callback.basic">35.2.5.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.callback.parameters">35.2.5.3. Parámetros por defecto dentro de un callback</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.compress">35.2.6. Compress y Decompress</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.options">35.2.6.1. Opciones soportadas para Zend_Filter_Compress y Zend_Filter_Decompress</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.basic">35.2.6.2. Adaptadores de compresión soportados</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.generic">35.2.6.3. Manejo genérico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.archive">35.2.6.4. Crear un archivo comprimido</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.decompress">35.2.6.5. Descomprimir un archivo comprimido</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.bz2">35.2.6.6. Adaptador Bz2</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.gz">35.2.6.7. Adaptador Gz</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.lzf">35.2.6.8. Adaptador Lzf</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.rar">35.2.6.9. Adaptador Rar</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.tar">35.2.6.10. Adaptador Tar</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.compress.zip">35.2.6.11. Adaptador Zip</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.digits">35.2.7. Digits</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.digits.options">35.2.7.1. Opciones soportadas para Zend_Filter_Digits</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.digits.basic">35.2.7.2. Uso básico</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.dir">35.2.8. Dir</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.dir.options">35.2.8.1. Opciones soportadas para Zend_Filter_Dir</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.dir.basic">35.2.8.2. Uso básico</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.encrypt">35.2.9. Encrypt y Decrypt</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.options">35.2.9.1. Opciones soportadas para Zend_Filter_Encrypt y Zend_Filter_Decrypt</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.adapterusage">35.2.9.2. Uso del adaptador</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.mcrypt">35.2.9.3. Cifrado con Mcrypt</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.mcryptdecrypt">35.2.9.4. Descifrado con Mcrypt</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.openssl">35.2.9.5. Cifrado con OpenSSL</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.openssl.simplified">35.2.9.5.1. Uso simplificado con Openssl</a></span></dt>
<dt><span class="sect4"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.openssl.compressed">35.2.9.5.2. Comprimir el contenido</a></span></dt>
</dl></dd>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.encrypt.openssldecrypt">35.2.9.6. Descifrado con OpenSSL</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities">35.2.10. HtmlEntities</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities.options">35.2.10.1. Opciones soportadas para Zend_Filter_HtmlEntities</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities.basic">35.2.10.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities.quotestyle">35.2.10.3. Estilo de comillas</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.htmlentities.">35.2.10.4. Métodos auxiliares</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.int">35.2.11. Int</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.int.options">35.2.11.1. Opciones soportadas para Zend_Filter_Int</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.int.basic">35.2.11.2. Uso básico</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized">35.2.12. LocalizedToNormalized y NormalizedToLocalized</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.options">35.2.12.1.
            Opciones soportadas para Zend_Filter_LocalizedToNormalized y
            Zend_Filter_NormalizedToLocalized
        </a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.workflow">35.2.12.2. Flujo de trabajo</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.numbersnormal">35.2.12.3. Normalización de números</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.dates">35.2.12.4. Normalización de fecha y hora</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.localizedtonormalized.numberslocal">35.2.12.5. Localización de números</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.normalizedtolocalized.dates">35.2.12.6. Localización de fecha y hora</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.null">35.2.13. Null</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.null.options">35.2.13.1. Opciones soportadas para Zend_Filter_Null</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.null.default">35.2.13.2. Comportamiento por defecto de Zend_Filter_Null</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.null.types">35.2.13.3. Cambiar el comportamiento de Zend_Filter_Null</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.pregreplace">35.2.14. PregReplace</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.pregreplace.options">35.2.14.1. Opciones soportadas para Zend_Filter_PregReplace</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.pregreplace.basic">35.2.14.2. Uso básico</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.realpath">35.2.15. RealPath</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.realpath.options">35.2.15.1. Opciones soportadas para Zend_Filter_RealPath</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.realpath.basic">35.2.15.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.realpath.exists">35.2.15.3. Rutas inexistentes</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.stringtolower">35.2.16. StringToLower</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtolower.options">35.2.16.1. Opciones soportadas para Zend_Filter_StringToLower</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtolower.basic">35.2.16.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtolower.encoding">35.2.16.3. Cadenas con distintas codificaciones</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.stringtoupper">35.2.17. StringToUpper</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtoupper.options">35.2.17.1. Opciones soportadas para Zend_Filter_StringToUpper</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtoupper.basic">35.2.17.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtoupper.encoding">35.2.17.3. Cadenas con distintas codificaciones</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.stringtrim">35.2.18. StringTrim</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtrim.options">35.2.18.1. Opciones soportadas para Zend_Filter_StringTrim</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtrim.basic">35.2.18.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stringtrim.types">35.2.18.3. Comportamiento por defecto de Zend_Filter_StringTrim</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.stripnewlines">35.2.19. StripNewLines</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.strinpnewlines.options">35.2.19.1. Opciones soportadas para Zend_Filter_StripNewLines</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.stripnewlines.basic">35.2.19.2. Uso básico</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.set.phtml#zend.filter.set.striptags">35.2.20. StripTags</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.striptags.options">35.2.20.1. Opciones soportadas para Zend_Filter_StripTags</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.striptags.basic">35.2.20.2. Uso básico</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.striptags.allowtags">35.2.20.3. Permitir etiquetas definidas</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.set.phtml#zend.filter.set.striptags.allowattribs">35.2.20.4. Permitir atributos definidos</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.filter.filter_chains.phtml">35.3. Cadenas de filtros</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="zend.filter.filter_chains.phtml#zend.filter.filter_chains.order">35.3.1. Cambiar el orden de la cadena de filtros</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="zend.filter.writing_filters.phtml">35.4. Escribiendo filtros</a></span></dt>
<dt><span class="sect1"><a href="zend.filter.input.phtml">35.5. Zend_Filter_Input</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.declaring">35.5.1. Declarar reglas de filtros y validadores</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.running">35.5.2. Crear el procesador de filtros y validadores</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.results">35.5.3. Obtener campos validados y otros informes</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.results.isvalid">35.5.3.1. Consultar si la entrada es válida</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.results.reports">35.5.3.2. Obtener campos no válidos, faltantes o desconocidos</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.results.escaping">35.5.3.3. Obtener campos válidos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.metacommands">35.5.4. Uso de metacomandos para controlar las reglas de filtros o validadores</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.fields">35.5.4.1. El metacomando FIELDS</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.presence">35.5.4.2. El metacomando PRESENCE</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.default">35.5.4.3. El metacomando DEFAULT_VALUE</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.allow-empty">35.5.4.4. El metacomando ALLOW_EMPTY</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.break-chain">35.5.4.5. El metacomando BREAK_CHAIN</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.messages">35.5.4.6. El metacomando MESSAGES</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.input.phtml#zend.filter.input.metacommands.global">35.5.4.7. Uso de opciones para establecer metacomandos para todas las reglas</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.input.phtml#zend.filter.input.namespaces">35.5.5. Añadir espacios de nombres de clases de filtro</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.filter.inflector.phtml">35.6. Zend_Filter_Inflector</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.operation">35.6.1. Operación</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.paths">35.6.2. Establecer rutas a filtros alternativos</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.targets">35.6.3. Establecer el objetivo del inflector</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.rules">35.6.4. Reglas de inflexión</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.filter.inflector.phtml#zend.filter.inflector.rules.static">35.6.4.1. Reglas estáticas</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.inflector.phtml#zend.filter.inflector.rules.filters">35.6.4.2. Reglas de inflexión de filtros</a></span></dt>
<dt><span class="sect3"><a href="zend.filter.inflector.phtml#zend.filter.inflector.rules.multiple">35.6.4.3. Establecer muchas reglas a la vez</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.utility">35.6.5. Métodos de utilidad</a></span></dt>
<dt><span class="sect2"><a href="zend.filter.inflector.phtml#zend.filter.inflector.config">35.6.6. Usar Zend_Config con Zend_Filter_Inflector</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.filter.introduction"></a>35.1. Introducción</h2></div></div></div>
<p>
        El componente <code class="classname">Zend_Filter</code> proporciona un conjunto de filtros de datos
        comúnmente necesarios. También proporciona un mecanismo simple de encadenamiento de filtros
        mediante el cual se pueden aplicar múltiples filtros a un único dato
        en un orden definido por el usuario.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.introduction.definition"></a>35.1.1. ¿Qué es un filtro?</h3></div></div></div>
<p>
            En el mundo físico, un filtro se utiliza típicamente para eliminar
            porciones no deseadas de una entrada, y la porción deseada de la entrada
            pasa a través como salida del filtro (por ejemplo, café). En tales escenarios,
            un filtro es un operador que produce un subconjunto de la entrada. Este
            tipo de filtrado es útil para aplicaciones web - eliminar entradas
            no permitidas, recortar espacios en blanco innecesarios, etc.
        </p>
<p>
            Esta definición básica de un filtro puede extenderse para incluir
            transformaciones generalizadas sobre la entrada. Una transformación común
            aplicada en las aplicaciones web es el escapado de entidades <acronym class="acronym">HTML</acronym>. Por
            ejemplo, si un campo de formulario se rellena automáticamente con una entrada no confiable
            (por ejemplo, desde un navegador web), este valor debería estar libre
            de entidades <acronym class="acronym">HTML</acronym> o contener solo entidades <acronym class="acronym">HTML</acronym>
            escapadas, con el fin de prevenir un comportamiento no deseado y vulnerabilidades de seguridad. Para cumplir
            este requisito, las entidades <acronym class="acronym">HTML</acronym> que aparezcan en la entrada deben
            ser eliminadas o escapadas. Por supuesto, qué enfoque es más
            apropiado depende de la situación. Un filtro que elimina las
            entidades <acronym class="acronym">HTML</acronym> opera dentro del alcance de la primera definición de
            filtro - un operador que produce un subconjunto de la entrada. Un filtro
            que escapa las entidades <acronym class="acronym">HTML</acronym>, sin embargo, transforma la entrada
            (por ejemplo, "&amp;" se transforma en
            "&amp;amp;"). Soportar estos casos de uso para los
            desarrolladores web es importante, y "filtrar," en el contexto del uso de
            <code class="classname">Zend_Filter</code>, significa realizar algunas transformaciones sobre los datos
            de entrada.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.introduction.using"></a>35.1.2. Uso básico de filtros</h3></div></div></div>
<p>
            Habiendo establecido esta definición de filtro, se proporciona la base
            para <code class="classname">Zend_Filter_Interface</code>, que requiere que un
            único método llamado <code class="methodname">filter()</code> sea implementado por una clase
            de filtro.
        </p>
<p>
            A continuación se muestra un ejemplo básico del uso de un filtro sobre dos datos de entrada,
            los caracteres de ampersand (<span class="emphasis"><em>&amp;</em></span>) y comilla doble
            (<span class="emphasis"><em>"</em></span>):
        </p>
<pre class="programlisting">
$htmlEntities = new Zend_Filter_HtmlEntities();

echo $htmlEntities-&gt;filter('&amp;'); // &amp;amp;
echo $htmlEntities-&gt;filter('"'); // &amp;quot;
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.introduction.static"></a>35.1.3. Uso del método estático staticFilter()</h3></div></div></div>
<p>
            Si resulta inconveniente cargar una determinada clase de filtro y crear una
            instancia del filtro, puede utilizar el método estático
            <code class="methodname">Zend_Filter::filterStatic()</code> como estilo alternativo de invocación.
            El primer argumento de este método es un valor de dato de entrada, que
            pasaría al método <code class="methodname">filter()</code>. El segundo
            argumento es una cadena, que corresponde al nombre base de la
            clase de filtro, relativo al espacio de nombres <code class="classname">Zend_Filter</code>. El
            método <code class="methodname">staticFilter()</code> carga automáticamente la clase, crea
            una instancia, y aplica el método <code class="methodname">filter()</code> a los datos
            de entrada.
        </p>
<pre class="programlisting">
echo Zend_Filter::filterStatic('&amp;', 'HtmlEntities');
</pre>
<p>
            También puede pasar un array de argumentos del constructor, si son
            necesarios para la clase de filtro.
        </p>
<pre class="programlisting">
echo Zend_Filter::filterStatic('"',
                               'HtmlEntities',
                               array('quotestyle' =&gt; ENT_QUOTES));
</pre>
<p>
            El uso estático puede ser conveniente para invocar un filtro de forma ad hoc,
            pero si necesita ejecutar un filtro para múltiples entradas,
            es más eficiente seguir el primer ejemplo anterior,
            creando una instancia del objeto filtro y llamando a su
            método <code class="methodname">filter()</code>.
        </p>
<p>
            Además, la clase <code class="classname">Zend_Filter_Input</code> le permite instanciar y
            ejecutar múltiples clases de filtros y validadores bajo demanda para procesar
            conjuntos de datos de entrada. Vea <a class="link" href="zend.filter.input.phtml" title="35.5. Zend_Filter_Input">Zend_Filter_Input</a>.
        </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.introduction.static.namespaces"></a>35.1.3.1. Espacios de nombres</h4></div></div></div>
<p>
                Cuando trabaje con filtros propios definidos, puede pasar un cuarto parámetro
                a <code class="methodname">Zend_Filter::filterStatic()</code> que es el espacio de nombres
                donde se puede encontrar su filtro.
            </p>
<pre class="programlisting">
echo Zend_Filter::filterStatic(
    '"',
    'MyFilter',
    array($parameters),
    array('FirstNamespace', 'SecondNamespace')
);
</pre>
<p>
                <code class="classname">Zend_Filter</code> también permite establecer espacios de nombres por defecto.
                Esto significa que puede establecerlos una vez en su bootstrap y no tener que darlos
                de nuevo en cada llamada a <code class="methodname">Zend_Filter::filterStatic()</code>.
                El siguiente fragmento de código es idéntico al anterior.
            </p>
<pre class="programlisting">
Zend_Filter::setDefaultNamespaces(array('FirstNamespace', 'SecondNamespace'));
echo Zend_Filter::filterStatic('"', 'MyFilter', array($parameters));
echo Zend_Filter::filterStatic('"', 'OtherFilter', array($parameters));
</pre>
<p>
                Para su comodidad existen los siguientes métodos que permiten el manejo de
                espacios de nombres:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <span class="emphasis"><em><code class="methodname">Zend_Filter::getDefaultNamespaces()</code></em></span>:
                        Devuelve todos los espacios de nombres por defecto establecidos como un array.
                    </p></li>
<li class="listitem"><p>
                        <span class="emphasis"><em><code class="methodname">Zend_Filter::setDefaultNamespaces()</code></em></span>:
                        Establece nuevos espacios de nombres por defecto y sobrescribe cualquier valor establecido previamente. Acepta
                        una cadena para un único espacio de nombres o un array para múltiples espacios de nombres.
                    </p></li>
<li class="listitem"><p>
                        <span class="emphasis"><em><code class="methodname">Zend_Filter::addDefaultNamespaces()</code></em></span>:
                        Añade espacios de nombres adicionales a los ya establecidos. Acepta una cadena
                        para un único espacio de nombres o un array para múltiples espacios de nombres.
                    </p></li>
<li class="listitem"><p>
                        <span class="emphasis"><em><code class="methodname">Zend_Filter::hasDefaultNamespaces()</code></em></span>:
                        Devuelve <code class="constant">TRUE</code> cuando hay uno o más espacios de nombres por defecto
                        establecidos, y <code class="constant">FALSE</code> cuando no hay ninguno establecido.
                    </p></li>
</ul></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.introduction.caveats"></a>35.1.4. Doble filtrado</h3></div></div></div>
<p>
            Cuando se utilizan dos filtros uno tras otro, hay que tener en cuenta que a menudo no es
            posible obtener la salida original utilizando el filtro opuesto. Tome el siguiente
            ejemplo:
        </p>
<pre class="programlisting">
$original = "my_original_content";

// Adjuntar un filtro
$filter   = new Zend_Filter_Word_UnderscoreToCamelCase();
$filtered = $filter-&gt;filter($original);

// Usar su opuesto
$filter2  = new Zend_Filter_Word_CamelCaseToUnderscore();
$filtered = $filter2-&gt;filter($filtered)
</pre>
<p>
            El ejemplo de código anterior podría dar la impresión de que se obtendrá la salida
            original después de aplicar el segundo filtro. Pero pensando lógicamente esto no es el
            caso. Después de aplicar el primer filtro <span class="emphasis"><em>my_original_content</em></span> se
            cambiará a <span class="emphasis"><em>MyOriginalContent</em></span>. Pero después de aplicar el segundo filtro
            el resultado es <span class="emphasis"><em>My_Original_Content</em></span>.
        </p>
<p>
            Como puede ver, no siempre es posible obtener la salida original utilizando un filtro
            que parece ser el opuesto. Depende del filtro y también de la entrada dada.
        </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.file.transfer.filters.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.filter.set.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">34.3. Filtros para Zend_File_Transfer </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 35.2. Clases de filtro estándar</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
