<?php $title = 'registerNamespaces'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">registerNamespaces</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.register-namespace.phtml">Anterior</a> </td>
<th width="60%" align="center">42.7.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.register-prefix.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.standard-autoloader.methods.register-namespaces"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>registerNamespaces — Registra varios espacios de nombres con el autoloader</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">registerNamespaces</span>(<span class="methodparam">$namespaces</span>);</code>
</div>
<div class="refsection">
<a name="id37117"></a><h2>registerNamespaces()</h2>
<p>
                    Acepta un array o un objeto <code class="interfacename">Traversable</code>. A continuación
                    iterará a través del argumento, y pasará cada elemento a <a class="link" href="zend.loader.standard-autoloader.methods.register-namespace.phtml" title="registerNamespace">registerNamespace()</a>.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.register-namespace.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.register-prefix.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">registerNamespace </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> registerPrefix</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
