<?php $title = 'Capítulo 73. Zend_Tool_Project'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 73. Zend_Tool_Project</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.tool.framework.extending.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.tool.project.create-a-project.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.tool.project"></a>Capítulo 73. Zend_Tool_Project</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.tool.project.phtml#zend.tool.project.introduction">73.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.tool.project.create-a-project.phtml">73.2. Crear un proyecto</a></span></dt>
<dt><span class="sect1"><a href="zend.tool.project.providers.phtml">73.3. Proveedores de proyecto de Zend_Tool</a></span></dt>
<dt><span class="sect1"><a href="zend.tool.project.internals.phtml">73.4. Zend_Tool_Project internamente</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.project.internals.phtml#zend.tool.project.internals.xml-structure">73.4.1. Estructura Xml interna de Zend_Tool_Project</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.project.internals.phtml#zend.tool.project.internals.extending">73.4.2. Extensión interna de Zend_Tool_Project</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.tool.project.introduction"></a>73.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Tool_Project</code> se basa en las capacidades de
        <code class="classname">Zend_Tool_Framework</code> y las amplía para gestionar un "proyecto". En general, un
        "proyecto" es un esfuerzo planificado o una iniciativa. En el mundo de la informática, los proyectos
        generalmente son una colección de recursos. Estos recursos pueden ser archivos, directorios, bases de datos,
        esquemas, imágenes, estilos y más.
    </p>
<p>
        Este mismo concepto se aplica a los proyectos de Zend Framework. En los proyectos de Zend Framework, se tienen
        controladores, acciones, vistas, modelos, bases de datos, etcétera. En términos de
        <code class="classname">Zend_Tool</code>, necesitamos una forma de rastrear estos tipos de recursos - por eso
        <code class="classname">Zend_Tool_Project</code>.
    </p>
<p>
        <code class="classname">Zend_Tool_Project</code> es capaz de rastrear los recursos del proyecto a lo largo
        del desarrollo de un proyecto. Así, por ejemplo, si en un comando se crea un controlador,
        y en el siguiente comando desea crear una acción dentro de ese controlador,
        <code class="classname">Zend_Tool_Project</code> tendrá que <span class="emphasis"><em>conocer</em></span>
        el archivo del controlador que creó para que pueda (en la siguiente acción) añadir dicha
        acción a él. Esto es lo que mantiene nuestros proyectos actualizados y con <span class="emphasis"><em>estado</em></span>.
    </p>
<p>
        Otro punto importante para entender sobre los proyectos es que, generalmente, los recursos se
        organizan de forma jerárquica. Con esto en mente,
        <code class="classname">Zend_Tool_Project</code> es capaz de serializar el proyecto actual en
        una representación interna que le permite realizar un seguimiento no solo de <span class="emphasis"><em>qué</em></span>
        recursos forman parte de un proyecto en un momento dado, sino también de <span class="emphasis"><em>dónde</em></span> se encuentran
        en relación entre sí.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.tool.framework.extending.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.tool.project.create-a-project.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">72.6. Extender y configurar Zend_Tool_Framework </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 73.2. Crear un proyecto</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
