<?php $title = '15.3. Autenticación Digest'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">15.3. Autenticación Digest</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.auth.adapter.dbtable.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 15. Zend_Auth</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.auth.adapter.http.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.auth.adapter.digest"></a>15.3. Autenticación Digest</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.auth.adapter.digest.introduction"></a>15.3.1. Introducción</h3></div></div></div>
<p>
            La <a class="ulink" href="http://en.wikipedia.org/wiki/Digest_access_authentication" target="_top">autenticación
                Digest</a> es un método de autenticación <acronym class="acronym">HTTP</acronym> que
            mejora la <a class="ulink" href="http://en.wikipedia.org/wiki/Basic_authentication_scheme" target="_top">autenticación
                Basic</a> al proporcionar una forma de autenticarse sin tener que
            transmitir la contraseña en texto claro a través de la red.
        </p>
<p>
            Este adaptador permite la autenticación contra archivos de texto que contienen líneas con los elementos
            básicos de la autenticación Digest:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    nombre de usuario, como "<span class="emphasis"><em><code class="filename">joe.user</code></em></span>"
                </p></li>
<li class="listitem"><p>
                    reino (realm), como "<span class="emphasis"><em>Administrative Area</em></span>"
                </p></li>
<li class="listitem"><p>
                    hash <acronym class="acronym">MD5</acronym> del nombre de usuario, el reino y la contraseña, separados
                    por dos puntos
                </p></li>
</ul></div>
<p>
            Los elementos anteriores se separan con dos puntos, como en el siguiente ejemplo (en el que la
            contraseña es "<span class="emphasis"><em>somePassword</em></span>"):
        </p>
<pre class="programlisting">
someUser:Some Realm:fde17b91c3a510ecbaf7dbd37f59d4f8
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.auth.adapter.digest.specifics"></a>15.3.2. Detalles específicos</h3></div></div></div>
<p>
            El adaptador de autenticación Digest, <code class="classname">Zend_Auth_Adapter_Digest</code>,
            requiere varios parámetros de entrada:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    filename - Archivo contra el cual se realizan las consultas de autenticación
                </p></li>
<li class="listitem"><p>
                    realm - Reino de autenticación Digest
                </p></li>
<li class="listitem"><p>
                    username - Usuario de autenticación Digest
                </p></li>
<li class="listitem"><p>
                    password - Contraseña para el usuario del reino
                </p></li>
</ul></div>
<p>
            Estos parámetros deben establecerse antes de llamar a <code class="methodname">authenticate()</code>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.auth.adapter.digest.identity"></a>15.3.3. Identidad</h3></div></div></div>
<p>
            El adaptador de autenticación Digest devuelve un objeto <code class="classname">Zend_Auth_Result</code>,
            que ha sido poblado con la identidad como un array que tiene las claves
            <span class="emphasis"><em>realm</em></span> y <span class="emphasis"><em>username</em></span>. Los valores respectivos del array
            asociados a estas claves corresponden a los valores establecidos antes de que se llame a
            <code class="methodname">authenticate()</code>.
        </p>
<pre class="programlisting">
$adapter = new Zend_Auth_Adapter_Digest($filename,
                                        $realm,
                                        $username,
                                        $password);

$result = $adapter-&gt;authenticate();

$identity = $result-&gt;getIdentity();

print_r($identity);

/*
Array
(
    [realm] =&gt; Some Realm
    [username] =&gt; someUser
)
*/
</pre>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.auth.adapter.dbtable.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.auth.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.auth.adapter.http.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">15.2. Autenticación con tabla de base de datos </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 15.4. Adaptador de autenticación HTTP</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
