<?php $title = 'Capítulo 68. Zend_Test'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 68. Zend_Test</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.tag.cloud.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.test.phpunit.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.test"></a>Capítulo 68. Zend_Test</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.test.phtml#zend.test.introduction">68.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.test.phpunit.phtml">68.2. Zend_Test_PHPUnit</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.test.phpunit.phtml#zend.test.phpunit.bootstrapping">68.2.1. Arrancar su TestCase</a></span></dt>
<dt><span class="sect2"><a href="zend.test.phpunit.phtml#zend.test.phpunit.testing">68.2.2. Probar sus controladores y aplicaciones MVC</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.testing.redirector">68.2.2.1. Pruebas de controladores y el helper de acción Redirector</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions">68.2.3. Aserciones</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.query">68.2.3.1. Aserciones de selector CSS</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.xpath">68.2.3.2. Aserciones XPath</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.redirect">68.2.3.3. Aserciones de redirección</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.header">68.2.3.4. Aserciones de cabecera de respuesta</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.phtml#zend.test.phpunit.assertions.request">68.2.3.5. Aserciones de petición</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.test.phpunit.phtml#zend.test.phpunit.examples">68.2.4. Ejemplos</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.test.phpunit.db.phtml">68.3. Zend_Test_PHPUnit_Db</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.quickstart">68.3.1. Inicio rápido</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.quickstart.testcase">68.3.1.1. Configurar un TestCase de base de datos</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.quickstart.dataset">68.3.1.2. Especificar un conjunto de datos inicial (seed)</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.quickstart.initial-tests">68.3.1.3. Algunas pruebas iniciales de base de datos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.testing">68.3.2. Uso, API y puntos de extensión</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.testing.testcase">68.3.2.1. La clase Zend_Test_PHPUnit_DatabaseTestCase</a></span></dt>
<dt><span class="sect3"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.testing.controllerintegration">68.3.2.2. Integrar las pruebas de base de datos con ControllerTestCase</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.test.phpunit.db.phtml#zend.test.phpunit.db.adapter">68.3.3. Uso del adaptador de pruebas de base de datos</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.test.introduction"></a>68.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Test</code> proporciona herramientas para facilitar las pruebas unitarias de sus
        aplicaciones de Zend Framework. Por el momento, ofrecemos facilidades para permitir
        la prueba de sus aplicaciones <acronym class="acronym">MVC</acronym> de Zend Framework
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.tag.cloud.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.test.phpunit.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">67.2. Zend_Tag_Cloud </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 68.2. Zend_Test_PHPUnit</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
