<?php $title = 'setOptions'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">setOptions</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.constructor.phtml">Anterior</a> </td>
<th width="60%" align="center">42.7.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.set-fallback-autoloader.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.standard-autoloader.methods.set-options"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>setOptions — Establece el estado del objeto según las opciones proporcionadas.</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">setOptions</span>(<span class="methodparam">$options</span>);</code>
</div>
<div class="refsection">
<a name="id37060"></a><h2>setOptions()</h2>
<p>
                    Recibe como argumento un array asociativo o un objeto
                    <code class="interfacename">Traversable</code>. Las claves reconocidas se detallan
                    en <a class="xref" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.options" title="42.7.3. Configuration Options">Sección 42.7.3, “Opciones de configuración”</a>, con el
                    siguiente comportamiento:
                </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                            El valor <code class="varname">namespaces</code> se pasará a <a class="link" href="zend.loader.standard-autoloader.methods.register-namespaces.phtml" title="registerNamespaces">registerNamespaces()</a>.
                        </p></li>
<li class="listitem"><p>
                            El valor <code class="varname">prefixes</code> se pasará a <a class="link" href="zend.loader.standard-autoloader.methods.register-prefixes.phtml" title="registerPrefixes">registerPrefixes()</a>.
                        </p></li>
<li class="listitem"><p>
                            El valor <code class="varname">fallback_autoloader</code> se pasará a <a class="link" href="zend.loader.standard-autoloader.methods.set-fallback-autoloader.phtml" title="setFallbackAutoloader">setFallbackAutoloader()</a>.
                        </p></li>
</ul></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.standard-autoloader.methods.constructor.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.standard-autoloader.phtml#zend.loader.standard-autoloader.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.standard-autoloader.methods.set-fallback-autoloader.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">__construct </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> setFallbackAutoloader</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
