<?php $title = 'Capítulo 36. Zend_Form'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 36. Zend_Form</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.filter.inflector.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.form.quickstart.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.form"></a>Capítulo 36. Zend_Form</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.form.phtml#zend.form.introduction">36.1. Zend_Form</a></span></dt>
<dt><span class="sect1"><a href="zend.form.quickstart.phtml">36.2. Inicio rápido de Zend_Form</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.form.quickstart.phtml#zend.form.quickstart.create">36.2.1. Crear un objeto form</a></span></dt>
<dt><span class="sect2"><a href="zend.form.quickstart.phtml#zend.form.quickstart.elements">36.2.2. Añadir elementos al formulario</a></span></dt>
<dt><span class="sect2"><a href="zend.form.quickstart.phtml#zend.form.quickstart.render">36.2.3. Renderizar un formulario</a></span></dt>
<dt><span class="sect2"><a href="zend.form.quickstart.phtml#zend.form.quickstart.validate">36.2.4. Comprobar si un formulario es válido</a></span></dt>
<dt><span class="sect2"><a href="zend.form.quickstart.phtml#zend.form.quickstart.errorstatus">36.2.5. Obtener el estado de error</a></span></dt>
<dt><span class="sect2"><a href="zend.form.quickstart.phtml#zend.form.quickstart.puttingtogether">36.2.6. Poniéndolo todo junto</a></span></dt>
<dt><span class="sect2"><a href="zend.form.quickstart.phtml#zend.form.quickstart.config">36.2.7. Uso de un objeto Zend_Config</a></span></dt>
<dt><span class="sect2"><a href="zend.form.quickstart.phtml#zend.form.quickstart.conclusion">36.2.8. Conclusión</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.form.elements.phtml">36.3. Creación de elementos de formulario usando Zend_Form_Element</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.loaders">36.3.1. Cargadores de plugins</a></span></dt>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.filters">36.3.2. Filtros</a></span></dt>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.validators">36.3.3. Validadores</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.form.elements.phtml#zend.form.elements.validators.errors">36.3.3.1. Mensajes de error personalizados</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.decorators">36.3.4. Decoradores</a></span></dt>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.metadata">36.3.5. Metadatos y atributos</a></span></dt>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.standard">36.3.6. Elementos estándar</a></span></dt>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.methods">36.3.7. Métodos de Zend_Form_Element</a></span></dt>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.config">36.3.8. Configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.form.elements.phtml#zend.form.elements.custom">36.3.9. Elementos personalizados</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.form.forms.phtml">36.4. Creación de formularios usando Zend_Form</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.plugins">36.4.1. Cargadores de plugins</a></span></dt>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.elements">36.4.2. Elementos</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.elements.values">36.4.2.1. Rellenar y obtener valores</a></span></dt>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.elements.global">36.4.2.2. Operaciones globales</a></span></dt>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.elements.methods">36.4.2.3. Métodos para interactuar con elementos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.displaygroups">36.4.3. Grupos de visualización</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.displaygroups.global">36.4.3.1. Operaciones globales</a></span></dt>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.displaygroups.customClasses">36.4.3.2. Uso de clases de grupos de visualización personalizadas</a></span></dt>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.displaygroups.interactionmethods">36.4.3.3. Métodos para interactuar con grupos de visualización</a></span></dt>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.displaygroups.methods">36.4.3.4. Métodos de Zend_Form_DisplayGroup</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.subforms">36.4.4. Subformularios</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.subforms.global">36.4.4.1. Operaciones globales</a></span></dt>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.subforms.methods">36.4.4.2. Métodos para interactuar con subformularios</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.metadata">36.4.5. Metadatos y atributos</a></span></dt>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.decorators">36.4.6. Decoradores</a></span></dt>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.validation">36.4.7. Validación</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.validation.errors">36.4.7.1. Mensajes de error personalizados</a></span></dt>
<dt><span class="sect3"><a href="zend.form.forms.phtml#zend.form.forms.validation.values">36.4.7.2. Obtención solo de los valores válidos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.methods">36.4.8. Métodos</a></span></dt>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.config">36.4.9. Configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.form.forms.phtml#zend.form.forms.custom">36.4.10. Formularios personalizados</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.form.decorators.phtml">36.5. Creación de marcado de formulario personalizado usando Zend_Form_Decorator</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.form.decorators.phtml#zend.form.decorators.operation">36.5.1. Funcionamiento</a></span></dt>
<dt><span class="sect2"><a href="zend.form.decorators.phtml#zend.form.decorators.standard">36.5.2. Decoradores estándar</a></span></dt>
<dt><span class="sect2"><a href="zend.form.decorators.phtml#zend.form.decorators.custom">36.5.3. Decoradores personalizados</a></span></dt>
<dt><span class="sect2"><a href="zend.form.decorators.phtml#zend.form.decorators.individual">36.5.4. Renderizado de decoradores individuales</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.form.standardElements.phtml">36.6. Elementos de formulario estándar incluidos con Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.button">36.6.1. Zend_Form_Element_Button</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.captcha">36.6.2. Zend_Form_Element_Captcha</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.checkbox">36.6.3. Zend_Form_Element_Checkbox</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.file">36.6.4. Zend_Form_Element_File</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.hidden">36.6.5. Zend_Form_Element_Hidden</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.hash">36.6.6. Zend_Form_Element_Hash</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.Image">36.6.7. Zend_Form_Element_Image</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.multiCheckbox">36.6.8. Zend_Form_Element_MultiCheckbox</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.multiselect">36.6.9. Zend_Form_Element_Multiselect</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.password">36.6.10. Zend_Form_Element_Password</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.radio">36.6.11. Zend_Form_Element_Radio</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.reset">36.6.12. Zend_Form_Element_Reset</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.select">36.6.13. Zend_Form_Element_Select</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.submit">36.6.14. Zend_Form_Element_Submit</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.text">36.6.15. Zend_Form_Element_Text</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardElements.phtml#zend.form.standardElements.textarea">36.6.16. Zend_Form_Element_Textarea</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.form.standardDecorators.phtml">36.7. Decoradores de formulario estándar incluidos con Zend Framework</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.callback">36.7.1. Zend_Form_Decorator_Callback</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.captcha">36.7.2. Zend_Form_Decorator_Captcha</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.description">36.7.3. Zend_Form_Decorator_Description</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.dtDdWrapper">36.7.4. Zend_Form_Decorator_DtDdWrapper</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.errors">36.7.5. Zend_Form_Decorator_Errors</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.fieldset">36.7.6. Zend_Form_Decorator_Fieldset</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.file">36.7.7. Zend_Form_Decorator_File</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.form">36.7.8. Zend_Form_Decorator_Form</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.formElements">36.7.9. Zend_Form_Decorator_FormElements</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.formErrors">36.7.10. Zend_Form_Decorator_FormErrors</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.htmlTag">36.7.11. Zend_Form_Decorator_HtmlTag</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.image">36.7.12. Zend_Form_Decorator_Image</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.label">36.7.13. Zend_Form_Decorator_Label</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.prepareElements">36.7.14. Zend_Form_Decorator_PrepareElements</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.tooltip">36.7.15. Zend_Form_Decorator_Tooltip</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.viewHelper">36.7.16. Zend_Form_Decorator_ViewHelper</a></span></dt>
<dt><span class="sect2"><a href="zend.form.standardDecorators.phtml#zend.form.standardDecorators.viewScript">36.7.17. Zend_Form_Decorator_ViewScript</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.form.i18n.phtml">36.8. Internacionalización de Zend_Form</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.form.i18n.phtml#zend.form.i18n.initialization">36.8.1. Inicialización de I18n en formularios</a></span></dt>
<dt><span class="sect2"><a href="zend.form.i18n.phtml#zend.form.i18n.standard">36.8.2. Objetivos estándar de I18n</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.form.advanced.phtml">36.9. Uso avanzado de Zend_Form</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.form.advanced.phtml#zend.form.advanced.arrayNotation">36.9.1. Notación de array</a></span></dt>
<dt><span class="sect2"><a href="zend.form.advanced.phtml#zend.form.advanced.multiPage">36.9.2. Formularios multipágina</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.form.introduction"></a>36.1. Zend_Form</h2></div></div></div>
<p>
        <code class="classname">Zend_Form</code> simplifica la creación y el manejo de formularios en su
        aplicación web. Realiza las siguientes tareas:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Filtrado y validación de la entrada de los elementos</p></li>
<li class="listitem"><p>Ordenación de elementos</p></li>
<li class="listitem"><p>Renderizado de elementos y formularios, incluyendo el escapado</p></li>
<li class="listitem"><p>Agrupación de elementos y formularios</p></li>
<li class="listitem"><p>Configuración a nivel de elemento y de formulario</p></li>
</ul></div>
<p>
        <code class="classname">Zend_Form</code> utiliza varios componentes de Zend Framework para
        lograr sus objetivos, incluyendo <code class="classname">Zend_Config</code>,
        <code class="classname">Zend_Validate</code>, <code class="classname">Zend_Filter</code>,
        <code class="classname">Zend_Loader_PluginLoader</code>, y opcionalmente
        <code class="classname">Zend_View</code>.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.filter.inflector.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.form.quickstart.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">35.6. Zend_Filter_Inflector </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 36.2. Inicio rápido de Zend_Form</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
