<?php $title = '74.4. Creación de archivos fuente'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">74.4. Creación de archivos fuente</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.translate.using.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 74. Zend_Translate</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.translate.additional.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.translate.sourcecreation"></a>74.4. Creación de archivos fuente</h2></div></div></div>
<p>
        A continuación encontrará una descripción de los diferentes formatos de origen
        que pueden utilizarse con <code class="classname">Zend_Translate</code>.
    </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
            Tenga en cuenta que la mayoría de los formatos descritos deberían crearse utilizando
            una herramienta o un proceso de generación. Estas herramientas y procesos no forman parte
            de Zend Framework y para la mayoría de los formatos descritos hay disponibles herramientas
            gratuitas.
        </p></td></tr>
</table></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.translate.sourcecreation.array"></a>74.4.1. Creación de archivos fuente Array</h3></div></div></div>
<p>
            Los archivos fuente Array son simples arrays. Pero tiene que definirlos
            manualmente, ya que no hay ninguna herramienta que ayude en esto.
            Pero como son tan simples, es la forma más rápida de buscar
            mensajes si su código funciona como se espera. Generalmente es el mejor
            adaptador para comenzar con el negocio de la traducción.
        </p>
<pre class="programlisting">
$english = array(
    'message1' =&gt; 'message1',
    'message2' =&gt; 'message2',
    'message3' =&gt; 'message3');

$german = array(
    'message1' =&gt; 'Nachricht1',
    'message2' =&gt; 'Nachricht2',
    'message3' =&gt; 'Nachricht3');

$translate = new Zend_Translate(
    array(
        'adapter' =&gt; 'array',
        'content' =&gt; $english,
        'locale'  =&gt; 'en'
    )
);
$translate-&gt;addTranslation(array('content' =&gt; $german, 'locale' =&gt; 'de'));
</pre>
<p>
            Desde la versión 1.5 también se admite tener arrays incluidos dentro de un archivo externo.
            Solo tiene que proporcionar el nombre del archivo y <code class="classname">Zend_Translate</code>
            lo incluirá automáticamente y buscará el array. Vea el siguiente ejemplo para más detalles:
        </p>
<pre class="programlisting">
// myarray.php
return array(
    'message1' =&gt; 'Nachricht1',
    'message2' =&gt; 'Nachricht2',
    'message3' =&gt; 'Nachricht3');

// controller
$translate = new Zend_Translate(
    array(
        'adapter' =&gt; 'array',
        'content' =&gt; '/path/to/myarray.php',
        'locale'  =&gt; 'de'
    )
);
</pre>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Los archivos que no devuelvan un array no se podrán incluir.
                Además, cualquier salida dentro de este archivo será ignorada y suprimida.
            </p></td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.translate.sourcecreation.gettext"></a>74.4.2. Creación de archivos fuente Gettext</h3></div></div></div>
<p>
            Los archivos fuente Gettext son creados por la biblioteca gettext de GNU.
            Hay varias herramientas gratuitas disponibles que pueden analizar sus
            archivos de código y crear los archivos fuente gettext necesarios.
            Estos tienen la extensión <span class="emphasis"><em>*.mo</em></span>
            y son archivos binarios.
            Una herramienta de código abierto para crear los archivos es
            <a class="ulink" href="http://sourceforge.net/projects/poedit/" target="_top">poEdit</a>.
            Esta herramienta también le ayuda durante el propio proceso de traducción.
        </p>
<pre class="programlisting">
// We accume that we have created the mo files and translated them
$translate = new Zend_Translate(
    array(
        'adapter' =&gt; 'gettext',
        'content' =&gt; '/path/to/english.mo',
        'locale'  =&gt; 'en'
    )
);
$translate-&gt;addTranslation(
    array(
        'content' =&gt; '/path/to/german.mo',
        'locale' =&gt; 'de'
    )
);
</pre>
<p>
            Como puede ver, los adaptadores se utilizan exactamente de la misma manera,
            con una pequeña diferencia:
            cambiar <span class="emphasis"><em>array</em></span> por <span class="emphasis"><em>gettext</em></span>. Todos los demás usos son
            exactamente los mismos que con los demás adaptadores.
            Con el adaptador gettext ya no tiene que preocuparse de
            la estructura de directorios estándar de gettext,
            de bindtextdomain ni de textdomain.
            Solo indique la ruta y el nombre de archivo al adaptador.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top">
<p>
                 Siempre debería utilizar UTF-8 como codificación de origen.
                 De lo contrario tendrá problemas al utilizar dos
                 codificaciones de origen diferentes.
                 Por ejemplo, uno de sus archivos fuente está codificado
                 con ISO-8815-11 y otro con CP815.
                 Solo puede establecer una codificación para su archivo fuente,
                 así que probablemente uno de sus idiomas no se mostrará correctamente.
            </p>
<p>
                 UTF-8 es un formato portable que admite todos los idiomas.
                 Al utilizar UTF-8 para todos los idiomas, eliminará
                 el problema de las codificaciones incompatibles.
            </p>
</td></tr>
</table></div>
<p>
            Muchos editores de gettext añaden información del adaptador como cadena de traducción vacía.
            Esta es la razón por la que las cadenas vacías no se traducen cuando se utiliza el
            adaptador gettext. En su lugar, se eliminan de la tabla de traducción y
            se proporcionan mediante el método <code class="methodname">getAdapterInfo()</code>. Este devolverá
            la información del adaptador para todos los archivos gettext añadidos como un array usando
            el nombre de archivo como clave.
        </p>
<pre class="programlisting">
// Getting the adapter informations
$translate = new Zend_Translate(
    array(
        'adapter' =&gt; 'gettext',
        'content' =&gt; '/path/to/english.mo',
        'locale'  =&gt; 'en'
    )
);
print_r($translate-&gt;getAdapterInfo());
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.translate.sourcecreation.tmx"></a>74.4.3. Creación de archivos fuente TMX</h3></div></div></div>
<p>
            Los archivos fuente TMX son un nuevo estándar de la industria.
            Tienen la ventaja de ser archivos <acronym class="acronym">XML</acronym>, por lo que son
            legibles por cualquier editor y, por supuesto, por las personas.
            Puede crear archivos TMX manualmente con un editor de texto,
            o puede utilizar una herramienta especial. Pero la mayoría de las herramientas actualmente disponibles para
            crear archivos fuente TMX no son gratuitas.
        </p>
<div class="example">
<a name="zend.translate.sourcecreation.tmx.example"></a><p class="title"><b>Ejemplo 74.3. Ejemplo de archivo TMX</b></p>
<div class="example-contents">
<pre class="programlisting">
&lt;?xml version="1.0" ?&gt;
&lt;!DOCTYPE tmx SYSTEM "tmx14.dtd"&gt;
&lt;tmx version="1.4"&gt;
   &lt;header creationtoolversion="1.0.0" datatype="winres" segtype="sentence"
           adminlang="en-us" srclang="de-at" o-tmf="abc"
           creationtool="XYZTool" &gt;
   &lt;/header&gt;
   &lt;body&gt;
       &lt;tu tuid='message1'&gt;
           &lt;tuv xml:lang="de"&gt;&lt;seg&gt;Nachricht1&lt;/seg&gt;&lt;/tuv&gt;
           &lt;tuv xml:lang="en"&gt;&lt;seg&gt;message1&lt;/seg&gt;&lt;/tuv&gt;
       &lt;/tu&gt;
       &lt;tu tuid='message2'&gt;
           &lt;tuv xml:lang="de"&gt;&lt;seg&gt;Nachricht2&lt;/seg&gt;&lt;/tuv&gt;
           &lt;tuv xml:lang="en"&gt;&lt;seg&gt;message2&lt;/seg&gt;&lt;/tuv&gt;
       &lt;/tu&gt;
   &lt;/body&gt;
&lt;/tmx&gt;
</pre>
<pre class="programlisting">
$translate = new Zend_Translate(
    array(
        'adapter' =&gt; 'tmx',
        'content' =&gt; 'path/to/mytranslation.tmx',
        'locale'  =&gt; 'en'
    )
);
</pre>
</div>
</div>
<br class="example-break"><p>
            Los archivos TMX pueden tener varios idiomas dentro del mismo archivo.
            Todos los demás idiomas incluidos se añaden automáticamente,
            por lo que no tiene que llamar a <code class="methodname">addLanguage()</code>.
        </p>
<p>
            Si desea que solo se traduzcan idiomas específicos del origen, puede
            establecer la opción <span class="property">defined_language</span> en <code class="constant">TRUE</code>.
            Con esta opción puede añadir explícitamente los idiomas deseados con
            <code class="methodname">addLanguage()</code>. El valor por defecto de esta opción es añadir todos
            los idiomas.
        </p>
<div class="note"><table border="0" summary="Note: Option useId">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Opción useId</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Cuando establece la opción <span class="emphasis"><em>useId</em></span> en <code class="constant">FALSE</code>
                entonces se utilizará la cabecera <span class="emphasis"><em>srclang</em></span> para definir el idioma
                que establece el mensaje.
            </p>
<p>
                En nuestro ejemplo, la clave del mensaje sería por defecto <span class="emphasis"><em>message1</em></span>.
                Cuando esta opción se establece en <code class="constant">FALSE</code> se utilizaría la clave
                de mensaje <span class="emphasis"><em>Nachricht1</em></span>.
            </p>
<p>
                Tenga en cuenta que la entrada <span class="emphasis"><em>tuv</em></span> que está relacionada con la
                entrada <span class="emphasis"><em>srclang</em></span> debe ser la primera
                entrada <span class="emphasis"><em>tuv</em></span> tal como se establece en el ejemplo anterior.
            </p>
</td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.translate.sourcecreation.csv"></a>74.4.4. Creación de archivos fuente CSV</h3></div></div></div>
<p>
            Los archivos fuente CSV son pequeños y legibles por humanos.
            Si sus clientes quieren traducir por su cuenta,
            probablemente utilizará el adaptador CSV.
        </p>
<div class="example">
<a name="zend.translate.sourcecreation.csv.example"></a><p class="title"><b>Ejemplo 74.4. Ejemplo de archivo CSV</b></p>
<div class="example-contents">
<pre class="programlisting">
﻿#Example csv file
message1;Nachricht1
message2;Nachricht2
</pre>
<pre class="programlisting">
$translate = new Zend_Translate(
    array(
        'adapter' =&gt; 'csv',
        'content' =&gt; '/path/to/mytranslation.csv',
        'locale'  =&gt; 'de'
    )
);
$translate-&gt;addTranslation(
    array(
        'content' =&gt; 'path/to/other.csv',
        'locale' =&gt; 'fr'
    )
);
</pre>
</div>
</div>
<br class="example-break"><p>
            Hay tres opciones diferentes para el adaptador CSV.
            Puede establecer <span class="property">delimiter</span>, <span class="property">limit</span> y
            <span class="property">enclosure</span>.
        </p>
<p>
            El delimitador por defecto para cadenas CSV es '<span class="emphasis"><em>;</em></span>', pero
            con la opción <span class="property">delimiter</span>
            puede decidir utilizar otro.
        </p>
<p>
            El límite por defecto para una línea dentro de un archivo CSV es '<span class="emphasis"><em>0</em></span>'. Esto significa
            que el final de una línea CSV se busca automáticamente. Si establece
            <span class="property">limit</span> en cualquier valor, entonces el archivo CSV se
            leerá más rápido, pero cualquier línea que exceda este límite se truncará.
        </p>
<p>
            El delimitador de texto por defecto para archivos CSV es '<span class="emphasis"><em>"</em></span>'. Puede
            establecer uno diferente utilizando la opción <span class="property">enclosure</span>.
        </p>
<div class="example">
<a name="zend.translate.sourcecreation.csv.example2"></a><p class="title"><b>Ejemplo 74.5. Segundo ejemplo de archivo CSV</b></p>
<div class="example-contents">
<pre class="programlisting">
﻿# Example CSV file
"message,1",Nachricht1
message2,"Nachricht,2"
"message3,",Nachricht3
</pre>
<pre class="programlisting">
$translate = new Zend_Translate(
    array(
        'adapter' =&gt; 'csv',
        'content' =&gt; '/path/to/mytranslation.csv',
        'locale'  =&gt; 'de',
        'delimiter' =&gt; ','
    )
);

$translate-&gt;addTranslation(
    array(
        'content' =&gt; '/path/to/other.csv',
        'locale' =&gt; 'fr'
    )
);
</pre>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando utiliza caracteres no ASCII dentro de su archivo CSV, como diéresis o
                caracteres UTF-8, entonces siempre debería utilizar el delimitador de texto. Omitir el
                delimitador de texto puede provocar la pérdida de caracteres en su traducción.
            </p></td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.translate.sourcecreation.ini"></a>74.4.5. Creación de archivos fuente INI</h3></div></div></div>
<p>
            Los archivos fuente <acronym class="acronym">INI</acronym> son legibles por humanos pero normalmente no muy pequeños ya
            que también incluyen otros datos además de las traducciones. Si tiene datos que deban
            ser editables por sus clientes, puede utilizar el adaptador <acronym class="acronym">INI</acronym>.
        </p>
<div class="example">
<a name="zend.translate.sourcecreation.ini.example"></a><p class="title"><b>Ejemplo 74.6. Ejemplo de archivo INI</b></p>
<div class="example-contents">
<pre class="programlisting">
[Test]
;TestPage Comment
Message_1="Nachricht 1 (de)"
Message_2="Nachricht 2 (de)"
Message_3="Nachricht :3 (de)"
</pre>
<pre class="programlisting">
$translate = new Zend_Translate(
    array(
        'adapter' =&gt; 'ini',
        'content' =&gt; '/path/to/mytranslation.ini',
        'locale'  =&gt; 'de'
    )
);
$translate-&gt;addTranslation(
    array(
        'content' =&gt; '/path/to/other.ini',
        'locale' =&gt; 'it'
    )
);
</pre>
</div>
</div>
<br class="example-break"><p>
            Los archivos <acronym class="acronym">INI</acronym> tienen varias restricciones. Si un valor en el
            archivo <acronym class="acronym">INI</acronym> contiene algún carácter no alfanumérico, debe
            encerrarse entre comillas dobles (<span class="emphasis"><em>"</em></span>). También hay palabras reservadas que
            no deben utilizarse como claves en archivos <acronym class="acronym">INI</acronym>. Estas incluyen:
            <code class="constant">NULL</code>, yes, no, <code class="constant">TRUE</code>, y
            <code class="constant">FALSE</code>. Los valores <code class="constant">NULL</code>, <span class="emphasis"><em>no</em></span>
            y <code class="constant">FALSE</code> dan como resultado <span class="emphasis"><em>""</em></span>,
            <span class="emphasis"><em>yes</em></span> y <code class="constant">TRUE</code> dan como resultado '1'. Los caracteres
            <span class="emphasis"><em>{}|&amp;~![()"</em></span> no deben utilizarse en ninguna parte de la clave y tienen un
            significado especial en el valor. No los utilice, ya que producirá un comportamiento inesperado.
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.translate.using.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.translate.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.translate.additional.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">74.3. Uso de adaptadores de traducción </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 74.5. Características adicionales para la traducción</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
