<?php $title = 'Capítulo 25. Zend_Currency'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 25. Zend_Currency</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.controller.exceptions.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.currency.usage.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.currency"></a>Capítulo 25. Zend_Currency</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.currency.phtml#zend.currency.introduction">25.1. Introducción a Zend_Currency</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="zend.currency.phtml#zend.currency.introduction.list">25.1.1. ¿Por qué debería usar Zend_Currency?</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="zend.currency.usage.phtml">25.2. Uso de Zend_Currency</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.currency.usage.phtml#zend.currency.usage.generic">25.2.1. Uso genérico</a></span></dt>
<dt><span class="sect2"><a href="zend.currency.usage.phtml#zend.currency.usage.locale">25.2.2. Creación de una moneda basada en una configuración regional</a></span></dt>
<dt><span class="sect2"><a href="zend.currency.usage.phtml#zend.currency.usage.territory">25.2.3. Creación de una moneda basada en un país</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.currency.options.phtml">25.3. Opciones para monedas</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.description.phtml">25.4. ¿Qué define una moneda?</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.position.phtml">25.5. ¿Dónde está la moneda?</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.number.phtml">25.6. ¿Cómo se ve la moneda?</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.value.phtml">25.7. ¿Cuánto vale mi moneda?</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.currency.value.phtml#zend.currency.value.money">25.7.1. Trabajar con valores de moneda</a></span></dt>
<dt><span class="sect2"><a href="zend.currency.value.phtml#zend.currency.value.precision">25.7.2. Uso de la precisión en las monedas</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.currency.calculation.phtml">25.8. Cálculos con monedas</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.exchange.phtml">25.9. Intercambio de monedas</a></span></dt>
<dt><span class="sect1"><a href="zend.currency.additional.phtml">25.10. Información adicional sobre Zend_Currency</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.currency.additional.phtml#zend.currency.additional.informations">25.10.1. Información de monedas</a></span></dt>
<dt><span class="sect2"><a href="zend.currency.additional.phtml#zend.currency.additional.cache">25.10.2. Optimización del rendimiento de monedas</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.currency.introduction"></a>25.1. Introducción a Zend_Currency</h2></div></div></div>
<p>
        <code class="classname">Zend_Currency</code> forma parte del sólido soporte para I18n en Zend
        Framework. Se encarga de todos los aspectos relacionados con las monedas, la representación de
        dinero, el formateo, los servicios de cambio y los cálculos.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.currency.introduction.list"></a>25.1.1. ¿Por qué debería usar Zend_Currency?</h3></div></div></div>
<p>
            <code class="classname">Zend_Currency</code> le ofrece los siguientes beneficios:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: opencircle; ">
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Soporte completo de configuración regional</em></span>
                </p>
<p>
                    Este componente funciona con todas las configuraciones regionales disponibles y por
                    lo tanto conoce más de 100 monedas localizadas diferentes. Esto incluye información
                    como nombres de monedas, abreviaturas, signos monetarios y mucho más.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Definiciones de monedas reutilizables</em></span>
                </p>
<p>
                    <code class="classname">Zend_Currency</code> tiene la ventaja de que las
                    representaciones de moneda ya definidas pueden reutilizarse. También podría tener 2
                    representaciones diferentes para la misma moneda.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Cálculo de monedas</em></span>
                </p>
<p>
                    <code class="classname">Zend_Currency</code> también le permite calcular con valores de
                    moneda. Para ello, proporciona una interfaz a servicios de cambio.
                </p>
</li>
<li class="listitem" style="list-style-type: circle">
<p>
                    <span class="emphasis"><em>Métodos adicionales</em></span>
                </p>
<p>
                    <code class="classname">Zend_Currency</code> incluye varios métodos adicionales que
                    ofrecen información detallada sobre las monedas, como qué moneda se usa en una
                    región definida y cuáles son las abreviaturas conocidas de una moneda.
                </p>
</li>
</ul></div>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.controller.exceptions.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.currency.usage.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">24.12. Excepciones de MVC </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 25.2. Uso de Zend_Currency</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
