<?php $title = '40.3. Opciones de configuración de Zend_Layout'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">40.3. Opciones de configuración de Zend_Layout</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.layout.quickstart.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 40. Zend_Layout</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.layout.advanced.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.layout.options"></a>40.3. Opciones de configuración de Zend_Layout</h2></div></div></div>
<p>
        <code class="classname">Zend_Layout</code> tiene una variedad de opciones de configuración. Estas
        pueden establecerse llamando a los accesores apropiados, pasando un array u objeto
        <code class="classname">Zend_Config</code> al constructor o a
        <code class="methodname">startMvc()</code>, pasando un array de opciones a
        <code class="methodname">setOptions()</code>, o pasando un objeto <code class="classname">Zend_Config</code>
        a <code class="methodname">setConfig()</code>.
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                <span class="emphasis"><em>layout</em></span>: el layout a usar. Usa el
                inflector actual para resolver el nombre proporcionado hacia el
                script de vista de layout apropiado. Por defecto, este valor es
                'layout' y se resuelve a 'layout.phtml'. Los accesores
                son <code class="methodname">setLayout()</code> y <code class="methodname">getLayout()</code>.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>layoutPath</em></span>: la ruta base a los scripts de vista de
                layout. Los accesores son <code class="methodname">setLayoutPath()</code> y
                <code class="methodname">getLayoutPath()</code>.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>contentKey</em></span>: la variable de layout usada para el
                contenido por defecto (cuando se usa con el <acronym class="acronym">MVC</acronym>). El valor por defecto es
                'content'. Los accesores son <code class="methodname">setContentKey()</code> y
                <code class="methodname">getContentKey()</code>.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>mvcSuccessfulActionOnly</em></span>: cuando se usa el
                <acronym class="acronym">MVC</acronym>, si una acción lanza una excepción y este indicador es
                <code class="constant">TRUE</code>, el layout no se renderizará (esto es para evitar el
                doble renderizado del layout cuando se usa el <a class="link" href="zend.controller.plugins.phtml#zend.controller.plugins.standard.errorhandler" title="24.10.5.2. Zend_Controller_Plugin_ErrorHandler">plugin
                    ErrorHandler</a>). Por defecto, el indicador es <code class="constant">TRUE</code>.
                Los accesores son <code class="methodname">setMvcSuccessfulActionOnly()</code> y
                <code class="methodname">getMvcSuccessfulActionOnly()</code>.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>view</em></span>: el objeto de vista a usar al renderizar. Cuando se usa con el
                <acronym class="acronym">MVC</acronym>, <code class="classname">Zend_Layout</code> intentará usar el
                objeto de vista registrado con <a class="link" href="zend.controller.actionhelpers.phtml#zend.controller.actionhelpers.viewrenderer" title="24.8.4.7. ViewRenderer">el ViewRenderer</a> si
                no se le ha pasado explícitamente ningún objeto de vista. Los accesores son
                <code class="methodname">setView()</code> y <code class="methodname">getView()</code>.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>helperClass</em></span>: la clase de helper de acción a usar
                cuando se usa <code class="classname">Zend_Layout</code> con los componentes <acronym class="acronym">MVC</acronym>.
                Por defecto, esta es
                <code class="classname">Zend_Layout_Controller_Action_Helper_Layout</code>.
                Los accesores son <code class="methodname">setHelperClass()</code> y
                <code class="methodname">getHelperClass()</code>.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>pluginClass</em></span>: la clase de plugin del controlador frontal
                a usar cuando se usa <code class="classname">Zend_Layout</code> con los componentes
                <acronym class="acronym">MVC</acronym>. Por defecto, esta es
                <code class="classname">Zend_Layout_Controller_Plugin_Layout</code>. Los accesores
                son <code class="methodname">setPluginClass()</code> y
                <code class="methodname">getPluginClass()</code>.
            </p></li>
<li class="listitem"><p>
                <span class="emphasis"><em>inflector</em></span>: el inflector a usar al
                resolver los nombres de layout a rutas de scripts de vista de layout; vea <a class="link" href="zend.layout.advanced.phtml#zend.layout.advanced.inflector" title="40.4.4. Custom Layout Script Path Resolution: Using the Inflector">la
                    documentación del inflector de <code class="classname">Zend_Layout</code> para más
                    detalles</a>. Los accesores son <code class="methodname">setInflector()</code>
                y <code class="methodname">getInflector()</code>.
            </p></li>
</ul></div>
<div class="note"><table border="0" summary="Note: helperClass and pluginClass must be passed to startMvc()">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">helperClass y pluginClass deben pasarse a startMvc()</th>
</tr>
<tr><td align="left" valign="top"><p>
            Para que las opciones <span class="property">helperClass</span> y
            <span class="property">pluginClass</span> tengan efecto, deben
            pasarse como opciones a <code class="methodname">startMvc()</code>; si se establecen más tarde,
            no tienen efecto.
        </p></td></tr>
</table></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.layout.options.examples"></a>40.3.1. Ejemplos</h3></div></div></div>
<p>
            Los siguientes ejemplos asumen el siguiente array
            <code class="varname">$options</code> y el objeto <code class="varname">$config</code>:
        </p>
<pre class="programlisting">
$options = array(
    'layout'     =&gt; 'foo',
    'layoutPath' =&gt; '/path/to/layouts',
    'contentKey' =&gt; 'CONTENT',           // ignored when MVC not used
);
</pre>
<pre class="programlisting">
/**
[layout]
layout = "foo"
layoutPath = "/path/to/layouts"
contentKey = "CONTENT"
*/
$config = new Zend_Config_Ini('/path/to/layout.ini', 'layout');
</pre>
<div class="example">
<a name="zend.layout.options.examples.constructor"></a><p class="title"><b>Ejemplo 40.1. Pasar opciones al constructor o a startMvc()</b></p>
<div class="example-contents">
<p>
                Tanto el constructor como el método estático <code class="methodname">startMvc()</code>
                pueden aceptar un array de opciones o un objeto
                <code class="classname">Zend_Config</code> con opciones para
                configurar la instancia de <code class="classname">Zend_Layout</code>.
            </p>
<p>
                Primero, veamos cómo pasar un array:
            </p>
<pre class="programlisting">
// Using constructor:
$layout = new Zend_Layout($options);

// Using startMvc():
$layout = Zend_Layout::startMvc($options);
</pre>
<p>
                Y ahora usando un objeto de configuración:
            </p>
<pre class="programlisting">
$config = new Zend_Config_Ini('/path/to/layout.ini', 'layout');

// Using constructor:
$layout = new Zend_Layout($config);

// Using startMvc():
$layout = Zend_Layout::startMvc($config);
</pre>
<p>
                Básicamente, esta es la forma más sencilla de personalizar su
                instancia de <code class="classname">Zend_Layout</code>.
            </p>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.layout.options.examples.setoptionsconfig"></a><p class="title"><b>Ejemplo 40.2. Usar setOption() y setConfig()</b></p>
<div class="example-contents">
<p>
                A veces necesita configurar el objeto <code class="classname">Zend_Layout</code>
                después de que ya ha sido instanciado;
                <code class="methodname">setOptions()</code> y <code class="methodname">setConfig()</code> le dan
                una forma rápida y sencilla de hacerlo:
            </p>
<pre class="programlisting">
// Using an array of options:
$layout-&gt;setOptions($options);

// Using a Zend_Config object:
$layout-&gt;setConfig($options);
</pre>
<p>
                Tenga en cuenta, sin embargo, que ciertas opciones, como
                <span class="property">pluginClass</span> y <span class="property">helperClass</span>, no tendrán
                ningún efecto cuando se pasen usando este método; deben pasarse
                al constructor o al método <code class="methodname">startMvc()</code>.
            </p>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.layout.options.examples.accessors"></a><p class="title"><b>Ejemplo 40.3. Usar accesores</b></p>
<div class="example-contents">
<p>
                Finalmente, también puede configurar su instancia de <code class="classname">Zend_Layout</code>
                mediante accesores. Todos los accesores implementan una interfaz
                fluida, lo que significa que sus llamadas pueden encadenarse:
            </p>
<pre class="programlisting">
$layout-&gt;setLayout('foo')
       -&gt;setLayoutPath('/path/to/layouts')
       -&gt;setContentKey('CONTENT');
</pre>
</div>
</div>
<br class="example-break">
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.layout.quickstart.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.layout.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.layout.advanced.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">40.2. Inicio rápido de Zend_Layout </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 40.4. Uso avanzado de Zend_Layout</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
