<?php $title = 'Capítulo 80. Zend_XmlRpc'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 80. Zend_XmlRpc</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.wildfire.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.xmlrpc.client.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.xmlrpc"></a>Capítulo 80. Zend_XmlRpc</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.xmlrpc.phtml#zend.xmlrpc.introduction">80.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.xmlrpc.client.phtml">80.2. Zend_XmlRpc_Client</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.introduction">80.2.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.method-calls">80.2.2. Llamadas a métodos</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.value.parameters">80.2.3. Tipos y conversiones</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.value.parameters.php-native">80.2.3.1. Tipos nativos de PHP como parámetros</a></span></dt>
<dt><span class="sect3"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.value.parameters.xmlrpc-value">80.2.3.2. Objetos Zend_XmlRpc_Value como parámetros</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.requests-and-responses">80.2.4. Objeto proxy del servidor</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.error-handling">80.2.5. Manejo de errores</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.error-handling.http">80.2.5.1. Errores HTTP</a></span></dt>
<dt><span class="sect3"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.error-handling.faults">80.2.5.2. Fallos de XML-RPC</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.introspection">80.2.6. Introspección del servidor</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.request-to-response">80.2.7. De la petición a la respuesta</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.client.phtml#zend.xmlrpc.client.http-client">80.2.8. Cliente HTTP y pruebas</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.xmlrpc.server.phtml">80.3. Zend_XmlRpc_Server</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.introduction">80.3.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.usage">80.3.2. Uso básico</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.structure">80.3.3. Estructura del servidor</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.anatomy">80.3.4. Anatomía de un servicio web</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.anatomy.general">80.3.4.1. Consideraciones generales</a></span></dt>
<dt><span class="sect3"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.anatomy.expose">80.3.4.2. ¿Qué exponer?</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.conventions">80.3.5. Convenciones</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.namespaces">80.3.6. Utilización de espacios de nombres</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.request">80.3.7. Objetos de petición personalizados</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.response">80.3.8. Respuestas personalizadas</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.fault">80.3.9. Manejo de excepciones mediante fallos</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.caching">80.3.10. Almacenamiento en caché de definiciones del servidor entre peticiones</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.use">80.3.11. Ejemplos de uso</a></span></dt>
<dt><span class="sect2"><a href="zend.xmlrpc.server.phtml#zend.xmlrpc.server.performance">80.3.12. Optimización del rendimiento</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.xmlrpc.introduction"></a>80.1. Introducción</h2></div></div></div>
<p>
        Desde su <a class="ulink" href="http://www.xmlrpc.com/" target="_top">página de inicio</a>,
        <acronym class="acronym">XML-RPC</acronym> se describe como "...una llamada a procedimiento remoto usando
        <acronym class="acronym">HTTP</acronym> como transporte y <acronym class="acronym">XML</acronym> como codificación.
        <acronym class="acronym">XML-RPC</acronym> está diseñado para ser lo más simple posible, a la vez que permite
        transmitir, procesar y devolver estructuras de datos complejas."
    </p>
<p>
        Zend Framework proporciona soporte tanto para consumir servicios remotos de <acronym class="acronym">XML-RPC</acronym>
        como para construir nuevos servidores <acronym class="acronym">XML-RPC</acronym>.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.wildfire.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.xmlrpc.client.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 79. Zend_Wildfire </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 80.2. Zend_XmlRpc_Client</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
