<?php $title = '50.2. Zend_Mobile_Push_Apns'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">50.2. Zend_Mobile_Push_Apns</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mobile.push.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 50. Zend_Mobile_Push</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mobile.push.gcm.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mobile.push.apns"></a>50.2. Zend_Mobile_Push_Apns</h2></div></div></div>
<p>
        <code class="classname">Zend_Mobile_Push_Apns</code> proporciona la capacidad de
        enviar notificaciones push a <acronym class="acronym">APNS</acronym> generalmente en
        conjunto con <code class="classname">Zend_Mobile_Push_Message_Apns</code>;
        sin embargo, hay un caso en el que no se utilizaría, y es al obtener
        retroalimentación (feedback) del servidor APNS.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mobile.push.apns.server"></a>50.2.1. Enviando mensajes</h3></div></div></div>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>Antes de enviar mensajes, debe seguir los
                <a class="ulink" href="http://developer.apple.com/library/mac/#documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/ProvisioningDevelopment/ProvisioningDevelopment.html" target="_top">pasos de aprovisionamiento y despliegue descritos por Apple</a>.</p></td></tr>
</table></div>
<p>
            Al implementar APNS, dispone de algunos componentes que
            utilizará. <code class="classname">Zend_Mobile_Push_Apns</code>
            que contiene los componentes del servidor y
            <code class="classname">Zend_Mobile_Push_Message_Apns</code> que contiene
            el mensaje que desea enviar. Generalmente, al enviar
            notificaciones push a Apple debería hacerlo por lotes.
        </p>
<p>
            La implementación real del código es bastante mínima; sin embargo,
            se deben tener en cuenta consideraciones sobre el manejo de errores.
        </p>
<pre class="programlisting">
$message = new Zend_Mobile_Push_Message_Apns();
$message-&gt;setAlert('Zend Mobile Push Example');
$message-&gt;setBadge(1);
$message-&gt;setSound('default');
$message-&gt;setId(time());
$message-&gt;setToken('ABCDEF0123456789');

$apns = new Zend_Mobile_Push_Apns();
$apns-&gt;setCertificate('/path/to/provisioning-certificate.pem');
// if you have a passphrase on your certificate:
// $apns-&gt;setCertificatePassphrase('foobar');

try {
    $apns-&gt;connect(Zend_Mobile_Push_Apns::SERVER_SANDBOX_URI);
} catch (Zend_Mobile_Push_Exception_ServerUnavailable $e) {
    // you can either attempt to reconnect here or try again later
    exit(1);
} catch (Zend_Mobile_Push_Exception $e) {
    echo 'APNS Connection Error:' . $e-&gt;getMessage();
    exit(1);
}

try {
    $apns-&gt;send($message);
} catch (Zend_Mobile_Push_Exception_InvalidToken $e) {
    // you would likely want to remove the token from being sent to again
    echo $e-&gt;getMessage();
} catch (Zend_Mobile_Push_Exception $e) {
    // all other exceptions only require action to be sent
    echo $e-&gt;getMessage();
}
$apns-&gt;close();
</pre>
<div class="table">
<a name="zend.mobile.push.apns.server.exceptions"></a><p class="title"><b>Tabla 50.3. Excepciones y técnicas de remediación</b></p>
<div class="table-contents"><table class="table" summary="Exceptions and Remediation Techniques" border="1">
<colgroup>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th align="left">Excepción</th>
<th align="left">Significado</th>
<th align="left">Manejo</th>
</tr></thead>
<tbody>
<tr>
<td align="left">Zend_Mobile_Push_Exception</td>
<td align="left">Este tipo de excepciones son de naturaleza más genérica
                        y se lanzan ya sea desde APNS o internamente durante la
                        validación de entrada</td>
<td align="left">Lea el mensaje y determine los pasos de remediación.</td>
</tr>
<tr>
<td align="left">Zend_Mobile_Push_Exception_InvalidPayload</td>
<td align="left">Generalmente, el payload no lanzará una excepción
                        a menos que el tamaño del payload sea demasiado grande o le
                        falte contenido requerido.</td>
<td align="left">Verifique que el tamaño del payload esté dentro de los
                        requisitos de APNS</td>
</tr>
<tr>
<td align="left">Zend_Mobile_Push_Exception_InvalidToken</td>
<td align="left">Cualquier forma de token inválido ocurrirá si el token ya
                        no está registrado, falta un token o tiene un
                        formato inválido.</td>
<td align="left">Debe eliminar el token y no intentar enviar
                        a él nuevamente.</td>
</tr>
<tr>
<td align="left">Zend_Mobile_Push_Exception_InvalidTopic</td>
<td align="left">Un topic inválido simplemente significa que el id del mensaje era
                        demasiado largo o no era un entero.</td>
<td align="left">Asegúrese de que el ID del mensaje sea un entero.</td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><div class="warning"><table border="0" summary="Warning">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Warning]" src="images/warning.png"></td>
<th align="left">Advertencia</th>
</tr>
<tr><td align="left" valign="top"><p>
                Al enviar por lotes y estar enviando una gran cantidad de notificaciones
                push, debe asegurarse de usar usleep de vez en cuando. Esto
                garantizará que sus mensajes se entreguen y que APNS no simplemente
                le cuelgue la conexión.
        </p></td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mobile.push.apns.feedback"></a>50.2.2. Obteniendo retroalimentación</h3></div></div></div>
<p>
            APNS tiene un servicio de retroalimentación al que <span class="emphasis"><em>debe</em></span>
            escuchar. Apple indica que monitorea a los proveedores para asegurarse de que
            estén escuchando este servicio.
        </p>
<p>
            El servicio de retroalimentación simplemente devuelve un array de tokens de dispositivo y
            la hora. Puede usar la hora para asegurarse de que el dispositivo no se haya
            vuelto a registrar para notificaciones push desde el último envío.
        </p>
<pre class="programlisting">
$apns = new Zend_Mobile_Push_Apns();
$apns-&gt;setCertificate('/path/to/provisioning-certificate.pem');

try {
    $apns-&gt;connect(Zend_Mobile_Push_Apns::SERVER_FEEDBACK_SANDBOX_URI);
} catch (Zend_Mobile_Push_Exception_ServerUnavailable $e) {
    // you can either attempt to reconnect here or try again later
    exit(1);
} catch (Zend_Mobile_Push_Exception $e) {
    echo 'APNS Connection Error:' . $e-&gt;getMessage();
    exit(1);
}

$tokens = $apns-&gt;feedback();
foreach ($tokens as $token =&gt; $time) {
    echo $time . "\t" . $token . PHP_EOL;
}
$apns-&gt;close();
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.mobile.push.apns.message"></a>50.2.3. Mensajes avanzados</h3></div></div></div>
<p>
            APNS ofrece la capacidad de enviar mensajes más avanzados; por
            ejemplo, los ejemplos anteriores muestran la implementación más básica de un
            mensaje. <code class="classname">Zend_Mobile_Push_Message_Apns</code>
            le permite hacer mensajes mucho más avanzados como se describe a continuación.
        </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.mobile.push.apns.message.alerts"></a>50.2.3.1. Alertas</h4></div></div></div>
<p>
                Las alertas pueden contener desde un simple mensaje de cuerpo hasta tener una
                clave de acción y una imagen de inicio (iOS 4). Es posible que solo desee proporcionar
                una clave de acción cuando solo se necesite una confirmación, O cuando
                busque localizar el botón con texto no estándar (es decir, no
                "View").
            </p>
<p>
                El siguiente ejemplo de código muestra alertas de los <a class="ulink" href="http://developer.apple.com/library/mac/#documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/ApplePushService/ApplePushService.html" target="_top">ejemplos
                de payload de APNS</a>.
            </p>
<pre class="programlisting">
    $message = new Zend_Mobile_Push_Message_Apns();

    // message with different button
    $message-&gt;setAlert('Bob wants to play poker', 'PLAY');
    // message using apps localized strings w/ string replacements
    $message-&gt;setAlert(null, null, 'GAME_PLAY_REQUEST_FORMAT', array('Jenna', 'Frank'));
    </pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.mobile.push.apns.message.custom-data"></a>50.2.3.2. Datos personalizados</h4></div></div></div>
<p>
                Puede enviar a su aplicación datos personalizados que le permiten tomar decisiones
                basadas en las notificaciones, como sincronizar datos.
            </p>
<pre class="programlisting">
                $message = new Zend_Mobile_Push_Message_Apns();
                $message-&gt;addCustomData('foo', 'bar');
                $message-&gt;addCustomData('foo', array('bar' =&gt; 1));
                $message-&gt;addCustomData('bar', 'foo');
</pre>
<div class="warning"><table border="0" summary="Warning">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Warning]" src="images/warning.png"></td>
<th align="left">Advertencia</th>
</tr>
<tr><td align="left" valign="top"><p>
                    No puede usar una clave personalizada 'aps' ya que está reservada por Apple y
                    se utiliza para los datos push principales.
                </p></td></tr>
</table></div>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mobile.push.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mobile.push.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mobile.push.gcm.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 50. Zend_Mobile_Push </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 50.3. Zend_Mobile_Push_Gcm</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
