<?php $title = '35.2. Clases de filtros estándar'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">35.2. Clases de filtros estándar</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.filter.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 35. Zend_Filter</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.filter.filter_chains.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.filter.set"></a>35.2. Clases de filtros estándar</h2></div></div></div>
<p>
        Zend Framework incluye un conjunto estándar de filtros, listos para que los uses.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.alnum"></a>35.2.1. Alnum</h3></div></div></div>
<p>
        <code class="classname">Zend_Filter_Alnum</code> es un filtro que devuelve únicamente caracteres
        alfabéticos y dígitos. Todos los demás caracteres son suprimidos.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.alnum.options"></a>35.2.1.1. Opciones soportadas para Zend_Filter_Alnum</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_Alnum</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allowwhitespace</span></em></span>: Si esta opción se
                    establece, entonces se permiten los caracteres de espacio en blanco. En caso contrario, son
                    suprimidos. Por defecto los espacios en blanco no están permitidos.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.alnum.basic"></a>35.2.1.2. Uso básico</h4></div></div></div>
<p>
            Vea el siguiente ejemplo del comportamiento por defecto de este filtro.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Alnum();
$return = $filter-&gt;filter('This is (my) content: 123');
// returns 'Thisismycontent123'
</pre>
<p>
            El ejemplo anterior devuelve 'Thisismycontent123'. Como puede ver, todos los espacios en blanco
            y también los paréntesis son filtrados.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                <code class="classname">Zend_Filter_Alnum</code> funciona en casi todos los idiomas. Pero en realidad
                hay tres excepciones: chino, japonés y coreano. Dentro de estos idiomas se usa el
                alfabeto inglés en lugar de los caracteres de estos idiomas. El idioma
                en sí se detecta usando <code class="classname">Zend_Locale</code>.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.alnum.whitespace"></a>35.2.1.3. Permitir espacios en blanco</h4></div></div></div>
<p>
            <code class="classname">Zend_Filter_Alnum</code> también puede permitir espacios en blanco. Esto puede ser útil
            cuando desea eliminar caracteres especiales de un texto. Vea el siguiente ejemplo:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Alnum(array('allowwhitespace' =&gt; true));
$return = $filter-&gt;filter('This is (my) content: 123');
// returns 'This is my content 123'
</pre>
<p>
            El ejemplo anterior devuelve 'This is my content 123'. Como puede ver, solo se filtran
            los paréntesis, mientras que los espacios en blanco no se ven afectados.
        </p>
<p>
            Para cambiar <span class="property">allowWhiteSpace</span> posteriormente puede usar
            <code class="methodname">setAllowWhiteSpace()</code> y
            <code class="methodname">getAllowWhiteSpace()</code>.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.alpha"></a>35.2.2. Alpha</h3></div></div></div>
<p>
        <code class="classname">Zend_Filter_Alpha</code> es un filtro que devuelve la cadena
        <code class="varname">$value</code>, eliminando todo excepto los caracteres alfabéticos. Este filtro incluye una
        opción para permitir también caracteres de espacio en blanco.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.alpha.options"></a>35.2.2.1. Opciones soportadas para Zend_Filter_Alpha</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_Alpha</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allowwhitespace</span></em></span>: Si esta opción se
                    establece, entonces se permiten los caracteres de espacio en blanco. En caso contrario, son
                    suprimidos. Por defecto los caracteres de espacio en blanco no están permitidos.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.alpha.basic"></a>35.2.2.2. Uso básico</h4></div></div></div>
<p>
            A continuación se muestra un ejemplo básico de uso:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Alpha();

print $filter-&gt;filter('This is (my) content: 123');
</pre>
<p>
            El ejemplo anterior devuelve 'Thisismycontent'. Observe que los caracteres de espacio en blanco y
            los paréntesis se eliminan.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                <code class="classname">Zend_Filter_Alpha</code> funciona en la mayoría de los idiomas; sin embargo, hay
                tres excepciones: chino, japonés y coreano. Con estos idiomas se usa el
                alfabeto inglés. El idioma se detecta mediante el uso de
                <code class="classname">Zend_Locale</code>.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.alpha.whitespace"></a>35.2.2.3. Permitir caracteres de espacio en blanco</h4></div></div></div>
<p>
            <code class="classname">Zend_Filter_Alpha</code> también puede permitir caracteres de espacio en blanco. Esto puede
            ser útil cuando desea eliminar caracteres especiales de una cadena. Vea el siguiente
            ejemplo:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Alpha(array('allowwhitespace' =&gt; true));

print $filter-&gt;filter('This is (my) content: 123');
</pre>
<p>
            El ejemplo anterior devuelve 'This is my content '. Observe que los paréntesis, los dos puntos y
            los números han sido eliminados, mientras que los caracteres de espacio en blanco permanecen.
        </p>
<p>
            Para cambiar <span class="property">allowWhiteSpace</span> después de la instanciación puede usarse el método
            <code class="methodname">setAllowWhiteSpace()</code>.
        </p>
<p>
            Para consultar el valor actual de <span class="property">allowWhiteSpace</span> puede usarse el método
            <code class="methodname">getAllowWhiteSpace()</code>.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.basename"></a>35.2.3. BaseName</h3></div></div></div>
<p>
        <code class="classname">Zend_Filter_BaseName</code> permite filtrar una cadena que contiene
        la ruta a un archivo, y devolverá el nombre base de ese archivo.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.basename.options"></a>35.2.3.1. Opciones soportadas para Zend_Filter_BaseName</h4></div></div></div>
<p>
            No hay opciones adicionales para <code class="classname">Zend_Filter_BaseName</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.basename.basic"></a>35.2.3.2. Uso básico</h4></div></div></div>
<p>
            A continuación se muestra un ejemplo básico de uso:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_BaseName();

print $filter-&gt;filter('/vol/tmp/filename');
</pre>
<p>
            Esto devolverá 'filename'.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_BaseName();

print $filter-&gt;filter('/vol/tmp/filename.txt');
</pre>
<p>
            Esto devolverá '<code class="filename">filename.txt</code>'.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.boolean"></a>35.2.4. Boolean</h3></div></div></div>
<p>
        Este filtro convierte una entrada dada en un valor <code class="constant">BOOLEAN</code>. Esto suele ser
        útil cuando se trabaja con bases de datos o al procesar valores de formularios.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.boolean.options"></a>35.2.4.1. Opciones soportadas para Zend_Filter_Boolean</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_Boolean</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">casting</span></em></span>: Cuando esta opción se establece en
                    <code class="constant">TRUE</code> cualquier entrada dada será convertida a booleano. Esta
                    opción por defecto es <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">locale</span></em></span>: Esta opción establece el idioma
                    que se usará para detectar entradas localizadas.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">type</span></em></span>: La opción <span class="property">type</span>
                    establece el tipo booleano que debe usarse. Lea lo siguiente para
                    más detalles.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.boolean.default"></a>35.2.4.2. Comportamiento por defecto de Zend_Filter_Boolean</h4></div></div></div>
<p>
            Por defecto, este filtro funciona convirtiendo la entrada a un valor
            <code class="constant">BOOLEAN</code>; en otras palabras, opera de forma similar a llamar a
            <span class="command"><strong>(boolean) $value</strong></span>.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Boolean();
$value  = '';
$result = $filter-&gt;filter($value);
// returns false
</pre>
<p>
            Esto significa que, sin proporcionar ninguna configuración,
            <code class="classname">Zend_Filter_Boolean</code> acepta todos los tipos de entrada y devuelve un
            <code class="constant">BOOLEAN</code> tal como se obtendría al convertir el tipo a
            <code class="constant">BOOLEAN</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.boolean.types"></a>35.2.4.3. Cambiar el comportamiento de Zend_Filter_Boolean</h4></div></div></div>
<p>
            A veces la conversión con <span class="command"><strong>(boolean)</strong></span> no será suficiente.
            <code class="classname">Zend_Filter_Boolean</code> le permite configurar tipos específicos a
            convertir, así como cuáles omitir.
        </p>
<p>
            Se pueden manejar los siguientes tipos:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>boolean</em></span>: Devuelve un valor booleano tal cual.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>integer</em></span>: Convierte un valor entero <span class="emphasis"><em>0</em></span>
                    a <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>float</em></span>: Convierte un valor flotante <span class="emphasis"><em>0.0</em></span>
                    a <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>string</em></span>: Convierte una cadena vacía <span class="emphasis"><em>''</em></span> a
                    <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>zero</em></span>: Convierte una cadena que contiene el único carácter
                    cero (<span class="emphasis"><em>'0'</em></span>) a <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>empty_array</em></span>: Convierte un <span class="emphasis"><em>array</em></span> vacío
                    a <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>null</em></span>: Convierte un valor <code class="constant">NULL</code>
                    a <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>php</em></span>: Convierte valores según lo hace <acronym class="acronym">PHP</acronym>
                    al convertirlos a <code class="constant">BOOLEAN</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>false_string</em></span>: Convierte una cadena que contiene la palabra "false"
                    a un booleano <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>yes</em></span>: Convierte una cadena localizada que contiene la palabra
                    "no" a <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>all</em></span>: Convierte todos los tipos anteriores a
                    <code class="constant">BOOLEAN</code>.
                </p></li>
</ul></div>
<p>
            Todos los demás valores dados devolverán <code class="constant">TRUE</code> por defecto.
        </p>
<p>
            Hay varias formas de seleccionar cuáles de los tipos anteriores se filtran. Puede indicar uno
            o varios tipos y sumarlos, puede dar un array, puede usar constantes, o puede
            dar una cadena de texto. Vea los siguientes ejemplos:
        </p>
<pre class="programlisting">
// converts 0 to false
$filter = new Zend_Filter_Boolean(Zend_Filter_Boolean::INTEGER);

// converts 0 and '0' to false
$filter = new Zend_Filter_Boolean(
    Zend_Filter_Boolean::INTEGER + Zend_Filter_Boolean::ZERO
);

// converts 0 and '0' to false
$filter = new Zend_Filter_Boolean(array(
    'type' =&gt; array(
        Zend_Filter_Boolean::INTEGER,
        Zend_Filter_Boolean::ZERO,
    ),
));

// converts 0 and '0' to false
$filter = new Zend_Filter_Boolean(array(
    'type' =&gt; array(
        'integer',
        'zero',
    ),
));
</pre>
<p>
            También puede dar una instancia de <code class="classname">Zend_Config</code> para establecer los tipos
            deseados. Para establecer los tipos después de la instanciación, use el método
            <code class="methodname">setType()</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.boolean.localized"></a>35.2.4.4. Booleanos localizados</h4></div></div></div>
<p>
            Como se mencionó anteriormente, <code class="classname">Zend_Filter_Boolean</code> también puede
            reconocer las cadenas localizadas "yes" y "no". Esto significa que puede preguntarle a su cliente en un
            formulario "sí" o "no" en su idioma nativo y
            <code class="classname">Zend_Filter_Boolean</code> convertirá la respuesta al valor booleano
            apropiado.
        </p>
<p>
            Para establecer el idioma deseado, puede usar la opción <span class="property">locale</span>, o
            el método <code class="methodname">setLocale()</code>.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Boolean(array(
    'type'   =&gt; Zend_Filter_Boolean::ALL,
    'locale' =&gt; 'de',
));

// returns false
echo $filter-&gt;filter('nein');

$filter-&gt;setLocale('en');

// returns true
$filter-&gt;filter('yes');
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.boolean.casting"></a>35.2.4.5. Desactivar la conversión</h4></div></div></div>
<p>
            A veces es necesario reconocer solo <code class="constant">TRUE</code> o
            <code class="constant">FALSE</code> y devolver todos los demás valores sin cambios.
            <code class="classname">Zend_Filter_Boolean</code> le permite hacer esto estableciendo la opción
            <span class="property">casting</span> en <code class="constant">FALSE</code>.
        </p>
<p>
            En este caso <code class="classname">Zend_Filter_Boolean</code> funcionará como se describe en la
            siguiente tabla, que muestra qué valores devuelven <code class="constant">TRUE</code> o
            <code class="constant">FALSE</code>. Todos los demás valores dados se devuelven sin cambios cuando
            <span class="property">casting</span> está establecido en <code class="constant">FALSE</code>
        </p>
<div class="table">
<a name="zend.filter.set.boolean.casting.table"></a><p class="title"><b>Tabla 35.1. Uso sin conversión</b></p>
<div class="table-contents"><table class="table" summary="Usage without casting" border="1">
<colgroup>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Tipo</th>
<th>Verdadero</th>
<th>Falso</th>
</tr></thead>
<tbody>
<tr>
<td><code class="constant">Zend_Filter_Boolean::BOOLEAN</code></td>
<td><code class="constant">TRUE</code></td>
<td><code class="constant">FALSE</code></td>
</tr>
<tr>
<td><code class="constant">Zend_Filter_Boolean::INTEGER</code></td>
<td>0</td>
<td>1</td>
</tr>
<tr>
<td><code class="constant">Zend_Filter_Boolean::FLOAT</code></td>
<td>0.0</td>
<td>1.0</td>
</tr>
<tr>
<td><code class="constant">Zend_Filter_Boolean::STRING</code></td>
<td>""</td>
<td> </td>
</tr>
<tr>
<td><code class="constant">Zend_Filter_Boolean::ZERO</code></td>
<td>"0"</td>
<td>"1"</td>
</tr>
<tr>
<td><code class="constant">Zend_Filter_Boolean::EMPTY_ARRAY</code></td>
<td><code class="methodname">array()</code></td>
<td> </td>
</tr>
<tr>
<td><code class="constant">Zend_Filter_Boolean::NULL</code></td>
<td><code class="constant">NULL</code></td>
<td> </td>
</tr>
<tr>
<td><code class="constant">Zend_Filter_Boolean::FALSE_STRING</code></td>
<td>"false" (sin distinción de mayúsculas)</td>
<td>"true" (sin distinción de mayúsculas)</td>
</tr>
<tr>
<td><code class="constant">Zend_Filter_Boolean::YES</code></td>
<td>"yes" localizado (sin distinción de mayúsculas)</td>
<td>"no" localizado (sin distinción de mayúsculas)</td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><p>
            El siguiente ejemplo muestra el comportamiento al cambiar la opción
            <span class="property">casting</span>:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Boolean(array(
    'type'    =&gt; Zend_Filter_Boolean::ALL,
    'casting' =&gt; false,
));

// returns false
echo $filter-&gt;filter(0);

// returns true
echo $filter-&gt;filter(1);

// returns the value
echo $filter-&gt;filter(2);
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.callback"></a>35.2.5. Callback</h3></div></div></div>
<p>
        Este filtro le permite usar sus propios métodos en conjunto con
        <code class="classname">Zend_Filter</code>. No tiene que crear un nuevo filtro cuando ya
        tiene un método que hace el trabajo.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.callback.options"></a>35.2.5.1. Opciones soportadas para Zend_Filter_Callback</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_Callback</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">callback</span></em></span>: Esto establece el callback
                    que debe usarse.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">options</span></em></span>: Esta propiedad establece las
                    opciones que se usan cuando se procesa el callback.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.callback.basic"></a>35.2.5.2. Uso básico</h4></div></div></div>
<p>
            El uso de este filtro es bastante simple. Supongamos que queremos crear un filtro que
            invierta una cadena.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Callback('strrev');

print $filter-&gt;filter('Hello!');
// returns "!olleH"
</pre>
<p>
            Como puede ver, es realmente simple usar un callback para definir un filtro propio. También es
            posible usar un método definido dentro de una clase, dando un array como
            callback.
        </p>
<pre class="programlisting">
// Our classdefinition
class MyClass
{
    public function Reverse($param);
}

// The filter definition
$filter = new Zend_Filter_Callback(array('MyClass', 'Reverse'));
print $filter-&gt;filter('Hello!');
</pre>
<p>
            Para obtener el callback establecido actualmente use <code class="methodname">getCallback()</code>, y para establecer
            otro callback use <code class="methodname">setCallback()</code>.
        </p>
<div class="note"><table border="0" summary="Note: Possible exceptions">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Posibles excepciones</th>
</tr>
<tr><td align="left" valign="top"><p>
                Debe tener en cuenta que definir un método de callback que no se pueda invocar generará
                una excepción.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.callback.parameters"></a>35.2.5.3. Parámetros por defecto dentro de un callback</h4></div></div></div>
<p>
            También es posible definir parámetros por defecto, que se pasan al método invocado
            como array cuando se ejecuta el filtro. Este array se concatenará con el valor
            que se va a filtrar.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Callback(
    array(
        'callback' =&gt; 'MyMethod',
        'options'  =&gt; array('key' =&gt; 'param1', 'key2' =&gt; 'param2')
    )
);
$filter-&gt;filter(array('value' =&gt; 'Hello'));
</pre>
<p>
            Cuando llamara manualmente a la definición del método anterior, se vería así:
        </p>
<pre class="programlisting">
$value = MyMethod('Hello', 'param1', 'param2');
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.compress"></a>35.2.6. Compress y Decompress</h3></div></div></div>
<p>
        Estos dos filtros son capaces de comprimir y descomprimir cadenas, archivos y
        directorios.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.options"></a>35.2.6.1. Opciones soportadas para Zend_Filter_Compress y Zend_Filter_Decompress</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_Compress</code>
            y <code class="classname">Zend_Filter_Decompress</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">adapter</span></em></span>: El adaptador de compresión que
                    debe usarse. Por defecto es <span class="property">Gz</span>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">options</span></em></span>: Opciones adicionales que se
                    pasan al adaptador en la inicialización. Cada adaptador soporta sus propias opciones.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.basic"></a>35.2.6.2. Adaptadores de compresión soportados</h4></div></div></div>
<p>
            Los siguientes formatos de compresión son soportados mediante su propio adaptador:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>Bz2</em></span>
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Gz</em></span>
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Lzf</em></span>
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Rar</em></span>
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Tar</em></span>
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Zip</em></span>
                </p></li>
</ul></div>
<p>
            Cada formato de compresión tiene diferentes capacidades, como se describe a continuación. Todos los filtros
            de compresión pueden usarse de formas aproximadamente iguales, y difieren principalmente en las opciones
            disponibles y el tipo de compresión que ofrecen (tanto algorítmicamente como en términos de cadena
            frente a archivo frente a directorio)
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.generic"></a>35.2.6.3. Manejo genérico</h4></div></div></div>
<p>
            Para crear un filtro de compresión necesita seleccionar el formato de compresión que quiere
            usar. La siguiente descripción toma el adaptador <span class="emphasis"><em>Bz2</em></span>. Los detalles de
            todos los demás adaptadores se describen después de esta sección.
        </p>
<p>
            Los dos filtros son básicamente idénticos, ya que utilizan los mismos backends.
            <code class="classname">Zend_Filter_Compress</code> debe usarse cuando desee comprimir
            elementos, y <code class="classname">Zend_Filter_Decompress</code> debe usarse cuando desee
            descomprimirlos.
        </p>
<p>
            Por ejemplo, si queremos comprimir una cadena, tenemos que inicializar
            <code class="classname">Zend_Filter_Compress</code> e indicar el adaptador deseado.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Compress('Bz2');
</pre>
<p>
            Para usar un adaptador diferente, simplemente lo especifica en el constructor.
        </p>
<p>
            También puede proporcionar un array de opciones o un objeto <code class="classname">Zend_Config</code>.
            Si lo hace, proporcione como mínimo la clave "adapter", y luego la clave "options" o
            "adapterOptions" (que debe ser un array de opciones para dar al adaptador en la
            instanciación).
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Compress(array(
    'adapter' =&gt; 'Bz2',
    'options' =&gt; array(
        'blocksize' =&gt; 8,
    ),
));
</pre>
<div class="note"><table border="0" summary="Note: Default compression Adapter">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Adaptador de compresión por defecto</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando no se proporciona ningún adaptador de compresión, se usará el adaptador <span class="emphasis"><em>Gz</em></span>.
            </p></td></tr>
</table></div>
<p>
            El uso es casi el mismo si queremos descomprimir una cadena. Simplemente debemos usar el
            filtro de descompresión en este caso.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Decompress('Bz2');
</pre>
<p>
            Para obtener la cadena comprimida, tenemos que dar la cadena original. El valor filtrado es
            la versión comprimida de la cadena original.
        </p>
<pre class="programlisting">
$filter     = new Zend_Filter_Compress('Bz2');
$compressed = $filter-&gt;filter('Uncompressed string');
// Returns the compressed string
</pre>
<p>
            La descompresión funciona de la misma manera.
        </p>
<pre class="programlisting">
$filter     = new Zend_Filter_Decompress('Bz2');
$compressed = $filter-&gt;filter('Compressed string');
// Returns the uncompressed string
</pre>
<div class="note"><table border="0" summary="Note: Note on string compression">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota sobre la compresión de cadenas</th>
</tr>
<tr><td align="left" valign="top"><p>
                No todos los adaptadores soportan la compresión de cadenas. Formatos de compresión como
                <span class="emphasis"><em>Rar</em></span> solo pueden manejar archivos y directorios. Para más detalles, consulte
                la sección del adaptador que desee usar.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.archive"></a>35.2.6.4. Crear un archivo comprimido</h4></div></div></div>
<p>
            Crear un archivo comprimido funciona casi igual que comprimir una cadena. Sin embargo, en este
            caso necesitamos un parámetro adicional que contenga el nombre del archivo que queremos
            crear.
        </p>
<pre class="programlisting">
$filter     = new Zend_Filter_Compress(array(
    'adapter' =&gt; 'Bz2',
    'options' =&gt; array(
        'archive' =&gt; 'filename.bz2',
    ),
));
$compressed = $filter-&gt;filter('Uncompressed string');
// Returns true on success and creates the archive file
</pre>
<p>
            En el ejemplo anterior la cadena sin comprimir se comprime, y luego se escribe en
            el archivo comprimido indicado.
        </p>
<div class="note"><table border="0" summary="Note: Existing archives will be overwritten">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Los archivos comprimidos existentes serán sobrescritos</th>
</tr>
<tr><td align="left" valign="top"><p>
                El contenido de cualquier archivo existente será sobrescrito cuando el nombre de archivo
                del archivo comprimido indicado ya exista.
            </p></td></tr>
</table></div>
<p>
            Cuando desee comprimir un archivo, debe dar el nombre del archivo con su ruta.
        </p>
<pre class="programlisting">
$filter     = new Zend_Filter_Compress(array(
    'adapter' =&gt; 'Bz2',
    'options' =&gt; array(
        'archive' =&gt; 'filename.bz2'
    ),
));
$compressed = $filter-&gt;filter('C:\temp\compressme.txt');
// Returns true on success and creates the archive file
</pre>
<p>
            También puede especificar un directorio en lugar de un nombre de archivo. En este caso todo el directorio
            con todos sus archivos y subdirectorios será comprimido en el archivo comprimido.
        </p>
<pre class="programlisting">
$filter     = new Zend_Filter_Compress(array(
    'adapter' =&gt; 'Bz2',
    'options' =&gt; array(
        'archive' =&gt; 'filename.bz2'
    ),
));
$compressed = $filter-&gt;filter('C:\temp\somedir');
// Returns true on success and creates the archive file
</pre>
<div class="note"><table border="0" summary="Note: Do not compress large or base directories">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">No comprima directorios grandes o base</th>
</tr>
<tr><td align="left" valign="top"><p>
                Nunca debe comprimir directorios grandes o base, como una partición completa.
                Comprimir una partición completa es una tarea que consume mucho tiempo y que puede llevar
                a problemas masivos en su servidor cuando no hay suficiente espacio o su
                script tarda demasiado tiempo.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.decompress"></a>35.2.6.5. Descomprimir un archivo comprimido</h4></div></div></div>
<p>
            Descomprimir un archivo comprimido funciona casi igual que comprimirlo. Debe especificar
            el parámetro <span class="property">archive</span>, o dar el nombre de archivo del archivo comprimido cuando
            descomprima el archivo.
        </p>
<pre class="programlisting">
$filter     = new Zend_Filter_Decompress('Bz2');
$compressed = $filter-&gt;filter('filename.bz2');
// Returns true on success and decompresses the archive file
</pre>
<p>
            Algunos adaptadores soportan descomprimir el archivo en otro subdirectorio. En este
            caso puede establecer el parámetro <span class="property">target</span>.
        </p>
<pre class="programlisting">
$filter     = new Zend_Filter_Decompress(array(
    'adapter' =&gt; 'Zip',
    'options' =&gt; array(
        'target' =&gt; 'C:\temp',
    )
));
$compressed = $filter-&gt;filter('filename.zip');
// Returns true on success and decompresses the archive file
// into the given target directory
</pre>
<div class="note"><table border="0" summary="Note: Directories to extract to must exist">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Los directorios de extracción deben existir</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando desee descomprimir un archivo comprimido en un directorio, ese directorio debe
                existir.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.bz2"></a>35.2.6.6. Adaptador Bz2</h4></div></div></div>
<p>
            El adaptador Bz2 puede comprimir y descomprimir:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Cadenas</p></li>
<li class="listitem"><p>Archivos</p></li>
<li class="listitem"><p>Directorios</p></li>
</ul></div>
<p>
            Este adaptador hace uso de la extensión Bz2 de <acronym class="acronym">PHP</acronym>.
        </p>
<p>
            Para personalizar la compresión, este adaptador soporta las siguientes opciones:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>Archive</em></span>: Este parámetro establece el archivo comprimido que debe
                    usarse o crearse.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Blocksize</em></span>: Este parámetro establece el tamaño de bloque a usar. Puede
                    ser de '0' a '9'. El valor por defecto es '4'.
                </p></li>
</ul></div>
<p>
            Todas las opciones se pueden establecer en la instanciación o usando un método relacionado. Por ejemplo, los
            métodos relacionados para 'Blocksize' son <code class="methodname">getBlocksize()</code> y
            <code class="methodname">setBlocksize()</code>. También puede usar el método
            <code class="methodname">setOptions()</code>, que acepta todas las opciones como array.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.gz"></a>35.2.6.7. Adaptador Gz</h4></div></div></div>
<p>
            El adaptador Gz puede comprimir y descomprimir:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Cadenas</p></li>
<li class="listitem"><p>Archivos</p></li>
<li class="listitem"><p>Directorios</p></li>
</ul></div>
<p>
            Este adaptador hace uso de la extensión Zlib de <acronym class="acronym">PHP</acronym>.
        </p>
<p>
            Para personalizar la compresión, este adaptador soporta las siguientes opciones:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>Archive</em></span>: Este parámetro establece el archivo comprimido que debe
                    usarse o crearse.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Level</em></span>: El nivel de compresión a usar. Puede ser de '0' a
                    '9'. El valor por defecto es '9'.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Mode</em></span>: Hay dos modos soportados. 'compress' y
                    'deflate'. El valor por defecto es 'compress'.
                </p></li>
</ul></div>
<p>
            Todas las opciones se pueden establecer en la inicialización o usando un método relacionado. Por ejemplo, los
            métodos relacionados para 'Level' son <code class="methodname">getLevel()</code> y
            <code class="methodname">setLevel()</code>. También puede usar el método
            <code class="methodname">setOptions()</code>, que acepta todas las opciones como array.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.lzf"></a>35.2.6.8. Adaptador Lzf</h4></div></div></div>
<p>
            El adaptador Lzf puede comprimir y descomprimir:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>Cadenas</p></li></ul></div>
<div class="note"><table border="0" summary="Note: Lzf supports only strings">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Lzf solo soporta cadenas</th>
</tr>
<tr><td align="left" valign="top"><p>
                El adaptador Lzf no puede manejar archivos ni directorios.
            </p></td></tr>
</table></div>
<p>
            Este adaptador hace uso de la extensión Lzf de <acronym class="acronym">PHP</acronym>.
        </p>
<p>
            No hay opciones disponibles para personalizar este adaptador.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.rar"></a>35.2.6.9. Adaptador Rar</h4></div></div></div>
<p>
            El adaptador Rar puede comprimir y descomprimir:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Archivos</p></li>
<li class="listitem"><p>Directorios</p></li>
</ul></div>
<div class="note"><table border="0" summary="Note: Rar does not support strings">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Rar no soporta cadenas</th>
</tr>
<tr><td align="left" valign="top"><p>
                El adaptador Rar no puede manejar cadenas.
            </p></td></tr>
</table></div>
<p>
            Este adaptador hace uso de la extensión Rar de <acronym class="acronym">PHP</acronym>.
        </p>
<div class="note"><table border="0" summary="Note: Rar compression not supported">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">La compresión Rar no está soportada</th>
</tr>
<tr><td align="left" valign="top"><p>
                Debido a restricciones con el formato de compresión Rar, no hay compresión
                disponible de forma gratuita. Cuando desee comprimir archivos en un nuevo archivo Rar, debe
                proporcionar un callback al adaptador que pueda invocar un programa de compresión Rar.
            </p></td></tr>
</table></div>
<p>
            Para personalizar la compresión, este adaptador soporta las siguientes opciones:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>Archive</em></span>: Este parámetro establece el archivo comprimido que debe
                    usarse o crearse.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Callback</em></span>: Un callback que proporciona soporte de compresión a
                    este adaptador.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Password</em></span>: La contraseña que debe usarse para
                    la descompresión.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Target</em></span>: El destino donde se escribirán los archivos
                    descomprimidos.
                </p></li>
</ul></div>
<p>
            Todas las opciones se pueden establecer en la instanciación o usando un método relacionado. Por ejemplo, los
            métodos relacionados para 'Target' son <code class="methodname">getTarget()</code> y
            <code class="methodname">setTarget()</code>. También puede usar el método
            <code class="methodname">setOptions()</code>, que acepta todas las opciones como array.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.tar"></a>35.2.6.10. Adaptador Tar</h4></div></div></div>
<p>
            El adaptador Tar puede comprimir y descomprimir:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Archivos</p></li>
<li class="listitem"><p>Directorios</p></li>
</ul></div>
<div class="note"><table border="0" summary="Note: Tar does not support strings">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Tar no soporta cadenas</th>
</tr>
<tr><td align="left" valign="top"><p>
                El adaptador Tar no puede manejar cadenas.
            </p></td></tr>
</table></div>
<p>
            Este adaptador hace uso del componente <code class="classname">Archive_Tar</code> de
            <acronym class="acronym">PEAR</acronym>.
        </p>
<p>
            Para personalizar la compresión, este adaptador soporta las siguientes opciones:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>Archive</em></span>: Este parámetro establece el archivo comprimido que debe
                    usarse o crearse.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Mode</em></span>: Un modo a usar para la compresión. Se soportan ya sea
                    '<code class="constant">NULL</code>' que significa ninguna compresión, 'Gz' que hace
                    uso de la extensión Zlib de <acronym class="acronym">PHP</acronym>, y 'Bz2' que hace uso de
                    la extensión Bz2 de <acronym class="acronym">PHP</acronym>. El valor por defecto es
                    '<code class="constant">NULL</code>'.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Target</em></span>: El destino donde se escribirán los archivos
                    descomprimidos.
                </p></li>
</ul></div>
<p>
            Todas las opciones se pueden establecer en la instanciación o usando un método relacionado. Por ejemplo, los
            métodos relacionados para 'Target' son <code class="methodname">getTarget()</code> y
            <code class="methodname">setTarget()</code>. También puede usar el método
            <code class="methodname">setOptions()</code>, que acepta todas las opciones como array.
        </p>
<div class="note"><table border="0" summary="Note: Directory usage">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Uso de directorios</th>
</tr>
<tr><td align="left" valign="top"><p>
                Al comprimir directorios con Tar se usa la ruta completa del archivo. Esto
                significa que los archivos Tar creados no solo tendrán el subdirectorio, sino la ruta
                completa del archivo comprimido.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.compress.zip"></a>35.2.6.11. Adaptador Zip</h4></div></div></div>
<p>
            El adaptador Zip puede comprimir y descomprimir:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>Cadenas</p></li>
<li class="listitem"><p>Archivos</p></li>
<li class="listitem"><p>Directorios</p></li>
</ul></div>
<div class="note"><table border="0" summary="Note: Zip does not support string decompression">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Zip no soporta descompresión a cadena</th>
</tr>
<tr><td align="left" valign="top"><p>
                El adaptador Zip no puede manejar la descompresión a una cadena; la descompresión
                siempre se escribirá en un archivo.
            </p></td></tr>
</table></div>
<p>
            Este adaptador hace uso de la extensión <code class="classname">Zip</code> de
            <acronym class="acronym">PHP</acronym>.
        </p>
<p>
            Para personalizar la compresión, este adaptador soporta las siguientes opciones:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>Archive</em></span>: Este parámetro establece el archivo comprimido que debe
                    usarse o crearse.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Target</em></span>: El destino donde se escribirán los archivos
                    descomprimidos.
                </p></li>
</ul></div>
<p>
            Todas las opciones se pueden establecer en la instanciación o usando un método relacionado. Por ejemplo, los
            métodos relacionados para 'Target' son <code class="methodname">getTarget()</code> y
            <code class="methodname">setTarget()</code>. También puede usar el método
            <code class="methodname">setOptions()</code>, que acepta todas las opciones como array.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.digits"></a>35.2.7. Digits</h3></div></div></div>
<p>
        Devuelve la cadena <code class="varname">$value</code>, eliminando todo excepto los dígitos.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.digits.options"></a>35.2.7.1. Opciones soportadas para Zend_Filter_Digits</h4></div></div></div>
<p>
            No hay opciones adicionales para <code class="classname">Zend_Filter_Digits</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.digits.basic"></a>35.2.7.2. Uso básico</h4></div></div></div>
<p>
            A continuación se muestra un ejemplo básico de uso:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Digits();

print $filter-&gt;filter('October 2009');
</pre>
<p>
            Esto devuelve "2009".
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Digits();

print $filter-&gt;filter('HTML 5 for Dummies');
</pre>
<p>
            Esto devuelve "5".
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.dir"></a>35.2.8. Dir</h3></div></div></div>
<p>
        Dada una cadena que contiene una ruta a un archivo, esta función devolverá el
        nombre del directorio.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.dir.options"></a>35.2.8.1. Opciones soportadas para Zend_Filter_Dir</h4></div></div></div>
<p>
            No hay opciones adicionales para <code class="classname">Zend_Filter_Dir</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.dir.basic"></a>35.2.8.2. Uso básico</h4></div></div></div>
<p>
            A continuación se muestra un ejemplo básico de uso:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Dir();

print $filter-&gt;filter('/etc/passwd');
</pre>
<p>
            Esto devuelve "<code class="filename">/etc</code>".
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Dir();

print $filter-&gt;filter('C:/Temp/x');
</pre>
<p>
            Esto devuelve "<code class="filename">C:/Temp</code>".
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.encrypt"></a>35.2.9. Encrypt y Decrypt</h3></div></div></div>
<p>
        Estos filtros permiten cifrar y descifrar cualquier cadena dada. Para ello hacen uso de
        adaptadores. Actualmente hay adaptadores para las extensiones <code class="classname">Mcrypt</code> y
        <code class="classname">OpenSSL</code> de <acronym class="acronym">PHP</acronym>.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.encrypt.options"></a>35.2.9.1. Opciones soportadas para Zend_Filter_Encrypt y Zend_Filter_Decrypt</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_Encrypt</code> y
            <code class="classname">Zend_Filter_Decrypt</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">adapter</span></em></span>: Esto establece el adaptador de
                    cifrado que debe usarse
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">algorithm</span></em></span>: Solo para
                    <code class="classname">MCrypt</code>. El algoritmo que debe usarse. Debería ser
                    uno de los cifrados de algoritmo que se pueden encontrar en
                    <a class="ulink" href="http://php.net/mcrypt" target="_top">los cifrados mcrypt de PHP</a>. Si no se establece,
                    por defecto es <span class="property">blowfish</span>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">algorithm_directory</span></em></span>: Solo para
                    <code class="classname">MCrypt</code>. El directorio donde se puede encontrar el
                    algoritmo. Si no se establece, por defecto es la ruta establecida dentro de la extensión mcrypt.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">compression</span></em></span>: Si el valor cifrado
                    debe comprimirse. Por defecto no hay compresión.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">envelope</span></em></span>: Solo para
                    <code class="classname">OpenSSL</code>. La clave de sobre cifrada del usuario que
                    cifró el contenido. Puede proporcionar la ruta y el nombre de archivo del archivo de clave, o simplemente
                    el contenido del archivo de clave en sí. Cuando se ha establecido la opción
                    <span class="property">package</span>, puede omitir este
                    parámetro.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">key</span></em></span>: Solo para
                    <code class="classname">MCrypt</code>. La clave de cifrado con la que se cifrará la entrada. Se
                    necesita la misma clave para el descifrado.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">mode</span></em></span>: Solo para
                    <code class="classname">MCrypt</code>. El modo de cifrado que debe usarse. Debería
                    ser uno de los modos que se pueden encontrar en
                    <a class="ulink" href="http://php.net/mcrypt" target="_top">los modos mcrypt de PHP</a>. Si no se establece,
                    por defecto es 'cbc'.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">mode_directory</span></em></span>: Solo para
                    <code class="classname">MCrypt</code>. El directorio donde se puede encontrar el modo.
                    Si no se establece, por defecto es la ruta establecida dentro de la extensión <code class="classname">Mcrypt</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">package</span></em></span>: Solo para
                    <code class="classname">OpenSSL</code>. Si la clave de sobre debe empaquetarse con el
                    valor cifrado. Por defecto es <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">private</span></em></span>: Solo para
                    <code class="classname">OpenSSL</code>. Su clave privada que se usará para
                    cifrar el contenido. La clave privada también puede ser un nombre de archivo con ruta
                    del archivo de clave, o simplemente el contenido del archivo de clave en sí.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">public</span></em></span>: Solo para
                    <code class="classname">OpenSSL</code>. La clave pública del usuario al que quiere
                    proporcionar el contenido cifrado. Puede dar varias claves públicas usando un
                    array. Puede proporcionar la ruta y el nombre de archivo del archivo de clave, o simplemente
                    el contenido del archivo de clave en sí.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">salt</span></em></span>: Solo para
                    <code class="classname">MCrypt</code>. Si la clave debe usarse como valor de sal. La clave
                    usada para el cifrado entonces también se cifrará. Por defecto es
                    <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">vector</span></em></span>: Solo para
                    <code class="classname">MCrypt</code>. El vector de inicialización que se usará. Si
                    no se establece, será un vector aleatorio.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.encrypt.adapterusage"></a>35.2.9.2. Uso de adaptadores</h4></div></div></div>
<p>
            Como estas dos metodologías de cifrado funcionan de forma completamente diferente, el uso de los
            adaptadores también difiere. Tiene que seleccionar el adaptador que quiere usar al
            inicializar el filtro.
        </p>
<pre class="programlisting">
// Use the Mcrypt adapter
$filter1 = new Zend_Filter_Encrypt(array('adapter' =&gt; 'mcrypt'));

// Use the OpenSSL adapter
$filter2 = new Zend_Filter_Encrypt(array('adapter' =&gt; 'openssl'));
</pre>
<p>
            Para establecer otro adaptador también puede usar <code class="methodname">setAdapter()</code>, y el
            método <code class="methodname">getAdapter()</code> para obtener el adaptador establecido actualmente.
        </p>
<pre class="programlisting">
// Use the Mcrypt adapter
$filter = new Zend_Filter_Encrypt();
$filter-&gt;setAdapter('openssl');
</pre>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando no proporciona la opción <span class="property">adapter</span> ni usa
                <code class="methodname">setAdapter()</code>, se usará el adaptador <code class="classname">Mcrypt</code>
                por defecto.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.encrypt.mcrypt"></a>35.2.9.3. Cifrado con Mcrypt</h4></div></div></div>
<p>
            Cuando ha instalado la extensión <code class="classname">Mcrypt</code> puede usar el
            adaptador <code class="classname">Mcrypt</code>. Si proporciona una cadena en lugar de un array de
            opciones, esta cadena se usará como clave.
        </p>
<p>
            También puede obtener y establecer los valores de cifrado posteriormente con los métodos
            <code class="methodname">getEncryption()</code> y <code class="methodname">setEncryption()</code>.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que obtendrá una excepción si la extensión mcrypt no está disponible en su
                entorno.
            </p></td></tr>
</table></div>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                También debe tener en cuenta que todos los ajustes se comprobarán al crear la instancia
                o al llamar a <code class="methodname">setEncryption()</code>. Si mcrypt detecta un problema
                con sus ajustes, se lanzará una excepción.
            </p></td></tr>
</table></div>
<p>
            Puede obtener o establecer el vector de cifrado llamando a <code class="methodname">getVector()</code>
            y <code class="methodname">setVector()</code>. Una cadena dada se truncará o rellenará hasta
            el tamaño de vector necesario del algoritmo usado.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que cuando no está usando un vector propio, debe obtener el vector y
                almacenarlo. De lo contrario no podrá decodificar la cadena codificada.
            </p></td></tr>
</table></div>
<pre class="programlisting">
// Use the default blowfish settings
$filter = new Zend_Filter_Encrypt('myencryptionkey');

// Set a own vector, otherwise you must call getVector()
// and store this vector for later decryption
$filter-&gt;setVector('myvector');
// $filter-&gt;getVector();

$encrypted = $filter-&gt;filter('text_to_be_encoded');
print $encrypted;

// For decryption look at the Decrypt filter
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.encrypt.mcryptdecrypt"></a>35.2.9.4. Descifrado con Mcrypt</h4></div></div></div>
<p>
            Para descifrar contenido que fue previamente cifrado con <code class="classname">Mcrypt</code>
            necesita tener las opciones con las que se llamó al cifrado.
        </p>
<p>
            Hay una diferencia notable para usted. Cuando no proporcionó un vector en el
            cifrado, necesita obtenerlo después de cifrar el contenido usando el
            método <code class="methodname">getVector()</code> en el filtro de cifrado. Sin el
            vector correcto no podrá descifrar el contenido.
        </p>
<p>
            En cuanto haya proporcionado todas las opciones, el descifrado es tan simple como el cifrado.
        </p>
<pre class="programlisting">
// Use the default blowfish settings
$filter = new Zend_Filter_Decrypt('myencryptionkey');

// Set the vector with which the content was encrypted
$filter-&gt;setVector('myvector');

$decrypted = $filter-&gt;filter('encoded_text_normally_unreadable');
print $decrypted;
</pre>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que obtendrá una excepción si la extensión mcrypt no está disponible en su
                entorno.
            </p></td></tr>
</table></div>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                También debe tener en cuenta que todos los ajustes se comprobarán al crear la instancia
                o al llamar a <code class="methodname">setEncryption()</code>. Si mcrypt detecta un problema
                con sus ajustes, se lanzará una excepción.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.encrypt.openssl"></a>35.2.9.5. Cifrado con OpenSSL</h4></div></div></div>
<p>
            Cuando ha instalado la extensión <code class="classname">OpenSSL</code> puede usar el
            adaptador <code class="classname">OpenSSL</code>. Puede obtener o establecer las claves públicas
            posteriormente con los métodos <code class="methodname">getPublicKey()</code> y
            <code class="methodname">setPublicKey()</code>. La clave privada también se puede obtener y establecer
            con los métodos relacionados <code class="methodname">getPrivateKey()</code> y
            <code class="methodname">setPrivateKey()</code>.
        </p>
<pre class="programlisting">
// Use openssl and provide a private key
$filter = new Zend_Filter_Encrypt(array(
    'adapter' =&gt; 'openssl',
    'private' =&gt; '/path/to/mykey/private.pem'
));

// of course you can also give the public keys at initiation
$filter-&gt;setPublicKey(array(
    '/public/key/path/first.pem',
    '/public/key/path/second.pem'
));
</pre>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que el adaptador <code class="classname">OpenSSL</code> no funcionará si no
                proporciona claves válidas.
            </p></td></tr>
</table></div>
<p>
            Cuando también quiera codificar las claves, debe proporcionar una frase de paso con el
            método <code class="methodname">setPassphrase()</code>. Cuando quiera decodificar contenido que
            fue codificado con una frase de paso, no solo necesitará la clave pública, sino también la
            frase de paso para decodificar la clave cifrada.
        </p>
<pre class="programlisting">
// Use openssl and provide a private key
$filter = new Zend_Filter_Encrypt(array(
    'adapter' =&gt; 'openssl',
    'private' =&gt; '/path/to/mykey/private.pem'
));

// of course you can also give the public keys at initiation
$filter-&gt;setPublicKey(array(
    '/public/key/path/first.pem',
    '/public/key/path/second.pem'
));
$filter-&gt;setPassphrase('mypassphrase');
</pre>
<p>
            Por último, cuando use OpenSSL necesita dar al receptor el contenido cifrado, la
            frase de paso cuando haya proporcionado una, y las claves de sobre para el descifrado.
        </p>
<p>
            Esto significa que tiene que obtener las claves de sobre después del cifrado con el
            método <code class="methodname">getEnvelopeKey()</code>.
        </p>
<p>
            Así que nuestro ejemplo completo para cifrar contenido con <code class="classname">OpenSSL</code> se
            ve así.
        </p>
<pre class="programlisting">
// Use openssl and provide a private key
$filter = new Zend_Filter_Encrypt(array(
    'adapter' =&gt; 'openssl',
    'private' =&gt; '/path/to/mykey/private.pem'
));

// of course you can also give the public keys at initiation
$filter-&gt;setPublicKey(array(
    '/public/key/path/first.pem',
    '/public/key/path/second.pem'
));
$filter-&gt;setPassphrase('mypassphrase');

$encrypted = $filter-&gt;filter('text_to_be_encoded');
$envelope  = $filter-&gt;getEnvelopeKey();
print $encrypted;

// For decryption look at the Decrypt filter
</pre>
<div class="sect4">
<div class="titlepage"><div><div><h5 class="title">
<a name="zend.filter.set.encrypt.openssl.simplified"></a>35.2.9.5.1. Uso simplificado con Openssl</h5></div></div></div>
<p>
                Como se vio antes, necesita obtener la clave de sobre para poder descifrar el valor
                cifrado anteriormente. Esto puede ser muy molesto cuando trabaja con múltiples valores.
            </p>
<p>
                Para tener un uso simplificado puede establecer la opción <span class="property">package</span> en
                <code class="constant">TRUE</code>. El valor por defecto es <code class="constant">FALSE</code>.
            </p>
<pre class="programlisting">
// Use openssl and provide a private key
$filter = new Zend_Filter_Encrypt(array(
    'adapter' =&gt; 'openssl',
    'private' =&gt; '/path/to/mykey/private.pem',
    'public'  =&gt; '/public/key/path/public.pem',
    'package' =&gt; true
));

$encrypted = $filter-&gt;filter('text_to_be_encoded');
print $encrypted;

// For decryption look at the Decrypt filter
</pre>
<p>
                Ahora el valor devuelto contiene el valor cifrado y el sobre. No necesita
                obtenerlos después de la compresión. Pero, y este es el aspecto negativo de
                esta característica, el valor cifrado ahora solo se puede descifrar usando
                <code class="classname">Zend_Filter_Encrypt</code>.
            </p>
</div>
<div class="sect4">
<div class="titlepage"><div><div><h5 class="title">
<a name="zend.filter.set.encrypt.openssl.compressed"></a>35.2.9.5.2. Comprimir el contenido</h5></div></div></div>
<p>
                Según el valor original, el valor cifrado puede ser una cadena muy grande. Para
                reducir el valor, <code class="classname">Zend_Filter_Encrypt</code> permite el uso de
                compresión.
            </p>
<p>
                La opción <span class="property">compression</span> puede establecerse ya sea con el nombre de un
                adaptador de compresión, o con un array que establezca todas las opciones deseadas para el
                adaptador de compresión.
            </p>
<pre class="programlisting">
// Use basic compression adapter
$filter1 = new Zend_Filter_Encrypt(array(
    'adapter'     =&gt; 'openssl',
    'private'     =&gt; '/path/to/mykey/private.pem',
    'public'      =&gt; '/public/key/path/public.pem',
    'package'     =&gt; true,
    'compression' =&gt; 'bz2'
));

// Use basic compression adapter
$filter2 = new Zend_Filter_Encrypt(array(
    'adapter'     =&gt; 'openssl',
    'private'     =&gt; '/path/to/mykey/private.pem',
    'public'      =&gt; '/public/key/path/public.pem',
    'package'     =&gt; true,
    'compression' =&gt; array('adapter' =&gt; 'zip', 'target' =&gt; '\usr\tmp\tmp.zip')
));
</pre>
<div class="note"><table border="0" summary="Note: Decryption with same settings">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Descifrado con los mismos ajustes</th>
</tr>
<tr><td align="left" valign="top"><p>
                    Cuando quiera descifrar un valor que además está comprimido, necesita
                    establecer los mismos ajustes de compresión para el descifrado que para el cifrado.
                    De lo contrario el descifrado fallará.
                </p></td></tr>
</table></div>
</div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.encrypt.openssldecrypt"></a>35.2.9.6. Descifrado con OpenSSL</h4></div></div></div>
<p>
            El descifrado con <code class="classname">OpenSSL</code> es tan simple como el cifrado. Pero necesita
            tener todos los datos de la persona que cifró el contenido. Vea el siguiente ejemplo:
        </p>
<pre class="programlisting">
// Use openssl and provide a private key
$filter = new Zend_Filter_Decrypt(array(
    'adapter' =&gt; 'openssl',
    'private' =&gt; '/path/to/mykey/private.pem'
));

// of course you can also give the envelope keys at initiation
$filter-&gt;setEnvelopeKey(array(
    '/key/from/encoder/first.pem',
    '/key/from/encoder/second.pem'
));
</pre>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que el adaptador <code class="classname">OpenSSL</code> no funcionará si no
                proporciona claves válidas.
            </p></td></tr>
</table></div>
<p>
            Opcionalmente podría ser necesario proporcionar la frase de paso para descifrar las claves
            en sí mediante el método <code class="methodname">setPassphrase()</code>.
        </p>
<pre class="programlisting">
// Use openssl and provide a private key
$filter = new Zend_Filter_Decrypt(array(
    'adapter' =&gt; 'openssl',
    'private' =&gt; '/path/to/mykey/private.pem'
));

// of course you can also give the envelope keys at initiation
$filter-&gt;setEnvelopeKey(array(
    '/key/from/encoder/first.pem',
    '/key/from/encoder/second.pem'
));
$filter-&gt;setPassphrase('mypassphrase');
</pre>
<p>
            Por último, decodifique el contenido. Nuestro ejemplo completo para descifrar el contenido
            previamente cifrado se ve así.
        </p>
<pre class="programlisting">
// Use openssl and provide a private key
$filter = new Zend_Filter_Decrypt(array(
    'adapter' =&gt; 'openssl',
    'private' =&gt; '/path/to/mykey/private.pem'
));

// of course you can also give the envelope keys at initiation
$filter-&gt;setEnvelopeKey(array(
    '/key/from/encoder/first.pem',
    '/key/from/encoder/second.pem'
));
$filter-&gt;setPassphrase('mypassphrase');

$decrypted = $filter-&gt;filter('encoded_text_normally_unreadable');
print $decrypted;
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.htmlentities"></a>35.2.10. HtmlEntities</h3></div></div></div>
<p>
        Devuelve la cadena <code class="varname">$value</code>, convirtiendo los caracteres a sus
        equivalentes de entidades <acronym class="acronym">HTML</acronym> correspondientes cuando existen.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.htmlentities.options"></a>35.2.10.1. Opciones soportadas para Zend_Filter_HtmlEntities</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_HtmlEntities</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">quotestyle</span></em></span>: Equivalente al
                    parámetro nativo <span class="emphasis"><em>quote_style</em></span> de la función htmlentities de
                    <acronym class="acronym">PHP</acronym>. Esto le permite definir qué se hará
                    con las comillas 'simples' y "dobles". Se aceptan las siguientes constantes:

                    <code class="constant">ENT_COMPAT</code>, <code class="constant">ENT_QUOTES</code>
                    <code class="constant">ENT_NOQUOTES</code>, siendo el valor por defecto
                    <code class="constant">ENT_COMPAT</code>.
                </p></li>
<li class="listitem">
<p>
                    <span class="emphasis"><em><span class="property">charset</span></em></span>: Equivalente al
                    parámetro nativo <span class="emphasis"><em>charset</em></span> de la función htmlentities de
                    <acronym class="acronym">PHP</acronym>. Esto define el conjunto de caracteres que se usará en el
                    filtrado. A diferencia de la función nativa de <acronym class="acronym">PHP</acronym>, el valor por defecto es
                    'UTF-8'. Vea "http://php.net/htmlentities" para una lista de conjuntos de caracteres
                    soportados.
                </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                     Esta opción también se puede establecer mediante el parámetro <code class="varname">$options</code> como
                     un objeto <code class="classname">Zend_Config</code> o array. La clave de opción se
                     aceptará ya sea como charset o encoding.
                    </p></td></tr>
</table></div>
</li>
<li class="listitem">
<p>
                    <span class="emphasis"><em><span class="property">doublequote</span></em></span>: Equivalente al
                    parámetro nativo <span class="emphasis"><em>double_encode</em></span> de la función htmlentities de
                    <acronym class="acronym">PHP</acronym>. Si se establece en false, las entidades html existentes
                    no se codificarán. Por defecto se convierte todo (true).
                </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                        Esta opción debe establecerse mediante el parámetro <code class="varname">$options</code> o el
                        método <code class="methodname">setDoubleEncode()</code>.
                    </p></td></tr>
</table></div>
</li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.htmlentities.basic"></a>35.2.10.2. Uso básico</h4></div></div></div>
<p>
            Vea el siguiente ejemplo del comportamiento por defecto de este filtro.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_HtmlEntities();

print $filter-&gt;filter('&lt;');
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.htmlentities.quotestyle"></a>35.2.10.3. Estilo de comillas</h4></div></div></div>
<p>
            <code class="classname">Zend_Filter_HtmlEntities</code> permite cambiar el estilo de comillas usado.
            Esto puede ser útil cuando desea dejar sin filtrar las comillas dobles, simples o de ambos
            tipos. Vea el siguiente ejemplo:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_HtmlEntities(array('quotestyle' =&gt; ENT_QUOTES));

$input  = "A 'single' and " . '"double"';
print $filter-&gt;filter($input);
</pre>
<p>
            El ejemplo anterior devuelve
            <span class="emphasis"><em>A 'single' and "double"</em></span>. Observe que las comillas 'simples'
            así como las "dobles" se filtran.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_HtmlEntities(array('quotestyle' =&gt; ENT_COMPAT));

$input  = "A 'single' and " . '"double"';
print $filter-&gt;filter($input);
</pre>
<p>
            El ejemplo anterior devuelve <span class="emphasis"><em>A 'single' and "double"</em></span>.
            Observe que las comillas "dobles" se filtran mientras que las 'simples' no se ven alteradas.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_HtmlEntities(array('quotestyle' =&gt; ENT_NOQUOTES));

$input  = "A 'single' and " . '"double"';
print $filter-&gt;filter($input);
</pre>
<p>
            El ejemplo anterior devuelve <span class="emphasis"><em>A 'single' and "double"</em></span>. Observe que
            ni las comillas "dobles" ni las 'simples' se ven alteradas.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.htmlentities."></a>35.2.10.4. Métodos auxiliares</h4></div></div></div>
<p>
            Para cambiar u obtener el <span class="property">quotestyle</span> después de la instanciación, se pueden
            usar respectivamente los dos métodos <code class="methodname">setQuoteStyle()</code> y
            <code class="methodname">getQuoteStyle()</code>.
            <code class="methodname">setQuoteStyle()</code> acepta un parámetro
            <code class="varname">$quoteStyle</code>. Se aceptan las siguientes constantes:
            <code class="constant">ENT_COMPAT</code>, <code class="constant">ENT_QUOTES</code>,
            <code class="constant">ENT_NOQUOTES</code>
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_HtmlEntities();

$filter-&gt;setQuoteStyle(ENT_QUOTES);
print $filter-&gt;getQuoteStyle(ENT_QUOTES);
</pre>
<p>
            Para cambiar u obtener el <span class="property">charset</span> después de la instanciación, se pueden
            usar respectivamente los dos métodos <code class="methodname">setCharSet()</code> y <code class="methodname">getCharSet()</code>.
            <code class="methodname">setCharSet()</code> acepta un parámetro
            <code class="varname">$charSet</code>. Vea "http://php.net/htmlentities" para una lista de
            conjuntos de caracteres soportados.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_HtmlEntities();

$filter-&gt;setQuoteStyle(ENT_QUOTES);
print $filter-&gt;getQuoteStyle(ENT_QUOTES);
</pre>
<p>
            Para cambiar u obtener la opción <span class="property">doublequote</span> después de la instanciación,
            se pueden usar respectivamente los dos métodos <code class="methodname">setDoubleQuote()</code> y
            <code class="methodname">getDoubleQuote()</code>.
            <code class="methodname">setDoubleQuote()</code> acepta un parámetro booleano
            <code class="varname">$doubleQuote</code>.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_HtmlEntities();

$filter-&gt;setQuoteStyle(ENT_QUOTES);
print $filter-&gt;getQuoteStyle(ENT_QUOTES);
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.int"></a>35.2.11. Int</h3></div></div></div>
<p>
        <code class="classname">Zend_Filter_Int</code> le permite transformar un valor escalar que contiene
        en un entero.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.int.options"></a>35.2.11.1. Opciones soportadas para Zend_Filter_Int</h4></div></div></div>
<p>
            No hay opciones adicionales para <code class="classname">Zend_Filter_Int</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.int.basic"></a>35.2.11.2. Uso básico</h4></div></div></div>
<p>
            A continuación se muestra un ejemplo básico de uso:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Int();

print $filter-&gt;filter('-4 is less than 0');
</pre>
<p>
            Esto devolverá '-4'.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.localizedtonormalized"></a>35.2.12. LocalizedToNormalized y NormalizedToLocalized</h3></div></div></div>
<p>
        Estos dos filtros pueden cambiar una entrada localizada dada a su representación normalizada y
        viceversa. Usan internamente <code class="classname">Zend_Locale</code> para hacer esta transformación
        por usted.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.localizedtonormalized.options"></a>35.2.12.1.
            Opciones soportadas para Zend_Filter_LocalizedToNormalized y
            Zend_Filter_NormalizedToLocalized
        </h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para
            <code class="classname">Zend_Filter_LocalizedToNormalized</code> y
            <code class="classname">Zend_Filter_NormalizedToLocalized</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">date_format</span></em></span>: Esto establece el formato de fecha
                    a usar para la normalización y para detectar el formato de fecha localizado
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">locale</span></em></span>: Esto establece el idioma a usar
                    para la normalización y para detectar el formato localizado
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">precision</span></em></span>: Esto establece la precisión a
                    usar para la conversión de números
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.localizedtonormalized.workflow"></a>35.2.12.2. Flujo de trabajo</h4></div></div></div>
<p>
            La normalización permite a su usuario introducir información en la notación de su propio
            idioma, y luego puede almacenar el valor normalizado en su base de datos, por ejemplo. La localización,
            por otro lado, le permite mostrar información normalizada de forma localizada
            a su usuario.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que la normalización y la localización no son lo mismo que la traducción. Estos
                filtros no pueden traducir cadenas de un idioma a otro como cabría
                esperar con los meses o los nombres de los días.
            </p></td></tr>
</table></div>
<p>
            Los siguientes tipos de entrada pueden normalizarse y localizarse:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>integer</em></span>: Números enteros. La normalización devuelve la notación
                    inglesa
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>float</em></span>: Números flotantes. La normalización devuelve la notación
                    inglesa
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>numbers</em></span>: Otros números, como los reales. La normalización devuelve
                    la notación inglesa
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>time</em></span>: Valores de hora. El valor normalizado es un array con claves
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>date</em></span>: Valores de fecha. El valor normalizado es un array con claves
                </p></li>
</ul></div>
<p>
            Cualquier otra entrada se devolverá tal cual, sin modificarla.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que la salida normalizada siempre se da como cadena. De lo contrario su
                entorno transferiría automáticamente la salida normalizada a la notación usada
                por el idioma en el que está configurado su entorno.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.localizedtonormalized.numbersnormal"></a>35.2.12.3. Normalización de números</h4></div></div></div>
<p>
            Cualquier número dado, como entero, flotante o real, puede normalizarse. Tenga en cuenta que
            los números en notación científica en realidad no pueden ser manejados por este filtro.
        </p>
<p>
            Así que veamos en detalle cómo funciona esta normalización para números:
        </p>
<pre class="programlisting">
// Initiate the filter
$filter = new Zend_Filter_LocalizedToNormalized();
$filter-&gt;filter('123.456,78');
// returns the value '123456.78'
</pre>
<p>
            Supongamos que ha establecido el idioma 'de' como idioma de aplicación en general.
            <code class="classname">Zend_Filter_LocalizedToNormalized</code> tomará el idioma establecido y
            lo usará para detectar qué tipo de entrada dio usted. En nuestro ejemplo era un valor con
            precisión. Ahora el filtro le devolverá la representación normalizada de este valor
            como cadena.
        </p>
<p>
            También puede controlar cómo debe verse su número normalizado. Para ello puede dar
            todas las opciones que también usa <code class="classname">Zend_Locale_Format</code>. Para
            más detalles sobre las opciones disponibles, eche un vistazo a este
            <a class="link" href="zend.locale.parsing.phtml" title="43.3. Normalization and Localization">capítulo de Zend_Locale</a>.
        </p>
<p>
            A continuación hay un ejemplo con precisión definida para que pueda ver cómo funcionan las opciones:
        </p>
<pre class="programlisting">
// Numeric Filter
$filter = new Zend_Filter_LocalizedToNormalized(array('precision' =&gt; 2));

$filter-&gt;filter('123.456');
// returns the value '123456.00'

$filter-&gt;filter('123.456,78901');
// returns the value '123456.79'
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.localizedtonormalized.dates"></a>35.2.12.4. Normalización de fecha y hora</h4></div></div></div>
<p>
            Las entradas de fecha y hora también pueden normalizarse. Todos los valores de fecha y hora dados
            se devolverán como array, donde cada parte de la fecha se da dentro de su propia clave.
        </p>
<pre class="programlisting">
// Initiate the filter
$filter = new Zend_Filter_LocalizedToNormalized();
$filter-&gt;filter('12.April.2009');
// returns array('day' =&gt; '12', 'month' =&gt; '04', 'year' =&gt; '2009')
</pre>
<p>
            Supongamos que ha establecido el idioma 'de' de nuevo. Ahora la entrada se detecta automáticamente
            como fecha, y obtendrá un array con claves como resultado.
        </p>
<p>
            Por supuesto, también puede controlar cómo se ve su entrada de fecha con las
            opciones <span class="emphasis"><em>date_format</em></span> y <span class="emphasis"><em>locale</em></span>.
        </p>
<pre class="programlisting">
// Date Filter
$filter = new Zend_Filter_LocalizedToNormalized(
    array('date_format' =&gt; 'ss:mm:HH')
);

$filter-&gt;filter('11:22:33');
// returns array('hour' =&gt; '33', 'minute' =&gt; '22', 'second' =&gt; '11')
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.localizedtonormalized.numberslocal"></a>35.2.12.5. Localización de números</h4></div></div></div>
<p>
            Cualquier número dado, como entero, flotante o real, puede localizarse. Tenga en cuenta que
            los números en notación científica en realidad no pueden ser manejados por este filtro.
        </p>
<p>
            Así que veamos en detalle cómo funciona la localización para números:
        </p>
<pre class="programlisting">
// Initiate the filter
$filter = new Zend_Filter_NormalizedToLocalized();
$filter-&gt;filter(123456.78);
// returns the value '123.456,78'
</pre>
<p>
            Supongamos que ha establecido el idioma 'de' como idioma de aplicación en general.
            <code class="classname">Zend_Filter_NormalizedToLocalized</code> tomará el idioma establecido y
            lo usará para detectar qué tipo de salida quiere obtener. En nuestro ejemplo era un valor
            con precisión. Ahora el filtro le devolverá la representación localizada de este
            valor como cadena.
        </p>
<p>
            También puede controlar cómo debe verse su número localizado. Para ello puede dar
            todas las opciones que también usa <code class="classname">Zend_Locale_Format</code>. Para
            detalles sobre cómo se usan estas opciones, eche un vistazo a este
            <a class="link" href="zend.locale.parsing.phtml" title="43.3. Normalization and Localization">capítulo de Zend_Locale</a>.
        </p>
<p>
            A continuación hay un ejemplo con precisión definida para que pueda ver cómo
            funcionan las opciones:
        </p>
<pre class="programlisting">
// Numeric Filter
$filter = new Zend_Filter_NormalizedToLocalized(array('precision' =&gt; 2));

$filter-&gt;filter(123456);
// returns the value '123.456,00'

$filter-&gt;filter(123456.78901);
// returns the value '123.456,79'
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.normalizedtolocalized.dates"></a>35.2.12.6. Localización de fecha y hora</h4></div></div></div>
<p>
            Los valores normalizados de fecha y hora también pueden localizarse. Todos los valores de fecha y hora
            dados se devolverán como cadena, con el formato definido por el idioma establecido.
        </p>
<pre class="programlisting">
// Initiate the filter
$filter = new Zend_Filter_NormalizedToLocalized();
$filter-&gt;filter(array('day' =&gt; '12', 'month' =&gt; '04', 'year' =&gt; '2009');
// returns '12.04.2009'
</pre>
<p>
            Supongamos que ha establecido el idioma 'de' de nuevo. Ahora la entrada se detecta automáticamente
            como fecha, y se devolverá en el formato definido por el idioma 'de'.
        </p>
<p>
            Por supuesto, también puede controlar cómo se ve su entrada de fecha con las
            opciones <span class="emphasis"><em>date_format</em></span> y <span class="emphasis"><em>locale</em></span>.
        </p>
<pre class="programlisting">
// Date Filter
$filter = new Zend_Filter_LocalizedToNormalized(
    array('date_format' =&gt; 'ss:mm:HH')
);

$filter-&gt;filter(array('hour' =&gt; '33', 'minute' =&gt; '22', 'second' =&gt; '11'));
// returns '11:22:33'
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.null"></a>35.2.13. Null</h3></div></div></div>
<p>
        Este filtro cambia la entrada dada a <code class="constant">NULL</code> si cumple criterios
        específicos. Esto suele ser necesario cuando se trabaja con bases de datos y se desea tener un
        valor <code class="constant">NULL</code> en lugar de un booleano o cualquier otro tipo.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.null.options"></a>35.2.13.1. Opciones soportadas para Zend_Filter_Null</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_Null</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">type</span></em></span>: El tipo de variable que debe
                    soportarse.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.null.default"></a>35.2.13.2. Comportamiento por defecto de Zend_Filter_Null</h4></div></div></div>
<p>
            Por defecto este filtro funciona como el método <code class="methodname">empty()</code> de
            <acronym class="acronym">PHP</acronym>; en otras palabras, si
            <code class="methodname">empty()</code> devuelve un booleano <code class="constant">TRUE</code>, entonces se
            devolverá un valor <code class="constant">NULL</code>.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_Null();
$value  = '';
$result = $filter-&gt;filter($value);
// returns null instead of the empty string
</pre>
<p>
            Esto significa que, sin proporcionar ninguna configuración,
            <code class="classname">Zend_Filter_Null</code> aceptará todos los tipos de entrada y devolverá
            <code class="constant">NULL</code> en los mismos casos que <code class="methodname">empty()</code>.
        </p>
<p>
            Cualquier otro valor se devolverá tal cual, sin ningún cambio.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.null.types"></a>35.2.13.3. Cambiar el comportamiento de Zend_Filter_Null</h4></div></div></div>
<p>
            A veces no es suficiente filtrar según <code class="methodname">empty()</code>. Para ello,
            <code class="classname">Zend_Filter_Null</code> le permite configurar qué tipo se
            convertirá y cuál no.
        </p>
<p>
            Se pueden manejar los siguientes tipos:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>boolean</em></span>: Convierte un valor booleano
                    <span class="emphasis"><em><code class="constant">FALSE</code></em></span> a
                    <code class="constant">NULL</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>integer</em></span>: Convierte un valor entero <span class="emphasis"><em>0</em></span>
                    a <code class="constant">NULL</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>empty_array</em></span>: Convierte un <span class="emphasis"><em>array</em></span> vacío
                    a <code class="constant">NULL</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>string</em></span>: Convierte una cadena vacía <span class="emphasis"><em>''</em></span> a
                    <code class="constant">NULL</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>zero</em></span>: Convierte una cadena que contiene el único carácter
                    cero (<span class="emphasis"><em>'0'</em></span>) a <code class="constant">NULL</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>all</em></span>: Convierte todos los tipos anteriores a <code class="constant">NULL</code>.
                    (Este es el comportamiento por defecto.)
                </p></li>
</ul></div>
<p>
            Hay varias formas de seleccionar cuáles de los tipos anteriores se filtran. Puede indicar uno
            o varios tipos y sumarlos, puede dar un array, puede usar constantes, o puede
            dar una cadena de texto. Vea los siguientes ejemplos:
        </p>
<pre class="programlisting">
// converts false to null
$filter = new Zend_Filter_Null(Zend_Filter_Null::BOOLEAN);

// converts false and 0 to null
$filter = new Zend_Filter_Null(
    Zend_Filter_Null::BOOLEAN + Zend_Filter_Null::INTEGER
);

// converts false and 0 to null
$filter = new Zend_Filter_Null( array(
    Zend_Filter_Null::BOOLEAN,
    Zend_Filter_Null::INTEGER
));

// converts false and 0 to null
$filter = new Zend_Filter_Null(array(
    'boolean',
    'integer',
));
</pre>
<p>
            También puede dar una instancia de <code class="classname">Zend_Config</code> para establecer los tipos
            deseados. Para establecer los tipos posteriormente use <code class="methodname">setType()</code>.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.pregreplace"></a>35.2.14. PregReplace</h3></div></div></div>
<p>
        <code class="classname">Zend_Filter_PregReplace</code> realiza una búsqueda usando expresiones regulares
        y reemplaza todos los elementos encontrados.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.pregreplace.options"></a>35.2.14.1. Opciones soportadas para Zend_Filter_PregReplace</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_PregReplace</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">match</span></em></span>: El patrón que se
                    buscará.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">replace</span></em></span>: La cadena que se usa como
                    reemplazo de las coincidencias.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.pregreplace.basic"></a>35.2.14.2. Uso básico</h4></div></div></div>
<p>
            Para usar este filtro correctamente debe dar dos opciones:
        </p>
<p>
            Debe darse la opción <span class="property">match</span> para establecer el patrón que se
            buscará. Puede ser una cadena para un solo patrón, o un array de cadenas para
            varios patrones.
        </p>
<p>
            Para establecer el patrón que se usará como reemplazo se debe usar la opción
            <span class="property">replace</span>. Puede ser una cadena para un solo patrón, o
            un array de cadenas para varios patrones.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_PregReplace(array('match' =&gt; '/bob/',
                                            'replace' =&gt; 'john'));
$input  = 'Hy bob!';

$filter-&gt;filter($input);
// returns 'Hy john!'
</pre>
<p>
            Puede usar <code class="methodname">getMatchPattern()</code> y
            <code class="methodname">setMatchPattern()</code> para establecer el patrón de coincidencia posteriormente. Para
            establecer el patrón de reemplazo puede usar <code class="methodname">getReplacement()</code> y
            <code class="methodname">setReplacement()</code>.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_PregReplace();
$filter-&gt;setMatchPattern(array('bob', 'Hy'))
       -&gt;setReplacement(array('john', 'Bye'));
$input  = 'Hy bob!";

$filter-&gt;filter($input);
// returns 'Bye john!'
</pre>
<p>
            Para un uso más complejo, eche un vistazo al <a class="ulink" href="http://www.php.net/manual/en/reference.pcre.pattern.modifiers.php" target="_top">capítulo de patrones
                PCRE</a> de <acronym class="acronym">PHP</acronym>.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.realpath"></a>35.2.15. RealPath</h3></div></div></div>
<p>
        Este filtro resuelve los enlaces y nombres de ruta dados y devuelve nombres de ruta absolutos
        canonicalizados.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.realpath.options"></a>35.2.15.1. Opciones soportadas para Zend_Filter_RealPath</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_RealPath</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">exists</span></em></span>: Esta opción por defecto es
                    <code class="constant">TRUE</code>, lo que comprueba si la ruta dada realmente existe.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.realpath.basic"></a>35.2.15.2. Uso básico</h4></div></div></div>
<p>
            Para cualquier enlace o nombre de ruta dado se devolverá su ruta absoluta.
            Las referencias a '<code class="filename">/./</code>', '<code class="filename">/../</code>' y los caracteres extra
            '<code class="filename">/</code>' en la ruta de entrada se eliminarán. La ruta resultante
            no tendrá ningún enlace simbólico, ni carácter '<code class="filename">/./</code>' o
            '<code class="filename">/../</code>'.
        </p>
<p>
            <code class="classname">Zend_Filter_RealPath</code> devolverá <code class="constant">FALSE</code> en
            caso de fallo, por ejemplo si el archivo no existe. En sistemas <acronym class="acronym">BSD</acronym>
            <code class="classname">Zend_Filter_RealPath</code> no falla si solo el último componente de la ruta
            no existe, mientras que otros sistemas devolverán <code class="constant">FALSE</code>.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_RealPath();
$path   = '/www/var/path/../../mypath';
$filtered = $filter-&gt;filter($path);

// returns '/www/mypath'
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.realpath.exists"></a>35.2.15.3. Rutas no existentes</h4></div></div></div>
<p>
            A veces es útil obtener también rutas cuando no existen, por ejemplo cuando quiere
            obtener la ruta real de una ruta que quiere crear. Puede entonces dar un
            <code class="constant">FALSE</code> en la inicialización, o usar <code class="methodname">setExists()</code> para
            establecerlo.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_RealPath(false);
$path   = '/www/var/path/../../non/existing/path';
$filtered = $filter-&gt;filter($path);

// returns '/www/non/existing/path'
// even when file_exists or realpath would return false
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.stringtolower"></a>35.2.16. StringToLower</h3></div></div></div>
<p>
        Este filtro convierte cualquier entrada a minúsculas.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtolower.options"></a>35.2.16.1. Opciones soportadas para Zend_Filter_StringToLower</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para
            <code class="classname">Zend_Filter_StringToLower</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">encoding</span></em></span>: Esta opción puede usarse para
                    establecer una codificación que debe usarse.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtolower.basic"></a>35.2.16.2. Uso básico</h4></div></div></div>
<p>
            Este es un ejemplo básico:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StringToLower();

print $filter-&gt;filter('SAMPLE');
// returns "sample"
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtolower.encoding"></a>35.2.16.3. Cadenas con codificaciones diferentes</h4></div></div></div>
<p>
            Por defecto solo manejará caracteres del idioma actual de su
            servidor. Los caracteres de otros conjuntos de caracteres se ignorarían. Aun así, es
            posible convertirlos también a minúsculas cuando la extensión mbstring está disponible
            en su entorno. Simplemente establezca la codificación deseada al inicializar el
            filtro <code class="classname">StringToLower</code>. O use el
            método <code class="methodname">setEncoding()</code> para cambiar la codificación posteriormente.
        </p>
<pre class="programlisting">
// using UTF-8
$filter = new Zend_Filter_StringToLower('UTF-8');

// or give an array which can be useful when using a configuration
$filter = new Zend_Filter_StringToLower(array('encoding' =&gt; 'UTF-8'));

// or do this afterwards
$filter-&gt;setEncoding('ISO-8859-1');
</pre>
<div class="note"><table border="0" summary="Note: Setting wrong encodings">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Establecer codificaciones incorrectas</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Tenga en cuenta que obtendrá una excepción si quiere establecer una codificación
                y la extensión mbstring no está disponible en su entorno.
            </p>
<p>
                También, al intentar establecer una codificación que no está soportada por su
                extensión mbstring, obtendrá una excepción.
            </p>
</td></tr>
</table></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.stringtoupper"></a>35.2.17. StringToUpper</h3></div></div></div>
<p>
        Este filtro convierte cualquier entrada a mayúsculas.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtoupper.options"></a>35.2.17.1. Opciones soportadas para Zend_Filter_StringToUpper</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para
            <code class="classname">Zend_Filter_StringToUpper</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">encoding</span></em></span>: Esta opción puede usarse para
                    establecer una codificación que debe usarse.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtoupper.basic"></a>35.2.17.2. Uso básico</h4></div></div></div>
<p>
            Este es un ejemplo básico para usar el filtro <code class="classname">StringToUpper</code>:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StringToUpper();

print $filter-&gt;filter('Sample');
// returns "SAMPLE"
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtoupper.encoding"></a>35.2.17.3. Cadenas con codificaciones diferentes</h4></div></div></div>
<p>
            Al igual que el filtro <code class="classname">StringToLower</code>, este filtro maneja
            solo caracteres del idioma actual de su servidor. El uso de conjuntos de
            caracteres diferentes funciona igual que con <code class="classname">StringToLower</code>.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StringToUpper(array('encoding' =&gt; 'UTF-8'));

// or do this afterwards
$filter-&gt;setEncoding('ISO-8859-1');
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.stringtrim"></a>35.2.18. StringTrim</h3></div></div></div>
<p>
        Este filtro modifica una cadena dada de tal manera que se eliminan ciertos caracteres del
        principio y del final.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtrim.options"></a>35.2.18.1. Opciones soportadas para Zend_Filter_StringTrim</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_StringTrim</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">charlist</span></em></span>: Lista de caracteres a
                    eliminar del principio y del final de la cadena. Si no se establece o es nulo,
                    se invocará el comportamiento por defecto, que consiste en eliminar solo los espacios en blanco
                    del principio y del final de la cadena.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtrim.basic"></a>35.2.18.2. Uso básico</h4></div></div></div>
<p>
            A continuación se muestra un ejemplo básico de uso:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StringTrim();

print $filter-&gt;filter(' This is (my) content: ');
</pre>
<p>
            El ejemplo anterior devuelve 'This is (my) content:'. Observe que los caracteres de espacio en blanco
            se han eliminado.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stringtrim.types"></a>35.2.18.3. Comportamiento por defecto de Zend_Filter_StringTrim</h4></div></div></div>
<pre class="programlisting">
$filter = new Zend_Filter_StringTrim(':');
// or new Zend_Filter_StringTrim(array('charlist' =&gt; ':'));

print $filter-&gt;filter(' This is (my) content:');
</pre>
<p>
            El ejemplo anterior devuelve 'This is (my) content'. Observe que se eliminan los caracteres de espacio en blanco
            y los dos puntos. También puede proporcionar una instancia de
            <code class="classname">Zend_Config</code> o un array con una clave 'charlist'. Para establecer la
            lista de caracteres deseada después de la instanciación, use el
            método <code class="methodname">setCharList()</code>.
            <code class="methodname">getCharList()</code> devuelve los valores establecidos para charlist.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.stripnewlines"></a>35.2.19. StripNewLines</h3></div></div></div>
<p>
        Este filtro modifica una cadena dada y elimina todos los caracteres de nueva línea dentro de esa cadena.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.strinpnewlines.options"></a>35.2.19.1. Opciones soportadas para Zend_Filter_StripNewLines</h4></div></div></div>
<p>
            No hay opciones adicionales para <code class="classname">Zend_Filter_StripNewLines</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.stripnewlines.basic"></a>35.2.19.2. Uso básico</h4></div></div></div>
<p>
            A continuación se muestra un ejemplo básico de uso:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StripNewLines();

print $filter-&gt;filter("This is (my)\n\rcontent: ');
</pre>
<p>
            El ejemplo anterior devuelve 'This is (my) content:'. Observe que se han eliminado todos los caracteres
            de nueva línea.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.filter.set.striptags"></a>35.2.20. StripTags</h3></div></div></div>
<p>
        Este filtro puede eliminar etiquetas <acronym class="acronym">XML</acronym> y <acronym class="acronym">HTML</acronym> del contenido
        dado.
    </p>
<div class="warning"><table border="0" summary="Warning: Zend_Filter_StripTags is potentially unsecure">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Warning]" src="images/warning.png"></td>
<th align="left">Zend_Filter_StripTags es potencialmente inseguro</th>
</tr>
<tr><td align="left" valign="top">
<p>
            Tenga en cuenta que <code class="classname">Zend_Filter_StripTags</code> solo debe usarse para eliminar
            todas las etiquetas disponibles.
        </p>
<p>
            Usar <code class="classname">Zend_Filter_StripTags</code> para hacer que su sitio sea
            <span class="emphasis"><em>seguro</em></span> eliminando algunas etiquetas no deseadas conducirá a código inseguro y
            peligroso.
        </p>
<p>
            <code class="classname">Zend_Filter_StripTags</code> no debe usarse para prevenir
            ataques de <acronym class="acronym">XSS</acronym>. Este filtro no es un reemplazo para usar Tidy o
            HtmlPurifier.
        </p>
</td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.striptags.options"></a>35.2.20.1. Opciones soportadas para Zend_Filter_StripTags</h4></div></div></div>
<p>
            Las siguientes opciones son soportadas para <code class="classname">Zend_Filter_StripTags</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allowAttribs</span></em></span>: Esta opción establece los
                    atributos que se aceptan. Todos los demás atributos se eliminan del contenido
                    dado
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allowTags</span></em></span>: Esta opción establece las etiquetas
                    que se aceptan. Todas las demás etiquetas se eliminarán del contenido dado
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.striptags.basic"></a>35.2.20.2. Uso básico</h4></div></div></div>
<p>
            Vea el siguiente ejemplo del comportamiento por defecto de este filtro:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StripTags();

print $filter-&gt;filter('&lt;B&gt;My content&lt;/B&gt;');
</pre>
<p>
            Como resultado obtendrá el contenido sin etiquetas 'My content'.
        </p>
<p>
            Cuando el contenido contiene etiquetas rotas o parciales, todo el contenido siguiente
            se eliminará. Vea el siguiente ejemplo:
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StripTags();

print $filter-&gt;filter('This contains &lt;a href="http://example.com"&gt;no ending tag');
</pre>
<p>
            Lo anterior devolverá 'This contains', con el resto eliminado.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.striptags.allowtags"></a>35.2.20.3. Permitir etiquetas definidas</h4></div></div></div>
<p>
            <code class="classname">Zend_Filter_StripTags</code> permite eliminar todas las etiquetas excepto las definidas.
            Esto puede usarse, por ejemplo, para eliminar todas las etiquetas excepto los enlaces de un texto.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StripTags(array('allowTags' =&gt; 'a'));

$input  = "A text with &lt;br/&gt; a &lt;a href='link.com'&gt;link&lt;/a&gt;";
print $filter-&gt;filter($input);
// returns: A text with a &lt;a href='link.com'&gt;link&lt;/a&gt;
</pre>
<p>
            El ejemplo anterior elimina todas las etiquetas excepto el enlace. Proporcionando un array puede establecer
            varias etiquetas a la vez.
        </p>
<div class="warning"><table border="0" summary="Warning">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Warning]" src="images/warning.png"></td>
<th align="left">Advertencia</th>
</tr>
<tr><td align="left" valign="top"><p>
                No use esta característica para obtener un contenido <span class="emphasis"><em>probablemente seguro</em></span>. Este
                componente no reemplaza el uso de un filtro html correctamente configurado.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.filter.set.striptags.allowattribs"></a>35.2.20.4. Permitir atributos definidos</h4></div></div></div>
<p>
            También es posible eliminar todos los atributos excepto los permitidos de una etiqueta.
        </p>
<pre class="programlisting">
$filter = new Zend_Filter_StripTags(array('allowAttribs' =&gt; 'src'));

$input  = "A text with &lt;br/&gt; a &lt;img src='picture.com' width='100'&gt;picture&lt;/img&gt;";
print $filter-&gt;filter($input);
// returns: A text with a &lt;img src='picture.com'&gt;picture&lt;/img&gt;
</pre>
<p>
            El ejemplo anterior elimina todas las etiquetas excepto img. Además, de la etiqueta img
            se eliminarán todos los atributos excepto src. Proporcionando un array puede establecer varios
            atributos a la vez.
        </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.filter.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.filter.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.filter.filter_chains.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 35. Zend_Filter </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 35.3. Cadenas de filtros</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
