<?php $title = '36.4. Creación de formularios usando Zend_Form'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">36.4. Creación de formularios usando Zend_Form</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.form.elements.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 36. Zend_Form</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.form.decorators.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.form.forms"></a>36.4. Creación de formularios usando Zend_Form</h2></div></div></div>
<p>
        La clase <code class="classname">Zend_Form</code> se utiliza para agrupar elementos de
        formulario, grupos de visualización y subformularios. A continuación puede realizar
        las siguientes acciones sobre esos elementos:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                Validación, incluyendo la recuperación de códigos y mensajes de error
            </p></li>
<li class="listitem"><p>
                Agregación de valores, incluyendo poblar elementos y recuperar tanto
                valores filtrados como sin filtrar de todos los elementos
            </p></li>
<li class="listitem"><p>
                Iteración sobre todos los elementos, en el orden en que fueron introducidos o
                en base a las indicaciones de orden recuperadas de cada elemento
            </p></li>
<li class="listitem"><p>
                Renderizado de todo el formulario, ya sea mediante un único decorador que
                realiza un renderizado personalizado o iterando sobre cada elemento del formulario
            </p></li>
</ul></div>
<p>
        Aunque los formularios creados con <code class="classname">Zend_Form</code> pueden ser complejos,
        probablemente su mejor caso de uso son los formularios sencillos; su mejor uso está en
        el desarrollo rápido de aplicaciones (RAD) y la creación de prototipos.
    </p>
<p>
        En su forma más básica, simplemente se instancia un objeto de formulario:
    </p>
<pre class="programlisting">
// Generic form object:
$form = new Zend_Form();

// Custom form object:
$form = new My_Form()
</pre>
<p>
        Opcionalmente se puede pasar una instancia de <code class="classname">Zend_Config</code> o un array,
        que se usará para establecer el estado del objeto y potencialmente crear nuevos elementos:
    </p>
<pre class="programlisting">
// Passing in configuration options:
$form = new Zend_Form($config);
</pre>
<p>
        <code class="classname">Zend_Form</code> es iterable, e iterará sobre elementos,
        grupos de visualización y subformularios, usando el orden en que fueron registrados y
        cualquier índice de orden que cada uno pueda tener. Esto resulta útil en los casos en los que se
        desea renderizar los elementos manualmente en el orden apropiado.
    </p>
<p>
        La magia de <code class="classname">Zend_Form</code> reside en su capacidad para actuar como una fábrica
        de elementos y grupos de visualización, así como en su capacidad de renderizarse
        a sí mismo mediante decoradores.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.plugins"></a>36.4.1. Cargadores de plugins</h3></div></div></div>
<p>
            <code class="classname">Zend_Form</code> hace uso de
            <code class="classname">Zend_Loader_PluginLoader</code> para permitir a los desarrolladores especificar
            las ubicaciones de elementos y decoradores alternativos. Cada uno tiene su propio
            cargador de plugins asociado, y se utilizan métodos de acceso generales para
            recuperarlos y modificarlos.
        </p>
<p>
            Los siguientes tipos de cargador se usan con los diversos métodos del cargador de
            plugins: 'element' y 'decorator'. Los nombres de tipo no distinguen
            mayúsculas de minúsculas.
        </p>
<p>
            Los métodos usados para interactuar con los cargadores de plugins son los siguientes:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="methodname">setPluginLoader($loader, $type)</code>: $loader es el
                    propio objeto cargador de plugins, mientras que type es uno de los tipos
                    especificados arriba. Esto establece el cargador de plugins para el tipo indicado
                    con el nuevo objeto cargador especificado.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">getPluginLoader($type)</code>: recupera el cargador de plugins
                    asociado con $type.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addPrefixPath($prefix, $path, $type = null)</code>: añade una
                    asociación de prefijo/ruta al cargador especificado por $type. Si
                    $type es <code class="constant">NULL</code>, se intentará añadir la ruta a todos los
                    cargadores, añadiendo al prefijo "_Element" y
                    "_Decorator"; y añadiendo a la ruta "Element/" y
                    "Decorator/". Si tiene todas sus clases adicionales de elementos de formulario
                    bajo una jerarquía común, este es un método conveniente para
                    establecer el prefijo base de todas ellas.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addPrefixPaths(array $spec)</code>: permite añadir muchas
                    rutas a la vez a uno o más cargadores de plugins. Espera que cada
                    elemento del array sea un array con las claves 'path', 'prefix' y
                    'type'.
                </p></li>
</ul></div>
<p>
            Adicionalmente, se pueden especificar rutas de prefijo para todos los elementos y
            grupos de visualización creados a través de una instancia de <code class="classname">Zend_Form</code>
            usando los siguientes métodos:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="methodname">addElementPrefixPath($prefix, $path, $type = null)</code>:
                    Igual que <code class="methodname">addPrefixPath()</code>, debe especificar un prefijo
                    de clase y una ruta. <code class="varname">$type</code>, cuando se especifica, debe ser
                    uno de los tipos de cargador de plugins especificados por
                    <code class="classname">Zend_Form_Element</code>; consulte la <a class="link" href="zend.form.elements.phtml#zend.form.elements.loaders" title="36.3.1. Plugin Loaders">sección de
                        plugins de elementos</a> para más información sobre los valores
                    válidos de <code class="varname">$type</code>. Si no se especifica
                    <code class="varname">$type</code>, el método asumirá que se trata de un prefijo general para
                    todos los tipos.
                </p></li>
<li class="listitem"><p>
                    <code class="methodname">addDisplayGroupPrefixPath($prefix, $path)</code>:
                    Igual que <code class="methodname">addPrefixPath()</code>, debe especificar un prefijo
                    de clase y una ruta; sin embargo, dado que los grupos de visualización solo admiten
                    decoradores como plugins, no se necesita ningún <code class="varname">$type</code>.
                </p></li>
</ul></div>
<p>
            Los elementos y decoradores personalizados son una forma sencilla de compartir
            funcionalidad entre formularios y encapsular funcionalidad personalizada.
            Consulte el <a class="link" href="zend.form.elements.phtml#zend.form.elements.loaders.customLabel" title="Example 36.1. Custom Label">ejemplo
                de etiqueta personalizada</a> en la documentación de elementos para ver un ejemplo de
            cómo los elementos personalizados pueden usarse como reemplazo de las
            clases estándar.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.elements"></a>36.4.2. Elementos</h3></div></div></div>
<p>
            <code class="classname">Zend_Form</code> proporciona varios métodos de acceso para añadir y
            eliminar elementos de formulario de un formulario. Estos pueden aceptar instancias de
            objetos elemento o servir como fábricas para instanciar los propios
            objetos elemento.
        </p>
<p>
            El método más básico para añadir un elemento es
            <code class="methodname">addElement()</code>. Este método puede aceptar un objeto de
            tipo <code class="classname">Zend_Form_Element</code> (o de una clase que extienda
            <code class="classname">Zend_Form_Element</code>), o argumentos para construir un nuevo
            elemento, incluyendo el tipo de elemento, el nombre y cualquier opción de
            configuración.
        </p>
<p>
            Algunos ejemplos:
        </p>
<pre class="programlisting">
// Using an element instance:
$element = new Zend_Form_Element_Text('foo');
$form-&gt;addElement($element);

// Using a factory
//
// Creates an element of type Zend_Form_Element_Text with the
// name of 'foo':
$form-&gt;addElement('text', 'foo');

// Pass label option to the element:
$form-&gt;addElement('text', 'foo', array('label' =&gt; 'Foo:'));
</pre>
<div class="note"><table border="0" summary="Note: addElement() Implements Fluent Interface">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">addElement() implementa una interfaz fluida</th>
</tr>
<tr><td align="left" valign="top">
<p>
                <code class="methodname">addElement()</code> implementa una interfaz fluida; es decir,
                devuelve el objeto <code class="classname">Zend_Form</code>, y no
                el elemento. Esto se hace para permitir encadenar
                varios métodos addElement() u otros métodos del formulario que
                implementen la interfaz fluida (todos los setters de <code class="classname">Zend_Form</code>
                implementan este patrón).
            </p>
<p>
                Si se desea que se devuelva el elemento en su lugar, use
                <code class="methodname">createElement()</code>, que se describe a continuación. Tenga en cuenta,
                sin embargo, que <code class="methodname">createElement()</code> no adjunta el
                elemento al formulario.
            </p>
<p>
                Internamente, <code class="methodname">addElement()</code> en realidad usa
                <code class="methodname">createElement()</code> para crear el elemento antes de
                adjuntarlo al formulario.
            </p>
</td></tr>
</table></div>
<p>
            Una vez que un elemento se ha añadido al formulario, se puede recuperar por
            nombre. Esto puede hacerse ya sea usando el método <code class="methodname">getElement()</code>
            o usando sobrecarga para acceder al elemento como una propiedad de
            objeto:
        </p>
<pre class="programlisting">
// getElement():
$foo = $form-&gt;getElement('foo');

// As object property:
$foo = $form-&gt;foo;
</pre>
<p>
            Ocasionalmente, puede que desee crear un elemento sin adjuntarlo
            al formulario (por ejemplo, si desea hacer uso de las diversas
            rutas de plugin registradas con el formulario, pero desea adjuntar más tarde el
            objeto a un subformulario). El método <code class="methodname">createElement()</code>
            permite hacerlo:
        </p>
<pre class="programlisting">
// $username becomes a Zend_Form_Element_Text object:
$username = $form-&gt;createElement('text', 'username');
</pre>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.elements.values"></a>36.4.2.1. Poblado y recuperación de valores</h4></div></div></div>
<p>
                Después de validar un formulario, normalmente necesitará recuperar los
                valores para poder realizar otras operaciones, como actualizar una
                base de datos o notificar a un servicio web. Puede recuperar todos los valores
                para todos los elementos usando <code class="methodname">getValues()</code>;
                <code class="methodname">getValue($name)</code> permite recuperar el valor de un
                único elemento por su nombre:
            </p>
<pre class="programlisting">
// Get all values:
$values = $form-&gt;getValues();

// Get only 'foo' element's value:
$value = $form-&gt;getValue('foo');
</pre>
<p>
                A veces querrá poblar el formulario con valores especificados
                antes de renderizarlo. Esto puede hacerse con los métodos
                <code class="methodname">setDefaults()</code> o <code class="methodname">populate()</code>
                :
            </p>
<pre class="programlisting">
$form-&gt;setDefaults($data);
$form-&gt;populate($data);
</pre>
<p>
                Por otro lado, puede que desee limpiar un formulario después de poblarlo
                o validarlo; esto puede hacerse usando el
                método <code class="methodname">reset()</code>:
            </p>
<pre class="programlisting">
$form-&gt;reset();
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.elements.global"></a>36.4.2.2. Operaciones globales</h4></div></div></div>
<p>
                En ocasiones querrá que ciertas operaciones afecten a todos los
                elementos. Los escenarios comunes incluyen la necesidad de establecer rutas de prefijo de
                plugin para todos los elementos, establecer decoradores para todos los elementos y
                establecer filtros para todos los elementos. Como ejemplos:
            </p>
<div class="example">
<a name="zend.form.forms.elements.global.allpaths"></a><p class="title"><b>Ejemplo 36.2. Establecer rutas de prefijo para todos los elementos</b></p>
<div class="example-contents">
<p>
                    Puede establecer rutas de prefijo para todos los elementos por tipo, o usando
                    un prefijo global. Algunos ejemplos:
                </p>
<pre class="programlisting">
// Set global prefix path:
// Creates paths for prefixes My_Foo_Filter, My_Foo_Validate,
// and My_Foo_Decorator
$form-&gt;addElementPrefixPath('My_Foo', 'My/Foo/');

// Just filter paths:
$form-&gt;addElementPrefixPath('My_Foo_Filter',
                            'My/Foo/Filter',
                            'filter');

// Just validator paths:
$form-&gt;addElementPrefixPath('My_Foo_Validate',
                            'My/Foo/Validate',
                            'validate');

// Just decorator paths:
$form-&gt;addElementPrefixPath('My_Foo_Decorator',
                            'My/Foo/Decorator',
                            'decorator');
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.form.forms.elements.global.decorators"></a><p class="title"><b>Ejemplo 36.3. Establecer decoradores para todos los elementos</b></p>
<div class="example-contents">
<p>
                    Puede establecer decoradores para todos los elementos.
                    <code class="methodname">setElementDecorators()</code> acepta un array de
                    decoradores, igual que <code class="methodname">setDecorators()</code>, y
                    sobrescribirá cualquier decorador previamente establecido en cada elemento. En
                    este ejemplo, establecemos los decoradores simplemente como un ViewHelper
                    y un Label:
                </p>
<pre class="programlisting">
$form-&gt;setElementDecorators(array(
    'ViewHelper',
    'Label'
));
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.form.forms.elements.global.decoratorsFilter"></a><p class="title"><b>Ejemplo 36.4. Establecer decoradores para algunos elementos</b></p>
<div class="example-contents">
<p>
                    También puede establecer decoradores para un subconjunto de elementos,
                    ya sea por inclusión o exclusión. El segundo argumento de
                    <code class="methodname">setElementDecorators()</code> puede ser un array de
                    nombres de elementos; por defecto, especificar tal array
                    establecerá los decoradores indicados solo en esos elementos. También
                    puede pasar un tercer argumento, una marca que indica si
                    esta lista de elementos es de inclusión o exclusión.
                    Si la marca es <code class="constant">FALSE</code>, decorará todos los
                    elementos <span class="emphasis"><em>excepto</em></span> los de la lista pasada.
                    Como en el uso estándar del método, cualquier decorador que se pase
                    sobrescribirá los decoradores previamente establecidos en cada
                    elemento.
                </p>
<p>
                    En el siguiente fragmento, indicamos que solo queremos los decoradores
                    ViewHelper y Label para los elementos 'foo' y 'bar':
                </p>
<pre class="programlisting">
$form-&gt;setElementDecorators(
    array(
        'ViewHelper',
        'Label'
    ),
    array(
        'foo',
        'bar'
    )
);
</pre>
<p>
                    Por otro lado, con este fragmento, ahora indicaremos
                    que queremos usar únicamente los decoradores ViewHelper y Label
                    para todos los elementos <span class="emphasis"><em>excepto</em></span>
                    los elementos 'foo' y 'bar':
                </p>
<pre class="programlisting">
$form-&gt;setElementDecorators(
    array(
        'ViewHelper',
        'Label'
    ),
    array(
        'foo',
        'bar'
    ),
    false
);
</pre>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: Some Decorators are Inappropriate for Some Elements">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Algunos decoradores son inadecuados para algunos elementos</th>
</tr>
<tr><td align="left" valign="top">
<p>
                    Aunque <code class="methodname">setElementDecorators()</code> puede parecer
                    una buena solución, hay algunos casos en los que puede
                    terminar dando resultados inesperados. Por ejemplo,
                    los diversos elementos de botón (Submit, Button, Reset)
                    actualmente usan la etiqueta como el valor del botón,
                    y solo usan los decoradores ViewHelper y DtDdWrapper,
                    evitando que se renderice una etiqueta, errores y sugerencias
                    adicionales. El ejemplo anterior duplicaría algún
                    contenido (la etiqueta) para los elementos de botón.
                </p>
<p>
                    Puede usar el array de inclusión/exclusión para superar
                    este problema, como se indicó en el ejemplo anterior.
                </p>
<p>
                    Por lo tanto, use este método con prudencia, y tenga en cuenta que puede
                    necesitar excluir algunos elementos o cambiar manualmente los decoradores de algunos elementos
                    para evitar una salida no deseada.
                </p>
</td></tr>
</table></div>
<div class="example">
<a name="zend.form.forms.elements.global.filters"></a><p class="title"><b>Ejemplo 36.5. Establecer filtros para todos los elementos</b></p>
<div class="example-contents">
<p>
                    En algunos casos, puede que desee aplicar el mismo filtro a todos los
                    elementos; un caso común es aplicar <code class="methodname">trim()</code> a todos los valores:
                </p>
<pre class="programlisting">
$form-&gt;setElementFilters(array('StringTrim'));
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.elements.methods"></a>36.4.2.3. Métodos para interactuar con elementos</h4></div></div></div>
<p>
                Los siguientes métodos pueden usarse para interactuar con elementos:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">createElement($element, $name = null, $options =
                            null)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addElement($element, $name = null, $options = null)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addElements(array $elements)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setElements(array $elements)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getElement($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getElements()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">removeElement($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">clearElements()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setDefaults(array $defaults)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setDefault($name, $value)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getValue($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getValues()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getUnfilteredValue($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getUnfilteredValues()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setElementFilters(array $filters)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setElementDecorators(array $decorators)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addElementPrefixPath($prefix, $path, $type = null)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addElementPrefixPaths(array $spec)</code>
                    </p></li>
</ul></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.displaygroups"></a>36.4.3. Grupos de visualización</h3></div></div></div>
<p>
            Los grupos de visualización son una forma de crear agrupaciones virtuales de elementos con fines
            de visualización. Todos los elementos permanecen accesibles por nombre en el
            formulario, pero al iterar sobre el formulario o renderizarlo, cualquier elemento en
            un grupo de visualización se renderiza en conjunto. El caso de uso más común para
            esto es la agrupación de elementos en fieldsets.
        </p>
<p>
            La clase base para los grupos de visualización es
            <code class="classname">Zend_Form_DisplayGroup</code>. Aunque puede instanciarse
            directamente, generalmente es mejor usar el método
            <code class="methodname">addDisplayGroup()</code> de <code class="classname">Zend_Form</code> para hacerlo. Este método toma un
            array de nombres de elementos como primer argumento, y un nombre para el grupo de visualización
            como segundo argumento. Opcionalmente se puede pasar un array de
            opciones o un objeto <code class="classname">Zend_Config</code> como tercer argumento.
        </p>
<p>
            Suponiendo que los elementos 'username' y 'password' ya están establecidos
            en el formulario, el siguiente código agruparía estos elementos en un
            grupo de visualización 'login':
        </p>
<pre class="programlisting">
$form-&gt;addDisplayGroup(array('username', 'password'), 'login');
</pre>
<p>
            Puede acceder a los grupos de visualización usando el
            método <code class="methodname">getDisplayGroup()</code>, o mediante sobrecarga usando el
            nombre del grupo de visualización:
        </p>
<pre class="programlisting">
// Using getDisplayGroup():
$login = $form-&gt;getDisplayGroup('login');

// Using overloading:
$login = $form-&gt;login;
</pre>
<div class="note"><table border="0" summary="Note: Default Decorators Do Not Need to Be Loaded">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">No es necesario cargar los decoradores por defecto</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Por defecto, los decoradores por defecto se cargan durante la inicialización del
                objeto. Puede deshabilitar esto pasando la
                opción 'disableLoadDefaultDecorators' al crear un grupo
                de visualización:
            </p>
<pre class="programlisting">
$form-&gt;addDisplayGroup(
    array('foo', 'bar'),
    'foobar',
    array('disableLoadDefaultDecorators' =&gt; true)
);
</pre>
<p>
                Esta opción puede combinarse con cualquier otra opción que se pase,
                tanto como opciones de array como en un objeto <code class="classname">Zend_Config</code>.
            </p>
</td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.displaygroups.global"></a>36.4.3.1. Operaciones globales</h4></div></div></div>
<p>
                Al igual que con los elementos, hay algunas operaciones que podrían
                afectar a todos los grupos de visualización; estas incluyen establecer decoradores y
                establecer la ruta de plugin en la que buscar decoradores.
            </p>
<div class="example">
<a name="zend.form.forms.displaygroups.global.paths"></a><p class="title"><b>Ejemplo 36.6. Establecer la ruta de prefijo de decorador para todos los grupos de visualización</b></p>
<div class="example-contents">
<p>
                    Por defecto, los grupos de visualización heredan cualquiera que sea la ruta de decorador
                    que use el formulario; sin embargo, si deben buscar en ubicaciones
                    alternativas, puede usar el
                    método <code class="methodname">addDisplayGroupPrefixPath()</code>.
                </p>
<pre class="programlisting">
$form-&gt;addDisplayGroupPrefixPath('My_Foo_Decorator', 'My/Foo/Decorator');
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.form.forms.displaygroups.global.decorators"></a><p class="title"><b>Ejemplo 36.7. Establecer decoradores para todos los grupos de visualización</b></p>
<div class="example-contents">
<p>
                    Puede establecer decoradores para todos los grupos de visualización.
                    <code class="methodname">setDisplayGroupDecorators()</code> acepta un array de
                    decoradores, igual que <code class="methodname">setDecorators()</code>, y
                    sobrescribirá cualquier decorador previamente establecido en cada grupo
                    de visualización. En este ejemplo, establecemos los decoradores simplemente como un
                    fieldset (el decorador FormElements es necesario para asegurar
                    que los elementos se iteren):
                </p>
<pre class="programlisting">
$form-&gt;setDisplayGroupDecorators(array(
    'FormElements',
    'Fieldset'
));
</pre>
</div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.displaygroups.customClasses"></a>36.4.3.2. Uso de clases de grupo de visualización personalizadas</h4></div></div></div>
<p>
                Por defecto, <code class="classname">Zend_Form</code> usa la clase
                <code class="classname">Zend_Form_DisplayGroup</code> para los grupos de visualización.
                Puede que necesite extender esta clase para proporcionar
                funcionalidad personalizada. <code class="methodname">addDisplayGroup()</code> no
                permite pasar una instancia concreta, pero sí permite especificar
                la clase a usar como una de sus opciones, usando la
                clave 'displayGroupClass':
            </p>
<pre class="programlisting">
// Use the 'My_DisplayGroup' class
$form-&gt;addDisplayGroup(
    array('username', 'password'),
    'user',
    array('displayGroupClass' =&gt; 'My_DisplayGroup')
);
</pre>
<p>
                Si la clase aún no se ha cargado, <code class="classname">Zend_Form</code>
                intentará hacerlo usando <code class="classname">Zend_Loader</code>.
            </p>
<p>
                También puede especificar una clase de grupo de visualización por defecto para usar con
                el formulario de manera que todos los grupos de visualización creados con ese objeto
                de formulario usen dicha clase:
            </p>
<pre class="programlisting">
// Use the 'My_DisplayGroup' class for all display groups:
$form-&gt;setDefaultDisplayGroupClass('My_DisplayGroup');
</pre>
<p>
                Esta configuración puede especificarse en configuraciones como
                'defaultDisplayGroupClass', y se cargará tempranamente para asegurar que
                todos los grupos de visualización usen esa clase.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.displaygroups.interactionmethods"></a>36.4.3.3. Métodos para interactuar con grupos de visualización</h4></div></div></div>
<p>
                Los siguientes métodos pueden usarse para interactuar con los grupos de
                visualización:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">addDisplayGroup(array $elements, $name, $options
                            = null)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addDisplayGroups(array $groups)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setDisplayGroups(array $groups)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getDisplayGroup($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getDisplayGroups()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">removeDisplayGroup($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">clearDisplayGroups()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setDisplayGroupDecorators(array $decorators)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addDisplayGroupPrefixPath($prefix, $path)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setDefaultDisplayGroupClass($class)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getDefaultDisplayGroupClass($class)</code>
                    </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.displaygroups.methods"></a>36.4.3.4. Métodos de Zend_Form_DisplayGroup</h4></div></div></div>
<p>
                <code class="classname">Zend_Form_DisplayGroup</code> tiene los siguientes métodos,
                agrupados por tipo:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>Configuración:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                                <code class="methodname">setOptions(array $options)</code>
                            </p></li>
<li class="listitem"><p><code class="methodname">setConfig(Zend_Config $config)</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Metadatos:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p><code class="methodname">setAttrib($key, $value)</code></p></li>
<li class="listitem"><p><code class="methodname">addAttribs(array $attribs)</code></p></li>
<li class="listitem"><p><code class="methodname">setAttribs(array $attribs)</code></p></li>
<li class="listitem"><p><code class="methodname">getAttrib($key)</code></p></li>
<li class="listitem"><p><code class="methodname">getAttribs()</code></p></li>
<li class="listitem"><p><code class="methodname">removeAttrib($key)</code></p></li>
<li class="listitem"><p><code class="methodname">clearAttribs()</code></p></li>
<li class="listitem"><p><code class="methodname">setName($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getName()</code></p></li>
<li class="listitem"><p><code class="methodname">setDescription($value)</code></p></li>
<li class="listitem"><p><code class="methodname">getDescription()</code></p></li>
<li class="listitem"><p><code class="methodname">setLegend($legend)</code></p></li>
<li class="listitem"><p><code class="methodname">getLegend()</code></p></li>
<li class="listitem"><p><code class="methodname">setOrder($order)</code></p></li>
<li class="listitem"><p><code class="methodname">getOrder()</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Elementos:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                                <code class="methodname">createElement($type, $name, array $options
                                    = array())</code>
                            </p></li>
<li class="listitem"><p>
                                <code class="methodname">addElement($typeOrElement, $name, array $options =
                                    array())</code>
                            </p></li>
<li class="listitem"><p><code class="methodname">addElements(array $elements)</code></p></li>
<li class="listitem"><p><code class="methodname">setElements(array $elements)</code></p></li>
<li class="listitem"><p><code class="methodname">getElement($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getElements()</code></p></li>
<li class="listitem"><p><code class="methodname">removeElement($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearElements()</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Cargadores de plugins:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                                <code class="methodname">setPluginLoader(Zend_Loader_PluginLoader
                                    $loader)</code>
                            </p></li>
<li class="listitem"><p><code class="methodname">getPluginLoader()</code></p></li>
<li class="listitem"><p><code class="methodname">addPrefixPath($prefix, $path)</code></p></li>
<li class="listitem"><p><code class="methodname">addPrefixPaths(array $spec)</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Decoradores:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                                <code class="methodname">addDecorator($decorator, $options = null)</code>
                            </p></li>
<li class="listitem"><p><code class="methodname">addDecorators(array $decorators)</code></p></li>
<li class="listitem"><p><code class="methodname">setDecorators(array $decorators)</code></p></li>
<li class="listitem"><p><code class="methodname">getDecorator($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getDecorators()</code></p></li>
<li class="listitem"><p><code class="methodname">removeDecorator($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearDecorators()</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Renderizado:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                                <code class="methodname">setView(Zend_View_Interface $view = null)</code>
                            </p></li>
<li class="listitem"><p><code class="methodname">getView()</code></p></li>
<li class="listitem"><p>
                                <code class="methodname">render(Zend_View_Interface $view = null)</code>
                            </p></li>
</ul></div>
</li>
<li class="listitem">
<p>I18n:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                                <code class="methodname">setTranslator(Zend_Translate_Adapter $translator =
                                    null)</code>
                            </p></li>
<li class="listitem"><p><code class="methodname">getTranslator()</code></p></li>
<li class="listitem"><p><code class="methodname">setDisableTranslator($flag)</code></p></li>
<li class="listitem"><p><code class="methodname">translatorIsDisabled()</code></p></li>
</ul></div>
</li>
</ul></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.subforms"></a>36.4.4. Subformularios</h3></div></div></div>
<p>
            Los subformularios sirven para varios propósitos:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    Crear agrupaciones lógicas de elementos. Dado que los subformularios son simplemente
                    formularios, se pueden validar subformularios como entidades individuales.
                </p></li>
<li class="listitem"><p>
                    Crear formularios de varias páginas. Dado que los subformularios son simplemente formularios, se
                    puede mostrar un subformulario distinto por página, construyendo formularios de varias
                    páginas donde cada formulario tiene su propia lógica de validación. Solo cuando
                    todos los subformularios validen se considerará completo el formulario.
                </p></li>
<li class="listitem"><p>
                    Agrupaciones de visualización. Al igual que los grupos de visualización, los subformularios, cuando se renderizan
                    como parte de un formulario más grande, pueden usarse para agrupar elementos. Sin embargo, tenga en
                    cuenta que el objeto de formulario maestro no tendrá conocimiento de los elementos
                    de los subformularios.
                </p></li>
</ul></div>
<p>
            Un subformulario puede ser un objeto <code class="classname">Zend_Form</code>, o, más
            típicamente, un objeto <code class="classname">Zend_Form_SubForm</code>. Este último
            contiene decoradores adecuados para su inclusión en un formulario más grande (es decir,
            no renderiza etiquetas de formulario <acronym class="acronym">HTML</acronym> adicionales, pero sí agrupa
            elementos). Para adjuntar un subformulario, simplemente añádalo al formulario y déle
            un nombre:
        </p>
<pre class="programlisting">
$form-&gt;addSubForm($subForm, 'subform');
</pre>
<p>
            Puede recuperar un subformulario usando ya sea
            <code class="methodname">getSubForm($name)</code> o mediante sobrecarga usando el nombre
            del subformulario:
        </p>
<pre class="programlisting">
// Using getSubForm():
$subForm = $form-&gt;getSubForm('subform');

// Using overloading:
$subForm = $form-&gt;subform;
</pre>
<p>
            Los subformularios se incluyen en la iteración del formulario, aunque los elementos que
            contienen no lo están.
        </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.subforms.global"></a>36.4.4.1. Operaciones globales</h4></div></div></div>
<p>
                Al igual que los elementos y los grupos de visualización, hay algunas operaciones que
                podrían necesitar afectar a todos los subformularios. A diferencia de los grupos de visualización y los
                elementos, sin embargo, los subformularios heredan la mayor parte de su funcionalidad del
                objeto de formulario maestro, y la única operación real que podría necesitar
                realizarse globalmente es establecer decoradores para los subformularios. Con este
                propósito, existe el método <code class="methodname">setSubFormDecorators()</code>
                . En el siguiente ejemplo, estableceremos el decorador para todos los
                subformularios simplemente como un fieldset (el decorador FormElements es
                necesario para asegurar que sus elementos se iteren):
            </p>
<pre class="programlisting">
$form-&gt;setSubFormDecorators(array(
    'FormElements',
    'Fieldset'
));
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.subforms.methods"></a>36.4.4.2. Métodos para interactuar con subformularios</h4></div></div></div>
<p>
                Los siguientes métodos pueden usarse para interactuar con subformularios:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">addSubForm(Zend_Form $form, $name, $order = null)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addSubForms(array $subForms)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setSubForms(array $subForms)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getSubForm($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getSubForms()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">removeSubForm($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">clearSubForms()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setSubFormDecorators(array $decorators)</code>
                    </p></li>
</ul></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.metadata"></a>36.4.5. Metadatos y atributos</h3></div></div></div>
<p>
            Aunque la utilidad de un formulario deriva principalmente de los elementos que
            contiene, también puede contener otros metadatos, como un nombre (usado a menudo
            como un ID único en el marcado <acronym class="acronym">HTML</acronym>); la acción y el método del formulario;
            el número de elementos, grupos y subformularios que contiene; y
            metadatos arbitrarios (usados normalmente para establecer atributos <acronym class="acronym">HTML</acronym> para la
            propia etiqueta del formulario).
        </p>
<p>
            Puede establecer y recuperar el nombre de un formulario usando los métodos de acceso al nombre:
        </p>
<pre class="programlisting">
// Set the name:
$form-&gt;setName('registration');

// Retrieve the name:
$name = $form-&gt;getName();
</pre>
<p>
            Para establecer la acción (url a la que se envía el formulario) y el método (método
            mediante el cual debe enviarse, por ejemplo, 'POST' o '<code class="constant">GET</code>'), use los métodos de acceso
            action y method:
        </p>
<pre class="programlisting">
// Set the action and method:
$form-&gt;setAction('/user/login')
     -&gt;setMethod('post');
</pre>
<p>
            También puede especificar el tipo de codificación del formulario específicamente usando los
            métodos de acceso enctype. <code class="classname">Zend_Form</code> define dos constantes,
            <code class="constant">Zend_Form::ENCTYPE_URLENCODED</code> y
            <code class="constant">Zend_Form::ENCTYPE_MULTIPART</code>, que corresponden a los
            valores 'application/x-www-form-urlencoded' y
            'multipart/form-data', respectivamente; sin embargo, puede establecer esto a
            cualquier tipo de codificación arbitrario.
        </p>
<pre class="programlisting">
// Set the action, method, and enctype:
$form-&gt;setAction('/user/login')
     -&gt;setMethod('post')
     -&gt;setEnctype(Zend_Form::ENCTYPE_MULTIPART);
</pre>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                El método, la acción y el enctype solo se usan internamente para el renderizado,
                y no para ningún tipo de validación.
            </p></td></tr>
</table></div>
<p>
            <code class="classname">Zend_Form</code> implementa la interfaz <code class="classname">Countable</code>
            , lo que permite pasarlo como argumento a count:
        </p>
<pre class="programlisting">
$numItems = count($form);
</pre>
<p>
            El establecimiento de metadatos arbitrarios se realiza mediante los métodos de acceso attribs.
            Dado que la sobrecarga en <code class="classname">Zend_Form</code> se usa para acceder a
            elementos, grupos de visualización y subformularios, este es el único método para
            acceder a los metadatos.
        </p>
<pre class="programlisting">
// Setting attributes:
$form-&gt;setAttrib('class', 'zend-form')
     -&gt;addAttribs(array(
         'id'       =&gt; 'registration',
         'onSubmit' =&gt; 'validate(this)',
     ));

// Retrieving attributes:
$class = $form-&gt;getAttrib('class');
$attribs = $form-&gt;getAttribs();

// Remove an attribute:
$form-&gt;removeAttrib('onSubmit');

// Clear all attributes:
$form-&gt;clearAttribs();
</pre>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.decorators"></a>36.4.6. Decoradores</h3></div></div></div>
<p>
            Crear el marcado para un formulario suele ser una tarea que consume tiempo,
            particularmente si se planea reutilizar el mismo marcado para mostrar cosas
            tales como errores de validación, valores enviados, etc.
            La respuesta de <code class="classname">Zend_Form</code> a este problema son los
            <span class="emphasis"><em>decoradores</em></span>.
        </p>
<p>
            Los decoradores para objetos <code class="classname">Zend_Form</code> pueden usarse para renderizar
            un formulario. El decorador FormElements iterará sobre todos los elementos de
            un formulario (elementos, grupos de visualización y subformularios) y los renderizará,
            devolviendo el resultado. Luego se pueden usar decoradores adicionales para
            envolver este contenido, o añadirlo al principio o al final.
        </p>
<p>
            Los decoradores por defecto para <code class="classname">Zend_Form</code> son FormElements,
            HtmlTag (que envuelve en una lista de definición) y Form; el código equivalente
            para crearlos es el siguiente:
        </p>
<pre class="programlisting">
$form-&gt;setDecorators(array(
    'FormElements',
    array('HtmlTag', array('tag' =&gt; 'dl')),
    'Form'
));
</pre>
<p>
            Esto crea una salida como la siguiente:
        </p>
<pre class="programlisting">
&lt;form action="/form/action" method="post"&gt;
&lt;dl&gt;
...
&lt;/dl&gt;
&lt;/form&gt;
</pre>
<p>
            Cualquier atributo establecido en el objeto de formulario se usará como atributos <acronym class="acronym">HTML</acronym>
            de la etiqueta <span class="emphasis"><em>&lt;form&gt;</em></span>.
        </p>
<div class="note"><table border="0" summary="Note: Default Decorators Do Not Need to Be Loaded">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">No es necesario cargar los decoradores por defecto</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Por defecto, los decoradores por defecto se cargan durante la inicialización del
                objeto. Puede deshabilitar esto pasando la
                opción 'disableLoadDefaultDecorators' al constructor:
            </p>
<pre class="programlisting">
$form = new Zend_Form(array('disableLoadDefaultDecorators' =&gt; true));
</pre>
<p>
                Esta opción puede combinarse con cualquier otra opción que se pase,
                tanto como opciones de array como en un objeto <code class="classname">Zend_Config</code>.
            </p>
</td></tr>
</table></div>
<div class="note"><table border="0" summary="Note: Using Multiple Decorators of the Same Type">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Uso de múltiples decoradores del mismo tipo</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Internamente, <code class="classname">Zend_Form</code> usa la clase de un
                decorador como mecanismo de búsqueda al recuperar decoradores. Como
                resultado, no puede registrar varios decoradores del mismo
                tipo; los decoradores posteriores simplemente sobrescribirán los que
                existían antes.
            </p>
<p>
                Para evitar esto, puede usar alias. En lugar de pasar un
                decorador o un nombre de decorador como primer argumento a
                <code class="methodname">addDecorator()</code>, pase un array con un único
                elemento, con el alias apuntando al objeto o nombre de
                decorador:
            </p>
<pre class="programlisting">
// Alias to 'FooBar':
$form-&gt;addDecorator(array('FooBar' =&gt; 'HtmlTag'), array('tag' =&gt; 'div'));

// And retrieve later:
$form = $element-&gt;getDecorator('FooBar');
</pre>
<p>
                En los métodos <code class="methodname">addDecorators()</code> y
                <code class="methodname">setDecorators()</code>, deberá pasar la
                opción 'decorator' en el array que representa al decorador:
            </p>
<pre class="programlisting">
// Add two 'HtmlTag' decorators, aliasing one to 'FooBar':
$form-&gt;addDecorators(
    array('HtmlTag', array('tag' =&gt; 'div')),
    array(
        'decorator' =&gt; array('FooBar' =&gt; 'HtmlTag'),
        'options' =&gt; array('tag' =&gt; 'dd')
    ),
);

// And retrieve later:
$htmlTag = $form-&gt;getDecorator('HtmlTag');
$fooBar  = $form-&gt;getDecorator('FooBar');
</pre>
</td></tr>
</table></div>
<p>
            Puede crear sus propios decoradores para generar el formulario. Un
            caso de uso común es cuando conoce exactamente el <acronym class="acronym">HTML</acronym> que desea usar; su
            decorador podría crear ese <acronym class="acronym">HTML</acronym> exacto y simplemente devolverlo,
            potencialmente usando los decoradores de elementos individuales o de grupos
            de visualización.
        </p>
<p>
            Los siguientes métodos pueden usarse para interactuar con decoradores:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">addDecorator($decorator, $options = null)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addDecorators(array $decorators)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setDecorators(array $decorators)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getDecorator($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getDecorators()</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">removeDecorator($name)</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">clearDecorators()</code>
                    </p></li>
</ul></div>
<p>
            <code class="classname">Zend_Form</code> también usa sobrecarga para permitir renderizar
            decoradores específicos. <code class="methodname">__call()</code> interceptará métodos
            cuyo nombre comience con el texto 'render' y usará el resto del nombre del
            método para buscar un decorador; si lo encuentra, renderizará ese
            <span class="emphasis"><em>único</em></span> decorador. Cualquier argumento pasado al
            método de llamada se usará como contenido para pasar al método
            <code class="methodname">render()</code> del decorador. Como ejemplo:
        </p>
<pre class="programlisting">
// Render only the FormElements decorator:
echo $form-&gt;renderFormElements();

// Render only the fieldset decorator, passing in content:
echo $form-&gt;renderFieldset("&lt;p&gt;This is fieldset content&lt;/p&gt;");
</pre>
<p>
            Si el decorador no existe, se lanza una excepción.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.validation"></a>36.4.7. Validación</h3></div></div></div>
<p>
            Un caso de uso principal de los formularios es validar los datos enviados.
            <code class="classname">Zend_Form</code> permite validar un formulario completo, un formulario parcial,
            o respuestas para XmlHttpRequests (AJAX). Si los datos enviados no son válidos, dispone de
            métodos para recuperar los diversos códigos y mensajes de error para
            elementos y subformularios.
        </p>
<p>
            Para validar un formulario completo, use el método <code class="methodname">isValid()</code>:
        </p>
<pre class="programlisting">
if (!$form-&gt;isValid($_POST)) {
    // failed validation
}
</pre>
<p>
            <code class="methodname">isValid()</code> validará todos los elementos requeridos, y cualquier
            elemento no requerido contenido en los datos enviados.
        </p>
<p>
            En ocasiones necesitará validar solo un subconjunto de los datos; para
            esto, use <code class="methodname">isValidPartial($data)</code>:
        </p>
<pre class="programlisting">
if (!$form-&gt;isValidPartial($data)) {
    // failed validation
}
</pre>
<p>
            <code class="methodname">isValidPartial()</code> solo intenta validar los elementos de
            los datos para los que existen elementos coincidentes; si un elemento no
            está representado en los datos, se omite.
        </p>
<p>
            Al validar elementos o grupos de elementos para una petición <acronym class="acronym">AJAX</acronym>,
            normalmente estará validando un subconjunto del formulario, y querrá que la
            respuesta vuelva en <acronym class="acronym">JSON</acronym>. <code class="methodname">processAjax()</code> hace
            exactamente eso:
        </p>
<pre class="programlisting">
$json = $form-&gt;processAjax($data);
</pre>
<p>
            Puede entonces simplemente enviar la respuesta <acronym class="acronym">JSON</acronym> al cliente. Si el
            formulario es válido, esto será una respuesta booleana <code class="constant">TRUE</code>. Si no,
            será un objeto javascript que contiene pares clave/mensaje, donde cada
            'message' es un array de mensajes de error de validación.
        </p>
<p>
            Para los formularios que fallan la validación, puede recuperar tanto los códigos
            como los mensajes de error, usando <code class="methodname">getErrors()</code> y
            <code class="methodname">getMessages()</code>, respectivamente:
        </p>
<pre class="programlisting">
$codes = $form-&gt;getErrors();
$messages = $form-&gt;getMessages();
</pre>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Dado que los mensajes devueltos por <code class="methodname">getMessages()</code> son un
                array de pares código/mensaje de error, <code class="methodname">getErrors()</code>
                normalmente no es necesario.
            </p></td></tr>
</table></div>
<p>
            Puede recuperar códigos y mensajes de error para elementos individuales
            simplemente pasando el nombre del elemento a cada uno:
        </p>
<pre class="programlisting">
$codes = $form-&gt;getErrors('username');
$messages = $form-&gt;getMessages('username');
</pre>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Nota: al validar elementos, <code class="classname">Zend_Form</code> envía un
                segundo argumento al método <code class="methodname">isValid()</code> de cada elemento:
                el array de datos que se está validando. Esto puede luego ser usado por
                validadores individuales para permitirles utilizar otros valores
                enviados al determinar la validez de los datos. Un ejemplo
                sería un formulario de registro que requiere tanto una contraseña como
                una confirmación de contraseña; el elemento contraseña podría usar la
                confirmación de contraseña como parte de su validación.
            </p></td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.validation.errors"></a>36.4.7.1. Mensajes de error personalizados</h4></div></div></div>
<p>
                En ocasiones, puede que desee especificar uno o más mensajes de error
                específicos para usar en lugar de los mensajes de error generados por los
                validadores adjuntos a sus elementos. Además, en ocasiones
                puede que desee marcar el formulario como inválido usted mismo. Esta
                funcionalidad es posible mediante los siguientes métodos.
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">addErrorMessage($message)</code>: añade un mensaje de error
                        para mostrar en los errores de validación del formulario. Puede llamar a esto más
                        de una vez, y los nuevos mensajes se añaden a la pila.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addErrorMessages(array $messages)</code>: añade varios
                        mensajes de error para mostrar en los errores de validación del formulario.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setErrorMessages(array $messages)</code>: añade varios
                        mensajes de error para mostrar en los errores de validación del formulario,
                        sobrescribiendo todos los mensajes de error previamente establecidos.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getErrorMessages()</code>: recupera la lista de
                        mensajes de error personalizados que se han definido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">clearErrorMessages()</code>: elimina todos los mensajes de
                        error personalizados que se han definido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">markAsError()</code>: marca el formulario como
                        que ha fallado la validación.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addError($message)</code>: añade un mensaje a la pila de
                        mensajes de error personalizados y marca el formulario como inválido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">addErrors(array $messages)</code>: añade varios
                        mensajes a la pila de mensajes de error personalizados y marca el
                        formulario como inválido.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">setErrors(array $messages)</code>: sobrescribe la
                        pila de mensajes de error personalizados con los mensajes proporcionados y
                        marca el formulario como inválido.
                    </p></li>
</ul></div>
<p>
                Todos los errores establecidos de esta manera pueden traducirse.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.form.forms.validation.values"></a>36.4.7.2. Recuperación de solo los valores válidos</h4></div></div></div>
<p>
                Hay escenarios en los que se desea permitir al usuario trabajar en un formulario válido
                en varios pasos. Mientras tanto, se permite al usuario guardar el formulario con cualquier
                conjunto de valores intermedios. Luego, si se especifican todos los datos, se puede transferir
                el modelo de la etapa de construcción o prototipado a una etapa válida.
            </p>
<p>
                Puede recuperar todos los valores válidos que coincidan con los datos enviados llamando a:
            </p>
<pre class="programlisting">
$validValues = $form-&gt;getValidValues($_POST);
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.methods"></a>36.4.8. Métodos</h3></div></div></div>
<p>
            A continuación se muestra una lista completa de los métodos disponibles para
            <code class="classname">Zend_Form</code>, agrupados por tipo:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>Configuración y opciones:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p><code class="methodname">setOptions(array $options)</code></p></li>
<li class="listitem"><p><code class="methodname">setConfig(Zend_Config $config)</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Cargadores de plugins y rutas:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">setPluginLoader(Zend_Loader_PluginLoader_Interface $loader,
                                $type = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">getPluginLoader($type = null)</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">addPrefixPath($prefix, $path, $type = null) </code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addPrefixPaths(array $spec)</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">addElementPrefixPath($prefix, $path, $type
                                = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addElementPrefixPaths(array $spec)</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">addDisplayGroupPrefixPath($prefix, $path)</code>
                        </p></li>
</ul></div>
</li>
<li class="listitem">
<p>Metadatos:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p><code class="methodname">setAttrib($key, $value)</code></p></li>
<li class="listitem"><p><code class="methodname">addAttribs(array $attribs)</code></p></li>
<li class="listitem"><p><code class="methodname">setAttribs(array $attribs)</code></p></li>
<li class="listitem"><p><code class="methodname">getAttrib($key)</code></p></li>
<li class="listitem"><p><code class="methodname">getAttribs()</code></p></li>
<li class="listitem"><p><code class="methodname">removeAttrib($key)</code></p></li>
<li class="listitem"><p><code class="methodname">clearAttribs()</code></p></li>
<li class="listitem"><p><code class="methodname">setAction($action)</code></p></li>
<li class="listitem"><p><code class="methodname">getAction()</code></p></li>
<li class="listitem"><p><code class="methodname">setMethod($method)</code></p></li>
<li class="listitem"><p><code class="methodname">getMethod()</code></p></li>
<li class="listitem"><p><code class="methodname">setName($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getName()</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Elementos:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">addElement($element, $name = null, $options
                                = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addElements(array $elements)</code></p></li>
<li class="listitem"><p><code class="methodname">setElements(array $elements)</code></p></li>
<li class="listitem"><p><code class="methodname">getElement($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getElements()</code></p></li>
<li class="listitem"><p><code class="methodname">removeElement($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearElements()</code></p></li>
<li class="listitem"><p><code class="methodname">setDefaults(array $defaults)</code></p></li>
<li class="listitem"><p><code class="methodname">setDefault($name, $value)</code></p></li>
<li class="listitem"><p><code class="methodname">getValue($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getValues()</code></p></li>
<li class="listitem"><p><code class="methodname">getUnfilteredValue($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getUnfilteredValues()</code></p></li>
<li class="listitem"><p><code class="methodname">setElementFilters(array $filters)</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">setElementDecorators(array $decorators)</code>
                        </p></li>
</ul></div>
</li>
<li class="listitem">
<p>Subformularios:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">addSubForm(Zend_Form $form, $name, $order
                                = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addSubForms(array $subForms)</code></p></li>
<li class="listitem"><p><code class="methodname">setSubForms(array $subForms)</code></p></li>
<li class="listitem"><p><code class="methodname">getSubForm($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getSubForms()</code></p></li>
<li class="listitem"><p><code class="methodname">removeSubForm($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearSubForms()</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">setSubFormDecorators(array $decorators)</code>
                        </p></li>
</ul></div>
</li>
<li class="listitem">
<p>Grupos de visualización:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">addDisplayGroup(array $elements, $name, $options
                                = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addDisplayGroups(array $groups)</code></p></li>
<li class="listitem"><p><code class="methodname">setDisplayGroups(array $groups)</code></p></li>
<li class="listitem"><p><code class="methodname">getDisplayGroup($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getDisplayGroups()</code></p></li>
<li class="listitem"><p><code class="methodname">removeDisplayGroup($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearDisplayGroups()</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">setDisplayGroupDecorators(array $decorators)</code>
                        </p></li>
</ul></div>
</li>
<li class="listitem">
<p>Validación</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p><code class="methodname">populate(array $values)</code></p></li>
<li class="listitem"><p><code class="methodname">isValid(array $data)</code></p></li>
<li class="listitem"><p><code class="methodname">isValidPartial(array $data)</code></p></li>
<li class="listitem"><p><code class="methodname">processAjax(array $data)</code></p></li>
<li class="listitem"><p><code class="methodname">persistData()</code></p></li>
<li class="listitem"><p><code class="methodname">getErrors($name = null)</code></p></li>
<li class="listitem"><p><code class="methodname">getMessages($name = null)</code></p></li>
</ul></div>
</li>
<li class="listitem">
<p>Renderizado:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">setView(Zend_View_Interface $view = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">getView()</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">addDecorator($decorator, $options = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">addDecorators(array $decorators)</code></p></li>
<li class="listitem"><p><code class="methodname">setDecorators(array $decorators)</code></p></li>
<li class="listitem"><p><code class="methodname">getDecorator($name)</code></p></li>
<li class="listitem"><p><code class="methodname">getDecorators()</code></p></li>
<li class="listitem"><p><code class="methodname">removeDecorator($name)</code></p></li>
<li class="listitem"><p><code class="methodname">clearDecorators()</code></p></li>
<li class="listitem"><p>
                            <code class="methodname">render(Zend_View_Interface $view = null)</code>
                        </p></li>
</ul></div>
</li>
<li class="listitem">
<p>I18n:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <code class="methodname">setTranslator(Zend_Translate_Adapter $translator
                                = null)</code>
                        </p></li>
<li class="listitem"><p><code class="methodname">getTranslator()</code></p></li>
<li class="listitem"><p><code class="methodname">setDisableTranslator($flag)</code></p></li>
<li class="listitem"><p><code class="methodname">translatorIsDisabled()</code></p></li>
</ul></div>
</li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.config"></a>36.4.9. Configuración</h3></div></div></div>
<p>
            <code class="classname">Zend_Form</code> es totalmente configurable mediante
            <code class="methodname">setOptions()</code> y <code class="methodname">setConfig()</code> (o pasando
            opciones o un objeto <code class="classname">Zend_Config</code> al
            constructor). Usando estos métodos, puede especificar elementos de formulario,
            grupos de visualización, decoradores y metadatos.
        </p>
<p>
            Como regla general, si 'set' + la clave de la opción se refiere a un
            método de <code class="classname">Zend_Form</code>, entonces el valor proporcionado se
            pasará a ese método. Si el método de acceso no existe, se asume que la clave
            hace referencia a un atributo, y se pasará a
            <code class="methodname">setAttrib()</code>.
        </p>
<p>
            Las excepciones a la regla incluyen las siguientes:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="property">prefixPath</span> se pasará a
                    <code class="methodname">addPrefixPaths()</code>
                </p></li>
<li class="listitem"><p>
                    <span class="property">elementPrefixPath</span> se pasará a
                    <code class="methodname">addElementPrefixPaths()</code>
                </p></li>
<li class="listitem"><p>
                    <span class="property">displayGroupPrefixPath</span> se pasará a
                    <code class="methodname">addDisplayGroupPrefixPaths()</code>
                </p></li>
<li class="listitem">
<p>los siguientes setters no pueden establecerse de esta manera:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p><span class="property">setAttrib</span> (aunque setAttribs *sí* funciona)</p></li>
<li class="listitem"><p><span class="property">setConfig</span></p></li>
<li class="listitem"><p><span class="property">setDefault</span></p></li>
<li class="listitem"><p><span class="property">setOptions</span></p></li>
<li class="listitem"><p><span class="property">setPluginLoader</span></p></li>
<li class="listitem"><p><span class="property">setSubForms</span></p></li>
<li class="listitem"><p><span class="property">setTranslator</span></p></li>
<li class="listitem"><p><span class="property">setView</span></p></li>
</ul></div>
</li>
</ul></div>
<p>
            Como ejemplo, aquí hay un archivo de configuración que pasa configuración para
            cada tipo de dato configurable:
        </p>
<pre class="programlisting">
[element]
name = "registration"
action = "/user/register"
method = "post"
attribs.class = "zend_form"
attribs.onclick = "validate(this)"

disableTranslator = 0

prefixPath.element.prefix = "My_Element"
prefixPath.element.path = "My/Element/"
elementPrefixPath.validate.prefix = "My_Validate"
elementPrefixPath.validate.path = "My/Validate/"
displayGroupPrefixPath.prefix = "My_Group"
displayGroupPrefixPath.path = "My/Group/"

elements.username.type = "text"
elements.username.options.label = "Username"
elements.username.options.validators.alpha.validator = "Alpha"
elements.username.options.filters.lcase = "StringToLower"
; more elements, of course...

elementFilters.trim = "StringTrim"
;elementDecorators.trim = "StringTrim"

displayGroups.login.elements.username = "username"
displayGroups.login.elements.password = "password"
displayGroupDecorators.elements.decorator = "FormElements"
displayGroupDecorators.fieldset.decorator = "Fieldset"

decorators.elements.decorator = "FormElements"
decorators.fieldset.decorator = "FieldSet"
decorators.fieldset.decorator.options.class = "zend_form"
decorators.form.decorator = "Form"
</pre>
<p>
            Lo anterior podría abstraerse fácilmente a un archivo de configuración basado en
            <acronym class="acronym">XML</acronym> o en un array de <acronym class="acronym">PHP</acronym>.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.form.forms.custom"></a>36.4.10. Formularios personalizados</h3></div></div></div>
<p>
            Una alternativa al uso de formularios basados en configuración es subclasificar
            <code class="classname">Zend_Form</code>. Esto tiene varios beneficios:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    Puede probar unitariamente su formulario fácilmente para asegurar que las validaciones y
                    el renderizado se comportan como se espera.
                </p></li>
<li class="listitem"><p>
                    Control detallado sobre elementos individuales.
                </p></li>
<li class="listitem"><p>
                    Reutilización de objetos de formulario, y mayor portabilidad (sin necesidad de
                    rastrear archivos de configuración).
                </p></li>
<li class="listitem"><p>
                    Implementación de funcionalidad personalizada.
                </p></li>
</ul></div>
<p>
            El caso de uso más típico sería usar el
            método <code class="methodname">init()</code> para configurar elementos de formulario específicos y
            la configuración:
        </p>
<pre class="programlisting">
class My_Form_Login extends Zend_Form
{
    public function init()
    {
        $username = new Zend_Form_Element_Text('username');
        $username-&gt;class = 'formtext';
        $username-&gt;setLabel('Username:')
                 -&gt;setDecorators(array(
                     array('ViewHelper',
                           array('helper' =&gt; 'formText')),
                     array('Label',
                           array('class' =&gt; 'label'))
                 ));

        $password = new Zend_Form_Element_Password('password');
        $password-&gt;class = 'formtext';
        $password-&gt;setLabel('Password:')
                 -&gt;setDecorators(array(
                     array('ViewHelper',
                           array('helper' =&gt; 'formPassword')),
                     array('Label',
                           array('class' =&gt; 'label'))
                 ));

        $submit = new Zend_Form_Element_Submit('login');
        $submit-&gt;class = 'formsubmit';
        $submit-&gt;setValue('Login')
               -&gt;setDecorators(array(
                   array('ViewHelper',
                   array('helper' =&gt; 'formSubmit'))
               ));

        $this-&gt;addElements(array(
            $username,
            $password,
            $submit
        ));

        $this-&gt;setDecorators(array(
            'FormElements',
            'Fieldset',
            'Form'
        ));
    }
}
</pre>
<p>
            Este formulario puede entonces instanciarse simplemente con:
        </p>
<pre class="programlisting">
$form = new My_Form_Login();
</pre>
<p>
            y toda la funcionalidad ya está configurada y lista; no se necesitan archivos de
            configuración. (Tenga en cuenta que este ejemplo está muy simplificado, ya que
            no contiene validadores ni filtros para los elementos.)
        </p>
<p>
            Otra razón común para la extensión es definir un conjunto de
            decoradores por defecto. Puede hacer esto sobrescribiendo el
            método <code class="methodname">loadDefaultDecorators()</code>:
        </p>
<pre class="programlisting">
class My_Form_Login extends Zend_Form
{
    public function loadDefaultDecorators()
    {
        $this-&gt;setDecorators(array(
            'FormElements',
            'Fieldset',
            'Form'
        ));
    }
}
</pre>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.form.elements.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.form.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.form.decorators.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">36.3. Creación de elementos de formulario usando Zend_Form_Element </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 36.5. Creación de marcado de formulario personalizado usando Zend_Form_Decorator</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
