<?php $title = 'Capítulo 65. Zend_Session'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 65. Zend_Session</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.yahoo.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.session.basic_usage.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.session"></a>Capítulo 65. Zend_Session</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.session.phtml#zend.session.introduction">65.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.session.basic_usage.phtml">65.2. Uso básico</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.session.basic_usage.phtml#zend.session.basic_usage.basic_examples">65.2.1. Ejemplos del tutorial</a></span></dt>
<dt><span class="sect2"><a href="zend.session.basic_usage.phtml#zend.session.basic_usage.iteration">65.2.2. Iterando sobre espacios de nombres de sesión</a></span></dt>
<dt><span class="sect2"><a href="zend.session.basic_usage.phtml#zend.session.basic_usage.accessors">65.2.3. Accesores para espacios de nombres de sesión</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.session.advanced_usage.phtml">65.3. Uso avanzado</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.session.advanced_usage.phtml#zend.session.advanced_usage.starting_a_session">65.3.1. Iniciando una sesión</a></span></dt>
<dt><span class="sect2"><a href="zend.session.advanced_usage.phtml#zend.session.advanced_usage.locking">65.3.2. Bloqueo de espacios de nombres de sesión</a></span></dt>
<dt><span class="sect2"><a href="zend.session.advanced_usage.phtml#zend.session.advanced_usage.expiration">65.3.3. Expiración de espacios de nombres</a></span></dt>
<dt><span class="sect2"><a href="zend.session.advanced_usage.phtml#zend.session.advanced_usage.controllers">65.3.4. Encapsulación de sesiones y controladores</a></span></dt>
<dt><span class="sect2"><a href="zend.session.advanced_usage.phtml#zend.session.advanced_usage.single_instance">65.3.5. Evitar múltiples instancias por espacio de nombres</a></span></dt>
<dt><span class="sect2"><a href="zend.session.advanced_usage.phtml#zend.session.advanced_usage.arrays">65.3.6. Trabajar con arrays</a></span></dt>
<dt><span class="sect2"><a href="zend.session.advanced_usage.phtml#zend.session.advanced_usage.objects">65.3.7. Uso de sesiones con objetos</a></span></dt>
<dt><span class="sect2"><a href="zend.session.advanced_usage.phtml#zend.session.advanced_usage.testing">65.3.8. Uso de sesiones con pruebas unitarias</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.session.global_session_management.phtml">65.4. Gestión global de sesiones</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.configuration_options">65.4.1. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.headers_sent">65.4.2. Error: Cabeceras ya enviadas</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.session_identifiers">65.4.3. Identificadores de sesión</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.session_identifiers.hijacking_and_fixation">65.4.3.1. Secuestro y fijación de sesión</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.rememberme">65.4.4. rememberMe(integer $seconds)</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.forgetme">65.4.5. forgetMe()</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.sessionexists">65.4.6. sessionExists()</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.destroy">65.4.7. destroy(bool $remove_cookie = true, bool $readonly = true)</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.stop">65.4.8. stop()</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.writeclose">65.4.9. writeClose($readonly = true)</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.expiresessioncookie">65.4.10. expireSessionCookie()</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.savehandler">65.4.11. setSaveHandler(Zend_Session_SaveHandler_Interface $interface)</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.namespaceisset">65.4.12. namespaceIsset($namespace)</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.namespaceunset">65.4.13. namespaceUnset($namespace)</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.namespaceget">65.4.14. namespaceGet($namespace)</a></span></dt>
<dt><span class="sect2"><a href="zend.session.global_session_management.phtml#zend.session.global_session_management.getiterator">65.4.15. getIterator()</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.session.savehandler.dbtable.phtml">65.5. Zend_Session_SaveHandler_DbTable</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.session.introduction"></a>65.1. Introducción</h2></div></div></div>
<p>
        El equipo de Zend Framework Auth agradece enormemente sus comentarios y contribuciones en
        nuestra lista de correo: <a class="ulink" href="mailto:fw-auth@lists.zend.com" target="_top">fw-auth@lists.zend.com</a>
    </p>
<p>
        En las aplicaciones web escritas usando <acronym class="acronym">PHP</acronym>, una <span class="emphasis"><em>sesión</em></span>
        representa una conexión lógica, uno a uno, entre datos de estado persistentes del lado del
        servidor y un cliente de agente de usuario particular (por ejemplo, un navegador web). <code class="classname">Zend_Session</code> ayuda
        a gestionar y preservar los datos de sesión, un complemento lógico de los datos de cookies, a través de múltiples
        peticiones de página del mismo cliente. A diferencia de los datos de cookies, los datos de sesión no se almacenan en el lado
        del cliente y solo se comparten con el cliente cuando el código fuente del lado del servidor pone
        voluntariamente los datos a disposición en respuesta a una petición del cliente. A efectos de este componente y
        esta documentación, el término "datos de sesión" se refiere a los datos del lado del servidor almacenados en <a class="ulink" href="http://www.php.net/manual/en/reserved.variables.php#reserved.variables.session" target="_top"><code class="varname">$_SESSION</code></a>,
        gestionados por <code class="classname">Zend_Session</code>, y manipulados individualmente por
        los objetos accesores de <code class="classname">Zend_Session_Namespace</code>.
        Los <span class="emphasis"><em>espacios de nombres de sesión</em></span> proporcionan acceso a los datos de sesión usando los clásicos <a class="ulink" href="http://en.wikipedia.org/wiki/Namespace_%28computer_science%29" target="_top">espacios de nombres</a>
        implementados lógicamente como grupos con nombre de arrays asociativos, indexados por cadenas (similar a
        los arrays normales de <acronym class="acronym">PHP</acronym>).
    </p>
<p>
        Las instancias de <code class="classname">Zend_Session_Namespace</code> son objetos accesores para porciones
        con espacio de nombres de <code class="varname">$_SESSION</code>. El componente <code class="classname">Zend_Session</code>
        envuelve la extensión ext/session existente de <acronym class="acronym">PHP</acronym> con una interfaz de administración y gestión,
        además de proporcionar una <acronym class="acronym">API</acronym> para que
        <code class="classname">Zend_Session_Namespace</code> persista los espacios de nombres de sesión.
        <code class="classname">Zend_Session_Namespace</code> proporciona una interfaz estandarizada y orientada a objetos
        para trabajar con espacios de nombres persistidos dentro del mecanismo de sesión estándar de <acronym class="acronym">PHP</acronym>.
        Existe soporte tanto para espacios de nombres de sesión anónimos como autenticados (por ejemplo, de "inicio de sesión").
        <code class="classname">Zend_Auth</code>, el componente de autenticación de Zend
        Framework, utiliza <code class="classname">Zend_Session_Namespace</code> para almacenar cierta información
        asociada con usuarios autenticados. Dado que <code class="classname">Zend_Session</code> utiliza
        internamente las funciones normales de ext/session de <acronym class="acronym">PHP</acronym>, se aplican todas las
        opciones y ajustes de configuración habituales (véase <a class="ulink" href="http://www.php.net/session" target="_top">http://www.php.net/session</a>), con bonificaciones
        como la comodidad de una interfaz orientada a objetos y un comportamiento por defecto que proporciona tanto
        buenas prácticas como una integración fluida con Zend Framework. Así, un
        identificador de sesión estándar de <acronym class="acronym">PHP</acronym>, ya sea transmitido mediante cookie o dentro de
        <acronym class="acronym">URL</acronym>s, mantiene la asociación entre un cliente y los datos de estado de la sesión.
    </p>
<p>
        El
        <a class="ulink" href="http://www.php.net/manual/en/function.session-set-save-handler.php" target="_top">manejador de guardado de ext/session</a>
        por defecto no mantiene esta asociación para clústeres de servidores en ciertas
        condiciones, ya que los datos de sesión se almacenan en el sistema de archivos del servidor que respondió a
        la petición. Si una petición puede ser procesada por un servidor distinto de aquel en el que se encuentran
        los datos de sesión, entonces el servidor que responde no tiene acceso a los datos de sesión (si
        no están disponibles desde un sistema de archivos en red). Se proporcionará una lista de manejadores de guardado
        adicionales apropiados, cuando estén disponibles. Se anima a los miembros de la comunidad a sugerir y
        enviar manejadores de guardado a la lista <a class="ulink" href="mailto:fw-auth@lists.zend.com" target="_top">fw-auth@lists.zend.com</a>. Se ha publicado en la lista un
        manejador de guardado compatible con <code class="classname">Zend_Db</code>.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.yahoo.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.session.basic_usage.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.38. Zend_Service_Yahoo </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 65.2. Uso básico</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
