<?php $title = 'Capítulo 39. Zend_Json'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 39. Zend_Json</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.http.user-agent-storage-session.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.json.basics.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.json"></a>Capítulo 39. Zend_Json</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.json.phtml#zend.json.introduction">39.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.json.basics.phtml">39.2. Uso básico</a></span></dt>
<dd><dl><dt><span class="sect2"><a href="zend.json.basics.phtml#zend.json.basics.prettyprint">39.2.1. Imprimir JSON con formato legible</a></span></dt></dl></dd>
<dt><span class="sect1"><a href="zend.json.advanced.phtml">39.3. Uso avanzado de Zend_Json</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.json.advanced.phtml#zend.json.advanced.objects1">39.3.1. Objetos JSON</a></span></dt>
<dt><span class="sect2"><a href="zend.json.advanced.phtml#zend.json.advanced.objects2">39.3.2. Codificar objetos PHP</a></span></dt>
<dt><span class="sect2"><a href="zend.json.advanced.phtml#zend.json.advanced.internal">39.3.3. Codificador/Decodificador interno</a></span></dt>
<dt><span class="sect2"><a href="zend.json.advanced.phtml#zend.json.advanced.expr">39.3.4. Expresiones JSON</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.json.xml2json.phtml">39.4. Conversión de XML a JSON</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.json.xml2json.phtml#zend.json.xml2json.changes">39.4.1. Cambios</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.json.xml2json.phtml#zend.json.xml2json.changes.1-11-6">39.4.1.1. Cambios en la versión 1.11.6</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.json.server.phtml">39.5. Zend_Json_Server - servidor JSON-RPC</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.json.server.phtml#zend.json.server.details">39.5.1. Detalles avanzados</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.json.server.phtml#zend.json.server.details.zendjsonserver">39.5.1.1. Zend_Json_Server</a></span></dt>
<dt><span class="sect3"><a href="zend.json.server.phtml#zend.json.server.details.zendjsonserverrequest">39.5.1.2. Zend_Json_Server_Request</a></span></dt>
<dt><span class="sect3"><a href="zend.json.server.phtml#zend.json.server.details.zendjsonserverresponse">39.5.1.3. Zend_Json_Server_Response</a></span></dt>
<dt><span class="sect3"><a href="zend.json.server.phtml#zend.json.server.details.zendjsonservererror">39.5.1.4. Zend_Json_Server_Error</a></span></dt>
<dt><span class="sect3"><a href="zend.json.server.phtml#zend.json.server.details.zendjsonserversmd">39.5.1.5. Zend_Json_Server_Smd</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.json.introduction"></a>39.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Json</code> proporciona métodos de conveniencia para serializar
        <acronym class="acronym">PHP</acronym> nativo a <acronym class="acronym">JSON</acronym> y decodificar <acronym class="acronym">JSON</acronym> a
        <acronym class="acronym">PHP</acronym> nativo. Para obtener más información sobre <acronym class="acronym">JSON</acronym>, <a class="ulink" href="http://www.json.org/" target="_top">visite el sitio del proyecto <acronym class="acronym">JSON</acronym></a>.
    </p>
<p>
        <acronym class="acronym">JSON</acronym>, JavaScript Object Notation, puede usarse para el intercambio
        de datos entre JavaScript y otros lenguajes. Dado que <acronym class="acronym">JSON</acronym> puede
        evaluarse directamente mediante JavaScript, es un formato más eficiente y ligero
        que <acronym class="acronym">XML</acronym> para intercambiar datos con clientes JavaScript.
    </p>
<p>
        Además, <code class="classname">Zend_Json</code> proporciona una forma útil de convertir cualquier
        cadena con formato <acronym class="acronym">XML</acronym> arbitrario en una cadena con formato
        <acronym class="acronym">JSON</acronym>. Esta funcionalidad incorporada permitirá a los desarrolladores
        <acronym class="acronym">PHP</acronym> transformar los datos empresariales codificados en formato <acronym class="acronym">XML</acronym>
        en formato <acronym class="acronym">JSON</acronym> antes de enviarlos a aplicaciones cliente Ajax basadas en
        el navegador. Proporciona una manera sencilla de realizar la conversión dinámica de datos
        en el código del lado del servidor, evitando así el análisis innecesario de
        <acronym class="acronym">XML</acronym> en las aplicaciones del lado del navegador. Ofrece una práctica
        función que facilita técnicas de procesamiento de datos específicas de la aplicación.
    </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.http.user-agent-storage-session.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.json.basics.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">38.13. El adaptador de almacenamiento UserAgent en sesión </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 39.2. Uso básico</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
