<?php $title = '63.2. Zend_Server_Reflection'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">63.2. Zend_Server_Reflection</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.server.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 63. Zend_Server</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.server.reflection"></a>63.2. Zend_Server_Reflection</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.server.reflection.introduction"></a>63.2.1. Introducción</h3></div></div></div>
<p>
            <code class="classname">Zend_Server_Reflection</code> proporciona un mecanismo estándar para
            realizar introspección de funciones y clases para su uso con clases de servidor. Se basa
            en la <acronym class="acronym">API</acronym> de Reflection de <acronym class="acronym">PHP</acronym> 5,
            aumentándola con métodos para recuperar tipos y descripciones de parámetros y valores de
            retorno, una lista completa de prototipos de funciones y métodos (es decir, todas las
            combinaciones de llamada válidas posibles), y descripciones de funciones o métodos.
        </p>
<p>
            Normalmente, esta funcionalidad solo será utilizada por los desarrolladores de clases de
            servidor del framework.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.server.reflection.usage"></a>63.2.2. Uso</h3></div></div></div>
<p>
            El uso básico es sencillo:
        </p>
<pre class="programlisting">
$class    = Zend_Server_Reflection::reflectClass('My_Class');
$function = Zend_Server_Reflection::reflectFunction('my_function');

// Get prototypes
$prototypes = $reflection-&gt;getPrototypes();

// Loop through each prototype for the function
foreach ($prototypes as $prototype) {

    // Get prototype return type
    echo "Return type: ", $prototype-&gt;getReturnType(), "\n";

    // Get prototype parameters
    $parameters = $prototype-&gt;getParameters();

    echo "Parameters: \n";
    foreach ($parameters as $parameter) {
        // Get parameter type
        echo "    ", $parameter-&gt;getType(), "\n";
    }
}

// Get namespace for a class, function, or method.
// Namespaces may be set at instantiation time (second argument), or using
// setNamespace()
$reflection-&gt;getNamespace();
</pre>
<p>
            <code class="methodname">reflectFunction()</code> devuelve un objeto
            <code class="classname">Zend_Server_Reflection_Function</code>;
            <code class="methodname">reflectClass()</code> devuelve un objeto
            <code class="classname">Zend_Server_Reflection_Class</code>. Consulte la documentación de la
            <acronym class="acronym">API</acronym> para ver qué métodos están disponibles para cada uno.
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.server.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.server.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 63. Zend_Server </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> Capítulo 64. Zend_Service</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
