<?php $title = '38.5. Zend_Http_Response'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">38.5. Zend_Http_Response</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.http.cookies.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 38. Zend_Http</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.http.user-agent.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.http.response"></a>38.5. Zend_Http_Response</h2></div></div></div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.response.introduction"></a>38.5.1. Introducción</h3></div></div></div>
<p>
            <code class="classname">Zend_Http_Response</code> proporciona un acceso sencillo a un
            mensaje de respuesta <acronym class="acronym">HTTP</acronym>, así como un conjunto de métodos estáticos para
            analizar mensajes de respuesta <acronym class="acronym">HTTP</acronym>. Normalmente,
            <code class="classname">Zend_Http_Response</code> se utiliza como un objeto devuelto por una
            solicitud de <code class="classname">Zend_Http_Client</code>.
        </p>
<p>
            En la mayoría de los casos, un objeto <code class="classname">Zend_Http_Response</code> se instanciará
            usando el método fromString(), que lee una cadena que contiene un
            mensaje de respuesta <acronym class="acronym">HTTP</acronym>, y devuelve un nuevo
            objeto <code class="classname">Zend_Http_Response</code>:
            </p>
<div class="example">
<a name="zend.http.response.introduction.example-1"></a><p class="title"><b>Ejemplo 38.30. Instanciación de un objeto Zend_Http_Response mediante el método de fábrica</b></p>
<div class="example-contents"><pre class="programlisting">
$str = '';
$sock = fsockopen('www.example.com', 80);
$req =     "GET / HTTP/1.1\r\n" .
        "Host: www.example.com\r\n" .
        "Connection: close\r\n" .
        "\r\n";

fwrite($sock, $req);
while ($buff = fread($sock, 1024))
    $str .= $sock;

$response = Zend_Http_Response::fromString($str);
</pre></div>
</div>
<p><br class="example-break">
        </p>
<p>
            También puede utilizar el método constructor para crear un nuevo objeto
            de respuesta, especificando todos los parámetros de la respuesta:
        </p>
<p>
            <span class="command"><strong>public function __construct($code, $headers, $body = null, $version = '1.1',
                $message = null)</strong></span>
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <code class="varname">$code</code>: El código de respuesta <acronym class="acronym">HTTP</acronym> (por ejemplo, 200,
                    404, etc.)
                </p></li>
<li class="listitem"><p>
                    <code class="varname">$headers</code>: Un array asociativo de cabeceras de respuesta
                    <acronym class="acronym">HTTP</acronym> (por ejemplo, 'Host' =&gt; 'example.com')
                </p></li>
<li class="listitem"><p>
                    <code class="varname">$body</code>: El cuerpo de la respuesta como cadena de texto
                </p></li>
<li class="listitem"><p>
                    <code class="varname">$version</code>: La versión de respuesta <acronym class="acronym">HTTP</acronym>
                    (normalmente 1.0 o 1.1)
                </p></li>
<li class="listitem"><p>
                    <code class="varname">$message</code>: El mensaje de respuesta <acronym class="acronym">HTTP</acronym> (por ejemplo
                    'OK', 'Internal Server Error'). Si no se especifica, el mensaje se establecerá
                    según el código de respuesta
                </p></li>
</ul></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.response.testers"></a>38.5.2. Métodos de comprobación booleanos</h3></div></div></div>
<p>
            Una vez que se instancia un objeto <code class="classname">Zend_Http_Response</code>, este proporciona
            varios métodos que pueden utilizarse para comprobar el tipo de respuesta. Todos ellos
            devuelven un valor booleano <code class="constant">TRUE</code> o <code class="constant">FALSE</code>:
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">isSuccessful()</code>: Si la solicitud fue exitosa
                        o no. Devuelve <code class="constant">TRUE</code> para los códigos de respuesta <acronym class="acronym">HTTP</acronym>
                        1xx y 2xx
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">isError()</code>: Si el código de respuesta implica un
                        error o no. Devuelve <code class="constant">TRUE</code> para los códigos de respuesta <acronym class="acronym">HTTP</acronym>
                        4xx (errores de cliente) y 5xx (errores de servidor)
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">isRedirect()</code>: Si la respuesta es una respuesta
                        de redirección o no. Devuelve <code class="constant">TRUE</code> para los códigos de respuesta
                        <acronym class="acronym">HTTP</acronym> 3xx
                    </p></li>
</ul></div>
<p>

            </p>
<div class="example">
<a name="zend.http.response.testers.example-1"></a><p class="title"><b>Ejemplo 38.31. Uso del método isError() para validar una respuesta</b></p>
<div class="example-contents"><pre class="programlisting">
if ($response-&gt;isError()) {
  echo "Error transmitting data.\n"
  echo "Server reply was: " . $response-&gt;getStatus() .
       " " . $response-&gt;getMessage() . "\n";
}
// .. process the response here...
</pre></div>
</div>
<p><br class="example-break">
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.response.acessors"></a>38.5.3. Métodos de acceso</h3></div></div></div>
<p>
            El objetivo principal del objeto de respuesta es proporcionar un acceso sencillo a
            los distintos parámetros de la respuesta.
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">getStatus()</code>: Obtiene el código de estado de la
                        respuesta <acronym class="acronym">HTTP</acronym> (por ejemplo, 200, 504, etc.)
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getMessage()</code>: Obtiene el mensaje de estado de la
                        respuesta <acronym class="acronym">HTTP</acronym> (por ejemplo, "Not Found", "Authorization Required")
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getBody()</code>: Obtiene el cuerpo de la respuesta
                        <acronym class="acronym">HTTP</acronym> completamente decodificado
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getRawBody()</code>: Obtiene el cuerpo de la respuesta
                        <acronym class="acronym">HTTP</acronym> en bruto, posiblemente codificado. si el cuerpo fue decodificado usando codificación GZIP
                        por ejemplo, no se decodificará.
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getHeaders()</code>: Obtiene las cabeceras de respuesta
                        <acronym class="acronym">HTTP</acronym> como un array asociativo (por ejemplo, 'Content-type' =&gt; 'text/html')
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getHeader($header)</code>: Obtiene una cabecera de respuesta
                        <acronym class="acronym">HTTP</acronym> específica, indicada por $header
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">getHeadersAsString($status_line, $br)</code>: Obtiene
                        el conjunto completo de cabeceras como una cadena de texto. Si <code class="varname">$status_line</code> es
                        <code class="constant">TRUE</code> (por defecto), también se devolverá la primera línea de estado (por ejemplo, "HTTP/1.1
                        200 OK"). Las líneas se separan con el
                        parámetro <code class="varname">$br</code> (puede ser, por ejemplo, "&lt;br /&gt;".
                        Por defecto "\n")
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">asString($br)</code>: Obtiene el mensaje de respuesta completo como
                        una cadena de texto. Las líneas se separan con el parámetro $br (puede ser, por ejemplo,
                        "&lt;br /&gt;". Por defecto "\n"). También puede usar el método mágico
                        <code class="methodname">__toString()</code> al convertir el objeto en cadena.
                        En ese caso, delegará en <code class="methodname">asString()</code>.
                    </p></li>
</ul></div>
<p>

            </p>
<div class="example">
<a name="zend.http.response.acessors.example-1"></a><p class="title"><b>Ejemplo 38.32. Uso de los métodos de acceso de Zend_Http_Response</b></p>
<div class="example-contents"><pre class="programlisting">
if ($response-&gt;getStatus() == 200) {
  echo "The request returned the following information:&lt;br /&gt;";
  echo $response-&gt;getBody();
} else {
  echo "An error occurred while fetching data:&lt;br /&gt;";
  echo $response-&gt;getStatus() . ": " . $response-&gt;getMessage();
}
</pre></div>
</div>
<p><br class="example-break">

            </p>
<div class="note"><table border="0" summary="Note: Always check return value">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Compruebe siempre el valor devuelto</th>
</tr>
<tr><td align="left" valign="top"><p>
                    Dado que una respuesta puede contener varias instancias de la misma cabecera,
                    el método getHeader() y el método getHeaders() pueden devolver ya sea una
                    única cadena de texto, o un array de cadenas para cada cabecera. Siempre debe
                    comprobar si el valor devuelto es una cadena o un array.
                </p></td></tr>
</table></div>
<p>

            </p>
<div class="example">
<a name="zend.http.response.acessors.example-2"></a><p class="title"><b>Ejemplo 38.33. Acceso a las cabeceras de respuesta</b></p>
<div class="example-contents"><pre class="programlisting">
$ctype = $response-&gt;getHeader('Content-type');
if (is_array($ctype)) $ctype = $ctype[0];

$body = $response-&gt;getBody();
if ($ctype == 'text/html' || $ctype == 'text/xml') {
  $body = htmlentities($body);
}

echo $body;
</pre></div>
</div>
<p><br class="example-break">
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.response.static_parsers"></a>38.5.4. Analizadores estáticos de respuestas HTTP</h3></div></div></div>
<p>
            La clase <code class="classname">Zend_Http_Response</code> también incluye varios
            métodos de uso interno para procesar y analizar mensajes de respuesta <acronym class="acronym">HTTP</acronym>.
            Todos estos métodos se exponen como métodos estáticos, lo que significa que pueden
            utilizarse externamente, incluso si no necesita instanciar un objeto
            de respuesta, y simplemente desea extraer una parte específica de la respuesta.

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::extractCode($response_str)</code>:
                        Extrae y devuelve el código de respuesta <acronym class="acronym">HTTP</acronym> (por ejemplo, 200 o
                        404) de <code class="varname">$response_str</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::extractMessage($response_str)</code>:
                        Extrae y devuelve el mensaje de respuesta <acronym class="acronym">HTTP</acronym> (por ejemplo, "OK" o
                        "File Not Found") de <code class="varname">$response_str</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::extractVersion($response_str)</code>:
                        Extrae y devuelve la versión <acronym class="acronym">HTTP</acronym> (por ejemplo, 1.1 o 1.0) de
                        <code class="varname">$response_str</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::extractHeaders($response_str)</code>:
                        Extrae y devuelve las cabeceras de respuesta <acronym class="acronym">HTTP</acronym> de
                        <code class="varname">$response_str</code> como un array
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::extractBody($response_str)</code>:
                        Extrae y devuelve el cuerpo de la respuesta <acronym class="acronym">HTTP</acronym> de
                        <code class="varname">$response_str</code>
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::responseCodeAsText($code,
                            $http11)</code>: Obtiene el mensaje de respuesta <acronym class="acronym">HTTP</acronym> estándar
                        para un código de respuesta $code. Por ejemplo, devolverá "Internal Server
                        Error" si <code class="varname">$code</code> es 500. Si <code class="varname">$http11</code> es
                        <code class="constant">TRUE</code> (por defecto), devolverá los mensajes estándar
                        de <acronym class="acronym">HTTP</acronym>/1.1 - de lo contrario se devolverán los mensajes de
                        <acronym class="acronym">HTTP</acronym>/1.0. Si
                        <code class="varname">$code</code> no se especifica, este método devolverá todos los códigos de respuesta
                        <acronym class="acronym">HTTP</acronym> conocidos como un array asociativo (código =&gt; mensaje).
                    </p></li>
</ul></div>
<p>
        </p>
<p>
            Aparte de los métodos de análisis, la clase también incluye un conjunto de decodificadores para las
            codificaciones de transferencia de respuesta <acronym class="acronym">HTTP</acronym> comunes:

            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::decodeChunkedBody($body)</code>:
                        Decodifica un cuerpo completo de "Content-Transfer-Encoding: Chunked"
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::decodeGzip($body)</code>: Decodifica
                        un cuerpo de "Content-Encoding: gzip"
                    </p></li>
<li class="listitem"><p>
                        <code class="methodname">Zend_Http_Response::decodeDeflate($body)</code>: Decodifica
                        un cuerpo de "Content-Encoding: deflate"
                    </p></li>
</ul></div>
<p>
        </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.http.cookies.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.http.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.http.user-agent.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">38.4. Zend_Http_Cookie and Zend_Http_CookieJar </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 38.6. Zend_Http_UserAgent</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
