<?php $title = 'autoload'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">autoload</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.get-autoload-map.phtml">Anterior</a> </td>
<th width="60%" align="center">42.8.4. Métodos disponibles</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.loader.class-map-autoloader.methods.register.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="refentry">
<a name="zend.loader.class-map-autoloader.methods.autoload"></a><div class="titlepage"></div>
<div class="refnamediv">
<h2>Nombre</h2>
<p>autoload — Intenta cargar una clase.</p>
</div>
<div class="refsynopsisdiv">
<h2>Sinopsis</h2>
<code class="methodsynopsis"><span class="methodname">autoload</span>(<span class="methodparam">$class</span>);</code>
</div>
<div class="refsection">
<a name="id37276"></a><h2>autoload()</h2>
<p>
                    Intenta cargar la clase especificada. Devuelve un booleano
                    <code class="constant">false</code> en caso de fallo, o una cadena que indica la clase
                    cargada en caso de éxito.
                </p>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.loader.class-map-autoloader.methods.get-autoload-map.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.loader.class-map-autoloader.phtml#zend.loader.class-map-autoloader.methods">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.loader.class-map-autoloader.methods.register.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">getAutoloadMap </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> register</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
