<?php $title = '64.36. Zend_Service_WindowsAzure_Storage_Queue'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">64.36. Zend_Service_WindowsAzure_Storage_Queue</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.service.windowsazure.diagnostics.manager.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 64. Zend_Service</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.service.windowsazure.storage.table.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.service.windowsazure.storage.queue"></a>64.36. Zend_Service_WindowsAzure_Storage_Queue</h2></div></div></div>
<p>
        El servicio Queue almacena mensajes que pueden ser leídos por cualquier cliente que tenga
        acceso a la cuenta de almacenamiento.
    </p>
<p>
        Una cola puede contener un número ilimitado de mensajes, cada uno de los cuales puede tener
        hasta 8 KB de tamaño. Los mensajes generalmente se añaden al final de la cola y se recuperan
        desde el principio de la cola, aunque no se garantiza el comportamiento primero en entrar,
        primero en salir (<acronym class="acronym">FIFO</acronym>). Si necesitas almacenar mensajes
        de más de 8 KB, puedes almacenar los datos del mensaje en una cola o en una tabla y luego
        almacenar una referencia a los datos como mensaje en una cola.
    </p>
<p>
        Queue Storage es ofrecido por Windows Azure como una <acronym class="acronym">API</acronym>
        <acronym class="acronym">REST</acronym> que es envuelta por la clase
        <code class="classname">Zend_Service_WindowsAzure_Storage_Queue</code> con el fin de
        proporcionar una interfaz nativa de <acronym class="acronym">PHP</acronym> para la cuenta de
        almacenamiento.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.service.windowsazure.storage.queue.api"></a>64.36.1. Ejemplos de la API</h3></div></div></div>
<p>
            Este tema enumera algunos ejemplos de uso de la clase
            <code class="classname">Zend_Service_WindowsAzure_Storage_Queue</code>. Otras funcionalidades
            están disponibles en el paquete de descarga, así como una documentación detallada de la
            <acronym class="acronym">API</acronym> de esas funcionalidades.
        </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.storage.queue.api.create-queue"></a>64.36.1.1. Creación de una cola</h4></div></div></div>
<p>
                Utilizando el siguiente código, se puede crear una cola en el almacenamiento de desarrollo.
            </p>
<div class="example">
<a name="zend.service.windowsazure.storage.queue.api.create-queue.example"></a><p class="title"><b>Ejemplo 64.167. Creación de una cola</b></p>
<div class="example-contents"><pre class="programlisting">
$storageClient = new Zend_Service_WindowsAzure_Storage_Queue();
$result = $storageClient-&gt;createQueue('testqueue');

echo 'Queue name is: ' . $result-&gt;Name;
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.storage.queue.api.delete-queue"></a>64.36.1.2. Eliminación de una cola</h4></div></div></div>
<p>
                Utilizando el siguiente código, se puede eliminar una cola del almacenamiento de desarrollo.
            </p>
<div class="example">
<a name="zend.service.windowsazure.storage.queue.api.delete-queue.example"></a><p class="title"><b>Ejemplo 64.168. Eliminación de una cola</b></p>
<div class="example-contents"><pre class="programlisting">
$storageClient = new Zend_Service_WindowsAzure_Storage_Queue();
$storageClient-&gt;deleteQueue('testqueue');
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.storage.queue.api.storing-queue"></a>64.36.1.3. Añadir un mensaje a una cola</h4></div></div></div>
<p>
                Utilizando el siguiente código, se puede añadir un mensaje a una cola en el almacenamiento
                de desarrollo. Ten en cuenta que la cola ya se ha creado previamente.
            </p>
<div class="example">
<a name="zend.service.windowsazure.storage.queue.api.storing-queue.example"></a><p class="title"><b>Ejemplo 64.169. Añadir un mensaje a una cola</b></p>
<div class="example-contents"><pre class="programlisting">
$storageClient = new Zend_Service_WindowsAzure_Storage_Queue();

// 3600 = time-to-live of the message, if omitted defaults to 7 days
$storageClient-&gt;putMessage('testqueue', 'This is a test message', 3600);
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.storage.queue.api.read-queue"></a>64.36.1.4. Lectura de un mensaje de una cola</h4></div></div></div>
<p>
                Utilizando el siguiente código, se puede leer un mensaje de una cola en el almacenamiento
                de desarrollo. Ten en cuenta que la cola y el mensaje ya se han creado previamente.
            </p>
<div class="example">
<a name="zend.service.windowsazure.storage.queue.api.read-queue.example"></a><p class="title"><b>Ejemplo 64.170. Lectura de un mensaje de una cola</b></p>
<div class="example-contents"><pre class="programlisting">
$storageClient = new Zend_Service_WindowsAzure_Storage_Queue();

// retrieve 10 messages at once
$messages = $storageClient-&gt;getMessages('testqueue', 10);

foreach ($messages as $message) {
    echo $message-&gt;MessageText . "\r\n";
}
</pre></div>
</div>
<br class="example-break"><p>
                Los mensajes que se leen usando <code class="methodname">getMessages()</code> serán
                invisibles en la cola durante 30 segundos, tras los cuales los mensajes reaparecerán en
                la cola. Para marcar un mensaje como procesado y eliminarlo de la cola, utiliza el
                método <code class="methodname">deleteMessage()</code>.
            </p>
<div class="example">
<a name="zend.service.windowsazure.storage.queue.api.read-queue.processexample"></a><p class="title"><b>Ejemplo 64.171. Marcar un mensaje como procesado</b></p>
<div class="example-contents"><pre class="programlisting">
$storageClient = new Zend_Service_WindowsAzure_Storage_Queue();

// retrieve 10 messages at once
$messages = $storageClient-&gt;getMessages('testqueue', 10);

foreach ($messages as $message) {
    echo $message . "\r\n";

    // Mark the message as processed
    $storageClient-&gt;deleteMessage('testqueue', $message);
}
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.service.windowsazure.storage.queue.api.peek-queue"></a>64.36.1.5. Comprobar si hay mensajes en una cola</h4></div></div></div>
<p>
                Utilizando el siguiente código, se puede comprobar si una cola tiene nuevos mensajes.
                Ten en cuenta que la cola y el mensaje ya se han creado previamente.
            </p>
<div class="example">
<a name="zend.service.windowsazure.storage.queue.api.peek-queue.example"></a><p class="title"><b>Ejemplo 64.172. Comprobar si hay mensajes en una cola</b></p>
<div class="example-contents"><pre class="programlisting">
$storageClient = new Zend_Service_WindowsAzure_Storage_Queue();

// retrieve 10 messages at once
$messages = $storageClient-&gt;peekMessages('testqueue', 10);

foreach ($messages as $message) {
    echo $message-&gt;MessageText . "\r\n";
}
</pre></div>
</div>
<br class="example-break"><p>
                Ten en cuenta que los mensajes que se leen usando <code class="methodname">peekMessages()</code>
                no se volverán invisibles en la cola, ni pueden marcarse como procesados usando el
                método <code class="methodname">deleteMessage()</code>. Para hacerlo, utiliza
                <code class="methodname">getMessages()</code> en su lugar.
            </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.service.windowsazure.diagnostics.manager.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.service.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.service.windowsazure.storage.table.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">64.35. Zend_Service_WindowsAzure_Diagnostics_Manager </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 64.37. Zend_Service_WindowsAzure_Storage_Table</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
