<?php $title = '45.2. Envío vía SMTP'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">45.2. Envío vía SMTP</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.mail.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 45. Zend_Mail</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.mail.multiple-emails.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.mail.sending"></a>45.2. Envío vía SMTP</h2></div></div></div>
<p>
        Para enviar correo vía SMTP, se debe crear <code class="classname">Zend_Mail_Transport_Smtp</code>
        y registrarlo con <code class="classname">Zend_Mail</code> antes de llamar al método
        <code class="methodname">send()</code>. Para el resto de las llamadas a
        <code class="methodname">Zend_Mail::send()</code> en el script actual, se utilizará entonces
        el transporte SMTP:
    </p>
<div class="example">
<a name="zend.mail.sending.example-1"></a><p class="title"><b>Ejemplo 45.3. Enviar correo electrónico vía SMTP</b></p>
<div class="example-contents"><pre class="programlisting">
$tr = new Zend_Mail_Transport_Smtp('mail.example.com');
Zend_Mail::setDefaultTransport($tr);
</pre></div>
</div>
<br class="example-break"><p>
        El método <code class="methodname">setDefaultTransport()</code> y el constructor de
        <code class="classname">Zend_Mail_Transport_Smtp</code> no son costosos. Estas dos líneas se
        pueden procesar en el momento de configuración del script (por ejemplo, config.inc o similar)
        para configurar el comportamiento de la clase <code class="classname">Zend_Mail</code> durante el
        resto del script. Esto mantiene la información de configuración fuera de la lógica de la
        aplicación, ya sea que el correo se envíe vía SMTP o
        <a class="ulink" href="http://php.net/mail" target="_top"><code class="methodname">mail()</code></a>, qué
        servidor de correo se utiliza, etc.
    </p>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.mail.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.mail.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.mail.multiple-emails.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 45. Zend_Mail </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 45.3. Envío de múltiples correos por conexión SMTP</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
