<?php $title = 'Capítulo 38. Zend_Http'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 38. Zend_Http</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.gdata.exception.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.http.client.advanced.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.http"></a>Capítulo 38. Zend_Http</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.http.phtml#zend.http.client">38.1. Introducción</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.usage">38.1.1. Usando Zend_Http_Client</a></span></dt>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.configuration">38.1.2. Parámetros de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.basic-requests">38.1.3. Realizar peticiones HTTP básicas</a></span></dt>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.parameters">38.1.4. Añadir parámetros GET y POST </a></span></dt>
<dt><span class="sect2"><a href="zend.http.phtml#zend.http.client.accessing_last">38.1.5. Acceder a la última petición y respuesta</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.client.advanced.phtml">38.2. Zend_Http_Client - Uso avanzado</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.redirections">38.2.1. Redirecciones HTTP</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.cookies">38.2.2. Añadir cookies y usar la persistencia de cookies</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.custom_headers">38.2.3. Establecer cabeceras de petición personalizadas</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.file_uploads">38.2.4. Subida de archivos</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.raw_post_data">38.2.5. Enviar datos POST en bruto</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.http_authentication">38.2.6. Autenticación HTTP</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.multiple_requests">38.2.7. Enviar múltiples peticiones con el mismo cliente</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.advanced.phtml#zend.http.client.streaming">38.2.8. Transmisión de datos (streaming)</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.client.adapters.phtml">38.3. Zend_Http_Client - Adaptadores de conexión</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.overview">38.3.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.socket">38.3.2. El adaptador Socket</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.socket.streamcontext">38.3.2.1. Personalizar y acceder al contexto de flujo del adaptador Socket</a></span></dt></dl></dd>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.proxy">38.3.3. El adaptador Proxy</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.curl">38.3.4. El adaptador cURL</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.test">38.3.5. El adaptador de pruebas (Test)</a></span></dt>
<dt><span class="sect2"><a href="zend.http.client.adapters.phtml#zend.http.client.adapters.extending">38.3.6. Crear sus propios adaptadores de conexión</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.cookies.phtml">38.4. Zend_Http_Cookie y Zend_Http_CookieJar</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.introduction">38.4.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookie.instantiating">38.4.2. Instanciar objetos Zend_Http_Cookie</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookie.accessors">38.4.3. Métodos getter de Zend_Http_Cookie</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookie.matching">38.4.4. Zend_Http_Cookie: comparación con un escenario</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookiejar">38.4.5. La clase Zend_Http_CookieJar: instanciación</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookiejar.adding_cookies">38.4.6. Añadir cookies a un objeto Zend_Http_CookieJar</a></span></dt>
<dt><span class="sect2"><a href="zend.http.cookies.phtml#zend.http.cookies.cookiejar.getting_cookies">38.4.7. Recuperar cookies de un objeto Zend_Http_CookieJar</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.response.phtml">38.5. Zend_Http_Response</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.response.phtml#zend.http.response.introduction">38.5.1. Introducción</a></span></dt>
<dt><span class="sect2"><a href="zend.http.response.phtml#zend.http.response.testers">38.5.2. Métodos de prueba booleanos</a></span></dt>
<dt><span class="sect2"><a href="zend.http.response.phtml#zend.http.response.acessors">38.5.3. Métodos de acceso</a></span></dt>
<dt><span class="sect2"><a href="zend.http.response.phtml#zend.http.response.static_parsers">38.5.4. Analizadores estáticos de respuestas HTTP</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent.phtml">38.6. Zend_Http_UserAgent</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.intro">38.6.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.quick-start">38.6.2. Inicio rápido</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.options">38.6.3. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.methods">38.6.4. Métodos disponibles</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent.phtml#zend.http.user-agent.examples">38.6.5. Ejemplos</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-device.phtml">38.7. La interfaz UserAgent Device</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.intro">38.7.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.quick-start">38.7.2. Inicio rápido</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.options">38.7.3. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.methods">38.7.4. Métodos disponibles</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-device.phtml#zend.http.user-agent-device.examples">38.7.5. Ejemplos</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-features.phtml">38.8. El adaptador UserAgent Features</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-features.phtml#zend.http.user-agent-features.intro">38.8.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features.phtml#zend.http.user-agent-features.quick-start">38.8.2. Inicio rápido</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features.phtml#zend.http.user-agent-features.options">38.8.3. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features.phtml#zend.http.user-agent-features.methods">38.8.4. Métodos disponibles</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-features-browscap.phtml">38.9. El adaptador UserAgent Features de Browscap</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-features-browscap.phtml#zend.http.user-agent-features-browscap.intro">38.9.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-browscap.phtml#zend.http.user-agent-features-browscap.quick-start">38.9.2. Inicio rápido</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-browscap.phtml#zend.http.user-agent-features-browscap.options">38.9.3. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-browscap.phtml#zend.http.user-agent-features-browscap.methods">38.9.4. Métodos disponibles</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-features-device-atlas.phtml">38.10. El adaptador UserAgent Features de DeviceAtlas</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-features-device-atlas.phtml#zend.http.user-agent-features-device-atlas.intro">38.10.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-device-atlas.phtml#zend.http.user-agent-features-device-atlas.quick-start">38.10.2. Inicio rápido</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-device-atlas.phtml#zend.http.user-agent-features-device-atlas.options">38.10.3. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-device-atlas.phtml#zend.http.user-agent-features-device-atlas.methods">38.10.4. Métodos disponibles</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-features-tera-wurfl.phtml">38.11. El adaptador UserAgent Features de TeraWurfl</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-features-tera-wurfl.phtml#zend.http.user-agent-features-tera-wurfl.intro">38.11.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-tera-wurfl.phtml#zend.http.user-agent-features-tera-wurfl.quick-start">38.11.2. Inicio rápido</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-tera-wurfl.phtml#zend.http.user-agent-features-tera-wurfl.options">38.11.3. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-features-tera-wurfl.phtml#zend.http.user-agent-features-tera-wurfl.methods">38.11.4. Métodos disponibles</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-storage.phtml">38.12. La interfaz UserAgent Storage</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-storage.phtml#zend.http.user-agent-storage.intro">38.12.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage.phtml#zend.http.user-agent-storage.quick-start">38.12.2. Inicio rápido</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage.phtml#zend.http.user-agent-storage.options">38.12.3. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage.phtml#zend.http.user-agent-storage.methods">38.12.4. Métodos disponibles</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.http.user-agent-storage-session.phtml">38.13. El adaptador UserAgent Storage de Session</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.http.user-agent-storage-session.phtml#zend.http.user-agent-storage-session.intro">38.13.1. Resumen</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage-session.phtml#zend.http.user-agent-storage-session.quick-start">38.13.2. Inicio rápido</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage-session.phtml#zend.http.user-agent-storage-session.options">38.13.3. Opciones de configuración</a></span></dt>
<dt><span class="sect2"><a href="zend.http.user-agent-storage-session.phtml#zend.http.user-agent-storage-session.methods">38.13.4. Métodos disponibles</a></span></dt>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.http.client"></a>38.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Http_Client</code> proporciona una interfaz sencilla para realizar
        peticiones del protocolo de transferencia de hipertexto (HTTP). <code class="classname">Zend_Http_Client</code> soporta la mayoría de
        las características simples esperadas de un cliente <acronym class="acronym">HTTP</acronym>, así como algunas
        características más complejas, como la autenticación <acronym class="acronym">HTTP</acronym> y la subida de archivos. Las
        peticiones exitosas (y la mayoría de las fallidas también) devuelven un objeto <code class="classname">Zend_Http_Response</code>,
        que proporciona acceso a las cabeceras y al cuerpo de la respuesta (vea
        <a class="link" href="zend.http.response.phtml" title="38.5. Zend_Http_Response">esta sección</a>).
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.usage"></a>38.1.1. Usando Zend_Http_Client</h3></div></div></div>
<p>
            El constructor de la clase acepta opcionalmente una URL como su primer parámetro
            (puede ser tanto una cadena como un objeto <code class="classname">Zend_Uri_Http</code>), y un array
            u objeto <code class="classname">Zend_Config</code> que contenga las opciones de configuración. Ambos pueden
            omitirse, y establecerse más tarde usando los métodos setUri() y setConfig().

            </p>
<div class="example">
<a name="zend.http.client.introduction.example-1"></a><p class="title"><b>Ejemplo 38.1. Instanciar un objeto Zend_Http_Client</b></p>
<div class="example-contents"><pre class="programlisting">
$client = new Zend_Http_Client('http://example.org', array(
    'maxredirects' =&gt; 0,
    'timeout'      =&gt; 30));

// This is actually exactly the same:
$client = new Zend_Http_Client();
$client-&gt;setUri('http://example.org');
$client-&gt;setConfig(array(
    'maxredirects' =&gt; 0,
    'timeout'      =&gt; 30));

// You can also use a Zend_Config object to set the client's configuration
$config = new Zend_Config_Ini('httpclient.ini', 'secure');
$client-&gt;setConfig($config);
</pre></div>
</div>
<p><br class="example-break">

            </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                    <code class="classname">Zend_Http_Client</code> usa
                    <code class="classname">Zend_Uri_Http</code> para validar las URLs. Esto significa
                    que algunos caracteres especiales como el símbolo de barra vertical ('|') o el
                    símbolo de intercalación ('^') no serán aceptados en la URL por defecto.
                    Esto puede modificarse estableciendo la opción 'allow_unwise' de
                    <code class="classname">Zend_Uri</code> a '<code class="constant">TRUE</code>'. Vea <a class="link" href="zend.uri.phtml#zend.uri.validation.allowunwise" title='75.1.4.1. Allowing "Unwise" characters in URIs'>esta sección</a> para más
                    información.
                </p></td></tr>
</table></div>
<p>
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.configuration"></a>38.1.2. Parámetros de configuración</h3></div></div></div>
<p>
            El constructor y el método setConfig() aceptan un array asociativo
            de parámetros de configuración, o un objeto <code class="classname">Zend_Config</code>. Establecer
            estos parámetros es opcional, ya que todos tienen valores por defecto.

            </p>
<div class="table">
<a name="zend.http.client.configuration.table"></a><p class="title"><b>Tabla 38.1. Parámetros de configuración de Zend_Http_Client</b></p>
<div class="table-contents"><table class="table" summary="Zend_Http_Client configuration parameters" border="1">
<colgroup>
<col>
<col>
<col>
<col>
</colgroup>
<thead><tr>
<th>Parámetro</th>
<th>Descripción</th>
<th>Valores esperados</th>
<th>Valor por defecto</th>
</tr></thead>
<tbody>
<tr>
<td>maxredirects</td>
<td>Número máximo de redirecciones a seguir (0 = ninguna)</td>
<td>integer</td>
<td>5</td>
</tr>
<tr>
<td>strict</td>
<td>
                                Indica si se realiza validación de los nombres de las cabeceras. Cuando se establece a
                                <code class="constant">FALSE</code>, las funciones de validación se omitirán.
                                Normalmente esto no debería cambiarse
                            </td>
<td>boolean</td>
<td><code class="constant">TRUE</code></td>
</tr>
<tr>
<td>strictredirects</td>
<td>
                                Indica si se debe seguir estrictamente el <acronym class="acronym">RFC</acronym> al
                                redireccionar (vea <a class="link" href="zend.http.client.advanced.phtml#zend.http.client.redirections" title="38.2.1. HTTP Redirections">esta sección</a>)
                            </td>
<td>boolean</td>
<td><code class="constant">FALSE</code></td>
</tr>
<tr>
<td>useragent</td>
<td>Cadena identificadora del agente de usuario (enviada en las cabeceras de la petición)</td>
<td>string</td>
<td>'Zend_Http_Client'</td>
</tr>
<tr>
<td>timeout</td>
<td>Tiempo de espera de la conexión (segundos)</td>
<td>integer</td>
<td>10</td>
</tr>
<tr>
<td>httpversion</td>
<td>Versión del protocolo HTTP (normalmente '1.1' o '1.0')</td>
<td>string</td>
<td>'1.1'</td>
</tr>
<tr>
<td>adapter</td>
<td>
                                Clase adaptadora de conexión a usar (vea <a class="link" href="zend.http.client.adapters.phtml" title="38.3. Zend_Http_Client - Connection Adapters">esta sección</a>)
                            </td>
<td>mixed</td>
<td>'Zend_Http_Client_Adapter_Socket'</td>
</tr>
<tr>
<td>keepalive</td>
<td>
                                Indica si se deben habilitar las conexiones keep-alive con el servidor. Útil y
                                puede mejorar el rendimiento si se realizan varias peticiones consecutivas al
                                mismo servidor.
                            </td>
<td>boolean</td>
<td><code class="constant">FALSE</code></td>
</tr>
<tr>
<td>storeresponse</td>
<td>
                                Indica si se debe almacenar la última respuesta para su posterior recuperación con
                                <code class="methodname">getLastResponse()</code>. Si se establece a
                                <code class="constant">FALSE</code>
                                <code class="methodname">getLastResponse()</code> devolverá
                                <code class="constant">NULL</code>.
                            </td>
<td>boolean</td>
<td><code class="constant">TRUE</code></td>
</tr>
<tr>
<td>encodecookies</td>
<td>
                                Indica si se debe pasar el valor de la cookie a través de urlencode/urldecode.
                                Habilitar esto rompe la compatibilidad con algunos servidores web.
                                Deshabilitarlo limita el rango de valores que pueden contener las cookies.
                            </td>
<td>boolean</td>
<td><code class="constant">TRUE</code></td>
</tr>
</tbody>
</table></div>
</div>
<p><br class="table-break">
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.basic-requests"></a>38.1.3. Realizar peticiones HTTP básicas</h3></div></div></div>
<p>
            Realizar peticiones <acronym class="acronym">HTTP</acronym> simples es muy fácil de hacer usando el
            método request(), y rara vez necesita más de tres líneas de código:

            </p>
<div class="example">
<a name="zend.http.client.basic-requests.example-1"></a><p class="title"><b>Ejemplo 38.2. Realizar una petición GET simple</b></p>
<div class="example-contents"><pre class="programlisting">
$client = new Zend_Http_Client('http://example.org');
$response = $client-&gt;request();
</pre></div>
</div>
<p><br class="example-break">

            El método request() toma un parámetro opcional: el método de petición.
            Puede ser <span class="property">GET</span>, <span class="property">POST</span>,
            <span class="property">PUT</span>, <span class="property">HEAD</span>, <span class="property">DELETE</span>,
            <span class="property">TRACE</span>, <span class="property">OPTIONS</span> o <span class="property">CONNECT</span>
            tal como se definen en el protocolo <acronym class="acronym">HTTP</acronym>

            <a href="#ftn.id31191" class="footnote" name="id31191"><sup class="footnote">[6]</sup></a>.

            Para mayor comodidad, todos ellos están definidos como constantes de clase:
            Zend_Http_Client::GET, Zend_Http_Client::POST y así sucesivamente.
        </p>
<p>
            Si no se especifica ningún método, se usa el método establecido por la última
            llamada a <code class="methodname">setMethod()</code>. Si
            <code class="methodname">setMethod()</code> nunca fue llamado, el método de petición
            por defecto es <code class="constant">GET</code> (vea el ejemplo anterior).

            </p>
<div class="example">
<a name="zend.http.client.basic-requests.example-2"></a><p class="title"><b>Ejemplo 38.3. Usar métodos de petición distintos de GET</b></p>
<div class="example-contents"><pre class="programlisting">
// Preforming a POST request
$response = $client-&gt;request('POST');

// Yet another way of preforming a POST request
$client-&gt;setMethod(Zend_Http_Client::POST);
$response = $client-&gt;request();
</pre></div>
</div>
<p><br class="example-break">
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.parameters"></a>38.1.4. Añadir parámetros GET y POST </h3></div></div></div>
<p>
            Añadir parámetros <code class="constant">GET</code> a una petición <acronym class="acronym">HTTP</acronym> es
            bastante sencillo, y puede hacerse especificándolos como parte de la URL, o usando
            el método setParameterGet().
            Este método toma el nombre del parámetro <code class="constant">GET</code> como su primer parámetro,
            y el valor del parámetro <code class="constant">GET</code> como su segundo parámetro.
            Por comodidad, el método setParameterGet() también puede aceptar un
            único array asociativo de variables <code class="constant">GET</code> nombre =&gt; valor, lo cual puede
            resultar más cómodo cuando es necesario establecer varios parámetros <code class="constant">GET</code>.

            </p>
<div class="example">
<a name="zend.http.client.parameters.example-1"></a><p class="title"><b>Ejemplo 38.4. Establecer parámetros GET</b></p>
<div class="example-contents"><pre class="programlisting">
// Setting a get parameter using the setParameterGet method
$client-&gt;setParameterGet('knight', 'lancelot');

// This is equivalent to setting such URL:
$client-&gt;setUri('http://example.com/index.php?knight=lancelot');

// Adding several parameters with one call
$client-&gt;setParameterGet(array(
    'first_name'  =&gt; 'Bender',
    'middle_name' =&gt; 'Bending'
    'made_in'     =&gt; 'Mexico',
));
</pre></div>
</div>
<p><br class="example-break">
        </p>
<p>
            Aunque los parámetros <code class="constant">GET</code> pueden enviarse con cualquier método de petición, los parámetros
            POST solo se envían en el cuerpo de las peticiones POST. Añadir parámetros
            POST a una petición es muy similar a añadir parámetros <code class="constant">GET</code>,
            y puede hacerse con el método setParameterPost(), que es
            similar en estructura al método setParameterGet().

            </p>
<div class="example">
<a name="zend.http.client.parameters.example-2"></a><p class="title"><b>Ejemplo 38.5. Establecer parámetros POST</b></p>
<div class="example-contents"><pre class="programlisting">
// Setting a POST parameter
$client-&gt;setParameterPost('language', 'fr');

// Setting several POST parameters, one of them with several values
$client-&gt;setParameterPost(array(
    'language'  =&gt; 'es',
    'country'   =&gt; 'ar',
    'selection' =&gt; array(45, 32, 80)
));
</pre></div>
</div>
<p><br class="example-break">

            Note que al enviar peticiones POST, puede establecer tanto parámetros <code class="constant">GET</code> como
            POST. Por otro lado, aunque establecer parámetros POST
            para una petición que no sea POST no provocará un error, es inútil.
            A menos que la petición sea una petición POST, los parámetros POST simplemente
            se ignoran.
        </p>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.http.client.accessing_last"></a>38.1.5. Acceder a la última petición y respuesta</h3></div></div></div>
<p>
            <code class="classname">Zend_Http_Client</code> proporciona métodos para acceder a la última petición
            enviada y a la última respuesta recibida por el objeto cliente.
            <code class="classname">Zend_Http_Client-&gt;getLastRequest()</code> no toma parámetros
            y devuelve la última petición <acronym class="acronym">HTTP</acronym> enviada por el cliente como una cadena.
            De manera similar, <code class="classname">Zend_Http_Client-&gt;getLastResponse()</code> devuelve
            la última respuesta <acronym class="acronym">HTTP</acronym> recibida por el cliente como un
            objeto <a class="link" href="zend.http.response.phtml" title="38.5. Zend_Http_Response">Zend_Http_Response</a>.
        </p>
</div>
</div>
<div class="footnotes">
<br><hr style="width:100; text-align:left;margin-left: 0">
<div id="ftn.id31191" class="footnote"><p><a href="#id31191" class="para"><sup class="para">[6] </sup></a>
                Vea RFC 2616 - <a class="ulink" href="http://www.w3.org/Protocols/rfc2616/rfc2616.html" target="_top">http://www.w3.org/Protocols/rfc2616/rfc2616.html</a>.
              </p></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.gdata.exception.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.http.client.advanced.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">37.11. Capturar excepciones de Gdata </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 38.2. Zend_Http_Client - Uso avanzado</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
