<?php $title = 'Capítulo 71. Zend_Tool'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 71. Zend_Tool</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.timesync.working.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.tool.extending.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.tool"></a>Capítulo 71. Zend_Tool</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.tool.phtml#zend.tool.usage.cli">71.1. Uso de Zend_Tool en la línea de comandos</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.phtml#zend.tool.usage.cli.installation">71.1.1. Instalación</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.installation.download-and-go">71.1.1.1. Descargar y listo</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.installation.pear">71.1.1.2. Instalación mediante Pear</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.installation.install-by-hand">71.1.1.3. Instalación manual</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.tool.phtml#zend.tool.usage.cli.general-purpose-commands">71.1.2. Comandos de propósito general</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.general-purpose-commands.version">71.1.2.1. Versión</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.general-purpose-commands.built-in-help">71.1.2.2. Ayuda incorporada</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.general-purpose-commands.manifest">71.1.2.3. Manifiesto</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands">71.1.3. Comandos específicos del proyecto</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.project">71.1.3.1. Proyecto</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.module">71.1.3.2. Módulo</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.controller">71.1.3.3. Controlador</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.action">71.1.3.4. Acción</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.view">71.1.3.5. Vista</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.model">71.1.3.6. Modelo</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.form">71.1.3.7. Formulario</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.database-adapter">71.1.3.8. DbAdapter</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.db-table">71.1.3.9. DbTable</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.project-specific-commands.layout">71.1.3.10. Layout</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.tool.phtml#zend.tool.usage.cli.environment-customization">71.1.4. Personalización del entorno</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.environment-customization.storage-directory">71.1.4.1. El directorio de almacenamiento</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.environment-customization.configuration-file">71.1.4.2. El archivo de configuración</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.phtml#zend.tool.usage.cli.environment-customization.environment-locations">71.1.4.3. Ubicaciones del entorno</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.tool.extending.phtml">71.2. Extendiendo Zend_Tool</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.tool.extending.phtml#zend.tool.extending.overview">71.2.1. Resumen de Zend_Tool</a></span></dt>
<dt><span class="sect2"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework">71.2.2. Extensiones de Zend_Tool_Framework</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.architecture">71.2.2.1. Arquitectura general</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client">71.2.2.2. Comprendiendo el cliente CLI</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client.setup-general">71.2.2.2.1. Configuración de la herramienta CLI</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client.setup-starnix">71.2.2.2.2. Configuración de la herramienta CLI en sistemas tipo Unix</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client.setup-windows">71.2.2.2.3. Configuración de la herramienta CLI en Windows</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.cli-client.setup-othernotes">71.2.2.2.4. Otras consideraciones de configuración</a></span></dt>
</dl></dd>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests">71.2.2.3. Creación de proveedores</a></span></dt>
<dd><dl>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests.loading">71.2.2.3.1. Cómo encuentra Zend_Tool sus proveedores</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests.basic">71.2.2.3.2. Instrucciones básicas para crear proveedores</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests.response">71.2.2.3.3. El objeto response</a></span></dt>
<dt><span class="sect4"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-framework.providers-and-manifests.advanced">71.2.2.3.4. Información avanzada de desarrollo</a></span></dt>
</dl></dd>
</dl></dd>
<dt><span class="sect2"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-project">71.2.3. Extensiones de Zend_Tool_Project</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-project.architecture">71.2.3.1. Arquitectura general</a></span></dt>
<dt><span class="sect3"><a href="zend.tool.extending.phtml#zend.tool.extending.zend-tool-project.providers">71.2.3.2. Creación de proveedores</a></span></dt>
</dl></dd>
</dl></dd>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.tool.usage.cli"></a>71.1. Uso de Zend_Tool en la línea de comandos</h2></div></div></div>
<p>
        La <acronym class="acronym">CLI</acronym>, o herramienta de línea de comandos (conocida internamente como la herramienta de consola),
        es actualmente la interfaz principal para realizar solicitudes de <code class="classname">Zend_Tool</code>.
        Con la herramienta <acronym class="acronym">CLI</acronym>, los desarrolladores pueden emitir solicitudes de herramientas
        dentro de la "ventana de línea de comandos", también conocida comúnmente como ventana de "terminal". Este
        entorno es predominante en entornos *nix, pero también tiene una implementación común
        en windows con <code class="filename">cmd.exe</code>, console2 y también con el proyecto Cygwin.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.tool.usage.cli.installation"></a>71.1.1. Instalación</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.installation.download-and-go"></a>71.1.1.1. Descargar y listo</h4></div></div></div>
<p>
                Primero descargue Zend Framework. Esto se puede hacer yendo a framework.zend.com
                y descargando la última versión. Después de haber descargado el paquete y colocarlo
                en su sistema. El siguiente paso es hacer que el comando zf esté disponible en su
                sistema. La forma más fácil de hacer esto es copiar los archivos apropiados del directorio
                bin/ de la descarga, y colocar estos archivos dentro del
                <span class="emphasis"><em>mismo</em></span> directorio que la ubicación del binario cli de
                <acronym class="acronym">PHP</acronym>.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.installation.pear"></a>71.1.1.2. Instalación mediante Pear</h4></div></div></div>
<p>
                Para instalar mediante PEAR, debe usar el sitio de terceros zfcampus.org para obtener el
                último paquete PEAR de Zend Framework. Estos paquetes normalmente se compilan dentro del día
                siguiente a una versión oficial de Zend Framework. La ventaja de instalar mediante el
                gestor de paquetes PEAR es que, durante el proceso de instalación, la biblioteca de ZF terminará en
                el include_path, y los scripts zf.php y zf terminarán en un lugar de su
                sistema que le permitirá ejecutarlos sin necesidad de configuración adicional.
            </p>
<pre class="programlisting">
pear channel-discover pear.zfcampus.org
pear install zfcampus/zf
</pre>
<p>
                Eso es todo. Después de la instalación inicial, debería poder continuar
                ejecutando el comando zf. Una buena forma de comprobar si está ahí es ejecutar
                zf --help
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.installation.install-by-hand"></a>71.1.1.3. Instalación manual</h4></div></div></div>
<p>
                La instalación manual se refiere al proceso de forzar a que zf.php y la biblioteca
                de Zend Framework trabajen juntos cuando se colocan en lugares no convencionales, o al menos,
                en un lugar desde el cual su sistema no pueda ejecutarlos fácilmente (típico de programas en el
                PATH de su sistema).
            </p>
<p>
                Si está en un sistema *nix o mac, también puede crear un enlace desde algún lugar en
                su path hacia el archivo zf.sh. Si hace esto, no necesita preocuparse por tener
                la biblioteca de Zend Framework en su include_path, ya que los archivos zf.php y zf.sh podrán
                acceder a la biblioteca de forma relativa a donde se encuentran (es decir, los archivos ./bin/
                son ../library/ en relación con la biblioteca de Zend Framework).
            </p>
<p>
                Existen otras opciones disponibles para configurar zf.php y la biblioteca
                en su sistema. Estas opciones giran en torno a establecer variables de
                entorno específicas. Estas se describen en la sección posterior sobre "personalización del entorno
                CLI". Las variables de entorno para establecer el include_path de zf.php,
                ZEND_TOOL_INCLUDE_PATH y ZF_TOOL_INCLUDE_PATH_PREPEND, son las de mayor interés.
            </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.tool.usage.cli.general-purpose-commands"></a>71.1.2. Comandos de propósito general</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.general-purpose-commands.version"></a>71.1.2.1. Versión</h4></div></div></div>
<p>
                Esto mostrará el número de versión actual de la copia de Zend Framework que está usando la herramienta
                zf.php.
            </p>
<pre class="programlisting">
zf show version
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.general-purpose-commands.built-in-help"></a>71.1.2.2. Ayuda incorporada</h4></div></div></div>
<p>
                El sistema de ayuda incorporado es el lugar principal donde puede obtener
                información actualizada sobre lo que su sistema es capaz de hacer. El sistema de ayuda es dinámico en
                el sentido de que, a medida que se agregan proveedores a su sistema, se vuelven automáticamente ejecutables, y
                como tal, los parámetros necesarios para ejecutarlos estarán en la pantalla de ayuda. La
                forma más fácil de obtener la pantalla de ayuda es la siguiente:
            </p>
<pre class="programlisting">
zf --help
</pre>
<p>
                Esto le dará una visión general de las diversas capacidades del sistema.
                A veces, hay comandos más específicos de los que se pueden ejecutar, y para obtener más
                información sobre estos, es posible que deba ejecutar un comando de ayuda más especializado.
                Para obtener ayuda especializada, simplemente reemplace cualquiera de los elementos del comando con un "?".
                Esto le indicará al sistema de ayuda que desea más información sobre qué comandos
                pueden colocarse en lugar del signo de interrogación. Por ejemplo:
            </p>
<pre class="programlisting">
zf ? controller
</pre>
<p>
                Lo anterior significa "muéstrame todas las 'acciones' para el proveedor 'controller'"; mientras que lo
                siguiente:
            </p>
<pre class="programlisting">
zf show ?
</pre>
<p>
                significa "muéstrame todos los proveedores que soportan la acción 'show'". Esto funciona para
                profundizar en las opciones también, como puede ver en los siguientes ejemplos:
            </p>
<pre class="programlisting">
zf show version.? (show any specialties)
zf show version ? (show any options)
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.general-purpose-commands.manifest"></a>71.1.2.3. Manifiesto</h4></div></div></div>
<p>
                Esto mostrará qué información hay en el manifiesto del sistema de herramientas. Esto es más
                importante para los desarrolladores de proveedores que para los usuarios ocasionales del sistema de herramientas.
            </p>
<pre class="programlisting">
zf show manifest
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.tool.usage.cli.project-specific-commands"></a>71.1.3. Comandos específicos del proyecto</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.project"></a>71.1.3.1. Proyecto</h4></div></div></div>
<p>
                El proveedor de proyecto es el primer comando que quizás desee ejecutar. Esto configurará la
                estructura básica de su aplicación. Esto es necesario antes de que cualquiera de los otros
                proveedores pueda ejecutarse.
            </p>
<pre class="programlisting">
zf create project MyProjectName
</pre>
<p>
                Esto creará un proyecto en un directorio llamado ./MyProjectName. A partir de este punto,
                es importante tener en cuenta que cualquier comando posterior en la línea de comandos debe
                ejecutarse desde dentro del directorio del proyecto que acaba de crear. Por lo tanto, después de la creación,
                es necesario cambiar a ese directorio.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.module"></a>71.1.3.2. Módulo</h4></div></div></div>
<p>
                El proveedor de módulos permite la fácil creación de un módulo de Zend Framework. Un
                módulo sigue el patrón hMVC de forma libre. Al crear módulos, se tomará la
                misma estructura usada en el nivel de application/, y se duplicará dentro del nombre
                elegido para su módulo, dentro del directorio "modules" del directorio
                application/, sin duplicar el directorio modules en sí mismo. Por ejemplo:
            </p>
<pre class="programlisting">
zf create module Blog
</pre>
<p>
                Esto creará un módulo llamado Blog en application/modules/Blog, y todos los
                artefactos que un módulo necesitará.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.controller"></a>71.1.3.3. Controlador</h4></div></div></div>
<p>
                El proveedor de controladores es responsable de crear controladores (en su mayoría) vacíos, así
                como sus directorios y archivos de scripts de vista correspondientes. Para utilizarlo para
                crear un controlador 'Auth', por ejemplo, ejecute:
            </p>
<pre class="programlisting">
zf create controller Auth
</pre>
<p>
                Esto creará un controlador llamado Auth; específicamente, creará un archivo en
                application/controllers/AuthController.php con el AuthController dentro.
                Si desea crear un controlador para un módulo, use cualquiera de los siguientes:
            </p>
<pre class="programlisting">
zf create controller Post 1 Blog
zf create controller Post -m Blog
zf create controller Post --module=Blog
</pre>
<p>
                Nota: En el primer comando, 1 es el valor del indicador "includeIndexAction".
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.action"></a>71.1.3.4. Acción</h4></div></div></div>
<p>
                Para crear una acción dentro de un controlador existente:
            </p>
<pre class="programlisting">
zf create action login Auth
zf create action login -c Auth
zf create action login --controller-name=Auth
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.view"></a>71.1.3.5. Vista</h4></div></div></div>
<p>
                Para crear una vista fuera de la creación normal de controlador/acción, usaría
                una de las siguientes opciones:
            </p>
<pre class="programlisting">
zf create view Auth my-script-name
zf create view -c Auth -a my-script-name
            </pre>
<p>
                Esto creará un script de vista en la carpeta del controlador de Auth.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.model"></a>71.1.3.6. Modelo</h4></div></div></div>
<p>
                El proveedor de modelos solo es responsable de crear los archivos de modelo apropiados,
                con el nombre apropiado dentro de la carpeta de la aplicación. Por ejemplo
            </p>
<pre class="programlisting">
zf create model User
</pre>
<p>
                Si desea crear un modelo dentro de un módulo específico:
            </p>
<pre class="programlisting">
zf create model Post -m Blog
</pre>
<p>
                Lo anterior creará un modelo 'Post' dentro del módulo 'Blog'.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.form"></a>71.1.3.7. Formulario</h4></div></div></div>
<p>
                El proveedor de formularios solo es responsable de crear el archivo de formulario apropiado y el
                método init(), con el nombre apropiado dentro de la carpeta de la aplicación. Por ejemplo:
            </p>
<pre class="programlisting">
zf create form Auth
</pre>
<p>
                Si desea crear un modelo dentro de un módulo específico:
            </p>
<pre class="programlisting">
zf create form Comment -m Blog
</pre>
<p>
                Lo anterior creará un formulario 'Comment' dentro del módulo 'Blog'.
            </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.database-adapter"></a>71.1.3.8. DbAdapter</h4></div></div></div>
<p>
                Para configurar un DbAdapter, deberá proporcionar la información como una cadena
                codificada en formato url. Esta cadena debe ir entre comillas en la línea de comandos.
            </p>
<p>
                Por ejemplo, para introducir la siguiente información:

                </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>adapter: Pdo_Mysql</p></li>
<li class="listitem"><p>username: test</p></li>
<li class="listitem"><p>password: test</p></li>
<li class="listitem"><p>dbname: test </p></li>
</ul></div>
<p>

                Se deberá ejecutar lo siguiente en la línea de comandos:
            </p>
<pre class="programlisting">
zf configure dbadapter "adapter=Pdo_Mysql&amp;username=test&amp;password=test&amp;dbname=test"
</pre>
<p>
                Esto asume que desea almacenar esta información dentro del
                espacio 'production' del archivo de configuración de la aplicación. Lo siguiente
                mostrará una configuración de sqlite, en la sección 'development' del
                archivo de configuración de la aplicación.
            </p>
<pre class="programlisting">
zf configure dbadapter "adapter=Pdo_Sqlite&amp;dbname=../data/test.db" development
zf configure dbadapter "adapter=Pdo_Sqlite&amp;dbname=../data/test.db" -s development
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.db-table"></a>71.1.3.9. DbTable</h4></div></div></div>
<p>
                El proveedor DbTable es responsable de crear los archivos de modelo/acceso a datos de
                <code class="classname">Zend_Db_Table</code> para que su aplicación los use, con el nombre de clase
                apropiado, y en la ubicación correcta dentro de la aplicación.
                Las dos piezas de información importantes son el <span class="emphasis"><em>nombre de DbTable</em></span>,
                y el <span class="emphasis"><em>nombre real de la tabla de la base de datos</em></span>. Por ejemplo:
            </p>
<pre class="programlisting">
zf create dbtable User user
zf create dbtable User -a user

// also accepts a force option to overwrite existing files
zf create dbtable User user -f
zf create dbtable User user --force-overwrite
</pre>
<p>
                El proveedor DbTable también es capaz de crear los archivos apropiados
                escaneando la base de datos configurada con el proveedor DbAdapter anterior.
            </p>
<pre class="programlisting">
zf create dbtable.from-database
</pre>
<p>
                Al ejecutar lo anterior, podría tener sentido usar primero la opción pretend / "-p"
                para que pueda ver qué se haría, y qué tablas se pueden
                encontrar en la base de datos.
            </p>
<pre class="programlisting">
zf -p create dbtable.from-database
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.project-specific-commands.layout"></a>71.1.3.10. Layout</h4></div></div></div>
<p>
                Actualmente, la única acción soportada para los layouts es simplemente habilitarlos,
                lo cual configurará las claves apropiadas en el archivo application.ini para que el recurso
                de la aplicación funcione, y creará los directorios apropiados y el archivo layout.phtml.
            </p>
<pre class="programlisting">
zf enable layout
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.tool.usage.cli.environment-customization"></a>71.1.4. Personalización del entorno</h3></div></div></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.environment-customization.storage-directory"></a>71.1.4.1. El directorio de almacenamiento</h4></div></div></div>
<p>
                El directorio de almacenamiento es importante para que los proveedores tengan un lugar donde encontrar
                lógica personalizada generada por el usuario que pueda cambiar la forma en que se comportan. Un ejemplo
                se puede encontrar a continuación en la colocación de un archivo de perfil de proyecto personalizado.
            </p>
<pre class="programlisting">
zf --setup storage-directory
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.environment-customization.configuration-file"></a>71.1.4.2. El archivo de configuración</h4></div></div></div>
<p>
                Esto creará el archivo zf.ini apropiado. Esto <span class="emphasis"><em>debería</em></span>
                ejecutarse después de <span class="command"><strong>zf --setup storage-directory</strong></span>. Si no se hace así, se
                ubicará dentro del directorio home del usuario. Si se hace, se ubicará dentro
                del directorio de almacenamiento del usuario.
            </p>
<pre class="programlisting">
zf --setup config-file
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.tool.usage.cli.environment-customization.environment-locations"></a>71.1.4.3. Ubicaciones del entorno</h4></div></div></div>
<p>
                Estas deben establecerse si desea anular los lugares predeterminados donde zf
                intentará leer sus valores.
            </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>ZF_HOME</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>el directorio en el que esta herramienta buscará un directorio home</p></li>
<li class="listitem"><p>el directorio debe existir</p></li>
<li class="listitem">
<p>orden de búsqueda:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: square; ">
<li class="listitem"><p>variable de entorno ZF_HOME</p></li>
<li class="listitem"><p>variable de entorno HOME</p></li>
<li class="listitem"><p>luego la variable de entorno HOMEPATH</p></li>
</ul></div>
</li>
</ul></div>
</li>
<li class="listitem">
<p>ZF_STORAGE_DIRECTORY</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>dónde buscará esta herramienta un directorio de almacenamiento</p></li>
<li class="listitem"><p>el directorio debe existir</p></li>
<li class="listitem">
<p>orden de búsqueda:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: square; ">
<li class="listitem"><p>variable de entorno ZF_STORAGE_DIRECTORY</p></li>
<li class="listitem"><p>directorio $homeDirectory/.zf/</p></li>
</ul></div>
</li>
</ul></div>
</li>
<li class="listitem">
<p>ZF_CONFIG_FILE</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>dónde buscará esta herramienta un archivo de configuración</p></li>
<li class="listitem">
<p>orden de búsqueda:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: square; ">
<li class="listitem"><p>variable de entorno ZF_CONFIG_FILE</p></li>
<li class="listitem"><p>archivo $homeDirectory/.zf.ini si existe</p></li>
<li class="listitem"><p>archivo $storageDirectory/zf.ini si existe</p></li>
</ul></div>
</li>
</ul></div>
</li>
<li class="listitem">
<p>ZEND_TOOL_INCLUDE_PATH</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>establece el include_path para que esta herramienta use este valor</p></li>
<li class="listitem">
<p>comportamiento original:</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: square; ">
<li class="listitem"><p>
                                        usar el include_path de <acronym class="acronym">PHP</acronym> para encontrar ZF
                                    </p></li>
<li class="listitem"><p>usar la variable de entorno ZEND_TOOL_INCLUDE_PATH</p></li>
<li class="listitem"><p>
                                        usar la ruta ../library (relativa a zf.php) para encontrar ZF
                                    </p></li>
</ul></div>
</li>
</ul></div>
</li>
<li class="listitem">
<p>ZF_TOOL_INCLUDE_PATH_PREPEND</p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; "><li class="listitem"><p>anteponer al include_path actual del php.ini este valor</p></li></ul></div>
</li>
</ul></div>
</div>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.timesync.working.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.tool.extending.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">70.2. Trabajando con Zend_TimeSync </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 71.2. Extendiendo Zend_Tool</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
</content>
