<?php $title = '76.2. Clases de validación estándar'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">76.2. Clases de validación estándar</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.validate.phtml">Anterior</a> </td>
<th width="60%" align="center">Capítulo 76. Zend_Validate</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.validate.validator_chains.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.validate.set"></a>76.2. Clases de validación estándar</h2></div></div></div>
<p>
        Zend Framework incluye un conjunto estándar de clases de validación, listas para que las use.
    </p>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.alnum"></a>76.2.1. Alnum</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Alnum</code> le permite validar si un valor determinado contiene
        solo caracteres alfabéticos y dígitos. No existe limitación de longitud para la entrada
        que desea validar.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.alnum.options"></a>76.2.1.1. Opciones admitidas para Zend_Validate_Alnum</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Alnum</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allowWhiteSpace</span></em></span>: Si se permiten
                    caracteres de espacio en blanco. Esta opción tiene como valor predeterminado <code class="constant">FALSE</code>
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.alnum.basic"></a>76.2.1.2. Uso básico</h4></div></div></div>
<p>
            Un ejemplo básico es el siguiente:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Alnum();
if ($validator-&gt;isValid('Abcd12')) {
    // value contains only allowed chars
} else {
    // false
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.alnum.whitespace"></a>76.2.1.3. Uso de espacios en blanco</h4></div></div></div>
<p>
            Por defecto los espacios en blanco no se aceptan porque no forman parte del alfabeto.
            Aun así, hay una forma de aceptarlos como entrada. Esto permite validar oraciones
            o frases completas.
        </p>
<p>
            Para permitir el uso de espacios en blanco debe indicar la opción
            <span class="property">allowWhiteSpace</span>. Esto se puede hacer al crear una instancia
            del validador, o posteriormente mediante <code class="methodname">setAllowWhiteSpace()</code>.
            Para obtener el estado actual puede usar <code class="methodname">getAllowWhiteSpace()</code>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Alnum(array('allowWhiteSpace' =&gt; true));
if ($validator-&gt;isValid('Abcd and 12')) {
    // value contains only allowed chars
} else {
    // false
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.alnum.languages"></a>76.2.1.4. Uso de diferentes idiomas</h4></div></div></div>
<p>
            Al usar <code class="classname">Zend_Validate_Alnum</code>, el idioma que el usuario configure
            en su navegador se utilizará para establecer los caracteres permitidos. Esto significa que
            cuando su usuario configura <span class="emphasis"><em>de</em></span> para alemán, también puede introducir
            caracteres como <span class="emphasis"><em>ä</em></span>, <span class="emphasis"><em>ö</em></span> y <span class="emphasis"><em>ü</em></span> además
            de los caracteres del alfabeto inglés.
        </p>
<p>
            Qué caracteres están permitidos depende completamente del idioma utilizado, ya que cada
            idioma define su propio conjunto de caracteres.
        </p>
<p>
            En realidad hay 3 idiomas que no se aceptan en su propia escritura. Estos idiomas son
            <span class="emphasis"><em>coreano</em></span>, <span class="emphasis"><em>japonés</em></span> y
            <span class="emphasis"><em>chino</em></span>, ya que estos idiomas utilizan un alfabeto en el que un
            solo carácter se construye usando múltiples caracteres.
        </p>
<p>
            En caso de que utilice estos idiomas, la entrada solo se validará usando
            el alfabeto inglés.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.alpha"></a>76.2.2. Alpha</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Alpha</code> le permite validar si un valor determinado contiene
        solo caracteres alfabéticos. No existe limitación de longitud para la entrada que desea
        validar. Este validador está relacionado con el validador <code class="classname">Zend_Validate_Alnum</code>,
        con la excepción de que no acepta dígitos.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.alpha.options"></a>76.2.2.1. Opciones admitidas para Zend_Validate_Alpha</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Alpha</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allowWhiteSpace</span></em></span>: Si se permiten
                    caracteres de espacio en blanco. Esta opción tiene como valor predeterminado <code class="constant">FALSE</code>
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.alpha.basic"></a>76.2.2.2. Uso básico</h4></div></div></div>
<p>
            Un ejemplo básico es el siguiente:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Alpha();
if ($validator-&gt;isValid('Abcd')) {
    // value contains only allowed chars
} else {
    // false
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.alpha.whitespace"></a>76.2.2.3. Uso de espacios en blanco</h4></div></div></div>
<p>
            Por defecto los espacios en blanco no se aceptan porque no forman parte del alfabeto.
            Aun así, hay una forma de aceptarlos como entrada. Esto permite validar oraciones
            o frases completas.
        </p>
<p>
            Para permitir el uso de espacios en blanco debe indicar la opción
            <span class="property">allowWhiteSpace</span>. Esto se puede hacer al crear una instancia
            del validador, o posteriormente mediante <code class="methodname">setAllowWhiteSpace()</code>.
            Para obtener el estado actual puede usar <code class="methodname">getAllowWhiteSpace()</code>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Alpha(array('allowWhiteSpace' =&gt; true));
if ($validator-&gt;isValid('Abcd and efg')) {
    // value contains only allowed chars
} else {
    // false
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.alpha.languages"></a>76.2.2.4. Uso de diferentes idiomas</h4></div></div></div>
<p>
            Al usar <code class="classname">Zend_Validate_Alpha</code>, el idioma que el usuario configure
            en su navegador se utilizará para establecer los caracteres permitidos. Esto significa que
            cuando su usuario configura <span class="emphasis"><em>de</em></span> para alemán, también puede introducir
            caracteres como <span class="emphasis"><em>ä</em></span>, <span class="emphasis"><em>ö</em></span> y <span class="emphasis"><em>ü</em></span> además
            de los caracteres del alfabeto inglés.
        </p>
<p>
            Qué caracteres están permitidos depende completamente del idioma utilizado, ya que cada
            idioma define su propio conjunto de caracteres.
        </p>
<p>
            En realidad hay 3 idiomas que no se aceptan en su propia escritura. Estos idiomas son
            <span class="emphasis"><em>coreano</em></span>, <span class="emphasis"><em>japonés</em></span> y
            <span class="emphasis"><em>chino</em></span>, ya que estos idiomas utilizan un alfabeto en el que un
            solo carácter se construye usando múltiples caracteres.
        </p>
<p>
            En caso de que utilice estos idiomas, la entrada solo se validará usando
            el alfabeto inglés.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.barcode"></a>76.2.3. Barcode</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Barcode</code> le permite comprobar si un valor determinado puede
        representarse como un código de barras.
    </p>
<p>
        <code class="classname">Zend_Validate_Barcode</code> admite múltiples estándares de códigos de barras y
        puede extenderse muy fácilmente con implementaciones propias de códigos de barras. Se admiten los
        siguientes estándares de códigos de barras:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>
                <span class="emphasis"><em>CODE25</em></span>: A menudo llamado "two of five" o "Code25 Industrial".
            </p>
<p>
                Este código de barras no tiene limitación de longitud. Admite solo dígitos, y el último
                dígito puede ser opcionalmente un checksum que se calcula con módulo 10. Este estándar es
                muy antiguo y hoy en día no se usa mucho. Los casos de uso comunes se dan dentro de la
                industria.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>CODE25INTERLEAVED</em></span>: A menudo llamado "Code 2 of 5 Interleaved".
            </p>
<p>
                Este estándar es una variante de CODE25. No tiene limitación de longitud, pero debe
                contener una cantidad par de caracteres. Admite solo dígitos, y el último dígito puede
                ser opcionalmente un checksum que se calcula con módulo 10. Se usa en todo el mundo y es
                común en el mercado.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>CODE39</em></span>: CODE39 es uno de los códigos disponibles más antiguos.
            </p>
<p>
                Este código de barras tiene una longitud variable. Admite dígitos, caracteres alfabéticos
                en mayúsculas y 7 caracteres especiales como espacio en blanco, punto y signo de dólar.
                Puede tener un checksum opcional que se calcula con módulo 43. Este estándar se usa en
                todo el mundo y es común dentro de la industria.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>CODE39EXT</em></span>: CODE39EXT es una extensión de CODE39.
            </p>
<p>
                Este código de barras tiene las mismas propiedades que CODE39. Además permite el uso de
                los 128 caracteres ASCII. Este estándar se usa en todo el mundo y es común dentro de la
                industria.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>CODE93</em></span>: CODE93 es el sucesor de CODE39.
            </p>
<p>
                Este código de barras tiene una longitud variable. Admite dígitos, caracteres alfabéticos
                y 7 caracteres especiales. Tiene un checksum opcional que se calcula con módulo 47 y
                contiene 2 caracteres. Este estándar produce un código más denso que CODE39 y es más
                seguro.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>CODE93EXT</em></span>: CODE93EXT es una extensión de CODE93.
            </p>
<p>
                Este código de barras tiene las mismas propiedades que CODE93. Además permite el uso de
                los 128 caracteres ASCII. Este estándar se usa en todo el mundo y es común dentro de la
                industria.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>EAN2</em></span>: EAN es la abreviatura de "European Article Number".
            </p>
<p>
                Este código de barras debe tener 2 caracteres. Admite solo dígitos y no tiene checksum.
                Este estándar se usa principalmente como añadido a EAN13 (ISBN) cuando se imprime en
                libros.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>EAN5</em></span>: EAN es la abreviatura de "European Article Number".
            </p>
<p>
                Este código de barras debe tener 5 caracteres. Admite solo dígitos y no tiene checksum.
                Este estándar se usa principalmente como añadido a EAN13 (ISBN) cuando se imprime en
                libros.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>EAN8</em></span>: EAN es la abreviatura de "European Article Number".
            </p>
<p>
                Este código de barras puede tener 7 u 8 caracteres. Admite solo dígitos. Cuando tiene una
                longitud de 8 caracteres incluye un checksum. Este estándar se usa en todo el mundo pero
                tiene un alcance muy limitado. Se puede encontrar en artículos pequeños donde no se
                podría imprimir un código de barras más largo.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>EAN12</em></span>: EAN es la abreviatura de "European Article Number".
            </p>
<p>
                Este código de barras debe tener una longitud de 12 caracteres. Admite solo dígitos, y
                el último dígito es siempre un checksum que se calcula con módulo 10. Este estándar se
                usa dentro de EE. UU. y es común en el mercado. Ha sido reemplazado por EAN13.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>EAN13</em></span>: EAN es la abreviatura de "European Article Number".
            </p>
<p>
                Este código de barras debe tener una longitud de 13 caracteres. Admite solo dígitos, y
                el último dígito es siempre un checksum que se calcula con módulo 10. Este estándar se
                usa en todo el mundo y es común en el mercado.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>EAN14</em></span>: EAN es la abreviatura de "European Article Number".
            </p>
<p>
                Este código de barras debe tener una longitud de 14 caracteres. Admite solo dígitos, y
                el último dígito es siempre un checksum que se calcula con módulo 10. Este estándar se
                usa en todo el mundo y es común en el mercado. Es el sucesor de EAN13.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>EAN18</em></span>: EAN es la abreviatura de "European Article Number".
            </p>
<p>
                Este código de barras debe tener una longitud de 18 caracteres. Admite solo dígitos. El
                último dígito es siempre un dígito de checksum que se calcula con módulo 10. Este código
                se usa a menudo para la identificación de contenedores de transporte.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>GTIN12</em></span>: GTIN es la abreviatura de "Global Trade Item Number".
            </p>
<p>
                Este código de barras usa el mismo estándar que EAN12 y es su sucesor. Se usa
                comúnmente dentro de EE. UU.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>GTIN13</em></span>: GTIN es la abreviatura de "Global Trade Item Number".
            </p>
<p>
                Este código de barras usa el mismo estándar que EAN13 y es su sucesor. Se usa en todo
                el mundo por la industria.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>GTIN14</em></span>: GTIN es la abreviatura de "Global Trade Item Number".
            </p>
<p>
                Este código de barras usa el mismo estándar que EAN14 y es su sucesor. Se usa en todo
                el mundo y es común en el mercado.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>IDENTCODE</em></span>: Identcode es usado por Deutsche Post y DHL. Es una
                implementación especializada de Code25.
            </p>
<p>
                Este código de barras debe tener una longitud de 12 caracteres. Admite solo dígitos, y
                el último dígito es siempre un checksum que se calcula con módulo 10. Este estándar se
                usa principalmente por las empresas DP y DHL.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>INTELLIGENTMAIL</em></span>: Intelligent Mail es un código de barras postal.
            </p>
<p>
                Este código de barras puede tener una longitud de 20, 25, 29 o 31 caracteres. Admite
                solo dígitos, y no contiene checksum. Este estándar es el sucesor de
                <acronym class="acronym">PLANET</acronym> y <acronym class="acronym">POSTNET</acronym>. Se usa principalmente por el
                Servicio Postal de los Estados Unidos.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>ISSN</em></span>: <acronym class="acronym">ISSN</acronym> es la abreviatura de
                International Standard Serial Number.
            </p>
<p>
                Este código de barras puede tener una longitud de 8 o 13 caracteres. Admite solo dígitos,
                y el último dígito debe ser un dígito de checksum que se calcula con módulo 11.
                Se usa en todo el mundo para publicaciones impresas.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>ITF14</em></span>: ITF14 es la implementación GS1 de un código de barras
                Interleaved Two of Five.
            </p>
<p>
                Este código de barras es una variante especial de Interleaved 2 of 5. Debe tener una
                longitud de 14 caracteres y se basa en GTIN14. Admite solo dígitos, y el último dígito
                debe ser un dígito de checksum que se calcula con módulo 10. Se usa en todo el mundo y
                es común dentro del mercado.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>LEITCODE</em></span>: Leitcode es usado por Deutsche Post y DHL. Es una
                implementación especializada de Code25.
            </p>
<p>
                Este código de barras debe tener una longitud de 14 caracteres. Admite solo dígitos, y
                el último dígito es siempre un checksum que se calcula con módulo 10. Este estándar se
                usa principalmente por las empresas DP y DHL.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>PLANET</em></span>: Planet es la abreviatura de Postal Alpha Numeric
                Encoding Technique.
            </p>
<p>
                Este código de barras puede tener una longitud de 12 o 14 caracteres. Admite solo
                dígitos, y el último dígito es siempre un checksum. Este estándar se usa principalmente
                por el Servicio Postal de los Estados Unidos.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>POSTNET</em></span>: Postnet es usado por el Servicio Postal de EE. UU.
            </p>
<p>
                Este código de barras puede tener una longitud de 6, 7, 10 o 12 caracteres. Admite solo
                dígitos, y el último dígito es siempre un checksum. Este estándar se usa principalmente
                por el Servicio Postal de los Estados Unidos.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>ROYALMAIL</em></span>: Royalmail es usado por Royal Mail.
            </p>
<p>
                Este código de barras no tiene una longitud definida. Admite dígitos, letras en
                mayúsculas, y el último dígito es siempre un checksum. Este estándar se usa
                principalmente por Royal Mail para su Cleanmail Service. También se llama
                <acronym class="acronym">RM4SCC</acronym>.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>SSCC</em></span>: SSCC es la abreviatura de "Serial Shipping Container
                Code".
            </p>
<p>
                Este código de barras es una variante del código de barras EAN. Debe tener una longitud
                de 18 caracteres y admite solo dígitos. El último dígito debe ser un dígito de checksum
                que se calcula con módulo 10. Se usa comúnmente en la industria del transporte.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>UPCA</em></span>: UPC es la abreviatura de "Univeral Product Code".
            </p>
<p>
                Este código de barras precedió a EAN13. Debe tener una longitud de 12 caracteres y
                admite solo dígitos. El último dígito debe ser un dígito de checksum que se calcula
                con módulo 10. Se usa comúnmente dentro de EE. UU.
            </p>
</li>
<li class="listitem">
<p>
                <span class="emphasis"><em>UPCE</em></span>: UPCE es la variante corta de UPCA.
            </p>
<p>
                Este código de barras es una variante más pequeña de UPCA. Puede tener una longitud de
                6, 7 u 8 caracteres y admite solo dígitos. Cuando el código de barras tiene 8 caracteres
                de longitud incluye un checksum que se calcula con módulo 10. Se usa comúnmente con
                productos pequeños donde no cabría un código de barras UPCA.
            </p>
</li>
</ul></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.barcode.options"></a>76.2.3.1. Opciones admitidas para Zend_Validate_Barcode</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Barcode</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">adapter</span></em></span>: Establece el adaptador de
                    código de barras que se usará. Se admiten todos los adaptadores mencionados
                    anteriormente. Al usar un adaptador definido por el usuario, debe indicar el
                    nombre de clase completo.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">checksum</span></em></span>: <code class="constant">TRUE</code>
                    cuando el código de barras debe contener un checksum. El valor predeterminado
                    depende del adaptador utilizado. Tenga en cuenta que algunos adaptadores no permiten
                    establecer esta opción.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">options</span></em></span>: Define opciones opcionales
                    para adaptadores propios.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.barcode.basic"></a>76.2.3.2. Uso básico</h4></div></div></div>
<p>
            Para validar si una cadena determinada es un código de barras solo necesita conocer su
            tipo. Vea el siguiente ejemplo para un código de barras EAN13:
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Barcode('EAN13');
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.barcode.checksum"></a>76.2.3.3. Checksum opcional</h4></div></div></div>
<p>
            Algunos códigos de barras se pueden proporcionar con un checksum opcional. Estos códigos
            de barras serían válidos incluso sin checksum. Aun así, cuando proporciona un checksum,
            también debería validarlo. Por defecto, estos tipos de código de barras no realizan
            validación de checksum. Usando la opción <span class="property">checksum</span> puede definir si
            el checksum se validará o se ignorará.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Barcode(array(
    'adapter'  =&gt; 'EAN13',
    'checksum' =&gt; false,
));
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<div class="note"><table border="0" summary="Note: Reduced security by disabling checksum validation">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Seguridad reducida al deshabilitar la validación de checksum</th>
</tr>
<tr><td align="left" valign="top"><p>
                 Al desactivar la validación de checksum también reducirá la seguridad de los códigos
                 de barras usados. Además debe tener en cuenta que también puede desactivar la
                 validación de checksum para aquellos tipos de código de barras que deben contener
                 un valor de checksum. Los códigos de barras que no serían válidos podrían entonces
                 devolverse como válidos aunque no lo sean.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.barcode.custom"></a>76.2.3.4. Escribir adaptadores personalizados</h4></div></div></div>
<p>
            Puede escribir validadores de código de barras personalizados para usar con
            <code class="classname">Zend_Validate_Barcode</code>; esto suele ser necesario cuando se trabaja
            con tipos de código de barras propietarios. Para escribir su propio validador de código
            de barras, necesita la siguiente información.
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem">
<p>
                    <span class="emphasis"><em>Length</em></span>: La longitud que debe tener su código de barras.
                    Puede tener uno de los siguientes valores:
                </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: circle; ">
<li class="listitem"><p>
                            <span class="emphasis"><em>Integer</em></span>: Un valor mayor que 0, lo que significa que
                            el código de barras debe tener esa longitud.
                        </p></li>
<li class="listitem"><p>
                            <span class="emphasis"><em>-1</em></span>: No hay limitación para la longitud de este
                            código de barras.
                        </p></li>
<li class="listitem"><p>
                            <span class="emphasis"><em>"even"</em></span>: La longitud de este código de barras debe
                            tener una cantidad par de dígitos.
                        </p></li>
<li class="listitem"><p>
                            <span class="emphasis"><em>"odd"</em></span>: La longitud de este código de barras debe
                            tener una cantidad impar de dígitos.
                        </p></li>
<li class="listitem"><p>
                            <span class="emphasis"><em>array</em></span>: Un array de valores enteros. La longitud
                            de este código de barras debe tener uno de los valores establecidos en el array.
                        </p></li>
</ul></div>
</li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Characters</em></span>: Una cadena que contiene todos los caracteres
                    permitidos para este código de barras. También se permite el valor entero 128, que
                    significa los primeros 128 caracteres de la tabla ASCII.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>Checksum</em></span>: Una cadena que se usará como callback para un
                    método que realiza la validación del checksum.
                </p></li>
</ul></div>
<p>
            Su validador de código de barras personalizado debe extender
            <code class="classname">Zend_Validate_Barcode_AdapterAbstract</code> o implementar
            <span class="interface">Zend_Validate_Barcode_AdapterInterface</span>.
        </p>
<p>
            Como ejemplo, creemos un validador que espera un número par de caracteres que incluyan
            todos los dígitos y las letras 'ABCDE', y que requiere un checksum.
        </p>
<pre class="programlisting">
class My_Barcode_MyBar extends Zend_Validate_Barcode_AdapterAbstract
{
    protected $_length     = 'even';
    protected $_characters = '0123456789ABCDE';
    protected $_checksum   = '_mod66';

    protected function _mod66($barcode)
    {
        // do some validations and return a boolean
    }
}

$valid = new Zend_Validate_Barcode('My_Barcode_MyBar');
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.between"></a>76.2.4. Between</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Between</code> le permite validar si un valor determinado está
        entre otros dos valores.
    </p>
<div class="note"><table border="0" summary="Note: Zend_Validate_Between supports only number validation">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Zend_Validate_Between admite solo la validación de números</th>
</tr>
<tr><td align="left" valign="top"><p>
            Debe tenerse en cuenta que <code class="classname">Zend_Validate_Between</code> admite solo la
            validación de números. Las cadenas o fechas no se pueden validar con este validador.
        </p></td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.between.options"></a>76.2.4.1. Opciones admitidas para Zend_Validate_Between</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Between</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">inclusive</span></em></span>: Define si la validación
                    incluye los valores de los límites mínimo y máximo o los excluye. Su valor
                    predeterminado es <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">max</span></em></span>: Establece el límite máximo para
                    la validación.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">min</span></em></span>: Establece el límite mínimo para
                    la validación.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.between.basic"></a>76.2.4.2. Comportamiento predeterminado para Zend_Validate_Between</h4></div></div></div>
<p>
            Por defecto este validador comprueba si un valor está entre <span class="property">min</span> y
            <span class="property">max</span>, donde ambos valores límite están permitidos como valor.
        </p>
<pre class="programlisting">
$valid  = new Zend_Validate_Between(array('min' =&gt; 0, 'max' =&gt; 10));
$value  = 10;
$result = $valid-&gt;isValid($value);
// returns true
</pre>
<p>
            En el ejemplo anterior el resultado es <code class="constant">TRUE</code> debido a que por
            defecto la búsqueda incluye los valores límite. Esto significa en nuestro caso que
            cualquier valor de '0' a '10' está permitido. Y valores como '-1' y '11' devolverán
            <code class="constant">FALSE</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.between.inclusively"></a>76.2.4.3. Validación excluyendo los valores límite</h4></div></div></div>
<p>
            A veces es útil validar un valor excluyendo los valores límite. Vea el siguiente
            ejemplo:
        </p>
<pre class="programlisting">
$valid  = new Zend_Validate_Between(
    array(
        'min' =&gt; 0,
        'max' =&gt; 10,
        'inclusive' =&gt; false
    )
);
$value  = 10;
$result = $valid-&gt;isValid($value);
// returns false
</pre>
<p>
            El ejemplo es casi igual a nuestro primer ejemplo, pero excluimos el valor límite. Ahora
            los valores '0' y '10' ya no están permitidos y devolverán
            <code class="constant">FALSE</code>.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.callback"></a>76.2.5. Callback</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Callback</code> le permite proporcionar un callback con el que
        validar un valor determinado.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.callback.options"></a>76.2.5.1. Opciones admitidas para Zend_Validate_Callback</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Callback</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">callback</span></em></span>: Establece el callback que
                    se llamará para la validación.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">options</span></em></span>: Establece las opciones
                    adicionales que se darán al callback.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.callback.basic"></a>76.2.5.2. Uso básico</h4></div></div></div>
<p>
            El caso de uso más simple es tener una sola función y usarla como callback. Supongamos
            que tenemos la siguiente función.
        </p>
<pre class="programlisting">
function myMethod($value)
{
    // some validation
    return true;
}
</pre>
<p>
            Para usarla dentro de <code class="classname">Zend_Validate_Callback</code> solo tiene que
            llamarla de esta manera:
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Callback('myMethod');
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.callback.closure"></a>76.2.5.3. Uso con closures</h4></div></div></div>
<p>
            <acronym class="acronym">PHP</acronym> 5.3 introduce las <a class="ulink" href="http://php.net/functions.anonymous" target="_top">closures</a>, que son básicamente
            funciones autocontenidas o <span class="emphasis"><em>anónimas</em></span>. <acronym class="acronym">PHP</acronym>
            considera las closures otra forma de callback, y, como tal, se pueden usar con
            <code class="classname">Zend_Validate_Callback</code>. Por ejemplo:
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Callback(function($value){
    // some validation
    return true;
});

if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.callback.class"></a>76.2.5.4. Uso con callbacks basados en clases</h4></div></div></div>
<p>
            Por supuesto también es posible usar un método de clase como callback. Supongamos que
            tenemos el siguiente método de clase:
        </p>
<pre class="programlisting">
class MyClass
{
    public function myMethod($value)
    {
        // some validation
        return true;
    }
}
</pre>
<p>
            La definición del callback es en este caso casi la misma. Solo tiene que crear una
            instancia de la clase antes del método y crear un array que describa el callback:
        </p>
<pre class="programlisting">
$object = new MyClass;
$valid = new Zend_Validate_Callback(array($object, 'myMethod'));
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<p>
            También puede definir un método estático como callback. Considere la siguiente
            definición de clase y uso del validador:
        </p>
<pre class="programlisting">
class MyClass
{
    public static function test($value)
    {
        // some validation
        return true;
    }
}

$valid = new Zend_Validate_Callback(array('MyClass', 'test'));
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<p>
            Finalmente, si está usando <acronym class="acronym">PHP</acronym> 5.3, puede definir el método mágico
            <code class="methodname">__invoke()</code> en su clase. Si lo hace, simplemente proporcionar una
            instancia de la clase como callback también funcionará:
        </p>
<pre class="programlisting">
class MyClass
{
    public function __invoke($value)
    {
        // some validation
        return true;
    }
}

$object = new MyClass();
$valid = new Zend_Validate_Callback($object);
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.callback.options2"></a>76.2.5.5. Añadir opciones</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_Callback</code> también permite el uso de opciones que se
            proporcionan como argumentos adicionales al callback.
        </p>
<p>
            Considere la siguiente definición de clase y método:
        </p>
<pre class="programlisting">
class MyClass
{
    function myMethod($value, $option)
    {
        // some validation
        return true;
    }
}
</pre>
<p>
            Hay dos formas de informar al validador sobre opciones adicionales: pasarlas en el
            constructor, o pasarlas al método <code class="methodname">setOptions()</code>.
        </p>
<p>
            Para pasarlas al constructor, necesitaría pasar un array que contenga dos claves,
            "callback" y "options":
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Callback(array(
    'callback' =&gt; array('MyClass', 'myMethod'),
    'options'  =&gt; $option,
));

if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<p>
            De lo contrario, puede pasarlas al validador después de la instanciación:
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Callback(array('MyClass', 'myMethod'));
$valid-&gt;setOptions($option);

if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<p>
            Cuando se dan valores adicionales a <code class="methodname">isValid()</code>, estos valores se
            añadirán inmediatamente después de <code class="varname">$value</code>.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Callback(array('MyClass', 'myMethod'));
$valid-&gt;setOptions($option);

if ($valid-&gt;isValid($input, $additional)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<p>
            Al hacer la llamada al callback, el valor que se va a validar siempre se pasará como
            primer argumento al callback, seguido de todos los demás valores dados a
            <code class="methodname">isValid()</code>; todas las demás opciones lo seguirán. La cantidad y
            el tipo de opciones que se pueden usar no está limitado.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.creditcard"></a>76.2.6. CreditCard</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_CreditCard</code> le permite validar si un valor determinado
        podría ser un número de tarjeta de crédito.
    </p>
<p>
        Una tarjeta de crédito contiene varios elementos de metadatos, incluyendo un holograma,
        número de cuenta, logotipo, fecha de caducidad, código de seguridad y el nombre del titular
        de la tarjeta. Los algoritmos para verificar la combinación de metadatos solo los conoce la
        empresa emisora, y deben verificarse con ella para fines de pago. Sin embargo, a menudo es
        útil saber si un número determinado cae dentro de los rangos de números posibles
        <span class="emphasis"><em>antes</em></span> de realizar dicha verificación, y, como tal,
        <code class="classname">Zend_Validate_CreditCard</code> simplemente verifica que el número de tarjeta
        de crédito proporcionado esté bien formado.
    </p>
<p>
        Para aquellos casos en los que tenga un servicio que pueda realizar una verificación
        exhaustiva, <code class="classname">Zend_Validate_CreditCard</code> también proporciona la capacidad
        de adjuntar un callback de servicio para activarlo una vez que el número de tarjeta de
        crédito se haya considerado válido; este callback se activará entonces, y su valor de
        retorno determinará la validez general.
    </p>
<p>
        Se aceptan las siguientes entidades emisoras:
    </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem">
<p>
                <span class="emphasis"><em>American Express</em></span>
            </p>
<p>
                <span class="emphasis"><em>China UnionPay</em></span>
            </p>
<p>
                <span class="emphasis"><em>Diners Club Card Blanche</em></span>
            </p>
<p>
                <span class="emphasis"><em>Diners Club International</em></span>
            </p>
<p>
                <span class="emphasis"><em>Diners Club US &amp; Canada</em></span>
            </p>
<p>
                <span class="emphasis"><em>Discover Card</em></span>
            </p>
<p>
                <span class="emphasis"><em>JCB</em></span>
            </p>
<p>
                <span class="emphasis"><em>Laser</em></span>
            </p>
<p>
                <span class="emphasis"><em>Maestro</em></span>
            </p>
<p>
                <span class="emphasis"><em>MasterCard</em></span>
            </p>
<p>
                <span class="emphasis"><em>Solo</em></span>
            </p>
<p>
                <span class="emphasis"><em>Visa</em></span>
            </p>
<p>
                <span class="emphasis"><em>Visa Electron</em></span>
            </p>
</li></ul></div>
<div class="note"><table border="0" summary="Note: Invalid institutes">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Entidades no válidas</th>
</tr>
<tr><td align="left" valign="top">
<p>
            Las entidades <span class="emphasis"><em>Bankcard</em></span> y <span class="emphasis"><em>Diners Club
                enRoute</em></span> ya no existen. Por lo tanto se tratan como no válidas.
        </p>
<p>
            <span class="emphasis"><em>Switch</em></span> ha sido renombrada a <span class="emphasis"><em>Visa</em></span> y por
            lo tanto también se trata como no válida.
        </p>
</td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.creditcard.options"></a>76.2.6.1. Opciones admitidas para Zend_Validate_CreditCard</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_CreditCard</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">service</span></em></span>: Un callback a un servicio
                    en línea que además se usará para la validación.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">type</span></em></span>: El tipo de tarjeta de crédito
                    que se validará. Vea la siguiente lista de entidades para más detalles.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.creditcard.basic"></a>76.2.6.2. Uso básico</h4></div></div></div>
<p>
            Hay varias entidades de tarjetas de crédito que pueden validarse con
            <code class="classname">Zend_Validate_CreditCard</code>. Por defecto, se aceptarán todas las
            entidades conocidas. Vea el siguiente ejemplo:
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_CreditCard();
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<p>
            El ejemplo anterior validaría contra todas las entidades de tarjetas de crédito
            conocidas.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.creditcard.institute"></a>76.2.6.3. Aceptar tarjetas de crédito definidas</h4></div></div></div>
<p>
            A veces es necesario aceptar solo entidades de tarjetas de crédito definidas en lugar
            de todas; por ejemplo, cuando tiene una tienda en línea que solo acepta tarjetas Visa y
            American Express. <code class="classname">Zend_Validate_CreditCard</code> le permite hacer
            exactamente esto limitándolo exactamente a estas entidades.
        </p>
<p>
            Para usar una limitación puede proporcionar entidades específicas en la inicialización,
            o posteriormente mediante <code class="methodname">setType()</code>. Cada uno puede tomar varios
            argumentos.
        </p>
<p>
            Puede proporcionar una sola entidad:
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_CreditCard(
    Zend_Validate_CreditCard::AMERICAN_EXPRESS
);
</pre>
<p>
            Cuando quiere permitir múltiples entidades, puede proporcionarlas como array:
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_CreditCard(array(
    Zend_Validate_CreditCard::AMERICAN_EXPRESS,
    Zend_Validate_CreditCard::VISA
));
</pre>
<p>
            Y como con todos los validadores, también puede pasar un array asociativo de opciones o
            una instancia de <code class="classname">Zend_Config</code>. En este caso debe proporcionar las
            entidades con la clave de array <span class="property">type</span> como se simula aquí:
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_CreditCard(array(
    'type' =&gt; array(Zend_Validate_CreditCard::AMERICAN_EXPRESS)
));
</pre>
<div class="table">
<a name="zend.validate.set.creditcard.institute.table"></a><p class="title"><b>Tabla 76.1. Constantes para entidades de tarjetas de crédito</b></p>
<div class="table-contents"><table class="table" summary="Constants for credit card institutes" border="1">
<colgroup>
<col>
<col>
</colgroup>
<thead><tr>
<th>Entidad</th>
<th>Constante</th>
</tr></thead>
<tbody>
<tr>
<td><span class="emphasis"><em>American Express</em></span></td>
<td><code class="constant">AMERICAN_EXPRESS</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>China UnionPay</em></span></td>
<td><code class="constant">UNIONPAY</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Diners Club Card Blanche</em></span></td>
<td><code class="constant">DINERS_CLUB</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Diners Club International</em></span></td>
<td><code class="constant">DINERS_CLUB</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Diners Club US &amp; Canada</em></span></td>
<td><code class="constant">DINERS_CLUB_US</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Discover Card</em></span></td>
<td><code class="constant">DISCOVER</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>JCB</em></span></td>
<td><code class="constant">JCB</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Laser</em></span></td>
<td><code class="constant">LASER</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Maestro</em></span></td>
<td><code class="constant">MAESTRO</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>MasterCard</em></span></td>
<td><code class="constant">MASTERCARD</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Solo</em></span></td>
<td><code class="constant">SOLO</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Visa</em></span></td>
<td><code class="constant">VISA</code></td>
</tr>
<tr>
<td><span class="emphasis"><em>Visa Electron</em></span></td>
<td><code class="constant">VISA</code></td>
</tr>
</tbody>
</table></div>
</div>
<br class="table-break"><p>
            También puede establecer o añadir entidades después de la instanciación usando los
            métodos <code class="methodname">setType()</code>, <code class="methodname">addType()</code> y
            <code class="methodname">getType()</code>.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_CreditCard();
$valid-&gt;setType(array(
    Zend_Validate_CreditCard::AMERICAN_EXPRESS,
    Zend_Validate_CreditCard::VISA
));
</pre>
<div class="note"><table border="0" summary="Note: Default institute">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Entidad predeterminada</th>
</tr>
<tr><td align="left" valign="top">
<p>
                Cuando no se da ninguna entidad en la inicialización se usa <code class="constant">ALL</code>,
                que establece todas las entidades a la vez.
            </p>
<p>
                En este caso el uso de <code class="methodname">addType()</code> es inútil porque todas las
                entidades ya se han añadido.
            </p>
</td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.creditcard.servicecheck"></a>76.2.6.4. Validación usando APIs externas</h4></div></div></div>
<p>
            Como se dijo antes, <code class="classname">Zend_Validate_CreditCard</code> solo validará
            el número de tarjeta de crédito. Afortunadamente, algunas entidades proporcionan
            <acronym class="acronym">API</acronym>s en línea que pueden validar un número de tarjeta de crédito
            usando algoritmos que no están disponibles al público. La mayoría de estos servicios son
            de pago. Por lo tanto, esta comprobación está desactivada por defecto.
        </p>
<p>
            Cuando tenga acceso a dicha <acronym class="acronym">API</acronym>, puede usarla como un complemento
            para <code class="classname">Zend_Validate_CreditCard</code> y aumentar la seguridad de la
            validación.
        </p>
<p>
            Para hacerlo, simplemente necesita dar un callback que se llamará cuando la validación
            genérica haya pasado. Esto evita que se llame a la <acronym class="acronym">API</acronym> para
            números no válidos, lo que aumenta el rendimiento de la aplicación.
        </p>
<p>
            <code class="methodname">setService()</code> establece un nuevo servicio, y
            <code class="methodname">getService()</code> devuelve el servicio establecido. Como opción de
            configuración,
            puede dar la clave de array '<span class="property">service</span>' en la inicialización. Para más
            detalles sobre las posibles opciones eche un vistazo a <a class="link" href="zend.validate.set.phtml#zend.validate.set.callback" title="76.2.5. Callback">Callback</a>.
        </p>
<pre class="programlisting">
// Your service class
class CcService
{
    public function checkOnline($cardnumber, $types)
    {
        // some online validation
    }
}

// The validation
$service = new CcService();
$valid   = new Zend_Validate_CreditCard(Zend_Validate_CreditCard::VISA);
$valid-&gt;setService(array($service, 'checkOnline'));
</pre>
<p>
            Como puede ver, el método callback se llamará con el número de tarjeta de crédito como
            primer parámetro, y los tipos aceptados como segundo parámetro.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.ccnum"></a>76.2.7. Ccnum</h3></div></div></div>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                El validador <code class="classname">Ccnum</code> se ha declarado obsoleto en favor del
                validador <code class="classname">CreditCard</code>. Por razones de seguridad debería usar
                CreditCard en lugar de Ccnum.
            </p></td></tr>
</table></div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.date"></a>76.2.8. Date</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Date</code> le permite validar si un valor determinado contiene
        una fecha. Este validador también valida entradas localizadas.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.date.options"></a>76.2.8.1. Opciones admitidas para Zend_Validate_Date</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Date</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">format</span></em></span>: Establece el formato que se
                    usa para escribir la fecha.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">locale</span></em></span>: Establece la configuración
                    regional que se usará para validar los valores de fecha.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.date.basic"></a>76.2.8.2. Validación de fecha predeterminada</h4></div></div></div>
<p>
            La forma más fácil de validar una fecha es usando el formato de fecha predeterminado.
            Se usa cuando no se ha dado ninguna configuración regional ni ningún formato.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Date();

$validator-&gt;isValid('2000-10-10');   // returns true
$validator-&gt;isValid('10.10.2000'); // returns false
</pre>
<p>
            El formato de fecha predeterminado para <code class="classname">Zend_Validate_Date</code> es
            'yyyy-MM-dd'.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.date.localized"></a>76.2.8.3. Validación de fecha localizada</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_Date</code> también valida fechas dadas en un formato
            localizado. Usando la opción <span class="property">locale</span> puede definir la configuración
            regional que debe usar el formato de fecha para la validación.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Date(array('locale' =&gt; 'de'));

$validator-&gt;isValid('10.Feb.2010'); // returns true
$validator-&gt;isValid('10.May.2010'); // returns false
</pre>
<p>
            La opción <span class="property">locale</span> establece el formato de fecha predeterminado. En
            el ejemplo anterior este es 'dd.MM.yyyy', que se define como formato de fecha
            predeterminado para 'de'.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.date.formats"></a>76.2.8.4. Validación de fecha definida por el usuario</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_Date</code> también admite formatos de fecha definidos por
            el usuario. Cuando quiera validar tal fecha puede usar la opción
            <span class="property">format</span>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Date(array('format' =&gt; 'yyyy'));

$validator-&gt;isValid('2010'); // returns true
$validator-&gt;isValid('May');  // returns false
</pre>
<p>
            Por supuesto puede combinar <span class="property">format</span> y <span class="property">locale</span>.
            En este caso también puede usar nombres de mes o de día localizados.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Date(array('format' =&gt; 'yyyy MMMM', 'locale' =&gt; 'de'));

$validator-&gt;isValid('2010 Dezember'); // returns true
$validator-&gt;isValid('2010 June');     // returns false
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.Db"></a>76.2.9. Db_RecordExists y Db_NoRecordExists</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Db_RecordExists</code> y
        <code class="classname">Zend_Validate_Db_NoRecordExists</code> proporcionan un medio para probar
        si un registro existe en una tabla determinada de una base de datos, con un
        valor determinado.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.db.options"></a>76.2.9.1. Opciones admitidas para Zend_Validate_Db_*</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para
            <code class="classname">Zend_Validate_Db_NoRecordExists</code> y
            <code class="classname">Zend_Validate_Db_RecordExists</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">adapter</span></em></span>: El adaptador de base de
                    datos que se usará para la búsqueda.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">exclude</span></em></span>: Establece los registros que
                    se excluirán de la búsqueda.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">field</span></em></span>: El campo de la base de datos
                    dentro de esta tabla en el que se buscará el registro.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">schema</span></em></span>: Establece el esquema que se
                    usará para la búsqueda.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">table</span></em></span>: La tabla en la que se
                    buscará el registro.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.db.basic-usage"></a>76.2.9.2. Uso básico</h4></div></div></div>
<p>
            Un ejemplo de uso básico de los validadores:
        </p>
<pre class="programlisting">
//Check that the email address exists in the database
$validator = new Zend_Validate_Db_RecordExists(
    array(
        'table' =&gt; 'users',
        'field' =&gt; 'emailaddress'
    )
);

if ($validator-&gt;isValid($emailaddress)) {
    // email address appears to be valid
} else {
    // email address is invalid; print the reasons
    foreach ($validator-&gt;getMessages() as $message) {
        echo "$message\n";
    }
}
</pre>
<p>
            Lo anterior probará que una dirección de correo electrónico determinada está en la
            tabla de la base de datos. Si no se encuentra ningún registro que contenga el valor de
            <code class="varname">$emailaddress</code> en la columna especificada, se muestra un mensaje de
            error.
        </p>
<pre class="programlisting">
//Check that the username is not present in the database
$validator = new Zend_Validate_Db_NoRecordExists(
    array(
        'table' =&gt; 'users',
        'field' =&gt; 'username'
    )
);
if ($validator-&gt;isValid($username)) {
    // username appears to be valid
} else {
    // username is invalid; print the reason
    $messages = $validator-&gt;getMessages();
    foreach ($messages as $message) {
        echo "$message\n";
    }
}
</pre>
<p>
            Lo anterior probará que un nombre de usuario determinado no está en la tabla de la
            base de datos. Si se encuentra un registro que contiene el valor de
            <code class="varname">$username</code> en la columna especificada, se muestra un mensaje de
            error.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.db.excluding-records"></a>76.2.9.3. Excluir registros</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_Db_RecordExists</code> y
            <code class="classname">Zend_Validate_Db_NoRecordExists</code> también proporcionan un medio
            para probar la base de datos, excluyendo una parte de la tabla, ya sea proporcionando
            una cláusula where como cadena, o un array con las claves
            "field" y "value".
        </p>
<p>
            Cuando se proporciona un array para la cláusula de exclusión, se usa el operador
            <span class="emphasis"><em>!=</em></span>, de modo que puede comprobar el resto de una tabla en busca
            de un valor antes de modificar un registro (por ejemplo en un formulario de perfil de
            usuario)
        </p>
<pre class="programlisting">
//Check no other users have the username
$user_id   = $user-&gt;getId();
$validator = new Zend_Validate_Db_NoRecordExists(
    array(
        'table' =&gt; 'users',
        'field' =&gt; 'username',
        'exclude' =&gt; array(
            'field' =&gt; 'id',
            'value' =&gt; $user_id
        )
    )
);

if ($validator-&gt;isValid($username)) {
    // username appears to be valid
} else {
    // username is invalid; print the reason
    $messages = $validator-&gt;getMessages();
    foreach ($messages as $message) {
        echo "$message\n";
    }
}
</pre>
<p>
            El ejemplo anterior comprobará la tabla para asegurar que ningún registro salvo aquel
            donde <span class="command"><strong>id = $user_id</strong></span> contiene el valor
            $username.
        </p>
<p>
            También puede proporcionar una cadena para la cláusula de exclusión, de modo que pueda
            usar un operador distinto de <span class="emphasis"><em>!=</em></span>. Esto puede ser útil para probar
            contra claves compuestas.
        </p>
<pre class="programlisting">
$email     = 'user@example.com';
$clause    = $db-&gt;quoteInto('email = ?', $email);
$validator = new Zend_Validate_Db_RecordExists(
    array(
        'table'   =&gt; 'users',
        'field'   =&gt; 'username',
        'exclude' =&gt; $clause
    )
);

if ($validator-&gt;isValid($username)) {
    // username appears to be valid
} else {
    // username is invalid; print the reason
    $messages = $validator-&gt;getMessages();
    foreach ($messages as $message) {
        echo "$message\n";
    }
}
</pre>
<p>
            El ejemplo anterior comprobará la tabla 'users'
            para asegurar que solo un registro con tanto el nombre de usuario
            <code class="varname">$username</code> como el email
            <code class="varname">$email</code> es válido.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.db.database-adapters"></a>76.2.9.4. Adaptadores de base de datos</h4></div></div></div>
<p>
            También puede especificar un adaptador. Esto le permitirá trabajar con aplicaciones
            que usan múltiples adaptadores de base de datos, o donde no ha establecido un
            adaptador predeterminado. Como en el siguiente ejemplo:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Db_RecordExists(
    array(
        'table' =&gt; 'users',
        'field' =&gt; 'id',
        'adapter' =&gt; $dbAdapter
    )
);
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.db.database-schemas"></a>76.2.9.5. Esquemas de base de datos</h4></div></div></div>
<p>
            Puede especificar un esquema dentro de su base de datos para adaptadores como
            PostgreSQL y DB/2 simplemente proporcionando un array con las claves
            <span class="property">table</span> y <span class="property">schema</span>. Como en el siguiente
            ejemplo:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Db_RecordExists(
    array(
        'table'  =&gt; 'users',
        'schema' =&gt; 'my',
        'field'  =&gt; 'id'
    )
);
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.digits"></a>76.2.10. Digits</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Digits</code> valida si un valor determinado contiene solo
        dígitos.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.digits.options"></a>76.2.10.1. Opciones admitidas para Zend_Validate_Digits</h4></div></div></div>
<p>
            No hay opciones adicionales para <code class="classname">Zend_Validate_Digits</code>:
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.digits.basic"></a>76.2.10.2. Validar dígitos</h4></div></div></div>
<p>
            Para validar si un valor determinado contiene solo dígitos y ningún otro carácter,
            simplemente llame al validador como se muestra en este ejemplo:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Digits();

$validator-&gt;isValid("1234567890"); // returns true
$validator-&gt;isValid(1234);         // returns true
$validator-&gt;isValid('1a234');      // returns false
</pre>
<div class="note"><table border="0" summary="Note: Validating numbers">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Validar números</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando quiera validar números o valores numéricos, tenga en cuenta que este
                validador solo valida dígitos. Esto significa que cualquier otro signo como un
                separador de miles o una coma no pasará este validador. En este caso debería usar
                <code class="classname">Zend_Validate_Int</code> o
                <code class="classname">Zend_Validate_Float</code>.
            </p></td></tr>
</table></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.email_address"></a>76.2.11. EmailAddress</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_EmailAddress</code> le permite validar una dirección de correo
        electrónico. El validador primero divide la dirección de correo en la parte local @ el
        nombre de host e intenta cotejarlos contra especificaciones conocidas para direcciones de
        correo y nombres de host.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.basic"></a>76.2.11.1. Uso básico</h4></div></div></div>
<p>
            Un ejemplo básico de uso está a continuación:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_EmailAddress();
if ($validator-&gt;isValid($email)) {
    // email appears to be valid
} else {
    // email is invalid; print the reasons
    foreach ($validator-&gt;getMessages() as $message) {
        echo "$message\n";
    }
}
</pre>
<p>
            Esto cotejará la dirección de correo electrónico <code class="varname">$email</code> y, en caso
            de fallo, rellenará <code class="methodname">getMessages()</code> con mensajes de error útiles.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.options"></a>76.2.11.2. Opciones para validar direcciones de correo electrónico</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_EmailAddress</code> admite varias opciones que se pueden
            establecer bien en la inicialización, dando un array con las opciones relacionadas, o
            posteriormente, usando <code class="methodname">setOptions()</code>. Se admiten las siguientes
            opciones:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allow</span></em></span>: Define qué tipo de nombres de
                    dominio se aceptan. Esta opción se usa junto con la opción hostname para
                    establecer el validador de nombre de host. Para más información sobre los
                    posibles valores de esta opción, eche un vistazo a <a class="link" href="zend.validate.set.phtml#zend.validate.set.hostname" title="76.2.15. Hostname">Hostname</a>
                    y las posibles constantes <code class="constant">ALLOW</code>*. Esta opción tiene como
                    valor predeterminado <code class="constant">ALLOW_DNS</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">deep</span></em></span>: Define si los registros MX del
                    servidor deben verificarse con una comprobación profunda. Cuando esta opción se
                    establece en <code class="constant">TRUE</code>, además de los registros MX también se
                    usan los registros A, A6 y <code class="constant">AAAA</code> para verificar si el
                    servidor acepta correos. Esta opción tiene como valor predeterminado
                    <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">domain</span></em></span>: Define si se debe comprobar
                    la parte del dominio. Cuando esta opción se establece en
                    <code class="constant">FALSE</code>, solo se comprobará la parte local de la dirección de
                    correo electrónico. En este caso no se llamará al validador de nombre de host.
                    Esta opción tiene como valor predeterminado <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">hostname</span></em></span>: Establece el validador de
                    nombre de host con el que se validará la parte del dominio de la dirección de
                    correo electrónico.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">mx</span></em></span>: Define si se deben detectar los
                    registros MX del servidor. Si esta opción se define como
                    <code class="constant">TRUE</code>, entonces se usan los registros MX para verificar si el
                    servidor acepta correos. Esta opción tiene como valor predeterminado
                    <code class="constant">FALSE</code>.
                </p></li>
</ul></div>
<pre class="programlisting">
$validator = new Zend_Validate_EmailAddress();
$validator-&gt;setOptions(array('domain' =&gt; false));
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.complexlocal"></a>76.2.11.3. Partes locales complejas</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_EmailAddress</code> cotejará cualquier dirección de correo
            electrónico válida según RFC2822. Por ejemplo, los correos válidos incluyen
            <span class="emphasis"><em>bob@domain.com</em></span>, <span class="emphasis"><em>bob+jones@domain.us</em></span>,
            <span class="emphasis"><em>"bob@jones"@domain.com</em></span> y
            <span class="emphasis"><em>"bob jones"@domain.com</em></span>.
        </p>
<p>
            Algunos formatos de correo electrónico obsoletos actualmente no se validarán (p. ej.
            retornos de carro o un carácter "\" en una dirección de correo electrónico).
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.purelocal"></a>76.2.11.4. Validar solo la parte local</h4></div></div></div>
<p>
            Si necesita que <code class="classname">Zend_Validate_EmailAddress</code> compruebe solo la
            parte local de una dirección de correo electrónico, y quiere deshabilitar la validación
            del nombre de host, puede establecer la opción <span class="property">domain</span> en
            <code class="constant">FALSE</code>. Esto obliga a <code class="classname">Zend_Validate_EmailAddress</code>
            a no validar la parte de nombre de host de la dirección de correo electrónico.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_EmailAddress();
$validator-&gt;setOptions(array('domain' =&gt; FALSE));
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.hostnametype"></a>76.2.11.5. Validar diferentes tipos de nombres de host</h4></div></div></div>
<p>
            La parte de nombre de host de una dirección de correo electrónico se valida contra
            <a class="link" href="zend.validate.set.phtml#zend.validate.set.hostname" title="76.2.15. Hostname">
                <code class="classname">Zend_Validate_Hostname</code></a>. Por defecto
            solo se aceptan nombres de host DNS de la forma <code class="filename">domain.com</code>, aunque
            si lo desea también puede aceptar direcciones IP y nombres de host locales.
        </p>
<p>
            Para hacer esto necesita instanciar <code class="classname">Zend_Validate_EmailAddress</code>
            pasando un parámetro para indicar el tipo de nombres de host que quiere aceptar. Hay más
            detalles incluidos en <code class="classname">Zend_Validate_Hostname</code>, aunque a continuación
            aparece un ejemplo de cómo aceptar nombres de host tanto DNS como locales:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_EmailAddress(
                    Zend_Validate_Hostname::ALLOW_DNS |
                    Zend_Validate_Hostname::ALLOW_LOCAL);
if ($validator-&gt;isValid($email)) {
    // email appears to be valid
} else {
    // email is invalid; print the reasons
    foreach ($validator-&gt;getMessages() as $message) {
        echo "$message\n";
    }
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.checkacceptance"></a>76.2.11.6. Comprobar si el nombre de host realmente acepta correo</h4></div></div></div>
<p>
            Solo porque una dirección de correo electrónico esté en el formato correcto, no
            significa necesariamente que esa dirección de correo realmente exista. Para ayudar a
            resolver este problema, puede usar la validación MX para comprobar si existe una
            entrada MX (correo) en el registro DNS para el nombre de host del correo. Esto le dice
            que el nombre de host acepta correo, pero no le dice que la dirección de correo
            electrónico exacta en sí sea válida.
        </p>
<p>
            La comprobación MX no está habilitada por defecto. Para habilitar la comprobación MX
            puede pasar un segundo parámetro al constructor de
            <code class="classname">Zend_Validate_EmailAddress</code>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_EmailAddress(
    array(
        'allow' =&gt; Zend_Validate_Hostname::ALLOW_DNS,
        'mx'    =&gt; true
    )
);
</pre>
<div class="note"><table border="0" summary="Note: MX Check under Windows">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Comprobación MX en Windows</th>
</tr>
<tr><td align="left" valign="top"><p>
                Dentro de entornos Windows la comprobación MX solo está disponible cuando se usa
                <acronym class="acronym">PHP</acronym> 5.3 o superior. Por debajo de <acronym class="acronym">PHP</acronym> 5.3 la
                comprobación MX no se usará aunque esté activada dentro de las opciones.
            </p></td></tr>
</table></div>
<p>
            Alternativamente puede pasar <code class="constant">TRUE</code> o
            <code class="constant">FALSE</code> a <code class="methodname">setValidateMx()</code> para habilitar
            o deshabilitar la validación MX.
        </p>
<p>
            Al habilitar esta configuración se usarán funciones de red para comprobar la presencia
            de un registro MX en el nombre de host de la dirección de correo electrónico que desea
            validar. Tenga en cuenta que esto probablemente ralentizará su script.
        </p>
<p>
            A veces la validación de registros MX devuelve <code class="constant">FALSE</code>, incluso si
            se aceptan los correos. La razón detrás de este comportamiento es que los servidores
            pueden aceptar correos incluso si no proporcionan un registro MX. En este caso pueden
            proporcionar registros A, A6 o <code class="constant">AAAA</code>. Para permitir que
            <code class="classname">Zend_Validate_EmailAddress</code> también compruebe estos otros
            registros, necesita establecer la validación MX profunda. Esto se puede hacer en la
            inicialización estableciendo la opción <span class="property">deep</span> o usando
            <code class="methodname">setOptions()</code>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_EmailAddress(
    array(
        'allow' =&gt; Zend_Validate_Hostname::ALLOW_DNS,
        'mx'    =&gt; true,
        'deep'  =&gt; true
    )
);
</pre>
<div class="warning"><table border="0" summary="Warning: Performance warning">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Warning]" src="images/warning.png"></td>
<th align="left">Advertencia de rendimiento</th>
</tr>
<tr><td align="left" valign="top"><p>
                Debe tener en cuenta que habilitar la comprobación MX ralentizará su script debido
                a las funciones de red usadas. Habilitar la comprobación profunda ralentizará su
                script aún más, ya que busca en el servidor dado 3 tipos adicionales.
            </p></td></tr>
</table></div>
<div class="note"><table border="0" summary="Note: Disallowed IP addresses">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Direcciones IP no permitidas</th>
</tr>
<tr><td align="left" valign="top"><p>
                Debe tener en cuenta que la validación MX solo se acepta para servidores externos.
                Cuando la validación MX profunda está habilitada, las direcciones IP locales como
                <span class="command"><strong>192.168.*</strong></span>
                o <span class="command"><strong>169.254.*</strong></span> no se aceptan.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.validateidn"></a>76.2.11.7. Validar nombres de dominio internacionales</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_EmailAddress</code> también cotejará caracteres
            internacionales que existen en algunos dominios. Esto se conoce como soporte de
            International Domain Name (IDN). Esto está habilitado por defecto, aunque puede
            deshabilitarlo cambiando la configuración a través del objeto interno
            <code class="classname">Zend_Validate_Hostname</code> que existe dentro de
            <code class="classname">Zend_Validate_EmailAddress</code>.
        </p>
<pre class="programlisting">
$validator-&gt;getHostnameValidator()-&gt;setValidateIdn(false);
</pre>
<p>
            Más información sobre el uso de <code class="methodname">setValidateIdn()</code> aparece en la
            documentación de <code class="classname">Zend_Validate_Hostname</code>.
        </p>
<p>
            Tenga en cuenta que los IDN solo se validan si permite que se validen nombres de host
            DNS.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.validatetld"></a>76.2.11.8. Validar dominios de nivel superior</h4></div></div></div>
<p>
            Por defecto, un nombre de host se comprobará contra una lista de TLD conocidos. Esto
            está habilitado por defecto, aunque puede deshabilitarlo cambiando la configuración a
            través del objeto interno <code class="classname">Zend_Validate_Hostname</code> que existe
            dentro de <code class="classname">Zend_Validate_EmailAddress</code>.
        </p>
<pre class="programlisting">
$validator-&gt;getHostnameValidator()-&gt;setValidateTld(false);
</pre>
<p>
            Más información sobre el uso de <code class="methodname">setValidateTld()</code> aparece en la
            documentación de <code class="classname">Zend_Validate_Hostname</code>.
        </p>
<p>
            Tenga en cuenta que los TLD solo se validan si permite que se validen nombres de host
            DNS.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.email_address.setmessage"></a>76.2.11.9. Establecer mensajes</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_EmailAddress</code> también hace uso de
            <code class="classname">Zend_Validate_Hostname</code> para comprobar la parte de nombre de host
            de una dirección de correo electrónico determinada. Al igual que con Zend Framework
            1.10 puede simplemente establecer mensajes para
            <code class="classname">Zend_Validate_Hostname</code> desde dentro de
            <code class="classname">Zend_Validate_EmailAddress</code>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_EmailAddress();
$validator-&gt;setMessages(
    array(
        Zend_Validate_Hostname::UNKNOWN_TLD =&gt; "I don't know the TLD you gave"
    )
);
</pre>
<p>
            Antes de Zend Framework 1.10 tenía que adjuntar los mensajes a su propio
            <code class="classname">Zend_Validate_Hostname</code>, y luego establecer este validador dentro
            de <code class="classname">Zend_Validate_EmailAddress</code> para obtener sus propios mensajes
            devueltos.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.float"></a>76.2.12. Float</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Float</code> le permite validar si un valor determinado contiene
        un valor de punto flotante. Este validador también valida entradas localizadas.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.float.options"></a>76.2.12.1. Opciones admitidas para Zend_Validate_Float</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Float</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">locale</span></em></span>: Establece la configuración
                    regional que se usará para validar valores flotantes localizados.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.float.basic"></a>76.2.12.2. Validación simple de valores flotantes</h4></div></div></div>
<p>
            La forma más simple de validar un valor flotante es usando la configuración del
            sistema. Cuando no se usa ninguna opción, se usa la configuración regional del entorno
            para la validación:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Float();

$validator-&gt;isValid(1234.5);   // returns true
$validator-&gt;isValid('10a01'); // returns false
$validator-&gt;isValid('1,234.5'); // returns true
</pre>
<p>
            En el ejemplo anterior esperábamos que nuestro entorno esté configurado con "en" como
            configuración regional.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.float.localized"></a>76.2.12.3. Validación de valores flotantes localizada</h4></div></div></div>
<p>
            A menudo es útil poder validar también valores localizados. Los valores flotantes a
            menudo se escriben de forma diferente en otros países. Por ejemplo usando inglés
            escribirá "1.5". En alemán puede escribir "1,5" y en otros idiomas puede usar
            agrupación.
        </p>
<p>
            <code class="classname">Zend_Validate_Float</code> es capaz de validar tales notaciones. Pero
            está limitado a la configuración regional que establezca. Vea el siguiente código:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Float(array('locale' =&gt; 'de'));

$validator-&gt;isValid(1234.5); // returns true
$validator-&gt;isValid("1 234,5"); // returns false
$validator-&gt;isValid("1.234"); // returns true
</pre>
<p>
            Como puede ver, al usar una configuración regional, su entrada se valida de forma
            localizada. Al usar una notación diferente obtiene un <code class="constant">FALSE</code> cuando
            la configuración regional fuerza una notación diferente.
        </p>
<p>
            La configuración regional también se puede establecer posteriormente usando
            <code class="methodname">setLocale()</code> y recuperar usando
            <code class="methodname">getLocale()</code>.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.greaterthan"></a>76.2.13. GreaterThan</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_GreaterThan</code> le permite validar si un valor determinado
        es mayor que un valor límite mínimo.
    </p>
<div class="note"><table border="0" summary="Note: Zend_Validate_GreaterThan supports only number validation">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Zend_Validate_GreaterThan admite solo la validación de números</th>
</tr>
<tr><td align="left" valign="top"><p>
            Debe tenerse en cuenta que <code class="classname">Zend_Validate_GreaterThan</code> admite solo
            la validación de números. Las cadenas o fechas no se pueden validar con este validador.
        </p></td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.greaterthan.options"></a>76.2.13.1. Opciones admitidas para Zend_Validate_GreaterThan</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para
            <code class="classname">Zend_Validate_GreaterThan</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">min</span></em></span>: Establece el valor límite mínimo.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.greaterthan.basic"></a>76.2.13.2. Uso básico</h4></div></div></div>
<p>
            Para validar si un valor determinado es mayor que un límite definido simplemente use
            el siguiente ejemplo.
        </p>
<pre class="programlisting">
$valid  = new Zend_Validate_GreaterThan(array('min' =&gt; 10));
$value  = 11;
$return = $valid-&gt;isValid($value);
// returns true
</pre>
<p>
            El ejemplo anterior devuelve <code class="constant">TRUE</code> para todos los valores que son
            mayores que 10.
        </p>
<pre class="programlisting">
$valid  = new Zend_Validate_GreaterThan(array('min' =&gt; 10));
$value  = 10;
$return = $valid-&gt;isValid($value);
// returns false
</pre>
<p>
            El ejemplo anterior devuelve <code class="constant">FALSE</code> para todos los valores que son
            menores o iguales al valor límite mínimo.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.hex"></a>76.2.14. Hex</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Hex</code> le permite validar si un valor determinado contiene
        solo caracteres hexadecimales. Estos son todos los caracteres de <span class="emphasis"><em>0 a 9</em></span> y
        <span class="emphasis"><em>A a F</em></span>, sin distinción entre mayúsculas y minúsculas. No existe
        limitación de longitud para la entrada que desea validar.
    </p>
<pre class="programlisting">
$validator = new Zend_Validate_Hex();
if ($validator-&gt;isValid('123ABC')) {
    // value contains only hex chars
} else {
    // false
}
</pre>
<div class="note"><table border="0" summary="Note: Invalid characters">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Caracteres no válidos</th>
</tr>
<tr><td align="left" valign="top"><p>
            Todos los demás caracteres devolverán false, incluyendo espacios en blanco y el punto
            decimal. Además los ceros unicode y números de otras escrituras distintas del latín no
            se tratarán como válidos.
        </p></td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.hex.options"></a>76.2.14.1. Opciones admitidas para Zend_Validate_Hex</h4></div></div></div>
<p>
            No hay opciones adicionales para <code class="classname">Zend_Validate_Hex</code>:
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.hostname"></a>76.2.15. Hostname</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Hostname</code> le permite validar un nombre de host contra un
        conjunto de especificaciones conocidas. Es posible comprobar tres tipos diferentes de
        nombres de host: un nombre de host <acronym class="acronym">DNS</acronym> (p. ej. <code class="filename">domain.com</code>),
        una dirección IP (p. ej. 1.2.3.4), y nombres de host locales (p. ej. localhost). Por defecto
        solo se cotejan los nombres de host <acronym class="acronym">DNS</acronym>.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.hostname.options"></a>76.2.15.1. Opciones admitidas para Zend_Validate_Hostname</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Hostname</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allow</span></em></span>: Define el tipo de nombre de
                    host que se permite usar. Vea <a class="link" href="zend.validate.set.phtml#zend.validate.set.hostname.types" title="76.2.15.3. Validating different types of hostnames">Tipos de nombre de host</a> para
                    más detalles.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">idn</span></em></span>: Define si se permiten los
                    dominios <acronym class="acronym">IDN</acronym>. Esta opción tiene como valor predeterminado
                    <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">ip</span></em></span>: Permite definir un validador de
                    IP propio. Esta opción tiene como valor predeterminado una nueva instancia de
                    <code class="classname">Zend_Validate_Ip</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">tld</span></em></span>: Define si se validan los
                    <acronym class="acronym">TLD</acronym>. Esta opción tiene como valor predeterminado
                    <code class="constant">TRUE</code>.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.hostname.basic"></a>76.2.15.2. Uso básico</h4></div></div></div>
<p>
            Un ejemplo básico de uso está a continuación:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Hostname();
if ($validator-&gt;isValid($hostname)) {
    // hostname appears to be valid
} else {
    // hostname is invalid; print the reasons
    foreach ($validator-&gt;getMessages() as $message) {
        echo "$message\n";
    }
}
</pre>
<p>
            Esto cotejará el nombre de host <code class="varname">$hostname</code> y, en caso de fallo,
            rellenará <code class="methodname">getMessages()</code> con mensajes de error útiles.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.hostname.types"></a>76.2.15.3. Validar diferentes tipos de nombres de host</h4></div></div></div>
<p>
            Puede encontrar que también quiere cotejar direcciones IP, nombres de host locales, o
            una combinación de todos los tipos permitidos. Esto se puede hacer pasando un parámetro
            a <code class="classname">Zend_Validate_Hostname</code> cuando lo instancie. El parámetro debe
            ser un entero que determine qué tipos de nombres de host se permiten. Se le anima a
            usar las constantes de <code class="classname">Zend_Validate_Hostname</code> para hacer esto.
        </p>
<p>
            Las constantes de <code class="classname">Zend_Validate_Hostname</code> son:
            <code class="constant">ALLOW_DNS</code> para permitir solo nombres de host
            <acronym class="acronym">DNS</acronym>, <code class="constant">ALLOW_IP</code> para permitir direcciones IP,
            <code class="constant">ALLOW_LOCAL</code> para permitir nombres de red locales,
            <code class="constant">ALLOW_URI</code> para permitir direcciones conformes a
            <a class="ulink" href="http://tools.ietf.org/html/rfc3986" target="_top">RFC3986</a>,
            y <code class="constant">ALLOW_ALL</code> para permitir los cuatro tipos anteriores.
        </p>
<div class="note"><table border="0" summary="Note: Additional Information on ALLOW_URI">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Información adicional sobre ALLOW_URI</th>
</tr>
<tr><td align="left" valign="top"><p>
                <code class="constant">ALLOW_URI</code> permite comprobar nombres de host
                según <a class="ulink" href="http://tools.ietf.org/html/rfc3986" target="_top">RFC3986</a>. Estos
                son nombres registrados que usan <acronym class="acronym">WINS</acronym>, NetInfo y también
                nombres de host locales como los definidos en su archivo
                <code class="filename">.hosts</code>.
            </p></td></tr>
</table></div>
<p>
            Para comprobar solo direcciones IP puede usar el siguiente ejemplo:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Hostname(Zend_Validate_Hostname::ALLOW_IP);
if ($validator-&gt;isValid($hostname)) {
    // hostname appears to be valid
} else {
    // hostname is invalid; print the reasons
    foreach ($validator-&gt;getMessages() as $message) {
        echo "$message\n";
    }
}
</pre>
<p>
            Además de usar <code class="constant">ALLOW_ALL</code> para aceptar todos los tipos de nombres
            de host comunes, puede combinar estos tipos para permitir combinaciones. Por ejemplo,
            para aceptar nombres de host <acronym class="acronym">DNS</acronym> y locales, instancie su objeto
            <code class="classname">Zend_Validate_Hostname</code> así:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Hostname(Zend_Validate_Hostname::ALLOW_DNS |
                                        Zend_Validate_Hostname::ALLOW_IP);
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.hostname.idn"></a>76.2.15.4. Validar nombres de dominio internacionales</h4></div></div></div>
<p>
            Algunos dominios de código de país de nivel superior (ccTLD), como 'de' (Alemania),
            admiten caracteres internacionales en nombres de dominio. Esto se conoce como
            International Domain Names (<acronym class="acronym">IDN</acronym>). Estos dominios pueden ser
            cotejados por <code class="classname">Zend_Validate_Hostname</code> mediante caracteres
            extendidos que se usan en el proceso de validación.
        </p>
<div class="note"><table border="0" summary="Note: IDN domains">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Dominios IDN</th>
</tr>
<tr><td align="left" valign="top"><p>
                Hasta ahora más de 50 ccTLD admiten dominios <acronym class="acronym">IDN</acronym>.
            </p></td></tr>
</table></div>
<p>
            Para cotejar un dominio <acronym class="acronym">IDN</acronym> es tan simple como usar el validador
            Hostname estándar, ya que la comprobación <acronym class="acronym">IDN</acronym> está habilitada por
            defecto. Si desea deshabilitar la validación <acronym class="acronym">IDN</acronym> esto se puede
            hacer bien pasando un parámetro al constructor de
            <code class="classname">Zend_Validate_Hostname</code> o mediante el método
            <code class="methodname">setValidateIdn()</code>.
        </p>
<p>
            Puede deshabilitar la validación <acronym class="acronym">IDN</acronym> pasando un segundo parámetro
            al constructor de <code class="classname">Zend_Validate_Hostname</code> de la siguiente manera.
        </p>
<pre class="programlisting">
$validator =
    new Zend_Validate_Hostname(
        array(
            'allow' =&gt; Zend_Validate_Hostname::ALLOW_DNS,
            'idn'   =&gt; false
        )
    );
</pre>
<p>
            Alternativamente puede pasar <code class="constant">TRUE</code> o
            <code class="constant">FALSE</code> a <code class="methodname">setValidateIdn()</code> para habilitar o
            deshabilitar la validación <acronym class="acronym">IDN</acronym>. Si está intentando cotejar un
            nombre de host <acronym class="acronym">IDN</acronym> que actualmente no se admite, es probable que
            falle la validación si tiene algún carácter internacional. Cuando no existe un archivo
            de ccTLD en <code class="filename">Zend/Validate/Hostname</code> que especifique los caracteres
            adicionales, se realiza una validación de nombre de host normal.
        </p>
<div class="note"><table border="0" summary="Note: IDN validation">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Validación IDN</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que los <acronym class="acronym">IDN</acronym> solo se validan si permite que se
                validen nombres de host <acronym class="acronym">DNS</acronym>.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.hostname.tld"></a>76.2.15.5. Validar dominios de nivel superior</h4></div></div></div>
<p>
            Por defecto, un nombre de host se comprobará contra una lista de <acronym class="acronym">TLD</acronym>
            conocidos. Si esta funcionalidad no es necesaria, se puede deshabilitar de la misma
            manera que al deshabilitar el soporte <acronym class="acronym">IDN</acronym>. Puede deshabilitar la
            validación <acronym class="acronym">TLD</acronym> pasando un tercer parámetro al constructor de
            <code class="classname">Zend_Validate_Hostname</code>. En el siguiente ejemplo estamos
            admitiendo la validación <acronym class="acronym">IDN</acronym> mediante el segundo parámetro.
        </p>
<pre class="programlisting">
$validator =
    new Zend_Validate_Hostname(
        array(
            'allow' =&gt; Zend_Validate_Hostname::ALLOW_DNS,
            'idn'   =&gt; true,
            'tld'   =&gt; false
        )
    );
</pre>
<p>
            Alternativamente puede pasar <code class="constant">TRUE</code> o
            <code class="constant">FALSE</code> a <code class="methodname">setValidateTld()</code> para habilitar o
            deshabilitar la validación <acronym class="acronym">TLD</acronym>.
        </p>
<div class="note"><table border="0" summary="Note: TLD validation">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Validación TLD</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que los <acronym class="acronym">TLD</acronym> solo se validan si permite que se
                validen nombres de host <acronym class="acronym">DNS</acronym>.
            </p></td></tr>
</table></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.iban"></a>76.2.16. Iban</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Iban</code> valida si un valor determinado podría ser un
        número <acronym class="acronym">IBAN</acronym>. <acronym class="acronym">IBAN</acronym> es la abreviatura de
        "International Bank Account Number".
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.iban.options"></a>76.2.16.1. Opciones admitidas para Zend_Validate_Iban</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Iban</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">locale</span></em></span>: Establece la configuración
                    regional que se usa para obtener el formato <acronym class="acronym">IBAN</acronym> para la
                    validación.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.iban.basic"></a>76.2.16.2. Validación IBAN</h4></div></div></div>
<p>
            Los números <acronym class="acronym">IBAN</acronym> siempre están relacionados con un país. Esto
            significa que diferentes países usan diferentes formatos para sus números
            <acronym class="acronym">IBAN</acronym>. Esta es la razón por la que los números
            <acronym class="acronym">IBAN</acronym> siempre necesitan una configuración regional. Sabiendo esto
            ya sabemos cómo usar <code class="classname">Zend_Validate_Iban</code>.
        </p>
<div class="sect4">
<div class="titlepage"><div><div><h5 class="title">
<a name="zend.validate.set.iban.basic.application"></a>76.2.16.2.1. Configuración regional de toda la aplicación</h5></div></div></div>
<p>
                Podríamos usar la configuración regional de toda la aplicación. Esto significa que
                cuando no se da ninguna opción en la inicialización,
                <code class="classname">Zend_Validate_Iban</code> busca la configuración regional de toda
                la aplicación. Vea el siguiente fragmento de código:
            </p>
<pre class="programlisting">
// within bootstrap
Zend_Registry::set('Zend_Locale', new Zend_Locale('de_AT'));

// within the module
$validator = new Zend_Validate_Iban();

if ($validator-&gt;isValid('AT611904300234573201')) {
    // IBAN appears to be valid
} else {
    // IBAN is not valid
}
</pre>
<div class="note"><table border="0" summary="Note: Application wide locale">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Configuración regional de toda la aplicación</th>
</tr>
<tr><td align="left" valign="top"><p>
                    Por supuesto esto solo funciona cuando se estableció previamente una
                    configuración regional de toda la aplicación en el registro. De lo contrario
                    <code class="classname">Zend_Locale</code> intentará usar la configuración regional que
                    envíe el cliente o, cuando no se envíe ninguna, usa la configuración regional
                    del entorno. Tenga en cuenta que esto puede llevar a un comportamiento no
                    deseado dentro de la validación.
                </p></td></tr>
</table></div>
</div>
<div class="sect4">
<div class="titlepage"><div><div><h5 class="title">
<a name="zend.validate.set.iban.basic.false"></a>76.2.16.2.2. Validación IBAN no exhaustiva</h5></div></div></div>
<p>
                A veces es útil solo validar si el valor determinado <span class="emphasis"><em>es</em></span>
                un número <acronym class="acronym">IBAN</acronym> o no. Esto significa que no quiere validarlo
                contra un país definido. Esto se puede hacer usando
                <code class="constant">FALSE</code> como configuración regional.
            </p>
<pre class="programlisting">
$validator = new Zend_Validate_Iban(array('locale' =&gt; false));
// Note: you can also set a FALSE as single parameter

if ($validator-&gt;isValid('AT611904300234573201')) {
    // IBAN appears to be valid
} else {
    // IBAN is not valid
}
</pre>
<p>
                Así que <span class="emphasis"><em>cualquier</em></span> número <acronym class="acronym">IBAN</acronym> será
                válido. Tenga en cuenta que esto no debería hacerse cuando solo acepta cuentas de
                un único país.
            </p>
</div>
<div class="sect4">
<div class="titlepage"><div><div><h5 class="title">
<a name="zend.validate.set.iban.basic.aware"></a>76.2.16.2.3. Validación IBAN sensible a la región</h5></div></div></div>
<p>
                Para validar contra un país definido, solo necesita dar la configuración regional
                deseada. Puede hacer esto mediante la opción <span class="property">locale</span> y también
                posteriormente usando <code class="methodname">setLocale()</code>.
            </p>
<pre class="programlisting">
$validator = new Zend_Validate_Iban(array('locale' =&gt; 'de_AT'));

if ($validator-&gt;isValid('AT611904300234573201')) {
    // IBAN appears to be valid
} else {
    // IBAN is not valid
}
</pre>
<div class="note"><table border="0" summary="Note: Use full qualified locales">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Use configuraciones regionales completamente calificadas</th>
</tr>
<tr><td align="left" valign="top"><p>
                    Debe dar una configuración regional completamente calificada, de lo contrario
                    el país no se podría detectar correctamente porque los idiomas se hablan en
                    múltiples países.
                </p></td></tr>
</table></div>
</div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.identical"></a>76.2.17. Identical</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Identical</code> le permite validar si un valor determinado
        es idéntico a un haystack establecido.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.identical.options"></a>76.2.17.1. Opciones admitidas para Zend_Validate_Identical</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Identical</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">strict</span></em></span>: Define si la validación debe
                    hacerse estricta. El valor predeterminado es <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">token</span></em></span>: Establece el token contra el
                    que se validará la entrada.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.identical.basic"></a>76.2.17.2. Uso básico</h4></div></div></div>
<p>
            Para validar si dos valores son idénticos necesita establecer el valor de origen como
            haystack. Vea el siguiente ejemplo que valida dos cadenas.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Identical('origin');
if ($valid-&gt;isValid($value) {
    return true;
}
</pre>
<p>
            La validación solo devolverá <code class="constant">TRUE</code> cuando ambos valores sean 100%
            idénticos. En nuestro ejemplo, cuando <code class="varname">$value</code> es 'origin'.
        </p>
<p>
            También puede establecer el token deseado posteriormente usando el método
            <code class="methodname">setToken()</code> y <code class="methodname">getToken()</code> para obtener el
            token establecido actualmente.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.identical.types"></a>76.2.17.3. Objetos idénticos</h4></div></div></div>
<p>
            Por supuesto <code class="classname">Zend_Validate_Identical</code> puede validar no solo
            cadenas, sino también cualquier otro tipo de variable como Booleano, Entero, Flotante,
            Array o incluso Objetos. Como ya se ha señalado, Haystack y Value deben ser idénticos.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Identical(123);
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<div class="note"><table border="0" summary="Note: Type comparison">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Comparación de tipos</th>
</tr>
<tr><td align="left" valign="top"><p>
                Debe tener en cuenta que también se usa el tipo de una variable para la validación.
                Esto significa que la cadena <span class="emphasis"><em>'3'</em></span> no es idéntica al entero
                <span class="emphasis"><em>3</em></span>. Cuando quiera una validación no estricta debe
                establecer la opción <span class="property">strict</span>.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.identical.formelements"></a>76.2.17.4. Elementos de formulario</h4></div></div></div>
<p>
            <code class="classname">Zend_Validate_Identical</code> también admite la comparación de
            elementos de formulario. Esto se puede hacer usando el nombre del elemento como
            <span class="property">token</span>. Vea el siguiente ejemplo:
        </p>
<pre class="programlisting">
$form-&gt;addElement('password', 'elementOne');
$form-&gt;addElement('password', 'elementTwo', array(
    'validators' =&gt; array(
        array('identical', false, array('token' =&gt; 'elementOne'))
    )
));
</pre>
<p>
            Usando el nombre del primer elemento como <span class="property">token</span> para el segundo
            elemento, el validador valida si el segundo elemento es igual al primer elemento. En
            caso de que su usuario no introduzca dos valores idénticos, obtendrá un error de
            validación.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.identical.strict"></a>76.2.17.5. Validación estricta</h4></div></div></div>
<p>
            Como se mencionó antes, <code class="classname">Zend_Validate_Identical</code> valida los
            tokens de forma estricta. Puede cambiar este comportamiento usando la opción
            <span class="property">strict</span>. El valor predeterminado para esta propiedad es
            <code class="constant">TRUE</code>.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Identical(array('token' =&gt; 123, 'strict' =&gt; FALSE));
$input = '123';
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<p>
            La diferencia con el ejemplo anterior es que la validación devuelve en este caso
            <code class="constant">TRUE</code>, incluso si compara un valor entero con uno de cadena
            siempre que el contenido sea idéntico pero no el tipo.
        </p>
<p>
            Por conveniencia también puede usar <code class="methodname">setStrict()</code> y
            <code class="methodname">getStrict()</code>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.identical.configuration"></a>76.2.17.6. Configuración</h4></div></div></div>
<p>
            Como todos los demás validadores, <code class="classname">Zend_Validate_Identical</code>
            también admite el uso de configuraciones como parámetro de entrada. Esto significa que
            puede configurar este validador con un objeto <code class="classname">Zend_Config</code>.
        </p>
<p>
            Pero esto añade un caso del que debe ser consciente. Cuando use un array como haystack,
            debería envolverlo dentro de una clave '<span class="property">token</span>' cuando pudiera
            contener un solo elemento.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Identical(array('token' =&gt; 123));
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
<p>
            El ejemplo anterior valida el entero 123. La razón de este caso especial es que puede
            configurar el token que se debe usar dando la clave
            '<span class="property">token</span>'.
        </p>
<p>
            Así que, cuando su haystack contiene un elemento y este elemento se llama
            '<span class="property">token</span>', entonces debe envolverlo como se muestra en el ejemplo
            de abajo.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_Identical(array('token' =&gt; array('token' =&gt; 123)));
if ($valid-&gt;isValid($input)) {
    // input appears to be valid
} else {
    // input is invalid
}
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.in_array"></a>76.2.18. InArray</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_InArray</code> le permite validar si un valor determinado
        está contenido dentro de un array. También es capaz de validar arrays multidimensionales.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.in_array.options"></a>76.2.18.1. Opciones admitidas para Zend_Validate_InArray</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_InArray</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">haystack</span></em></span>: Establece el haystack para
                    la validación.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">recursive</span></em></span>: Define si la validación
                    debe hacerse de forma recursiva. Esta opción tiene como valor predeterminado
                    <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">strict</span></em></span>: Define si la validación
                    debe hacerse estricta. Esta opción tiene como valor predeterminado
                    <code class="constant">FALSE</code>.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.in_array.basic"></a>76.2.18.2. Validación simple de array</h4></div></div></div>
<p>
            La forma más simple es simplemente dar el array contra el que se debe buscar en la
            inicialización:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_InArray(array('key' =&gt; 'value',
                                             'otherkey' =&gt; 'othervalue'));
if ($validator-&gt;isValid('value')) {
    // value found
} else {
    // no value found
}
</pre>
<p>
            Esto se comportará exactamente como el método <code class="methodname">in_array()</code> de
            <acronym class="acronym">PHP</acronym>.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Por defecto esta validación no es estricta ni puede validar arrays
                multidimensionales.
            </p></td></tr>
</table></div>
<p>
            Por supuesto también puede dar el array contra el que validar posteriormente usando el
            método <code class="methodname">setHaystack()</code>. <code class="methodname">getHaystack()</code>
            devuelve el array haystack establecido actualmente.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_InArray();
$validator-&gt;setHaystack(array('key' =&gt; 'value', 'otherkey' =&gt; 'othervalue'));

if ($validator-&gt;isValid('value')) {
    // value found
} else {
    // no value found
}
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.in_array.strict"></a>76.2.18.3. Validación estricta de array</h4></div></div></div>
<p>
            Como se mencionó antes, también puede hacer una validación estricta dentro del array.
            Por defecto no habría diferencia entre el valor entero <span class="emphasis"><em>0</em></span> y la
            cadena <span class="emphasis"><em>"0"</em></span>. Al hacer una validación estricta esta diferencia
            también se validará y solo se aceptan los mismos tipos.
        </p>
<p>
            Una validación estricta también se puede hacer usando dos formas diferentes. En la
            inicialización y mediante un método. En la inicialización debe dar un array con la
            siguiente estructura:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_InArray(
    array(
        'haystack' =&gt; array('key' =&gt; 'value', 'otherkey' =&gt; 'othervalue'),
        'strict'   =&gt; true
    )
);

if ($validator-&gt;isValid('value')) {
    // value found
} else {
    // no value found
}
</pre>
<p>
            La clave <span class="emphasis"><em>haystack</em></span> contiene su array contra el que validar. Y
            al establecer la clave <span class="emphasis"><em>strict</em></span> en <code class="constant">TRUE</code>,
            la validación se hace usando una comprobación estricta de tipos.
        </p>
<p>
            Por supuesto también puede usar el método <code class="methodname">setStrict()</code> para
            cambiar esta configuración posteriormente y <code class="methodname">getStrict()</code> para
            obtener el estado establecido actualmente.
        </p>
<div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que la configuración <span class="emphasis"><em>strict</em></span> es por defecto
                <code class="constant">FALSE</code>.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.in_array.recursive"></a>76.2.18.4. Validación recursiva de array</h4></div></div></div>
<p>
            Además del método <code class="methodname">in_array()</code> de <acronym class="acronym">PHP</acronym>, este
            validador también se puede usar para validar arrays multidimensionales.
        </p>
<p>
            Para validar arrays multidimensionales debe establecer la opción
            <span class="emphasis"><em>recursive</em></span>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_InArray(
    array(
        'haystack' =&gt; array(
            'firstDimension' =&gt; array('key' =&gt; 'value',
                                      'otherkey' =&gt; 'othervalue'),
            'secondDimension' =&gt; array('some' =&gt; 'real',
                                       'different' =&gt; 'key')),
        'recursive' =&gt; true
    )
);

if ($validator-&gt;isValid('value')) {
    // value found
} else {
    // no value found
}
</pre>
<p>
            Su array se validará entonces de forma recursiva para ver si el valor dado está
            contenido. Además podría usar <code class="methodname">setRecursive()</code> para establecer
            esta opción posteriormente y <code class="methodname">getRecursive()</code> para recuperarla.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_InArray(
    array(
        'firstDimension' =&gt; array('key' =&gt; 'value',
                                  'otherkey' =&gt; 'othervalue'),
        'secondDimension' =&gt; array('some' =&gt; 'real',
                                   'different' =&gt; 'key')
    )
);
$validator-&gt;setRecursive(true);

if ($validator-&gt;isValid('value')) {
    // value found
} else {
    // no value found
}
</pre>
<div class="note"><table border="0" summary="Note: Default setting for recursion">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Configuración predeterminada para la recursión</th>
</tr>
<tr><td align="left" valign="top"><p>
                Por defecto la validación recursiva está desactivada.
            </p></td></tr>
</table></div>
<div class="note"><table border="0" summary="Note: Option keys within the haystack">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Claves de opción dentro del haystack</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando use las claves '<span class="property">haystack</span>',
                '<span class="property">strict</span>' o '<span class="property">recursive</span>' dentro de su
                haystack, debe envolver la clave <span class="property">haystack</span>.
            </p></td></tr>
</table></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.int"></a>76.2.19. Int</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Int</code> valida si un valor determinado es un entero.
        También se reconocen y pueden validarse valores enteros localizados.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.int.options"></a>76.2.19.1. Opciones admitidas para Zend_Validate_Int</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Int</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">locale</span></em></span>: Establece la configuración
                    regional que se usará para validar enteros localizados.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.int.basic"></a>76.2.19.2. Validación simple de enteros</h4></div></div></div>
<p>
            La forma más simple de validar un entero es usando la configuración del sistema.
            Cuando no se usa ninguna opción, se usa la configuración regional del entorno para la
            validación:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Int();

$validator-&gt;isValid(1234);   // returns true
$validator-&gt;isValid(1234.5); // returns false
$validator-&gt;isValid('1,234'); // returns true
</pre>
<p>
            En el ejemplo anterior esperábamos que nuestro entorno esté configurado con "en" como
            configuración regional. Como puede ver en el tercer ejemplo, también se reconoce la
            agrupación.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.int.localized"></a>76.2.19.3. Validación de enteros localizada</h4></div></div></div>
<p>
            A menudo es útil poder validar también valores localizados. Los valores enteros a
            menudo se escriben de forma diferente en otros países. Por ejemplo usando inglés puede
            escribir "1234" o "1,234". Ambos son valores enteros pero la agrupación es opcional.
            En alemán, por ejemplo, puede escribir "1.234" y en francés "1 234".
        </p>
<p>
            <code class="classname">Zend_Validate_Int</code> es capaz de validar tales notaciones. Pero
            está limitado a la configuración regional que establezca. Esto significa que no
            simplemente elimina el separador, valida si se usa el separador correcto. Vea el
            siguiente código:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Int(array('locale' =&gt; 'de'));

$validator-&gt;isValid(1234); // returns true
$validator-&gt;isValid("1,234"); // returns false
$validator-&gt;isValid("1.234"); // returns true
</pre>
<p>
            Como puede ver, al usar una configuración regional, su entrada se valida de forma
            localizada. Usando la notación inglesa obtiene un <code class="constant">FALSE</code> cuando
            la configuración regional fuerza una notación diferente.
        </p>
<p>
            La configuración regional también se puede establecer posteriormente usando
            <code class="methodname">setLocale()</code> y recuperar usando
            <code class="methodname">getLocale()</code>.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.ip"></a>76.2.20. Ip</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Ip</code> le permite validar si un valor determinado es una
        dirección IP. Admite el estándar IPv4 y también el estándar IPv6.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.ip.options"></a>76.2.20.1. Opciones admitidas para Zend_Validate_Ip</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Ip</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allowipv4</span></em></span>: Define si el validador
                    permite direcciones IPv4. Esta opción tiene como valor predeterminado
                    <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">allowipv6</span></em></span>: Define si el validador
                    permite direcciones IPv6. Esta opción tiene como valor predeterminado
                    <code class="constant">TRUE</code>.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.ip.basic"></a>76.2.20.2. Uso básico</h4></div></div></div>
<p>
            Un ejemplo básico de uso está a continuación:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Ip();
if ($validator-&gt;isValid($ip)) {
    // ip appears to be valid
} else {
    // ip is invalid; print the reasons
}
</pre>
<div class="note"><table border="0" summary="Note: Invalid IP addresses">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Direcciones IP no válidas</th>
</tr>
<tr><td align="left" valign="top"><p>
                Tenga en cuenta que <code class="classname">Zend_Validate_Ip</code> solo valida
                direcciones IP. Direcciones como '<code class="filename">mydomain.com</code>' o
                '<code class="filename">192.168.50.1/index.html</code>' no son direcciones IP
                válidas. Son o bien nombres de host o <acronym class="acronym">URL</acronym>s válidas pero no
                direcciones IP.
            </p></td></tr>
</table></div>
<div class="note"><table border="0" summary="Note: IPv6 validation">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Validación IPv6</th>
</tr>
<tr><td align="left" valign="top"><p>
                <code class="classname">Zend_Validate_Ip</code> valida direcciones IPv6 con expresiones
                regulares. La razón es que los filtros y métodos del propio
                <acronym class="acronym">PHP</acronym> no siguen la <acronym class="acronym">RFC</acronym>. Muchas otras clases
                disponibles tampoco la siguen.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.ip.singletype"></a>76.2.20.3. Validar solo IPv4 o IPV6</h4></div></div></div>
<p>
            A veces es útil validar solo uno de los formatos admitidos. Por ejemplo cuando su red
            solo admite IPv4. En este caso sería inútil permitir IPv6 dentro de este validador.
        </p>
<p>
            Para limitar <code class="classname">Zend_Validate_Ip</code> a un protocolo puede establecer
            las opciones <span class="property">allowipv4</span> o <span class="property">allowipv6</span> en
            <code class="constant">FALSE</code>. Puede hacer esto bien dando la opción al constructor o
            usando <code class="methodname">setOptions()</code> posteriormente.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Ip(array('allowipv6' =&gt; false);
if ($validator-&gt;isValid($ip)) {
    // ip appears to be valid ipv4 address
} else {
    // ip is no ipv4 address
}
</pre>
<div class="note"><table border="0" summary="Note: Default behaviour">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Comportamiento predeterminado</th>
</tr>
<tr><td align="left" valign="top"><p>
                El comportamiento predeterminado que sigue <code class="classname">Zend_Validate_Ip</code>
                es permitir ambos estándares.
            </p></td></tr>
</table></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.isbn"></a>76.2.21. Isbn</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_Isbn</code> le permite validar un valor
        <acronym class="acronym">ISBN-10</acronym> o <acronym class="acronym">ISBN-13</acronym>.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.isbn.options"></a>76.2.21.1. Opciones admitidas para Zend_Validate_Isbn</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Isbn</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">separator</span></em></span>: Define el separador
                    permitido para el número <acronym class="acronym">ISBN</acronym>. Su valor predeterminado
                    es una cadena vacía.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">type</span></em></span>: Define el tipo permitido de
                    números <acronym class="acronym">ISBN</acronym>. Su valor predeterminado es
                    <code class="constant">Zend_Validate_Isbn::AUTO</code>. Para más detalles eche un vistazo a
                    <a class="link" href="zend.validate.set.phtml#zend.validate.set.isbn.type-explicit" title="76.2.21.3. Setting an explicit ISBN validation type">esta sección</a>.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.isbn.basic"></a>76.2.21.2. Uso básico</h4></div></div></div>
<p>
            Un ejemplo básico de uso está a continuación:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Isbn();
if ($validator-&gt;isValid($isbn)) {
    // isbn is valid
} else {
    // isbn is not valid
}
</pre>
<p>
            Esto validará cualquier <acronym class="acronym">ISBN-10</acronym> e <acronym class="acronym">ISBN-13</acronym>
            sin separador.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.isbn.type-explicit"></a>76.2.21.3. Establecer un tipo de validación ISBN explícito</h4></div></div></div>
<p>
            Un ejemplo de restricción de tipo <acronym class="acronym">ISBN</acronym> está a continuación:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Isbn();
$validator-&gt;setType(Zend_Validate_Isbn::ISBN13);
// OR
$validator = new Zend_Validate_Isbn(array(
    'type' =&gt; Zend_Validate_Isbn::ISBN13,
));

if ($validator-&gt;isValid($isbn)) {
    // this is a valid ISBN-13 value
} else {
    // this is an invalid ISBN-13 value
}
</pre>
<p>
            Lo anterior validará solo valores <acronym class="acronym">ISBN-13</acronym>.
        </p>
<p>
            Los tipos válidos incluyen:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p><code class="constant">Zend_Validate_Isbn::AUTO</code> (predeterminado)</p></li>
<li class="listitem"><p><code class="constant">Zend_Validate_Isbn::ISBN10</code></p></li>
<li class="listitem"><p><code class="constant">Zend_Validate_Isbn::ISBN13</code></p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.isbn.separator"></a>76.2.21.4. Especificar una restricción de separador</h4></div></div></div>
<p>
            Un ejemplo de restricción de separador está a continuación:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Isbn();
$validator-&gt;setSeparator('-');
// OR
$validator = new Zend_Validate_Isbn(array(
    'separator' =&gt; '-',
));

if ($validator-&gt;isValid($isbn)) {
    // this is a valid ISBN with separator
} else {
    // this is an invalid ISBN with separator
}
</pre>
<div class="note"><table border="0" summary="Note: Values without separator">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Valores sin separador</th>
</tr>
<tr><td align="left" valign="top"><p>
                Esto devolverá <code class="constant">FALSE</code> si <code class="varname">$isbn</code> no contiene
                un separador <span class="emphasis"><em>o</em></span> si es un valor
                <acronym class="acronym">ISBN</acronym> no válido.
            </p></td></tr>
</table></div>
<p>
            Los separadores válidos incluyen:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>"" (vacío) (predeterminado)</p></li>
<li class="listitem"><p>"-" (guion)</p></li>
<li class="listitem"><p>" " (espacio)</p></li>
</ul></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.lessthan"></a>76.2.22. LessThan</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_LessThan</code> le permite validar si un valor determinado
        es menor que un valor límite máximo. Es el primo de
        <code class="classname">Zend_Validate_GreaterThan</code>.
    </p>
<div class="note"><table border="0" summary="Note: Zend_Validate_LessThan supports only number validation">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Zend_Validate_LessThan admite solo la validación de números</th>
</tr>
<tr><td align="left" valign="top"><p>
            Debe tenerse en cuenta que <code class="classname">Zend_Validate_LessThan</code> admite solo la
            validación de números. Las cadenas o fechas no se pueden validar con este validador.
        </p></td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.lessthan.options"></a>76.2.22.1. Opciones admitidas para Zend_Validate_LessThan</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_LessThan</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">max</span></em></span>: Establece el valor máximo
                    permitido.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.lessthan.basic"></a>76.2.22.2. Uso básico</h4></div></div></div>
<p>
            Para validar si un valor determinado es menor que un límite definido simplemente use
            el siguiente ejemplo.
        </p>
<pre class="programlisting">
$valid  = new Zend_Validate_LessThan(array('max' =&gt; 10));
$value  = 10;
$return = $valid-&gt;isValid($value);
// returns true
</pre>
<p>
            El ejemplo anterior devuelve <code class="constant">TRUE</code> para todos los valores que sean
            iguales a 10 o menores que 10.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.notempty"></a>76.2.23. NotEmpty</h3></div></div></div>
<p>
        Este validador le permite validar si un valor determinado no está vacío. Esto suele ser
        útil cuando se trabaja con elementos de formulario u otra entrada de usuario, donde puede
        usarlo para asegurarse de que los elementos requeridos tienen valores asociados.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.notempty.options"></a>76.2.23.1. Opciones admitidas para Zend_Validate_NotEmpty</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_NotEmpty</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">type</span></em></span>: Establece el tipo de
                    validación que se procesará. Para más detalles eche un vistazo a <a class="link" href="zend.validate.set.phtml#zend.validate.set.notempty.types" title="76.2.23.3. Changing behaviour for Zend_Validate_NotEmpty">esta sección</a>.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.notempty.default"></a>76.2.23.2. Comportamiento predeterminado para Zend_Validate_NotEmpty</h4></div></div></div>
<p>
            Por defecto, este validador funciona de forma diferente a como esperaría cuando ha
            trabajado con la función <code class="methodname">empty()</code> de <acronym class="acronym">PHP</acronym>.
            En particular, este validador evaluará tanto el entero <span class="emphasis"><em>0</em></span> como
            la cadena '<span class="emphasis"><em>0</em></span>' como vacíos.
        </p>
<pre class="programlisting">
$valid = new Zend_Validate_NotEmpty();
$value  = '';
$result = $valid-&gt;isValid($value);
// returns false
</pre>
<div class="note"><table border="0" summary="Note: Default behaviour differs from PHP">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">El comportamiento predeterminado difiere de PHP</th>
</tr>
<tr><td align="left" valign="top"><p>
                Sin proporcionar configuración, el comportamiento de
                <code class="classname">Zend_Validate_NotEmpty</code> difiere del de
                <acronym class="acronym">PHP</acronym>.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.notempty.types"></a>76.2.23.3. Cambiar el comportamiento de Zend_Validate_NotEmpty</h4></div></div></div>
<p>
            Algunos proyectos tienen opiniones diferentes sobre lo que se considera un valor
            "vacío": una cadena con solo espacios en blanco podría considerarse vacía, o
            <span class="emphasis"><em>0</em></span> puede considerarse no vacío (particularmente para
            secuencias booleanas). Para adaptarse a necesidades diferentes,
            <code class="classname">Zend_Validate_NotEmpty</code> le permite configurar qué tipos deben
            validarse como vacíos y cuáles no.
        </p>
<p>
            Se pueden manejar los siguientes tipos:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em>boolean</em></span>: Devuelve <code class="constant">FALSE</code> cuando el
                    valor booleano es <code class="constant">FALSE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>integer</em></span>: Devuelve <code class="constant">FALSE</code> cuando se da
                    un valor entero <span class="emphasis"><em>0</em></span>. Por defecto esta validación no está
                    activada y devuelve <code class="constant">TRUE</code> para cualquier valor entero.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>float</em></span>: Devuelve <code class="constant">FALSE</code> cuando se da
                    un valor flotante <span class="emphasis"><em>0.0</em></span>. Por defecto esta validación no
                    está activada y devuelve <code class="constant">TRUE</code> para cualquier valor flotante.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>string</em></span>: Devuelve <code class="constant">FALSE</code> cuando se da
                    una cadena vacía <span class="emphasis"><em>''</em></span>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>zero</em></span>: Devuelve <code class="constant">FALSE</code> cuando se da
                    el carácter cero único (<span class="emphasis"><em>'0'</em></span>).
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>empty_array</em></span>: Devuelve <code class="constant">FALSE</code> cuando se
                    da un <span class="emphasis"><em>array</em></span> vacío.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>null</em></span>: Devuelve <code class="constant">FALSE</code> cuando se da un
                    valor <code class="constant">NULL</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>php</em></span>: Devuelve <code class="constant">FALSE</code> por las mismas
                    razones por las que el método <code class="methodname">empty()</code> de
                    <acronym class="acronym">PHP</acronym> devolvería <code class="constant">TRUE</code>.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>space</em></span>: Devuelve <code class="constant">FALSE</code> cuando se da
                    una cadena que contiene solo espacios en blanco.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>object</em></span>: Devuelve <code class="constant">TRUE</code>.
                    Se devolverá <code class="constant">FALSE</code> cuando <span class="property">object</span> no
                    esté permitido pero se dé un objeto.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>object_string</em></span>: Devuelve <code class="constant">FALSE</code> cuando
                    se da un objeto y su método <code class="methodname">__toString()</code> devuelve una
                   cadena vacía.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>object_count</em></span>: Devuelve <code class="constant">FALSE</code> cuando
                    se da un objeto, tiene una interfaz <code class="classname">Countable</code> y su
                    conteo es 0.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em>all</em></span>: Devuelve <code class="constant">FALSE</code> en todos los
                    tipos anteriores.
                </p></li>
</ul></div>
<p>
            Todos los demás valores dados devolverán <code class="constant">TRUE</code> por defecto.
        </p>
<p>
            Hay varias formas de seleccionar cuáles de los tipos anteriores se validan. Puede dar
            uno o varios tipos y sumarlos, puede dar un array, puede usar constantes, o puede dar
            una cadena de texto. Vea los siguientes ejemplos:
        </p>
<pre class="programlisting">
// Returns false on 0
$validator = new Zend_Validate_NotEmpty(Zend_Validate_NotEmpty::INTEGER);

// Returns false on 0 or '0'
$validator = new Zend_Validate_NotEmpty(
    Zend_Validate_NotEmpty::INTEGER + Zend_NotEmpty::ZERO
);

// Returns false on 0 or '0'
$validator = new Zend_Validate_NotEmpty(array(
    Zend_Validate_NotEmpty::INTEGER,
    Zend_Validate_NotEmpty::ZERO
));

// Returns false on 0 or '0'
$validator = new Zend_Validate_NotEmpty(array(
    'integer',
    'zero',
));
</pre>
<p>
            También puede proporcionar una instancia de <code class="classname">Zend_Config</code> para
            establecer los tipos deseados. Para establecer tipos después de la instanciación, use
            el método <code class="methodname">setType()</code>.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.post_code"></a>76.2.24. PostCode</h3></div></div></div>
<p>
        <code class="classname">Zend_Validate_PostCode</code> le permite determinar si un valor determinado
        es un código postal válido. Los códigos postales son específicos de ciudades, y en algunas
        configuraciones regionales se denominan códigos <acronym class="acronym">ZIP</acronym>.
    </p>
<p>
        <code class="classname">Zend_Validate_PostCode</code> conoce más de 160 formatos diferentes de
        código postal. Para seleccionar el formato correcto hay 2 formas. Puede usar una
        configuración regional completamente calificada o puede establecer su propio formato
        manualmente.
    </p>
<p>
        Usar una configuración regional es más conveniente ya que Zend Framework ya conoce el
        formato de código postal apropiado para cada configuración regional; sin embargo, necesita
        usar la configuración regional completamente calificada (una que contenga un
        especificador de región) para hacerlo. Por ejemplo, la configuración regional "de" es una
        configuración regional pero no podría usarse con <code class="classname">Zend_Validate_PostCode</code>
        ya que no incluye la región; "de_AT", sin embargo, sería una configuración regional
        válida, ya que especifica el código de región ("AT", para Austria).
    </p>
<pre class="programlisting">
$validator = new Zend_Validate_PostCode('de_AT');
</pre>
<p>
        Cuando no establece usted mismo una configuración regional, entonces
        <code class="classname">Zend_Validate_PostCode</code> usará la configuración regional de toda la
        aplicación establecida, o, cuando no haya ninguna, la configuración regional devuelta por
        <code class="classname">Zend_Locale</code>.
    </p>
<pre class="programlisting">
// application wide locale within your bootstrap
$locale = new Zend_Locale('de_AT');
Zend_Registry::set('Zend_Locale', $locale);

$validator = new Zend_Validate_PostCode();
</pre>
<p>
        También puede cambiar la configuración regional posteriormente llamando a
        <code class="methodname">setLocale()</code>. Y por supuesto puede obtener la configuración
        regional realmente usada llamando a <code class="methodname">getLocale()</code>.
    </p>
<pre class="programlisting">
$validator = new Zend_Validate_PostCode('de_AT');
$validator-&gt;setLocale('en_GB');
</pre>
<p>
        Los formatos de código postal en sí mismos son simplemente cadenas de expresión regular.
        Cuando el formato de código postal internacional, que se usa al establecer la
        configuración regional, no se ajusta a sus necesidades, entonces también puede establecer
        manualmente un formato llamando a <code class="methodname">setFormat()</code>.
    </p>
<pre class="programlisting">
$validator = new Zend_Validate_PostCode('de_AT');
$validator-&gt;setFormat('AT-\d{5}');
</pre>
<div class="note"><table border="0" summary="Note: Conventions for self defined formats">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Convenciones para formatos definidos por el usuario</th>
</tr>
<tr><td align="left" valign="top">
<p>
            Cuando use formatos definidos por el usuario debería omitir las etiquetas de inicio
            (<span class="command"><strong>'/^'</strong></span>) y fin (<span class="command"><strong>'$/'</strong></span>). Se adjuntan
            automáticamente.
        </p>
<p>
            También debe tener en cuenta que los valores de código postal siempre se validan de
            forma estricta. Esto significa que deben escribirse de forma independiente sin
            caracteres adicionales cuando no estén cubiertos por el formato.
        </p>
</td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.post_code.constructor"></a>76.2.24.1. Opciones del constructor</h4></div></div></div>
<p>
            En su forma más básica, puede pasar bien un objeto <code class="classname">Zend_Locale</code> o
            una cadena que represente una configuración regional completamente calificada al
            constructor de <code class="classname">Zend_Validate_PostCode</code>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_PostCode('de_AT');
$validator = new Zend_Validate_PostCode($locale);
</pre>
<p>
            Además, puede pasar bien un array o un objeto <code class="classname">Zend_Config</code> al
            constructor. Cuando lo haga, debe incluir bien la clave "locale" o "format"; estas se
            usarán para establecer los valores apropiados en el objeto validador.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_PostCode(array(
    'locale' =&gt; 'de_AT',
    'format' =&gt; 'AT_\d+'
));
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.post_code.options"></a>76.2.24.2. Opciones admitidas para Zend_Validate_PostCode</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_PostCode</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">format</span></em></span>: Establece un formato de
                    código postal que se usará para la validación de la entrada.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">locale</span></em></span>: Establece una configuración
                    regional de la que se tomará el código postal.
                </p></li>
</ul></div>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.regex"></a>76.2.25. Regex</h3></div></div></div>
<p>
        Este validador le permite validar si una cadena determinada se ajusta a una expresión
        regular definida.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.regex.options"></a>76.2.25.1. Opciones admitidas para Zend_Validate_Regex</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para <code class="classname">Zend_Validate_Regex</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; "><li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">pattern</span></em></span>: Establece el patrón de
                    expresión regular para este validador.
                </p></li></ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.regex.basic"></a>76.2.25.2. Validación con Zend_Validate_Regex</h4></div></div></div>
<p>
            La validación con expresiones regulares permite tener validaciones complicadas hechas
            sin escribir un validador propio. El uso de expresiones regulares es bastante común y
            simple. Veamos algunos ejemplos:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Regex(array('pattern' =&gt; '/^Test/');

$validator-&gt;isValid("Test"); // returns true
$validator-&gt;isValid("Testing"); // returns true
$validator-&gt;isValid("Pest"); // returns false
</pre>
<p>
            Como puede ver, el patrón debe darse usando la misma sintaxis que
            <code class="methodname">preg_match()</code>. Para más detalles sobre expresiones regulares eche
            un vistazo al <a class="ulink" href="http://php.net/manual/en/reference.pcre.pattern.syntax.php" target="_top">manual de PHP sobre la sintaxis de patrones
                PCRE</a>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.regex.handling"></a>76.2.25.3. Manejo de patrones</h4></div></div></div>
<p>
            También es posible establecer un patrón diferente posteriormente usando
            <code class="methodname">setPattern()</code> y obtener el patrón establecido actualmente con
            <code class="methodname">getPattern()</code>.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_Regex(array('pattern' =&gt; '/^Test/');
$validator-&gt;setPattern('ing$/');

$validator-&gt;isValid("Test"); // returns false
$validator-&gt;isValid("Testing"); // returns true
$validator-&gt;isValid("Pest"); // returns false
</pre>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.sitemap"></a>76.2.26. Validadores Sitemap</h3></div></div></div>
<p>
        Los siguientes validadores se ajustan al <a class="ulink" href="http://www.sitemaps.org/protocol.php" target="_top">protocolo Sitemap <acronym class="acronym">XML</acronym></a>.
    </p>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.sitemap.changefreq"></a>76.2.26.1. Sitemap_Changefreq</h4></div></div></div>
<p>
            Valida si una cadena es válida para usarse como elemento 'changefreq'
            en un documento Sitemap <acronym class="acronym">XML</acronym>. Los valores válidos son: 'always',
            'hourly', 'daily', 'weekly', 'monthly', 'yearly', o 'never'.
        </p>
<p>
            Devuelve <code class="constant">TRUE</code> si y solo si el valor es una cadena
            y es igual a una de las frecuencias especificadas anteriormente.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.sitemap.lastmod"></a>76.2.26.2. Sitemap_Lastmod</h4></div></div></div>
<p>
            Valida si una cadena es válida para usarse como elemento 'lastmod'
            en un documento Sitemap <acronym class="acronym">XML</acronym>. El elemento lastmod debe
            contener una cadena de fecha <acronym class="acronym">W3C</acronym>, descartando opcionalmente
            información sobre la hora.
        </p>
<p>
            Devuelve <code class="constant">TRUE</code> si y solo si el valor dado es
            una cadena y es válido según el protocolo.
        </p>
<div class="example">
<a name="zend.validate.sitemap.lastmod.example"></a><p class="title"><b>Ejemplo 76.1. Validador Sitemap Lastmod</b></p>
<div class="example-contents"><pre class="programlisting">
$validator = new Zend_Validate_Sitemap_Lastmod();

$validator-&gt;isValid('1999-11-11T22:23:52-02:00'); // true
$validator-&gt;isValid('2008-05-12T00:42:52+02:00'); // true
$validator-&gt;isValid('1999-11-11'); // true
$validator-&gt;isValid('2008-05-12'); // true

$validator-&gt;isValid('1999-11-11t22:23:52-02:00'); // false
$validator-&gt;isValid('2008-05-12T00:42:60+02:00'); // false
$validator-&gt;isValid('1999-13-11'); // false
$validator-&gt;isValid('2008-05-32'); // false
$validator-&gt;isValid('yesterday'); // false
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.sitemap.loc"></a>76.2.26.3. Sitemap_Loc</h4></div></div></div>
<p>
            Valida si una cadena es válida para usarse como elemento 'loc'
            en un documento Sitemap <acronym class="acronym">XML</acronym>. Esto usa
            <code class="methodname">Zend_Form::check()</code> internamente. Lea más en
            <a class="link" href="zend.uri.phtml#zend.uri.validation" title="75.1.4. URI Validation">Validación de URI</a>.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.sitemap.priority"></a>76.2.26.4. Sitemap_Priority</h4></div></div></div>
<p>
            Valida si un valor es válido para usarse como elemento 'priority'
            en un documento Sitemap <acronym class="acronym">XML</acronym>. El valor debe ser un
            decimal entre 0.0 y 1.0. Este validador acepta tanto valores
            numéricos como valores de cadena.
        </p>
<div class="example">
<a name="zend.validate.sitemap.priority.example"></a><p class="title"><b>Ejemplo 76.2. Validador Sitemap Priority</b></p>
<div class="example-contents"><pre class="programlisting">
$validator = new Zend_Validate_Sitemap_Priority();

$validator-&gt;isValid('0.1'); // true
$validator-&gt;isValid('0.789'); // true
$validator-&gt;isValid(0.8); // true
$validator-&gt;isValid(1.0); // true

$validator-&gt;isValid('1.1'); // false
$validator-&gt;isValid('-0.4'); // false
$validator-&gt;isValid(1.00001); // false
$validator-&gt;isValid(0xFF); // false
$validator-&gt;isValid('foo'); // false
</pre></div>
</div>
<br class="example-break">
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.sitemap.options"></a>76.2.26.5. Opciones admitidas para Zend_Validate_Sitemap_*</h4></div></div></div>
<p>
            No hay opciones admitidas para ninguno de los validadores Sitemap.
        </p>
</div>
</div>
<div class="sect2">
<div class="titlepage"><div><div><h3 class="title">
<a name="zend.validate.set.stringlength"></a>76.2.27. StringLength</h3></div></div></div>
<p>
        Este validador le permite validar si una cadena determinada está dentro de una longitud
        definida.
    </p>
<div class="note"><table border="0" summary="Note: Zend_Validate_StringLength supports only string validation">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Zend_Validate_StringLength admite solo la validación de cadenas</th>
</tr>
<tr><td align="left" valign="top"><p>
            Debe tenerse en cuenta que <code class="classname">Zend_Validate_StringLength</code> admite
            solo la validación de cadenas. Los enteros, flotantes, fechas u objetos no se pueden
            validar con este validador.
        </p></td></tr>
</table></div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.stringlength.options"></a>76.2.27.1. Opciones admitidas para Zend_Validate_StringLength</h4></div></div></div>
<p>
            Se admiten las siguientes opciones para
            <code class="classname">Zend_Validate_StringLength</code>:
        </p>
<div class="itemizedlist"><ul class="itemizedlist" style="list-style-type: disc; ">
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">encoding</span></em></span>: Establece la codificación
                    <code class="constant">ICONV</code> que se debe usar para esta cadena.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">min</span></em></span>: Establece la longitud mínima
                    permitida para una cadena.
                </p></li>
<li class="listitem"><p>
                    <span class="emphasis"><em><span class="property">max</span></em></span>: Establece la longitud máxima
                    permitida para una cadena.
                </p></li>
</ul></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.stringlength.basic"></a>76.2.27.2. Comportamiento predeterminado para Zend_Validate_StringLength</h4></div></div></div>
<p>
            Por defecto este validador comprueba si un valor está entre <span class="property">min</span> y
            <span class="property">max</span>. Pero para <span class="property">min</span> el valor predeterminado es
            <span class="emphasis"><em>0</em></span> y para <span class="property">max</span> es
            <span class="emphasis"><em><code class="constant">NULL</code></em></span>, lo que significa ilimitado.
        </p>
<p>
            Así que por defecto, sin dar ninguna opción, este validador solo comprueba si la
            entrada es una cadena.
        </p>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.stringlength.maximum"></a>76.2.27.3. Limitar la longitud máxima permitida de una cadena</h4></div></div></div>
<p>
            Para limitar la longitud máxima permitida de una cadena necesita establecer la
            propiedad <span class="property">max</span>. Acepta un valor entero como entrada.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_StringLength(array('max' =&gt; 6));

$validator-&gt;isValid("Test"); // returns true
$validator-&gt;isValid("Testing"); // returns false
</pre>
<p>
            También puede establecer la longitud máxima permitida posteriormente usando el método
            <code class="methodname">setMax()</code>. Y <code class="methodname">getMax()</code> para
            recuperar el límite máximo actual.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_StringLength();
$validator-&gt;setMax(6);

$validator-&gt;isValid("Test"); // returns true
$validator-&gt;isValid("Testing"); // returns false
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.stringlength.minimum"></a>76.2.27.4. Limitar la longitud mínima requerida de una cadena</h4></div></div></div>
<p>
            Para limitar la longitud mínima requerida de una cadena necesita establecer la
            propiedad <span class="property">min</span>. También acepta un valor entero como entrada.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_StringLength(array('min' =&gt; 5));

$validator-&gt;isValid("Test"); // returns false
$validator-&gt;isValid("Testing"); // returns true
</pre>
<p>
            También puede establecer la longitud mínima solicitada posteriormente usando el método
            <code class="methodname">setMin()</code>. Y <code class="methodname">getMin()</code> para
            recuperar el límite mínimo actual.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_StringLength();
$validator-&gt;setMin(5);

$validator-&gt;isValid("Test"); // returns false
$validator-&gt;isValid("Testing"); // returns true
</pre>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.stringlength.both"></a>76.2.27.5. Limitar una cadena por ambos lados</h4></div></div></div>
<p>
            A veces se requiere obtener una cadena que tenga una longitud máxima definida pero que
            también tenga una longitud mínima. Por ejemplo cuando tiene un cuadro de texto donde un
            usuario puede introducir su nombre, entonces puede querer limitar el nombre a un
            máximo de 30 caracteres pero quiere asegurarse de que introdujo su nombre. Así que
            limita la longitud mínima requerida a 3 caracteres. Vea el siguiente ejemplo:
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_StringLength(array('min' =&gt; 3, 'max' =&gt; 30));

$validator-&gt;isValid("."); // returns false
$validator-&gt;isValid("Test"); // returns true
$validator-&gt;isValid("Testing"); // returns true
</pre>
<div class="note"><table border="0" summary="Note: Setting a lower maximum border than the minimum border">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Establecer un límite máximo menor que el límite mínimo</th>
</tr>
<tr><td align="left" valign="top"><p>
                Cuando intenta establecer un valor máximo menor que el valor mínimo actual, o un
                valor mínimo mayor que el valor máximo actual, se lanzará una excepción.
            </p></td></tr>
</table></div>
</div>
<div class="sect3">
<div class="titlepage"><div><div><h4 class="title">
<a name="zend.validate.set.stringlength.encoding"></a>76.2.27.6. Codificación de valores</h4></div></div></div>
<p>
            Las cadenas siempre usan una codificación. Incluso cuando no establece la codificación
            explícitamente, <acronym class="acronym">PHP</acronym> usa una. Cuando su aplicación usa una
            codificación diferente a la del propio <acronym class="acronym">PHP</acronym>, entonces debería
            establecer una codificación usted mismo.
        </p>
<p>
            Puede establecer su propia codificación en la inicialización con la opción
            <span class="property">encoding</span>, o usando el método <code class="methodname">setEncoding()</code>.
            Supongamos que su instalación usa <acronym class="acronym">ISO</acronym> y su aplicación está
            configurada en <acronym class="acronym">ISO</acronym>. En este caso verá el siguiente
            comportamiento.
        </p>
<pre class="programlisting">
$validator = new Zend_Validate_StringLength(
    array('min' =&gt; 6)
);
$validator-&gt;isValid("Ärger"); // returns false

$validator-&gt;setEncoding("UTF-8");
$validator-&gt;isValid("Ärger"); // returns true

$validator2 = new Zend_Validate_StringLength(
    array('min' =&gt; 6, 'encoding' =&gt; 'UTF-8')
);
$validator2-&gt;isValid("Ärger"); // returns true
</pre>
<p>
            Así que cuando su instalación y su aplicación usan codificaciones diferentes, siempre
            debería establecer una codificación usted mismo.
        </p>
</div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.validate.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="zend.validate.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.validate.validator_chains.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">Capítulo 76. Zend_Validate </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 76.3. Cadenas de validadores</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
