<?php $title = 'Capítulo 17. Zend_Cache'; include __DIR__ . '/_header.phtml'; ?>
<div class="navheader"><table width="100%" summary="Navigation header">
<tr><th colspan="3" align="center">Capítulo 17. Zend_Cache</th></tr>
<tr>
<td width="20%" align="left">
<a accesskey="p" href="zend.barcode.renderers.phtml">Anterior</a> </td>
<th width="60%" align="center">Parte III. Referencia de Zend Framework</th>
<td width="20%" align="right"> <a accesskey="n" href="zend.cache.theory.phtml">Siguiente</a>
</td>
</tr>
</table></div>
<div class="chapter">
<div class="titlepage"><div><div><h2 class="title">
<a name="zend.cache"></a>Capítulo 17. Zend_Cache</h2></div></div></div>
<div class="toc">
<p><b>Tabla de contenidos</b></p>
<dl class="toc">
<dt><span class="sect1"><a href="zend.cache.phtml#zend.cache.introduction">17.1. Introducción</a></span></dt>
<dt><span class="sect1"><a href="zend.cache.theory.phtml">17.2. Teoría de la caché</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.cache.theory.phtml#zend.cache.factory">17.2.1. El método de fábrica de Zend_Cache</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.theory.phtml#zend.cache.tags">17.2.2. Etiquetado de registros</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.theory.phtml#zend.cache.clean">17.2.3. Limpieza de la caché</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.cache.frontends.phtml">17.3. Frontends de Zend_Cache</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.cache.frontends.phtml#zend.cache.frontends.core">17.3.1. Zend_Cache_Core</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.core.introduction">17.3.1.1. Introducción</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.core.options">17.3.1.2. Opciones disponibles</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.core.examples">17.3.1.3. Ejemplos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.cache.frontends.phtml#zend.cache.frontends.output">17.3.2. Zend_Cache_Frontend_Output</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.output.introduction">17.3.2.1. Introducción</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.output.options">17.3.2.2. Opciones disponibles</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.output.examples">17.3.2.3. Ejemplos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.cache.frontends.phtml#zend.cache.frontends.function">17.3.3. Zend_Cache_Frontend_Function</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.function.introduction">17.3.3.1. Introducción</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.function.options">17.3.3.2. Opciones disponibles</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.function.examples">17.3.3.3. Ejemplos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.cache.frontends.phtml#zend.cache.frontends.class">17.3.4. Zend_Cache_Frontend_Class</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.class.introduction">17.3.4.1. Introducción</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.class.options">17.3.4.2. Opciones disponibles</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.class.examples">17.3.4.3. Ejemplos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.cache.frontends.phtml#zend.cache.frontends.file">17.3.5. Zend_Cache_Frontend_File</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.file.introduction">17.3.5.1. Introducción</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.file.options">17.3.5.2. Opciones disponibles</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.file.examples">17.3.5.3. Ejemplos</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.cache.frontends.phtml#zend.cache.frontends.page">17.3.6. Zend_Cache_Frontend_Page</a></span></dt>
<dd><dl>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.page.introduction">17.3.6.1. Introducción</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.page.options">17.3.6.2. Opciones disponibles</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.page.examples">17.3.6.3. Ejemplos</a></span></dt>
<dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.page.cancel">17.3.6.4. El método específico Cancel</a></span></dt>
</dl></dd>
<dt><span class="sect2"><a href="zend.cache.frontends.phtml#zend.cache.frontends.capture">17.3.7. Zend_Cache_Frontend_Capture</a></span></dt>
<dd><dl><dt><span class="sect3"><a href="zend.cache.frontends.phtml#zend.cache.frontends.capture.introduction">17.3.7.1. Introducción</a></span></dt></dl></dd>
</dl></dd>
<dt><span class="sect1"><a href="zend.cache.backends.phtml">17.4. Backends de Zend_Cache</a></span></dt>
<dd><dl>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.file">17.4.1. Zend_Cache_Backend_File</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.sqlite">17.4.2. Zend_Cache_Backend_Sqlite</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.memcached">17.4.3. Zend_Cache_Backend_Memcached</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.libmemcached">17.4.4. Zend_Cache_Backend_Libmemcached</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.apc">17.4.5. Zend_Cache_Backend_Apc</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.xcache">17.4.6. Zend_Cache_Backend_Xcache</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.platform">17.4.7. Zend_Cache_Backend_ZendPlatform</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.twolevels">17.4.8. Zend_Cache_Backend_TwoLevels</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.zendserver">17.4.9. Zend_Cache_Backend_ZendServer_Disk y Zend_Cache_Backend_ZendServer_ShMem</a></span></dt>
<dt><span class="sect2"><a href="zend.cache.backends.phtml#zend.cache.backends.static">17.4.10. Zend_Cache_Backend_Static</a></span></dt>
</dl></dd>
<dt><span class="sect1"><a href="zend.cache.cache.manager.phtml">17.5. El gestor de caché</a></span></dt>
</dl>
</div>
<div class="sect1">
<div class="titlepage"><div><div><h2 class="title" style="clear: both">
<a name="zend.cache.introduction"></a>17.1. Introducción</h2></div></div></div>
<p>
        <code class="classname">Zend_Cache</code> proporciona una forma genérica de almacenar en caché cualquier dato.
    </p>
<p>
      El almacenamiento en caché en Zend Framework es gestionado por frontends mientras que los registros de la caché se
      almacenan a través de adaptadores backend (<span class="emphasis"><em>File</em></span>, <span class="emphasis"><em>Sqlite</em></span>,
      <span class="emphasis"><em>Memcache</em></span>...) a través de un sistema flexible de IDs y etiquetas. Usando estos, es
      fácil eliminar tipos específicos de registros posteriormente (por ejemplo: "eliminar todos los registros de la caché
      marcados con una etiqueta dada").
    </p>
<p>
        El núcleo del módulo (<code class="classname">Zend_Cache_Core</code>) es genérico, flexible y
        configurable. Aun así, para sus necesidades específicas existen frontends de caché que extienden
        <code class="classname">Zend_Cache_Core</code> por conveniencia: <span class="emphasis"><em>Output</em></span>,
        <span class="emphasis"><em>File</em></span>, <span class="emphasis"><em>Function</em></span> y <span class="emphasis"><em>Class</em></span>.
    </p>
<div class="example">
<a name="zend.cache.introduction.example-1"></a><p class="title"><b>Ejemplo 17.1. Obtener un frontend con Zend_Cache::factory()</b></p>
<div class="example-contents">
<p>
            <code class="methodname">Zend_Cache::factory()</code> instancia los objetos correctos y los
            enlaza entre sí. En este primer ejemplo, usaremos el frontend <span class="emphasis"><em>Core</em></span>
            junto con el backend <span class="emphasis"><em>File</em></span>.
        </p>
<pre class="programlisting">
$frontendOptions = array(
   'lifetime' =&gt; 7200, // cache lifetime of 2 hours
   'automatic_serialization' =&gt; true
);

$backendOptions = array(
    'cache_dir' =&gt; './tmp/' // Directory where to put the cache files
);

// getting a Zend_Cache_Core object
$cache = Zend_Cache::factory('Core',
                             'File',
                             $frontendOptions,
                             $backendOptions);
</pre>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note: Frontends and Backends Consisting of Multiple Words">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Frontends y backends compuestos por varias palabras</th>
</tr>
<tr><td align="left" valign="top"><p>
            Algunos frontends y backends se nombran usando varias palabras, como
            'ZendPlatform'. Al especificarlos en la fábrica, sepárelos
            usando un separador de palabras, como un espacio (' '), un guion
            ('-'), o un punto ('.').
        </p></td></tr>
</table></div>
<div class="example">
<a name="zend.cache.introduction.example-2"></a><p class="title"><b>Ejemplo 17.2. Almacenar en caché el resultado de una consulta a la base de datos</b></p>
<div class="example-contents">
<p>
            Ahora que tenemos un frontend, podemos almacenar en caché cualquier tipo de dato (activamos la serialización).
            Por ejemplo, podemos almacenar en caché el resultado de una consulta a la base de datos muy costosa. Después de que se
            almacena en caché, ni siquiera es necesario conectarse a la base de datos; los registros se obtienen de la caché
            y se deserializan.
        </p>
<pre class="programlisting">
// $cache initialized in previous example

// see if a cache already exists:
if( ($result = $cache-&gt;load('myresult')) === false ) {

    // cache miss; connect to the database

    $db = Zend_Db::factory( [...] );

    $result = $db-&gt;fetchAll('SELECT * FROM huge_table');

    $cache-&gt;save($result, 'myresult');

} else {

    // cache hit! shout so that we know
    echo "This one is from cache!\n\n";

}

print_r($result);
</pre>
</div>
</div>
<br class="example-break"><div class="example">
<a name="zend.cache.introduction.example-3"></a><p class="title"><b>Ejemplo 17.3. Almacenar en caché la salida con el frontend Output de Zend_Cache</b></p>
<div class="example-contents">
<p>
            'Marcamos' las secciones en las que queremos almacenar en caché la salida añadiendo alguna lógica condicional,
            encapsulando la sección entre los métodos <code class="methodname">start()</code> y
            <code class="methodname">end()</code> (esto se parece al primer ejemplo y es la estrategia
            central para el almacenamiento en caché).
        </p>
<p>
            Dentro, escriba sus datos como de costumbre - toda la salida se almacenará en caché cuando la ejecución llegue al
            método <code class="methodname">end()</code>. En la siguiente ejecución, toda la sección se
            omitirá en favor de obtener los datos de la caché (siempre que el registro de caché sea válido).
        </p>
<pre class="programlisting">
$frontendOptions = array(
   'lifetime' =&gt; 30,                   // cache lifetime of 30 seconds
   'automatic_serialization' =&gt; false  // this is the default anyways
);

$backendOptions = array('cache_dir' =&gt; './tmp/');

$cache = Zend_Cache::factory('Output',
                             'File',
                             $frontendOptions,
                             $backendOptions);

// we pass a unique identifier to the start() method
if(!$cache-&gt;start('mypage')) {
    // output as usual:

    echo 'Hello world! ';
    echo 'This is cached ('.time().') ';

    $cache-&gt;end(); // the output is saved and sent to the browser
}

echo 'This is never cached ('.time().').';
</pre>
<p>
            Observe que mostramos el resultado de <code class="methodname">time()</code> dos veces; esto es
            algo dinámico con fines demostrativos. Intente ejecutar esto y luego actualizar la página
            varias veces; notará que el primer número no cambia mientras que el segundo cambia
            a medida que pasa el tiempo. Esto se debe a que el primer número se generó en la sección en caché y se
            guardó junto con otra salida. Después de medio minuto (hemos configurado el tiempo de vida en 30 segundos), los
            números deberían coincidir de nuevo porque el registro de caché ha expirado -- solo para volver a almacenarse en caché.
            Debería probar esto en su navegador o consola.
        </p>
</div>
</div>
<br class="example-break"><div class="note"><table border="0" summary="Note">
<tr>
<td rowspan="2" align="center" valign="top" width="25"><img alt="[Note]" src="images/note.png"></td>
<th align="left">Nota</th>
</tr>
<tr><td align="left" valign="top"><p>
            Al usar <code class="classname">Zend_Cache</code>, preste atención al importante identificador de
            caché (pasado a <code class="methodname">save()</code> y
            <code class="methodname">start()</code>). Debe ser único para cada recurso que almacene en caché,
            de lo contrario los registros de caché no relacionados podrían anularse mutuamente o, incluso peor, mostrarse en
            lugar de otro.
        </p></td></tr>
</table></div>
</div>
</div>
<div class="navfooter"><table width="100%" summary="Navigation footer">
<tr>
<td width="40%" align="left">
<a accesskey="p" href="zend.barcode.renderers.phtml">Anterior</a> </td>
<td width="20%" align="center"><a accesskey="u" href="reference.phtml">Subir</a></td>
<td width="40%" align="right"> <a accesskey="n" href="zend.cache.theory.phtml">Siguiente</a>
</td>
</tr>
<tr>
<td width="40%" align="left" valign="top">16.4. Renderizadores de Zend_Barcode </td>
<td width="20%" align="center"><a accesskey="h" href="index.phtml">Inicio</a></td>
<td width="40%" align="right" valign="top"> 17.2. Teoría de la caché</td>
</tr>
</table></div>
<div class="revinfo"></div>
<?php include __DIR__ . '/_footer.phtml'; ?>
